### ISSUE TITLE
Strange shortcut to start Open-shell.

### ISSUE THREAD

**Issue by DmitrijOkeanij** [Open-Shell/Open-Shell-Menu#100]
I noticed that there is no shortcut to start Open-Shell after installing?? But it automatic starts after I enter Settings... I think that there must to be separete shortcut.

And 2 bug. Link in setting go to old site of classic-shell.

And thanks to developers of shis fork! It's great that this program Alive!

**Comment by bfoos** [comment]
@Dmitrij-Polyanin After installation, you start Open-Shell by simply pressing the Windows key.
