### ISSUE TITLE
randomly signs me out

### ISSUE THREAD

**Issue by mr2meowsYT** [Open-Shell/Open-Shell-Menu#1003]
thois program is malware after i installed it it will keep signing me out randomly all day long

**Comment by Ibuprophen** [comment]
Can you please provide evidence as to how you came to this conclusion? 

I've personally never heard of this behavior myself.

Maybe @ge0rdi can provide some insight as to his experience in this type of behavior? 

~Ibuprophen

**Comment by IMNdi** [comment]
I remember there was an update of Chromium around start pf April and both Edge and Chrome both signed me out of everything. Possible unrelated issue?

**Comment by mr2meowsYT** [comment]
gonna close this issue because I no longer use windows
