### ISSUE TITLE
There are some Suspicious in Open-Shell please look at the Source code and fix/remove the Suspicious lines of code from the Software Please

### ISSUE THREAD

**Issue by WorldRuler42** [Open-Shell/Open-Shell-Menu#1006]
There's some Suspicious lines of code in here I have Proof here please take a look at these 2 links https://analyze.intezer.com/analyses/76222d1d-beed-418b-841e-ea0ac412baeb and this one too https://www.virustotal.com/gui/file/2f637b8a5666f4537fbb4e1502becde2469e4888008a79060549b26ade5068dd so if you could fix this it would be good if you did so we can all use the software safely I'm asking this Because I really want to use the software but I can't. Hopefully this issue can be fix I know this might not be a bug report per say but I'm reporting that it has Suspicious and Malware code so please help to make it more of a secure software so more people can use it safely here you can also see this if you don't believe me https://analyze.intezer.com/analyses/71a26026-510d-456a-a307-e50e9b3bf17b/sub/61c1fe26-e531-4478-a3d0-ba43092535e2/code-reuse https://analyze.intezer.com/analyses/71a26026-510d-456a-a307-e50e9b3bf17b/sub/61c1fe26-e531-4478-a3d0-ba43092535e2/string-reuse https://analyze.intezer.com/analyses/71a26026-510d-456a-a307-e50e9b3bf17b/sub/61c1fe26-e531-4478-a3d0-ba43092535e2/ttps so I would like to ask you to please look at the Source code and the Links I sent you to verify Open-Shell's Source Code I'm just asking if you could remove those 6 lines of code from the software I'm begging you to so people stay safe while using it. Here I even sent you guys a screenshot If that wasn't enough there are Links I sent you during the bug/virus report. This is where I have an issue with the software if you could please have someone or a couple of people to look over the source code and fix it/remove those 6 lines of code we'll be fine.
https://www.virustotal.com/gui/file/2f637b8a5666f4537fbb4e1502becde2469e4888008a79060549b26ade5068dd/details
https://www.virustotal.com/gui/file/2f637b8a5666f4537fbb4e1502becde2469e4888008a79060549b26ade5068dd/relations
https://www.virustotal.com/gui/file/2f637b8a5666f4537fbb4e1502becde2469e4888008a79060549b26ade5068dd/behavior
![Screenshot 2022-04-12 222658](https://user-images.githubusercontent.com/33233996/163087984-4ab56472-861f-4906-8faf-d1291dddc3d0.png)

**Comment by WorldRuler42** [comment]
Can You please show me the sorce code then?

**Comment by WorldRuler42** [comment]
How do you know that for sure?

**Comment by WorldRuler42** [comment]
Then why dud it pick up and says it has 6 then?

**Comment by Ibuprophen** [comment]
That website may provide some insight into potential viruses, but it's also known for false positive results. 

This specific website has always been a mute discussion. My Antivirus/Anti-Malware software (as with many other users for this software) has not failed me for years and has never given me any red flags for this software. 

Sorry, but this Discussion is Closed... 💯 

~Ibuprophen
