### ISSUE TITLE
I/E vs Edge Favorites

### ISSUE THREAD

**Issue by ghost** [Open-Shell/Open-Shell-Menu#1014]
I am using Open Shell Menu ver. 4.4.160 on Windows 10 Pro. The Favorites button on the Windows Start Menu points to the Internet Explorer bookmarks. Since I use Microsoft Edge and I/E is soon to be retired, how can I make the Favorites button point to the Edge bookmarks instead of the Internet Explorer's favorites? This is very frustrating, and I would be grateful for any help.
I apologize if this has been addressed on your website, but I could not find anything. 
Open Shell Menu is otherwise GREAT!

Tom Stewart

**Comment by ge0rdi** [comment]
It seems that modern Edge (Chromium-based) doesn't store favorites in standard folder anymore.
It uses its own format that is accessible from within Edge only.
