### ISSUE TITLE
windows "settings" app

### ISSUE THREAD

**Issue by rnmerchant** [Open-Shell/Open-Shell-Menu#1018]
**Describe the bug**
I have found that the choice of "settings" (i.e. the newish Win10/11/? replacement for the Control Panel does not open from OpenShell.   However it opens properly for me from the Windows Start Menu.

**To Reproduce**
1. OpenShell menu
2. Click on 'Settings" (in the right panel)
3. observe for Win10 Settings window to open.  It doesn't for me.  No error message or anything.  Nothing happening on Task Manager.

**Expected behavior**
Settings menu should open

**Version:**
 - Open-Shell 4.4.160
 - OS: Win10 21H2 build 19044.1706  All current (April 10 2022) updates applied.

**Comment by Reggie521** [comment]
Same issue here. It was working with version 4.4.160 but after updating to 4.4.170 the link no longer opens the Settings app.
