### ISSUE TITLE
Page padding not working after run.

### ISSUE THREAD

**Issue by DmitrijOkeanij** [Open-Shell/Open-Shell-Menu#102]
I tried to make some white space after Run, before Shutdown. But how? Now it is not working.

![2018-10-23_16-36-56](https://user-images.githubusercontent.com/10674646/47364457-05058180-d6e2-11e8-97d5-8ad5e01e9cb0.png)
![2018-10-23_16-37-26](https://user-images.githubusercontent.com/10674646/47364456-05058180-d6e2-11e8-97c4-c798b4363112.png)

**Comment by Dmitrij-Polyanin** [comment]
This is in Smoke Glass Skin.
Tries Metro - works fine.

**Comment by CTVCAM8** [comment]
That space shrinks and expands depending on a lot of factors.

A quick fix to force more blank space above the Shutdown text when using Classic style:

Open 'Customize Start Menu' tab, drag over one or more 'Custom' entry command and drop 
in between separator/column padding.
If separator disappears (Bug?), drag and drop extra separator.


![force blank area](https://user-images.githubusercontent.com/44127216/47428657-cc4cc300-d748-11e8-9f13-d3ea3fa8002e.png)
