### ISSUE TITLE
Updater don't downlaod anything

### ISSUE THREAD

**Issue by Niklas20114552** [Open-Shell/Open-Shell-Menu#1020]
**Describe the bug**
(Sorry for my English, i live in Germany)
The Bug is, that the Open-Shell Updater download a 1KB File, that i can open with Notepad.
The Text is: 
{"message":"Artifacts download limit (1024 MB/day) exceeded."}

**To Reproduce**
1. Open the Open-Shell Update
2. Click on 'Download'

**Expected behavior**
The updater should download the latest Open-Shell version

**Screenshots**
![image](https://user-images.githubusercontent.com/83753407/168309227-21490e75-f54c-44d4-9223-bdbf42e22a6f.png)
![image](https://user-images.githubusercontent.com/83753407/168309336-eb6bf9b8-8c53-4410-93e9-b5c9eca447b5.png)

**Version:**
 - Open-Shell Version: I don't know, i think it was 4.4.160
 - OS: [e.g. Windows 10 21H2]

**Comment by blackcrack** [comment]
hey Du deutscher.. jeh mehr Du Dich bei Engländer entschuldigst, jeh mehr sehen die sich im recht..
nur weil manche meinen Ihren "ich bin ja so geil Arsch" breit treten zu müssen, kausiert das mit dem Entschuldigung.. bullschit, wenn Du dich entschuldigst und verneigst um so besser kann man deinen Kopf ab hacken.. LASS DAS !!
Du kannst Dich zumindest mitteilen, das iss doch schon etwas.. ich hab die gleiche Scheisse durch gemacht.. und habs am ende geblickt, daß man das nicht sollte..

Warum seh ich die 1.7 und Du hast nur die 1.6 installiert ?

erstens, es iss die version 1.70 schon unterwegs, wenn de' nach den nightlys schaust auf der GH -hauptseite Readme.md
runterscrollen , da Steht nightlys, das iss dahin verlinkt :  
https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts
und wenn Du keine Artifacts dann klick auf den turkiesen Button, dann solltest Du zwei Dateien sehen..
Isses in deutsch ? Du kannst DLL's runterladen, dann auf deutsche Übersetzung und dann sollte das in Deutsch angezeigt werden.

Update, derzeit iss OpenShell noch im Umbau, damit es vollens open source iss, das ist noch nicht abgeschlossen,
Ich kann nich Coden, aber ich weis was es alles gibt und geht und kann scripten im Linux und im Win.. 
ansonsten wär der "nicht open source" mist schon lang draußen und es könnte weitergehen.. 
Kennst Du jemanden der C/c++ kann, dann hau Ihn an..
hier iss derzeit nur einer der hier mithelfen kann, das iss ge0rdi , moment der Hauptprogrammierer und Ibuprophen 
der aber auch nur rudimentär coden kann. Ich hab beim Founder , als er das ganze runter fahren wollte, nachgefragt ob er das nich eventuell das ganze frei geben würde, darauf hin hat er das dann veröffentlicht und unter open-source gestellt mit der Auflage, den ganzen source code um zu bauen, als Open Source.. .. Ich glaub, die Hälfte iss schon gemacht, irgend wo gibts so ein Balken wo man sieht wie viel Prozent schon gemacht iss.. also, wenn Du Programmierer kennst die hier mit basteln können, sprich mit denen.

Ansonsten, Danke für das Issue melden.. 

liebe grüße
Blacky

blackysgate.de und .net

**Comment by mariagil1975** [comment]
I get the same message: {"message":"Artifacts download limit (1024 MB/day) exceeded."}

**Comment by schmurtzm** [comment]
Same here, it's not possible to download the artifacts !

**Comment by blackcrack** [comment]
help with at the programming and it works, call frends who be in able to programming ad speak about Open Shell and look for programmers for this community project, any can help, so generate help, then works also..

best

**Comment by ge0rdi** [comment]
This should be fixed already.
