### ISSUE TITLE
Version 4.4.170 Update - File not Opening

### ISSUE THREAD

**Issue by K-no-Uta** [Open-Shell/Open-Shell-Menu#1021]
The updater suggested an update to version 4.4.170. I downloaded it. It says, sth. like "the app cannot be executed on this PC, contact the provider about another version." (German PC, this is a rough translation)

I right clicked on the file and chose to execute as administrator. It says that the file cannot be found. 

I tried to use compatibility mode and the problem fixer thing that adjust the option for you and nothing worked. So my best guess is there maybe a problem with the file itself? So I came here.

**Expected behavior**
Installation of update as usual

**Version:**
 - Open-Shell: 4.4.1170
 - OS: e.g. Windows 11 Home 21H2

**Comment by Ibuprophen** [comment]
I believe that the Update feature is still a work in progress. 

You can locate all the Official Releases (& Pre-Releases) on the following link. 

https://github.com/Open-Shell/Open-Shell-Menu/releases

Thank you for taking the time to let us know. 👍 

~Ibuprophen

**Comment by K-no-Uta** [comment]
Thanks a lot. Due to your input I found the problem, I think. The checkbox that made the updater search for nightly builds was chec. I unchecked it and it worked. Although I cannot tell if it's just because the issue was fixed while I was away.

Either way this issue is resolved.
