### ISSUE TITLE
No taskbar clock, No snipping tool

### ISSUE THREAD

**Issue by 1phatnoob** [Open-Shell/Open-Shell-Menu#1026]
Replaced classic shell with Open shell on windows 11.

Now there is no taskbar clock.

I am also unable to use the snipping tool

In settings both 'apps' are installed and should be visible.

Have tried repair, reset etc, but nothing works.

Can you help?

**Comment by 1phatnoob** [comment]
![image](https://user-images.githubusercontent.com/106278319/170362829-c6192207-99fb-43f3-b7ed-6ceefbf32379.png)

**Comment by blackcrack** [comment]
it's a Fiture of Win11 ;)

take Windows 11 Patcher :)
or take the bar from us frend's, Retrobar:

https://github.com/dremin/RetroBar

**Comment by namiltd** [comment]
To enable missing icons just execute: `explorer shell:::{05d7b0f4-2121-4eff-bf6b-ed3f69b894d9}`

**Comment by 1phatnoob** [comment]
i've restored icons and it allows me to drop in liked i used to before on windows 10.
So the taskbar issue is resolved.

But I cannot use windows snip tool.
I still have no taskbar clock!

![image](https://user-images.githubusercontent.com/106278319/170885643-3452f485-b2ff-4deb-b5dc-210bcd024202.png)

**Comment by namiltd** [comment]
he settings that I have indicated are the switches for clock visibility, volume, etc.

**Comment by 1phatnoob** [comment]
> The settings that I have indicated are the switches for clock visibility, volume, etc. These are old settings and have more options than the standard ones you see in Windows 11.

Hi, i'd been here before, but what I hadnt clicked was the turn system icons on or off.

Got my clock back thankyou.

Any ideas how to get my windows snipping tool working again?

**Comment by namiltd** [comment]
Windows key + Shift + S

**Comment by ge0rdi** [comment]
I'm not sure any of these issues is `Open-Shell` related.

**Comment by VsevolodGolovanov** [comment]
For me the snipping tool stopped working when I did the registry tweak to bring back older taskbar (don't think I had OpenShell installed). I ended up reverting the tweak and using StartAllBack instead, which allows customizing the taskbar too. In case that helps somebody...
This was the tweak, IIRC:

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell\Update\Packages]
"UndockingDisabled"=dword:00000001

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Search]
"SearchboxTaskbarMode"=dword:00000000

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"ShowTaskViewButton"=dword:00000000
"ShowCortanaButton"=dword:00000000

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer]
"NoTaskGrouping"=dword:00000001
```
