### ISSUE TITLE
Perjodic update

### ISSUE THREAD

**Issue by blackcrack** [Open-Shell/Open-Shell-Menu#1027]
@ge0rdi , @Ibuprophen 
Please make the 4.4.170 to a actual Release 
before delete :
https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts

best

p.s.: release is not only a update of fitures, it's also a advertising ..

**Comment by ge0rdi** [comment]
Hello.
Release created.
Thank you.
