### ISSUE TITLE
Installation Issue - Icons Moving on Dal Monitor

### ISSUE THREAD

**Issue by CieronKnight** [Open-Shell/Open-Shell-Menu#1029]
I upgraded today from 4.4.160  to 4.4.170 but after restarting my PC, all the desktop icons moved to the secondary monitor. I tried uninstalling and reverting to 4.4.160 but this did not resolve the issue. The only way I could resolve it was through System Restore.

**Comment by muhachris297** [comment]
This sounds like a bug that may need to be worked out in the program.
