### ISSUE TITLE
Using /qn (for silent installation) with 4.4.170 causes "normal" installation methods (CMD, WinGet) to fail

### ISSUE THREAD

**Issue by dw2546** [Open-Shell/Open-Shell-Menu#1030]
**Describe the bug** / **To Reproduce** / **Expected behavior**

All of these are merged in this section.

Command prompt with /qn option returns 0 for %errorlevel% but actually never installs:

	OpenShellSetup_4_4_170.exe /qn ADDLOCAL=StartMenu,Update&&echo Result (errorlevel): %errorlevel%
	Result (errorlevel): 0

Winget installation (stock, no overrides) fails with error code 1603:

	winget install Open-Shell.Open-Shell-Menu

	Summary output (fails with error code 1603):
	2022-05-28 10:15:19.542 [CLI ] Installer args: /qn ADDLOCAL=StartMenu
	2022-05-28 10:15:19.543 [CLI ] Starting: 'C:\Users\x\AppData\Local\Temp\WinGet\Open-Shell.Open-Shell-Menu.4.4.170\OpenShellSetup_4_4_170.exe' with arguments '/qn ADDLOCAL=StartMenu'
	2022-05-28 10:15:20.958 [CLI ] ShellExecute installer failed: 1603
	2022-05-28 10:15:20.959 [CLI ] Terminating context: 0x8a150006 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:15d

Winget with forced interactive mode (-i,--interactive ... with or without overrides) succeeds but is NOT silent:

	winget install Open-Shell.Open-Shell-Menu --interactive --override ADDLOCAL=StartMenu,Update

The command above installs correctly but this is fully interactive (we want silent mode).

The /qn option has always worked previously.

**Screenshots**
N/A

**Open-Shell Version**
4.4.170

**Tested on Operating systems**
Windows 10 Pro Stable Build 19041.vb_release.191206-1406 (10.0.19044.1706)
Windows 11 Pro Beta Build 22621.ni_release.220506-1250 (10.0.22621.1)

**Additional context**
N/A

**Comment by Ibuprophen** [comment]
Though I (personally) feel that issues reported on Github are specifically for the software itself and believe that other issues not specific to the software (like methods other than the standard installation) are ready something that's more of a Question for the Community. 

Just a suggestion... 

Try taking a look at the following link regarding Silent Installation Parameters for an executable file. 

https://www.pdq.com/blog/install-silent-finding-silent-parameters/

It may help you figure out a method that best suits your specific need. 

Good Luck! 

~Ibuprophen
