### ISSUE TITLE
Modern Settings shortcuts are broken on my install

### ISSUE THREAD

**Issue by terax6669** [Open-Shell/Open-Shell-Menu#1031]
**To Reproduce**
1. Open start, search for windows updates
2. Click on "Check for updates"
3. Windows settings open, but not the update tab.

**Expected behavior**
The shortcut takes us to the expected location.

**Screenshots**
![image](https://user-images.githubusercontent.com/19204073/170841486-48e307cd-b46c-42c5-92f5-0cbfdc562957.png)

**Version:**
 - Open-Shell: 4.4.160 and 4.4.170
 - OS: Windows 11 Pro 21H2 22000.675

**Additional context**
I've noticed that the action is doubled.
![image](https://user-images.githubusercontent.com/19204073/170841640-5235d952-cd58-4fa5-9d47-b525411f17fc.png)
I think they're called `AAA_SystemSettings_MusUpdate_UpdateActionButton` and `AAA_SystemSettings_MusUpdate_UpdateActionButton-2`. The second one works for me. As you can see there are other duplicates there and other weird entries too...
![image](https://user-images.githubusercontent.com/19204073/170841697-a4ec410d-e443-4073-b8b5-6d1649949942.png)

**Comment by ge0rdi** [comment]
Just note that Windows started to add new settings descriptions and keep old ones (for whatever reason).
That's why we should those duplicates.

I'll try to remove duplicate ones and keep those newer (better) ones (with the numeric suffix).

**Comment by ge0rdi** [comment]
Should be fixed in [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build.

**Comment by terax6669** [comment]
It took a while to populate the settings the first time I used the search, but it seems to be working great now 👍

**Comment by ge0rdi** [comment]
Yup, first time the modern settings folder is enumerated it has to retrieve localized strings for all the settings. It takes some time. But then it is cached so subsequent searches are fast.

Thanks for confirming it works for you now.
