### ISSUE TITLE
Error Code 2203

### ISSUE THREAD

**Issue by LordGlizzy** [Open-Shell/Open-Shell-Menu#1035]
Hello, when i try to install open shell i get a error code 2203 and it will not install.

**Comment by Ibuprophen** [comment]
This is not specific to Open Shell, but a Windows OS specific error code. 

I haven't seen this error code (personally) in quite some time, but it either means that the users account doesn't have sufficient permission(s) to install the software OR an Antivirus Software is preventing/blocking the installation.

~Ibuprophen
