### ISSUE TITLE
Original Start button stays there and can't be hidden

### ISSUE THREAD

**Issue by noeyefish** [Open-Shell/Open-Shell-Menu#1036]
after download the lastes vresion of Open-Shell-Menu, windows 11 start button still there and above it ihave my custom shell button.

![image](https://user-images.githubusercontent.com/2453094/202844871-8941e563-0c8c-4ffb-817d-17cb486c47af.png)

**Comment by muhachris297** [comment]
This has always happened, it is nothing in specific to the version update. I personally like it, but it is technically an issue that would need to be fixed in a patch update to the program.

**Comment by Sumanuil** [comment]
You can cover it with a sufficiently large custom start button. 53 pixels wide seems to be enough.

**Comment by ge0rdi** [comment]
Support for Windows 11 start button was added in [4.4.181](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.181).

For more info about custom button limitations, see https://github.com/Open-Shell/Open-Shell-Menu/issues/911#issuecomment-1339824015.
