### ISSUE TITLE
Uninstalling OpenShell, Bricks StartMenu

### ISSUE THREAD

**Issue by I2pRandom** [Open-Shell/Open-Shell-Menu#1038]
Upon uninstalling OpenShell, the installer/program bricks the entire StartMenu and also will arbitrarily/randomly break the entire explorer.exe process making almost impossible to even get to the desktop, i've only been able to recover from this problem twice in the past. 

![image](https://user-images.githubusercontent.com/42506001/171995271-ab4050b6-49c7-4862-82ad-60c65aaa5338.png)

**Comment by SoftOrangeTech** [comment]
Hello @I2pRandom,
This may be a leftover of some code in the OpenShell program.
I will test this tomorrow and give you my results, if this happens to everybody or to you.
Thank you!

**Comment by mohamedmmc** [comment]
did a proper uninstall and got the same thing
can't even open windows button neither with mouse or keyboard

**Comment by Ibuprophen** [comment]
When it comes to Windows 10+, I've seen (on a couple of occasions) individuals who had experienced some type of issue (mostly minor) regarding the typical method when uninstalling 3rd party software that's actually tied to the Windows OS specifically. 

The following are just a few links I've saved that has provided me with ideas, guidance, techniques, etc... that had (for the most part) been very helpful to me. 

https://www.alphr.com/force-program-uninstall-windows/

https://www.urtech.ca/2019/09/solved-command-line-to-uninstall-software-exes-or-msis/

Ultimately, I find that uninstalling 3rd party software (primarily in Windows 10+), even using any of the above methods, were best done in safe mode using an Administrative Account (often hidden & only seen when in safe mode). 

Besides that, if issues arise, when/after uninstalling a 3rd party software, I can only suggest using the System File Checker that's outlined on the following link. 

https://support.microsoft.com/en-us/windows/using-system-file-checker-in-windows-365e0031-36b1-6031-f804-8fd86e0ef4ca/

I can't guarantee/endorse any specific method personally as everyone's environment, situation, etc... varies, but I do hope that this is helpful in some way for most/all. 

Good Luck! 

~Ibuprophen
