### ISSUE TITLE
Update to 4.4.170 has errors

### ISSUE THREAD

**Issue by AndyK70** [Open-Shell/Open-Shell-Menu#1039]
**Describe the bug**
I was on the latest stable release of Open-Shell and just had a notification for a newer release (4.4.170) addressing some issues. 

1. I clicked on Download and it downloaded the new version into my downloads folder.
2. I then closed the update notification, opened my windows explorer and in the downloads folder made a double click on the new downloaded file.
3. The update process started, I had to prompt the UAC and the updater copied some files.
4. Then the first error message came up: ![OpenShellSetup2022-06-05 131607](https://user-images.githubusercontent.com/666825/172048181-8c33b850-192e-4500-a20a-f80003349075.png)
5. after a click on OK the next error showed: ![OpenShellSetup2022-06-05 131705](https://user-images.githubusercontent.com/666825/172048213-eb657989-7826-4b18-acba-aedd714f402a.png)
6. It continued the update process but after it finished there was no Open-Shell Icon instead it was the normal windows menu icon and Open-Shell wasn't working.
7. I restarted the pc, Open-Shell still didn't show up.
8. I went to Apps & Features and uninstalled Open-Shell 
9. made another restart
10. then went to Downloads again and did another install.
11. The same error messages came up but this time the Open-Shell Icon appeared in the lower left corner and it seems to be working I just don't know if there are just two shortcut links missing or if something else is wrong under the hood.

**To Reproduce**
Steps to reproduce the behavior: please look above

**Expected behavior**
After a click on Install I expected a clean install without any error messages

**Screenshots**
see above

**Version:**
 - Open-Shell: 4.4.170
 - OS: Windows version 10.0.19044.1706

**Additional context**
please let me know if you need any other information

**Comment by bonzibudd** [comment]
The shortcut errors should be mostly harmless from what I can tell. If the first installation failed, it's possible that something else interrupted the process. Have you had any problems since installation?
