### ISSUE TITLE
Control Panel Menu Start Order Scrambled

### ISSUE THREAD

**Issue by ewcarmack** [Open-Shell/Open-Shell-Menu#1040]
**Describe the bug**
A clear and concise description of what the bug is:
In the Customize Start Menu tab, I have checked Control Panel to Display as menu. Unlike prior versions of Open-Shell, the menu sort order is no longer alphabetical.

**To Reproduce**
1. Go to 'Start Menu' 
2. Click on 'Start' button; then click on 'Control Panel' in side panel.
3. View the entire menu of control panel icons/shortcuts to the right
4. See error: The sort order is now scrambled with no way to Sort by Name (alphabetize it)

**Expected behavior**
A clear and concise description of what you expected to happen. The list of Control Panel icons/shortcuts should have been automatically listed from top to bottom in descending alphabetical order.

**Screenshots**
![image](https://user-images.githubusercontent.com/107085529/172507861-805e05f7-6298-444e-85bc-adf15da8a3f3.png)

**Version:**
 - Open-Shell: [4.4.170]
 - OS: [Windows 10 Pro 21H2]

**Additional context**
I have used Open-Shell (and its predecessors) on many different desktop and laptop PCs, Windows 7 through Windows 11, but never encountered this issue before. The above-described error appears now on my Dell Inspiron 5675 desktop PC.

**Comment by Ibuprophen** [comment]
Right click on the Control Panel folder itself and you should locate a sorting option. 

~Ibuprophen

**Comment by ewcarmack** [comment]
A sorting option does not appear when I right-click. I had tried that already before making this post. But thanks anyway.

ewcarmack

**Comment by BlueDrakoPT** [comment]
Right click on the Control Panel folder itself and you should locate a sorting option.  ---> how to right click in the control panel "itself" ????? When I try no sorting option appears like in other folders. Help is needed. Thanks!

**Comment by ewcarmack** [comment]
Problem Solved: I installed a more recent version (prerelease) of OpenShell, which solved the problem without further intervention by me. Apparently there was a bug in version 4.4.170; I am now using prerelease version 4.4.178. My Control Panel menu is now sorted alphabetically in descending order as originally intended.
