### ISSUE TITLE
Start menu "Classic with two columns" option has user icon out of place

### ISSUE THREAD

**Issue by SoftOrangeTech** [Open-Shell/Open-Shell-Menu#1041]
**Describe the bug**
Classic with two columns shows up the user icon, but it is out of place.

**To Reproduce**
1. Go to Open Shell Start
2. See user icon, it's out of place

**Expected behavior**
The user icon should stay aligned properly.

**Screenshots**
![Annotation 2022-06-12 155506](https://user-images.githubusercontent.com/106856843/173257062-1ba2435d-81cb-488c-81b2-b9b91b607105.png)

**Version:**
 - Open-Shell: 4.4.170
 - OS: Windows 10

**Additional context**
The user icon is usually in place. In here, it's out of place

**Comment by CTVCAM8** [comment]
It's a good idea to add a screenshot and any other info that helps define it as a possible bug or as per design.

Is it one of the menu skins that come with Open-Shell, or a user-modified skin, 
or is it the wrong position with all the skins?

Just in case you are using the default "Metro" skin in Classic with 2 columns,
the position of the user picture icon is moved to the right to accommodate the user name.
The "Metro" skin in Windows 7 style centers the user picture icon in the second column.

**Comment by SoftOrangeTech** [comment]
> It's a good idea to add a screenshot and any other info that helps define it as a possible bug or as per design.
> 
> Is it one of the menu skins that come with Open-Shell, or a user-modified skin, or is it the wrong position with all the skins?
> 
> Just in case you are using the default "Metro" skin in Classic with 2 columns, the position of the user picture icon is moved to the right to accommodate the user name. The "Metro" skin in Windows 7 style centers the user picture icon in the second column.

Here's a screenshot:
![Annotation 2022-06-12 155506](https://user-images.githubusercontent.com/106856843/173257035-1280302a-ee5a-48ed-a0a2-48160790b048.png)

**Comment by CTVCAM8** [comment]
That "Full Glass" skin was designed like that. 

If you want to have the user picture say in the center of the second column,
the "Full Glass" skin text file would need to be modified by adding "User_frame_position=center2,10" to override the original values.

You can read about it and more in the skinning tutorial

http://classicshell.net/tutorials/skintutorial.html


![Full Glass skin mod](https://user-images.githubusercontent.com/44127216/173259202-07fd305a-0856-4bee-b1aa-847821d1e671.png)




I'm not sure if the coders can add the user picture position as a general settings option, as each skin has its own separate parameters. 
Mind you the coders did a good job adding the new floating menu feature "Horizontal position offset" and "Vertical position offset". :)

**Comment by SoftOrangeTech** [comment]
> That "Full Glass" skin was designed like that.
> 
> If you want to have the user picture say in the center of the second column, the "Full Glass" skin text file would need to be modified by adding "User_frame_position=center2,10" to override the original values.
> 
> You can read about it and more in the skinning tutorial
> 
> http://classicshell.net/tutorials/skintutorial.html
> 
> ![Full Glass skin mod](https://user-images.githubusercontent.com/44127216/173259202-07fd305a-0856-4bee-b1aa-847821d1e671.png)
> 
> I'm not sure if the coders can add the user picture position as a general settings option, as each skin has its own separate parameters. Mind you the coders did a good job adding the new floating menu feature "Horizontal position offset" and "Vertical position offset". :)

But where is the text file located?

**Comment by SoftOrangeTech** [comment]
OK, thank you!

**Comment by SoftOrangeTech** [comment]
> [But where is the text file located?]
> 
> It's a bit complicated at the beginning. You would need to download and install Resource Hacker to be able to open the skin file, which is in "C:\Program Files\Open-Shell\Skins" and edit the text in folder #1 Save the skin under a different name so the original is kept.
> 
> It's best to read up about it first and decide if it is worth the trouble.

It feels like it **is** complicated, + you mentioned the #1 pull request. I'll reopen it until I used Resource Hacker.

**Comment by CTVCAM8** [comment]
![Skin text location ](https://user-images.githubusercontent.com/44127216/173267163-32a27a8b-819e-421a-8731-29476fa81d72.png)

Funny, the site automatically made the hash1 into an unintended link.

It would be great if I could just upload the modded skin to somewhere on Github.
If you really want it badly, I can upload it on the original Classic Shell site for you?

**Comment by SoftOrangeTech** [comment]
> ![Skin text location ](https://user-images.githubusercontent.com/44127216/173267163-32a27a8b-819e-421a-8731-29476fa81d72.png)
> 
> Funny, the site automatically made the hash1 into an unintended link.
> 
> It would be great if I could just upload the modded skin to somewhere on Github. If you really want it badly, I can upload it on the original Classic Shell site for you? On second thought, Instead of me using Classic Shell, try this way.
> 
> Not sure if an external download link is allowed here for it might get blocked.
> 
> Here is the link to down the modded skin file.
> 
> https://www.transfernow.net/dl/20220613LioFX7wb
> 
> Will expire in a number of days.
> 
> Put it in the skins folder on your computer.

Thanks for providing the mod! I will download the file and put it on the skins folder.
