### ISSUE TITLE
Use... [EDIT] 

### ISSUE THREAD

**Issue by muhachris297** [Open-Shell/Open-Shell-Menu#1045]
... [EDITED]...

**Comment by Ibuprophen** [comment]
Others are aware of alternative Start Menu software. 

This software may not be perfect and I don't know of any other start menu software that is. 

Everyone has different tastes to different software and advertising other start menu software has a better place elsewhere than posting it within this repositories issue is not very appropriated. 

I've never done this here before, but I feel that it was necessary. 

Thank you very much for your time and understanding with this. 

~Ibuprophen
