### ISSUE TITLE
Task bar issues on Windows 11 latest build 

### ISSUE THREAD

**Issue by mtbboy1993** [Open-Shell/Open-Shell-Menu#1046]
right corner feature does not work.
full screen does not work, task bar is is overlaid over whatever is open, a browser, a video in full screen.
stock windows start menu does not work, nor settings shortcut if you have one.
the feature displaying all open windows also does not work.

**Comment by blackcrack** [comment]
you does not work with "explorer patcher" damn, you should fresh patched with informations from past issues..

in short, you should be patched with informations about totally changed bullshit win11 who need first
a patch for explorer, before win11 react like a native Windows...

https://github.com/valinet/ExplorerPatcher

you can close this issue, thank you, i have finish..

**Comment by namiltd** [comment]
Try this .reg file:
`Windows Registry Editor Version 5.00

;Created by Vishal Gupta for AskVG.com

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell\Update\Packages]
"UndockingDisabled"=dword:00000001

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Search]
"SearchboxTaskbarMode"=dword:00000000

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"ShowTaskViewButton"=dword:00000000
"ShowCortanaButton"=dword:00000000

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer]
"NoTaskGrouping"=dword:00000000`

**Comment by ge0rdi** [comment]
Please, try with 4.4.181 or newer.
