### ISSUE TITLE
Frequently used programs not working

### ISSUE THREAD

**Issue by Blue-Spiral** [Open-Shell/Open-Shell-Menu#1048]
Frequently used programs not showing up in the start menu. Nothing shows up in the start menu when this option is set. Also, I've made two different directories in the start menu and set them on top of programs, one with educational apps, the other with games. Even when I chose "recent programs" to show in the start menu, no app from those folders ever shows up. This used to work until a few days ago. Not anymore. I have uninstalled and reinstalled the program, deleted the entries from registry and user roaming/local folders. Nothing helped. I don't understand what's happening. Open Shell used to work perfectly. Not anymore. Thank you very much in advance!
One more thing: when I used the "pin" option for start menu, my other folders appear under the "programs" and they do show  up. However, this makes the start menu clumsy looking and less comfortable to use.

**Comment by ge0rdi** [comment]
See #149.
