### ISSUE TITLE
Open Shell 4.4.170 explorer restarts intermittently ,BUG

### ISSUE THREAD

**Issue by Mitia514** [Open-Shell/Open-Shell-Menu#1051]
After updating the program to a new version Open Shell 4.4.170.
I began to notice that the explorer periodically reboots, 
it's so sad(

I had to install the old version  OpenShell 4.4.160
I hope you fix this annoying bug

Windows 10 Pro 64bit ,16gb, gtx1050ti</div>

**Comment by lieszkol** [comment]
I'd like to second this, in fact in my instance explorer kept crashing and restarting. Event viewer showed that igfxdin.dll was crashing, taking down the Explorer process with it. The computer became extremely unusable, I was only able to resolve the problem by opening the task manager and running appwiz.cpl to somehow uninstall Open Shell and get back control of the computer.

**Comment by Mitia514** [comment]
I had the same, it's sad.

**Comment by ge0rdi** [comment]
Please, try with latest [nightly](https://github.com/Open-Shell/Open-Shell-Menu/releases) build.
If the issue persists, try to obtain crash dump using this [guide](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-create-dump-on-Windows-Explorer-crash) and reopen this issue.
