### ISSUE TITLE
Microsoft Defender's SmartScreen filter prevents upgrade to 4.4.170

### ISSUE THREAD

**Issue by opty77** [Open-Shell/Open-Shell-Menu#1052]
Microsoft Defender Antivirus - KB2267602 (version 1.367.1478.0) and its SmartScreen filter prevents upgrade from 4.4.160 to 4.4.170 (unrecognized application) on Windows 10 Pro (21H2, build 19044.1706).

**Comment by blackcrack** [comment]
could anyone sent it in, to MS-Analyse ?
The binary of 4.4.170 should send it in to MS-Analyse and the issue is time near solved ...
