### ISSUE TITLE
Weird menu issues with latest update of Windows 11 (Windows 11, version 22H2)

### ISSUE THREAD

**Issue by pkirkaas** [Open-Shell/Open-Shell-Menu#1053]
I'm not sure this is an issue with Open-Shell - but just in case,  FYI -

I waited like 8 months to "upgrade" to W11 for it to stabilize. And when I finally upgraded to W11 in May, it actually went kind of OK after a day or two of reconfiguring.

But last week, after the 22H2 update,  I got some really weird behavior only in SOME of my applications - and different issues for different apps.

Some, like gvim which I've been using flawlessly for over 20 years - clicking on a menu item or right clicking for context menu just gives up/down arrows - no items - as if the "menu list" was shrunk to size 0 (see attached image).

Other apps like SmartGit - the menus appear normally, but when I click on a menu item, it's actually the item/command 2 lines above that is actually selected.

Clearly this is a problem with the latest W11 update, but I don't observe this behavior on my other computers with the same W11 update but DON'T have open-shell installed - so I thought I would just bring this to your attention.

Thanks so much for the work you have been doing to keep Windows usable!

![GVim-menu](https://user-images.githubusercontent.com/201110/173320447-fe534955-d60e-4d47-8508-e7602b83ce8a.jpg)

**Comment by SoftOrangeTech** [comment]
Hello,
Clearly this is an issue with Windows 10. Can you post a question on the [Microsoft Community](https://answers.microsoft.com/en-us?lc=1033) instead?
Thank you.

**Comment by ge0rdi** [comment]
It is very unlikely to be caused by `Open-Shell`.

I guess you must have some other software installed that causes it.
You can also check if uninstalling `Open-Shell` on affected machine makes it go away.
