### ISSUE TITLE
Apps folder showing blank icon for uninstalled apps

### ISSUE THREAD

**Issue by bynarie** [Open-Shell/Open-Shell-Menu#1056]
### Discussed in https://github.com/Open-Shell/Open-Shell-Menu/discussions/1055

<div type='discussions-op-text'>

<sup>Originally posted by **bynarie** June 14, 2022</sup>
As you can see in my image, apps folder is showing microsoft edge, with the blank icon, even though I have completely removed edge completely. Is there a folder where these shortcuts are placed or is there a way to correct this? Thanks!

![openshell](https://user-images.githubusercontent.com/9805554/173708108-35e9c950-50f9-423b-9b8e-6334bbd0257b.jpg)

</div>

**Comment by blackcrack** [comment]
it's imo not from Open-shell, it's a cache-thing, the other icons be displayed, so can it not be from OpenShell
and you can close the issue..
thy
best

**Comment by blackcrack** [comment]
https://github.com/Open-Shell/Open-Shell-Menu/discussions/1055

**Comment by DrStrange** [comment]
FYI, Microsoft appears to have finally fixed this. The Edge entry no longer appears under the Apps menu in Windows 10 22H2- v19045.3758
