### ISSUE TITLE
Everything is slow to open

### ISSUE THREAD

**Issue by tzr916** [Open-Shell/Open-Shell-Menu#1058]
The start menu itself is NOT slow.... I am referring to after I click on something in the Open Shell start menu. I can literally count three or four mississippi's before the item opens. It is everything, from documents or downloads folders, or windows settings, or a program, or control panel, etc. 

I've been using Open-Shell forever, but don't remember this being an issue until recently, maybe only started around six months ago. But it was definitely happening with a prior version of Open-Shell, so I installed the latest version, same issue.

Also, immediately after rebooting the computer the problem doesn't happen. Only after a few hours of uptime, do things start to open slow. Meanwhile, if I open these same items from desktop shortcut or default Win10 start menu, they open in a tenth of a second. 

Version:
 - Open-Shell: 4.4.170
 - OS: Windows 10 64b v21H2 b19044.1766
 - MSI Modern 14 laptop, Intel 1.6GHz Core i5-10210U, Kingston 512GB SSD, 16GB DDR4

**Comment by Ibuprophen** [comment]
Progress slow to launch isn't tied to the Menu and can point to 1 or more other possibilities (as I personally couldn't state anything specific without seeing the system itself). 

One thing that is typically the case is the number of background software and such running that typically results in either/or a high CPU usage and RAM space. 

~Ibuprophen

**Comment by tzr916** [comment]
Perhaps you missed where I  said - "meanwhile, if I open these same items from desktop shortcut or default Win10 start menu, they open in a tenth of a second".

CPU usage and RAM is not the issue. There is nothing running in the background. I run a clean system, no third party AV or firewall. 

Open to suggestions.

**Comment by blackcrack** [comment]
@Ibuprophen,  :, OSI 8 ! 
(Open Systems Interconnection model)
should Closed ! imho it's a "Not OpenShell" issue
