### ISSUE TITLE
MAJOR ISSUE: Does not restore any settings

### ISSUE THREAD

**Issue by sjain882** [Open-Shell/Open-Shell-Menu#106]
https://drive.google.com/open?id=1yij2a5uqEZ0LXfTSpw4zSI6hmJO6SN2i

**MENU SETTINGS 11 11 18.xml** - Created with Open Shell latest

Menu Settings weird.xml -  - Created with Open Shell latest

Menu Settings.xml - Created with Classic Start

***

1. I updated Classic Start latest to the new Open Shell one, and most of my settings were lost

2. The "Customise Start Menu" part of the settings was fine , though and I could access all my files

3. Didn't like it, because the new DPI thing was weird (hence weird in the xml name) and downgraded to classic start

4. Everything was exactly as it was before any changed were made

5. Installed this as per instructions: https://github.com/davestewart/classic-shell-win10

6. It looked very weird, did not scale well on my system - https://i.imgur.com/cXxBqqT.png

7. So i exited classic start and removed all the theme files

8. Then i opened it up again and restored my old settings. **I TRIED ALL THREE XML FILES, RESTARTING MY PC BETWEEN EACH ONE**

9. It is stuck like this - https://i.imgur.com/cXxBqqT.png - when it used to look like this - https://cdn.discordapp.com/attachments/460214567637614613/511170582742827009/unknown.png

10. I tried completely wiping all classic start / open shell things from appdata, local, roaming, locallow, programdata, program files, registry, using the Everything search tool, then restarted

11. Reinstalled classic start latest and rebooted

12. Restored "Menu Settings.xml", because its made for classic shell

13. exited Classic Start, same issue

14. Restarted explorer, same issue

16. Restarted PC for good measure, same issue

***

Really just want my old setup back. **please help!**

i tried rebooting between **every step above**

- Windows 10 Home
- x64
- version 1809
- build 17763.55
- no other shell extensions installed

**Comment by sjain882** [comment]
note that the "Customise Start Menu" has completely changed - it isnt one column any longer which allows me to change settings, add shortcuts, display as  menu . whaterver. How can I restore the old version? The version is identical to the one defined in my old "Menu Settings.xml" file - created with Classic Start while the menus and everything wasn't so messed up.

<Settings component="StartMenu" version="4.4.109">

code of my normal, working file that i want to restore incase ppl cant see google drive link / on mobile slow connections etc:


```
<?xml version="1.0"?>
<Settings component="StartMenu" version="4.4.109">
	<Hover value="Nothing"/>
	<StartHoverDelay value="0"/>
	<ShiftRight value="0"/>
	<ConfirmLogOff value="1"/>
	<ProgramsStyle value="Inline"/>
	<FoldersFirst value="1"/>
	<ProgramsMenuDelay value="200"/>
	<RecentPrograms value="Recent"/>
	<RecentSortName value="0"/>
	<ShutdownCommand value="CommandShutdownBox"/>
	<ShutdownW7 value="hibernate;switchuser;shutdown;logoff;restart;lock;sleep"/>
	<HybridShutdown value="0"/>
	<StartScreenShortcut value="0"/>
	<HighlightNew value="0"/>
	<CheckWinUpdates value="0"/>
	<MenuDelay value="550"/>
	<ScrollType value="NoScroll"/>
	<ExpandFolderLinks value="1"/>
	<EnableAccessibility value="0"/>
	<ShowNextToTaskbar value="1"/>
	<DelayIcons value="0"/>
	<ReportSkinErrors value="0"/>
	<SearchTrack value="1"/>
	<SearchPath value="0"/>
	<SearchInternet value="0"/>
	<InvertMetroIcons value="0"/>
	<OverrideDPI value="0"/>
	<MainMenuAnimation value="Slide"/>
	<MainMenuAnimationSpeed value="250"/>
	<SubMenuAnimation value="Slide"/>
	<SubMenuAnimationSpeed value="50"/>
	<SubMenuAnimationAlways value="1"/>
	<FontSmoothing value="ClearType"/>
	<GlassOverride value="0"/>
	<GlassColor value="1644825"/>
	<GlassOpacity value="50"/>
	<SkinW7 value="Metro"/>
	<SkinVariationW7 value=""/>
	<SkinOptionsW7>
		<Line>USER_IMAGE=1</Line>
		<Line>SMALL_ICONS=0</Line>
		<Line>LARGE_FONT=1</Line>
		<Line>COLOR_SILVER=0</Line>
		<Line>COLOR_GOLD=0</Line>
		<Line>COLOR_STEEL=0</Line>
		<Line>COLOR_TITANIUM=0</Line>
		<Line>COLOR_CUSTOM=000000</Line>
		<Line>SUBCOLOR_SILVER=0</Line>
		<Line>SUBCOLOR_GOLD=0</Line>
		<Line>SUBCOLOR_STEEL=0</Line>
		<Line>SUBCOLOR_TITANIUM=0</Line>
		<Line>SUBCOLOR_CUSTOM=000000</Line>
		<Line>CUSTOM_TEXT_SIZE=15</Line>
	</SkinOptionsW7>
	<EnableStartButton value="0"/>
	<StartButtonType value="CustomButton"/>
	<StartButtonPath value="D:\windows9x.png"/>
	<StartButtonSize value="99999"/>
	<StartButtonAlign value="0"/>
	<CustomTaskbar value="1"/>
	<TaskbarLook value="Glass"/>
	<TaskbarOpacity value="50"/>
	<TaskbarColor value="1644825"/>
	<SkipMetro value="1"/>
	<OpenMouseMonitor value="1"/>
	<MenuItems7>
		<Line>Item1.Link=D:\Shortcuts\Game Files</Line>
		<Line>Item1.Label=Game Files</Line>
		<Line>Item2.Link=D:\Quick Access Folder</Line>
		<Line>Item2.Label=Quick Access</Line>
		<Line>Item3.Link=%SystemDrive%\Program Files (x86)\Steam\steamapps\common</Line>
		<Line>Item3.Label=Steam Apps</Line>
		<Line>Item4.Link=D:\Shortcuts\Game Shortcuts</Line>
		<Line>Item4.Label=Games</Line>
		<Line>Item5.Link=D:\SCHOOL WORK</Line>
		<Line>Item5.Label=School Work</Line>
		<Line>Item6.Link=H:\OMSI 2\docs</Line>
		<Line>Item6.Label=OMSI 2 Documents</Line>
		<Line>Item7.Command=separator</Line>
		<Line>Item8.Command=computer</Line>
		<Line>Item9.Link=D:\</Line>
		<Line>Item9.Label=D:\</Line>
		<Line>Item9.Settings=NOEXPAND</Line>
		<Line>Item10.Command=separator</Line>
		<Line>Item11.Command=pc_settings</Line>
		<Line>Item11.Label=Settings</Line>
		<Line>Item11.Icon=%windir%\ImmersiveControlPanel\SystemSettings.exe,10</Line>
		<Line>Item11.Settings=TRACK_RECENT</Line>
		<Line>Item12.Command="C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  --profile-directory=Default --app-id=jjphmlaoffndcnecccgemfdaaoighkel</Line>
		<Line>Item12.Label=YouTube Floating Window</Line>
		<Line>Item13.Link=D:\_Libraries\Desktop\polish2018\TMPSHORTCUTS</Line>
		<Line>Item13.Label=TMP SHORTCUTS</Line>
		<Line>Item14.Link=D:\_Libraries\Desktop\polish2018\new apps folder</Line>
		<Line>Item14.Label=tmp apps folder testing</Line>
	</MenuItems7>
	<CascadingMenu value="0"/>
	<ShowNewFolder value="1"/>
</Settings>
```

**Comment by sjain882** [comment]
> This is more than likely that the XML file itself has the Classic Shell locations/references within it and those said locations/references for Classic Start isn't the same.
> 
> I had intended to look into this myself at one time and had forgotten about it...
> 
> I'll get back to you (if someone else doesn't) here to see what can be done.
> 
> ~Ibuprophen

Thank you so much for replying quickly within the day. Take your time, I can deal with it for now :) I myself am baffled because the version numbers are identical but the "Customise Start Menu" thing in settings is a different panel.

**Comment by CTVCAM8** [comment]
As an outsider looking at your xml settings, it all looks so jumbled, 
keeping remnants of Metallic, Metro skins, 7 style. It kind of lost its way. 
I don't see the original  Classic 2 style called "Windows 10" of David's. 


I tried his skin on Open-Shell 4.4.131 Put the skin in Open-Shell skins folder (not the old Classic Shell skins folder).
I did what you did, and loaded Dave's original xml file. Works ok. I'm using standard 100% size.

Found this from davestewart on Classic Shell:

http://classicshell.net/forum/viewtopic.php?f=7&t=8452&p=35841#p35841

Looking at his original xml file <OverrideDPI value="96"/>
This setting did not work too well when he used a higher dpi display.
What final dpi setting he used in the program is unknown, possibly system default "0", or a higher override number like 144 to 200.

I reset his dpi settings to default "0", and backed up  xml file with a new name. Reset all settings, exited Open-Shell, restarted and loaded new name xml file.
Exited again, restarted Open-Shell - result-appears to look and behave correctly. That was only 1 change. Your files have many changes.
I do notice a difference in the original and renamed 0 dpi file:

Original  Windows 10 Settings.xml
	
<SkinC2 value="Windows 10"/>
<SkinVariationC2 value=""/>
<SkinOptionsC2 value="E55CEDD2|C26EAF5D|86F3669C|5225DC46|5D3248DC|1FC64124|33C166BE|6EDFA36B|"/>
<EnableStartButton value="0"/>


Saved  0dpi Windows 10 Settings.xml

<SkinC2 value="Windows 10"/>
<SkinVariationC2 value=""/>
<SkinOptionsC2>
</SkinOptionsC2>
<EnableStartButton value="0"/>

Possibly this is caused by Dave using Classic Shell "4.2.4" for original xml?
That's about as much as I can help with. Coders will see better than me.

**Comment by sjain882** [comment]
I signed into my other account on this PC, which still had my old start menu fine like this:

https://i.imgur.com/iLWqIlq.png

When it's screwed up on my main account like this:

https://i.imgur.com/ugY57HI.png

**Both accounts have the same exact .xml imported.**

> I'm just wondering exactly which of the 3 files on your Shared Drive is the one with the issue?

Not sure if this is how you quote here - but all three basically, importing all of them has no effect, the start menu remains broken (see above, second imgur link).

> Your explanation kinda jumps around on a few spots and I just wanted to be certain which one is the file I should be directing my attention to.

I'm importing my settings over and over and nothing is happening basically. Sorry, my explanation is not well written and I will come back to add more details later, when I have time. Happens with Classic Start (latest release) _and_ Open Shell, sadly, with plenty of reboots between inputting settings, installing, uninstalling, etc.

I made a fresh export of settings **(incase importing into Classic Start somehow altered the backup xml file itself)** and copied the code from the XML **from the account with the normal start menu., This is an export of how i want it:**

```
<?xml version="1.0"?>
<Settings component="StartMenu" version="4.4.109">
	<Hover value="Nothing"/>
	<StartHoverDelay value="0"/>
	<ShiftRight value="0"/>
	<ConfirmLogOff value="1"/>
	<ProgramsStyle value="Inline"/>
	<FoldersFirst value="1"/>
	<ProgramsMenuDelay value="200"/>
	<RecentPrograms value="Recent"/>
	<RecentSortName value="0"/>
	<ShutdownCommand value="CommandShutdownBox"/>
	<ShutdownW7 value="hibernate;switchuser;shutdown;logoff;restart;lock;sleep"/>
	<HybridShutdown value="0"/>
	<StartScreenShortcut value="0"/>
	<HighlightNew value="0"/>
	<CheckWinUpdates value="0"/>
	<MenuDelay value="550"/>
	<ScrollType value="NoScroll"/>
	<ExpandFolderLinks value="1"/>
	<EnableAccessibility value="0"/>
	<ShowNextToTaskbar value="1"/>
	<DelayIcons value="0"/>
	<ReportSkinErrors value="0"/>
	<SearchTrack value="1"/>
	<SearchPath value="0"/>
	<SearchInternet value="0"/>
	<InvertMetroIcons value="0"/>
	<OverrideDPI value="0"/>
	<MainMenuAnimation value="Slide"/>
	<MainMenuAnimationSpeed value="250"/>
	<SubMenuAnimation value="Slide"/>
	<SubMenuAnimationSpeed value="50"/>
	<SubMenuAnimationAlways value="1"/>
	<FontSmoothing value="ClearType"/>
	<GlassOverride value="0"/>
	<GlassColor value="1644825"/>
	<GlassOpacity value="50"/>
	<SkinW7 value="Metro"/>
	<SkinVariationW7 value=""/>
	<SkinOptionsW7>
		<Line>USER_IMAGE=1</Line>
		<Line>SMALL_ICONS=0</Line>
		<Line>LARGE_FONT=1</Line>
		<Line>COLOR_SILVER=0</Line>
		<Line>COLOR_GOLD=0</Line>
		<Line>COLOR_STEEL=0</Line>
		<Line>COLOR_TITANIUM=0</Line>
		<Line>COLOR_CUSTOM=000000</Line>
		<Line>SUBCOLOR_SILVER=0</Line>
		<Line>SUBCOLOR_GOLD=0</Line>
		<Line>SUBCOLOR_STEEL=0</Line>
		<Line>SUBCOLOR_TITANIUM=0</Line>
		<Line>SUBCOLOR_CUSTOM=000000</Line>
		<Line>CUSTOM_TEXT_SIZE=15</Line>
	</SkinOptionsW7>
	<EnableStartButton value="0"/>
	<StartButtonType value="CustomButton"/>
	<StartButtonPath value="D:\windows9x.png"/>
	<StartButtonSize value="99999"/>
	<StartButtonAlign value="0"/>
	<CustomTaskbar value="1"/>
	<TaskbarLook value="Glass"/>
	<TaskbarOpacity value="50"/>
	<TaskbarColor value="1644825"/>
	<SkipMetro value="1"/>
	<OpenMouseMonitor value="1"/>
	<MenuItems7>
		<Line>Item1.Link=D:\Shortcuts\Game Files</Line>
		<Line>Item1.Label=Game Files</Line>
		<Line>Item2.Link=D:\Quick Access Folder</Line>
		<Line>Item2.Label=Quick Access</Line>
		<Line>Item3.Link=%SystemDrive%\Program Files (x86)\Steam\steamapps\common</Line>
		<Line>Item3.Label=Steam Apps</Line>
		<Line>Item4.Link=D:\Shortcuts\Game Shortcuts</Line>
		<Line>Item4.Label=Games</Line>
		<Line>Item5.Link=D:\SCHOOL WORK</Line>
		<Line>Item5.Label=School Work</Line>
		<Line>Item6.Link=H:\OMSI 2\docs</Line>
		<Line>Item6.Label=OMSI 2 Documents</Line>
		<Line>Item7.Command=separator</Line>
		<Line>Item8.Command=computer</Line>
		<Line>Item9.Link=D:\</Line>
		<Line>Item9.Label=D:\</Line>
		<Line>Item9.Settings=NOEXPAND</Line>
		<Line>Item10.Command=separator</Line>
		<Line>Item11.Command=pc_settings</Line>
		<Line>Item11.Label=Settings</Line>
		<Line>Item11.Icon=%windir%\ImmersiveControlPanel\SystemSettings.exe,10</Line>
		<Line>Item11.Settings=TRACK_RECENT</Line>
		<Line>Item12.Command="C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  --profile-directory=Default --app-id=jjphmlaoffndcnecccgemfdaaoighkel</Line>
		<Line>Item12.Label=YouTube Floating Window</Line>
		<Line>Item13.Link=D:\_Libraries\Desktop\polish2018\TMPSHORTCUTS</Line>
		<Line>Item13.Label=TMP SHORTCUTS</Line>
		<Line>Item14.Link=D:\_Libraries\Desktop\polish2018\new apps folder</Line>
		<Line>Item14.Label=tmp apps folder testing</Line>
	</MenuItems7>
	<CascadingMenu value="0"/>
	<ShowNewFolder value="1"/>
</Settings>
```

I think this is the basic - hopefully I can add more details later. Sorry for the inconvenience.

**Comment by AveYo** [comment]
Can confirm that the exported xml can "garbage" some entries, but that happens on CS 4.3.1 as well!  
I had to text-compare older xml several times. 
Unsurprisingly it was related to 'Create sub-menu' option from right-click. 
To prevent it - don't use that - instead - only drag&drop with Create entries accordingly.

@sjain882: until you fix your issue, might want to consider my [Optimized Configuration.xml](https://gist.github.com/AveYo/f2add193abfb2ddc5963e11273df083b)  (normal dpi)
![preview](https://i.imgur.com/tKkreIj.png)

**Comment by sjain882** [comment]
Thank you very much, will try ASAP

**Comment by AveYo** [comment]
It seems there is some bad caching involved, if you do small adjustments in the file and also rename it, it will increase the chances of successful import.

Note that under Settings my config has a **Reload Explorer** entry. I find that indispensable for CS/OS. Use it once.

That should take care of any lingering issue and allow you to import your personal config afterwards, but there is no guarantee it will work.

**Comment by sjain882** [comment]
@AveYo I've tried restarting explorer and rebooting my pc multiple times, I've mentioned this quite a lot into he posts

**Comment by CTVCAM8** [comment]
Sorry, I seem to have mistaken you wanted to use the Classic 2 column skin called "Windows 10" modded by davestewart .

From your last pictures, it looks like you really want Metro  (7 style menu with different jump/search main)  view,  not the  Classic 2 column with (jump/search submenu) view.
If so then pick " Windows 7 style" in the "Start Menu Style" tab and pick "Metro" skin.


Trying your Menu Settings weird.xml -results-corrupt
Using your " How I want it 4.4.109.xml",  works ok on Open-Shell for me. 
It even works on Classic Shell 4.3.1  Win 10 1809  17763.55 I just had to set to 7 style. :)

**Comment by ibuprophen1** [comment]
@sjain882, I believe that the following one would probably be much easier to do (as it looks like you had probably done much more work than I would have done myself).

1) See if you can completely uninstall the current Classic Start Menu software. 

2) Install the last known Classic Shell software version that your exported xml file had worked on. 

3) Import your xml backup file and make sure that the settings are good from the import. 

Once the Classic Shell is good to go... 

4) Now just install the latest version of the Classic Start software (as normal). This is supposed to install as an update/upgrade that "should/supposed to" carry everything over from the Classic Shell to the Classic Start. 

Hopefully everything went accordingly (as I am hoping it does). 

Once confirmed, just export another Backup xml file and be sure not to mix it up with the others (LOL!). 



~Ibuprophen

**Comment by sjain882** [comment]
@CTVCAM8 has solved my issue.

Setting the _**Start Menu Style**_ to _**Windows 7**_ has fixed my issue.

I still believe that this setting should be exported into the XML though (it seems to have done so for the XML included [here](https://github.com/davestewart/classic-shell-win10)) - leaving the issue open, will close it if Ibuprophen wishes me to (though I think he can do it himself anyway, as he is the dev)

I actually also tried @ibuprophen1 's steps above, but it didn't solve it, but at least his message was not gone to waste. And yes I have now made countless backups, including manual screenshots of all my settings.

Many thanks for your help everyone! Much appreciated, especially to Ibuprophen who remained very helpful and understanding towards a frustrated user (though I tried my best to hide this :P)

It's fixed. All my old options, entries, and layout is restored. https://i.imgur.com/PGPztfF.png

Might just give that Windows 10 theme a try, now that I know what the issue is. I really dig that look.

**Comment by CTVCAM8** [comment]
That is super good news @sjain882 for all the hoops you had to jump through.

For renamed skin xml backups that I have made for myself and others online, the backup xml would pick the correct skin automatically.
It exported the settings correctly.
The only thing I can think is as the xml backup contains every little option click/settings/locations,
 and skins used for classic1/2 as well as 7 style from the past,
 it must have done a bit of a screwup. 
 If I start out with all options reset and pick a default skin, the backup xml is very small (less than 30 lines).
After changing parameters on many things, the backup could end up a couple of hundred lines. More chance for something to go wrong.



About the no icons on 7 style skins. Yes, I think Ivo (the original developer) said it's not possible as it follows the way of the windows 7 start menu.

At one time Dave was planning on making bigger size icons set. Guess new projects got in the way. 3 years have passed by.

What could be possible in comments from  (Gaurav) on the old Classic Shell forum is the use of Segoe UI Symbol or Segoe UI Emoji fonts to make fake looking icons
in the second column. Only problems are there are not enough of them or show up too small to be useful for the ones I tried.
What Gaurav suggests to Ivo is coding be added to take advantage of the Segoe MDL2 Assets fonts (the symbol icons all over Windows 8/10)
by adding support for color fonts which are supported using DirectWrite:

http://classicshell.net/forum/viewtopic.php?f=17&t=5091#p33504

Time ran out. 
Now is your chance to put in a request for the coders at GitHub,
to add the "DirectWrite code to have good looking icon symbols on the second column of the 7 style menu. :)"



postscript about Menu Settings weird.xml

I figured out why the menu would be agonizingly slow to open and then collapse.
Menu Settings weird.xml had carried over <MainMenuAnimationSpeed value="23123"/> settings instead of <MainMenuAnimationSpeed value="250"/>
Changing that timing fixed it.

**Comment by sjain882** [comment]
Interesting, thanks a lot for the info. I actually forgot to check if my taskbar colour was restored (I don't think it was). I was picky about the colour but it was achieved via a combination of a shade of black, enabling windows transparency in settings and some setting in classic start.

Thanks for looking through the XML for me. Your long list of information and help is much appreciated!

**Comment by CTVCAM8** [comment]
Yes, you are correct about the taskbar color. I was only checking what was making it crash on my system.

Anyway, if you are not going to put in a request for correct size glyphs on the second column of 7 style menu,
then I will.  :)
Bye.

**Comment by XenHat** [comment]
Might be worth to compile a build of Open-Shell with special fixes related to settings export that uses the old paths, and do the export on that special build. We could even make a small utility for this.

**Comment by ge0rdi** [comment]
`Open-Shell` imports previous `Classic-Shell` settings on upgrade (this was added longer ago).
It also doesn't modify `Classic-Shell` settings at all.
