### ISSUE TITLE
how do   stop it from starting at  windows satrt up

### ISSUE THREAD

**Issue by Murf1954** [Open-Shell/Open-Shell-Menu#1060]
is there away to stop it from starting at windows start up and still us it i tried revo uninstaller  and click on auto runs and unchecked   it of but it  went back to the  windows 10 tiles can it  run with out starting at  start up

**Comment by CTVCAM8** [comment]
I'm not sure if I understand what you want exactly.
If you want the Windows default menu to start up, and at a later time of your choosing you want Open-Shell to start up,

check out these links: 

http://www.classicshell.net/forum/viewtopic.php?f=7&t=5311#:~:text=Classic%20Shell%3A%20Forum&text=If%20you%20mean%20turning%20off,it%20off%20to%20disable%20it.

or P Brixey and Spokey42 discussion

https://gitter.im/Open-Shell/Lobby?source=orgpage

![Stop Open-Shell from starting up on Win 10](https://user-images.githubusercontent.com/44127216/179369603-d1b23f5e-6793-4b74-aad5-037922675f77.png)


If you like to switch back and forth between the start menus, it's a good idea to have an Open-Shell Menu Settings shortcut on your desktop as Spokey42 did.


If you want to exit Open-Shell, right-click the start button, and select "Exit".
