### ISSUE TITLE
4.4.170 flagged with Russian trojan

### ISSUE THREAD

**Issue by Objectivite** [Open-Shell/Open-Shell-Menu#1062]
Check it on VIRUSTOTAL.COM.

Flagged up 5 times when I ran it 7 days ago.  Still flagged today with 3 engines.

The alerts are very different to the false positives for 4.4.160 and 4.4169.

O.

**Comment by Ibuprophen** [comment]
That website has flagged false positive for this software in various and creative ways. The latest release wasn't injected with anything but modifications to what's already in the software. 

~Ibuprophen
