### ISSUE TITLE
Starting a search with letter which is also an accelerator key triggers the command

### ISSUE THREAD

**Issue by kres0345** [Open-Shell/Open-Shell-Menu#1068]
**Describe the bug**
I wanted to search for a program that starts with 'L', but in danish, the accelerator key for shutdown is also 'L'. This behavior only seems to happen if you start the search quickly after opening the menu.

**To Reproduce**
1. Press windows key
2. Quickly, press the accelerator key for shutdown
3. Watch PC turn off with unsaved work

**Expected behavior**
Start a search using the letter. I think an option to disable the accelerator keys in the menu all-together would be nice, as I would always want to be focused on the search bar, but any fix is welcome.

**Version:**
 - Open-Shell: 4.4.170
 - OS: Windows 10 21H2

**Additional context**
Was playing Factorio at the time :((

**Comment by bonzibudd** [comment]
Related to #447 and #857. I'd still like to see a toggle for the hotkey implemented, or some way to make the behavior less finicky when Search is enabled.

**Comment by ge0rdi** [comment]
Search should be now always focused when start menu is opened in [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build.

Additionally, it is now possible to configure accelerators to trigger only when Alt is pressed (`Require Alt key for accelerators` setting) or disable keyboard accelerators completely (`Enable accelerators` setting).

**Comment by kres0345** [comment]
Awesome! Great work🎉
