### ISSUE TITLE
Classic Shell and/or Explorer hangs on open?

### ISSUE THREAD

**Issue by RalfRoemling** [Open-Shell/Open-Shell-Menu#107]
I've installed the last version of OpenShell recently and noticed something weird: When opening it via _Win-Key_ or _Strg-Esc_ at first it works but after sometime starts to crash irregularily.

When this happens the Taskbar isn't responding anymore too and is only showing the "working"-icon. After some time the OpenShell-StartIcon is back in place and function restored.

Anybody got a clue what's happening here? Can I add further info to assist?

System is Win10x64.1703 (Build15063.1387)

**Comment by RalfRoemling** [comment]
Hi ge0rdi, interestingly since procdump is running no crashes... have to investigate and will report back.

**Comment by war59312** [comment]
Same here on 1803.

KB4462933(https://support.microsoft.com/en-us/help/4462933/windows-10-update-kb4462933) appears to be the cause. Uninstall KB4462933 and no more issues.
