### ISSUE TITLE
Warning 1946. Property 'System.AppUserModel.ID' for shortcut 'Classic IE Settings.lnk' could not be set.

### ISSUE THREAD

**Issue by Kiff4Free** [Open-Shell/Open-Shell-Menu#1070]
During installation i get "Warning 1946. Property 'System.AppUserModel.ID' for shortcut 'Classic IE Settings.lnk' could not be set."

What could be the solution?

Edition	Windows 11 Home Single Language
Version	21H2
Installed on	‎22/‎10/‎2021
OS build	22000.778
Experience	Windows Feature Experience Pack 1000.22000.778.0

Open-Shell Menu 4.4.170

**Comment by Ibuprophen** [comment]
@Kiff4Free, This is typically an error tied to Windows 7, but it may/might happen (though rarely seem) in later Windows OS releases. 

This is actually not something serious and can just be ignored. 

This error only means that some properties could not be set on shortcuts the installer attempts to create.

I wouldn't worry about this error as I recall seeing this error once, quite some time ago, when I had Windows 7 Professional and just ignored it and nothing personally resulted in this. 

~Ibuprophen
