### ISSUE TITLE
https links don't work but http does

### ISSUE THREAD

**Issue by Xiper-Starchild** [Open-Shell/Open-Shell-Menu#1072]
Running links via the start menu by typing them in yourself only works if the link is regular http and not http with ssl.

1. Open start menu
2. Type a link with only http
3. Icon shows that you can run the link
4. Type a link with https
5. Doesn't give the option to run the link

The ability to run https links via the start menu.

 - Open-Shell: 4.4.160
 - OS: Windows 10 20H2

**Comment by blackcrack** [comment]
Boy,
load the latest release :  
https://github.com/Open-Shell/Open-Shell-Menu/releases

and close this issue..

and by the way, we (the OpenShell community like you) need programmers ..

best
