### ISSUE TITLE
Release page has wrong current version

### ISSUE THREAD

**Issue by ToddAndMargo** [Open-Shell/Open-Shell-Menu#1073]
https://github.com/Open-Shell/Open-Shell-Menu/releases/
Shows the current release as 4.4.160
The current release is actually 4.4.170

Please fix.

![Screenshot_2022-07-13_14-16-27](https://user-images.githubusercontent.com/843205/178838238-e5ae2c69-a27c-4ca6-b4d9-d63c7f8c31cb.png)

**Comment by Ibuprophen** [comment]
I see that it's correct with showing the latest release of 4.4.170...

~Ibuprophen

**Comment by ToddAndMargo** [comment]
Awesome!  Thank you for fixing it!
