### ISSUE TITLE
SUGGESTION: "Activation" watermark removal feature

### ISSUE THREAD

**Issue by lacy23** [Open-Shell/Open-Shell-Menu#1077]
I've got this weird bug with Windows 10 where even though it's been activated, it still previews the "Activate Windows" watermark after like a couple hours of use. It's been really frustrating and there's nothing I could do to remove it. I know there's a lot of "Activate Windows watermark removal" apps but I'd rather have you guys to implement a side-feature which could possibly remove it somehow. 
<3 
(Also I'm not quite sure if this is already a feature because I'm not on the latest version so idek if it's really there.)

**Comment by XenHat** [comment]
Periodically setting `HKEY_CURRENT_USER\Control Panel\Desktop\PaintDesktopVersion` to `dword:00000000` should solve this issue. Fairly easy to implement.

In the meantime, you can use the following Registry import (save as i.e. `DisableWatermark.reg`:

```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Desktop]
"PaintDesktopVersion"=dword:00000000
```

**Comment by lacy23** [comment]
I just checked and it is set to 0. I do recall doing this thanks to one of the tutorials a friend sent me. I'll run the .reg either way and see if it makes any difference. Will post an update as well! :)

**Comment by XenHat** [comment]
If that doesn't turn it off, there's something very wrong going on with your install... I would recommend the usual virus checks, corruption checks (`sfc /scannow`), etc.

**Comment by Ibuprophen** [comment]
@lacy23, This happened to my daughter's laptop once. 

I attached the following  zip file with a simple batch file in it that did the trick for me. 

[WatermarkDisabler.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/9128710/WatermarkDisabler.zip)

Unzip the file and locate the "WatermarkDisabler.bat" file then Right-click on it and select the on “Run as administrator” option. 

A command prompt window will quickly open then closed itself. 

Now restart your laptop or desktop and the Watermark should now (hopefully) be gone. 

Good Luck! 

~Ibuprophen

**Comment by lacy23** [comment]
UPDATE: It did come back and I'm sure it has something to do with the install but I'm really not willing to activate Windows again if that's what it's gonna come to.  

@XenHat I'm gonna run "sfc /scannow" and post the results tomorrow, it's been like an hour and I'm off to bed but I'll keep my PC on.

@Ibuprophen Thanks, I'll be sure to run this as well and see if it does the job hopefully. 

It means a lot, thank you guys so much! :)

**Comment by blackcrack** [comment]
@lacy23 , take [Winaero Tweaker](https://winaero.com/winaero-tweaker/) and the Ratiborus KMS and your issue is history..
and by the way, this regkey and your issue is not a OpenShell thing and something like watermark from MS-Windows is it also not..
It's a nice thing if @Xenhat and @Ibuprophen have try your help, but it's not really a Issue of OpenShell.
I hope WinAero Tweaker helps you, also by some adjusting in Windows :) but now could you by self close this theme, you have 
a post & close button by anwser this post :) thy for you understand :)

**Comment by lacy23** [comment]
UPDATE: I think the sfc /scannow did the job, it seemed to have fixed something in the system. I left my PC on for the entire day and it never showed up even once. 

@blackcrack this seems to be helpful as well, I'll keep that in mind and make use of it if the watermark comes back at all. Thank you all so much for your help, it truly means a lot! :)
