### ISSUE TITLE
Folders come back to This PC after removed if opened from start menu

### ISSUE THREAD

**Issue by K4sum1** [Open-Shell/Open-Shell-Menu#1084]
I'm using Windows 8,1, and I use OldNewExplorer to bring back the 7 styled explorer with Libraries and all. This includes removing the folders from This PC. However, if I open Documents, Downloads, etc from the Open Shell start menu, whatever folder I opened appears under This PC until the opened window is closed. I can bypass this by telling Open Shell to open the libraries versions of the folders instead, but I can't seem to get Downloads to open under the favorites like it does on 7. I'm stuck with it having the Downloads folder appear under This PC.

**Comment by ge0rdi** [comment]
Please, provide exact step-by-step description of your issue and how to replicate it.
Add screenshots for clarification.
Feel free to reopen then.

**Comment by deepspaceaxolotl** [comment]
I have the same issue, I believe it's exactly like the one described [here](https://www.tenforums.com/general-support/189274-downloads-link-being-placed-pc-navigation-bar.html) (with screenshots). I can replicate it by going to Downloads from the Quick Access menu, up to This PC, then using the back button to go back to Downloads, whereupon it shows up under This PC. I'm having a similar issue with Desktop, which I also have pinned to Quick Access and can replicate in the same way.

Would really appreciate having this issue reopened! Hopefully there's some way to fix this with Open Shell, the suggested solution in that thread I linked makes the Downloads folder disappear from the Quick Access menu, too.

**Comment by K4sum1** [comment]
I've just worked around it by using only the This PC folders. I have libraries and favorites disabled. I think it looks cleaner this way.

![Image](https://github.com/user-attachments/assets/380b3003-3431-4f59-ab0a-342af2530fd6)

**Comment by deepspaceaxolotl** [comment]
Could this be reopened? Hopefully my comment above has enough details to replicate it.
