### ISSUE TITLE
Classic Explorer no longer working on Windows 8.1

### ISSUE THREAD

**Issue by atesin** [Open-Shell/Open-Shell-Menu#1087]
**Describe the bug**
Classic **Explorer** (not "classic **internet** explorer) is not working in windows 8.1 ...  i tried many configurations in "settings for classic explorer" but is futile

**To Reproduce**
1. just open any windows explorer window, and classic toolbar won't show up
![image](https://user-images.githubusercontent.com/8086106/183524070-1364fa88-8303-488f-b0c2-2ee40ff85ad4.png)

**Expected behavior**
"windows explorer" windows with classic explorer toolbars (screenshot found elsewhere)
![](https://www.groovypost.com/wp-content/uploads/2012/11/Classic-Explorer.png)

**Version:**
 - Open-Shell: 4.4.170
 - OS: windows 8.1 pro x64

**Comment by CTVCAM8** [comment]
I tried it on Windows 8.1 Pro with Media Center version 6.3 (Build 9600) x64 fully updated
with Open Shell 4.4.170
It works.

The help file says "The new toolbar doesn’t show up in Explorer automatically after installation"
Mine did.

There's at least one way in the view tab that enables it (see picture).

![Classic Explorer Bar Win8 1](https://user-images.githubusercontent.com/44127216/185040422-8515a4f9-7a6e-4201-8bee-0a52968212a2.png)


If that doesn't work, try reinstalling.

**Comment by atesin** [comment]
oh my...   you saved my life...  WHAT A HIDDEN AND OBSCURED CONFIGURATION !!!

i was pulling my hair for months! .. reinstalled classicshell countless times and versions!, searching for help and support in vain .....  please somebody from dev team, document this in a more visible place, and then close this issue

**Comment by CTVCAM8** [comment]
I found Gaurav's link talking about it using Windows 7,8,8.1,10 on Classic Shell:

https://coddec.github.io/Classic-Shell/www.classicshell.net/forum/viewtopica7ee.html?f=8&t=1580

**Comment by atesin** [comment]
> I found Gaurav's link talking about it using Windows 7,8,8.1,10 on Classic Shell:
> 
> https://coddec.github.io/Classic-Shell/www.classicshell.net/forum/viewtopica7ee.html?f=8&t=1580

yeah, obscured...  not easily findable
