### ISSUE TITLE
Show Desktop button (+more) broken

### ISSUE THREAD

**Issue by sayakamane** [Open-Shell/Open-Shell-Menu#1089]
Sorry if this is a known issue, I am tired and couldn't find anything.

Using "7 for 10" by 2of3 for WindowsBlinds + Classicshell vista themed breaks the "show desktop" button as well as the pop-up menu and the opened applications transparency. 

Once again, I'm sorry if this is already known. just couldn't find any information on how to fix it as it's very confusing to a nub like me. Thank you!
![image](https://user-images.githubusercontent.com/110994679/183939395-3a81dd55-b1b8-4b06-95aa-80a2d862d4c9.png)

**Comment by YesTrustMe** [comment]
Please add more info please like including your OS version. This would be helpful for everyone.
