### ISSUE TITLE
Some rogue release uploaded?

### ISSUE THREAD

**Issue by ltGuillaume** [Open-Shell/Open-Shell-Menu#1101]
A day ago, I got a notification for a new version (dated August 13th). I updated, but the version number is lower than the current 4.4.170 (it's 4.4.8). But now it's gone from the Releases page again.

What's going on?

**Comment by Ibuprophen** [comment]
I was removed by someone (nor has anyone reached out to me) as a Contributor in the Open Shell development. 

I am now (sadly) unable to provide any developmental contributions to this. 

I can only do my best to provide what guidance I can to help others. 

The 3 developers here are @coddec, @ge0rdi & @XenHat. 

Good Luck! 

~Ibuprophen

**Comment by ltGuillaume** [comment]
> I was removed by someone (nor has anyone reached out to me) as a Contributor in the Open Shell development.

Sorry to hear that. Are these two things connected somehow, or what do you mean?

**Comment by LinuxOnTheDesktop** [comment]
@ltGuillaume

About the release: I am merely a user, but I take myself to know, from [here](https://github.com/Open-Shell/Open-Shell-Menu/issues/1094), the following. The release was mis-packaged. A new, corrected release has been delayed because of bandwidth problems.

**Comment by Ibuprophen** [comment]
@ltGuillaume, I had released a package via Appveyor, but something went wrong in Appveyor that caused issues with installation and the release was pulled till it could be resolved. 

Before I could reach out to the other individuals regarding this, one of them decided to pull me from the team. 

I have no knowledge of what's going on at this point in time. 

Sorry my friend... :-((

~Ibuprophen

**Comment by ge0rdi** [comment]
> What's going on?

The wrong release was made by mistake.
It is already removed by now.

**Comment by ltGuillaume** [comment]
Ah I didn't look through the closed issues before creating this one (I just _assumed_ that this issue was too recent to be closed), my bad. @LinuxOnTheDesktop Thanks for linking the closed issue, I've read through it.

> but something went wrong in Appveyor

Well, seems like you entered a wrong version number to use.

Anyway, thx for the explanations.

**Comment by Ibuprophen** [comment]
I had uploaded the v4.4.200 to my File Host Account for others to test to see if the installation error is resolved (hopefully). 

https://www.androidfilehost.com/?fid=15664248565197204249

I had just compressed it to a zip file to help reduce the size. 

[Please Note that AFH is free for those not familiar with this server.] 

~Ibuprophen

**Comment by blackcrack** [comment]
the original File is them of the original Repository 
and this is at moment 4.4.173 !!
https://ci.appveyor.com/project/passionate-coder/open-shell-menu/build/artifacts
and not from an foreign Repository

**Comment by ge0rdi** [comment]
> I had uploaded the v4.4.200 to my File Host Account for others to test to see if the installation error is resolved (hopefully).

Official versions are available via GitHub releases page (or AppVeyor in case of nightly builds).
We do not recommend to download/install from unofficial sources.
