### ISSUE TITLE
Need more explicit control over text size

### ISSUE THREAD

**Issue by pderocco** [Open-Shell/Open-Shell-Menu#1110]
I have a 17" laptop with a 3840x2160 display. The Display Scaling in Windows is set to 150%, which still leaves text quite small, but if I wanted big text I wouldn't have wasted money on that display. The text in the Start menu, however, is much larger than the text everywhere else. Changing "Override system DPI" over the range from 96 to 480 only varies it a little bit.

If there is some reason that the 5:1 range of "Override system DPI" doesn't produce a 5:1 variation in text size, then we need an alternative way to specify the sizes. I don't really care how it is specified, as for me it is a "set-it-and-forget-it" option.

This shows the huge difference between the text size in the Start menu and the text size in the Open-Shell settings dialog. The smaller size is what I want.

<img width="917" alt="Untitled" src="https://user-images.githubusercontent.com/19559397/185775964-1e5eb0f0-a1f0-4de1-8db0-da43bf35f8f7.png">

**Comment by blackcrack** [comment]
you be in able to programming,
write a patch for it to make the menu scaleable and make it possible for change the Font (/Size) in the Skin for overwrite,
would be a cool idea :)  
maybe make the both windows more smaller for have a customizing menu at bottom..
did you take the latest nightly 4.4.173 ? i have download it and post it in the Discussions part ...
This Tab/part is now with 2 Inframes , check it out..

**Comment by CTVCAM8** [comment]
Something isn't tracking correctly.

Could be related to Windows system options like Ease of Access display settings "Make text bigger", 
or the % scaling not tracking with Open-Shell. 

Restarting Open-Shell with "Override system DPI" back to the default setting "0", so it tracks the 150% system size should work.

If that doesn't do anything,
you could try the "Metallic" skin, and adjust the built-in "Text size" option to say "8".

If that does not work either, something really is buggy.

**Comment by blackcrack** [comment]
![grafik](https://user-images.githubusercontent.com/7925717/186081794-af24eb5e-3647-410e-a36e-10e771655542.png)

![grafik](https://user-images.githubusercontent.com/7925717/186081823-ce9fda77-b4df-4fc2-803b-8c45bde9e386.png)

**Comment by bonzibudd** [comment]
In the Classic theme, Open-Shell follows the font information specified by Windows, and it does not override the size like other skins. So because of that, when you use "Override DPI," the font size doesn't change because the system font hasn't changed.

Are any other apps behaving in a similar way? It's possible that Open-Shell is using an uncommon font metric to determine the size, so it still looks normal in most interfaces.

**Comment by ge0rdi** [comment]
> In the Classic theme, Open-Shell follows the font information specified by Windows, and it does not override the size like other skins.

That's right.
Since there is no font specified in `Classic Skin`, we are using default system font.
But we don't scale font size according to DPI (whether system/monitor one or the override in settings).

Will fix that soon.

**Comment by ge0rdi** [comment]
Original fix in 4.4.188 wasn't correct, so we are working on (hopefully) proper fix.

**Comment by ge0rdi** [comment]
4.4.189 should contain proper fix.
