### ISSUE TITLE
Control Panel items in Alphabetical Order

### ISSUE THREAD

**Issue by BlueDrakoPT** [Open-Shell/Open-Shell-Menu#1111]
Open-Shell 4.4.171 sorts all items from control panel in alphabetical order.  (display as menu selected)
Version 4.4.172 and up create 2 items groups in alphabetical order... why?

Tested in windows 10 21H2 and windows 11 22H2.
![Snap2](https://user-images.githubusercontent.com/93726676/185796485-c2a27db1-53f6-4696-885d-a582802b434b.jpg)

**Comment by blackcrack** [comment]
did you try to go on an entry, right mouse key and look the menu of Mouse 
"automatic Sorting"
"Sorting now" 
should you see in the right Mouse menu..

if this is soulution , could you use the Comment&Close Button :)

best

**Comment by BlueDrakoPT** [comment]
That's the problem: there's no "automatic sorting" in right click menu.
![Snap1](https://user-images.githubusercontent.com/93726676/185800978-2ed8ef09-2e0a-423f-8bfe-f10091ec415b.jpg)

**Comment by blackcrack** [comment]
well, Win7 Pro ..  
![Screen 0000-](https://user-images.githubusercontent.com/7925717/185806831-5379728e-57ea-4e89-a624-9fd52d54fbd3.jpg)
![Screen 00001-](https://user-images.githubusercontent.com/7925717/185806837-0de19899-87ac-4968-b789-64e0826c7d71.jpg)

**Comment by Avrution** [comment]
Can confirm the issue.

**Comment by blackcrack** [comment]
@BlueDrakoPT 
if this issue resolved, please klick on Comment+Close Button

![Screen 00000](https://user-images.githubusercontent.com/7925717/185914929-35a451d6-d927-433d-bc2f-65a1029fd4ec.jpg)

**Comment by BlueDrakoPT** [comment]
The problem is "ONLY" in Control Panel. Other Programs and Program Folders can be sorted in settings. Version 4.4.171 doesn't have the problem, only 4.4.172 and up.

**Comment by Avrution** [comment]
Oddly enough, it seems that folder doesn't even get modified when changing those options.  It is always in the same order, even when picking Z - A.

**Comment by Thorbeast61** [comment]
> The problem is "ONLY" in Control Panel. Other Programs and Program Folders can be sorted in settings. Version 4.4.171 doesn't have the problem, only 4.4.172 and up.

I confirm this.

**Comment by ge0rdi** [comment]
The issue was caused by https://github.com/Open-Shell/Open-Shell-Menu/commit/bb26cec0ecbdca0350e7c1474eec32954d18d14d.

Looking into it.

**Comment by ge0rdi** [comment]
Guys, can you test with this build?
https://ci.appveyor.com/project/passionate-coder/open-shell-menu/builds/44726481/artifacts

It should fix the sorting issue.

**Comment by BlueDrakoPT** [comment]
YES! It's fixed. Thank you.
