### ISSUE TITLE
Open-Shell start menu permanently crashing under Win 11 when pushing the button, especially after unlocking

### ISSUE THREAD

**Issue by schildzilla** [Open-Shell/Open-Shell-Menu#1123]
**Describe the bug**
When my laptop (running Windows 11) is locking itself automatically (not standby, only deactivate), then after unlocking the start menu becomes inoperable. But this issue also often appears under normal usage.
When pushing the start button, nothing happens.
After several clicks, the start menu crashes and reloads. But this doesn't solve the issue. It crashes again when I try to open it.
Workaround which is working sometimes: After a crash directly right click on the Open Shell Icon and close the program, then reopen it  and sometimes it works again.

**To Reproduce**
1. Lock the computer and unlock it again
2. Click on start
3. Must be crashed now. No menu appears and after multiple click a restart of the start menu is performed, which doesn't solve the issue.
4. Can also happen under normal usage

**Expected behavior**
As it mostly appears after using the lock screen, maybe this is a cause? But it also happens when not entering the lock screen.

**Version:**
 - Open-Shell: 4.4.175
 - OS: Windows 11 21H2 (Build 22000.856)

**Comment by blackcrack** [comment]
At the Headpage : https://github.com/Open-Shell/Open-Shell-Menu
Features
    Classic style Start Menu for Windows 7, 8, 8.1, 10

who can read is clear in vantage !
Or, you search for an Programmer who make it compatible !

**Comment by PraetorAngel** [comment]
To clarify, this only happens in Open-Shell-?  It is unclear if the windows start menu works or not under the same circumstances, it might be relevant.
I would do the following to rule them out: uninstall-reboot-reinstall with a fresh copy, sfc /scannow, dism /online /cleanup-image /restorehealth, and see if there's a command to reinstall the lock app using powershell.

**Comment by Andynam0** [comment]
I'm getting the same in Win10 - after unlocking I hit ctrl+esc or the windows key and explorer.exe restarts and everything starts working well - Without openshell no issues. If I press shift+the startmenu explorer also restarts with openshell installed.  
OpenShell 4.4.170 - Classic Style (in case that makes a difference)
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19044 N/A Build 19044
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free

**Comment by schildzilla** [comment]
This only happens in Open-Shell.
At the start it worked very well.
This issue just appeared after a while. I didn't change anything.
Reinstall didn't work either.
The issue is gone for now, after I've deactivated "General behavior" > "Delay loading of icons" which eliminated the issue, even after reactivating the function.
I did a complete settings reset later just to be sure and left the function deactivated.
No more issues for now under Windows 11.

Andynam0: Can you try to deactivate "Delay loading of icons" and report back?

**Comment by Andynam0** [comment]
I've unchecked it, I'll report back, so far so good though! (after restart)
