### ISSUE TITLE
Changed options are not displayed in bold (Classic Explorer)

### ISSUE THREAD

**Issue by w64bit** [Open-Shell/Open-Shell-Menu#1135]
**Describe the bug**
Changed options are not anymore displayed in bold in Classic Explorer

**Version:**
 Open-Shell 4.4.177
 Windows 10 21H2, 22H2, x64

**Additional context**
4.4.169 it's OK

**Comment by ge0rdi** [comment]
Can you provide a screenshot for clarification?

Is the setting displayed as bold if you change it to other than default value?

> 4.4.169 it's OK

What about latest official version 4.4.170?

**Comment by ge0rdi** [comment]
Hmm, I think I've got it.
Recent (rather unfortunate) change caused settings that were manually changed to _default_ value to be not highlighted.

I will revert the change (see #1138).

**Comment by blackcrack** [comment]
@w64bit 
test it out if works, close this issue :)
https://ci.appveyor.com/project/passionate-coder/open-shell-menu/builds/44742237

big thanks @ge0rdi 

best
