### ISSUE TITLE
OpenShell Menu block Windows11 explorer to start since today (15.09.2022) Windows update!

### ISSUE THREAD

**Issue by uom42** [Open-Shell/Open-Shell-Menu#1144]
OpenShell Menu & Classic Shell StartMenu also, block Windows11 explorer (desktop) to start since today Windows update.

After user logon we will see black screen.
Yo can start TaskMrg and start any other app from it except explorer (Desktop).

Windows eplorer for disk/folder (not desktop) may be started also manually.

tested with OpenShellSetup_4_4_170.exe & ClassicShellSetup_4_3_1.exe

after uninstall OpenShell / ClassicShell and starting desktop manually (explorer.exe) - desktop appears.

ver: Microsoft Windows [Version 10.0.22000.978]

**Comment by kotenok2000** [comment]
I have ran ver in command line and it says  Microsoft Windows [Version 10.0.22000.978] 
i think your version is outdated.

**Comment by uom42** [comment]
> Works for me. I have ran ver in command line and it says Microsoft Windows [Version 10.0.22000.978] i think your version is outdated.

Sorry, my old version info was mistake.
ver: Microsoft Windows [Version 10.0.22000.978]

**Comment by blackcrack** [comment]
[https://defenderui.com](https://defenderui.com)
therewith have you a good surface for Defender and be in able to ignore the StartMenu.exe

**Comment by uom42** [comment]
> therewith have you a good surface for Defender and be in able to ignore the StartMenu.exe

In case you didn't know, Defender has its own customization UI.
I added StartMenu.exe and whole it's folder to WindowsDefender exclusions, but it not helped.

if you wanted to say that the program you recommend has some special setting for this case - it would be great of you to point DIRECTLY TO THIS SETTING, and not just advise some obscure program to do something unknown...

**Comment by blackcrack** [comment]
a great answer to see what for an Character you have .. well.. the same to you.. you could directly show the configuration via a screenshot without messing around with it and someone trying to stand there badly. i have after all or at last tried to bring a solution .. and thank you for your statement..

**Comment by blackcrack** [comment]
and the peoples have not the ass in the pants to delete the Comments with his real name :+1: 
wow.. must i let stay me badly ? if, then delete the both Comments Mr. @Open-Shell

**Comment by uom42** [comment]
> you could directly show the configuration and point it out via a screenshot without messing around with

What configuration should I show?
I'm not a telepath and I can't read your thoughts, so take the trouble to express them all the same.

**Comment by ge0rdi** [comment]
@uom42 
Do you still have the issue?

**Comment by uom42** [comment]
> @uom42 Do you still have the issue?

Sorry, it happened that I upgraded my PC and reinstalled the OS. On the new OS, no problems so far.
