### ISSUE TITLE
Windows defender false positive? 

### ISSUE THREAD

**Issue by afk789** [Open-Shell/Open-Shell-Menu#1145]
Windows Defender said it detected a Trojan in Open Shell Nightly version 4.4.178 today. 
![Screenshot (296)](https://user-images.githubusercontent.com/59767288/190724694-d83b22d9-b727-4ce3-a7c8-a7b3f69e7bef.png)

**Comment by CTVCAM8** [comment]
Yes, similar situation

Windows8.1 fully updated 2022-09-16 
Windows Defender Up to date.

Downloaded OpenShellSetup_4_4_178.exe 
Picked Windows Edge to "Keep" and "Keep anyway".
Picked SmartScreen to "Run anyway".

Started full Open-Shell installation.
Picked "Do not close applications. A reboot will be required."
A window pops up showing  Malware has been found.
Took a screenshot of Defender.
Rebooted
Did Quick scan- No threats detected.
Did a custom scan of download folder with OpenShellSetup_4_4_178.exe still there. No threats.
Open-Shell seems to work 
![Malware found](https://user-images.githubusercontent.com/44127216/190829540-f3cbbca9-d310-4049-aca7-47dcc230e9e0.png)
![Win8 1 updates](https://user-images.githubusercontent.com/44127216/190829552-2a7e3f20-6538-4602-9719-c3bdbcb6f38d.png)

**Comment by rjodwyer** [comment]
Windows Defender ATP detecting as Sabsik malware in the update.exe
![open-shell-fp](https://user-images.githubusercontent.com/29014100/190846127-ffc9c9bf-3945-406e-a63c-b06bbb78f88a.png)

**Comment by ge0rdi** [comment]
Please, report this false-positive to Microsoft, so they can fix their Defender detections.
There is no malicious code in `Open-Shell`.

**Comment by CTVCAM8** [comment]
OK.
I submitted OpenShellSetup_4_4_178.exe to Microsoft
as a false positive when using Windows 8 Defender.
I didn't have any problem installing it on Windows 10.

https://www.microsoft.com/en-us/wdsi/filesubmission
