### ISSUE TITLE
Openshell crashes (and doesn't restart correctly) if using the search

### ISSUE THREAD

**Issue by jesses408** [Open-Shell/Open-Shell-Menu#1147]
**Describe the bug**
If using the search to try to find a program, openshell almost always crashes. Sometimes it restarts itself, but the restarted instance won't work right - some buttons don't work and the right side notification area is missing icons. The computer has to be restarted to fix it.

**To Reproduce**
1. Click start button
2. Start typing a few letters in search
3. Openshell crashes

**Expected behavior**
1. Openshell does not crash on search
2. If crashing, when restarting itself, it should bring itself to a fully working state

**Version:**
 - Open-Shell: 4.4.175 (although same issue was observed in 4.4.170)
 - OS: Windows 11 pro for workstations, version 21H2, OS build 22000.978

**Comment by ge0rdi** [comment]
Can you confirm it happens also with latest pre-release (since you are using pre-release already)?

If so, then please provide crash dump obtained using this [guide](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-create-dump-on-Windows-Explorer-crash).
