### ISSUE TITLE
Right-Clicking start menu items creates empty context menu

### ISSUE THREAD

**Issue by Hoanzn** [Open-Shell/Open-Shell-Menu#1150]
Observed with Window 11 Pro 22H2 on OpenShell 4.4.170:
o Goto OpenShell Start
o After Start menu has opened, right-click an installed executable
o OpenShell shows an empty context menu without lines, 
   with only two vertical arrows without a visible scrollbar.
Expected behavior:
o Context menu with the usual properties and features
   associated with an executable

**Comment by CTVCAM8** [comment]
The default context menu works for me.
Have you run "sfc /scannow" in Command Prompt as an Administrator?

![Default context menu Win11 22H2](https://user-images.githubusercontent.com/44127216/192160148-4337b1cc-c3bb-4e6b-9511-cfcf92f6e499.png)


I don't know about having a scrollbar.
Wasn't that a Windows bug with earlier Windows 11 version?

https://www.askvg.com/bug-scrollbar-in-context-menu-crashes-windows-11-explorer/
