### ISSUE TITLE
Add an command to reload settings from registry on-the-fly?

### ISSUE THREAD

**Issue by dominichayesferen** [Open-Shell/Open-Shell-Menu#1157]
**Is your feature request related to a problem? Please describe.**
I'm working on a pack that will allow users of Windows 8.x to make Windows 8.x look and feel more like Windows Vista, and as part of it Open Shell is used to provide the Start Menu. However, I also want to be able to change the theme, menu style, and Start Button on the fly whenever desired by the user or appropriate to a theme change, but as far as I know the only way to make Open Shell have settings be applied is 1. doing it from Open Shell settings, 2. restarting Explorer (interrupts theme changes), or 3. using the .xml import command (which nukes ALL other settings, which is NOT what I want to do).

If this were added, I'm pretty sure it would also help multiple other projects, too, in the same way. 

**Describe the solution you'd like**
I'd like to be able to, once I've committed changes to Open Shell's Registry values, tell Open Shell, programatically, to reload settings from Registry, potentially via an EXE command argument (`/reapplySettings`?). 

**Describe alternatives you've considered**
The only other programmatical alternatives to fulfil this configs-reload I've found are restarting Explorer, which is a no-go since it handles theme changing meaning the theme might not get completely changed (plus means waiting around for Explorer to start up again), and using the EXE command argument to load from XML (which nukes every other setting change made, which is NOT what I want to have happen).

**Additional context**
N/A

**Comment by ge0rdi** [comment]
@dominichayesferen 
Could you, please, test with build from PR #1158?
Note that it is CI build not meant for daily usage.

Running `"C:\Program Files\Open-Shell\StartMenu.exe" -reloadsettings` should reload settings from registry.
