### ISSUE TITLE
Win-7 style menu shows "Windows Shell Experience Host" even when repeatedly removed

### ISSUE THREAD

**Issue by PanoptesDreams** [Open-Shell/Open-Shell-Menu#1164]
### Describe the Bug
'Windows Shell Experience Host' menu item keeps reappearing in the Win-7 styled menu on semi-default settings. The item has been removed (by me) a lot and it keeps coming back.

### To Reproduce
1. Be on Windows 11
2. Use OS as normal
3. 'Windows Shell Experience Host' menu item will slowly make its way up the frequent items list

### Expected behavior
Menu Item *right-click* 'Remove from this list' removes item from list and prevents item return

### Screenshots
![image](https://user-images.githubusercontent.com/55162814/194693334-2f15371c-63c0-4f78-80fe-7a436fc895c7.png)

### Version:
 - Open-Shell - 4.4.170
 - OS: Windows 11 22621.608

### Additional context
It's a background item that should be hidden regardless

**Comment by bonzibudd** [comment]
I have this problem as well. The item should be exempted from appearing in the menu at all.

**Comment by ge0rdi** [comment]
@PanoptesDreams 
Could you, please, attach log created using this [guide](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-obtain-advanced-Open-Shell-Menu-log)?
It should help us to see what exactly was enumerated in frequent list and from where eventually.

**Comment by bonzibudd** [comment]
[StartMenuLog.txt](https://github.com/Open-Shell/Open-Shell-Menu/files/10145273/StartMenuLog.txt)

Here's the log file with ShellExperienceHost.

**Comment by ge0rdi** [comment]
Thank you.

It seems to be from _frequent programs_ that Win10+ tracks.
It should be easy to add exclusion for `Windows Shell Experience Host` in code that does the enumeration.
