### ISSUE TITLE
Start Menu no longer opens from Windows key in latest Insider builds

### ISSUE THREAD

**Issue by Irastris** [Open-Shell/Open-Shell-Menu#1165]
After updating my Windows 11 Insider build, Open-Shell no longer opens from the Windows key alone. Shift+Windows or a custom combo still work.

**To Reproduce:**
1. Update to latest Windows 11 Insider
2. Try to open the start menu with the Windows key

**Version:**
 - Open-Shell: 4.4.170
 - OS: Windows 11 Pro Insider Preview 22H2 v25217.1000

**Comment by CTimmerman** [comment]
On my Microsoft Windows [Version 10.0.22000.1098] according to `ver`, Open Shell Menu only opens on Windows key, not the Start button. Does the install (of only that component) require a reboot?

**Comment by Irastris** [comment]
> Open Shell Menu only opens on Windows key

That has been the case since Windows 11's release unfortunately, and now neither work. I've given up on Open-Shell as the project seems to lack any contributors capable of solving for Windows 11's changes given its mainstream availability for over a year now and leaving this issue open in the face of that seems pointless.

**Comment by gcatellani** [comment]
Problem reoccurs for me on Win 11 Version 10.0.22621.1992. Pressing the Windows key opens the Win11 start menu. Shift+Windows key opens OpenShell.

**Comment by ge0rdi** [comment]
@gcatellani 
You need to use latest `Open-Shell` build on Win11.

**Comment by gcatellani** [comment]
@ge0rdi Thank you, it works. I feel stupid for not having simply followed the link to your fix/commit and having checked the version, but I was kind of expecting that to have been integrated into the "stable" release already or be a new bug as it did work until recently.
