### ISSUE TITLE
[Feature request / Bug] Keyboard Accelerators are triggered without ALT keypress. 

### ISSUE THREAD

**Issue by Hadden89** [Open-Shell/Open-Shell-Menu#117]
A key press could be treated as a keyboard accelerator instead as part of the search.
An option to disable the function - which I don't use - will be nice :)

**Comment by AveYo** [comment]
You should use **Show search box** with **Access normally** and **Selected by default** checked.  
That way, I don't find an issue with Tab

**Comment by Hadden89** [comment]
Ok, the issue is becoming awkard. How I replicated:

1) Press start menu button;
2) Menu will be opened;
3) Press a number or a letter on the keyboard;
4) Some links will have an underlined letter (this should happen **only** if you press ALT before a letter).
5) As my OpenShell is localized, **shutdown** is **Arresta**. 
When I press A on keyboard, is treated as ALT+A (shutdown command).

I hope there's a settings to prevent this or to disable the ALT + <key> function in openshell.

**Comment by Hadden89** [comment]
@AveYo Well, now it works as expected, is what counts ^^
I left the replication procedure just in case someone else see a similar issue.
Actually I tried various combination but still seeing that alt highlighting but for what I know could be also an awkard w10 bug.
Obviously, I'll check your optimized profile too. OpenShell is built around optimization, after all :P

**Comment by Sam-Hall** [comment]
I've been using Classic Shell for years and now Open Shell, always with the "Select by default" option. I want to confirm that even with this option, sometimes accelerators still get triggered. Maybe the search box gets focus slightly after accelerator events start listening or maybe there's a race condition at play. Either way, an option to disable the accelerators entirely or require Alt to be pressed in conjunction would be much appreciated. I don't think I've ever used the accelerators on purpose, but they have triggered on accident from time to time.
