### ISSUE TITLE
Out of date links in Help file; lack of clear navigation

### ISSUE THREAD

**Issue by acrowland** [Open-Shell/Open-Shell-Menu#1173]
Hello,
I wanted to download the latest stable release of Open Shell, and struggled.
1. I typed Open Shell into the Open Shell search bar, pointed to Open-Shell Help. Selected Useful Links. All of them are for Classic Shell. Using the most obvious one, I got a page saying it was no longer maintained, as of 2017!
2. I tried openshell.org. Not the right site.
3. By clicking the Open Shell Settings icon in File Explorer (something not all users will actually have), I clicked the Open-shell Homepage link. It took me to GitHub, which is apparently the main shop window for the product now. And there I see “If you just want to use it or looking for setup file, click here to download” and a green Download button, with ‘Nightly builds’ below that. I click the big button and am taken, not to the latest stable download, but to the nightly builds page. All of the versions I can see have a ‘Pre-release’ button by them that doesn’t do anything. At this point I go back to the Help file, try the Classic Shell forums, click around a bit. Many of the links in GitHub which appear potentially informative only lead to stuff about GitHub itself, not the program in question (Open Shell), which is very confusing. The People link doesn’t come up with anything I can use, not even an email address for submitting a bug report about the old links.
4. Eventually discover that if you scroll down far enough there is an entry with ‘Latest’ next to it (which doesn’t work), and below that there is actually a download, though it is under the heading ‘Assets’, which doesn’t mean anything to me.
5. At some point I stumble across this Forum… It wasn’t even linked to on the home page.

Now before you go thinking I must be some sort of idiot, I would point out that I am a very experienced user and professional IT bod, but it took me a long time to find something simple (latest stable) and even longer to find the right forum. The defunct Classic Shell home pages and forums were far more discoverable. I can assure you that the majority of my customers would not be able to download and install O-S from these pages. Sure, you are developers and once you are used to GitHub it probably becomes clear, but please do not lose sight of the fact that you are writing for ordinary people.
So please point the big green button to the actual download. And please update the Help file!

**Comment by ge0rdi** [comment]
Hello and thank you for your feedback.

> I wanted to download the latest stable release of Open Shell, and struggled.

Note that there is updater component installed by default that checks for Open-Shell updates automatically (about once a week). So, by default users are notified about new versions automatically.

Do you have this feature disabled?
Or didn't it work for you?

> I typed Open Shell into the Open Shell search bar, pointed to Open-Shell Help. Selected Useful Links. All of them are for Classic Shell.

Unfortunately help file is still the one from Classic Shell. Nobody fixed/improved it yet.
It would be nice if anyone could have a look at this, but I guess it is not big priority (and this is a volunteer-maintained project).

> I tried openshell.org. Not the right site.

Not sure how did you get to such domain, but simplest possible google search for "Open Shell" returns our main github page on first place.

> By clicking the Open Shell Settings icon in File Explorer (something not all users will actually have)

Shortcut to `Open Shell Settings` is created in start menu by default on installation.
Moreover, settings are by default accessible from context menu when right clicking on start button.

> And there I see “If you just want to use it or looking for setup file, click here to download” and a green Download button, with ‘Nightly builds’ below that.

Yup. This is something that should be easy to improve.
Apparently, there is simple "Download" link missing. It is kind of weird we have link for nightly builds but not for actual official release.

> At some point I stumble across this Forum… It wasn’t even linked to on the home page.

There is `Get Help` section with `Report issues` link on home page.
I guess that should be pretty clear. Or do you have some concrete idea how to improve it?

**Comment by ge0rdi** [comment]
> Apparently, there is simple "Download" link missing. It is kind of weird we have link for nightly builds but not for actual official release.

Should be fixed already.
Please, have a look:
https://open-shell.github.io/Open-Shell-Menu/

**Comment by acrowland** [comment]
Hi go0rdi,

Thank you for such quick response! Yes, I am aware that it is a 
volunteer project, and excuse me if I came across rather harsh. I ma 
very grateful for the product and the work you all put it into it. 
Open-Shell not only keeps me happy, but also many of my customers, 
including a lot of older people who find change trying and difficult, 
and which gets forced on them at grim intervals by an industry dominated 
by young, technically savvy people who do not appreciate the effect just 
changing a minor aspect of the UI can have on, say, someone with 
dementia. You are all doing a vital and much appreciated job.

My aim in recounting my experience at such length was to help the 
maintainers stand back and see the web pages /as they might be 
encountered by one of my customers/. I might want to link to the project 
on my web pages too, but would not be confident in doing so as things 
stand, i.e. I fear many would be baffled and retreat (or ring me, which 
is worse).

So many thanks for fixing the link to the Release version so quickly. It 
is much better. By the way, I note that the 'big green button' on 
https://github.com/Open-Shell/Open-Shell-Menu also still goes to nightly 
builds rather than the Release version.

To answer your point and questions:

 1.

    Yes, I do have the latest version myself. I wanted to check that I
    had the latest for installing on other computers, though (I did, so
    that is all good).

 2.

    I guess I might volunteer to fix the help file, seeing as I brought
    it up. I am getting on myself, and can remember having to install
    Robohelp in the past, but I think that has changed. If the 'express'
    version of Visual Studio includes compiling help projects, or
    something else I can get my head around, I will look into it.

 3.

     >I tried openshell.org. Not the right site.

    I guessed. 'Classicshell.net' might have suggested Openshell.net to
    me but I got it wrong. Just an example of what a user might try. I
    certainly think that having a simple URL that redirects to GitHub
    would be a good plan, albeit with some costs associated. Google and
    Duckduckgo came up with the goods, but the address looks a bit
    daunting in search results.

 4. Thanks for the right-click menu hint. I didn't think of that. I
    don't see a link to O-S Settings in the normal menu, though.
 5.

    I agree that the |Report issues| link is clear. I think my point was
    that I found the Classic Shell forum before I found the Open Shell
    one, so I was looking for 'Forum' rather than wanting to report an
    issue at that stage, i.e. was still trying to help myself. I'm not
    sure that logging a bug for 'user too stupid to find the download'
    would get fixed ;)
    Ultimately, I think that separating the website for developers from
    the website for end users would be a good thing, even if they are
    hosted on the same domain. Just /seeing/ 'techie stuff' puts some
    users off, and that kind of user must be a large part of the target
    audience.

Thanks again.

Andrew

On 14.10.2022 13:18, ge0rdi wrote:
>
>     Apparently, there is simple "Download" link missing. It is kind of
>     weird we have link for nightly builds but not for actual official
>     release.
>
> Should be fixed already.
> Please, have a look:
> https://open-shell.github.io/Open-Shell-Menu/
>

**Comment by ge0rdi** [comment]
> I guess I might volunteer to fix the help file, seeing as I brought it up.

That would be really appreciated.

You can have a look at how help is being built here:
https://github.com/Open-Shell/Open-Shell-Menu/blob/master/Src/Setup/BuildInstaller.bat#L8

You should be able to figure out paths to help source files, etc.

> By the way, I note that the 'big green button' on https://github.com/Open-Shell/Open-Shell-Menu also still goes to nightly builds rather than the Release version.

Fixed already, thank you.

> I think that separating the website for developers from the website for end users would be a good thing, even if they are   hosted on the same domain.

That's why github offers hosting of project pages on github.io .
We have such already:
https://open-shell.github.io/Open-Shell-Menu

That is the main project page (Open-Shell should link to it).


BTW It is much better to use github for replies/comments rather than replying to e-mail notification. That way you have much more control over formatting, etc.
