### ISSUE TITLE
Classic explorer toolbar font color

### ISSUE THREAD

**Issue by f1WN356Uh51a1W6cn** [Open-Shell/Open-Shell-Menu#1176]
The font color is black in dark mode which makes it hard to read

**Version:**
 - Open-Shell: 4.4.179
 - OS: Windows 11 22621
![fontcolor](https://user-images.githubusercontent.com/62265474/196884708-be811856-1205-443a-975b-3eedddbc9534.png)

**Comment by blackcrack** [comment]
i guess is a think of lack of the "dark-mode", I didn't notice has been added .. if any Programmer whant support OpenShell therewith would it great :) ... by the way, have the Win11 an other, more new Startmenu hook ?

best

**Comment by f1WN356Uh51a1W6cn** [comment]
This was caused by an old installation of qttabbar so the issue can be closed
