### ISSUE TITLE
2px line above custom Start buttons (instead of 1px)

### ISSUE THREAD

**Issue by Darthagnon** [Open-Shell/Open-Shell-Menu#1185]
**Describe the bug**
Using a custom image for the start button puts a 2px line above it (vs. a 1px line along the rest of the taskbar). This does not occur with the built-in "Shell" Aero button.

**To Reproduce**
I'm using the below textures and custom scaling.
![Win7 Taskbar Reflection for opacity 40 qty ](https://user-images.githubusercontent.com/20792748/197766533-c425e71d-e4fc-40cf-a977-41331014e2b9.png)
![Windows 7 Start Button Small Icons](https://user-images.githubusercontent.com/20792748/197766536-127191fb-01a4-49cd-936b-f2b845d4fbb3.png)

**Expected behavior**
I expect the line above the Start menu to be consistent, as it is when I enable the built-in Shell button:
![Open-Shell bug 2](https://user-images.githubusercontent.com/20792748/197766852-df5c86ce-354a-4e90-ae43-f69114642e45.png)

**Screenshots**
How it looks when I enable the custom Start Button texture (by default)
![Open-Shell bug](https://user-images.githubusercontent.com/20792748/197766613-8b8298f9-0839-446c-97a4-cd4d4d1847e7.png)

**Version:**
 - Open-Shell: 4.4.169
 - OS: Win10 v1709

**Additional info**
I've found that by adjusting the button size and messing with "Align to corner of screen", I can get it working unreliably. Sometimes, with Alignment enabled and 50% size, it works. Sometimes, it doesn't. Must be something to do with image size, but it's weird that this 2px line appears when the image is not precisely sized (?)

**Comment by Darthagnon** [comment]
updated to 4.4.170 and the problem persists.

**Comment by CTVCAM8** [comment]
Hi @Darthagnon

Investigating your 125-size start button with RGB channels, 
I see easily that the image has been pushed up 3 pixels, and the bottom globe is premultiplied. See the images on left.

Actually, what I have found is Open shell always displays a 
modded button down by 1 pixel. See the right taskbar image.
I think Ivo coded it that way for a reason to make other 
functions work correctly.

I understand why you like the premultiplied globe with less glow.
Most image editors can fix the 3-pixel shift by using the "Move" tool,
but to get the button centered on the taskbar with Open-Shell, 
just move it down 2 pixels.

![Left has been modified](https://user-images.githubusercontent.com/44127216/197907851-fe89ed24-b7a2-465a-a775-b984cfe43352.png)

**Comment by CTVCAM8** [comment]
As for the extra line, I give up. I don't get it on my computer.

![No extra line with 4 4 178](https://user-images.githubusercontent.com/44127216/197961498-cefb8333-16f3-4fee-871c-6547e62f8b7f.png)


I have no idea where it is originating from yours.
I'm on version 4.4.178 and don't see it using your taskbar and button image.

Time to update Open-Shell?

**Comment by blackcrack** [comment]
https://github.com/Open-Shell/Open-Shell-Menu/releases
pssttt... @CTVCAM8 , 4.4.180 ;)

**Comment by CTVCAM8** [comment]
I wonder if another installed program has added that line?

Your Windows 10 version 1709 is quite old (October 2017). 
You could try older versions of Classic Shell like 4.30 or 4.31

**Comment by Darthagnon** [comment]
Found the cause: my taskbar image was the wrong size, and was being stretched badly.

Solution: `Open-Shell Settings` >> `Taskbar` >> `Customize taskbar` >> `Vertical stretching` >> `Stretch, Border sizes: 1`
This will make it ignore 1px around the border when stretching, and it will look fine.
![explorer_mrP2Jxq2Le](https://user-images.githubusercontent.com/20792748/198592974-cdec6b8a-a8b3-476b-978e-f6332a05ee13.png)

As for the start button, I noticed it was off-centre now that you pointed it out, @CTVCAM8! Fixed it by shifting everything down by 3px in Paint.NET. To be honest, it was just some random Win7 Orb from the old forums, when I was trying to find the perfect vanilla Win7 Orb. I guess this isn't it; don't suppose you have one somewhere you could share?

**Comment by CTVCAM8** [comment]
It's probably best to use 2,0
so it protects not just the black line, but also the white line from stretching.


Sorry, I don't even know what a Vanilla Win7 Orb looks like.  
If you want a similar 125-size version of what you already have, here:

![125 size  bottom orb premultiplied](https://user-images.githubusercontent.com/44127216/198710838-56208436-5c30-41a2-88f2-0c0f7250117b.png)

**Comment by ge0rdi** [comment]
Closing this one as the issue seems to be resolved (by using proper settings).
Feel free to continue the icon discussion if you like.
