### ISSUE TITLE
Recent programs don't show up

### ISSUE THREAD

**Issue by Gouvernathor** [Open-Shell/Open-Shell-Menu#1188]
**Describe the bug**
In the main start menu, on the left part, there should be a set of pinned apps or programs and then the recent apps. The recent ones don't show.

In the settings window, when you check "Show all setting", in the Main Menu tab, the "Show recent or frequent programs" choice, the "Frequest programs" option. It doesn't work, and never did since I installed OpenShell on my computer a year and a half ago (it did before I reinstalled Windows anew, although it possibly was classic-shell).
Surprisingly, the "Recent programs" option does work. See screenshots below.

**Screenshots**
"Don't show" option, works as intended.
![image](https://user-images.githubusercontent.com/44340603/198265657-b9e4b13d-d728-4dd2-aab3-35fb37a82c17.png)
"Recent programs" option, works as intended.
![image](https://user-images.githubusercontent.com/44340603/198265781-e39b0d8f-6a90-4bc1-b013-b08b993f5196.png)
"Frequent programs" option, fails.
![image](https://user-images.githubusercontent.com/44340603/198265878-8bd7741b-b605-4de5-bda8-f115f31a5e4e.png)

**Version:**
 - Open-Shell: 4.4.170 (but it was like this for months)
 - OS: Windows 10

**Comment by ge0rdi** [comment]
Have a look at #149 and #851 .

**Comment by Gouvernathor** [comment]
149 fixed it, thanks. Maybe adding a warning for that in the settings menu would be good ?
My settings may have been imported from an older version, so "Recent programs" may not be the default value, but if it is, maybe it should be changed or warned about in the installer ?

**Comment by ge0rdi** [comment]
> Maybe adding a warning for that in the settings menu would be good ?

I have created issue to track that idea (#1209).
Thank you.
