### ISSUE TITLE
cannot install open-shell v.4.4.170

### ISSUE THREAD

**Issue by ducwiz** [Open-Shell/Open-Shell-Menu#1189]
Hi, 

got a Dell PC running german MS Win10-64 pro Build 19041.vb_release.191206-1406. I run classic-shell and then open-shell for many years, very satisfied. But now it is impossible to update/install Open-Shell 4.4.170 over existing 4.4.167. I tried admin mode, switched off antivirus and firewall prgs. Nothing helps, pop-up  soon after starting exe says: 
![Snap 2022-10-28 at 18 11 03](https://user-images.githubusercontent.com/106952956/198686056-0f393ec6-f056-410b-8bde-e4a5416dc2dc.png)
I can translate this to english iff needed. 

Any idea?

tnx in advance  Hans (D)

**Comment by blackcrack** [comment]
Hi Hans @ducwiz 

nimm mal das da : https://github.com/Open-Shell/Open-Shell-Menu/releases
[4.4.180](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.180) Pre-release 

und, dann rechte maustaste aud em Setup und als Admin ausführen..
viel Spaß :)
comment und close wenn alles funtzt :)

**Comment by blackcrack** [comment]
hmm no clue why it not works as admin with the newest packet..
May have an other an idea ? (ich drück mal die daumen)

**Comment by f1WN356Uh51a1W6cn** [comment]
Is it possible for you to update to windows 10 version 19043 or newer? I don't know if it helps, it's just a guess 🤔

**Comment by ge0rdi** [comment]
There is probably something wrong on your machine.
For the future, please, use `Discussions` for things like this.
Report `Issue` only if you are quite sure there is a problem in `Open-Shell`.
