### ISSUE TITLE
Shutdown instead of Sleep

### ISSUE THREAD

**Issue by philee9** [Open-Shell/Open-Shell-Menu#1190]
when you click ok "startup" , a popup menu appears, then point the cursor on "Shutdown", you got the right pop up menu with  " change user, lock down,  sleep, etc" item. then you click on SLEEP. the compter will SHUTDOWN instead of Sleep. please correct this bug please

if you click on shutdown then you got a pop up WINDOW, then you select SLEEP, ths computer SLEEP correctly :)

**Comment by ge0rdi** [comment]
> compter will SHUTDOWN instead of Sleep

Are you sure computer is shut down?
How do you check that?
Does it look like freshly started once you turn it back on? (Like there are no applications running that were there before _sleep_).

`Open-Shell` uses [SetSuspendState](https://learn.microsoft.com/en-us/windows/win32/api/powrprof/nf-powrprof-setsuspendstate) API to actually _sleep_ the machine.
Not sure why it should shut it down.

**Comment by ge0rdi** [comment]
@philee9 
Do you happen to have Modern Standby enabled?
Could you provide output of `powercfg /a` command?

This looks similar to issue #787.

**Comment by ge0rdi** [comment]
Should be fixed in [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build.
