### ISSUE TITLE
Variable title name in start menu?...

### ISSUE THREAD

**Issue by FredThompsonII** [Open-Shell/Open-Shell-Menu#1205]
**Describe the bug**
Root level start menu displays "$Menu." preceding some entries.

**To Reproduce**
Display start menu

**Expected behavior**
Root level start menu should NOT display "$Menu." preceding some entries.

**Screenshots**
![Start Menu error](https://user-images.githubusercontent.com/16481959/201245996-110edb8c-d6f5-4a63-b777-bb1e20994b68.png)

**Version:**
 - Open-Shell: 4.4.180
 - OS: Windows 10 22H2 x64 Enterprise

**Additional context**

**Comment by ge0rdi** [comment]
Most likely `StartMenuL10N.ini` is missing from `Open-Shell` folder (or is corrupted) for some reason.
Try to reinstall `Open-Shell`.

**Comment by blackcrack** [comment]
[Classic+Open-Shell_Almanach.pdf](https://github.com/Open-Shell/Open-Shell-Menu/files/9988545/Classic%2BOpen-Shell_Almanach.pdf)

**Comment by FredThompsonII** [comment]
Thanks. Very helpful.
