### ISSUE TITLE
Open-Shell toolbar no longer compatible with Windows 11 22H2

### ISSUE THREAD

**Issue by Truchin** [Open-Shell/Open-Shell-Menu#1207]
Open-Shell 4.4.180

Since installing tabs in Windows 11 22H2 explorer the toolbar has issues.
It remains immobilized on the left.
Is there a solution?
Thank

**Comment by ge0rdi** [comment]
Duplicate of #1180.
Please, don't create duplicate issues.

**Comment by Truchin** [comment]
But there must be a solution!? I must not be the only one in this case.
