### ISSUE TITLE
Can't install or uninstall

### ISSUE THREAD

**Issue by trm2** [Open-Shell/Open-Shell-Menu#1215]
I just upgraded to Windows 11 and can't get Open-shell to open, reinstall or uninstall because I keep getting "the feature you are trying to use is on a network..."  "enter path to install package containing 'OpenShellSetup64_4_4_152msi

Obviously I am not a programmer but please save me from the hell world of widows 11 interface.
Tim

**Comment by ge0rdi** [comment]
Have you tried to install latest `Open-Shell` release over your existing one?
Does it still report some error?

Just note that `Open-Shell` is not fully compatible with Windows 11.
You can find many issues/discussions regarding Windows 11 here.

**Comment by trm2** [comment]
> Have you tried to install latest `Open-Shell` release over your existing one? Does it still report some error?
> 
> Just note that `Open-Shell` is not fully compatible with Windows 11. You can find many issues/discussions regarding Windows 11 here.

When W11 first booted I got a prompt asking if I wanted OS to be configured and I selected yes. It seemed installation ran but OS did not run. I then downloaded 4.4.170 and it stopped during install with message I posted above. I then tried to uninstall and got the same message. I tried going into the registry and deleting the install file but couldn't find it.

**Comment by ge0rdi** [comment]
Download 4.4.152 install package from [here](https://github.com/Open-Shell/Open-Shell-Menu/releases/download/v4.4.152/OpenShellSetup_4_4_152.exe).
Extract MSI from it using:
`OpenShellSetup_4_4_152.exe extract64`

Then uninstall (or install new) `Open-Shell` and when system asks for that MSI, provide path to extracted one.

**Comment by trm2** [comment]
> 

That did it! Thank you very much, really appreciate it.
