### ISSUE TITLE
Start button not fully replaced on Windows 11

### ISSUE THREAD

**Issue by Jaladhjin** [Open-Shell/Open-Shell-Menu#1216]
**Describe the bug**

The start button is not quite fitting right if I use the Shell icon replacement.

You can visually see that it doesn't fit & doesn't replace the start button outright so if I click wrong I can still click the Windows 11 button.

**To Reproduce**
1. Go to '...' Install program
2. Click on '....' Start Button
3. Scroll down to '....' Doesn't fit quite properly

**Expected behavior**

I'd like the start button to fit properly.

**Screenshots**

https://i.imgur.com/4l3c1zk.png

**Version:**
 - Open-Shell: [e.g. 4.4.131] 4.4.170
 - OS: [e.g. Windows 10 1903] Windows 11 21H2

**Additional context**

I've tried going so far as to replace the button icon as well with a matching W10/W11 button & it doesn't seem to fully "take over" the start button.

Is this known ?

I was surprised it worked at all when I 1st started using 11 but figured it'd be fixed eventually.

Grateful for suggestions thanks very much!

**Comment by ge0rdi** [comment]
> Is this known ?

Yes, it is known issue.
`Open-Shell` is not fully compatible with Windows 11 at the moment.
See all the Windows 11 issues/discussions.

Stay tuned, there may be some updates in near future ...

**Comment by ge0rdi** [comment]
Fixed in [4.4.181](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.181).
