### ISSUE TITLE
Windows Key does not open OpenShell-Startmenu (but default Win11)

### ISSUE THREAD

**Issue by konrad79** [Open-Shell/Open-Shell-Menu#1220]
Since my last Windows 11 update (now 22H2 22621.819) pressing the Windows Key the normal/default Windows 11 Start Menu (in the center of the screen) is opened and NOT the OpenShell configured StartMenu as all the years before.

Clicking on the OpenShell StartMenu StartButton (left in the taskbar) works fine. Only the Shortcut has stopped working.

**Comment by ge0rdi** [comment]
I'm at `Win11 22621.900` and Win key seems to be working properly (`Open-Shell 4.4.180`).

Maybe try to update Windows once again?

**Comment by konrad79** [comment]
Deinstalling and reinstalling the 4.4.180 with rebooting inbetween restored the expected behaviour :-)
