### ISSUE TITLE
Downloads folder missing

### ISSUE THREAD

**Issue by jax200** [Open-Shell/Open-Shell-Menu#1225]
**Describe the bug**
Option to include Downloads folder is missing in "Settings" / "Customize Start Menu" in Windows 11.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Customize Start Menu'
3. No folder "Downloads" to configure.

**Expected behavior**
As with Windows 10, should clearly see the "Downloads" folder to customize.

**Screenshots**
![shell](https://user-images.githubusercontent.com/4186439/205458269-32ead27d-9095-433c-a36f-589f867f6a66.png)

**Version:**
 - Open-Shell: 4.4.170
 - OS: Windows 11 version 22H2 (OS Build 2261.819)

**Additional context**
Have been using Win 10  versuib for many years w/o issue.

**Comment by ge0rdi** [comment]
Just to clarify.

`Downloads` folder is present only for `Windows 7` style.
It is not present (and most likely never was) for `Classic` and `Classic with two columns` styles (for whatever reason).
Checked this on clean installation on Win10 and Win11 (as well as in source code).

> As with Windows 10, should clearly see the "Downloads" folder to customize.

Could it be that you have added some custom item for it?
Can you provide a screenshot?

**Comment by CTVCAM8** [comment]
In "Customize Start Menu" drag "Custom" from right column and drop onto left column. 
Edit so link "Downloads | %USERPROFILE%\Downloads" is picked.

![Custom](https://user-images.githubusercontent.com/44127216/205695516-fda290de-3aec-4f38-8def-d8f7a23d5ac0.png)
