### ISSUE TITLE
Start menu doesn't work on Windows 11 in v. 4_4_181-dalrueyv

### ISSUE THREAD

**Issue by kkuhlemann** [Open-Shell/Open-Shell-Menu#1227]
After installation of the version 4_4_181-dalrueyv there is no start menu on Windows 11 22H2.

**To Reproduce**
1. Install Open Shell.'
2. Click on the Windows Menu button or the Windows button.
3. Get the Windows 11 start menu.

**Expected behavior**
See the Open Shell start menu.

**Version:**
 - Open-Shell: 4.4.181-dalrueyv
 - OS: Windows 11 22H2 22621.900

**Additional context**
An other problem is the fail of an explorer top menu in 22H2 beginning with the start of explorer tabs. Even the possibility to show always menus in the Explorer options doesn't exist any more. It was necessary to remove the tabs to enable Classic Explorer. Another way to start it will be necessary.

**Comment by ge0rdi** [comment]
Not sure why are you using unofficial PR build.
But this is expected and `Open-Shell` doesn't support Windows 11 at the moment.

Please, use only official builds (unless a developer asked you to check with concrete unofficial build).

**Comment by mike000000000001** [comment]
The official build does not work for me either. When I install it and click start icon, it doesn't start no matter what. Win 11 22H2.

**Comment by ge0rdi** [comment]
You need to use latest [pre-release](https://github.com/Open-Shell/Open-Shell-Menu/releases) build on Windows 11.
