### ISSUE TITLE
Part of taskbar turns black when using custom taskbar texture

### ISSUE THREAD

**Issue by CarrionAndOn** [Open-Shell/Open-Shell-Menu#1230]
**Describe the bug**
Sometimes when using an image file as the taskbar texture, just one specific part of it turns black. It stops happening when I open the menu settings and then close it.
![image](https://user-images.githubusercontent.com/30084485/205998830-80b82354-29a1-42d6-9fda-63d728e088d8.png)
**To Reproduce**
1. Choose a taskbar texture
2. Do anything
3. See error

**Expected behavior**

**Screenshots**

**Version:**
 - Open-Shell: 4.4.181
 - OS: Windows 11 22H2 (22621.819)

**Additional context**
It mainly seems to happen when I do anything in explorer, or open the menu settings.

**Comment by ge0rdi** [comment]
Could you provide also your custom texture? For testing.

**Comment by ge0rdi** [comment]
Similar issue here #803.

**Comment by ge0rdi** [comment]
Fixed in [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build.
