### ISSUE TITLE
Align to working area doesn't work properly with vertical taskbar

### ISSUE THREAD

**Issue by HarkTu** [Open-Shell/Open-Shell-Menu#1231]
**Describe the bug**
I use: 
https://github.com/valinet/ExplorerPatcher/
for vertical taskbar.

With Open Shell, start menu appears on the taskbar or under the taskbar. Tried with options checked for vertical and custom taskbars. Couldn't make it work like in Windows 10.

**Version:**
 - Open-Shell: 4.4.181
 - OS: Windows 11 22H2 22621.819

**Comment by ge0rdi** [comment]
It seems to be working properly for me:
![image](https://user-images.githubusercontent.com/2453094/206128047-8718f48c-03a3-49c3-b8bd-649d373036ac.png)

Can you provide your `Open-Shell` (export to XML) and `ExplorerPatcher` settings?

**Comment by HarkTu** [comment]
Thats the best result in windows 11, as in your screenshot, hides icons on taskbar.
![Screenshot_12](https://user-images.githubusercontent.com/46054251/206194342-ecfc3f5d-0113-40d5-9a91-885b4264dbe0.png)

I love it like this, near the taskbar.(windows 10)

**Comment by ge0rdi** [comment]
There is also `Show next to taskbar (when the taskbar is vertical)` setting.
That should be exactly about this positioning you want.

But it doesn't work on Windows 11 either.

**Comment by ge0rdi** [comment]
Fixed in [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build.
