### ISSUE TITLE
Custom start button partly overlays taskview button

### ISSUE THREAD

**Issue by Ottileinchen** [Open-Shell/Open-Shell-Menu#1232]
When "Use small taskbar buttons" is on in Windows 10 21H2 Taskbar Settings (taskbar on the left side, 4k display), and Replace Start Button, Aero Button is selected in Open-Shell Menu settings (ver. 4.4.170), the Task View Button is partly overlayed by the start button. This does not happen immediately after turning small taskbar buttons, or the Taskview button on, but after a reboot or log off/log on. Toggling one of these switches temproarily moves the Taskview button down, where it belongs.

![OpenShellStartButton](https://user-images.githubusercontent.com/37915741/206142546-e74a7e5c-2564-4d98-ad50-d2a83342b3b4.png)

**Comment by ge0rdi** [comment]
I can replicate it.

It seems the taskview button is not moved to proper position when custom start button is enabled.
Though any change to taskbar (like change in placement or size) will move taskview to proper position.

I'll try to have a look at it.

**Comment by ge0rdi** [comment]
Should be fixed in [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build.
