### ISSUE TITLE
Start-Button overlays Windows 11 Start-Button

### ISSUE THREAD

**Issue by daniel-lo** [Open-Shell/Open-Shell-Menu#1237]
Hi, on my Windows 11 machine 4.4.182 overlays the windows start button in the center task bar menu instead of residing in the left corner of the task bar (like usual).

**Comment by daniel-lo** [comment]
reboot does not remedy

**Comment by ge0rdi** [comment]
Could you provide screenshots for clarity?

`Open-Shell` start button now follows Windows start button setting (as its purpose is to replace Windows button).
If you have Windows button in center then `Open-Shell` will use that location too.

You can change alignment of Windows start button in Windows `Settings` -> `Personalization` -> `Taskbar` -> `Taskbar behavior` -> `Taskbar alignment`.
If you change it to `Left` you will have left-aligned start button and `Open-Shell` should follow that.

**Comment by daniel-lo** [comment]
Well .. before the update the Open Shell icon had always been nailed to the left of the task aber so I could use either that or the Windows 11 start button.

![grafik](https://user-images.githubusercontent.com/4311558/206423860-c65078bd-b6f0-4691-b948-3ff5c8835677.png)

**Comment by daniel-lo** [comment]
and this is the way it should look .. even with active Open Shell Menu:

![grafik](https://user-images.githubusercontent.com/4311558/206424147-a8932cbb-6307-4fdc-a86f-711f0012d0e0.png)

**Comment by ge0rdi** [comment]
> before the update the Open Shell icon had always been nailed to the left

That was because `Open-Shell` didn't support Windows 11 properly.
It was fixed in 4.4.181 build and now `Open-Shell` button should properly replace Windows one.

> and this is the way it should look .. even with active Open Shell Menu

You can simply disable custom `Open-Shell` button, if you don't want it.

**Comment by ge0rdi** [comment]
I'm sorry but there is no plan to add such option.
It doesn't make much sense to have two start buttons at the same time.

If you want to use Windows start menu, you can simply do `Shift`+click (or `Shift`+`Win`).

**Comment by daniel-lo** [comment]
what a pity .. can I change this behafour around? So Windows start menu without shift .. and Open Shell menu with shift?
