### ISSUE TITLE
Broken taskbar look under pinned items when using taskbar textures

### ISSUE THREAD

**Issue by patrik-krajcovic2** [Open-Shell/Open-Shell-Menu#1238]
**Describe the bug**
Taskbar look is broken under pinned items when using taskbar texture

**To Reproduce**
1. Go to http://www.classicshell.net/forum/viewtopic.php?t=6604 and download "Windows Vista Basic (Horizontal)".
2. Apply that custom taskbar texture on Open Shell Menu Settings.
3. You will see that texture under the pinned items will be broken.

IMPORTANT: Pin to taskbar some items, i am sure that empty taskbar would not be reproducible.

**Expected behavior**
Taskbar texture is not broken.

**Screenshots**
![Broken Taskbar](https://user-images.githubusercontent.com/69351811/206480388-bd54327c-4028-46fe-a72c-a0e693d92f4d.png)

**Version:**
 - Open-Shell: 4.4.182
 - OS: Windows 11 22621.900

**Comment by ge0rdi** [comment]
It seems to be the same issue as #1230.
