### ISSUE TITLE
Options to independently disable features, e.g. the Custom Taskbar and Menu?

### ISSUE THREAD

**Issue by StereoMadnessss** [Open-Shell/Open-Shell-Menu#1240]
In the current state of Open Shell, I do not know how to disable the taskbar, but I know how with the Start Menu and Classic Explorer, and I think that it could be improved.

**My Solution**
I think that in the installer, you should be able to pick from the following features independently (all selected by default):
Classic Explorer
Start Orb
Start Menu
Taskbar

This “package-like” solution would make things a lot easier for people, (Ex. Those who want to have a custom Start Orb, or maybe the Menu)

**Start11**
I was thinking about StartAllBack but the problem is that I know next to nothing about it, so I partially considered Start11, but it is paid, so I have ran out of ideas and solutions.

**Read This**
If this is already included then close this and let me know that I am blind.

**Comment by ge0rdi** [comment]
There are nice settings for all those things (I believe easily discoverable) when you right-click on start button and select `Settings` (or use `Open-Shell Menu Settings` shortcut in start menu).
![image](https://user-images.githubusercontent.com/2453094/206983423-c80a0dc6-3c1c-4234-9dd3-4605256c862e.png)

I don't think there is a need to change this and put it all to installer.
One can easily configure it as he needs after installation.
