### ISSUE TITLE
StartMenuDLL.dll 4.4.182.0 causes crashes of explorer.exe when i try to open folder from start menu

### ISSUE THREAD

**Issue by kotenok2000** [Open-Shell/Open-Shell-Menu#1245]
**Describe the bug**
StartMenuDLL.dll 4.4.182.0 causes crashes of explorer.exe when I try to open folder from start menu

**Version:**
 - Open-Shell: 4.4.182.0 
 - OS: 10.0.22621.963

**Additional context**
[explorer.exe.16016.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/10227818/explorer.exe.16016.zip)
![Снимок экрана (280)](https://user-images.githubusercontent.com/8822292/207596424-d9b22129-bbc5-4ffd-821d-d3fab7fc06f6.png)

**Comment by ge0rdi** [comment]
Thank you for the report.
From dump I can see where it crashes. So it should be easy to fix.

I'd just like to understand what are steps to reproduce it (as I'm unable to do so).
Can you provide some screenshots how do you have your menu organized and what exactly do you do when it crashes?

**Comment by kotenok2000** [comment]
I am not  sure. I ran system for 8 hours and used memory is 76%  of 16 gb.

https://user-images.githubusercontent.com/8822292/207604407-91ec0ffb-24c5-4fdb-a08a-8d5d2c241079.mp4


I also use this: https://winaero.com/how-to-change-taskbar-size-in-windows-11/

**Comment by ge0rdi** [comment]
Hmm, I don't understand your language, so it is quite hard to guess what you are clicking at.
For the future, please, report all things in English.

Ok, for now it will be easier if you could provide `Open-Shell` log using this [guide](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-obtain-advanced-Open-Shell-Menu-log).
Enable logging, replicate the crash and then attach log here.

Thank you.

**Comment by kotenok2000** [comment]
Am i using right log categories?
[StartMenuLog.txt](https://github.com/Open-Shell/Open-Shell-Menu/files/10228232/StartMenuLog.txt)

**Comment by ge0rdi** [comment]
Yup, the log is correct.
Unfortunately it didn't help me to see what you were doing :(

Nevermind, I will just fix the bug.

**Comment by ge0rdi** [comment]
Please, use build 4.4.183.
The issue should be fixed.

**Comment by ge0rdi** [comment]
> What was the problem?

Missing check for valid data (as you can see in https://github.com/Open-Shell/Open-Shell-Menu/commit/b0c1d9a2292bc1bb80c1988467ea716c1a3164fd commit).
