### ISSUE TITLE
Impossible to open the control panel

### ISSUE THREAD

**Issue by PiliJ** [Open-Shell/Open-Shell-Menu#1249]
Under Win 8.1x64, a problem found with version 4.4.182 that did not exist with version 180:
impossible to open the Windows control panel via Start menu!

**Comment by ge0rdi** [comment]
Please, describe what exactly are you doing (step by step).
Ideally provide also some screenshots for better context.

**Comment by ge0rdi** [comment]
Could you try with latest `4.4.183` build?

**Comment by PiliJ** [comment]
Problem don't occured with 183 !
FYI, it don't occured under Win 11 with version 182.
Problem solved anyway... thank you.
