### ISSUE TITLE
Cannot open documents folder, or any folder in that matter.

### ISSUE THREAD

**Issue by ghost** [Open-Shell/Open-Shell-Menu#1255]
**Describe the bug**
Whenever I try to open the Documents folder, or any other folder at all, explorer crashes

**To Reproduce**
1. Open the start menu
2. Click on the documents folder
3. Explorer crashes and restarts itself.

**Expected behavior**
For the folder to open

**Version:**
 - Open-Shell: 4.4.183
 - OS: Windows 11 22H2

**Comment by ge0rdi** [comment]
Please, provide crash dump from Explorer (see this [guide](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-create-dump-on-Windows-Explorer-crash)).
