### ISSUE TITLE
appveyor secret token pushed to the repository

### ISSUE THREAD

**Issue by xl32** [Open-Shell/Open-Shell-Menu#1257]
**Describe the bug**
Shouldn't secure deployment token and account name be set up as a stored secret instead of putting it to the repository?

**To Reproduce**
1. Go to https://github.com/Open-Shell/Open-Shell-Menu/blob/master/appveyor.yml
2. Observe deployment credentials as plain text

**Expected behavior**
Something like `$(APPVEYOR_TOKEN)` and `$(APPVEYOR_ACCOUNT_NAME)` should be observed instead of "passionate_coder" and his secret token

**Version:**
 - Open-Shell: master branch

**Comment by ge0rdi** [comment]
The `auth_token` is passed as [secure variable](https://www.appveyor.com/docs/build-configuration/#secure-variables) so it can be decrypted only by `passionate_coder` AppVeyor account (and only during builds from master).
