### ISSUE TITLE
Start menu settings window (from open shell folder not the actual start button) not opening 

### ISSUE THREAD

**Issue by kemonofriends10** [Open-Shell/Open-Shell-Menu#1262]
Start menu application not opening (the application not the actual start menu) 
ClassicExplorerSettings and ClassicIE_32 open just fine but Start Menu Settings or StartMenu do nothing when they're pressed
On task manager it shows Open-Shell menu (32 bit) as running and using memory and disc storage but there's no way to access it, so I can't change my start menu or windows bar

**To Reproduce**
1. download open shell
2. Click on StartMenu
3. nothing happens

**Version:**
 - i tried both 4.4.170 and 4.4.184
 - OS: Windows 10 19042.1023

ive used open shell and classic shell for years and years never had an issue until now
thanks

**Comment by bonzibudd** [comment]
`StartMenu.exe` is the process for executing the Start menu itself, not the Settings window. In order to open the Settings window via command, use `StartMenu.exe -settings`.

**Comment by kemonofriends10** [comment]
the problem is i'm not able to execute the start menu, nothing happens when I press either Startmenu.exe nor the start menu settings shortcut

I can see "open-shell menu (32 bit)" running in the task manager but I'm unable to view the window or do anything

I couldn't find anyone with the same issue anywhere either
