### ISSUE TITLE
Wont load/Isnt Working

### ISSUE THREAD

**Issue by Ice-Child** [Open-Shell/Open-Shell-Menu#1279]
**Describe the bug**
I installed and picked a theme. It does not load at all. I get the stock windows 11 interface.

**To Reproduce**
1. Go to 'taskbar'
2. Click on 'windows icon'
3. Scroll down to 'No need to scroll its loading the stock window not Open Shell Menu'

**Expected behavior**
As posted above, it doesnt work. I do not get the Windows 7 setup it shows in options. Instead I get Windows 11 normal menu.

**Screenshots**

**Version:**
 - Open-Shell: [e.g. 4.4.131]
 - OS: [e.g. Windows 10 1903]

**Additional context**

**Comment by bonzibudd** [comment]
Which version of Open-Shell are you using?

**Comment by Ice-Child** [comment]
I just downloaded it so I would say the latest and greatest. Just opened it so says 4.4.170

**Comment by bonzibudd** [comment]
Try latest nightly release: [4.4.187](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.187)

There have been several improvements for Windows 11 compatibility in recent pre-release versions.

**Comment by Ice-Child** [comment]
Thanks I will give that version a shot right now.

**Comment by Ice-Child** [comment]
Works like a champ. Thanks a ton @bonzibudd
