### ISSUE TITLE
Open-shell Menu 4.4.186

### ISSUE THREAD

**Issue by Fordium** [Open-Shell/Open-Shell-Menu#1282]
Hello. Have used Open-shell Menu for a long time. Both on Windows 10 and Windows 11. Freshly installed windows!
One thing that bothers me quite a bit is that there is always a white frame around the start menu icon! There is no way to get rid of the white frame!

It is not the icon file itself that has a white frame, but it is
(Open-shell Menu) that makes it! There is no way you can remove it!

I require that this problem be fixed!
It's things like that that shouldn't have been a problem!

when I choose (Custom Button) the start menu icon size is so weird! The frame that lies above the windows start button icon is completely wrong in size and the icon image inside is too large to fit.

These are two errors/bugs that I find strange that they exist!

![open shell menu 2](https://user-images.githubusercontent.com/122231842/211217752-25ef17de-46d1-4917-b3e4-5fe470fd68ec.jpg)
![Open shell menu](https://user-images.githubusercontent.com/122231842/211217753-2d7584aa-c0fe-4de3-9167-41a1adf63486.jpg)

**Comment by bonzibudd** [comment]
Please, don't create duplicate issues.

**Comment by Fordium** [comment]
Sorry. Am completely new to GitHub. 
It shall not happen again. 


***@***.***
 
From: Eli Farmer
Date: 2023-01-09 00:25
To: Open-Shell/Open-Shell-Menu
CC: Fordium; Author
Subject: Re: [Open-Shell/Open-Shell-Menu] Open-shell Menu 4.4.186 (Issue #1282)
Please, don't create duplicate issues.

**Comment by ge0rdi** [comment]
Also it is much better to reply directly on Github (instead to notification e-mail).
It looks much better (without the mail crap) and you have better control over formatting, etc.
