### ISSUE TITLE
Open-Shell Menu 4.4.186 bug

### ISSUE THREAD

**Issue by Fordium** [Open-Shell/Open-Shell-Menu#1283]
Hello. Have used Open-shell Menu for a long time. Both on Windows 10 and Windows 11. Freshly installed windows!
One thing that bothers me quite a bit is that there is always a white frame around the start menu icon! There is no way to get rid of the white frame!

It is not the icon file itself that has a white frame, but it is
(Open-shell Menu) that makes it! There is no way you can remove it!

I require that this problem be fixed!
It's things like that that shouldn't have been a problem!

when I choose (Custom Button) the start menu icon size is so weird! The frame that lies above the windows start button icon is completely wrong in size and the icon image inside is too large to fit.

These are two errors/bugs that I find strange that they exist!

![open shell menu 2](https://user-images.githubusercontent.com/122231842/211217939-741d7bbd-e17d-4dd2-86f8-edde02b5519c.jpg)
![Open shell menu](https://user-images.githubusercontent.com/122231842/211217940-260da31f-7c99-482f-931c-e17ed0bfd77e.jpg)

**Comment by bonzibudd** [comment]
Could you please attach those two custom button files?

For your first image, I don't see why you can't set `button size` to something smaller. Approximating from your display scaling, I think it should be around 70px.

**Comment by Fordium** [comment]
Here comes the icon file. No icon edit programs allow icons larger than 256x256

It doesn't help if I change the size as you suggest.
(Classic button) still has a white frame around it.
And (custom button) will not be correct.
I've tried changing the size in the settings but it doesn't help.

Have also tried several icon images without any help.

what do you mean by (PX)?



***@***.***
 
From: Eli Farmer
Date: 2023-01-09 00:22
To: Open-Shell/Open-Shell-Menu
CC: Fordium; Author
Subject: Re: [Open-Shell/Open-Shell-Menu] Open-Shell Menu 4.4.186 bug (Issue #1283)
Could you please attach those two custom button files?
For your first image, I don't see why you can't set button size to something smaller. Approximating from your display scaling, I think it should be around 70px.

**Comment by bonzibudd** [comment]
@Fordium 

If you meant to attach the icon files, they didn’t come through. You may need to use the GitHub web interface rather than email.

Looking at your second picture, it looks like you are using the `Classic button` with a custom `Button image`. The white border you see is intended in this button style, as it is meant to be the same as the Classic theme in older versions of Windows.

By PX, I am referring to the pixel amount specified by the button size. By default, Open-Shell uses the original size for the image, split into three sections corresponding to the normal, hot, and pressed states of the button.

**Comment by Fordium** [comment]
Ok. Normally, there is no problem sending 2 small files by email.Yes I can use   github.Sendt fra min Huawei-mobiltelefon-------- Opprinnelig melding --------Emne: Re: [Open-Shell/Open-Shell-Menu] Open-Shell Menu 4.4.186 bug (Issue #1283)Fra: Eli Farmer Til: Open-Shell/Open-Shell-Menu Kopi: Fordium ,Mention 

@Fordium

If you meant to attach the icon files, they didn’t come through. You may need to use the GitHub web interface rather than email.

Looking at your second picture, it looks like you are using the Classic button with a custom Button image. The white border you see is intended in this button style, as it is meant to be the same as the Classic theme in older versions of Windows.

By PX, I am referring to the pixel amount specified by the button size. By default, Open-Shell uses the original size for the image, split into three sections corresponding to the normal, hot, and pressed states of the button.



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/Open-Shell/Open-Shell-Menu/issues/1283#issuecomment-1376074869",

"url": "https://github.com/Open-Shell/Open-Shell-Menu/issues/1283#issuecomment-1376074869",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Fordium** [comment]
> (classic button) I don't understand why you can't choose to make the icon file bigger so it fits without getting the white frame?
That's the kind of thing that's important if you ask me.

(custom button) I don't know why the same icon file behaves so strangely. Have tried absolutely everything with nothing working.

you need to add such functions, possibilities! I think they are important. It must then be possible to use normal icon files without problems or normal image files!

[github.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/10376696/github.zip)

**Comment by bonzibudd** [comment]
> I don't understand why you can't choose to make the icon file bigger so it fits without getting the white frame?

That is the purpose of the `Custom button`. I can see that you used this option foe the first picture, so I'm not sure why you can't do the same with the other button image.

The reason that the custom button is not loading correctly is because the images need to follow the format as shown [here.](https://coddec.github.io/Classic-Shell/www.classicshell.net/tutorials/buttontutorial.html)

There are already many similar buttons that follow the format, you can find some here: https://coddec.github.io/Classic-Shell/www.classicshell.net/forum/viewtopicab93.html?f=18&t=3207

**Comment by Fordium** [comment]
> > I don't understand why you can't choose to make the icon file bigger so it fits without getting the white frame?
> 
> That is the purpose of the `Custom button`. I can see that you used this option foe the first picture, so I'm not sure why you can't do the same with the other button image.
> 
> The reason that the custom button is not loading correctly is because the images need to follow the format as shown [here.](https://coddec.github.io/Classic-Shell/www.classicshell.net/tutorials/buttontutorial.html)
> 
> There are already many similar buttons that follow the format, you can find some here: https://coddec.github.io/Classic-Shell/www.classicshell.net/forum/viewtopicab93.html?f=18&t=3207

I think you are misunderstanding or we are misunderstanding each other.
The one square icon image is with settings
(Classic Button) which has a white frame and the other rounds are with settings
(Custom Button)

icon size becomes completely wrong with use of
(custom Button) as you see in one of the 2 pictures I uploaded.
Does not help which image I use if they are an icon file or other image formats! Even though I have enlarged windows 11 to 150%, it should be possible to get them right!

looks more like a problem or too few choices in the open chell menu.

**Comment by Fordium** [comment]
I don't understand why I can't use a normal icon file, image that Windows uses or a normal square image. why is
(open shell menu) made in this weird way?
Shouldn't be that difficult to make it happen? you only need in addition the ability to fine-tune the image up and down and right and left and the size of the image,  or something like that.

Many  images in the link I got are transparent, you can see Windows' start button below.
Image resolution is so extremely small. looks like it's a competition who manages to have the smallest resolution!

see the one picture I am attaching. why can't i use it? (custom button) or (Classic button) or without a white frame

![icon jpg 1](https://user-images.githubusercontent.com/122231842/211436529-0a383f39-3e3a-4da2-a719-b867c7dc86d5.jpg)

**Comment by bonzibudd** [comment]
The point I’m trying to make is, I believe the reason your pictures are sized incorrectly is because they are not in the correct format. Here’s what I’m talking about: 
![](http://www.classicshell.net/tutorials/images/button0.png)

The picture needs to be a PNG or BMP in three sections, each for a different state of the button. This is basically the same format used in Windows itself from XP to 7.

**Comment by Fordium** [comment]
Yes, I understand this. I understand how this with 3 icons in the same image works.but I still find it strange that you can't take a normal picture (png) (bmp) (icon) to make it work? That's what you expect to work first without any problems!it is most likely the software that is not made well in this area!if you have to create a special image, you must also have a special program that satisfiesopen dhell menu since it requires special images that are not a normal image format.you have to change modify improve open shell menuSendt fra min Huawei-mobiltelefon

**Comment by Fordium** [comment]
> The point I’m trying to make is, I believe the reason your pictures are sized incorrectly is because they are not in the correct format. Here’s what I’m talking about: ![](https://camo.githubusercontent.com/f5eb2c2d706d63610210484a26907c64c6d35c04c705cc879a2fab9d9cb81083/687474703a2f2f7777772e636c61737369637368656c6c2e6e65742f7475746f7269616c732f696d616765732f627574746f6e302e706e67)
> 
> The picture needs to be a PNG or BMP in three sections, each for a different state of the button. This is basically the same format used in Windows itself from XP to 7.

The ones I had to do are the following. Many drawing programs are useless as they create a white background.
I had to take a ready-made icon image file with 3 images and modify it. I had to use a special icon program called
(Junior Icon Editor) where you can create invisible, transparent backgrounds.

You can NOT use a normal Microsoft paint image or something you find on the internet. you can't use a normal windows icon either.

Open Shell Menu has some weaknesses YES. The first thing you should expect from this type of program is that you should be able to take a normal picture or icon to make them work!

**Comment by ge0rdi** [comment]
I'm sorry that you have trouble with creating custom start button image.
`Open-Shell` simply needs this particular format of image (it is documented in help as well).

I have created feature request (#1299) to allow also standard images as custom start button.
Feel free to leave additional feedback there (or help with the implementation).

For now you should simply stick to existing buttons (I'm sure you can find many of then on the internets).

That said, I'm closing this issue.

**Comment by Fordium** [comment]
> I'm sorry that you have trouble with creating custom start button image. `Open-Shell` simply needs this particular format of image (it is documented in help as well).
> 
> I have created feature request (#1299) to allow also standard images as custom start button. Feel free to leave additional feedback there (or help with the implementation).
> 
> For now you should simply stick to existing buttons (I'm sure you can find many of then on the internets).
> 
> That said, I'm closing this issue.

I have no faith that there will be an update of the Open Shell Menu that will solve the problem. Some people are too difficult to talk to and everything should only be their way!!!!!!!!!!!
