### ISSUE TITLE
open shell not working - unknown reason

### ISSUE THREAD

**Issue by DukeOfURL01** [Open-Shell/Open-Shell-Menu#1284]
I've been using Open Shell / Classic Shell for years and think I know how to use it by now, I just installed it on one of my refurbished laptops running a newer installation of Win11 and it's not automatically working and I'm not sure what to do about it, or why  Anyone have any ideas?  Maybe things I can check?

**Comment by bonzibudd** [comment]
Which version of Open-Shell are you running?

If your'e not, try using latest nightly release: [4.4.187](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.187)

There have been several improvements for Windows 11 compatibility in recent pre-release versions.

**Comment by DukeOfURL01** [comment]
Let me look, I just downloaded and installed it 20 minutes ago, it looks like 4 4 170
Ill try the nightly build, I hope that does the trick.

**Comment by DukeOfURL01** [comment]
yup, that seemed to the job.  I wonder what was in 170->187 that fixed it. 
thanks.

**Comment by DukeOfURL01** [comment]
fixed
