### ISSUE TITLE
Classic start menu does not work if "Replace Start button" is disabled

### ISSUE THREAD

**Issue by PatrickZZZZZ** [Open-Shell/Open-Shell-Menu#1292]
### Describe the bug

I don't know if this has been reported before. If it has, my apologies.

I'm running Windows 11 22H2. In the Start Menu Style tab, if I uncheck "Replace Start button", the classic start menu doesn't work anymore. When I click the Start button, the default Windows 11 start menu opens. There is no way to enter the classic start menu with "Replace Start button" disabled.

I want to use the default Windows 11 start button to open the classic start menu provided by Open Shell. How do I do that?

### Area of issue

Start menu

### To reproduce

1. Open "Settings for Open-Shell Menu"
2. Go to the tab "Start Menu Style"
3. Uncheck "Replace Start button"

### Expected behavior

I expect the classic start menu, as provided by Open Shell, to open when I click the start button. This works as it should with "Replace Start button" enabled but doesn't work with "Replace Start button" disabled.

### Open-Shell version

4.4.170

### Windows version

Windows 11 22H2

**Comment by ge0rdi** [comment]
Please, use latest [release](https://github.com/Open-Shell/Open-Shell-Menu/releases).
