### ISSUE TITLE
Start menu "Classic style" says Windows 10 Pro when running on Windows 11 Pro

### ISSUE THREAD

**Issue by PatrickZZZZZ** [Open-Shell/Open-Shell-Menu#1293]
### Describe the bug

It's a minor issue, but when the Open Shell start menu is set to "Classic Style", on the left next to the menu it says "Windows 10 Pro". I'm running Windows 11 Pro. It would be nice if the correct Windows version was shown in the Start menu.

### Area of issue

Start menu

### To reproduce

1. Open "Settings for Open-Shell Menu"
2. Go to the tab "Start Menu Style"
3. Select "Classic style" as your style

### Expected behavior

I would expect the text to show "Windows 11 Pro" instead of "Windows 10 Pro" when I'm running Windows 11. Of course on Windows 10 it should show Windows 10.

### Open-Shell version

4.4.170

### Windows version

Windows 11 22H2

**Comment by ge0rdi** [comment]
Please, use latest [release](https://github.com/Open-Shell/Open-Shell-Menu/releases).
