### ISSUE TITLE
Classic Explorer bar cannot be removed

### ISSUE THREAD

**Issue by FZ500** [Open-Shell/Open-Shell-Menu#1296]
### Describe the bug

Windows 11 22621.1105 The Classic Explorer bar cannot be removed, After canceling the display, close the file explorer and open it again, and the Classic Explorer bar will appear again
![Win11-2023-01-19-22-36-30](https://user-images.githubusercontent.com/117428082/213470606-2b13c61d-a291-402b-adbd-555e4e537bc0.png)

### Area of issue

Windows Explorer

### To reproduce

After canceling the display, close the file explorer and open it again, and the Classic Explorer bar will appear again

### Open-Shell version

4.4.189

### Windows version

Windows 11 22621.1105

**Comment by Zebulpator** [comment]
I seem to have managed to disable CEB! And I myself did not understand how I could do it. At some point, as a result of my manipulations, the CEB icons moved to the right, and the usual menu buttons 'File', 'Edit', etc. appeared on the left. By clicking on these buttons, I unchecked CEB in the same way, and this panel disappeared forever! I don't know what will happen after rebooting Windows 11, but so far, when entering the explorer, the CEB panel does not appear.

**Comment by ge0rdi** [comment]
See https://github.com/Open-Shell/Open-Shell-Menu/issues/1526#issuecomment-1631893316 for workaround.
