### ISSUE TITLE
The back button (that appears after pressing on the "all programs" button) should be a back button instead of a list icon

### ISSUE THREAD

**Issue by DragoCubed** [Open-Shell/Open-Shell-Menu#13]
I'm not in any position to say this as I've just started learning programming but: this might not be too hard to implement.

**Comment by XenHat** [comment]
That is possible, but this would require to add a whole new skinnable button.
Possibly for a future release.

**Comment by bonzibudd** [comment]
This would not, in fact, require an entirely new button. The “All Programs” bitmap already has 2 independent images for the 2 states. Which skin would you like this to be added to?

**Comment by DragoCubed** [comment]
The default one :)

**Comment by bonzibudd** [comment]
@DragoCubed Try this out: [MetroBackBtn.skin7](https://1drv.ms/u/s!AqxEMH2XuF6DxHUuKQ4bKQWM41K3?e=vkgyeE)

If you're not a fan of the arrow, I can change it to something else.

**Comment by bonzibudd** [comment]
I may consider adding this to the default Metro skin. I can't think of any reason to not include a different icon when the button changes to a "Back" button.

**Comment by bonzibudd** [comment]
This issue should be closed, I mistakenly forgot to attach it with #705. @ge0rdi
