### ISSUE TITLE
Restarting windows without updating

### ISSUE THREAD

**Issue by FrankvdStam** [Open-Shell/Open-Shell-Menu#130]
When windows has updates ready to install, I get an option to restart without updating in Open-Shell. It will install updates though. To get around this I use shutdown /r in cmd but occaisonally I forget about it and then I'm forced to sit through an update. 

Can this either be fixed or the option to restart without updating removed?

**Comment by FrankvdStam** [comment]
Sidenote, maybe this has already been fixed, I just moved from classic-shell to open-shell.

**Comment by XenHat** [comment]
I looked for this functionality recently, for different reasons, and it appears that Microsoft did everything they could to prevent that from happening.
It is unlikely to be implemented as very little can be done without incurring data loss.
Rest assured that as soon as a working, reliable method is found, this will be added.

**Comment by FrankvdStam** [comment]
Look, it's fine if you don't want to fix the actual restarting part. I know that Microsoft wants to force updates on us. At least remove the false option to restart without updating though, like I said in the original post:

Can this either be fixed or **the option to restart without updating removed**?
