### ISSUE TITLE
Update checker not working?

### ISSUE THREAD

**Issue by eleius** [Open-Shell/Open-Shell-Menu#1301]
### Describe the bug

I always updated by download manually from github, but from 4.4.187 I decided to use Open Shell Update to check for updates. For some reason it always says it's up to date. So I manually installed 4.4.188, and when 4.4.189 was released I tried again, but again it said it was up to date, so I upgraded manually. Is it a bug or something on my end?

### Area of issue

Installation/Other

### To reproduce

1. Start "Open Shell Update" from the start menu
2. Check for updates

### Expected behavior

It should report a new version when it's available.

### Open-Shell version

4.4.189

### Windows version

Windows 10 LTSC

**Comment by ge0rdi** [comment]
You need to enable `Check for nightly builds` checkbox in updater if you want to receive also pre-release builds.
![image](https://user-images.githubusercontent.com/2453094/213888518-54a47d8f-6fbc-4013-a250-f7f5ee4ee12f.png)
