### ISSUE TITLE
Start Button Image locations is not the same on all monitors in multimonitor systems

### ISSUE THREAD

**Issue by uom42** [Open-Shell/Open-Shell-Menu#1310]
### Describe the bug

Start Button Image locations is not the same on all monitors in multimonitor systems.

Monitor 1 (main):
![Monitor 1 (main)](https://user-images.githubusercontent.com/6280840/215263638-1ba02350-a948-4934-993a-e39a74d46f07.png)

Monitor 2 (right):
![Monitor 2 (right)](https://user-images.githubusercontent.com/6280840/215263642-c0df0c56-35d3-494b-9b38-1adf55cfc9e1.png)

Settings:
![Settings](https://user-images.githubusercontent.com/6280840/215263647-24745242-4edb-48c4-bf9e-a1857533cbf7.png)

### Area of issue

Start menu

### To reproduce

1. Just install and get

### Expected behavior

Start Menu button images must be in some locations on each monitor in multimonitor systems.

### Open-Shell version

4.4.189

### Windows version

21H2 build 22000.1455

### Additional context

![Monitor 1 (main)](https://user-images.githubusercontent.com/6280840/215263847-a3f1be23-5dff-4d9a-a4d6-3843cfd9d19e.png)
![Monitor 2 (rigth)](https://user-images.githubusercontent.com/6280840/215263848-61bdbee3-8b1b-4ed9-93fc-968cc7755866.png)
![Settings](https://user-images.githubusercontent.com/6280840/215263849-8c9111b9-f407-4dc2-8716-f9dd88735ca4.png)

**Comment by ge0rdi** [comment]
Can you possibly provide screenshots of whole taskbars (and mark which one belongs to which monitor) for better clarity?

**Comment by uom42** [comment]
![TaskBar1](https://user-images.githubusercontent.com/6280840/215514616-828a2462-b5c3-42a6-88ed-485d501c36e2.png)

**Comment by ge0rdi** [comment]
@uom42 
Could you please test with build from #1314 PR?

**Comment by uom42** [comment]
> @uom42 Could you please test with build from #1314 PR?

Can't download 'https://ci.appveyor.com/api/buildjobs/uiitjqgl6prln2jk/artifacts/OpenShellSetup_4_4_190-jacvaaqe.exe'

{"message":"Artifacts download limit (1024 MB/day) exceeded."}

**Comment by ge0rdi** [comment]
Try later please.

**Comment by uom42** [comment]
> @uom42 Could you please test with build from #1314 PR?

Yes! That's fine!

**Comment by ge0rdi** [comment]
Thanks for confirmation.
I will close this issue once the change is in master and we have official pre-release build.
