### ISSUE TITLE
Error getting file security

### ISSUE THREAD

**Issue by Tokukarin** [Open-Shell/Open-Shell-Menu#1315]
### Describe the bug

![image](https://user-images.githubusercontent.com/50606374/215562649-47915df5-f9a3-4169-aaeb-82e8e867852f.png)

### Area of issue

Installation/Other

### To reproduce

Move AppData folder to another drive, make a hardlink to C drive restart PC and voila. Current Open-Shell installation broken and reinstall shows the above error

### Open-Shell version

Newest

### Windows version

21H1 19043.1110

**Comment by ge0rdi** [comment]
> make a hardlink to C drive

How exactly did you do the hardlink?

> Current Open-Shell installation broken

How is it broken?
What doesn't work?

**Comment by Tokukarin** [comment]
> > make a hardlink to C drive
> 
> How exactly did you do the hardlink?
> 
> > Current Open-Shell installation broken
> 
> How is it broken? What doesn't work?

mklink /J "source local appdata" "target external drive"

**Comment by Tokukarin** [comment]
![2023-01-30_19-19](https://user-images.githubusercontent.com/50606374/215881527-7bf3f403-8e9b-4853-81a7-7cd48b2e3d36.png)
And that, that is broken.

**Comment by Tokukarin** [comment]
I can understand that Open-Shell can't handle If I move files and make hardlinks.
But what pissed me off was that I was unable to deinstall (See first picture) that error appeared both with installing and uninstalling.

I reinstalled windows yesterday because I don't have the time to troubleshoot something like that on a workday.

**Comment by ge0rdi** [comment]
> And that, that is broken.

This message is not from `Open-Shell` but rather from Windows complaining about some issue with its own original Start menu.

> mklink /J "source local appdata" "target external drive"

So you moved your user's local appdata (`%LOCALAPPDATA%`), right?
Interesting that installer complains about global `C:\ProgramData` (`%ProgramData%`).
