### ISSUE TITLE
Don't show first-time settings dialog if settings were imported from XML already

### ISSUE THREAD

**Issue by daiaji** [Open-Shell/Open-Shell-Menu#1319]
### Is your feature request related to a problem? Please describe.

https://github.com/Open-Shell/Open-Shell-Menu/issues/118 https://github.com/Open-Shell/Open-Shell-Menu/issues/251 https://github.com/Open-Shell/Open-Shell-Menu/issues/630 https://github.com/Open-Shell/Open-Shell-Menu/issues/9

Basically, after importing Open-Shell configurations using the `-xml` parameter, Open-Shell will not use these configurations in a non-interactive way.

### Describe the solution you'd like

When the `-xml` parameter is used, Open-Shell-Menu automatically adds these key values to the registry.
`REG ADD "HKCU\Software\OpenShell\StartMenu" /v "ShowedStyle2" /t REG_DWORD /d "1" /f`
To be honest, this will not be particularly difficult, even without making major changes to the existing process. Just add a step of rewriting the registry to the implementation of the `-xml` parameter. Just doing this will make the command line operation experience better.

Especially when I use Open-Shell-Menu in Windows PE, I usually need to import Open-Shell-Menu configuration from the command line in batch processing, but it is not particularly convenient to edit the registry in Windows PE. Moreover, since Windows PE usually does not include any form of start menu component, Open-Shell-Menu is almost necessary. I hope Open-Shell-Menu provides portable application packaging for users, In this way, I don't need to install Open-Shell-Menu in the bare metal system when integrating Open-Shell-Menu for Windows PE.

### Area of issue

Start menu

### Alternatives you've considered

Add the registry manually.

**Comment by ge0rdi** [comment]
> Basically, after importing Open-Shell configurations using the -xml parameter, Open-Shell will not use these configurations in a non-interactive way.

Can you please explain what you mean by that?

`-xml` command line parameter should import settings that are stored in given XML and after that these settings should be used by `Open-Shell` the same way as if one set them via settings dialog.

> To be honest, this will not be particularly difficult, even without making major changes to the existing process.

If you already know what it takes and how to achieve what you need, you can submit pull-request with required changes.

> I hope Open-Shell-Menu provides portable application packaging for users, In this way, I don't need to install Open-Shell-Menu in the bare metal system when integrating Open-Shell-Menu for Windows PE.

Have you tried to copy `Open-Shell` install folder from machine where it is installed to machine where you need to use it?
It seems to be working for me.

**Comment by daiaji** [comment]
> Can you please explain what you mean by that?

Even if you use the `-xml` parameter to import the configuration backup, this pop-up window will pop up the first time you use the command line to start Open-Shell-Menu. Of course, it won't be the second time you start Open-Shell-Menu, because Open-Shell-Menu will fill in the registry when you start Open-Shell-Menu for the first time.
`REG ADD "HKCU\Software\OpenShell\StartMenu" /v "ShowedStyle2" /t REG_DWORD /d "1" /f`

> If you already know what it takes and how to achieve what you need, you can submit pull-request with required changes.

Although I know the principle, I am not familiar with C++.

> Have you tried to copy `Open-Shell` install folder from machine where it is installed to machine where you need to use it?
> It seems to be working for me.

Of course, this is what I do now, so I have to install Open-Shell Menu on my bare metal first.

**Comment by daiaji** [comment]
> Though feel free to create separate _enhancement_ issue for the portable package.
> It is always easier to track just one enhancement in one ticket.

I will do it tomorrow.

**Comment by ge0rdi** [comment]
Fixed in 4.4.190 .
