### ISSUE TITLE
CE Toolbar cannot be disabled on Windows 11

### ISSUE THREAD

**Issue by igrigorov** [Open-Shell/Open-Shell-Menu#1322]
### Describe the bug

This is the opposite issue of #1151 :
I'm trying to remove the Classic Explorer toolbar after a fresh install, so I'm right-clicking on it and it disappears.  
The problem is that it doesn't stay off and every time I open a new File Explorer window, the toolbar is there.

The rest of the options like 'Lock the toolbars', button size etc. are persisted correctly.

### Area of issue

Windows Explorer

### To reproduce

1. Right-click Classic Explorer Bar, de-select it
2. The toolbar disappears
3. Open a new File Explorer window, the toolbar is there again

### Expected behavior

The toolbar should remain disabled after deselecting it.

### Open-Shell version

4.4.170

### Windows version

Windows 11 22H2

**Comment by planetjohn16** [comment]
![image](https://user-images.githubusercontent.com/97569548/216795551-db02006c-6632-4ac2-9229-ce991698345b.png)
I believe I'm having a similar issue here? I removed the program and this now shows up, but interestingly enough only when I resize the window. I removed it forever ago just apparently don't resize file explore much. I also did disable everything before reinstalling and it's still there. I also tried reinstalling and uninstalling it today and it's still somehow there.

**Comment by ge0rdi** [comment]
@igrigorov 
It seems the behavior of Explorer changed after some update.
See https://github.com/Open-Shell/Open-Shell-Menu/issues/1526#issuecomment-1631893316 for workaround.

@jslattery7077 
This is different issue.
See https://github.com/Open-Shell/Open-Shell-Menu/issues/326#issuecomment-813086363 for the fix.
