### ISSUE TITLE
Openshell start button overlays weather widget (win11)

### ISSUE THREAD

**Issue by vandonsel** [Open-Shell/Open-Shell-Menu#1324]
### Is your feature request related to a problem? Please describe.

As far as I've looked, I can't move either. Screenshot attached so I don't mess up my description. I don't care which one gets moved where, but it would be nice if the weather wasn't covered up.
![image](https://user-images.githubusercontent.com/8953804/216512900-f2ca1496-9c38-491e-ad47-a7e1e3d8caeb.png)

### Describe the solution you'd like

I don't care which one gets moved where, but it would be nice if the weather wasn't covered up.

### Area of issue

Taskbar

### Alternatives you've considered

Not using openshell?

**Comment by ge0rdi** [comment]
This was already reported in #1244.

Currently the only workaround is to change Classic button text to something shorter, or simply not use Classic button at all.
