### ISSUE TITLE
Scaling options for Open-Shell's Start Menu skins

### ISSUE THREAD

**Issue by Patrxgt** [Open-Shell/Open-Shell-Menu#1326]
### Is your feature request related to a problem? Please describe.

I've always liked "glassy" Start Menu of Windows Vista/7 and I loved to see, that the faithful recreation of this style is available as a skin for Open-Shell, but when I've tried to use it, I quickly realized, that it's too small on 1080p screen with 100% scaling.

### Describe the solution you'd like

I would like to see an option to scale Start Menu skins either based on screen's resolution/scaling or as a custom option, that could be set in Open-Shell's options.

### Area of issue

Start menu

**Comment by ge0rdi** [comment]
There is `Override system DPI` option where you can provide custom DPI for `Open-Shell` menu.
Have you tried that?

**Comment by Patrxgt** [comment]
Yes, I did, but it only stretches menus size and doesn't makes it taller.

**Comment by ge0rdi** [comment]
I'm not sure I understand.
Can you possibly post some screenshot that would make it more clear? What it looks like now and how would you expect it to be?

**Comment by ge0rdi** [comment]
No response from the user.
