### ISSUE TITLE
OpenShell Causes Explorer.exe to constantly crash

### ISSUE THREAD

**Issue by PrincesssCadence** [Open-Shell/Open-Shell-Menu#133]
Hello!

I have used Classic Shell and now Open Shell all my life since I got Win10 for the first time, it has worked wonderfully always however today I woke up and my laptop that was supposed to be "asleep" was on and running.

My Windows 10 laptop was on an endless loop where OpenShell kept crashing Windows Explorer, Explorer restarts and crashes again and this goes on without resolve.

I had to manually kill OpenShell process through task manager and stop it from re-launching to get Explorer to stop crashing, all worked fine once OpenShell process was dead but then I get the default Start Menu back urgh!

I want to provide all information I can in order to troubleshoot this and have OpenShell up and running without crashing Windows Explorer constantly so please advise!

**Comment by ge0rdi** [comment]
Please, create [crash dump](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-create-dump-on-Windows-Explorer-crash) and upload it somewhere.

**Comment by PrincesssCadence** [comment]
Dear ge0rdi please find link below:
https://mega.nz/#!f0ACjK7A!fZd-vl9pTWN7mPvxdtUDkPhcq9z1w1Lbqp2SJtckjVY

**Comment by ge0rdi** [comment]
Crash happened inside `C:\Windows\System32\igfxCPL.cpl` which is part of Intel GPU drivers.

It may be somehow related to `OpenShell`, but I don't see how.
There are no public symbols for Intel binaries available. So I'm not even able to see proper stack trace :(

I'd suggest to report this (and provide crash dump) to Intel support (or forums).

In the meanwhile you may try to disable `igfxCPL.cpl` using [Autoruns](https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns). I'd say it is not vital component of Intel drivers (though this is just my personal opinion).

**Comment by PrincesssCadence** [comment]
Follow up:

I simply deleted the igfxCPL.cpl entirely from System32 and I haven't noticed any issue with the iGPU functionality while Open Shell no longer is causing Windows Explorer to crash.

Problem seems to have been fixed, so I couldn't be more thankful! I really appreciate the attention.

**Comment by CopperStar9** [comment]
Same thing happened to me. I dont like deleting System32 files tho.
