### ISSUE TITLE
[v4.4.185+] Some Windows app icons fail to load.

### ISSUE THREAD

**Issue by Shadowized** [Open-Shell/Open-Shell-Menu#1339]
### Describe the bug

After upgrading Open-Shell to **v4.4.189** I noticed some System App icons were failing to load and at first I thought it was the Windows thumbnail cache so I purged all of that and the issue persisted through multiple reboots. Dug into it a bit further and it appears to be an Open-Shell issue,  Specificially **v4.4.185** and later, **v4.4.184** is the last version for me that doesn't have this problem.

I placed a shortcut to one of the apps with a broken icon on my desktop and that was broken as well, here's a relevant screenshot to illustrate the problem.
![openshell_icon_bug](https://user-images.githubusercontent.com/5408749/221431290-c9ac70a5-d57d-41fc-b637-ded958383ef7.png)

### Area of issue

Start menu

### To reproduce

1. Install **v4.4.185** or newer
2. open the startmenu
3. type "features"
4. some icons don't load.

### Expected behavior

the icons to load normally.

### Open-Shell version

v4.4.185 - v4.4.189

### Windows version

Windows 10 22H2

### Additional context

FWIW, I also tested in some VM's with varying versions of Win10 including 1909, 21H2, and 22H2 LTSC IoT and all exhibited the same behavior.

**Comment by trungsamset0** [comment]
Im having the same bug, i cant even right click to open properties

**Comment by Shadowized** [comment]
I mentioned in my initial post that I cleared the cache and that did nothing, copying the cache from one machine to another is not a real solution to anything because the next time the cache gets cleared the problem comes back.

**Comment by trungsamset0** [comment]
heres another fix : https://www.tenforums.com/tutorials/8703-restore-default-file-type-associations-windows-10-a.html#option2

**Comment by Shadowized** [comment]
That is not at all relevant to this bug because the applications launch just fine - it's just not able to display the icons properly. if you actually read my initial submission you would have noticed that I tested this in multiple VM's and was able to reproduce the problem there too meaning its an issue with Open-Shell not my setup. No offense but please stop trying to "help" me.

**Comment by bonzibudd** [comment]
There’s a chance this is a bug caused by an incompatibility in the VS2022 switch.

**Comment by ge0rdi** [comment]
> There’s a chance this is a bug caused by an incompatibility in the VS2022 switch.

What makes you think so?
Are you able to replicate the issue as well?

**Comment by Shadowized** [comment]
> There’s a chance this is a bug caused by an incompatibility in the VS2022 switch.

Well I already had VS2019 installed so I tried test that theory, I cloned the repo locally and reverted e25b656275c68a3970bd3cc2a42749bb950b1754 to see if I could compile it, For some reason it kept failing to compile unless I also reverted 2a7fc0034cb410b5cabfbc37156e77710d9a8da7, once I did that it compiled fine.

After copying the two DLL's and main EXE to their correct locations plus purging my thumbnail cache for consistency it seems to work fine and all the icons load correctly, So perhaps there is something to it being caused by VS2022, or that other commit I mentioned above, I'm fairly confident of the issue being somewhere in the `StartMenuHelper` module though.

**Comment by ge0rdi** [comment]
@Shadowized 
Can you see proper icons when you open our virtual modern settings folder using `shell:::{82E749ED-B971-4550-BAF7-06AA2BF7E836}`?
Or are they missing there too?

**Comment by Shadowized** [comment]
@ge0rdi 
They are missing there as well.
![Explorer_2023-03-04_09-31-56](https://user-images.githubusercontent.com/5408749/222908253-91e51310-407f-4f7a-9aa5-405c3037f613.png)

**Comment by ge0rdi** [comment]
Could you attach `%LOCALAPPDATA%\OpenShell\ModernSettings.dat` file here?

**Comment by Shadowized** [comment]
Sure, 
[ModernSettings.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/10888946/ModernSettings.zip)

**Comment by ge0rdi** [comment]
The file seems to contain proper data. And for me it shows proper icons.

Also it is weird that icons are missing only for some items as we are generating them the same way for each one.
I have really no clue what could be wrong (and without replicating and debugging I'm afraid I can't help much).

**Comment by Shadowized** [comment]
Make sure to clear your thumbnail cache in explorer, otherwise it'll appear fine for a while until the entries get purged.

**Comment by ge0rdi** [comment]
How exactly are you clearing the cache? (so that I will do the same thing)

**Comment by Shadowized** [comment]
I delete all the .db files inside of `%userprofile%\AppData\Local\Microsoft\Windows\Explorer` with a batch while explorer isn't running.

**Comment by ge0rdi** [comment]
It still works fine for me.

**Comment by Shadowized** [comment]
Fair enough, I'll try to poke around and see if I can find a better way to replicate or solve it then. Funnily enough I created a new user profile on one of the VM's and that profile worked fine so I guess that's a start.

**Comment by Shadowized** [comment]
After seeing a new use profile fix the issue I went back to the original ones and used bleachbit to nuke the other caches multiple times, then did a reinstall of openshell and now its fine so I'm confused but... I'm going to chalk this up to windows being stupid.

**Comment by Hiche3** [comment]
Same issue, with the exact same icons showing (and not showing) when typing in "features", after upgrading from 4.4.170 to 4.4.190.

I cleared windows icon cache and repaired Open Shell, made no difference.

I then deleted %LOCALAPPDATA%\OpenShell\DataCache.db and ran the installer again (no changes just clicking all the way through), and that fixed the issue.
