### ISSUE TITLE
Open Shell- explorer hang about once per session at random point

### ISSUE THREAD

**Issue by dalchina** [Open-Shell/Open-Shell-Menu#134]
Hi, I had been using CS for years. Towards the end of my use of build 1709, explorer started to hang badly- it takes a long time to crash unless terminated via task manager. Happens when I click in the start button to launch either Classic or Open Shell (latest).

Have looked at numerous procdumps and tried reversing changes around the time this started without any relief from this. I upgraded to 1809, still the same problem.

I have attached a link to a dump file.

Whilst I have created a script to relaunch explorer when it crashes, this crash also breaks links in Settings e.g. to troubleshooters until I log off/on again.

I have read relevant posts on the old Classic Shell forum on this, and here too.

Link to 3 zipped procdump dmp files:
https://app.box.com/s/s2tlx4arvkrgd9hvmp3fpahv3me6suax

Thanks

**Comment by dalchina** [comment]
No response? Oh dear.

I have two choices. Either I use a small script I've written to crash explorer after I log on so as to generally not experience this bug,

or

I abandon Open Shell.

The latter is starting to look attractive.

I've spent a lot of time trying by elimination to stop this happening without success.

**Comment by dalchina** [comment]
I have spent 10s of hours doing procdumps and trying to use a process of elimination. I told you I have read threads on this in Classic Shell forum. Frankly you insult me my then saying I should search for existing issues when I plainly said I had.

I am a very experienced member of tenforums, and devote a lot of my time helping people their - for free. It is unfortunate the same attitude is not present here.

Good bye. And  Good bye Open Shell.

**Comment by XenHat** [comment]
#107 
#132
#133

While we value procdumps, there's no garantees we can solve it as explorer itself became a pile of shit since the anniversary update. 
You can stop using Open Shell if you desire so. You're not paying us, and we're not forcing you.

**Comment by dalchina** [comment]
I have advised tenforums not to bother seeking help on this program, and of the nature of the response.

Have a nice day.

**Comment by XenHat** [comment]
Your issue is unrelated to this software and reproducible in the absence of this software. I have advised you of the situation and of the rude and unhelpful nature of your responses.

Have a nice day.
