### ISSUE TITLE
Outdated layout in latest Windows 10 build and compilation

### ISSUE THREAD

**Issue by TehPlayer14** [Open-Shell/Open-Shell-Menu#135]
It duplicates that bar in explorer.exe

![obraz](https://user-images.githubusercontent.com/7756773/51673443-5584c780-1fce-11e9-8c3e-95508880ae99.png)

**Comment by ge0rdi** [comment]
It doesn't exactly _duplicate_ standard status bar. It shows different kind of information.

You can disable it by unticking `ClassicExplorer settings -> Status bar -> Show status bar` if you don't like it.

**Comment by isral** [comment]
@ge0rdi 
I just installed 1903 (before 1803) and I immediately noticed that I have 2 status bars.
It's not happen in 1803 with classic shell, so it is a bug.
Request to reopen this bug.
