### ISSUE TITLE
Left clicking and shift clicking the Windows 11 start button cannot open Open-Shell

### ISSUE THREAD

**Issue by Rakirs21** [Open-Shell/Open-Shell-Menu#1350]
### Describe the bug

In Windows 11, left clicking and shift-clicking the Windows start button will only open the default Windows 11 start menu and will not open the Open-Shell start menu. Settings in the "Controls" tab are set to "Left Click opens: Open-Shell Menu" and "Shift+Click opens: Open-Shell Menu".

![image](https://user-images.githubusercontent.com/41799469/223268940-33a1bf78-e7c1-4e27-9865-ef524e09c8a5.png)

### Area of issue

Taskbar

### To reproduce

1. Open "Open-Shell Menu Settings" and navigate to the "Controls" tab.
2. Set "Left Click opens:" and "Shift+Click opens:" to "Open-Shell Menu" then click Ok.
3. Click and/or shift+click the Windows 11 start button.

### Expected behavior

I expected the Open-Shell start menu to open.

### Open-Shell version

4.4.170

### Windows version

Windows 11 Home 22H2

**Comment by ge0rdi** [comment]
Please, use latest [pre-release](https://github.com/Open-Shell/Open-Shell-Menu/releases).
Only that does properly support Windows 11.

**Comment by deanhouseholder** [comment]
This fixed my issue!

**Comment by ItsJustRuby** [comment]
This is still occurring for me on 4.4.191 and Windows 11 Build 21996.1.

How can I help fix this issue?

**Comment by ge0rdi** [comment]
@ItsJustRuby 
The best thing you can do is to use official Windows 11 build instead of some old development build.

Windows 11 22H2 has build 22621.

Just update your Windows. We don't support old unofficial builds.

**Comment by ItsJustRuby** [comment]
Thanks, getting right to it! 👍
