### ISSUE TITLE
Random Missing Icons

### ISSUE THREAD

**Issue by refriedfood** [Open-Shell/Open-Shell-Menu#1352]
### Describe the bug

Icons randomly disappear within the start menu, pin menu, and jump list(?). Even after clearing window's icon db, and rebuilding the cache, it still persists and is permanent. I recently went back to version 4.3.1 (classic shell), and the problem is still there--only by a smaller margin--it always starts off fine, but then gradually seems to creep up with no rhythm or reason over a period of time.

![image](https://ptpimg.me/8vr491.png)

### Area of issue

Start menu

### To reproduce

Start > 
Start > All programs
Start > All programs > Directories

### Expected behavior

The icons to show as they do for the others.

### Open-Shell version

4.4.170

### Windows version

w10 pro 19h2 1909.18363.449

### Additional context

If you need the xml config file, I'd be glad to post it.

**Comment by refriedfood** [comment]
I did that already, as I stated. This is with both 44170 and 4.3.1 classic shell, meaning it's still a possible issue.

**Comment by ge0rdi** [comment]
Can you try also with latest pre-release?

If that doesn't help then backup your `Open-Shell` settings (save to XML) and then reset settings (`Reset all settings`).
To see if the issue is still there with default settings.

**Comment by refriedfood** [comment]
I'll give that a shot. It may take a while before I know or not if it works, as it always seems to start out fine, and then over a month or so they randomly start disappearing.
