### ISSUE TITLE
"Show status bar" not working anymore after KB4480955?

### ISSUE THREAD

**Issue by mimamue** [Open-Shell/Open-Shell-Menu#139]
Hi there, 
since this morning (or yesterday?) I realise that the "Show Status Bar" feature doesn't work anymore in Windows 7 Windows Explorer.
Everytime I start Windows Explorer again, I have to manually activate the Status Bar again in the "View" menue. I have already updated to the latest version of Open Shell (4.4.131), with no effect :-(
Since yesterday this worked perfectly for years on my PC, but suddenly the status bar is gone again and again ... what happened? Can anyone confirm the same issue on his Windows 7 (Home Premium, 32 Bit), with all latest Windows Updates? Just yesterday I installed Windows update KB4480955  (Preview for monthly quality rollup), http://support.microsoft.com/help/4480955.
Please help :-) THANKS A LOT!!!!

**Comment by XenHat** [comment]
While we do not actively prevent use of Open Shell on Windows 7, I believe it is primarily developed, tested and used on Windows 10 so testing for older OSes is difficult.
I refuse to install windows 7 again, but maybe another developer can take a look at it.

**Comment by mimamue** [comment]
Nobody out there to help a poor, lonesome Win 7 user missing his status bar? :-(

**Comment by mimamue** [comment]
Finally found the solution here, works even without Open Shell:
https://www.sevenforums.com/tutorials/61523-status-bar-turn-off.html
