### ISSUE TITLE
Classic Shell Branding needs to be removed

### ISSUE THREAD

**Issue by GTK66** [Open-Shell/Open-Shell-Menu#141]
The CS Branding needs to be removed especially if you expect the update to work as it points to CS and not to Open Shell.

[img]https://i.imgur.com/8nQ0Oss.png[/img]

**Comment by blackcrack** [comment]
not removed, changed to the right link.. there on Github.

**Comment by GTK66** [comment]
That is what I meant, if you bothered to look at the image I posted you would get it.
[img]https://i.imgur.com/8nQ0Oss.png[/img]

**Comment by LeeBinder** [comment]
I 2nd this recommendation.
