### ISSUE TITLE
Show frequent programs in menu not working

### ISSUE THREAD

**Issue by neverstop123** [Open-Shell/Open-Shell-Menu#149]
When I select show frequent programs and go days with using my PC as normal the menu stays empty. Show recent apps works but not the frequent programs.

**Comment by ge0rdi** [comment]
`Open-Shell` uses information about frequently used program that Windows tracks (at least on Windows 10).
If you don't see anything there, then most likely you have this tracking disabled.

To enable it follow these steps:

- Press `Win+I` keys to open Windows 10 Settings and select `Privacy` settings and then click on the `General` link.
- Enable  `Let Windows track app launches to improve Start and search results` setting.

https://www.thewindowsclub.com/show-most-used-apps-settings-is-disabled-greyed-out

**Comment by ibuprophen1** [comment]
The following link is also very helpful too... 

https://www.tenforums.com/tutorials/118039-enable-disable-most-used-apps-start-menu-windows-10-a.html


~Ibuprophen

**Comment by neverstop123** [comment]
> `Open-Shell` uses information about frequently used program that Windows tracks (at least on Windows 10).
> If you don't see anything there, then most likely you have this tracking disabled.
> 
> To enable it follow these steps:
> 
> * Press `Win+I` keys to open Windows 10 Settings and select `Privacy` settings and then click on the `General` link.
> * Enable  `Let Windows track app launches to improve Start and search results` setting.
> 
> https://www.thewindowsclub.com/show-most-used-apps-settings-is-disabled-greyed-out

Thank you, this fixed it!
