### ISSUE TITLE
Combine Control Panel and PC Settings search results

### ISSUE THREAD

**Issue by DragoCubed** [Open-Shell/Open-Shell-Menu#15]
As time goes on, more and more Control Panel settings are moving to the settings app. It would be great to not have to move up/down as much to get to a setting by combing them

**Comment by ibuprophen1** [comment]
It looks like this is a duplicate issue of https://github.com/Open-Shell/Open-Shell-Menu/issues/57 that's been discussed in more detail there as well. 

I'm going to close this one as a duplicate and further discussion to be referred to the other issue. 


~Ibuprophen

**Comment by DragoCubed** [comment]
Aw. I'm not used to having older things marked as a duplicate of newer things. Yesterday someone on AskUbuntu did that to me.

**Comment by ibuprophen1** [comment]
I had no intention to make it appear in that light and i do apologize if i did...

It's just that the issue i had referenced had much more activity regarding the same/similar issue and this specific issue has just been (unintentionally) stale for quite some time.

I've currently been scrubbing through as much issues as i can that are quite old and trying to help to either get some progress going in some fashion OR close what has been addressed, resolved, etc... as the issues on GitHub can get out of hand very easily/quickly.

I do hope you understand what I'm expressing via text... :+1: 


~Ibuporophen
