### ISSUE TITLE
Cannot enable right-click or drag-and-drop in Open Shell Menu.

### ISSUE THREAD

**Issue by b1scu1t** [Open-Shell/Open-Shell-Menu#1508]
### Describe the bug

The 'Settings for OpenShell' window would have the 'Enable Right-Click Menu' and 'Enable Drag-and-Drop' checkboxes disabled. Both would indicate that they are 'Locked by the Administrator', on a fresh install of OpenShell. As a result, I cannot right-click items in the start menu.

### Area of issue

Start menu

### To reproduce

1. Launch OpenShell (via start button or StartMenu.exe)
2. Right-click on start button and enter OpenShell settings.
3. Search for 'right-click'.
4. Locate the checkbox to enable right-click menu (It's greyed out...)

### Expected behavior

The user would be able to toggle the setting on.

### Open-Shell version

4.4.170

### Windows version

Windows 10 Enterprise LTSC 1809 (Build Version 10.0.17763)

### Additional context

It would state that the setting is 'Locked by the Administrator', but I have installed the Group Policy templates located at  `C:/Program Files/Openshell", as instructed by the Policy Definitions document. I've gone through Group Policy Editor and explicitly disabled any restrictions for all users, still nothing. Running Start Menu as administrator doesn't work either.

**Comment by ge0rdi** [comment]
You have those settings overridden somehow.

Try to delete following registry keys:
`HKEY_LOCAL_MACHINE\SOFTWARE\OpenShell\StartMenu`
`HKEY_LOCAL_MACHINE\Software\Policies\OpenShell`
`HKEY_CURRENT_USER\Software\Policies\OpenShell`

**Comment by b1scu1t** [comment]
I have deleted all three keys as instructed, but it is still locked. Now I get 'This setting has been blocked by a group policy'.
![image](https://user-images.githubusercontent.com/41207956/226226267-1ece3d6e-00a4-4da7-b00d-312a41f72c8a.png)

I've also tested the latest preview build, as seen in the screenshot. It has the same problem. 
Thanks for your help thus far!

**Comment by ge0rdi** [comment]
Hmm, I have checked code and there is one more case when these settings are _locked_.
If `SHRestricted(REST_NOCHANGESTARMENU)` call returns true.
According to [documentation](https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/ne-shlobj_core-restrictions) it means:

> If nonzero, the system administrator has disabled the ability to make changes to the Start menu. Applications should disable any feature that enables the user to reorganize their Start menu.

Though I don't know where exactly this can be set by Administrator :(
But apparently you have something set in system (by your Administrator?) and `Open-Shell` honors it.

**Comment by b1scu1t** [comment]
Damn, I did find it weird that no-one else seems to complain about this. It may be that my registry is borked. Should I close this?

**Comment by ge0rdi** [comment]
> It may be that my registry is borked.

Not necessarily. You (or someone else that can admin your machine) may have just set some setting that is meant to prevent changes in Windows Start menu (maybe in the past and then forgot about it?).

You can check this for example:
https://www.isunshare.com/windows-10/disable-changing-taskbar-and-start-menu-settings-in-windows-10.html

Or google for other ways how Administrator can prevent changes to start menu.

> Should I close this?

Well, I don't think there is any issue in `Open-Shell` regarding this.

**Comment by b1scu1t** [comment]
Found it! 
There are two ways to disable changing taskbar/start-menu settings; via Group Policy Editor or by the Registry.

It turns out that there WAS a switch flipped in the Registry. 
With Registry Editor, go to `\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer` or `\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer` and look for the `NoChangeStartMenu` value. Right-click and modify, change the data value to `0` and log-out. It works when you login again.

I do not remember ever creating or changing these values. I think it is some other third-party software, like ShutUpWindows10 or WinAero Tweaker that did this.

Either way, not Open-Shell's problem, thanks @ge0rdi  for the quick assistance!

**Comment by ge0rdi** [comment]
@b1scu1t 
Thank you for letting us know.

Based on your info, I think it can be also set in Group Policy editor:
`User Configuration` -> `Administrative Templates` -> `Start Menu and Taskbar` -> `Prevent users from customizing their Start Screen`
(that should correspond to given registry key)
