### ISSUE TITLE
Please help.

### ISSUE THREAD

**Issue by Twig6943** [Open-Shell/Open-Shell-Menu#1513]
### Describe the bug

Open Shell  broke my file explorer please help I beg theres a white line that annoys me
![image](https://user-images.githubusercontent.com/119701717/227707113-d183a001-0b34-46ab-8778-63b9e4c27d0b.png)

### Area of issue

Windows Explorer

### To reproduce

Install open shell on windows
disable the menu in explorer 
close and reopen the file explorer
and the white line will be there

### Expected behavior

I expected the open shell toolbar to just disappear

### Open-Shell version

4.4.170

### Windows version

Win 10 Ltsc 21h2

### Additional context

Open Shell  broke my file explorer please help I beg theres a white line that annoys me
![image](https://user-images.githubusercontent.com/119701717/227707113-d183a001-0b34-46ab-8778-63b9e4c27d0b.png)

**Comment by Alluseri** [comment]
I'm pretty sure you can fix it by just reinstalling Open-Shell without the "Classic Explorer" option enabled:
<img src="https://cdn.nest.rip/uploads/71beffbe-245e-4c8c-924b-164360f13621.png">

**Comment by TSBII** [comment]
This line is created due to IE .dll files that are still being used by Edge e.g. still intrinsic to the OS.
Use this to get rid of that line permanently:

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Toolbar]
"Locked"=dword:00000001

**Comment by ge0rdi** [comment]
> This line is created due to IE .dll files that are still being used by Edge e.g. still intrinsic to the OS.
Use this to get rid of that line permanently (it locks the IE toolbar ---that cannot be used anymore without hacking IE back into existence anyway)

I'm not sure how this is related to `Open-Shell`.
Anyways, it seems you have solved your issue.

**Comment by RandomMonkey99** [comment]
Im having the same issue but it finnaly goes away!
Thank you!!!!!
