### ISSUE TITLE
The never ending issue

### ISSUE THREAD

**Issue by andika207** [Open-Shell/Open-Shell-Menu#1516]
### Describe the bug

now it seems to be fixed but from time to time explorer.exe crashes on startup and I can do nothing until I close the classic-shell process on taskbar manager.
it's happened with any release so do not ask me for the version number

Firma con problemas:
  Nombre del evento de problema:	APPCRASH
  Nombre de la aplicación:	explorer.exe
  Versión de la aplicación:	6.1.7601.17514
  Marca de tiempo de la aplicación:	4ce7a144
  Nombre del módulo con errores:	StartMenuDLL.dll
  Versión del módulo con errores:	4.4.189.0
  Marca de tiempo del módulo con errores:	63c8f1c5
  Código de excepción:	c0000005
  Desplazamiento de excepción:	000000000003ad9d
  Versión del sistema operativo:	6.1.7601.2.1.0.256.48
  Id. de configuración regional:	3082
  Información adicional 1:	d2bb
  Información adicional 2:	d2bba6aa3ce9e987f42dfbea45ef990f
  Información adicional 3:	1f06
  Información adicional 4:	1f067ab9abf7a9eb1f333920372d402a

### Area of issue

Installation/Other

### To reproduce

START UP

### Open-Shell version

ALL

### Windows version

W7 x64

**Comment by Alluseri** [comment]
What's the point of using Open-Shell on Windows 7? The start menu is good as is.

**Comment by ge0rdi** [comment]
@andika207 
Please, try to obtain crash dump from the crash using steps in https://github.com/Open-Shell/Open-Shell-Menu/issues/1263#issuecomment-1365287057.

Hopefully, we will be able to see where it does crash (and why).

**Comment by ge0rdi** [comment]
No response from the OP.

**Comment by GGa-JJa** [comment]
Much time elapsed, but I believe it's the same problem that I was going to point out.
O.S. Windows 7, 64 bit, Italian.
Pictures here portrait the crash detail window (the same windows, with information scrolled a little). That is partially in Italian, also. If a translation is needed, please ask for what can't be understood (but I suppose it's the same in all languages).
This happens whenever I try to install the "classic menù".
The "classic explorer" appears to be working normally.

![fig_1](https://github.com/Open-Shell/Open-Shell-Menu/assets/127774868/a06e50fe-b176-4ca0-9758-23af2c664e6e)
![fig_2](https://github.com/Open-Shell/Open-Shell-Menu/assets/127774868/3c74f1cb-179f-4069-9228-ad5e11df6f59)

Any ideas? Workarounds?

Now I'll try the "steps in #1263"...

**Comment by GGa-JJa** [comment]
Here is the dump.
Instruction: delete the last ".zip" in the name (let them end with ".001" and ".002"), then unzip.
Sorry, but the site doesn't accept single files this big, and doesn't accept the original filenames.

[explorer.exe.744.zip.001.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/12447940/explorer.exe.744.zip.001.zip)
[explorer.exe.744.zip.002.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/12447944/explorer.exe.744.zip.002.zip)

**Comment by GGa-JJa** [comment]
Other information that may - or may not - be useful: when the OpenShell menu has just been installed, it appears to work as expected.
After a reboot, it doesn't anymore: explorer continues crashing until the OpenShell menu is uninstalled, or closed by the task manager (thanks to the OP for this method... I didn't find it myself).

**Comment by ge0rdi** [comment]
@GGa-JJa 
Thank you for the dump.

Could you, please, try build from #1678 pull-request?
I believe it should fix the issue for you.

**Comment by GGa-JJa** [comment]
Sorry for the delay, I just come back from a little vacation.

> Thank you for the dump.
Actually, thank _you_ for paying attention to my problem.

> Could you, please, try build from #1678 pull-request? I believe it should fix the issue for you.
Ehm... sorry for my ignorance about the matter... do you mean try building the .exe from the sources, or is there an already compiled version to try, somewhere?

In the first case, I'm sure some instructions do exist. Could you please just point me to them?

Thank you.
GGa.

**Comment by ge0rdi** [comment]
There is message from `AppVeyorBot` in that PR that points to actual build (on AppVeyor site).
You can click on it and download installer from `Artifacts` section.

Here is the link in case you'll have some troubles to find it:
https://ci.appveyor.com/project/passionate-coder/open-shell-menu/builds/47869291/artifacts

**Comment by GGa-JJa** [comment]
It appears to be working, now.
At least, it "survived" two reboots.

Thank you very much again!


> There is message from `AppVeyorBot` in that PR that points to actual build (on AppVeyor site).

Ouch! I didn't know I was so stupid.
... _the never ending learning_...

;-)

**Comment by ge0rdi** [comment]
Cool, thank you for confirmation.

The fix will be included in next official release (you can keep using the PR build for now).

**Comment by andika207** [comment]
I have not responded to this topic in a long while because I have been stressed with other matters.

I am still using the version **4.4.189** but didn't notice this bug anymore.... Win7 is up to date and maybe a windows update fixed this who knows...

regarding the settings everything is set by default (including the start button) I just choose the classic style menu because my main OS is WinXP and I don't expect to leave it any time soon. 

sometimes when the computer crashes, the ''my documents'' folder prompts on start up but I can live with this minor issue
