### ISSUE TITLE
Taskbar texture not showing up at all (WIN11)

### ISSUE THREAD

**Issue by Parallel00** [Open-Shell/Open-Shell-Menu#1520]
### Describe the bug

It was working fine when I first installed the software, but after Windows 11 updated, the texture wasn't showing up at all, no matter how many times I restarted Open Shell, or changed the texture, or set it to Opaque or Transparent.  The start button works fine, though.

### Area of issue

Taskbar

### To reproduce

1. try to change the taskbar texture, fiddle with the settings a bit.
2. See if it shows up

### Expected behavior

The taskbar texture showing up

### Open-Shell version

4.4.189

### Windows version

Windows 11 22H2

**Comment by ge0rdi** [comment]
Hello.
This is known issue in recent Windows 11.
No taskbar customizations work there.
See #1342 for more info.
