### ISSUE TITLE
Add more options for Start button Replacement

### ISSUE THREAD

**Issue by jsaue003** [Open-Shell/Open-Shell-Menu#1528]
### Is your feature request related to a problem? Please describe.

The Start Button replacement feature is great, but I find it strange how there's no matching Windows 95/98/XP start menu image and that you have to find and download one separately. 

### Describe the solution you'd like

Add some extra options for Start button replacement, the least of which would be the windows 98 classic start menu icon. 

http://classicshell.net/forum/download/file.php?id=1922

![image](https://user-images.githubusercontent.com/32148757/232252759-3b193fee-32b1-49fb-be98-3ed1862dc732.png)

### Area of issue

Taskbar

**Comment by ge0rdi** [comment]
There is built-in `Classic` button style that is meant to match Classic skin.

Each user may want something different, that's why there is the option to use own start button image.
I don't think we'd like to add more such default images.
