### ISSUE TITLE
Add an option for custom Windows Version name in the Start Menu

### ISSUE THREAD

**Issue by jsaue003** [Open-Shell/Open-Shell-Menu#1529]
### Is your feature request related to a problem? Please describe.

In the Start Menu, it shows your current windows version (i.e. Windows 10) vertically. I am not able to find a setting to change this to a classic name i.e. Windows 98

![image](https://user-images.githubusercontent.com/32148757/232253211-6662229a-ffb1-468e-8a53-4654b1ef3f9d.png)

### Describe the solution you'd like

I would like an option to customize the side portion of the Start Menu so it can say 'Windows 98' instead of Windows 10 Home

### Area of issue

Start menu

**Comment by ge0rdi** [comment]
There is `Menu Look` -> `Menu Caption` setting where you can put custom text that will be displayed instead of current Windows version.

**Comment by jsaue003** [comment]
> There is `Menu Look` -> `Menu Caption` setting where you can put custom text that will be displayed instead of current Windows version.

Thanks  @ge0rdi  - user error on my part not seeing that. Any way to mimic the "classic look" of Windows though? Adding an image below. It has either an image of Windows98, or really badly textured 'WINDOWS98' text. 

![image](https://user-images.githubusercontent.com/32148757/232312522-b1a1aedd-f43e-4443-953b-41fc03706cbe.png)

**Comment by ge0rdi** [comment]
I'd say you can create your own custom skin that will use that picture from Windows 98 on the left.

**Comment by jsauerland** [comment]
@ge0rdi After extensive researching... I discovered this is likely way, way out of my skillset. I wasn't able to figure out how to do it. Thanks btw!
