### ISSUE TITLE
No option to do just straight shutdown for Windows XP style menu, unlike Windows 7

### ISSUE THREAD

**Issue by YamiYukiSenpai** [Open-Shell/Open-Shell-Menu#1530]
### Is your feature request related to a problem? Please describe.

Windows 7 has the option to not prompt you to which option I want to do after I click "Shutdown", and is currently the default behavior:
![image](https://user-images.githubusercontent.com/13153124/232366220-33b00855-a473-43d8-b279-35ef4ac1c9e9.png)

This is what I get for Windows XP:
![image](https://user-images.githubusercontent.com/13153124/232366020-f9f80a04-53d0-43f6-a0c8-4f9951b96a18.png)

### Describe the solution you'd like

Give Windows XP the option to just do a straight-up shutdown if the menu is clicked.

### Area of issue

Start menu

**Comment by ge0rdi** [comment]
`Shutdown command` option is available only for `Windows 7 style` start menu style.
It doesn't depend on Windows version.

Moreover Windows XP is not even supported by this program.

**Comment by YamiYukiSenpai** [comment]
I meant Windows XP-style.  Pretty sure it was a given based on the theme
