### ISSUE TITLE
Jumplists doesn't seem to work

### ISSUE THREAD

**Issue by eastwing27** [Open-Shell/Open-Shell-Menu#1537]
### Describe the bug

I have jumplists enabled but it doesn't look like they appear in any way
![изображение](https://user-images.githubusercontent.com/32394236/234058622-97937e0b-bb07-4313-b1e2-512895eab677.png)

I did open several project with both VS and VS Code so if I get thi correctly, the menus should appear by this moment. Now, I use Windows 11, could it be the reason?

### Area of issue

Start menu

### To reproduce

Enable jumplists (when using with Windows 11?), add apps to the main menu and open several projects / docs.

### Open-Shell version

4.4.170

### Windows version

Windows 11 22H2

**Comment by ge0rdi** [comment]
Could you try if there is any difference with latest [pre-release](https://github.com/Open-Shell/Open-Shell-Menu/releases) build?

Does original Windows start menu show jump lists (recently opened documents) for VS and VS Code?

**Comment by eastwing27** [comment]
> Does original Windows start menu show jump lists (recently opened documents) for VS and VS Code?
Not sure, but it did work on Windows 10 (though I was using Classic Shell Menu before it brcame Open Shell)

Will try the pre-release and let you know

**Comment by ge0rdi** [comment]
> Not sure, but it did work on Windows 10

You can easily check.
Just use `Shift+Win` to show original Start menu and search for VS / VS Code to see if it will offer recently opened items.

**Comment by eastwing27** [comment]
@ge0rdi Yeah, you're right, I can't see any recent documents in the native Start menu. Not sure what's wrong, I've checked the settings and it looks like they're on. Anyway, it looks like it's more of a Windows 11 problem, not Open Shell one.

**Comment by ge0rdi** [comment]
Make sure you have `Show recently opened items ...` enabled in `Settings > Personalization > Start`.

![image](https://user-images.githubusercontent.com/2453094/234489519-b1872a47-b881-4804-a20e-64e210c13c1c.png)

**Comment by eastwing27** [comment]
That option was on. The recent files were off in Explorer settings (the ones you open via tiop popup menu). So, now jumplist does work for VS and Notepad++ - but not for VS Code.
I can assume the reason is "big" VS uses solution files while for VS Code projects are folders
