### ISSUE TITLE
have all dependencies, but setup wont work

### ISSUE THREAD

**Issue by LilithHatesPython** [Open-Shell/Open-Shell-Menu#1539]
### Describe the bug

![image](https://user-images.githubusercontent.com/125330887/235047611-b3b6e861-3aeb-43d8-9c94-b9cef964b640.png)
crashes right after this shows

### Area of issue

Installation/Other

### To reproduce

Downloaded all dependencies, tried to setup

### Open-Shell version

4.4.170

### Windows version

windows 10 21H2

**Comment by ge0rdi** [comment]
You can remove `@echo off` in `__MakeFinal.bat` to see what commands were executed.

Also in `BuildInstaller.bat` you can remove ` > nul` at line:
`hhc ..\Localization\%CS_LANG_FOLDER%\OpenShell.hhp > nul`
to see output of Help compiler.
