### ISSUE TITLE
Tried uninstalling openshell but only fucked up my windows 11 pc

### ISSUE THREAD

**Issue by SaucePan10** [Open-Shell/Open-Shell-Menu#1541]
### Describe the bug

So I downloaded open shell to make my taskbar transparent, while I was trying to make it transparent realised my start menu was changed to the Windows 7 start menu. I tried to fix it but couldn't and out of frustration I went to add/remove program features after I started the setup of uninstalling it My Pc bugged out and I couldn't see anything. I restarted it and my screen was a greyish colour I couldn't see anything on it but the start menu was still functional although I couldn't see it. When I tried uninstalling it again it said this app is in a different location I searched my pc but couldn't find it. Please help me fix this issue.                                                

![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/133041470/1583c6fe-fcd4-48a8-a9a0-55ad9805d063)

### Area of the issue

Start menu, Taskbar

### To reproduce

Open the open-shell application
Got to add/remove the program thing in the start menu
Try removing the open shell with the setup
Restart your PC with the physical start button
and viola you have successfully fucked up your pc

### Open-Shell version

Latest version I think

### Windows version

Windows 11

**Comment by ge0rdi** [comment]
What version of `Open-Shell` were you using?
Did the uninstaller report some error?
You may try to install it again (ideally using latest installer).

**Comment by sydbarrett74** [comment]
@SaucePan10: I understand your frustration with the bricking of your PC, and I curse as much as the next bloke, but do you _have_ to use expletives in your issue title? Not judging, just saying...

**Comment by ge0rdi** [comment]
Closing as there was no response from author of the issue.
