### ISSUE TITLE
Status bar font displays incorrectly if font size is 8

### ISSUE THREAD

**Issue by aubymori** [Open-Shell/Open-Shell-Menu#1547]
### Describe the bug

When you set the status bar's font to a font of size 8, it displays at a smaller size.
![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/44238627/38d48cb0-c94d-4ac5-82f1-04cf9365f376)

### Area of issue

Windows Explorer

### To reproduce

1. Open Classic Explorer Settings
2. Set the status bar font size to 8
3. The font is smaller than expected

### Expected behavior

The font should be rendered at a size of 8

### Open-Shell version

4.4.170

### Windows version

Windows 8.1

**Comment by ge0rdi** [comment]
@aubymori 
Could you please try build from PR #1548?

**Comment by aubymori** [comment]
Works great.
![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/44238627/be2c41e7-0602-4f19-a9f6-cf8a51372de7)
