### ISSUE TITLE
Just a Helpful FYI... 

### ISSUE THREAD

**Issue by ibuprophen1** [Open-Shell/Open-Shell-Menu#155]
This isn't an issue I'm reporting but, more of an FYI that may be helpful in regards to some possible issues experienced in Win8,x and Win10 (possibly others). 

In short, a friend of mine asked me about something that basically boiled down to him not Unblocking the Open Shell software he had downloaded that had resolved the minor issue he had experienced between his Windows 10 and the Open Shell software installed. 

Note: This applies to any File that you download, in this case the Open Shell Software, and it came from a "Trusted Source" (What you and/or the developer(s) deems as a Trusted Source NOT what Microsoft/Windows deems as trusted). 

The following image is simple and easy to follow (it says it all):

![UnBlocking-OpenShell](https://user-images.githubusercontent.com/18060271/54463090-49a0c080-4748-11e9-9595-8fcf598737c1.jpg)

You'll be surprised by how many individuals aren't aware of this as well. 

Note: This is NOT a solution to all the problems but, it may/might resolve a few/some/many problems individuals may be experiencing. 

Thank you all very much for your time and understanding with this! :-) 

~Ibuprophen

**Comment by blackcrack** [comment]
^^Sticky !

:clap: :+1:
