### ISSUE TITLE
bottom left corner click opens windows start menu and not open-shell

### ISSUE THREAD

**Issue by rica01** [Open-Shell/Open-Shell-Menu#1550]
### Describe the bug

Hello.

I changed the default image for the start button. There is something like a 1px border right on the left and bottom parts of the screen where, if clicked, the regular windows menu is opened. It is as if the custom image does not starts at position 0,0 but at 1,1; so clicking at 0,0 (bottom left) "bypasses" the custom image and the click lands on the windows button.

![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/11340563/60a1f567-1ebe-495d-829c-0ebc45a626fd)

### Area of issue

Start menu, Taskbar

### To reproduce

1. change the standard image for a custom one.
2. click on the bottom left corner
3. see the normal windows menu pop up

### Expected behavior

i expecte to see open shell

### Open-Shell version

4.4.170

### Windows version

windows 11 (Microsoft Windows [Version 10.0.22621.1702])

**Comment by ge0rdi** [comment]
Please, use [latest build](https://github.com/Open-Shell/Open-Shell-Menu/releases) for compatibility with Windows 11.
