### ISSUE TITLE
Wrong monitor placement 

### ISSUE THREAD

**Issue by Gogo64pro** [Open-Shell/Open-Shell-Menu#1554]
## Describe the bug

Pressing the Windows key brings up open shell menu to the non-primary screen if `Open Window Start menu on monitor with the mouse` setting is off. This may be happening because of cable arrangement on gpu. 

### Area of issue

Start menu

## To reproduce
Press windows key

### Expected behavior

Open shell menu opens up on primary screen

## Open-Shell version

4.4.189

## Windows version

Windows 10 22H2

**Comment by ge0rdi** [comment]
Are you sure you have properly selected your _primary_ display in Windows display settings?

See this [guide](https://www.thewindowsclub.com/change-primary-and-secondary-monitors-on-windows-10) for example.
There needs to be `Make this my main display` checkbox checked for display you want to be primary.
