### ISSUE TITLE
Open Shell does not show up anymore after windows update

### ISSUE THREAD

**Issue by Chaosruler972** [Open-Shell/Open-Shell-Menu#1557]
### Describe the bug

I updated recently my windows to the newest build, open shell does not show the windows 7 menu shell, it shows the "stock" windows 11 instead

Windows 11 Pro
Version: 22H2
OS build: 22621.1778
Experience: Windows Feature Experience Pack 1000.22642.1000.0
System type: 64-bit operating system, x64-based processo

### Area of issue

Start menu

### To reproduce

* press the start menu button

### Expected behavior

I expected the old (windows 7 style) menu bar to appear.

however, the regular one appeared instead.

### Open-Shell version

4.3.1

### Windows version

Windows 11 22H2

### Additional context

resolve attempts:
* uninstall and reinstall menu shell (with restarts)
* trying to open MenuShell executable manually (at C:\Program Files\Open-Shell\StartMenu.exe)

**Comment by ge0rdi** [comment]
`4.3.1` is obsolete `Classic-Shell` version (`Open-Shell` ancestor).

For Windows 11, please, install [latest Open-Shell build](https://github.com/Open-Shell/Open-Shell-Menu/releases).
