### ISSUE TITLE
Document dependency on Windows 10 settings for frequent programs

### ISSUE THREAD

**Issue by dazworker** [Open-Shell/Open-Shell-Menu#156]
As discussed in #149, on Windows 10, the list of frequent programs in the start menu depends on Windows settings. I stumbled upon the same problem and tracked down the solution myself because as far as I can see, this closed issue is the only place where this is discussed around here.

So, while this isn't Open-Shell's fault, I think the behaviour (Open-Shell's dependency on a Windows setting, reasons that this setting might be greyed out) should be documented. I'm thinking an entry in the help, along with a short note at the setting itself (or at least the tooltip) along the lines of "See help when experiencing problems on Windows 10".

**Comment by dazworker** [comment]
I just had a look at a machine running Windows 7 and noticed that Open-Shell uses the OS Start Menu settings there as well; the difference being that this probably does not depend on another privacy setting (which people might deactivate due to privacy concerns about Windows 10, thereby accidentally disabling the list).

**Comment by ibuprophen1** [comment]
I'm just curious if this issue is resolved? 👌


~Ibuprophen

**Comment by ibuprophen1** [comment]
I'm going to close this issue as Issuer Unresponsive to this submission. 

If necessary, the OP Issuer may open up a new issue. 

Thank you very much for your time, patience and understanding with this! 👍


~Ibuprophen
