### ISSUE TITLE
start menu customization doesnt work

### ISSUE THREAD

**Issue by CharlieYT567** [Open-Shell/Open-Shell-Menu#1560]
### Describe the bug

start menu appears as windows 11 

### Area of issue

Start menu

### To reproduce

.

### Expected behavior

to change the start menu

### Open-Shell version

the newest since june 6 2023 at 1:10 cdt

### Windows version

windows 11 (newest update) 

### Additional context

.

**Comment by ge0rdi** [comment]
> the newest since june 6 2023 at 1:10 cdt

Please, provide exact version of `Open-Shell` you are using.
You can find it easily by running `Open-Shell Menu Settings` shortcut.

> windows 11 (newest update)

Please, provide exact Windows 11 version as reported in `System > About` (`OS build` field).

**Comment by CharlieYT567** [comment]
fix: download [4.4.189](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.189)

**Comment by CharlieYT567** [comment]
> fix: download [4.4.189](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.189)
