### ISSUE TITLE
Win key does not trigger Open Shell anymore

### ISSUE THREAD

**Issue by FstTesla** [Open-Shell/Open-Shell-Menu#1563]
### Describe the bug

Since the Windows Update that upgraded to OS build **22621.1778**, hitting the Win key does not pop up Open Shell start menu anymore. Clicking on the Start button still works as expected.

I'm quite sure that the issue started after that upgrading to that OS build, because the same occurred on another machine with the same configuration.

### Area of issue

Start menu

### To reproduce

1. Ensure you have OS build 22621.1778 installed
2. Hit Win key
3. The default Windows 11 start menu pops up

### Expected behavior

The Open Shell start menu pops up, just as if I clicked on the Start button.

### Open-Shell version

4.4.170

### Windows version

Windows 11 22H2, build 22621.1778

### Additional context

I also have [ExplorerPatcher](https://github.com/valinet/ExplorerPatcher) version 22621.1555.55.1 installed. Open Shell and ExplorerPatcher have always worked together perfectly.

**Comment by ge0rdi** [comment]
Please, use [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) `Open-Shell` build for compatibility with Windows 11.
