### ISSUE TITLE
Windows menu overrides openshell menu

### ISSUE THREAD

**Issue by ExplosiveMine** [Open-Shell/Open-Shell-Menu#1568]
### Describe the bug

Despite having set "Windows Key Opens:" to Open-Shell menu, it still opens the windows menu for a weird reason

### Area of issue

Start menu

### To reproduce

1. Press windows key

### Expected behavior

Open-shell menu opening

### Open-Shell version

4.4.170

### Windows version

Windows 11 Pro 22H2

### Additional context

Here is  my settings
[Menu Settings.txt](https://github.com/Open-Shell/Open-Shell-Menu/files/11828937/Menu.Settings.txt)

**Comment by ge0rdi** [comment]
Please, have a look at https://github.com/Open-Shell/Open-Shell-Menu/issues/1564 .

**Comment by roger-wolfson** [comment]
I can reproduce this, on the newer version 4.4.181 which does in theory have a fix for this bug, but actually still shows the incorrect behavior for me. This broke for me in the 05-2023 monthly update and upgrading to .181 did not resolve it.

**Comment by ge0rdi** [comment]
@roger-wolfson 
> I can reproduce this, on the newer version 4.4.181 ...

You should use [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) `Open-Shell` build before reporting any bug on Win11 (as the linked issue says).

> This broke for me in the 05-2023 monthly update

Please, provide full Windows version (as reported in `Settings -> System -> About`).

**Comment by roger-wolfson** [comment]
My mistake - I saw the report was .170 and knew I'd just upgraded from that but had missed the pre-release channel.  .189 fixes it for me. 

My OS version is 22621.1848 but the break happened last month on some earlier update.

Thanks.
