### ISSUE TITLE
So many items missing

### ISSUE THREAD

**Issue by hy-net** [Open-Shell/Open-Shell-Menu#1570]
### Describe the bug

I have just got my 1st Win 11 Pro which I personally own and allowed to install Open Shell.

To my horror, so many familiar items are missing. No more **Notepad, Snipping Tool, Paint, Remote Desktop Connection** ... Just to name a few that I use almost daily

And that is the main reason we stick to Open Shell.

Using 4.4.189 (pre-release). Can someone please tell me this is a BUG, not a Feature

### Area of issue

Start menu

### To reproduce

![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/55421612/d0d01f93-9610-4066-97c5-58263f23f1a9)

### Expected behavior

![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/55421612/fb2788c9-5926-49e3-8d07-ca0ea20e4931)

### Open-Shell version

4.4.189

### Windows version

Win 11 22H2

**Comment by melabones36000** [comment]
It's not a bug. Mine is the same as yours. Has nothing to do with OpenShell. Windows 11 changed many things. Notepad, Snipping Tool, Paint, Remote Desktop Connection are not part of the Windows 11 system any longer and can be downloaded as separate programs from the Microsoft Store. That's why they are not showing in windows accessories.

**Comment by hy-net** [comment]
My mistake. Remote Desktop is still here.

@melabones36000 I just noticed notepad, mspaint and snippingtool are all moved to the Apps instead of conventional Exe.

**Comment by ge0rdi** [comment]
As @melabones36000 wrote this is not a bug.
`Open-Shell` just shows programs that are present on machine and have shortcuts in start menu folder.

If you'll find some program that is shown in standard Windows start menu and not in `Open-Shell` menu then this is something to report.
