### ISSUE TITLE
Open Shell nuked by Moments 3 Update

### ISSUE THREAD

**Issue by daknut** [Open-Shell/Open-Shell-Menu#1571]
### Describe the bug

The Open Shell Start Menu and links to the program are nuked once the Moments 3 Update has installed and been activated

### Area of issue

Start menu

### To reproduce

Windows Key brings up the W11 Start Screen

### Open-Shell version

4.4.170

### Windows version

Windows 11

### Additional context

This is by way of observation only. I run one compatible and one incompatible laptops with W11. I also look after 3 W11 laptops for old ladies. We all used to use Open Shell.

Now that the Moments 3 package has installed, Microsoft have removed Open Shell's functionality and the interface is no longer available.

The program continues to be installed but it won't operate.

**Comment by ge0rdi** [comment]
Please, make sure you are using [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) Open-Shell build before reporting a problem on Windows 11.

Official release doesn't support Windows 11 yet.

**Comment by daknut** [comment]
> Please, make sure you are using [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) Open-Shell build before reporting a problem on Windows 11.

The Open Shell version quoted was a pure guess - I tried to update before uninstalling and it was up to date. I had to complete the field so I went with what I thought was current. All five laptops have had Shell removed, unfortunately, because of the problem with Moments 3.

**Comment by ge0rdi** [comment]
I have fully updated Win11 22H2 (22621.1848) along with `Open-Shell` 4.4.189 and everything seems to be working just fine.
According to Windows Update history the KB5026446 (Moment 3) is installed.

**Comment by daknut** [comment]
> I have fully updated Win11 22H2 (22621.1848) along with `Open-Shell` 4.4.189 and everything seems to be working just fine. According to Windows Update history the KB5026446 (Moment 3) is installed.

Very strange. All five of the laptops I use or look after can no longer run Open Shell.

Having Moments 3 installed does not mean it's activated. Do you have seconds on your Taskbar or are you able to switch them on in Taskbar Settings under 'Taskbar Behaviours'? If neither, then the features aren't enabled.

In Settings/Windows Update do you have the 'Get the latest updates...' switched to 'Off'? This prevents Moments 3 activation for the time being until - so I'm reliably told - Update Tuesday in July. If you switch it 'on', Moments 3 will become immediately activated.

Let me know how you get on...

**Comment by ge0rdi** [comment]
> Having Moments 3 installed does not mean it's activated.

Right. I had to enable it manually using this guide:
https://pureinfotech.com/install-moment-3-feature-drop-update-windows-11/

Now I can see the `Show seconds in system tray clock (uses more power)` option.
I have it even enabled.

Still, `Open-Shell` works just fine for me.

Maybe just try to install [latest build](https://github.com/Open-Shell/Open-Shell-Menu/releases) again.
And if it still doesn't work try to obtain [Open-Shell log](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-obtain-advanced-Open-Shell-Menu-log).

**Comment by Bluscream** [comment]
I tried obtaining a log following the above instructions, but sadly no log gets generated when trying to open the start menu. Also the registry editor "converts" the 0xff to 41fff if that's important.

**Comment by daknut** [comment]
> I tried obtaining a log following the above instructions, but sadly no log gets generated when trying to open the start menu.

Yep. But, as I said, there is the new file in the location I stated.

It's a shame that geOrdi thought I was being 'unresponsive' - I felt that way about his replies, too. I was still investigating what the W11 Update had done to my system with reference to Open Shell when the post was closed.

**Comment by ge0rdi** [comment]
@Bluscream 
According to files you provided, you have `Open-Shell` 4.4.170 installed.
It was already [stated](https://github.com/Open-Shell/Open-Shell-Menu/issues/1571#issuecomment-1606107658) that this official release doesn't support Windows 11 yet.

You should install [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) `Open-Shell` build and use that one on Windows 11.

**Comment by ge0rdi** [comment]
@daknut 
> even a manual clicking of the exe file does nowt

You mean manually running `C:\Program Files\Open-Shell\StartMenu.exe` ?
You can create startup log like this:

- In registry key `HKEY_CURRENT_USER\Software\OpenShell\StartMenu\Settings`
- Create new `DWORD` item named `LogStartup` with value `1`
- Run `C:\Program Files\Open-Shell\StartMenu.exe`
- There should be `StartupLog.txt` created in `%LOCALAPPDATA%\OpenShell` folder
- Attach it here

> But, as I said, there is the new file in the location I stated. I was averse to delete that file and reboot but it would probably just have been reinstalled.

What file do you mean exactly?

**Comment by daknut** [comment]
> > But, as I said, there is the new file in the location I stated. I was averse to delete that file and reboot but it would probably just have been reinstalled.
> What file do you mean exactly?

Please excuse my frustration that you don't seem to reading my posts. I stated previously (in the 'other' thread) that:

"What I did find was a 'startscreen' file at C:\Users[User name]\AppData\Roaming\Microsoft\Windows\Start Menu which appeared after the upgrade."

In case you're not aware of the set up in Windows 11, the Start Menu folder location specific to an account is located at:
C:\Users\your-user-name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs.

The Start Menu folder for all users is located at:
C:\ProgramData\Microsoft\Windows\Start Menu\Programs.

Open Shell puts them together to produce the W98 Start menu.

Thanks for the info about how to create a startup log. Unfortunately, I gave up trying to get help with the problem and removed Open Shell from my OS - along with the four others that were using it.

**Comment by daknut** [comment]
> What file do you mean exactly?

I looked through the properties of the file mentioned above and it seems to have been an old OpenShell shortcut that looked in "C:\Program Files\Open-Shell\" to launch the program.

Apologies for misleading.

**Comment by Bluscream** [comment]
> @Bluscream According to files you provided, you have `Open-Shell` 4.4.170 installed. It was already [stated](https://github.com/Open-Shell/Open-Shell-Menu/issues/1571#issuecomment-1606107658) that this official release doesn't support Windows 11 yet.
> 
> You should install [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) `Open-Shell` build and use that one on Windows 11.

Where's the difference between "official release" and "latest release"? I always just use winget to download and update software

**Comment by ge0rdi** [comment]
@Bluscream 
Note that github (the link I provided) is the official source of `Open-Shell` install packages.

We didn't upload anything to `winget` repository. Though it seems to contain only official releases (not pre-releases).

**Comment by Bluscream** [comment]
> @Bluscream Note that github (the link I provided) is the official source of `Open-Shell` install packages.
> 
> We didn't upload anything to `winget` repository. Though it seems to contain only official releases (not pre-releases).

So you were basically asking me to download a beta then? That would've cleared things up for me. Either way, i downloaded the release from github and that was able to restore my open-shell menu to all it's glory. Thanks for taking a look and next time i encounter issues i will check for beta's first.
