### ISSUE TITLE
"Win11 start menu style" is still in active even after applying the start menu style to (Classic style, Classic with two columns and Windows 7 style).

### ISSUE THREAD

**Issue by Michellehdr** [Open-Shell/Open-Shell-Menu#1573]
### Describe the bug

"Win11 start menu style" is still in active even after applying the start menu style to (Classic style, Classic with two columns and Windows 7 style).

### Area of issue

Taskbar

### To reproduce

1.Deploy the latest OS 
2.Perform windows and store updates 
3.Install the application from vendor site 
4.Launch the Open-Shell Menu Settings.
5.Select the required start menu style and start button and click on OK
6.And Observe the Selected start menu and win11 start menu both are working.

### Expected behavior

Applied Start menu should work

### Open-Shell version

4.4.170

### Windows version

Windows 11

**Comment by ge0rdi** [comment]
Please, see this pinned issue https://github.com/Open-Shell/Open-Shell-Menu/issues/1564 .
