### ISSUE TITLE
When Setting up, Warning 1946

### ISSUE THREAD

**Issue by SD308** [Open-Shell/Open-Shell-Menu#1575]
### Describe the bug

As I reinstall Open-Shell, I get errors of:
"Warning 1946. Property '{9F4C2855-9F79-4B39-A8D0-E1D42DE1D5F3|, 26' for shortcut 'Open-Shell Update.lnk' could not be set." and
"Warning 1946. Property 'System.AppUserModel.ID' for shortcut 'Classic Explorer Settings.lnk' could not be set.".

### Area of issue

Installation/Other

### To reproduce

Install the app on windows 11 Pro.

### Open-Shell version

4.4.170

### Windows version

Windows 11 Pro: 22621

**Comment by ge0rdi** [comment]
That's pretty weird as that used to be issue on legacy Windows:
https://learn.microsoft.com/en-us/troubleshoot/windows/win32/warning-1946-when-you-install-installer-package

Try to use [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build (that does support Win11 anyways).

**Comment by SD308** [comment]
I did upgrade to 4.4.189, but the same issue persists, sadly. Side note: That's actually really interesting that it's happened again.

**Comment by ge0rdi** [comment]
You can try to create log from installer using:
`OpenShellSetup_4_4_189.exe /lvx* install.txt`

Maybe that will show something.

**Comment by SD308** [comment]
Which version are you talking about as the installer?

**Comment by ge0rdi** [comment]
You can uninstall `Open-Shell` and then install latest build using the command line I provided.
It will produce `install.txt` log that you can then attach here. Hopefully it will contain some clue about your issue.

**Comment by SD308** [comment]
I had to reinstall windows for other reasons, but I got it working. Was I supposed to use command prompt?

**Comment by ge0rdi** [comment]
> I got it working

Cool.

> Was I supposed to use command prompt?

Yup. Sorry for not being clear.
