### ISSUE TITLE
Taskbar Texture not loading

### ISSUE THREAD

**Issue by SD308** [Open-Shell/Open-Shell-Menu#1576]
### Describe the bug

When loading a taskbar texture, it seems to ignore the file name, and defaults to a standard texture (currently a clear pink).

### Area of issue

Taskbar

### To reproduce

1. Go to taskbar settings.
2. Click on customize taskbar.
3. Insert the picture file you want to load.
4. Hit accept.
5. Nothing happens.

### Open-Shell version

4.4.170

### Windows version

Windows 11 Pro: 22621

**Comment by SD308** [comment]
Ah. I seen you mentioned this bug before having to do with windows 11's taskbar.

**Comment by ge0rdi** [comment]
Right, taskbar customizations don't work in Win11 anymore.
See https://github.com/Open-Shell/Open-Shell-Menu/issues/1342 for more info.
