### ISSUE TITLE
cannot create new folder

### ISSUE THREAD

**Issue by clutchmaster420** [Open-Shell/Open-Shell-Menu#1579]
### Describe the bug

cannot create new folder because folder shortcuts do not open to true path

and no downloading that other version from a sketchy link is not the correct solution 

### Area of issue

Windows Explorer

### To reproduce

place folder shortcut in open shell, open that shortcut, open the ribbon, "new folder" button is greyed out

### Expected behavior

to create a new folder

### Open-Shell version

4.4.7.0

### Windows version

22h2

**Comment by ge0rdi** [comment]
Please, try with [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) `Open-Shell` build.
