### ISSUE TITLE
failed to extract setup file

### ISSUE THREAD

**Issue by bruzzler5** [Open-Shell/Open-Shell-Menu#1581]
### Describe the bug

OS: win10 64 bit

OpenShellSetup_4_4_170.exe can't be installed, regardless of running as administrator 
exe stops with err msg
Failed to extract setup file ****.msi
The MSI resource is corrupted

The same exe runs on win10 32 bit without any problems.  On debian gnome the exe can be expanded without errs.

Same problem with an earlier version

the win 10 64bit was freshly set up with all current updates,

sfc /scannow didn't change anything, same with dism....

Any ideas?

### Area of issue

Installation/Other

### To reproduce

click on exe, click on right button, select run as administrator

### Expected behavior

running the installation without any problems

### Open-Shell version

4.4.170

### Windows version

windows 10 22h2

**Comment by ge0rdi** [comment]
Most likely your installer file is corrupted (or incomplete).
Could you provide its size (in bytes) and hash (sha1/sha256)?
