### ISSUE TITLE
Windows 11 breaks OpenShell Start Menu

### ISSUE THREAD

**Issue by randolf** [Open-Shell/Open-Shell-Menu#1584]
### Describe the bug

When Windows 10 gets automatically upgraded to Windows 11, OpenShell stops working.  I tried re-installing it (v4.4.170, which is the current version), but this didn't help.

The first time this happened, I thought there must be something wrong with that particular Windows installation, but this is happening with all upgrades to Windows 11.

My users don't like the Microsoft Start Menus in Windows 10 or Windows 11, and always appreciate the better productivity they experience with OpenShell.  They're as hopeful as I am that OpenShell will be working again in the future, because it solves the problems that Microsoft created with their massive changes to the Start Menu in Windows 10 and 11 as they increasingly try to copy the MacOS style.

Is there a Windows Registry hack that I can use to fix this?

Please help!  Thanks in advance.

### Area of issue

Start menu

### To reproduce

1. Wait for Windows 10 to automatically upgrade itself to Windows 11 (it does this sometimes even when you tell it not to, so if that hasn't happened to you yet consider yourself lucky)
2. Press the "Windows" key on the keyboard to access the Start Menu

### Expected behavior

OpenShell Start Menu should appear, but it doesn't -- the less productive Microsoft MacOS-like Start Menu appears instead, and then end-users feel lost as they struggle to find the programs they need to use (some programs don't appear, and so the end-user assumes that they're not compatible with Windows 11, but OpenShell always shows everything, including those missing programs that are, in fact, compatible).

### Open-Shell version

v4.4.170

### Windows version

Windows 11 Home 22H2 22621.1848

### Additional context

OpenShell is amazing.  It makes it so much easier for everyone to use Windows, and it helps end-users to be more productive.  It's a wonderful solution.  Thank you!

**Comment by ge0rdi** [comment]
Please, use [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) Open-Shell build on Windows 11 as stated in #1564 pinned issue.

**Comment by randolf** [comment]
Thanks @ge0rdi, this resolves the compatibility problem with Windows 11.

This release should be brought to the attention of regular end users because the ones who asked me about it were ready to uninstall OpenShell and just "throw in the towel" so-to-speak.  So, I suspect that by not having this available where regular end users can find it is going to cause attrition.
