### ISSUE TITLE
With todays Win Upd (now 22621.1992) start menu stopped showing up on "Windows Key"

### ISSUE THREAD

**Issue by myverygoodusername** [Open-Shell/Open-Shell-Menu#1586]
### Describe the bug

After the reboot due to Winodws Update the start menu does not show up any longer when pressing the Windows Key.
Clicking on the start button by mouse is still working.

### Area of issue

Start menu

### To reproduce

Now I have (according to winver) Build 22621.1992.
With this I cannot open the open-shell start menu using the Windows Key any longer.

### Expected behavior

Pressing the Windows Key should open the open-shell start menu.

### Open-Shell version

4.4.170

### Windows version

Win 11 22H2 22621.1992

**Comment by ge0rdi** [comment]
Please, see https://github.com/Open-Shell/Open-Shell-Menu/issues/1564 pinned issue.

**Comment by myverygoodusername** [comment]
Funny fact : after installing "startallback" for evealuation I can open the open-shell start menu using the Windows Key.
