### ISSUE TITLE
Start button shifted upwards and out of taskbar

### ISSUE THREAD

**Issue by stevem99999** [Open-Shell/Open-Shell-Menu#1587]
### Describe the bug

Open Shell Start button seems to have lost alignment with the Windows 11 Taskbar - it has moved slightly upwards and I can't see a setting to restore it.
![Screenshot 2023-07-12 104124](https://github.com/Open-Shell/Open-Shell-Menu/assets/47871830/b1d14b7e-e17c-4491-a7e1-8e89ecbb05a7)

### Area of issue

Start menu, Taskbar

### To reproduce

Go to Start Button
Observe that it is no longer in alignment with TaskBar

### Expected behavior

Icon in line with Taskbar

### Open-Shell version

4.4.170

### Windows version

Windows Home 11 22H2

**Comment by ge0rdi** [comment]
Please, see https://github.com/Open-Shell/Open-Shell-Menu/issues/1564 pinned issue.
