### ISSUE TITLE
Classic Start Menu No Longer

### ISSUE THREAD

**Issue by USSnowboarding** [Open-Shell/Open-Shell-Menu#1588]
### Describe the bug

It's not a bug but rather a modification of this program.

Due to the recent (as of July 12th, 2023) security update, the start menu option is considered part of the Windows Security protection, and it's not allowing third-party override of the look of the start menu.

### Area of issue

Start menu

### To reproduce

Apply the latest Windows 11 updates as of July 12th, 2023

### Open-Shell version

4.4.170

### Windows version

Windows 11 22H2

**Comment by mo-han** [comment]
+1
now, have to work around this via shift-win or replacing start button

**Comment by ge0rdi** [comment]
Please, see #1564 pinned issue.
