### ISSUE TITLE
Menu does not activate in same spot as Windows start menu

### ISSUE THREAD

**Issue by dbny89** [Open-Shell/Open-Shell-Menu#1589]
### Describe the bug

On every version of Windows, you can throw your mouse pointer into the bottom-left corner of your screen and click and your Start menu will open. You do not have to measuredly position the tip of the pointer in the middle of the Start button before clicking it. Unfortunately with Open-Shell, when you slide the pointer into the corner, in my case, Windows 11's menu opens. You have to move the pointer up 10 or 20 pixels to the Open-Shell Start menu to click on it. This is sloppy. No matter what I do to position the button lower (trying -10 or -20 x,y positioning or making a big custom button that fills the entire corner) the Windows 11 menu always opens when you drag into the corner "pocket" and click. Can't stand it.

### Area of issue

Start menu

### To reproduce

slide the pointer into the bottom-left corner and click.

### Expected behavior

Open-Shell menu to open!

### Open-Shell version

4.4.170

### Windows version

11 build 23493

### Additional context

Frustrating because I'd prefer to use this instead of startallback, which is buggy as hell 1% of the time and fine 99% of the rest of the time.

**Comment by ge0rdi** [comment]
Please, see #1564 pinned issue.
