### ISSUE TITLE
The explorer bar has gone after last win10 update

### ISSUE THREAD

**Issue by bert07** [Open-Shell/Open-Shell-Menu#159]
![Explorer](https://user-images.githubusercontent.com/22558426/56100565-8e23a580-5f1a-11e9-8170-0be6d4b19fd2.jpg)

The classic explorer bar is gone.

**Comment by Moopere** [comment]
To get it back: View->Options->Classic Explorer Bar

![image](https://user-images.githubusercontent.com/17094611/58683943-fdf5ce80-83a8-11e9-833c-77210151aa34.png)

![image](https://user-images.githubusercontent.com/17094611/58683977-182fac80-83a9-11e9-89c5-b5184c8e2bb2.png)
