### ISSUE TITLE
Latest Windows 11 updates modify Windows key behavior.

### ISSUE THREAD

**Issue by Noctumsempra** [Open-Shell/Open-Shell-Menu#1590]
### Describe the bug

Hello,

I'm a happy user of OpenShell Classic Menu, and 2 nights ago, my computer suddendly restarted, Windows updated in its dictatorial way (took control --> don't turn of your PC), restarted again and now OpenShell Classic menu didnt't trigger with Windows key (it does if you CLICK the start button but I need the Windows key to be functional to OpenShell again)

I tried uninstalling, cleaning registry, reinstalling and nope. Windows key now only triggers Windows 11 UGLY MENU.
And also tried reinstalling Explorer Patcher. No case :(

I hope you can find a solution to this.
Regards.

### Area of issue

Start menu

### To reproduce

1. Press Windows key.
2. Windows 11 menu opens.

### Expected behavior

I expected OpenShell Classic Menu opening as usual.

### Open-Shell version

4.4.170

### Windows version

Windows 11 Enterprise 22H2

### Additional context

With this windows update, Lightshot didn't trigger with Printscreen (Microsoft changed behavior of Prnt Screen key by default)

**Comment by ge0rdi** [comment]
Please, see #1564 pinned issue.

**Comment by Noctumsempra** [comment]
Ohh, thank you. Now I got version 4.4.189 and the Windows key works again! ^^
