### ISSUE TITLE
Windows key opening the Windows start menu, and not the Open-Shell start menu [Windows 11]

### ISSUE THREAD

**Issue by 44Nifty** [Open-Shell/Open-Shell-Menu#1599]
### Describe the bug

Recently, (starting last  night maybe?) Open-Shell has  no longer been integrated with the Windows key on Windows 11.
I've tried restarting my computer, uninstalling and reinstalling Open-Shell, and nothing has worked

### Area of issue

Start menu

### To reproduce

1. Install Open-Shell
2. Press Windows key on your keyboard

### Expected behavior

I expect the Open-Shell start menu to open when I press the Windows key on my keyboard.

### Open-Shell version

4.4.170

### Windows version

Windows 11 22H2

**Comment by M0Z1NG0** [comment]
This just started happening to me too. On July 13, the KB5028185 windows update was installed, which according to [this](https://support.microsoft.com/en-au/topic/july-11-2023-kb5028185-os-build-22621-1992-605fa18f-bd49-41d8-80b1-245080e26c3d) made some changes to the start menu. I'd have to assume that update broke something.

**Comment by ge0rdi** [comment]
Please, see #1564 pinned issue.
