### ISSUE TITLE
Why cmd.exe when pin to taskbar, become powershell instead?

### ISSUE THREAD

**Issue by hy-net** [Open-Shell/Open-Shell-Menu#1604]
### Describe the bug

As per title.

I have no way to pin CMD.exe to taskbar.

### Area of issue

Taskbar

### To reproduce

Windows -> System -> Command Prompt

Right click the Command Prompt icon at taskbar and select Pin to Taskbar

### Open-Shell version

4.4.189

### Windows version

Win 11 22H2

**Comment by ge0rdi** [comment]
> select Pin to Taskbar

This is handled by Windows. It has nothing to do with `Open-Shell`.

You can right-click pinned icon and then select what _terminal_ you want to start:
![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/2453094/1947e039-c70d-41a5-a8e7-7043f1546503)

You can also configure default profile in terminal settings:
![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/2453094/13290ef4-f247-4e0f-b1fc-98634a4e4da3)
