### ISSUE TITLE
Open-shell stopped working after Windows 11's 22H2 update

### ISSUE THREAD

**Issue by alejandro-esquivel** [Open-Shell/Open-Shell-Menu#1605]
### Describe the bug

What the title says, I keep pressing the left windows key but the classic menu doesn't pop up, windows 11's does instead.

### Area of issue

Start menu

### To reproduce

1. Press left windows
2. it doesn't open.

### Expected behavior

Open-shell's menu should open

### Open-Shell version

4.4.710

### Windows version

Windows 11 22H2

**Comment by ge0rdi** [comment]
Please, see #1564 pinned issue.
