### ISSUE TITLE
After Windows Update, Windows Button stopped opening Open Shell

### ISSUE THREAD

**Issue by SabreRunner** [Open-Shell/Open-Shell-Menu#1606]
### Describe the bug

![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/10673434/27d74ba3-0afc-4d5e-a483-ab1550b2f198)

This is my version. It did update over the weekend and now my Windows button doesn't open Open Shell.

Help?

### Area of issue

Start menu

### To reproduce

1. Click Windows button

### Expected behavior

Open Open Shell

### Open-Shell version

4.4.170

### Windows version

Attached

**Comment by greenftechn** [comment]
This has impacted me as well. Windows and Open Shell versions the same as the OP.

**Comment by ge0rdi** [comment]
Please, see #1564 pinned issue.
