### ISSUE TITLE
Disable keyboard shortcuts

### ISSUE THREAD

**Issue by vkmbrlm** [Open-Shell/Open-Shell-Menu#1608]
### Is your feature request related to a problem? Please describe.

I disabled the searchbox (because I use Everything as a global search tool).
The buttons Restart, as also Shutdown are in my main menu.
If I press Win and then press R the machine restarts.
Same with the shutdown button, it has an automatic shortcut.

### Describe the solution you'd like

I would like to disable shortcuts for all menu-items to not accidentially restart or shutdown.
If that's not possible, I would like to be able to edit shortcuts in the tab "Main Menu" where I can customize every entry.

### Area of issue

Start menu

**Comment by ge0rdi** [comment]
Recent [pre-release builds](https://github.com/Open-Shell/Open-Shell-Menu/releases) have option `Enable accelerators` in `Open-Shell Settings` -> `General behavior`.

You can un-check it to completely disable keyboard accelerators. Or you can enable `Require Alt key for accelerators` (more standard Windows behavior).

**Comment by vkmbrlm** [comment]
Duplicate: #447
