### ISSUE TITLE
How to disable autostart?

### ISSUE THREAD

**Issue by nn-23** [Open-Shell/Open-Shell-Menu#161]
How do I disable autorun?
I iknow there's the HKCU\Software\StartMenu\Settings\Autorun Key, but this isn't what I'm looking for.

As of now Open-Shell starts as soon as a user logs on, and I have to disable it.
I want it to stay off by default, and then enable it only for a special user, when he wants it.

I struggle to find a solution for this.

Thanks
Alex

**Comment by ibuprophen1** [comment]
@nn-23, Do you have Windows 10 64-bit? 

If not, what do you have? 


~Ibuprophen

**Comment by ge0rdi** [comment]
There is `Open-Shell Start Menu` value created in `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` key by default. This causes `Open-Shell` to run automatically for every user (and then depending on his settings actually do something, or just finish immediately).

If you want to enable `Open-Shell` just for some users, you'll have to remove that value from HKLM and instead create it in _Run_ key of particular user:  
`HKEY\Users\<user-sid>\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`

**Comment by ibuprophen1** [comment]
Thank you very much for pointing this out @ge0rdi! :-) 

I was actually about to gather some information regarding this because I've seen it placed in (1 or 2) other areas within the registry that results in it auto starting when the system boots up. 

It's hard to explain this without gathering the information for you. 

I plan to begin gathering the info today or tomorrow. Please be patient with me My Friend. :-P 


~Ibuprophen

**Comment by ge0rdi** [comment]
There are two ways of disabling `Open-Shell` autostart (while giving particular users ability to enable it).

### Policy
There is `PolicyDefinitions.zip` file in `Open-Shell`'s install folder. See inside for instructions how to use it (`PolicyDefinitions.rtf`).

You can then edit `Computer Configuration -> Administrative Templates -> Open-Shell -> Open-Shell Menu -> Start automatically for this user`:

![image](https://user-images.githubusercontent.com/2453094/59161534-3487c380-8ae4-11e9-9efc-b8f3bf500895.png)

This way autostart will be disabled by default, but the setting won't be locked so particular users can override it by running `Open-Shell Menu Settings`.

### Default setting value
In `HKEY_LOCAL_MACHINE\SOFTWARE\OpenShell\StartMenu` create item named `AutoStart_Default` with value `0`.

This way the autostart setting will be disabled for given machine, but particular users will be able to enable it.

**Comment by zhmlcg** [comment]
ge0rdi'd method cannot achieve "This way autostart will be disabled by default, but the setting won't be locked so particular users can override it". In fact, if you change group policy that way, autostart will actually be enabled by default, which means any other user will see the Open Shell and get surprised. Then, if other user disables it in Computer Configuration or User Configuration (if s/he knows how to do that), the user who wants to use Open Shell cannot see it. This is obviously not the intended behavior of "Install only for me".

To achieve the correct behavior of "Install only for me", people should take the following as opposed to ge0rdi's method:
1) In the group editor screenshot of ge0rdi, choose "Disabled" as opposed to "Enabled". This way, autostart will indeed be disabled by default. To emphasize, this is in Computer Configuration which impacts the whole PC.

2) Log into the account of the user who wants to use Open Shell. Run regedit and add a DWORD value AutoStart_Default=1 under "Computer\HKEY_CURRENT_USER\SOFTWARE\OpenShell\StartMenu". Re-log.

**Comment by zhmlcg** [comment]
ge0rdi's method just does not work. My Windows version is 21H2.

**Comment by JasonHoku** [comment]
I found a entry for a task scheduler to run on login in the task scheduler in windows: win + r, then run: `taskschd.msc` right click openclaw gateway service, delete.
