### ISSUE TITLE
Openshell doesn't work anymore 

### ISSUE THREAD

**Issue by Lookoutforthetrain** [Open-Shell/Open-Shell-Menu#1612]
### Describe the bug

So I use openshell with retrobar
It used to work 
but now it doesn't anymore
I press the windows key that just takes me to the normal start menu
I click start and that just takes me to the normal start menu as well
And the only way I can get the shell menu work is to exit retrobar and click on the thing

### Area of issue

Start menu, Taskbar

### To reproduce

Click on retrobar start button
OR
Press windows key

### Open-Shell version

4.4.170

### Windows version

Winodws 11 10.0.22621

**Comment by ge0rdi** [comment]
Please, see #1564 pinned issue.
