### ISSUE TITLE
4.4.190 from February and now. What is the difference?

### ISSUE THREAD

**Issue by FFreestyleRR** [Open-Shell/Open-Shell-Menu#1619]
### Describe the bug

Hello.

I already have 4.4.190 from February. I tried to install the one from 2 days ago, but it gives me that the new version is already installed? How is that possible?

### Area of issue

Installation/Other

### To reproduce

https://i.ibb.co/5WTYkX5/Image-490.png

### Open-Shell version

4.4.190

### Windows version

Windows 10 22H2

**Comment by ge0rdi** [comment]
What you have is very likely unofficial build from some pull-request.
Maybe you've had some issue that was fixed in the meantime so you have used that unofficial build.

You should uninstall it (your settings will be kept) and install official 4.4.190 .
