### ISSUE TITLE
Cannot override start menu background and text color

### ISSUE THREAD

**Issue by zhro** [Open-Shell/Open-Shell-Menu#162]
We can already override the color of the taskbar but we cannot override the background or text color of the start menu. I want to change its color independent of the "accent" color in Windows 10 as this color is used for application titlebars.

**Comment by CTVCAM8** [comment]
This is only my opinion from past experience from trying to skin Classic Shell menus.

I think at this time, the only way to change menu **text** color is to pick a different menu skin, 
or edit the skin's text color using Resource Hacker. 

If in the future the Open Shell coders put an override text color option in settings, it could get complicated. 
For one column classic 1 style-easy
For two column classic 2 style- easy if both columns use same background color, 
or would need a secondary override option for just second column.  
For 7 style- easy if 1st, 2nd, jumplist and search views all use same background color,
or very complicated options if all different background colors used in the skin.
 

For the menu **background** color, pick a different menu skin.
One that has the capacity to use glass color.
Then use the "Override glass color" in "Menu Look" tab of settings.
Use the included color picker.

If you are using the Metro skin, it uses specially assigned Metro colors, 
that don't follow the old windows 7 glass color. 
Most of those Metro colors are just lighter/darker shades of the same color.
Trying to override the Metro menu color in settings does not work too well.
The Metro skin would need to be edited to your visual taste. 

Read about it in the archive skinning tutorial page
or if the original forum page is still up:

http://classicshell.net/tutorials/skintutorial.html

Another possibility. Just add all these options into a simplified looking skin and upload in Open-Shell package.
The original developer added skinning options for a value that can be a number, a text string, a color or an image.
The user just inputs info into override boxes in the skinning page of that skin to suit them.

**Comment by LinuxOnTheDesktop** [comment]
One expects OpenShell to be a customisation tool. Certainly it has many options. Yet, one cannot easily . . the colour? I mean the colour of the text and background on the menu. That is certainly a disappointing surprise.

**Comment by bonzibudd** [comment]
@LinuxOnTheDesktop I somewhat agree. Especially for the Metro skin, which would probably just be better off solely relying on the "Override" color since the metro color used is the same (or very similar) to the default override.

**Comment by bonzibudd** [comment]
Hey, just wanted to say that I'm working on a skin that fixes this: https://github.com/Open-Shell/Open-Shell-Menu/issues/538#issuecomment-778453041

If you want the entire background to change colors, you can toggle the "More transparent" option.

@zhro @LinuxOnTheDesktop

**Comment by LinuxOnTheDesktop** [comment]
@bonzibudd:

Good. Thank you. Ideally - is this the plan? - a skin with that capability should be the default.

**Comment by bonzibudd** [comment]
Yes, it would ideally become the default, but that's up to the developers if they want to implement it natively.

**Comment by bonzibudd** [comment]
New skin with immersive colors and respect to custom glass color added in #1274.
