### ISSUE TITLE
Align start menu to working area (Menu Look) do nothing

### ISSUE THREAD

**Issue by eltakin** [Open-Shell/Open-Shell-Menu#1621]
### Describe the bug

check/uncheck Align start menu to working area (Setting->Menu Look) doesn't change behavior.

### Area of issue

Start menu

### To reproduce

-

### Expected behavior

Changing position popup menu

### Open-Shell version

4.4.190

### Windows version

win 11 22h2

**Comment by ge0rdi** [comment]
I'm not really sure what the option is supposed to do (tooltip says "use with custom taskbars", do you use custom taskbar?).
The thing is that _working area_ is part of the screen excluding taskbar. So basically aligning with taskbar or working area should be the same with default taskbar.

> Changing position popup menu

How it should change position of start menu exactly?
Can you describe more what is your issue and what you'd like to achieve?

**Comment by eltakin** [comment]
this version is 4.4.170
windows taskbar is aligned to right side.
Check/uncheck one and you will see
[Open-Shell.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/12190548/Open-Shell.zip)

**Comment by ge0rdi** [comment]
> windows taskbar is aligned to right side.

I think it is related to `Show next to taskbar (when the taskbar is vertical)` setting that is now enabled by default.
You can disable it and start menu will _overlay_ taskbar when opened.

BTW there is no need to attach binaries from older version. Older versions are available here on Github.
It is better to provide screenshot that will clarify the issue.

**Comment by eltakin** [comment]
> You can disable it and start menu will _overlay_ taskbar when opened.
thx a lot, works as i need.
