### ISSUE TITLE
Two Windows Start Buttons

### ISSUE THREAD

**Issue by gitfirewall** [Open-Shell/Open-Shell-Menu#1622]
### Describe the bug

In the previous version (4.4.170) I had the Open-Shell start button on the far left, and the official Windows 11 start button in the centre, and it was very convenient.

Now with the latest version (4.4.190) I only have the Open-Shell start button in the center which has completely replaced the Windows one and I can't get it back to the way it was before.

Could you help me?

### Area of issue

Start menu

### To reproduce

Just install the program.

### Open-Shell version

4.4.190

### Windows version

Windows 11 22H2

**Comment by ge0rdi** [comment]
There is discussion about this #1252.

See my answer https://github.com/Open-Shell/Open-Shell-Menu/discussions/1252#discussioncomment-4417463.

Feel free to discuss there. But for now there is no plan to go back to the original buggy behavior.

**Comment by CornelisJ** [comment]
It appears that many users, including myself, prefer it to have two start menu buttons (Classic start button in the lower left corner, and Windows 11 start button in the middle). It would be great to have an option to leave the Classic start button at the lower left corner in future versions of Open-Shell.
