### ISSUE TITLE
Windows XP Skin creates "Empty" sub-menu boxes for any created sub-menus

### ISSUE THREAD

**Issue by NoahsRebels** [Open-Shell/Open-Shell-Menu#1625]
### Describe the bug

Any time I create sub-menus (at least using the Windows XP skin), there's a box above the first sub-menu item that just says "empty". I'm not sure if this is intended or not, and if it is, I'm not sure how to disable it. I tried looking around in the settings but didn't find anything. While not functionally an issue, it's kinda visually displeasing. This doesn't exist for other sub-menus like those for Programs and Apps.

![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/46310933/cb554324-9350-4067-8f83-a996d65adbd9)

### Area of issue

Start menu

### To reproduce

- Enable the Windows XP Luna skin (unsure if it only happens on this skin or others as well. The style is "classic with two columns")
- Create a sub-menu (In the left column)

### Expected behavior

The "(empty)" box should not appear. (it doesn't seem to even have functionality, right/ left clicking it does nothing) 

### Open-Shell version

4.4.170

### Windows version

1022H2

**Comment by ge0rdi** [comment]
Can you try with latest 4.4.190 ?

**Comment by NoahsRebels** [comment]
I updated and it still seems to be happening

**Comment by ge0rdi** [comment]
I'm unable to replicate this with clean install in Windows Sandbox :(
It may be possibly related to some custom settings.
Please, attach your setting obtained in `Open-Shell settings` -> `Backup` -> `Save to XML...`.

> Create a sub-menu (In the left column)

How exactly do you this?
And how do you add items to the folder?
Does it happen with any folder?

If you right-click on the folder and select `Open`, does the folder contain just files/shortcuts you have created?
Couldn't there be some _hidden_ files/folders?

**Comment by NoahsRebels** [comment]
Sure, here's my settings:
[Menu Settings.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/12191584/Menu.Settings.zip)

I went to the "customize start menu" area, and added a custom menu item which I called "My Games", which links to Steam. I then made two other custom menu items which link to 2 non-steam games, which are the sub-menu items from the screenshot.

**Comment by ge0rdi** [comment]
> I went to the "customize start menu" area, and added a custom menu item which I called "My Games", which links to Steam. I then made two other custom menu items which link to 2 non-steam games, which are the sub-menu items from the screenshot.

Thank you, I was able to replicate it using these steps.
This is why it is very important to write exact steps one is doing in the "To reproduce" section.

**Comment by NoahsRebels** [comment]
Sorry, I was indeed a bit too general for that part - is there a way to stop the empty box from appearing, or will it possibly be in the next update?

**Comment by NoahsRebels** [comment]
I feel kind of stupid, because I realized I could just put a folder with the shortcuts for all the games I play, and make the menu just direct to the folder itself, which resolves the issue. I hadn't even realized the command box was for executables, I thought it was just like built in commands. Sorry for the trouble lol, I only installed this a couple days ago

**Comment by ge0rdi** [comment]
No need to apologize.
I'm glad it works for you now.
