### ISSUE TITLE
Minimising a window with Win+Down opens the Windows start menu on key up

### ISSUE THREAD

**Issue by JannesMeyer** [Open-Shell/Open-Shell-Menu#164]
This only happens when Classic Shell is running.

The correct behaviour would be that the start menu doesn't open when I release Win+Down.

**Comment by ge0rdi** [comment]
What OS?
Works correctly for me (Win10 1809).

**Comment by JannesMeyer** [comment]
I have Windows 10 Pro 1803

**Comment by JannesMeyer** [comment]
However, it doesn't seem to be happening anymore after a reboot. It may have been an intermittent issue. I will comment if it happens again.

**Comment by blackcrack** [comment]
well, some others use WinXP, Vista and Win7, don't miss that ;)
Reactos is also coming, .. only as a note,
the other is, maybe have you also on run a Programm where works also with hotkey's,
i use as example " Volume² " from https://irzyxa.blogspot.com/ 
and other can robs the hotkey possible too.. just as hint :)

best regards
Blacky

**Comment by ibuprophen1** [comment]
I was just wondering if this issue has been resolved? 👌


~Ibuprophen

**Comment by JannesMeyer** [comment]
Yes, it is resolved. After the reboot it hasn't happened again.
