### ISSUE TITLE
Black column on start menu

### ISSUE THREAD

**Issue by shano223** [Open-Shell/Open-Shell-Menu#1640]
### Describe the bug

In open shell under the start menu style tab on my 2 laptops I have "classic with two columns" and "classic" picked for the way I like the menus. Before I Installed the new update when i clicked on start on the bottom left on pc the two columns would be BLUE in colour now after updating to the newer more recent version the left han side of the column has tuned black while the right is s
![Screenshot (1)](https://github.com/Open-Shell/Open-Shell-Menu/assets/141149830/82a02bba-7827-496b-878a-28f629e304a3)
till ok BLUE  - WHAT HAS HAPPENED. - how do i get the the 2 columns back to blue again. Like I sasid they were both blue befofre i updated to the 4.4.190 version

### Area of issue

Installation/Other

### To reproduce

hen i go to open open shell

### Expected behavior

both colums to tay the same

### Open-Shell version

4.4.190

### Windows version

windows 10 pro 22H2

### Additional context

NA

**Comment by ge0rdi** [comment]
There is new `Immersive` skin used by default in recent `Open-Shell` versions.

You can switch to old `Metro` skin (or whatever else skin you like) in `Open-Shell Menu Settings` -> `Skin`.

**Comment by shano223** [comment]
That is exactly what I was looking for - thank you very much
