### ISSUE TITLE
Right click Programs submenu cause Open-Shell hang

### ISSUE THREAD

**Issue by lededev** [Open-Shell/Open-Shell-Menu#1645]
### Describe the bug

as title

### Area of issue

Start menu

### To reproduce

as title

### Expected behavior

Show pop up menu: remove new installed highlighting & sort by name 

### Open-Shell version

4.4.190

### Windows version

Windows 11 22H2

### Additional context

old version before I upgrade not have that bug

**Comment by ge0rdi** [comment]
Please, enable `Open-Shell` logging as described [here](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-obtain-advanced-Open-Shell-Menu-log).

Replicate issue and also create dump from Explorer using [ProcDump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) in the state when it is hung:
`procdump -ma explorer.exe`

Provide `StartMenuLog.txt` and dump here.

**Comment by lededev** [comment]
too big that dump 
![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/30518126/9b2b6019-dda1-48f3-9e5a-402978e48495)
And I find in StartMenuLog.txt contains some of my personal information, I need replicate this bug a blank PC later.

**Comment by ge0rdi** [comment]
> too big that dump

You can upload it to some cloud storage and post link here.
Or you can send the link to me  (`ge0rdi (at) gmx.com`) if you don't want to make it public.

**Comment by ge0rdi** [comment]
> And I find in StartMenuLog.txt contains some of my personal information, I need replicate this bug a blank PC later.

Maybe post at least last lines of the log (when menu is hung), redacted if necessary.
It may help to see what was `Open-Shell` doing.

Ofc, it would be great if you are able to replicate on clean machine. Though I'm afraid that the issue is simply related to state of your machine (like SW you have or eventually another application that patches/modifies explorer, or so).

**Comment by lededev** [comment]
This issue disappear after I sort Programs menu items, now I cannot locate it on original PC.
Latest log in StartMenuLog.txt when hang. When Open-Shell no response, click on taskbar, windows will restart it. Win 11 with ExplorerPatcher.
```
    5157: Activate Item, ptr=000000001833C480, index=24, type=5
    5165: Close Menu, ptr=000000001833CA00
```
