### ISSUE TITLE
How do I control this with group policy?

### ISSUE THREAD

**Issue by klxz79** [Open-Shell/Open-Shell-Menu#165]
This should be a simple answer I just can't find it anywhere.  I've been controlling Classic Shell for years using GPO.  But I rolled out Open Shell through group policy and the Classic Shell changes don't work with Open Shell.  I've looked everywhere I could for Open Shell policy definitions but I can only find the Classic Shell ones.  What simple thing am I doing wrong here?  Where do I get the amdx files that work with Open Shell?  Or if the Classic Shell policy definitions work with Open Shell what do I have to do to make them work?  Rename them?

**Comment by ge0rdi** [comment]
There is `PolicyDefinitions.zip` file inside `Open-Shell` install folder.
It contains required policy definitions (`admx`/`adml`).

Original `Classic-Shell` policy definitions don't work because `Open-Shell` uses different registry paths.

**Comment by klxz79** [comment]
Thank you!

**Comment by pmqdesousa** [comment]
Good morning
Is there any place where to find a smart instruction list (for example: simple Excel-Sheet), where is described, which Open-Shell Policy settings belongs to which Registry settings ?

It would make everything easier to understand, for example where the Subkey settings for:
HKEY_CURRENT_USER\SOFTWARE\OpenShell\StartMenu\Settings

is stored in the Windows policy settings for Open-Shell.

Thanks in advance

Pedro
