### ISSUE TITLE
Not showing after install in Windows 11

### ISSUE THREAD

**Issue by fasteddys** [Open-Shell/Open-Shell-Menu#1654]
### Describe the bug

Hello, I am unable to get this menu to show up after installing in admin mode on Windows 11.

### Area of issue

Start menu

### To reproduce

Install as admin, then click on start menu, does not show in windows 11

### Open-Shell version

latest

### Windows version

latest

**Comment by ge0rdi** [comment]
> after installing in admin mode

What do you mean by that?
You can run installation as normal user and installer will show UAC prompt to get admin credentials.

Try to run `Open-Shell Menu Settings` shortcut from start menu.
