### ISSUE TITLE
Choosing Update and Restart (or shutdown) does nothing (apparently) - server 2019.

### ISSUE THREAD

**Issue by Benadictus** [Open-Shell/Open-Shell-Menu#1657]
### Describe the bug

Download and apply updates manually, or push updates to virtual guest OS through a patching-update program.
All updates PHASE #1 have completed.
(Phase #1 = complete all update installation portions that will cause the button [restart now] to appear.  All updates listed show "pending restart"
Phase #2 = the Zero to 30% "applying updates" message in the middle of the screen
Phase #3 = The 31 to 100% "applying updates" message in the middle of the screen, post reboot)

The Open-Shell menu shows the two options "Update and shut down" and also "Update and Restart"
Choosing either of these options **appears** to do nothing.
If I then manually in a command/powershell window "shutdown /s"  or "shutdown /r"  the virtual guest will actually shutdown or reboot.  There will be **NO** visible Phase #2 messaging (zero to 30%).
However upon rebooting the guest the updates are eventually completed.

I manage many server 2019 installations, however this is NOT consistent with all of them and I cannot detect what the differences might be.  On some the open-shell choices work as expected (ie: restart + update) but with others I have to use the command line shutdown/restart options.
NOTE: I did recently discover that the Program "server manager", which usually auto-launches upon login to a server, when choosing "local server" and the [tasks V] menu with "Shutdown local server" option  WILL SHOW the Phase #2 zero to 30% for a server with this condition.  How this shutdown is different from "Shutdown /S" I don't know.

Systems:  Server 2019 as a virtual Guest on Hyper-V host 2019
Not sure if this has anything to do with it, but the underlying version of "windows 10" within Server 2019 claims to be "1809" although it is still valid (will get MS updates) until October 2029.
![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/122576904/0565eade-ae92-4f5f-add8-e74633071783)

### Area of issue

Start menu

### To reproduce

1. Using Server 2019 with latest updates installed (minus the current month's updates)
2. It MIGHT require that this be a virtual guest 2019 with Hyper-V, although this is not definitive.
3. Apply MS monthly **rollup** updates as you normally would. (.net and OS)
4. Wait until the button  [restart now] appears on the windows update page.  All updates listed show "pending restart".
5. The Open-Shell menu shows the two options "Update and shut down" and also "Update and Restart"
6. Choose **either** of those options on Open-Shell.
7. No restart occurs, no shutdown occurs.

### Expected behavior

Updates get applied from zero to 30% and then guest OS shuts down.
If restart was chosen then it also starts up again and boots to 31% to 100% of updates.

### Open-Shell version

4.4.170

### Windows version

Server 2019  (1809)
Deployment Image Servicing and Management tool
Version: 10.0.17763.3406

Image Version: 10.0.17763.4645

**Comment by ge0rdi** [comment]
Could you try with latest `Open-Shell` version?

**Comment by ge0rdi** [comment]
Should be fixed already.
