### ISSUE TITLE
Application not working on Win11 ARM

### ISSUE THREAD

**Issue by 0wenches** [Open-Shell/Open-Shell-Menu#1658]
### Describe the bug

When installing Open Shell 4.4.190 on Windows 11 ARM through VMWare Fusion on a Mac, the shell menu doesn't open. After a restart, the explorer doesn't open. 

### Area of issue

Start menu, Taskbar, Windows Explorer

### To reproduce

1. open the installer
2. when asked, choose to not install the Classic Explorer
3. Install the program and exit out of the installer. 
4. go into "Open-Shell Menu Settings"
5. restart the computer
6. Log into the system.  

### Expected behavior

After the 4th step the menu should open, after restarting the computer, the Windows taskbar should be visible and the start menu should work. 

### Open-Shell version

4.4.190

### Windows version

Windows 11 for ARM 22H2

### Additional context

sry for my bad engrish.

**Comment by ge0rdi** [comment]
I'm sorry, but this is not a bug.
`Open-Shell` simply doesn't support ARM64 yet.

We have feature request #553 for it already.

**Comment by ge0rdi** [comment]
ARM64 support was added in [4.4.196](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.196).
Please, use that one (or newer) on ARM64 devices.
