### ISSUE TITLE
Can't open the Open Shell Menu with the windows key

### ISSUE THREAD

**Issue by VoetbalKijk** [Open-Shell/Open-Shell-Menu#1659]
### Describe the bug

On Windows 11 22621.1992 with ExplorerPatcher 22621.1413.54.5, Windows key opens standard menu

### Area of issue

Start menu

### To reproduce

1. Press ⊞ key
2. It opens the Windows 10 start menu

### Expected behavior

I expected it to open the Open-Shell Menu

### Open-Shell version

4.4.170

### Windows version

Windows 11 22H2

**Comment by ge0rdi** [comment]
Please, use latest `Open-Shell` version.

**Comment by VoetbalKijk** [comment]
Fixed👍
