### ISSUE TITLE
can you make it compatible with startallback so it opens in the middle of the screen ??

### ISSUE THREAD

**Issue by Ulf3000** [Open-Shell/Open-Shell-Menu#1664]
### Is your feature request related to a problem? Please describe.

when im using startallback to get the better taskbar with small icons and no grouping, then openshell startmenu will not open in the middle where the start button is but instead on the left side like win10. 

![grafik](https://github.com/Open-Shell/Open-Shell-Menu/assets/10765339/ba62bc48-2f8d-47c8-ae73-0792c5540fc2)

it makes a second start button on the left side , but having it in the middle in windows11 is really a good change 
I hope its possible for an easy fix ?

### Describe the solution you'd like

if possible fixed in the code 

or alternatively shrink the taskbar and make it use small icons maybe build into openshell 

### Area of issue

Start menu

### Alternatives you've considered

if there is another software tool  which can shrink the taskbar and make it use small icons then thats good too , please anyone suggest if you know :)

**Comment by ge0rdi** [comment]
You should use latest version of `Open-Shell`.
That one properly Windows 11.

**Comment by ge0rdi** [comment]
Should be fixed already in latest version.
