### ISSUE TITLE
Win 10 freezing

### ISSUE THREAD

**Issue by theLittlePrinceAD** [Open-Shell/Open-Shell-Menu#1675]
### Describe the bug

Hello,
After installing Open-Shell it starts and Win 10 freezes. I can press Ctrl-Alt-Del to start Task Manager and change active programs (started before Open-Shell installation), restart system, but cannot start new programs. Ending Opens-Shell's running task in Task Manager leads to its restarting.
This happens since installing Win 10, on all versions of Open-Shell (160, 170, 190) on one of my PCs - HP Spectre x360 14. Apparently it is some driver problem.

If you advice me how to stop the execution of Open-shell I could: Start an event-logger, Start Open Shell, Stop again Open-Shell and send you the result file. Or I can start the event logger before starting the installation of Open-Shell , but how to stop the Event logger in that case (to save the event log in a freezed PC)?

Please advice hot to run the event logger and which file to send to you?

P.S. I can actually start File Explorer (through Task Manager-Open location on some running processes) and start by it any executable program while PC is freezing.

### Area of issue

Start menu, Taskbar, Windows Explorer

### To reproduce

Please see explanation above.

### Open-Shell version

4.4.190

### Windows version

Windows 10 Pro 22H2, OS build	19045.3324, x64

### Additional context

Windows Feature Experience Pack 1000.19041.1000.0

**Comment by ge0rdi** [comment]
If you are able to start Task manager then please create dump from `Windows Explorer` process (right-click on the process and select `Create dump file`) and attach it here (or send to me directly to `ge0rdi (at) gmx.com`).

**Comment by theLittlePrinceAD** [comment]
> If you are able to start Task manager then please create dump from `Windows Explorer` process (right-click on the process and select `Create dump file`) and attach it here (or send to me directly to `ge0rdi (at) gmx.com`).

Thank you for your support!

Please find attached file @link. It has been created according your advice after installing Open shell, giving it time to start, and after having freezed the taskbar.

As file size is too big please see attached link to Mega cloud.
https://mega.nz/file/t5oWhawC#StH_qyBZTtPnzut5Ywd9r-LzLbRQo7jXUkHJ3BhstWA

**Comment by ge0rdi** [comment]
I can see weird _lockup_ in `Open-Shell` initialization. Trying to figure out what is going on there.

Though I have noted that you have `Start11` and `Fences` from `StarDock` running.
Those may possibly interfere with `Open-Shell`.
Could you disable/uninstall them temporarily to see if that will help with the lockup issue?

**Comment by theLittlePrinceAD** [comment]
> Though I have noted that you have `Start11` and `Fences` from `StarDock` running.

Actually, I have disabled Start11 before installing Open-Shell (there is an option in the app itself). Fences have been left running.

But - I have had this error since I have taken this PC on Win 10, long before I had Stardock's apps. Comming from Open Shell being a longtime user I tried a lot of ways and searched the net to manage it working at my situation, unfortunately without success. I suppose it has to do smth. with some display driver, as all apps I have installed on this PC are the same on my other PC-s, where Open shell works as expected.

**Comment by ge0rdi** [comment]
> I have disabled Start11 before installing Open-Shell

According to the dump it is loaded and running.
Maybe you can try to uninstall it (since you have disabled it already)?

> I have had this error since I have taken this PC on Win 10, long before I had Stardock's apps.

I see.

`Open-Shell` is stuck in its initialization. It tries to get some standard icons which results in some COM call that will then cause our init hook to be triggered and whole thing repeats again and again.

Need to compare it with _normal_ initialization to see what could have caused that behavior.

**Comment by theLittlePrinceAD** [comment]
> According to the dump it is loaded and running. Maybe you can try to uninstall it (since you have disabled it already)?

Uninstalled Start11 completely... and Open-shell started as expected. I thought - may be I have been wrong and Start11 is misbehaving :( Restarted several times, played with Open Shell and customized it, done some work (incl.Windows Update)... and restarted again... and Taskbar again stuck! Hence - Start11 is not the problem.

Please find link to Dump file.
https://mega.nz/file/MhRT1T6b#h77HSy-GJtbs-tk-Q_HdESnnj5JMdwvLzO7iXwhyPtc

**Comment by ge0rdi** [comment]
Cannot download the file:
`The file you are trying to download is no longer available`

**Comment by theLittlePrinceAD** [comment]
> Cannot download the file: `The file you are trying to download is no longer available`

Sorry, my fault! Me stupid!
Link updated.

**Comment by theLittlePrinceAD** [comment]
I tried a lot of combinations with Stardock's Start11 and Fences. At some cases Open-Shell was working OK. As there was no obvious pattern of behavior I uninstalled both Start11 and Fences, but after that at PC starting Open-Shell freezed the taskbar again.

So - Stardock's Start11 and Fences are not the problematic apps (as I have already stated, that at the time I first got the problem I had no idea of Stardock apps).

Please find the memory dump file, without Start11 and Fences:
https://mega.nz/file/RsgXSDRT#qU7Zg3k8U0h1SzjCOIdXuv6NGV8N6hur4epf4y7oIW4

P.S. I will have a check at Intel's display driver.

**Comment by ge0rdi** [comment]
@theLittlePrinceAD 
Could you, please, try build from #1678 PR?
It should avoid endless recursion during start menu initialization.

**Comment by theLittlePrinceAD** [comment]
> Could you, please, try build from #1678 PR? It should avoid endless recursion during start menu initialization.

Sorry, what exactly should I do?
I have been a programmer in the past, but have no idea now :(

**Comment by ge0rdi** [comment]
Sorry, for being unclear.

Download `Open-Shell` build from here:
https://ci.appveyor.com/project/passionate-coder/open-shell-menu/builds/47869291/artifacts
And install it to see if it helps in your case.

(In the pull-request I mentioned you can see message(s) from `AppVeyorBot` regarding new build. There is a link that will allow you to get the installer.)

**Comment by theLittlePrinceAD** [comment]
Sorry for answering this late, have been out of town.
Good news - Open-Shell is working perfectly now! :)
Using "OpenShellSetup_4_4_192-dsogbvsu.exe"
NO freezing!

You are the best!!! I am so happy!!!

**Comment by ge0rdi** [comment]
Cool. Thank you for confirmation.
I will include the fix into next official version (you can keep using the version you have for now).
