### ISSUE TITLE
Latest build fails for security issues

### ISSUE THREAD

**Issue by Grablfratz** [Open-Shell/Open-Shell-Menu#1677]
### Describe the bug

Received notice of new open-shell version today.  Both Windows Defender & Norton Antivirus flagged it as unsafe,  Norton promptly deleted it.  Never had a problem before.

### Area of issue

Installation/Other

### To reproduce

1.  Download file listed in new version notice
2. attempt to open it

### Expected behavior

Normal install

### Open-Shell version

Currently 4.4.190

### Windows version

Win  11 22H2

**Comment by ge0rdi** [comment]
> Both Windows Defender & Norton Antivirus flagged it as unsafe, Norton promptly deleted it.

It is a false-positive detection.
You should report it to your AV vendor, so they can fix their products.

**Comment by Grablfratz** [comment]
Reported it.  Thank you.
    On Wednesday, August 23, 2023 at 03:40:58 PM EDT, ge0rdi ***@***.***> wrote:  
 
 



Both Windows Defender & Norton Antivirus flagged it as unsafe, Norton promptly deleted it.


It is a false-positive detection.
You should report it to your AV vendor, so they can fix their products.

**Comment by ge0rdi** [comment]
Thanks.
Also for the future, please, report such false-positives to vendor of AV you are using.
