### ISSUE TITLE
Search doesn't find windows updates app

### ISSUE THREAD

**Issue by dig12345** [Open-Shell/Open-Shell-Menu#168]
Typing 'update' or 'windows update' or 'check for updates' in the search box does not yield the Windows Updates app. There seems to be no way to access it directly from the search box.

**Comment by ge0rdi** [comment]
What OS do you have?
Does Windows search (in standard Windows star menu) find it?
Could you post screenshot of `Open-Shell Menu` when you type `update` into search box?

**Comment by AveYo** [comment]
ms-settings:windowsupdate

**Comment by dig12345** [comment]
"Check for Updates" appears under the Modern Settings section. Not sure why I wasn't seeing it previously.
