### ISSUE TITLE
Files v4.4.190 and v4.4.191 flag as virus in Virustotal

### ISSUE THREAD

**Issue by AdasOsorus** [Open-Shell/Open-Shell-Menu#1680]
### Describe the bug

v4.4.190:
File: OpenShellSetup.exe
HASH: 31e616f27fad0c9b14a22c02ded2dc524411abf53d72c4136f22db1be0156865
Results: https://www.virustotal.com/gui/file/31e616f27fad0c9b14a22c02ded2dc524411abf53d72c4136f22db1be0156865?nocache=1

v4.4.191:
File: OpenShellSetup.exe
HASH: 9e9c32badb52444ca8a8726aef7c220ff48de8c7916cdfdca4dff6e009ac1f0c
Results: https://www.virustotal.com/gui/file/9e9c32badb52444ca8a8726aef7c220ff48de8c7916cdfdca4dff6e009ac1f0c

![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/41906277/9e13be63-2b01-4b3f-81f2-b58d3fe95a8d)

### Area of issue

Installation/Other

### To reproduce

1. upload file to https://www.virustotal.com/
2. scan file..

### Expected behavior

No results flag as "virus"

### Open-Shell version

4.4.190 & 4.4.191

### Windows version

N/A

**Comment by ge0rdi** [comment]
False-positive as usual.

> No results flag as "virus"

You should complain to those companies that detect our files without any real basis.
There is little (if at all) we can do.

**Comment by Ibuprophen** [comment]
Exactly @ge0rdi... 👍 

The following link is just 1 example about the VirusTotal issues with False positives... 

https://www.bigdatamark.com/problems-with-virustotal/

... but don't take my word for it as there's too many individuals who just assume what they're reading is factual without doing a little research/homework of their own. 

Peace and Love! 🥇 

~Ibuprophen
