### ISSUE TITLE
Seven VirusTotal security vendors report issues with the latest OpenShell installer - including Google?

### ISSUE THREAD

**Issue by tromlet** [Open-Shell/Open-Shell-Menu#1688]
### Describe the bug

Upon uploading the latest release binary to VirusTotal, seven vendors - including Google - have reported malware contained in the installer. Normally, I don't particularly give credence to a bunch of odd, less well-known security vendors reporting issues, so really the only one I'm concerned with here is Google - but seven *is* more than normal, as is Google being present here - and I'm curious as to why that might be?

https://www.virustotal.com/gui/file/9e9c32badb52444ca8a8726aef7c220ff48de8c7916cdfdca4dff6e009ac1f0c

### Area of issue

Installation/Other

### To reproduce

1. Download the latest OpenShell release installer binary
2. Upload it to VirusTotal (it's free, and you don't need an account)
3. Click the "re-analyze" button at the top - this will force VirusTotal to analyze the hash, upload the file, and subject it to the usual battery of tests from various security vendors. You should see the same output that I have.

### Expected behavior

Ideally, I'd expect there to be zero security vendors reporting issues.

### Open-Shell version

4.4.191

### Windows version

Windows 10 22H2

**Comment by ge0rdi** [comment]
This is a false-positive as already stated in #1680.

There is not much we can do about it.
You should report it to those AV vendors that are falsely detecting the file.
