### ISSUE TITLE
Explorer Crashed: IMAGE_NAME:  StartMenuDLL.dll (Dmp files) 

### ISSUE THREAD

**Issue by rugabunda** [Open-Shell/Open-Shell-Menu#1696]
### Describe the bug

Very random occurrence, not sure how to reproduce.  

### Area of issue

Start menu

### To reproduce

1. Click start.
2. Move mouse up to the top icon of the start menu.

### Expected behavior

no crash

### Open-Shell version

4.4.191

### Windows version

Win 11 22H2

### Additional context

Dump files:

[explorer.exe.dmp.7z.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/12566318/explorer.exe.dmp.7z.zip)

**Comment by ge0rdi** [comment]
Thank you for the dump.
Should be fixed in next version.

**Comment by rugabunda** [comment]
Wow! Great work, thank you.  I will keep you posted in the future if I see this problem again.
