### ISSUE TITLE
When trying to upgrade very old version, receiving failures

### ISSUE THREAD

**Issue by ylluminate** [Open-Shell/Open-Shell-Menu#1706]
### Describe the bug

Running Windows 10 and ran into an issue with a client where they were using an old version (I think it was build 142 (eg, `OpenShellSetup_4_4_142.exe`)) and it failed to upgrade and failed to uninstall due to complaining about a missing .msi for the old version. Even when running the old version and trying to uninstall it, odd things happen (I didn't get all of the details from them due to their extreme frustration/anger at me for the issue since I had installed Open Shell for them long ago).

In the end I only have been able to get the following errors while trying to install build and can no longer successfully install Open Shell for them:
![image1](https://p153.p0.n0.cdn.getcloudapp.com/items/Apul8dmQ/272ce88a-e020-4080-9199-71212aa0fb88.png?v=a985a73832a2a1ab4297201bf156ddd1)

![image2](https://p153.p0.n0.cdn.getcloudapp.com/items/Z4upP4NR/9278a89d-a55e-4185-831c-feca09363efa.png?v=d1528984f4bf1cb414baa2ace95e2fcc)

I thought perhaps I might be able to use the old `ClassicShellUtility` to perform a full and comprehensive removal of the app, but that would not execute:
![image3](https://p153.p0.n0.cdn.getcloudapp.com/items/12uQ68dy/53137c3f-7319-43e0-869a-72c43f490f2a.png?v=af4edfbfdbdb305ade1bcacc92420751)

### Area of issue

Installation/Other

### To reproduce

Try to install a new Open Shell.

### Open-Shell version

4.4.191

### Windows version

Windows 10 22H2

**Comment by ge0rdi** [comment]
> I thought perhaps I might be able to use the old ClassicShellUtility to perform a full and comprehensive removal of the app

I'd say this is the correct way to go as you are dealing with some ancient version of `Classic-Shell`.
You have to _unblock_ it somehow (not sure how exactly it was blocked by administrator).
Eventually try to run the tool in _safe mode_.

**Comment by ylluminate** [comment]
Well, it was still an Open-Shell version and I have manually removed all of the files (there were only a couple) and verified registry entries were gone... And it was running as an admin account.

So you're thinking I can execute the Utility for ClassicShell in Safe Mode successfully to gut it?

**Comment by ge0rdi** [comment]
> So is Safe Mode the only option for executing the old Utility?

It should work normally. I don't know why your machine blocks it. You should search for some way to unblock it.

You can also try latest [Utility](https://github.com/Open-Shell/Open-Shell-Menu/releases/download/v4.4.191/Utility.exe).
Though I'm not sure it will work properly for such ancient version.

**Comment by ylluminate** [comment]
Thanks. Since it's already "uninstalled" and somewhat manually removed, hopefully it will yank out the remaining threads. Appreciate your sharing this new version as I had not seen it.

**Comment by ylluminate** [comment]
@ge0rdi the new version of the utility worked perfectly. Thank you so much for pointing me to it.
