### ISSUE TITLE
Sleep not working

### ISSUE THREAD

**Issue by minman** [Open-Shell/Open-Shell-Menu#171]
Sleep Button is visible but clicking has no effect.

S1-S3, S4 are disabled, except S0 (low power idle mode)

Windows 10 Pro, 1809
Open-Shell Menu 4.4.131

see also https://github.com/coddec/Classic-Shell/pull/20
there others reported issues with SetSuspendState and S0

**Comment by delphersf** [comment]
Windows 10 1909 the same - sleep command with no effect!
And monitor off command effects like sleep!
It seems like it mixed up

**Comment by patricknelson** [comment]
Same here, Windows 10.0.19042.867, Open-Shell Menu v4.4.160

In my case, I click the star button, go to the "Shut down" arrow and select "Sleep" but nothing happens. However, holding shift and pressing Windows key to open the original start menu exposes the native power options, at which point the Sleep command (from there) actually works.

**Comment by patricknelson** [comment]
Another quick update: I found that the typical shortcut to suspend the computer doesn't work for me either, e.g.

```
C:\Windows\System32\rundll32.exe powrprof.dll,SetSuspendState 0,1,0
```

So I'm guessing that might actually just be an issue with my machine's configuration.  I found this forum thread where some people were able to fix it with `powercfg -hibernate off` (which didn't help me). Also found this page but still no luck on my part, but could help others: https://www.tipsdotcom.com/windows-10-sleep-shortcut.html

**Comment by flt4ever** [comment]
Sorry to revive this, but I have the same issue. I confirm what Patricknelson says, pressing the original Windows menu sleep does work but not the one from Openshell. I can also contribute adding that the sleep button from the Start10 menu works fine too, made by Stardock.

**Comment by ge0rdi** [comment]
Should be fixed in [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build.

**Comment by kizernis** [comment]
> What menu style do you use?
Windows 7

**Comment by ge0rdi** [comment]
https://www.tenforums.com/tutorials/7456-add-remove-sleep-power-menu-windows-10-a.html

Check if you have `Sleep` allowed in power options.

**Comment by kizernis** [comment]
The link helped, thank you very much!
Apologies for writing here, I took note of your instructions on how to ask questions.
