### ISSUE TITLE
On some PC, Open-Shell does now show "update and restart" in the shutdown menu when Windows updates are pending

### ISSUE THREAD

**Issue by kai-uwe-rommel** [Open-Shell/Open-Shell-Menu#172]
We use Open-Shell on about 80 Windows 10 PC. 

Usually, when Windows updates are pending, the "shutdown" in the shutdown menu turns into "update and shutdown". It does so on most of our PC. On some PC (about a dozen or so), it does not. Thus users do not notice if updates are pending and do not reboot.

When the users then shift-click on Start and thus open the original Windows 10 start menu and click on shutdown there, they see "update and shutdown" when Windows updates are pending etc.

What could cause this odd behaviour?

**Comment by blackcrack** [comment]
well, diffrent Versions of Windows, home, Pro, and so on.. also the actual stand of update of the WinNT System-Copy's in the disfferent versions..

check it out and write what is different there
to bring a bit feedback in from your part ..
best regards
Blacky

**Comment by kai-uwe-rommel** [comment]
There are no differences. Those systems where it works as expected and those where not have been deployed from the same customized Windows image ...

**Comment by ge0rdi** [comment]
Do you have `Check for Windows updates on shutdown` setting enabled on those affected machines?

Do you connect remotely to those machines? Or does it happen also when logged in locally?

**Comment by kai-uwe-rommel** [comment]
I'd say yes, this setting is enabled. We configure the Open Shell on all PC with a XML file and this sets the option. But I can double check on Friday.

Yes, the problem happens for regular local use. That's why the affected users do not install their pending Windows updates because they simply don't see them.

**Comment by ibuprophen1** [comment]
I'm wondering if the update checks for the Windows Server Update Service (WSUS) is pointing to the correct URL... 


~Ibuprophen

**Comment by kai-uwe-rommel** [comment]
See what I initially wrote: the original Windows start menu does correctly indicate pending updates. So THAT cannot be the case.

**Comment by kai-uwe-rommel** [comment]
The "Check for Windows updates on shutdown" is definitely enabled. I checked that on one of the affected systems.

**Comment by ge0rdi** [comment]
@kai-uwe-rommel 
Please, try to create advanced `Open-Shell` log on affected machine, using these instructions:
https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-obtain-advanced-Open-Shell-Menu-log

Hopefully it will shed some light onto the issue.
