### ISSUE TITLE
[Installer] Classic IE/Explorer should be unchecked by default

### ISSUE THREAD

**Issue by Hadden89** [Open-Shell/Open-Shell-Menu#1721]
### Is your feature request related to a problem? Please describe.

It seems logical on Windows 10/11 considering IE removal. 
Also Classic Explorer because could cause issues so should be left to advanced users.

### Describe the solution you'd like

[Installer] Classic IE/Explorer should be unchecked by default

### Area of issue

Installation/Other

**Comment by ge0rdi** [comment]
It is like that since [4.4.190](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.190).

From changelog:
> Setup: Don't install Classic IE by default

**Comment by Hadden89** [comment]
Oh thanks, guess updating from a pre 190 still had this setting. Tnx for confirmation :)

**Comment by ge0rdi** [comment]
> Guess updating from a pre 190 still had this setting remembered.

Upgrade preserves previous state. So if you have Classic IE installed previously, it will stay installed on upgrade.
Though you can just deselect components you don't want during upgrade.
