### ISSUE TITLE
Classic Explorer horizontal bar stays bright white when Windows 11 system theme is set to dark

### ISSUE THREAD

**Issue by CustodialMatter** [Open-Shell/Open-Shell-Menu#1722]
### Describe the bug

Three things I noticed:

1) There's no way to uninstall the classic explorer bar and only use the better start menu.  But I'm only trying to do this because:

2) The horizontal classic explorer menu bright white on my all-black OS.  There's no apparent way to theme it.  I've tried removing all the buttons, logging out, etc.  This blinding white bar always appears.

**Screenshot**

https://imgur.com/a/92DYubQ

3) When I right click to disable and close it and open a new window, it comes back!

A resolution to any of these 3 issues would solve my problem.  Love the app, Windows 11 is a whole clown circus!  They literally put a bowl of rice in my search bar today with a recipe and that was the last straw, never again

### Area of issue

Windows Explorer

### To reproduce

1. Clean install on latest Windows 11 Pro.  Japanese version, not an insider or other beta build otherwise

2.  I have memory integrity turned on and it's a Xeon W-2145 CPU, a few years old Dell workstation

### Expected behavior

Should either be dark or be able to be hidden and stay hidden

### Open-Shell version

4.4.191

### Windows version

Windows Pro 11 22H2 - 22621.2361

### Additional context

Super appreciate you

**Comment by ge0rdi** [comment]
I think this is the same issue as #827.
