### ISSUE TITLE
Why doesnt it show my username on the menu?

### ISSUE THREAD

**Issue by krek4747** [Open-Shell/Open-Shell-Menu#1734]
### Describe the bug

After I downloaded bunch of skins from the forum, suddenly on all available menus my username wouldnt show up on the top even if I had that ticked. I deleted all the files and uninstalled open shell, but I still have the same issue
![photo_2023-10-12_23-16-34](https://github.com/Open-Shell/Open-Shell-Menu/assets/139050379/56fbfad6-8053-4ff2-ab15-61ed20d177d8)

### Area of issue

Start menu

### To reproduce

1

### Open-Shell version

4.4.191

### Windows version

Windows 11 22h2

**Comment by ge0rdi** [comment]
Look for `User name text` setting.
Most likely it is empty.
Setting it to default should fill your user name.

**Comment by krek4747** [comment]
> Look for `User name text` setting. Most likely it is empty. Setting it to default should fill your user name.

ohh, that worked, thank you!
