### ISSUE TITLE
Open shell automatically implements changes in system on Windows 11

### ISSUE THREAD

**Issue by ORENYT** [Open-Shell/Open-Shell-Menu#1740]
### Describe the bug

I wanted to use Open-Shell to change taskbar. Unfortunately, other parts of system (especially Start and Search bar) were changed without any requests or approval. There are no "default version" for my OS. 

### Area of issue

Start menu, Installation/Other

### To reproduce

1. Download
2. Open app
3. Already everything changes

### Expected behavior

Confirmation of making an injection in OS

### Open-Shell version

4.4.190

### Windows version

Windows 11 Actual

**Comment by ge0rdi** [comment]
This is not a bug.

Main purpose of `Open-Shell` is to replace Windows Start menu.
Taskbar customization is just secondary feature.

If you don't want to use `Open-Shell` start menu, you can change what will be opened by Start key/mouse click in `Open-Shell Menu settings` -> `Controls`.

**Comment by ORENYT** [comment]
I don't think that it is a good feature to make changes automatically, especially for not-professional users, but I'll close the theme. 

> This is not a bug.
> 
> Main purpose of `Open-Shell` is to replace Windows Start menu. Taskbar customization is just secondary feature.
> 
> If you don't want to use `Open-Shell` start menu, you can change what will be opened by Start key/mouse click in `Open-Shell Menu settings` -> `Controls`.
