### ISSUE TITLE
Default start menu settings for all users with zero user interaction

### ISSUE THREAD

**Issue by jedimasterben** [Open-Shell/Open-Shell-Menu#175]
Hi, my organization has been a long time user of Classic Shell, and I only recently learned that it transitioned a few years ago to Open Shell. Before creating system images (for use on student systems where dozens of students could log in to each system daily) I would use command prompt to set a registry key so that the default menu for all users would be the Win7 style. That command was as follows:

[HKEY_LOCAL_MACHINE\SOFTWARE\Ivosoft\ClassicStartMenu]
"MenuStyle_Default"="Win7"

Open Shell doesn't seem to recognize this key when adding it to HKLM\software\OpenShell\OpenShell and I can't find any documentation in Github showing the proper context for this key. Can anyone help me out?

Thank you!

**Comment by ge0rdi** [comment]
Proper key name is now:
`HKEY_LOCAL_MACHINE\SOFTWARE\OpenShell\StartMenu`

Basically company name `Ivosoft` was changed to `OpenShell`.
And component name `ClassicStartMenu` is now just `StartMenu`.

**Comment by jedimasterben** [comment]
Okay, thank you. I had to create the string HKLM\Software\OpenShell\Startmenu as what the program creates on install is \OpenShell\OpenShell. I did it, however, and it did work perfectly. Thanks!

**Comment by ge0rdi** [comment]
`HKLM\Software\OpenShell\OpenShell` is shared key for all components (start menu, classic explorer, classic IE).

It is equivalent of `HKLM\Software\IvoSoft\ClassicShell` in original `Classic-Shell`.
