### ISSUE TITLE
Classic Explorer tool bar remains in the explorer after reconfiguring OpenShell

### ISSUE THREAD

**Issue by xinaovo** [Open-Shell/Open-Shell-Menu#1755]
### Describe the bug
A thin white bar remains in the explorer after I removed the classic explorer feature.
Here's a screenshot:
![屏幕截图 2023-11-08 170648](https://github.com/Open-Shell/Open-Shell-Menu/assets/107630526/f77e1d3f-ae93-4ba9-a27c-cd15a461db60)

### Area of issue

Windows Explorer

### To reproduce

1. Install the OpenShell normally
2. Use the installer to remove the Classic Explorer feature
3. restart the explorer

### Expected behavior

The Classic Explorer will be removed completely and nothing else left in my explorer.

### Open-Shell version

4.4.191

### Windows version

Windows 11 23H2 Home China, build 22631.2506

**Comment by AquaHarp** [comment]
Right-click on the white line and "Lock the toolbars" will appear.
Click on "Lock the toolbars" to erase the white line. 
![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/25244319/a627c8a1-be39-46f7-b21e-bf2721f4e88a)

**Comment by ge0rdi** [comment]
More details in https://github.com/Open-Shell/Open-Shell-Menu/issues/326#issuecomment-813086363.
