### ISSUE TITLE
Allow use of default Windows Search

### ISSUE THREAD

**Issue by stamminator** [Open-Shell/Open-Shell-Menu#1769]
### Is your feature request related to a problem? Please describe.

After [disabling web searching in Windows 11](https://www.tomshardware.com/how-to/disable-windows-web-search), I'm finding that the default search experience works very well and is actually my preferred method. The problem is, if I set `Show search box = No search box` in Open Shell, pressing the Win key and then starting to type (which is the standard way to do a search and the one I'm quite used to) will instead launch whichever app happens to start with the first letter I typed.

### Describe the solution you'd like

It would be great if there were an option which, when you open the Open Shell Start Menu and start typing, it just launches default Windows Search with whatever you've typed.

For example, if I open the start menu and want to search "display", the moment I type "d", the start menu closes and Windows Search launches with "d" already in the search box, and I can seamlessly keep typing "isplay"

This could handle paste events too. If instead of typing, I press Ctrl + V, the entire string that is in my clipboard (not just the first character) would go into Windows Search.

### Area of issue

Start menu

**Comment by ge0rdi** [comment]
> It would be great if there were an option which, when you open the Open Shell Start Menu and start typing, it just launches default Windows Search with whatever you've typed.

If you want to do search via Windows start menu, you can press `Shift + Win` (to invoke standard start menu) and then just type your query.

**Comment by stamminator** [comment]
Closing because [it appears this is not currently possible](https://stackoverflow.com/questions/77488964/is-it-possible-for-a-program-to-launch-windows-search-with-search-text-already-i)
