### ISSUE TITLE
Taskbar texture does not show up in Windows 11

### ISSUE THREAD

**Issue by Platinumhero** [Open-Shell/Open-Shell-Menu#1771]
### Describe the bug

The title says it all, I just switched to Windows 11 (22H2 as of right now) and when I try adding a taskbar texture it won't show up, no matter how I tried.

### Area of issue

Taskbar

### To reproduce

1. Go to the Open-Shell Menu Settings.
2. Go to the Taskbar tab.
3. Select "Taskbar texture" and insert an image.
4. Do what the settings say and restart Open-Shell.

### Expected behavior

IDFK, SHOW THE DAMN TASKBAR IMAGE?!?!?!

### Open-Shell version

4.4.191

### Windows version

Windows 11 22H2

**Comment by ge0rdi** [comment]
Taskbar customizations don't work since Win11 22H2.
See #1342 for more info.
