### ISSUE TITLE
Button text cannot be disabled on custom items in Classic Explorer Bar

### ISSUE THREAD

**Issue by cdn-content** [Open-Shell/Open-Shell-Menu#1775]
### Describe the bug

When adding custom items to Classic Explorer Bar, it is not possible to disable the button text, which makes the toolbar appear clunky. The only way to do so is to leave the label of the custom item blank, which can be confusing. This behavior is not present in the Classic Start Menu component of Open Shell, and it only seems to affect custom items, not built-in ones.

As seen below, the custom item I have added is a menu "File and folder operations" which contains commands such as cut, copy, paste, delete, etc. When giving a name (or tool-tip) to custom items, the button text automatically shows up, and there does not seem to be a way to disable it. Only built-in toolbar items appear as buttons, despite also having names of their own.

![Clipboard01](https://github.com/Open-Shell/Open-Shell-Menu/assets/58697911/00c6cc90-2bda-4432-ac2f-a79b82e5eea1)
![Clipboard00](https://github.com/Open-Shell/Open-Shell-Menu/assets/58697911/4dc798d6-926a-46a7-b2ee-e391e34f575a)

But when I delete the name (or tool-tip) of the custom item, the button text goes away.

![Clipboard03](https://github.com/Open-Shell/Open-Shell-Menu/assets/58697911/05e76bbc-85ae-4e45-9e07-8cb1c868d901)

![Clipboard04](https://github.com/Open-Shell/Open-Shell-Menu/assets/58697911/d43699e2-d0e6-41b1-94f6-a5f41ae5a2df)

### Area of issue

Windows Explorer

### To reproduce

1. Open the settings for Classic Explorer Bar (seashell in the toolbar of Explorer window)
2. Make sure "Show all settings" is checked; click on "Toolbar Buttons" tab
3. Add a custom item such as a menu or shortcut
4. Give this custom item a name and/or tool-tip
5. Click OK and then close any open Explorer windows, then reopen an Explorer window. The button text is now present.

To remove button text:
1. Repeat steps 1-3
2. Delete the custom item's name and/or tool-tip (either by right-clicking it and selecting "Edit item"; by selecting it and hitting Enter to edit or F2 to rename; or by double-clicking it so that its properties window opens up).
3. Repeat step 5 above

Again noticing that the behavior is not consistent across built-in toolbar items versus custom ones,

### Expected behavior

I expected that adding a label or tool-tip to custom items would have them behave like the built-in ones, or that there would be an option to enable/disable button text. It does not appear that there is such an option under Toolbar Settings tab. There is only a checkbox to choose whether the text should be on the side. Perhaps disabling it altogether could be an added feature?

![Clipboard02](https://github.com/Open-Shell/Open-Shell-Menu/assets/58697911/33f11497-bad9-42b6-bbbf-6f67db5ba78c)

### Open-Shell version

4.4.191

### Windows version

Windows 7 Home Premium SP1 x64

### Additional context

Again, I am not sure why this behavior only seems to affect custom menu items, or if there is something I am missing. But if there is a way to make the behavior uniform across all toolbar items (or add an option to enable/disable button text in future releases), it would be kindly appreciated.

**Comment by ge0rdi** [comment]
I don't think this is a bug.
Each item has `Label` field and if there is some text in that field this text is shown in the toolbar.

Standard items just don't have any text in `Label` field.
Therefore no text is displayed for them.

If you don't want to display any text for your _custom_ item then just remove text in its `Label` field.

**Comment by cdn-content** [comment]
Would this be better suited to feature requests? I would still like the name of the item to show up in the settings for convenience, and to have an option to display any labels or none. Maybe even per-item. Classic Start Menu allows this, and so does the Windows native Taskbar and other Taskbar customization programs like Free Launch Bar.

**Comment by ge0rdi** [comment]
> Would this be better suited to feature requests?

Yes, this is definitely more like feature request.
Because you want some functionality that is simply not there (existing functionality works as intended).

**Comment by cdn-content** [comment]
> Yes, this is definitely more like feature request.
> Because you want some functionality that is simply not there (existing functionality works as intended).

Reposted under Feature Requests at #1782.
