### ISSUE TITLE
[suggestion] able to setting up the seat of the Startbutton + start.exe =>read

### ISSUE THREAD

**Issue by blackcrack** [Open-Shell/Open-Shell-Menu#178]
Hi,

I have noticed the seat of the start button and be grow up therewith and have live by side of the of the never other developing the seat of the Start button in Linux fvwm... and MS, like many of us software-spreader of the past 0X times, now the seat of the Start-button never change.. of the left position of the Screen/Desktop surface of us Workplace of the Day's :) .. what is not good.. not really ..
It have ever stay, in silence, left at bottom .. so, we get  slowly bigger screens, 
like UHD-TV's where take a couples of us, because it's easy more cheap as a "Desktop","Workplace" Computer Monitor and give us easy a more hughe workspace..
so why then not set up the possible to move the  Startbutton in the middle
or for right handers at right space of the taskbar behind the Date.. or just
setting up of pixels of the seat of the button from right side or left side or 
in the middle, so it is more right side, 
from right side 400px to the middle
or 
from left side, 400px to the middle 
and 
"in the middle", center of the taskbar, the tasklist left sided ...

If it is possible to move/set it up where have a seat of the startbutton, makes the peoples possible to set it up where have the to pin the Startbutton, and this could be really cool, because it supports right, left handers and hughe monitors .. and the diversity of modding...
that's the first idea..

the 2nd idea .. (for other Programs like RD and Totalcmd)
the 2nd idea is, a exe-file, where popup a menu if it's presed/linked in, 
this can be use in a bar like a MAC-Like bar how Rocketbar and some other ...
This could be cool, if the Moders and designers make a own design and have the possible to set up the Startbutton of the open-shell anywhere on the desktop...
So, linking in the "exefile" (like "start.exe" in the openshell-folder and let popup the startmenu) anywhere where it is link in the "start.exe" with mouseover and active , without any switches or with /mover and /mactive for change the icon if is's possible for. maby both, a start .dll and a .exe... for loading in and have a own running exe file..

best regards
Blacky

**Comment by ibuprophen1** [comment]
Just to clarify.... Are you basically asking about adding the ability to move the actual Start Menu button elsewhere on the Bar? 


~Ibuprophen

**Comment by blackcrack** [comment]
@ibuprophen1 

Hi Ibu,
yes :) if it's possible .... 
to make it able for the users (and maybe for the Administrators)
to use the start in better way... but i believe, the Start-Button is hardcoded ...
best regards
Blacky
