### ISSUE TITLE
Taskbar Texture doesn't work (WIN11 22h2), using 4.4.190.

### ISSUE THREAD

**Issue by srzmnx** [Open-Shell/Open-Shell-Menu#1784]
### Describe the bug

I am trying to use a windows vista taskbar texture on my computer, but the feature doesn't work. I am on the latest version of OpenShell and one version behind on windows (22h2), I don't know why this is occuring but I really need a fix

This is the texture I want:
![gQPNALP](https://github.com/Open-Shell/Open-Shell-Menu/assets/83734653/9b76c602-56b3-403c-8f2d-83c2d67a89e5)

### Area of issue

Taskbar

### To reproduce

>open openshell
>try to set a taskbar texture on win11
>it doesnt work
>wtf.png

### Expected behavior

I expected the taskbar texture get changed.

### Open-Shell version

4.4.190

### Windows version

Windows 11 22H2

**Comment by ge0rdi** [comment]
Taskbar customizations don't work since Win11 22h2 :(
See more details in #1342.
