### ISSUE TITLE
Start menu bug since Win 11 23H2 Update

### ISSUE THREAD

**Issue by sunnywu484** [Open-Shell/Open-Shell-Menu#1786]
### Describe the bug

It seems the start menu hit a bug since Windows automatically updated last night. When I open the start menu, the list is tiny now instead of the original Windows 7 style. Also all the icons in the All Programs menu turned small and I can't see to get it back to normal. Did the Windows 11 update mess something up in the settings I don't know about, and is there some way for me to fix this?
![Screenshot 2023-12-05 120218](https://github.com/Open-Shell/Open-Shell-Menu/assets/28135495/fe8d8e03-db34-4776-96da-3dfc4ad937ca)
![Screenshot 2023-12-05 120230](https://github.com/Open-Shell/Open-Shell-Menu/assets/28135495/6cd5cccd-4150-47e1-8ba6-432a013ee673)

### Area of issue

Start menu

### To reproduce

Install "Windows 11, version 23H2" update. 

### Expected behavior

Nothing to change on Open SHell.

### Open-Shell version

4.4.191

### Windows version

Windows 11 23H2

### Additional context

Everything was fine before the Windows update.

**Comment by ge0rdi** [comment]
Try to clear `Open-Shell` caches.
`Open-Shell Menu Settings` -> `Backup` -> `Clear cached information`

If that doesn't help then please attach your XML configuration.

**Comment by sunnywu484** [comment]
Nope, clearing the cache didn't do anything. I cleared the cache, exited the application, and restarted it. Same thing. Here is XML in plain text (couldn't attach file):

<?xml version="1.0"?>
<Settings component="StartMenu" version="4.4.191">
	<MenuStyle value="Win7"/>
	<ControlPanelCategories value="0"/>
	<ProgramsStyle value="Inline"/>
	<AllProgramsMetro value="1"/>
	<FoldersFirst value="0"/>
	<HideProgramsMetro value="1"/>
	<ShutdownCommand value="CommandLock"/>
	<StartScreenShortcut value="0"/>
	<GlassOverride value="1"/>
	<GlassColor value="0"/>
	<SkinW7 value="Immersive"/>
	<SkinVariationW7 value=""/>
	<SkinOptionsW7>
		<Line>LIGHT=0</Line>
		<Line>DARK=0</Line>
		<Line>AUTO=1</Line>
		<Line>USER_IMAGE=1</Line>
		<Line>USER_NAME=0</Line>
		<Line>CENTER_NAME=0</Line>
		<Line>SMALL_ICONS=0</Line>
		<Line>OPAQUE=0</Line>
		<Line>DISABLE_MASK=0</Line>
		<Line>CUSTOM_TEXT_SIZE=20</Line>
		<Line>BLACK_TEXT=0</Line>
		<Line>BLACK_FRAMES=0</Line>
		<Line>TRANSPARENT_LESS=1</Line>
		<Line>TRANSPARENT_MORE=0</Line>
	</SkinOptionsW7>
	<EnableStartButton value="1"/>
	<StartButtonType value="CustomButton"/>
	<StartButtonPath value="%USERPROFILE%\OneDrive\Documents\Classic Shell\Blue Orb.png"/>
	<SkipMetro value="1"/>
	<MenuItems7>
		<Line>Item1.Command=user_files</Line>
		<Line>Item1.Settings=NOEXPAND</Line>
		<Line>Item2.Command=downloads</Line>
		<Line>Item2.Settings=NOEXPAND</Line>
		<Line>Item3.Command=user_documents</Line>
		<Line>Item3.Settings=NOEXPAND</Line>
		<Line>Item4.Command=user_pictures</Line>
		<Line>Item4.Settings=NOEXPAND</Line>
		<Line>Item5.Command=user_music</Line>
		<Line>Item5.Settings=NOEXPAND</Line>
		<Line>Item6.Command=user_videos</Line>
		<Line>Item6.Settings=ITEM_DISABLED</Line>
		<Line>Item7.Command=homegroup</Line>
		<Line>Item7.Settings=ITEM_DISABLED</Line>
		<Line>Item8.Command=separator</Line>
		<Line>Item9.Command=games</Line>
		<Line>Item9.Settings=TRACK_RECENT|ITEM_DISABLED</Line>
		<Line>Item10.Command=favorites</Line>
		<Line>Item10.Settings=ITEM_DISABLED</Line>
		<Line>Item11.Command=recent_documents</Line>
		<Line>Item11.Settings=ITEM_DISABLED</Line>
		<Line>Item12.Command=computer</Line>
		<Line>Item12.Settings=NOEXPAND</Line>
		<Line>Item13.Command=network</Line>
		<Line>Item13.Settings=ITEM_DISABLED</Line>
		<Line>Item14.Command=network_connections</Line>
		<Line>Item14.Settings=ITEM_DISABLED</Line>
		<Line>Item15.Command=separator</Line>
		<Line>Item16.Command=control_panel</Line>
		<Line>Item16.Settings=TRACK_RECENT</Line>
		<Line>Item17.Command=pc_settings</Line>
		<Line>Item17.Settings=TRACK_RECENT</Line>
		<Line>Item18.Command=admin</Line>
		<Line>Item18.Settings=TRACK_RECENT|ITEM_DISABLED</Line>
		<Line>Item19.Command=devices</Line>
		<Line>Item19.Settings=NOEXPAND</Line>
		<Line>Item20.Command=defaults</Line>
		<Line>Item20.Settings=ITEM_DISABLED</Line>
		<Line>Item21.Command=help</Line>
		<Line>Item22.Command=run</Line>
		<Line>Item23.Command=apps</Line>
		<Line>Item23.Settings=ITEM_DISABLED</Line>
		<Line>Item24.Command=windows_security</Line>
	</MenuItems7>
</Settings>

**Comment by sunnywu484** [comment]
Accidentally closed.

**Comment by sunnywu484** [comment]
<?xml version="1.0"?>
<Settings component="StartMenu" version="4.4.191">
	<MenuStyle value="Win7"/>
	<ControlPanelCategories value="0"/>
	<ProgramsStyle value="Inline"/>
	<AllProgramsMetro value="1"/>
	<FoldersFirst value="0"/>
	<HideProgramsMetro value="1"/>
	<ShutdownCommand value="CommandLock"/>
	<StartScreenShortcut value="0"/>
	<GlassOverride value="1"/>
	<GlassColor value="0"/>
	<SkinW7 value="Immersive"/>
	<SkinVariationW7 value=""/>
	<SkinOptionsW7>
		<Line>LIGHT=0</Line>
		<Line>DARK=0</Line>
		<Line>AUTO=1</Line>
		<Line>USER_IMAGE=1</Line>
		<Line>USER_NAME=0</Line>
		<Line>CENTER_NAME=0</Line>
		<Line>SMALL_ICONS=0</Line>
		<Line>OPAQUE=0</Line>
		<Line>DISABLE_MASK=0</Line>
		<Line>CUSTOM_TEXT_SIZE=20</Line>
		<Line>BLACK_TEXT=0</Line>
		<Line>BLACK_FRAMES=0</Line>
		<Line>TRANSPARENT_LESS=1</Line>
		<Line>TRANSPARENT_MORE=0</Line>
	</SkinOptionsW7>
	<EnableStartButton value="1"/>
	<StartButtonType value="CustomButton"/>
	<StartButtonPath value="%USERPROFILE%\OneDrive\Documents\Classic Shell\Blue Orb.png"/>
	<SkipMetro value="1"/>
	<MenuItems7>
		<Line>Item1.Command=user_files</Line>
		<Line>Item1.Settings=NOEXPAND</Line>
		<Line>Item2.Command=downloads</Line>
		<Line>Item2.Settings=NOEXPAND</Line>
		<Line>Item3.Command=user_documents</Line>
		<Line>Item3.Settings=NOEXPAND</Line>
		<Line>Item4.Command=user_pictures</Line>
		<Line>Item4.Settings=NOEXPAND</Line>
		<Line>Item5.Command=user_music</Line>
		<Line>Item5.Settings=NOEXPAND</Line>
		<Line>Item6.Command=user_videos</Line>
		<Line>Item6.Settings=ITEM_DISABLED</Line>
		<Line>Item7.Command=homegroup</Line>
		<Line>Item7.Settings=ITEM_DISABLED</Line>
		<Line>Item8.Command=separator</Line>
		<Line>Item9.Command=games</Line>
		<Line>Item9.Settings=TRACK_RECENT|ITEM_DISABLED</Line>
		<Line>Item10.Command=favorites</Line>
		<Line>Item10.Settings=ITEM_DISABLED</Line>
		<Line>Item11.Command=recent_documents</Line>
		<Line>Item11.Settings=ITEM_DISABLED</Line>
		<Line>Item12.Command=computer</Line>
		<Line>Item12.Settings=NOEXPAND</Line>
		<Line>Item13.Command=network</Line>
		<Line>Item13.Settings=ITEM_DISABLED</Line>
		<Line>Item14.Command=network_connections</Line>
		<Line>Item14.Settings=ITEM_DISABLED</Line>
		<Line>Item15.Command=separator</Line>
		<Line>Item16.Command=control_panel</Line>
		<Line>Item16.Settings=TRACK_RECENT</Line>
		<Line>Item17.Command=pc_settings</Line>
		<Line>Item17.Settings=TRACK_RECENT</Line>
		<Line>Item18.Command=admin</Line>
		<Line>Item18.Settings=TRACK_RECENT|ITEM_DISABLED</Line>
		<Line>Item19.Command=devices</Line>
		<Line>Item19.Settings=NOEXPAND</Line>
		<Line>Item20.Command=defaults</Line>
		<Line>Item20.Settings=ITEM_DISABLED</Line>
		<Line>Item21.Command=help</Line>
		<Line>Item22.Command=run</Line>
		<Line>Item23.Command=apps</Line>
		<Line>Item23.Settings=ITEM_DISABLED</Line>
		<Line>Item24.Command=windows_security</Line>
	</MenuItems7>
</Settings>

**Comment by sunnywu484** [comment]
[OpenShell 5 Dec 2023 - Copy.txt](https://github.com/Open-Shell/Open-Shell-Menu/files/13577051/OpenShell.5.Dec.2023.-.Copy.txt)

**Comment by Sequenze5517** [comment]
Im using Windows 11 Build 23H2 and it works fine.

**Comment by sunnywu484** [comment]
Rebooted computer, everything is normal now. Might want to offer that up as a solution next time. :)
