### ISSUE TITLE
Cannot upgrade to version Open Shell 4.4.191

### ISSUE THREAD

**Issue by AnaDigit** [Open-Shell/Open-Shell-Menu#1797]
### Describe the bug

I have v4.4.190 installed. When attempting to upgrade to v4.4.191, the program asks me for the location of ''OpenShellSetup_4_4_190.msi" to continue. It cannot find it, therefore the update to v4.4.191 aborts.

### Area of issue

Installation/Other

### To reproduce

1. Download the ''OpenShellSetup_4_4_191.exe''
2. Double-click to install
3. A window pops up asking me for the location of ''OpenShellSetup_4_4_190.msi''
4. Cannot find the file so I have to cancel the update - abort

### Expected behavior

To install the update to v4.4.191

### Open-Shell version

4.4.190

### Windows version

Windows 10 22H2

**Comment by ge0rdi** [comment]
You can download [4.4.190](https://github.com/Open-Shell/Open-Shell-Menu/releases/download/v4.4.190/OpenShellSetup_4_4_190.exe) installer and extract MSI from it by running:
`OpenShellSetup_4_4_190.exe extract64`

Then you can run `4.4.191` installation and provide extracted MSI when installer will ask about it.

**Comment by AnaDigit** [comment]
That did it! Thanks!

Merry Christmas and a Wonderful New Year!
