### ISSUE TITLE
Open Shell start menu button on top of Windows 11 start menu button.

### ISSUE THREAD

**Issue by ayuro123** [Open-Shell/Open-Shell-Menu#1800]
### Describe the bug

Hi, I just upgraded to Windows 11 and for some reason the Open Shell start menu button floats just above the existing start menu button and you can see both, although the original start menu button is partially obscured by the Open Shell button. I did not have this issue with Windows 10.
![Screenshot_19](https://github.com/Open-Shell/Open-Shell-Menu/assets/154864276/d9833a60-e9ff-459a-aadf-5bc4672fb615)

### Area of issue

Start menu

### To reproduce

Settings transferred over from Windows 10, although the issue only crept up a few minutes after upgrading from Classic Shell to Open Shell.

### Expected behavior

I should only see the Open Shell start menu button.

### Open-Shell version

4.4.191

### Windows version

Windows 11

**Comment by ge0rdi** [comment]
On Windows 11, unfortunately, we are unable to replace start button. Thus we can only overlay custom image on top of standard Windows button. If custom image contains transparency then original image will leak through that.

There is nothing we can do about this on Windows 11 (currently). More info in https://github.com/Open-Shell/Open-Shell-Menu/issues/1631.

Though in your case it seems that we have some issue with obtaining position of original Start button (so custom image seems to be shifted up).

What is you exact Windows version?

Do you use other customization software (like ExplorerPatcher, StartAllBack, ...)?

What is your machine? Could it be some kind of tablet with touch screen (without physical keyboard)?

**Comment by ayuro123** [comment]
Hi! Thanks for replying.

My Windows version is Windows 11 Home 23H2.
It is an HP touch-screen laptop with a keyboard, no other customization
software.

**Comment by ge0rdi** [comment]
Hmm, I think it may be the same issue as in #1744.
It seems to be somehow related to machines with touch-screen.
I have no clue what is going on there :(

For now I guess the only workaround is to use standard Start menu image.

**Comment by mhherrUSA** [comment]
Am totally pissed after installing the "Update"  4.4.191.  I have a Lenovo P16s Think Pad laptop with touchscreen.

With this update what used to be a fairly decent successor to the great Classic Shell program has turned to crap.  The START menu icon defaults to overriding existing items on the taskbar, and you can only reposition that by selecting "Custom  Button" and then it only positions the button to the left of the first taskbar item, not the expected result when checking "Align to corner of the screen" which is where the former version placed the "Classic" start button.  Selecting "Custom Button" defaults to the Shell image and attempting to change that to the "Classic" button causes the image to override the leftmost item in the taskbar.  

I give this "Update" a "D" grade.  The least you could have done is provide a USER MANUAL to explain all the new and erroneous behaviors, how to correctly size one's own png file to replace the start button image, and other useful information.

**Comment by AngryRaptor-13** [comment]
I also have this issue. I installed OpenShell version 4.4.191, and I'm using a Lenovo Yoga running Windows Home version 23H2.
<img width="54" alt="Screenshot 2024-02-17 204525" src="https://github.com/Open-Shell/Open-Shell-Menu/assets/160370582/ddf578f1-7922-4f1f-8d3f-af3ab3de4393">

**Comment by ge0rdi** [comment]
@AngryRaptor-13 
I assume your Lenovo Yoga also has touch screen, right?

**Comment by ge0rdi** [comment]
This is the same issue as #1744, so closing this one.
Please, check that issue for more info.
