### ISSUE TITLE
Start menu *.lnk neither listed as favorite nor visible in search

### ISSUE THREAD

**Issue by Dragodraki** [Open-Shell/Open-Shell-Menu#1802]
### Describe the bug

There are two problems, maybe they are connected somehow:
My OS: Windows 11 23H2 64-Bit (upgraded from Windows 7 to Windows 10 to Windows 11 a week ago)
Open Shell version: 4.4.191.0

On the one hand, in "Main Menu" -> "Pinned Programs Folder" the option "Use Start Menu folder" does not show any existing *.lnk (shortcut) files (I am aware of them being in %appdata%\Microsoft\Internet Explorer\Quick Launch\User Pinned\StartMenu\) when opening Open Shell. Copying them to a custom folder and choosing option "Pinned folder path:[...]" leads to Start menu immediately displays them. 
![grafik](https://github.com/Open-Shell/Open-Shell-Menu/assets/76787321/632eb951-2b82-4eca-ab97-799e489514d8)

The seccond error targets both options as well. Windows 7 was able to detect *.lnk files from nearly the entire system partition and include them to the search results. To make it easy for me, I store most of them in a subfolder from %appdata%\Microsoft\Internet Explorer\Quick Launch\User Pinned\StartMenu\...\ - like I said Windows 7 search detected them, but Open shell does not at all.
My index options were left untouched, so I doubt them to be the culprit here:
![grafik](https://github.com/Open-Shell/Open-Shell-Menu/assets/76787321/938c13ac-6c5c-450c-b403-ff7fbf9b579f)

Could you make Open Shell detects *.lnk files from everywhere like Windows 7 default was able to do? And please, fix the option for "Main Menu" -> "Pinned Programs Folder" the option "Use Start Menu folder" as well.

### Area of issue

Start menu

### To reproduce

Problem 1:  "Main Menu" -> "Pinned Programs Folder" the option "Use Start Menu folder"
Problem 2: Place a shortcut from a single third party executable (not programs that are installed by any setup) anywhere on system drive -> Open Shell does not detect them when searching

### Expected behavior

1. "Main Menu" -> "Pinned Programs Folder" the option "Use Start Menu folder" should the shortcut entries from "%appdata%\Microsoft\Internet Explorer\Quick Launch\User Pinned\StartMenu\".
2. Shortcuts (*.lnk files) from the whole system drive should be detected by Open Shell, even if the linked binary is not installed via setup wizard.

### Open-Shell version

4.4.191.0

### Windows version

Windows 11 23H2

**Comment by ge0rdi** [comment]
> Could you make Open Shell detects *.lnk files from everywhere like Windows 7 default was able to do?

`Open-Shell` uses built-in Windows _indexing_ to obtain search results.
Do those _lnk_ files appear in standard Windows Start menu when you search for them?

For the future, please, create one ticket per issue. It is much easier to track it that way.

**Comment by ge0rdi** [comment]
`Use Start Menu folder` option uses `FOLDERID_StartMenu` known folder that should typically expand to `%APPDATA%\Microsoft\Windows\Start Menu`.

So you should have those _lnk_ files in such folder if you want to see them.

**Comment by Dragodraki** [comment]
@ge0rdi: Now that you mention it, Windows 11 is not capable of showing that too. But Windows 7 definitely was and I know for sure there were no other indexed elements before. Maybe you can look into making Open Shell support it too since its task should be to emulate classic experience...

%APPDATA%\Microsoft\Windows\Start Menu\ is used for default system shortcuts and those installed by setup wizards - it has nothing to do with my question. Pinned items are/were stored here by Windows until 10 when it was discontinued:
%appdata%\Microsoft\Internet Explorer\Quick Launch\User Pinned\StartMenu\*

So I assume here is a misunderstanding. If Open Shell would like to provide the option to continue the location of shortcuts from earlier windows versions ("Main Menu" -> "Pinned Programs Folder" the option "Use Start Menu folder"), one has to look into %appdata%\Microsoft\Internet Explorer\Quick Launch\User Pinned\StartMenu\*. I don't know about Windows 2000/XP but for Vista/7/8 it is nowhere but this directory.

**Comment by ge0rdi** [comment]
> Windows 11 is not capable of showing that too

That means your files are not indexed properly.
Try to check indexing settings (maybe some folders/extensions are not indexed?). Or rebuild search index to see if that will help.
Once you have files indexed properly, they should show up in `Open-Shell` start menu.

> it has nothing to do with my question

I tried to explain what `Use Start Menu folder` option does.
As the name suggests (and tooltip confirms) it is simply about placing pinned items to default start menu folder.

If you want to use that option, then just move your items to folder I mentioned.
Or just move them to default `Open-Shell`'s pinned folder `%APPDATA%\OpenShell\Pinned`.

**Comment by Dragodraki** [comment]
I can see your point regarding it's not a bug then, but more an unfinished feature. You might condider moving this issue to another category if you feel so.

@ge0rdi 
> I tried to explain what Use Start Menu folder option does.
> As the name suggests (and tooltip confirms) it is simply about placing pinned items to default start menu folder.
As you can see in my first posted picture, this is not the case on my system.

> If you want to use that option, then just move your items to folder I mentioned.
Honestly, whats the reason for a ticket module if not to report bugs and things user wants to see improved?
The folder you mentioned contains some shortcuts by default and those from installations, but I highly doubt this is what Open Shell tries to implement here.

@everyone
The pinned items from users were stores here for a decade now: "%appdata%\Microsoft\Internet Explorer\Quick Launch\User Pinned\StartMenu\". [https://superuser.com/questions/171096/where-is-the-list-of-pinned-start-menu-and-taskbar-items-stored-in-windows-7](https://superuser.com/questions/171096/where-is-the-list-of-pinned-start-menu-and-taskbar-items-stored-in-windows-7). Of course the actual settings are stored in the registry, but since Windows Vista the called path provides something like a log and would provide easy method for Open Shell to do it the other way round: The shortcuts laying here could pinned into the the start menu from Open Shell to continue the session the users performed with MS start menu.

The seccond problem with indexing is not a bug targetting Open Shell, thats's for sure. But I would be very glad, if you could make Open Shell adding *.lnk files from the whole system drive make the users experience like Windows Vista/7/8 as close as possible (even if the indexing options say otherwise). The intention of shortcuts - wherever they are stored - are to shorten the call for apps and functions. I am sure most users intention would be seeing them displayed when performing an explicit search.

**Comment by ge0rdi** [comment]
> Honestly, whats the reason for a ticket module if not to report bugs and things user wants to see improved?

I have just explained how particular `Open-Shell` option works. There is no bug in it. It simply does what it says.
If you think it may be good idea to have an option for using some _obsolete_ folder for pinned items, you can of course create [Feature request](https://github.com/Open-Shell/Open-Shell-Menu/issues/new?assignees=&labels=Enhancement%2FFeature+Request&projects=&template=feature_request.yml) for that.

Though honestly, what's the problem to just move your _lnk_ files from folder that is no longer used by Windows to folder where `Open-Shell` stores its pinned items by default?
That would solve your issue with little effort.

> it's something set in stone and shouldn't be changed

Modern Windows doesn't use such folder anymore. In fact pinning to Start menu work differently there.
That's why `Open-Shell` has its own folder for pinned Start menu items (as it works differently than modern Start menu pinning). 

> But I would be very glad, if you could make Open Shell adding *.lnk files from the whole system drive into search results (of course if several *.lnk points to the same origin, one entry should be enough), making the users experience like Windows Vista/7/8 as close as possible (even if the indexing options say otherwise).

It would take ages to search whole system drive for _lnk_ (or other) files. They are typically created in well known locations (such as start menu, desktop, etc). So that they can be easily indexed and thus looked up fast.

Seriously, you should rather check (and fix) your indexing.

Eventually, if you move your _lnk_ files to `Open-Shell`'s pinned folder (as suggested above) they should appear in search results even if indexing doesn't work.

**Comment by Dragodraki** [comment]
My index is untouched. But I deleted it like you suggested anyway and I also ran Windows troubleshooting several times and sfc as like updates. Problem remains the same.

Here, one last try to show it to you.

![Search not work](https://github.com/Open-Shell/Open-Shell-Menu/assets/76787321/ebcdad4b-833a-45a1-a762-e87dcf3c11bb)

In the follwing screenshot I used as search key word "BlueScreenView". You can see the shortcuts to be present on my phyical as like on the virtual machine in VMware (original Windows 7 without Open Shell). My VM represents exact the behaviour from my earlier Windows 7 where all shortcuts from the entire drive are found (even if not explicit included in indexing options and with the binarys missing).
On my physical Windows 11 host (looks like Windows 7 now with Open Shell installed) indexing default is set and most the same like on earlier OS and my VM. Here Windows does not find any of the entries.

So, its indeed a bug - a Windows bug! But I thought Open Shell should do better than Windows - if you insist Open Shell must adapt to buggy settings shipped with new operating systems, I'll stop bothering you immediately. Otherwise you might consider fixing it somehow... for the sake of a functional system like many of us knew for years.

**Comment by ge0rdi** [comment]
My suggestion is simply to move your _lnk_ files to `%APPDATA%\OpenShell\Pinned`.
That way they will be pinned to start menu and also they should appear in search.

The other alternative is to just fix your _indexing_ settings as apparently there is some problem with them.

**Comment by Dragodraki** [comment]
How should I perform a GUI index fix? There is no troubleshooting for this besides the index re-build, and it did that already. When updating I even made annual feature updat which repairs all found errors.

![Uploading grafik.png…]()

I moved my pinned items to `%APPDATA%\OpenShell\Pinned` now. But the seccond problem remains: Not all shortcuts should be statically diplayed by open start menu - not that the place were there for so many. Thats the reason for why I have a subfolder with the rest of them inside %APPDATA%\OpenShell\Pinned\Additional Shortcuts\ and would like them to be found  when performing searches.

**Comment by ge0rdi** [comment]
I think the _problem_ here is that `AppData` folder is excluded from indexing by default.
You may try to change that, but it is hidden folder so it may be not straightforward.

Instead, I'd recommend to put your `Additional Shortcuts` folder to some indexed location.
For example Start menu folder.
Just right-click on start button, select `Open` and copy your folder with links there.

**Comment by Dragodraki** [comment]
> I'd recommend to put your Additional Shortcuts folder to some indexed location.

Only special folder like `%systemdrive%\Users\%username%\Desktop\` works but I don't want them all to lay on my Desktop or in my Documents. `%AppData%\Microsoft\Windows\Start Menu\Programs\` folder is currently in discussion to remove support for subdirs too by MS.

> I think the problem here is that AppData folder is excluded from indexing by default.

As you can see in my last screenshot, in VM (Windows 7 Original) `AppData` is also excluded, but it works fine ever since. I assume they mean binary files by that.
Your suggestion was to put them into another folder than AppData: It does not work either. If I copy "BlueScreenView.lnk" to the root user location - `%systemdrive%\Users\%username%\` - they are not detected by index too.

> You may try to change that, but it is hidden folder so it may be not straightforward.

I added whole C:\ drive to index experiementally. No changes, not after restarting explorer and not after waiting some time. In the end I reverted back to default setting to not break anything else accidently.


A few minutes ago I checked it with another computer: Windows 10 on the notebook from my sister (completely other configs) - here the problem exists too.

> It would take ages to search whole system drive for lnk (or other) files.

All I know is that Windows Vista/7/8 perform that within 2-3 sec, however they achieve that.

---
Don't get me wrong, I don't want to appear annoying. I am open for other possible solutions and very grateful for such a great tool like Open Shell exists in the first place. You (and your team?) did a fantastic job by creating/continuing it. With my problem you were my first approach since I thought it likeley to be you'd came up with another great implementation how to restore that feature like so many other so far.

**Comment by Dragodraki** [comment]
I copied my shortcuts all to `%AppData%\Microsoft\Windows\Start Menu\Programs\` - its a workaround. You can either improve search function in Open Shell or let it.

I'll miss all shortcuts being indexed no matter their location from earlier OS but it's a MS thing and I think it's new operating systems are getting worse and worse in terms of basic functions.
