### ISSUE TITLE
Bug with open shell and language dll

### ISSUE THREAD

**Issue by seba2282** [Open-Shell/Open-Shell-Menu#1808]
### Describe the bug

Hello,
After put  dll with my language to open shell, in updater go somewhere possible update nightly versions and from openshell, updater change name and is that site from last classic shell 

### Area of issue

Installation/Other

### To reproduce

![Openshell_1](https://github.com/Open-Shell/Open-Shell-Menu/assets/16944478/62bc3202-ac14-48c3-acf1-e62452178267)

![Openshell_2](https://github.com/Open-Shell/Open-Shell-Menu/assets/16944478/b06639a2-f406-41a4-89f7-973d1862163a)

It is without dll and with dll 

### Open-Shell version

4.4.191

### Windows version

Windows 10/11 all

**Comment by ge0rdi** [comment]
This is because you are using _old_ localization DLLs from `Classic-Shell`.
They are compatible with `Open-Shell` but they don't contain any new changes.

We don't support localizations in `Open-Shell` much (at the moment).
More on that in https://github.com/Open-Shell/Open-Shell-Menu/discussions/1627.

**Comment by seba2282** [comment]
Thanks for informations. Tell me then, how it will be then in future updates? will come normally by updater? What about unlock option update and nightly after use dll language? And will be some fixes in future and support languages too in some future updates?

**Comment by ge0rdi** [comment]
I'm afraid there is no plan to support localizations in reasonable future.

As I explained in linked discussion, we'd need to create some localization system that will allow us easily build and deploy localization DLLs (or something else). Somebody would have to do this and I'm not aware of anyone that would like to have a look at this area.

**Comment by seba2282** [comment]
One more thanks for all answers on my asks. I hope someday will be that support for languages. And hope all success in working over openshell for all team.
