### ISSUE TITLE
Open Shell stops restart/reboot

### ISSUE THREAD

**Issue by Papa-Echo** [Open-Shell/Open-Shell-Menu#181]
I have a new notebook with Windows 10 1809. After installing Open Shell 4.4.138 I had problems with the reboot of Windows. The problem is that Windows shuts down the computer during the restart process. It’s like pulling the plug or a blackout during the system startup.
Because I did not know that the problem was coming from Open Shell, I contacted the seller and returned the notebook. They sent me a new notebook. Everything worked fine, until I installed Open Shell on this second notebook. Then I had the same problem again. This time I uninstalled Open Shell and everything worked fine again.
Please fix the problem!

**Comment by ibuprophen1** [comment]
This is a new one.... Interesting... 

To be honest, I doubt anything can be done without something more to go on. Some type of logs and such are really needed to see what/how Windows and Open Shell is actually doing and why. 

Also, you had mentioned that you had installed Open Shell v4.4.138 when the latest stable version is v4.4.131. Had you tried the latest stable version? 


~Ibuprophen

**Comment by Papa-Echo** [comment]
If you go to this link https://www.majorgeeks.com/mg/getmirror/classic_start,1.html
you'll get 4.4.138.
Where do I get the latest stable version?
I think on the first notebook I had 4.4.131, but I am not 100% sure.

**Comment by blackcrack** [comment]
https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts

**Comment by ibuprophen1** [comment]
@blackcrack, those are Nightly Builds... 

The following location is where the Stable Builds are. 

https://github.com/Open-Shell/Open-Shell-Menu/releases

Nightly Builds are primarily those that are a work in progress that are created when various pull requests are merged and there's times when the Nightly Builds pass but, something may be found that requires additional work or the previous merge may require to be temporarily/permanently reverted. 


~Ibuprophen

**Comment by blackcrack** [comment]
i have wrote in the post, they are non-official, and nightly =>  Nightly (nicht offiziell !)
therewith become we are more feedback if there something.. but what the others have wrote.. and have not wrote the addition, i am not responsible. In an case know the peoples of the efb.nu this to appreciate that one, that the world does, can i not say :) 
But i have see, this 4.4.138 is not only post in MG, it is also post in different other Freeware Forums, without the addition Nightly/unstabile/inofficial from any one so stupid and have post this as normal Version .. and this makes me also a bit angry.. but what want we do.... at the end comes the most peoples and give feedback.. what's also well .. and in the other hand be there new versions and the peoples see, there does something.. as if nothing is doing, and then after a long time until a new release comes out ..
I guess, this is a bit a yingyang how can to classify it..

best 
Blacky

**Comment by ibuprophen1** [comment]
The website your referring to has no affiliation with the Official Open Shell. Your post spreads the word for this software but, doesn't do so in an official manner. Also, the OP member here didn't mention your website. Your bringing up information that wasn't even the case here to begin with. 


~Ibuprophen

**Comment by blackcrack** [comment]
@ibuprophen1 

i have wrote, it is unofficial, hun ! This is a nightly page .. how i had read it.. and i have wrote it also, to be it not official Ibu .. so it's not my fail to be other Page's use it as official..
what it is totally wrong.. if they are say, it's officially .. so, it's not comes from me.. so Ibu,
this webpage exist, the owner make a fail if he spread this "nightly builds" and give it open, because this page can be found by anyone, not only by me Buddy ;)

best regards
Blacky
