### ISSUE TITLE
There should be an "Apply" button at the bottom of Settings dialog so that user can see the effect in the middle of setting

### ISSUE THREAD

**Issue by Heng-Zhou** [Open-Shell/Open-Shell-Menu#1811]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

Unlike Linux which requires users to know what they are doing, Windows users sometimes have no idea what a feature is. So is the Open-Shell software. Some features may be never known to user and the user just wants to know whether this is the feature he likes and would like to apply. Currently, the user has to click "OK" to quit the whole dialog to apply the changes. When he is back, it is highly likely he is lost where he was and thus has to search many features for the location where he closed the settings dialog. So, please add an "Apply" button at the bottom of Settings dialog so that user can see the effect in the middle of setting and continue from where he is without having to break by closing the whole dialog. Thanks.

### Area of issue

Start menu, Taskbar, Windows Explorer, Internet Explorer, Installation/Other

**Comment by ge0rdi** [comment]
Most of settings should have immediate effect.
If you change Start menu style for example, you should see it applied next time you'll invoke start menu. There is no need to close settings dialog.

Some settings require `Open-Shell` exit and then start, or starting new Explorer window (in case of Classic Explorer). But those usually show message-box about that when changed.

Do you have an issue with concrete setting(s)?

**Comment by Heng-Zhou** [comment]
Glad to know. Maybe I didn't notice that.
