### ISSUE TITLE
Be able to change the order of Shut Down... menuitems

### ISSUE THREAD

**Issue by Heng-Zhou** [Open-Shell/Open-Shell-Menu#1813]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

I use menu form for the "Shut Down ...":

![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/111557423/6e9501d4-d680-4bcb-bfbb-6270ac389ec8)

in which the positions of menuitems are fixed. But I'd like to move "Hibernate" to the bottom of the menu for personal preference. Is it possible for Open-Shell to add a function in its Settings dialog to allow users to adjust position of menuitems? Thanks.

### Area of issue

Start menu

### Alternatives you've considered

Also, I hope I can remove some menuitems from "Shut Down...". For example, I am the only user of my Windows machine and no one would enter my room, so there is no need for "Switch User". So is "Log off" and "Lock" for the same reason. Also, as long as I am awake and at home, I am sitting in front of the machine, so "Sleep" menuitem is useless to me either. If I really need them, I can select them in Ctrl-Alt-Del screen. Hope Open-Shell can add this function for users like me (I'm sure there are many). Thanks.

**Comment by ge0rdi** [comment]
> Also, I hope I can remove some menuitems from "Shut Down...".

There is `Shutdown menu items` setting where you can set items that should be displayed in shutdown box.
Have a look at the tooltip to see how to edit it.

As for the order of items, it seems to be hard-coded currently. Not sure how easy/feasible it would be to allow reorganization of those items.

My advice is to simply select the most used shutdown command to be available in shutdown button (see `Shutdown command` setting) and then the order of rarely used commands shouldn't really matter.

**Comment by Heng-Zhou** [comment]
OK, I made it by drag and drop. It's not hard-coded.
