### ISSUE TITLE
﻿  Failed to extract setup file C:\ProgramData\OpenShellSetup64_4_4_191.msi'.

### ISSUE THREAD

**Issue by EmanuelAbate6565** [Open-Shell/Open-Shell-Menu#1825]
### Describe the bug

![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/85616930/5e1b091f-be2d-41a8-956c-550fab7917b5)

This happens when opening installer

### Area of issue

Installation/Other

### To reproduce

Just Opening The Installer causes this

### Open-Shell version

4.4.170

### Windows version

Windows 11 Version 22H2 (Build 22621.2861)

**Comment by ge0rdi** [comment]
This error is reported when it was not possible to create mentioned file.

Check permissions of `C:\ProgramData`, by default standard users should be able to write there.
Eventually, start the installer as Administrator.
