### ISSUE TITLE
My explorer.exe keeps restarting upon launch

### ISSUE THREAD

**Issue by BigMacWhoppers** [Open-Shell/Open-Shell-Menu#1830]
### Describe the bug

My process called **explorer.exe** keeps crashing and restarting upon setting the icon size to 0. I have uninstalled Open shell to prevent my CPU usage going to 100% and my pc crashing. _Do i install it, and set all to the defaults or do i reinstall my system?_

### Area of issue

Windows Explorer, Installation/Other

### To reproduce

1. Get apples monocolumm skin (i think thats the name)
2. Go to start menu tab
3. set icon size to 0
4. apply

### Expected behavior

uhh i expected for it to not crash

yeah

### Open-Shell version

4.4.191

### Windows version

Windows 10 22h2

### Additional context

cpu go boom

**Comment by ge0rdi** [comment]
> Get apples monocolumm skin (i think thats the name)

Could you provide the link to the skin you are using?
Does the issue happens only with that skin or also with default one?

> Go to start menu tab

What start menu tab you mean?
You mean tab in `Open-Shell` settings? Please, provide exact name of it.

**Comment by BigMacWhoppers** [comment]
> > Get apples monocolumm skin (i think thats the name)
> 
> Could you provide the link to the skin you are using? Does the issue happens only with that skin or also with default one?
> 
> > Go to start menu tab
> 
> What start menu tab you mean? You mean tab in `Open-Shell` settings? Please, provide exact name of it.

I think the skin that i used was posted on: http://www.classicshell.net/forum/viewtopic.php?f=17&t=5096 (apple.zip)
use a vm to test it since it says its a dangerous download idk
And, i forgot the name of the tab, its just the one with start menu icon size.

**Comment by ge0rdi** [comment]
> And, i forgot the name of the tab, its just the one with start menu icon size.

You mean this in `Menu look`?
![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/2453094/86179da9-decc-493e-8d12-8a5bd6e765e3)

Or icon size in `Start button` tab?
![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/2453094/c7e3b901-737a-4b0b-9b59-8e5c908d426d)

**Comment by BigMacWhoppers** [comment]
> > And, i forgot the name of the tab, its just the one with start menu icon size.
> 
> You mean this in `Menu look`? ![image](https://private-user-images.githubusercontent.com/2453094/301573287-86179da9-decc-493e-8d12-8a5bd6e765e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MDgyNDYsIm5iZiI6MTcwNjgwNzk0NiwicGF0aCI6Ii8yNDUzMDk0LzMwMTU3MzI4Ny04NjE3OWRhOS1kZWNjLTQ5M2UtOGQxMi04YTViZDZlNzY1ZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMTcxOTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGIwMzZmNDA2NDJlOTk5OWFhZjNmZDJlZjMzYzlmODI1MGYwNTc1MzA2NzIxYTlhZGM3NDQwMjQ4ZGQzOGQ2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eaLy58uASqax5QWf8_G_JO3zuSH0aW7Bc4duekOraig)
> 
> Or icon size in `Start button` tab? ![image](https://private-user-images.githubusercontent.com/2453094/301573627-c7e3b901-737a-4b0b-9b59-8e5c908d426d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MDgyNDYsIm5iZiI6MTcwNjgwNzk0NiwicGF0aCI6Ii8yNDUzMDk0LzMwMTU3MzYyNy1jN2UzYjkwMS03MzdhLTRiMGItOWI1OS04ZTVjOTA4ZDQyNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMTcxOTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzdiNjE0N2RkNWMwODAzOWViZGUzZTYxZWY3Zjc0OGYzNGM3ZjI5NTNkNWNjMDMyMDQxYjAzMWEzNzc0M2U0ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JHhf665Kgxl5hYBn6mJRisqgTafYzNK8WHshq_BYrUY)

yes. i set the icon size to 0 and it restarted explorer and my cpu went boom

**Comment by ge0rdi** [comment]
But what setting did you change to 0?
Is it a problem to write exactly how to replicate the issue?

**Comment by BigMacWhoppers** [comment]
> But what setting did you change to 0? Is it a problem to write exactly how to replicate the issue?

i set both settings to 0 in MENU LOOK tab and, yeah open shell went drunk that time.

**Comment by ge0rdi** [comment]
> i set both settings to 0 in MENU LOOK tab and, yeah open shell went drunk that time.

I did the same in clean `Open-Shell` installation in Windows Sandbox and it doesn't seem to cause any problem.
Start menu just doesn't show any icons (which is kind of expected).

Could you provide crash dump from Explorer crashing obtained using this [guide](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-create-dump-on-Windows-Explorer-crash)?

**Comment by BigMacWhoppers** [comment]
> > i set both settings to 0 in MENU LOOK tab and, yeah open shell went drunk that time.
> 
> I did the same in clean `Open-Shell` installation in Windows Sandbox and it doesn't seem to cause any problem. Start menu just doesn't show any icons (which is kind of expected).
> 
> Could you provide crash dump from Explorer crashing obtained using this [guide](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-create-dump-on-Windows-Explorer-crash)?

Sir, i am sorry for wasting your time. But i launched the latest version and reset all changes to defaults, which fixed the problem.

**Comment by ge0rdi** [comment]
Oki, great.
Thank you for letting us know.
