### ISSUE TITLE
Latest Windows Release (Canary Channel: 26040) - Tray Missing

### ISSUE THREAD

**Issue by rkmfl** [Open-Shell/Open-Shell-Menu#1831]
### Describe the bug

Once I install Open-Shell in the latest Win 26040 release (Win 11 / Server 2025), the tray (time and TSR apps, the right-side of the taskbar) disappears.

I assumed this was not an Open-Shell issue; however, if I uninstall, the tray returns.

### Area of issue

Taskbar

### To reproduce

Install Win 11 using 26040 release. Note tray shows. Install Open-Shell, note tray disappears.

No preferences option causes it to return.

### Open-Shell version

4.4.191

### Windows version

Windows 11 Insider (26040)

**Comment by ge0rdi** [comment]
Do you have taskbar customizations enabled?
`Customize taskbar` check-box in `Open-Shell` settings.

**Comment by rkmfl** [comment]
Thank you for the reply. I should have mentioned that I tested this thinking it may be the issue.

Both on or off, it has not changed the behavior; the tray is missing in both.

Thank you.

**Comment by ge0rdi** [comment]
I can't replicate such behavior :(
My tray looks fine:
![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/2453094/50043102-c11c-4961-be11-e421db799ab7)

Does the issue get fixed when you exit `Open-Shell` (right click on Start button and `Exit`)?

**Comment by rkmfl** [comment]
Thank you for trying:
<img width="250" alt="image" src="https://github.com/Open-Shell/Open-Shell-Menu/assets/3689892/d7124855-40bd-4051-a4b2-52a3598ba6d8">

You're correct, it must be something wrong with my specific system because ```exit``` does not cause it to re-appear. Uninstalling did.

I will continue to research; however, based on your experience, I suspect it may be unique to my system. Thank you.

**Comment by ge0rdi** [comment]
Do you use other customization software (like `ExplorerPatcher`)?
Maybe try to uninstall those to see if it helps.

`Open-Shell` should be affecting taskbar only with `Customize taskbar` enabled (well, at least looking at code).

**Comment by rkmfl** [comment]
Thank you. I tested on a fresh copy with nothing but Open Shell and the tray worked fine.

This was my error and is not a bug. Thank you to @ge0rdi for your help.
