### ISSUE TITLE
Start, Programs, Startup is left empty.

### ISSUE THREAD

**Issue by MichaelIsGreat123** [Open-Shell/Open-Shell-Menu#184]
Open-Shell leaves empty the Startup when it should not be. It is a BUG I guess.

**Comment by ibuprophen1** [comment]
More information is really needed... 

There's a few different ways I can assume what you're referring to and I prefer not to assume anything. 

Thank you very much! :-) 


~Ibuprophen

**Comment by MichaelIsGreat123** [comment]
OK, I am not sure what more information you need. But let me be more detailed if you find it more helpful.

I use Windows 10. To find which startup programs are opened when the computer is rebooted or when it is powered on from scratch, you can easily find these programs by doing Settings, Apps, Startup. There you see several programs that are launched at Startup when the computer is powered on.

If Open-Shell is logical, these same startup apps or programs should also be listed in the Open-Shell GUI used for the Start button that replaces the default Start GUI used in Windows 10. So, in Open-Shell, in Start, Programs, Startup, I also should see these same apps or programs but instead the Startup folder is completely empty.

I hope this explanation clarifies my initial posting.

Many things to the developers of Open-Shell. Without Open-Shell, I will really have a very bad time being productive in Windows 10.

**Comment by pepoluan** [comment]
Start > Programs > Startup will only show the contents of the Startup folder in `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup`. This is classically where programs will put a shortcut to be launched at startup.

Windows 10 does things differently, though. What you see in "Settings > Apps > Startup" does not all come from the aforementioned folder.

I see no bug.

**Comment by bonzibudd** [comment]
I believe this is by design. The "Startup" folders in AppData and ProgramData are only one of the many ways a program can set itself to launch at startup. Since it is a physical folder location, it wouldn't make sense to add entries from other sources.

**Comment by bonzibudd** [comment]
Open-Shell displays the "Startup" folder(s) as-is in their true path. Adding items from other sources would be unnecessary and misleading to the end-user.
