### ISSUE TITLE
Dell Precision 5540 laptop + Win11 does not go to sleep after updating to any version after 4.4.170

### ISSUE THREAD

**Issue by vkrevs** [Open-Shell/Open-Shell-Menu#1841]
### Describe the bug

Attempted to update to latest OpenShellMenu version 4.4.191 from 4.4.170 on my Dell Precision 5540 laptop + Win11 (22H2 build 22621.3007).

After update, clicking on Log Off -> Sleep does nothing.
Tried all versions between 4.4.170 and 4.4.191 - 4.4.170 is the last version that works.

### Area of issue

Installation/Other

### To reproduce

1. Install v4.4.191  on  Dell Precision 5540 laptop + Win11 (22H2 build 22621.3007).
2. Click on Log Off -> Sleep
3. Laptop does not go to sleep

### Expected behavior

Laptop goes to sleep

### Open-Shell version

4.4.191

### Windows version

Windows 11 22H2 (OS build 22621.3007)

**Comment by vkrevs** [comment]
Reverting to 4.4.170 allows the laptop to sleep again.

**Comment by ge0rdi** [comment]
> Tried all versions between 4.4.170 and 4.4.191 - 4.4.170 is the last version that works.

Interesting.
The only change related to `sleep` command I remember was https://github.com/Open-Shell/Open-Shell-Menu/commit/db0e768f817e872103969a1345087071e1b22211 in `4.4.185`.

So I'd expect if `4.4.170` works for you, then also `4.4.184` should work too (and `4.4.185` won't).
Could you possibly check that?

**Comment by vkrevs** [comment]
My apologies, I did not test the pre-release versions. Yes, it is exactly as you describe - 4.4.184 works and laptop sleeps and 4.4.185 doesn't. The screen gets turned off but the laptop does not sleep, fan is still on, etc and  pressing any key on the keyboard wakes up the screen.

**Comment by ge0rdi** [comment]
Thank you for confirmation.

I assume that `Sleep` from default Windows start menu works as expected, right?

Could you post output of `powercfg /a` command?

**Comment by vkrevs** [comment]
Actually, `Sleep` from default Windows start menu does not work. I've been using ClassicShell/OpenShellMenu for so long,  forgot to check that ... 

But `Hibernate` from default Windows start menu does work and it appears that what 4.4.170-4.4.184 did when I clicked `Log Off->Sleep` was actually equivalent to `Hibernate` ... 

So I guess OpenShellMenu 4.4.185+ does exactly what default Windows start menu does.  I'll close the issue.

`powercfg /a` output:

```
The following sleep states are available on this system:
    Standby (S0 Low Power Idle) Network Connected
    Hibernate

The following sleep states are not available on this system:
    Standby (S1)
	The system firmware does not support this standby state.
	This standby state is disabled when S0 low power idle is supported.

    Standby (S2)
	The system firmware does not support this standby state.
	This standby state is disabled when S0 low power idle is supported.

    Standby (S3)
	This standby state is disabled when S0 low power idle is supported.

    Hybrid Sleep
	Standby (S3) is not available.
	The hypervisor does not support this standby state.

    Fast Startup
	This action is disabled in the current system policy.

```
