### ISSUE TITLE
Feature Request - Windows 10 Tiles

### ISSUE THREAD

**Issue by JinnerAtumia** [Open-Shell/Open-Shell-Menu#185]
I love how Classic Shell works, and I just want a fully customizable live tiles from Windows 10

**Comment by ibuprophen1** [comment]
It's great to see your positive feedback! 

I just wanted to point out (in case you didn't realize) this is the continuing development that's now called "Open Shell". 

Your kind words means allot to the team! :-) 


~Ibuprophen
