### ISSUE TITLE
Desktop Context Menu makes Explorer hang and crash

### ISSUE THREAD

**Issue by Dark-Mortal** [Open-Shell/Open-Shell-Menu#1855]
### Describe the bug

Right-click on Desktop empty space makes explorer hang. Icons on Desktop do not respond (left or right click does not matter, even on mouse-over effect not shown). Sometimes even task bar icons do not respond, Start Menu, running process icons etc.
I am using latest 4.4.191 Open Shell version. Windows 10 Home 22H2. Computer laptop: 2 graphic cards: Intel UHD Graphics and nVidia GeForce RTX.
Context menu of Desktop icons works without problems. Context menu of Task Bar works fine.
**If I uninstall Open-Shell Desktop Context menu works without problems!**

I think it is some kind conflict with nVidia:

> [22:59:35] Exception: 000006BA
> [22:59:39] Exception: 8007000E
> [22:59:39] Exception: 8007000E
> [22:59:39] Exception: 8007000E
> [22:59:49] Exception: 8007000E
> [22:59:49] Exception: E06D7363.?AV?$clone_impl@VHresultException@UXDriver@Nvidia@@@exception_detail@boost@@
> [22:59:49] Exception: E06D7363.?AV?$clone_impl@VHresultException@UXDriver@Nvidia@@@exception_detail@boost@@
> [22:59:49] Exception: E06D7363.?AV?$clone_impl@VHresultException@UXDriver@Nvidia@@@exception_detail@boost@@
> [22:59:49] Exception: E06D7363.?AV?$clone_impl@VHresultException@UXDriver@Nvidia@@@exception_detail@boost@@
> [22:59:49] Exception: E06D7363.?AV?$clone_impl@VHresultException@UXDriver@Nvidia@@@exception_detail@boost@@
> [22:59:50] Exception: 8007000E
> [22:59:50] Exception: C000070A
> [22:59:50] Unhandled: C000041D

Dump: [Dropbox Link](https://www.dropbox.com/scl/fi/5716folrh0lybhfldf0ng/explorer.exe_240221_225950.dmp?rlkey=gfdwdp45aoyz4ugnfrpsf31ro&dl=0)

### Area of issue

Windows Explorer

### To reproduce

Right-click on Desktop empty space 

### Open-Shell version

4.4.191

### Windows version

Windows 10 Home 22H2

### Additional context

nVidia GeForce RTX

**Comment by Dark-Mortal** [comment]
Yes, but I tried to uninstall Open-Shell and everything starts to work fine, only Open-Shell. All other are still there.

**Comment by Dark-Mortal** [comment]
I updated nVidia driver and still have the same problem. Also I turned off applications, nothing help.
I found strange thing that if Explorer window is open (any folder) then Context Menu appears for several seconds but after that Explorer.exe restarts.
I can record dump with uninstalled Open-Shell when everything works... if it helps.

**Comment by ge0rdi** [comment]
You can try to disable `Customize taskbar` option and create following registry entry (and restart explorer):
```
[HKEY_CURRENT_USER\SOFTWARE\OpenShell\StartMenu\Settings]
"CompatibilityFixes"=dword:00000008
```

That should disable any `Open-Shell` hooking. 

> Yes, but I tried to uninstall Open-Shell and everything starts to work fine

Does also exiting `Open-Shell` help? (right-click on start and `Exit`)

**Comment by Dark-Mortal** [comment]
Status: INVALID

I am sorry, I found the source, it is not Open-Shell, true.
I was an application which defined `PdiShellExt Class`. I removed and no more crashes.
