### ISSUE TITLE
Optional integration with the Everything filesystem search utility

### ISSUE THREAD

**Issue by magic-spearmint** [Open-Shell/Open-Shell-Menu#1857]
### Is your feature request related to a problem? Please describe.

_This feature request is not related to any problems/issues with this software in particular._

For over a year now, I've been using [Everything](https://www.voidtools.com/support/everything/) with [EverythingToolbar](https://github.com/srwi/EverythingToolbar) in favour of Windows 10's built-in search and indexing related functionality (mostly because it's faster at indexing and search operations and less resource intensive, although the additional features are nice too).

### Describe the solution you'd like

The ability to perform Everything searches through both the Open Shell Menu and Classic Explorer search boxes and then view the results from within the Open Shell Menu/Explorer window would be incredibly convenient.

### Area of issue

Start menu, Windows Explorer

### Additional context

- Everything's SDK (and its documentation) can be found [here](https://www.voidtools.com/support/everything/sdk/).

**Comment by ge0rdi** [comment]
Duplicate of #836.

**Comment by magic-spearmint** [comment]
Dang, I searched for mentions of Everything in the tracker previously but missed that.
