### ISSUE TITLE
custom taskbar texture only showing on left and right sides (Windows 10)

### ISSUE THREAD

**Issue by nubnub4455** [Open-Shell/Open-Shell-Menu#1869]
### Describe the bug

![image_2024-03-16_141920619](https://github.com/Open-Shell/Open-Shell-Menu/assets/35082930/16d30425-560f-4ad9-830d-7a6529bed306)

taskbar texture is only showing on the sides of the taskbar. i know this is an old issue for windows 11 but i'm on windows 10 so i'm not sure why it's happening.

### Area of issue

Taskbar

### To reproduce

1. go to taskbar settings
2. set custom taskbar texture
3. see that it's not working

### Expected behavior

the custom taskbar texture to cover the whole taskbar

### Open-Shell version

4.4.191

### Windows version

Windows 10 22H2

### Additional context

i'm on enterprise so that may be part of the issue but i'm not sure

**Comment by Win761** [comment]
Did you make sure to restart Open-Shell Menu after applying the texture? Normally it should prompt you to do so after changing the taskbar texture.

**Comment by nubnub4455** [comment]
restarting fixed it, i feel kinda dumb now but thanks :)

**Comment by nubnub4455** [comment]
restarting fixed it, i feel kinda dumb now but thanks :)

**Comment by Win761** [comment]
Np ;)
