### ISSUE TITLE
Open-Shell start button overlays the Windows 11 23H2 one instead of removing it

### ISSUE THREAD

**Issue by ThunderboltCommunicationsCorp** [Open-Shell/Open-Shell-Menu#1882]
### Describe the bug

The start button created by Open-Shell simply overlays the Windows 11 23H2 one and does not look good at all. I have to use another program that replaces the taskbar entirely just to make it work properly. Please fix it soon.

### Area of issue

Taskbar

### To reproduce

1. Replace start button using Open-Shell control panel
2. There's the problem, it's not replaced it's overlayed

### Expected behavior

I expected the start button to be replaced instead of being overlayed resulting in a horrible experience

### Open-Shell version

Latest

### Windows version

Windows 11 23H2 with all updates

**Comment by ge0rdi** [comment]
This is already reported in #1631.
