### ISSUE TITLE
Submenus from Start Menu are different color

### ISSUE THREAD

**Issue by MidnightInAurora** [Open-Shell/Open-Shell-Menu#1899]
### Describe the bug

When clicking Start Menu and clicking a right-side menu, the resulting submenu is colored differently from the Start Menu.

### Area of issue

Start menu

### To reproduce

1. Click on Start Menu
2. Select right-side item with a submenu
3. Submenu is colored differently.  In my case, a much lighter blue.

### Expected behavior

Start menu and any submenus follow color picked as accent color in Windows Settings.
![menu](https://github.com/Open-Shell/Open-Shell-Menu/assets/55057433/1ee36065-ff07-4df7-ba80-e5671200a421)

### Open-Shell version

4.4.191

### Windows version

23H2, 24H2

**Comment by ge0rdi** [comment]
Submenu color is defined by _skin_.
If you want different color you can use different skin, or just try to _modify_ skin you are using.

**Comment by MidnightInAurora** [comment]
Yes!  Checked Opaque in Skin and the submenus follow the Windows accent color.  Perfect.

I knew there was a simple answer and I was just being stupid.

Thanks for the help.

Jim
