### ISSUE TITLE
when trying to uninstall, the entire desktop turns white and there is no taskbar.

### ISSUE THREAD

**Issue by milkdoesthebodygood** [Open-Shell/Open-Shell-Menu#1907]
### Describe the bug

sorry about this dumb question. i want to uninstall, but when i did from apps and features, it turned the entire desktop white, with like half of a window bar at the bottom, no taskbar no nothing. i pressed cancel before it could uninstall and be permanent(if it is) and then i reset my computer. if i didnt press cancel, would this be permanent? and how can i safely uninstall without that happening? can i only just disable it on startup? sorry if my english is bad or this doesnt make any sense. i am using windows 10 22h2. i also never use github ever, so sorry if i did somehting wrong in this, and im really scared of damaging my computer and i cant find this issue happening anywhere else this is my demonstration in ms paint LMFAO (edit: i know it says uninstall in that exact way in the help menu, thats how i figured out how, but it didnt work when i did that. just did this)
![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/118156649/08b8b5ba-0b8e-4eed-b800-cf50fff40e00)

### Area of issue

Installation/Other

### To reproduce

go in apps and features in control panel/settings, click uninstall openshell and yea

### Open-Shell version

4.4.191 (i think?)

### Windows version

windows 10 22h2

**Comment by woofledev** [comment]
solved, for anyone looking to fix this just try resetting the settings and then closing openshell
