### ISSUE TITLE
Text translation of the menu tabs

### ISSUE THREAD

**Issue by an0nimo** [Open-Shell/Open-Shell-Menu#191]
I searched this issue but cannot find anything about.
The text on menu tabs are in english even using portuguese language.
Does exist a way to translate the text on menu tabs ?

**Comment by an0nimo** [comment]
I solved this moving the dll language file to the installation folder of the Open Shell, and restarting it.

**Comment by ibuprophen1** [comment]
I'm just curious... 

The typical installation of the software places the dll file in one location when it needs to be elsewhere? 

Or is this specific only to your situation? 


~Ibuprophen

**Comment by an0nimo** [comment]
In the windows 10 1809 hasn't **%ALLUSERSPROFILE%\ClassicShell\Language**s folder to install the dll language file. It is installed in the **C:\ProgramData\ClassicShell\Languages** folder and not works to change the menu language. So, I needed copy and paste the dll language file to the instalation folder to have the translation working right.
