### ISSUE TITLE
Is it not possible to "Customize Taskbar" on 24H2 beta?

### ISSUE THREAD

**Issue by Brad-git-man** [Open-Shell/Open-Shell-Menu#1913]
### Describe the bug

On 24H2 beta the "Customize Taskbar" section does nothing when enabled and configured. I heard that MS has been removing the classic code from the taskbar, which is targeted for taskbar customizations. Will be possible to "Customize the Taskbar" in later versions of Open Shell on 24H2 beta?

### Area of issue

Taskbar

### To reproduce

Install Open Shell on 24H2 beta then try to customize the taskbar.

### Expected behavior

You should be able to still customize the taskbar on 11 24H2 beta, but it seems that MS is bent on making that more difficult all the time.

### Open-Shell version

4.4.191

### Windows version

11 24H2 beta

**Comment by ge0rdi** [comment]
Thank you, this is known issue.
Taskbar customizations don't work since Win11 22H2.
See more info in #1342.
