### ISSUE TITLE
Folder Icon Missing

### ISSUE THREAD

**Issue by CBSKI52** [Open-Shell/Open-Shell-Menu#1920]
### Describe the bug

In the Start menu the icon for the folders are missing. Icons for programs are present. 

<img width="159" alt="OpenShell Folder Icon Missing" src="https://github.com/Open-Shell/Open-Shell-Menu/assets/169304918/fe785a66-16ad-45bd-99ab-d1fb9a62348b">

### Area of issue

Start menu

### To reproduce

Click on Start button
Select All Programs
Scroll to Folders

### Expected behavior

The Folder icons in Start menu to be visible

### Open-Shell version

4.4.191

### Windows version

Windows 11 Pro 23H2

### Additional context

Was working

**Comment by ge0rdi** [comment]
Try to clear caches:
`Open-Shell Menu Settings` -> `Backup` -> `Clear cached information`

**Comment by CBSKI52** [comment]
Unable to find Backup or anything to do with Cache in Open-Shell Menu Settings

**Comment by ge0rdi** [comment]
Button at the bottom of the settings dialog:
![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/2453094/3b6958d4-9754-47c9-b583-51942544623a)

**Comment by CBSKI52** [comment]
Thank you - it worked - my bad for not expanding my window to see the backup
