### ISSUE TITLE
Open shell won't work with touch screens

### ISSUE THREAD

**Issue by Acoles94** [Open-Shell/Open-Shell-Menu#1922]
### Describe the bug

We have multiple users on site reporting that open shell isn't working when using their touch screens since updating to windows 11. These are mainly Phillips smart boards that are connected to the PC via HDMI. Open shell works fine when using a mouse to click on the windows button or pressing the windows button on the keyboard but as soon as you press the windows button on the task bar using the touch screen function of the Philips smart screens it reverts back to the Win11 start menu. It will then go back to using open shell if you use either the mouse or keyboard.

Any ideas would be much appreciated 

### Area of issue

Start menu

### To reproduce

click on windows start menu on touch screen 

displaying Win11 start menu rather than Open Shell 

### Open-Shell version

Open Shell 4.4.191

### Windows version

Win11 23H2

**Comment by ge0rdi** [comment]
Unfortunately, this is known issue on Win11 (as it uses different framework for taskbar).
See more info in #1229.
