### ISSUE TITLE
Languages to resx  to have a possible for realy good translateing 

### ISSUE THREAD

**Issue by blackcrack** [Open-Shell/Open-Shell-Menu#193]
take a look on this page : 

https://github.com/kkguo/apkshellext/wiki/Translation-and-Multi-language-support

for translate can use Crowdin.com and makes very simple and more funny to translate !

--***:quote***------------------------------------------------------------------------------
### 1. Translate
  * Goto http://translate.apkshellext.com
    - It will lead to translation project on [Crowdin.com](http://crowdin.com/project/apkshellext)
    - Pick your language or add your language
    - Follow the translation instruction
    - Please contact me for promotion to profreader, then you can prove on your own.

### 2. How the Multi-language implemented.

  Multi languages are supported, by applying .NET native globalization flow with a little trick.

  All localize strings are defined in Resource file, by default, an English (en-US) resource ([Resources.resx](https://github.com/kkguo/apkshellext/blob/ApkShellext2/ApkShellext2/Properties/Resources.resx)) is in use, alternative language strings are provided from additional resource file, such as [Resources.zh-CN.resx](https://github.com/kkguo/apkshellext/blob/ApkShellext2/ApkShellext2/Properties/Resources.zh-CN.resx) or [Resources.it-IT.resx](https://github.com/kkguo/apkshellext/blob/ApkShellext2/ApkShellext2/Properties/Resources.it-IT.resx), the language code (zh-CN/it-IT) is in the file name.
   
  Corresponding resource will be applied according to user's environment. So if you are using Chinese system, you will see Chinese menu by default.

  Each additional culture resource generates satellites dll file, laying under < build >/< lang-code >/ApkSHellext2.resources.dll besides ApkShellext2.dll, \~~Which is I cannot bear, I would like keep a lite and green release structure instead of bunch of files, so I put the satellites dll as a resource into the main dll and extract it out on-the-fly when needed. (see [code](https://github.com/kkguo/apkshellext/blob/ApkShellext2/ApkShellext2/Utility.cs#L93))~~ I'm using the satellites dll now, just lay the language dll folder as it. 

\~~But under this, the build process need to do twice if the resource file got updated. The first time is for generating the satellites dll, the second time will include it into main dll. In [Post-build event](https://github.com/kkguo/apkshellext/blob/ApkShellext2/ApkShellext2/ApkShellext2.csproj#L393), the generated satellites dll is moved to resources folder.~~

### 3. [Build with the new language](https://github.com/kkguo/apkshellext/wiki/How-to-build-and-debug#build-with-new-language)

https://crowdin.com/

**Comment by auanasgheps** [comment]
I would love this approach. This is the only _big_ project I translate without a centralised portal!

**Comment by blackcrack** [comment]
Thy Oli :+1:  :slightly_smiling_face: 

@ge0rdi , @coddec , @Ibuprophen

**Comment by Ibuprophen** [comment]
@blackcrack, I'll take a deeper look at this soon... 

Thank you very much for your assistance with this matter! :-) 


~Ibuprophen
