### ISSUE TITLE
Start menu color inconsistent Windows 11 (part is black, part is my color preference)

### ISSUE THREAD

**Issue by giftigdegen** [Open-Shell/Open-Shell-Menu#1945]
### Describe the bug

Nothing I change in settings restores the proper color to all of the start menu. See screenshot. 
(removed for PID)
### Area of issue

Start menu

### To reproduce

I don't know how to reproduce it; I've never had it. 

### Expected behavior

Would love the color to be consistent across the menu. 

### Open-Shell version

Latest, downloaded yesterday. 

### Windows version

Latest Win 11

### Additional context

I just bought this Surface Pro 7+ and downloaded the latest Windows 11 image direct from Microsoft.

**Comment by ge0rdi** [comment]
This is no bug.
It is rather _feature_ or new `Immersive` skin.

You can change this in `Skin` settings.
Change `Transparency style` to `Full glass` if you want accent color on whole menu.

**Comment by giftigdegen** [comment]
Beautiful. Thank you. Yeah, not a fan of the two-tone. On cars, or otherwise..
