### ISSUE TITLE
start button in the middle of screen

### ISSUE THREAD

**Issue by ap733** [Open-Shell/Open-Shell-Menu#1959]
### Describe the bug

the start button is in the middle of screen instead to stay all in the left.. how can i settle this matter in window 11
![srat button opne shell 2024-07-26_203659](https://github.com/user-attachments/assets/0fb9d4c1-5c57-43a6-be2b-476e8c046ce4)

### Area of issue

Start menu

### To reproduce

the start button is in the middle of screen instead to stay all in the left.

### Expected behavior

the start button is in the middle of screen instead to stay all in the left.

### Open-Shell version

4.4.191

### Windows version

windows 11 22631.3958

### Additional context

the start button is in the middle of screen instead to stay all in the left.

**Comment by ge0rdi** [comment]
`Windows Settings` -> `Personalization` -> `Taskbar` -> `Taskbar behaviors` -> `Taskbar alignment`
Here you can select `Left` (instead of default `Center`).

**Comment by ap733** [comment]
Yes thanks. Already solved  😊

 

 

 

Da: ge0rdi ***@***.***> 
Inviato: venerdì 26 luglio 2024 21:42
A: Open-Shell/Open-Shell-Menu ***@***.***>
Cc: ap733 ***@***.***>; Author ***@***.***>
Oggetto: Re: [Open-Shell/Open-Shell-Menu] start button in the middle of screen (Issue #1959)

 

Windows Settings -> Personalization -> Taskbar -> Taskbar behaviors -> Taskbar alignment
Here you can select Left (instead of default Center).
