### ISSUE TITLE
can't uninstall ClassicShell 4.3.0

### ISSUE THREAD

**Issue by mcswell** [Open-Shell/Open-Shell-Menu#196]
I have version 4.3.0 of ClassicShell installed.  When I try to install Open-Shell, the install program tells me it can't find classicshellsetup_4_3_0.msi.  I don't know where that file is; I have the executables etc., but not afaict the .msi file.  Version 4.3.0 is apparently one minor-minor version from the final 4.3.1, but that means I can't find its package on-line, only the 4.3.1 version.  And when I try to install ClassShell 4.3.1, it also tells me it can't find the 4.3.0 .msi either.  So I seem to be stuck with the penultimate ClassicShell.

The same thing happens when I try to tell Windows to uninstall ClassicShell using the "Apps and Features" dialog box: no can find msi.

Is there some other way to uninstall CS4.3.0?  I could try removing all its files from the Program Files dir, but I fear that would still leave s.t. around, at the very least the registry entries.

**Comment by blackcrack** [comment]
we are official at 4.4  
https://github.com/Open-Shell/Open-Shell-Menu/releases

best regards
Blacky

**Comment by mcswell** [comment]
Understood, but that's not the problem: it wasn't open-shell that I was having trouble with, it was Classic Shell.  

That said, I used a program from Microsoft
    https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed
to uninstall ClassicShell.  I was then able to install Open-Shell.

**Comment by blackcrack** [comment]
Hi @mcswell 
Look over to reactos.org, is a better WinNT but in alpha.. *g*
.. 
question, the huge bug ever ? : Microsoft
hihi
have a nice day :) :+1: 
best regards
Blacky

**Comment by eihns** [comment]
I have the feeling you dont understand the problem.

I have the same and i guess many ppl in the future.

Your open shell try to run the removing of classic shell, which fails, because of network unreachable (maybe it want to DL somethign?). This means

1.) classic shell is unremovable
2.) open shell is uninstallable

Can you include a own classic shell remove routine?

Im currently tryin the link mcswell gave.

**Comment by eihns** [comment]
It does complete the same "network unreachable"

I restartet now and the link he gave seems to work (but it takes a long long time)
