### ISSUE TITLE
Open-Shell Update doesn't work

### ISSUE THREAD

**Issue by Leo40Git** [Open-Shell/Open-Shell-Menu#197]
Clicking "Update Now" just shows a "Failed to check for new version".

Also, the link in the lower-right corner is to "classicshell.net", rather than the new URL.

**Comment by Leo40Git** [comment]
Well, I've updated to the latest nightly version (4.4.138). The update utility *still* doesn't work, and the new link to the GitHub repo is partially offscreen.
![image](https://user-images.githubusercontent.com/7997354/61901680-faa23d80-af28-11e9-94dc-4abf02f40450.png)

**Comment by blackcrack** [comment]
https://ci.appveyor.com/project/passionate-coder/open-shell-menu
 139 is the current nightly but is not published, because it is not set as stable .

best regards
Blacky

**Comment by Leo40Git** [comment]
Updated to 139, still doesn't work, still has link issue.
![image](https://user-images.githubusercontent.com/7997354/61930028-48e52a00-af85-11e9-9ba6-164da51715f3.png)

**Comment by NanhuGITHUB** [comment]
nightly mean daily so try again the next day

**Comment by Leo40Git** [comment]
...nightly is still 139.

**Comment by Leo40Git** [comment]
This might be related to this problem: https://github.com/Open-Shell/Open-Shell-Menu/blob/master/Src/Lib/Lib.rc#L313
Still using the "classicshell.net" domain, too.

**Comment by blackcrack** [comment]
i have edit it, it is still not usable at moment, it must first update the code for search new release
path and the new exefile in version "%version%=>", if this done, works this.. up to now, can i only update the string so far..

**Comment by klepp0906** [comment]
just hopping in so i can get some email action when this is fixed ;p

**Comment by ge0rdi** [comment]
Update doesn't work at the moment (this is known issue).
It was already removed from installation in latest nightly builds.

We may reintroduce it in the future (once someone will make it work).

**Comment by ge0rdi** [comment]
I'd like to let you know that latest nightly build (4.4.156) contain support for auto updates.
It is also possible to check for nightly updates.

**Comment by klepp0906** [comment]
rock on, you guys are killing it now :) thanks for the heads-up and work on the project!

**Comment by klepp0906** [comment]
seems to be working but not automatically checking.  Any ideas?  Does it require a task or something?

If I open Update.exe manually and click Check now, I"ll get prompted for an update - but had i not done that i'd have never been notified. 

unsure if this is intended but i'd assume not considering it would make "automatically check" moot.
