### ISSUE TITLE
Search box focus for "Classic Style"

### ISSUE THREAD

**Issue by metal450** [Open-Shell/Open-Shell-Menu#1993]
### Describe the bug

Using Windows 11 IoT LTSC 2024 (24H2). Open-shell 4.4.191.

* For both the "Classic with two columns" and "Windows 7 style", as soon as the Start Menu is opened the Search box is in focus - so I can press Windows key, then start typing. This is the expected behavior.
* For the "Classic style" only, when the start menu pops up, the search box is not in focus - so if you start typing, it will randomly select menu items based on their start letter. There doesn't seem to be a way open the start menu and quickly start searching.

### Area of issue

Start menu

### To reproduce

Described above

### Expected behavior

Described above

### Open-Shell version

4.4.9.1

### Windows version

11 IoT LTSC 2024 (24H2)

**Comment by metal450** [comment]
Sorry, I just found the option - closing :)

**Comment by john-clark** [comment]
I had to go searching too. This should be the default behavior to replicate windows.

<img width="291" height="448" alt="Image" src="https://github.com/user-attachments/assets/417f9b50-6fce-4d32-89f7-6b61e3be5c36" />

Adding this comment for people using Open Shell and being frustrated the windows key or ctrl-esc does not function properly. Changing this setting will return the start menu to working like normal.
