### ISSUE TITLE
Feature request: one action to toggle System *and* hidden files

### ISSUE THREAD

**Issue by jerry1970** [Open-Shell/Open-Shell-Menu#200]
I realise I am always using the options Show/Hide Hidden Files and Show/Hide System Files at the same time. How about adding one action that shows/hides both hidden and system files?

**Comment by mstick99** [comment]
Try Stefan's Tools -- http://tools.stefankueng.com/StExBar.html

**Comment by jerry1970** [comment]
Wow, thanks! Unbelievable what MS still have not added to make their programs a lot easier to use. Have been using Ubuntu for years, never needed Windows and was glad for it. Unfortunately I am forced to use Windows at the new job!
