### ISSUE TITLE
Taskbar opacity code

### ISSUE THREAD

**Issue by MarchWorks** [Open-Shell/Open-Shell-Menu#203]
I would like to allow in an app (javascript) that I built to change the opacity of the taskbar and so I need an exe file that accept a number between 0 and 100.

I would like to know which file in "Open-Shell-Menu" do that. It would be better of course if you  added it as a standalone library to "Open-Shell" org

**Comment by NanhuGITHUB** [comment]
JavaScript probably wont be able to do that

**Comment by MarchWorks** [comment]
@NanhuGITHUB I know I will execute the `file.exe` that will do that with javascript.

**Comment by blackcrack** [comment]
make a lnk or pif, who execute what you whant
and put it in the menu.. that's all.. or use this : 
http://www.blackysgate.de/files/folder-root/exe-creators/

there can you also add div. variabes who makes possible to 
make other trick's ..

you own folder of start menu is : 
%userprofile%\AppData\Roaming\Microsoft\Windows\Start Menu
%userprofile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs

or should be ..

best regards
Blacky

**Comment by blackcrack** [comment]
you're welcome :) :+1:
