### ISSUE TITLE
Open-shell Won't install on Win 11 Laptop (ARM64)

### ISSUE THREAD

**Issue by TerryMorse** [Open-Shell/Open-Shell-Menu#2031]
### Describe the bug

Not necessarily a bug. Possibly a Windows annoyance. I'm trying to install version 4.4.191 on a new Dell XPS running Windows 11, and the Program Compatibility Assistant keeps saying the program can't run on this device and won't let me install it. I'm new to Win 11 and can't find a way to override it, even if I run the installer as an administrator. Any suggestions how I can get it to install? Thank you.

### Area of issue

Installation/Other

### To reproduce

Downoad the installation file and attempt to run it.

### Open-Shell version

4.4.191

### Windows version

Windows 11 Home 10.0.26100

**Comment by ge0rdi** [comment]
Could it be that your laptop has ARM64 CPU?
`Open-Shell` is not compatible with ARM64.

**Comment by TerryMorse** [comment]
Thanks for responding.

 It is ARM64. What a bummer! I do so hate Windows 11.

Terry

**Comment by ge0rdi** [comment]
There is #553 regarding ARM64 support.
For now there is not much you can do.

**Comment by TerryMorse** [comment]
Thank you, geOrdi.
-----Original Message-----

**Comment by billearl** [comment]
You can use [StartAllBack](https://www.startallback.com/) is compatible with Win 11 (ARM64). Not as nice as Open-Shell, but far better than what Windows11 offers.

**Comment by ge0rdi** [comment]
ARM64 support was added in [4.4.196](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.196).
Please, use that one (or newer) on ARM64 devices.
