### ISSUE TITLE
Custom start button not auto-hiding with Windows taskbar in Windows 10.

### ISSUE THREAD

**Issue by DrR0Ck** [Open-Shell/Open-Shell-Menu#2039]
### Describe the bug

I just installed 4.4.192 and use a custom start button.  Prior versions of Open Shell, the start button properly auto-hides with the taskbar, however, it just kind of floats in place when the taskbar auto-hides on this version.  I tried uninstalling and reinstalling, as well as a reboot, but the issue remained consistent.  Apologies if there is a new setting somewhere in the app that I need to set to have this behave properly.  Let me know if anything is needed to help troubleshoot.

### Area of issue

Start menu, Taskbar

### To reproduce

Taskbar is set to auto-hide, custom start button in use.  Button does not auto-hide.

### Expected behavior

Button should move with the taskbar when it auto-hides.

### Open-Shell version

4.4.192

### Windows version

Windows 10 22H2 - up to date.

**Comment by ge0rdi** [comment]
Thank you for reporting. I can confirm the issue.
Will try to fix.

**Comment by DrR0Ck** [comment]
Checking now.

**Comment by DrR0Ck** [comment]
Yep.  Looks like you have that issue sorted out.  Thanks for addressing so quickly.

**Comment by ge0rdi** [comment]
Thanks. I will create new release with the fix.

**Comment by ge0rdi** [comment]
Fixed in `4.4.194`.
