### ISSUE TITLE
Custom textures messed up

### ISSUE THREAD

**Issue by jk-auger** [Open-Shell/Open-Shell-Menu#2050]
### Describe the bug

![image](https://github.com/user-attachments/assets/a93bbca3-1713-4d53-985b-ef6af528a547)
It's probably an error on my side, but when loading a custom texture, it only affects the stat button and the calendar clock, but not the background for the icons.
I'd imagine I just have a setting not turned on in the app, or on my pc.
start

### Area of issue

Taskbar

### To reproduce

run program without any changes
apply custom texture

### Open-Shell version

4.4.191

### Windows version

windows 10

**Comment by ge0rdi** [comment]
Could you have some other customization software installed?
Taskbar texturing used to work on Win10.

**Comment by jk-auger** [comment]
i just had to restart my pc and everything loaded correctly

**Comment by jk-auger** [comment]
> Could you have some other customization software installed? Taskbar texturing used to work on Win10.

i just had to restart my PC and everything loaded correctly, along with glass transparency. idk man lol
