### ISSUE TITLE
not able to create Open-Shell update link - Warning 1946

### ISSUE THREAD

**Issue by Kvarkas** [Open-Shell/Open-Shell-Menu#2053]
### Describe the bug

On update its shows such warnings:

![image](https://github.com/user-attachments/assets/f0018dbc-dd3f-4e15-aa95-bff496afd917)

![image](https://github.com/user-attachments/assets/e8edf42a-31e1-4d41-b156-e54450f81e00)

![image](https://github.com/user-attachments/assets/09752829-e9b5-40d7-8b28-aedb5b6ea6ab)

![image](https://github.com/user-attachments/assets/ffe0eb83-58f3-4013-afb0-617cc9f19fa9)

### Area of issue

Windows Explorer

### To reproduce

1. Install older version
2. Do update via menu (download, run)
3. Got warrnings
(functionality actualy not impacted)

### Expected behavior

should it be just silently continue? However guesing - its for some reasons dont got rights to create such links, run as administrator?

### Open-Shell version

OpenShellSetup_4_4_194

### Windows version

Windows 11 Pro Insider Preview - 27764.1000

### Additional context

![image](https://github.com/user-attachments/assets/c19395a7-e19b-40ff-9f25-86e5a2921d2a)

**Comment by ge0rdi** [comment]
This is the same issue as #1672.
Lets keep all discussion and findings at one place.
