### ISSUE TITLE
Start menu Shortcut

### ISSUE THREAD

**Issue by mikeadachi** [Open-Shell/Open-Shell-Menu#2057]
### Describe the bug

This was ok about two weeks ago. I have Classic Shell and Open shell both do this now. I can now only see Apps on Start Menu if it is direct link to App. I have Chrome as short cut on my desktop. When I click it I do not see Chrome on Start Menu. If I click Chrome direct it will show up on Start Menu. THIS DID NOT DO THIS BEFORE. So why now.

### Area of issue

Start menu

### To reproduce

Click on Shortcut it does not go to Start Menu.

### Expected behavior

For this to work like it has for years.

### Open-Shell version

4.4.191

### Windows version

Windows 10 22H2

### Additional context

Will I get an email if there is a fix.

**Comment by ge0rdi** [comment]
Please, don't create duplicate issues.
You have already reported the issue in #2056.
