### ISSUE TITLE
Latest "Modern" Style (Onion Skin) over Classic, paradox.

### ISSUE THREAD

**Issue by adonios77** [Open-Shell/Open-Shell-Menu#2064]
### Describe the bug

The new modern style images in the 'Start Menu Style' field did not help. (I think it's called 'Onion Skin'). The old ones were fine, and accurately depicted the changes that were about to happen (ex: now scroll bars and tree style menu don't show etc.). Even more, this latest 'modern' style appearance over the 'Classic-style-menu' program is a paradox.
I think that one of the reasons this program was created (and loved a lot) was its **usefulness against 'modern' UIs** whose 'simplification' was either not self-explanatory enough (or even hiding previous features, but that's another topic).
_I'm talking about the "Start Menu Style" changes on Open-Shell Menu v4.4.194_ 
![](https://raw.githubusercontent.com/Open-Shell/Open-Shell-Menu/c517e21465cc475ae125c28b1f71030756f6a8a9/Src/StartMenu/StartMenuDLL/style_7.png) ![](https://raw.githubusercontent.com/Open-Shell/Open-Shell-Menu/f60e2a18cbc6e3ad3db4da74d2e58d528b0d1e4c/Src/StartMenu/StartMenuDLL/style_7.png)

https://github.com/Open-Shell/Open-Shell-Menu/discussions/2063

### Area of issue

Start menu

### To reproduce

_I'm talking about the "Start Menu Style" changes on Open-Shell Menu v4.4.194_ 

### Expected behavior

The old ones were fine, and accurately depicted the changes that were about to happen (ex: now scroll bars and tree style menu don't show etc.).

### Open-Shell version

4.4.194

### Windows version

all windows versions

**Comment by ge0rdi** [comment]
Not sure what issue you are trying to report here.
You have already expressed your _opinion_ in discussions.
I guess that's enough.

**Comment by adonios77** [comment]
> Not sure what issue you are trying to report here. You have already expressed your _opinion_ in discussions. I guess that's enough.

I mean (clearly) that the specific change does not help the user to immediately understand the changes that are going to be made in the menu style options. Thank you.
