### ISSUE TITLE
Bad scaling when mixing 4k and 1080p monitors

### ISSUE THREAD

**Issue by evinnichenko** [Open-Shell/Open-Shell-Menu#2066]
### Describe the bug

Open-Shell scales badly when mixing 4k and 1080p monitors, with the main menu requiring a change of icon size and explorer's status bar having disproportionately large font.

### Area of issue

Start menu, Windows Explorer

### To reproduce

1. Have a 4k monitor (I set it to 200% scaling and set it as main, might be important) and a 1080p monitor.
2. Open Start menu on the 4k monitor, see that it is tiny.
3. Open Explorer on the 4k monitor - status bar looks fine.
4. Move it to the 1080p monitor - now font changes to be 2x or 3x larger than it needs to be.

### Expected behavior

Both Start menu and Explorer's status bar to retain same physical (that is, to a human eye) size between 4k and 1080p monitors

### Open-Shell version

4.4.194

### Windows version

Windows 10 22H2

**Comment by ge0rdi** [comment]
Regarding Start menu icons DPI issues we have #1309 already tracked.

As for Explorer DPI issues there are #1990 and #1610 already.
