### ISSUE TITLE
Internet connection interrupted with version 4.4.194

### ISSUE THREAD

**Issue by PiliJ** [Open-Shell/Open-Shell-Menu#2072]
### Describe the bug

Hi,
I installed the latest version on top of the old one (4.4.191) and since then I've had interruptions to my internet connection on the PC (not on the modem) ... when activating a license for example.
I think that installation or activation corrupts the DHCP protocol (not sure at all that it's the reason !)
Thanks !

### Area of issue

Installation/Other

### To reproduce

1. Installed some new programs and, after activation, there is a loss of Internet access (unrecoverable by the usual means)

### Expected behavior

No bug of course.

### Open-Shell version

4.4.194

### Windows version

Windows 11 23H2

**Comment by ge0rdi** [comment]
That would be rather improbable.
`Open-Shell` has nothing to do with internet connection.

I think your problems are caused by something else.
Maybe some issues with your provider?

**Comment by PiliJ** [comment]
I recover with Eazy Fix and have no problem with version 4.4.191

**Comment by ge0rdi** [comment]
> I recover with Eazy Fix 

What does that mean exactly?

> have no problem with version 4.4.191

So if you are in state where `194` is installed and you have problem with internet, does uninstalling `Open-Shell` help?

**Comment by PiliJ** [comment]
Eazy Fix is the same program as Rollback RX. You can recover an old situation with it (no need to uninstal version 4.4.194 ... I'm back where I started with version 4.4.191)!
At first I thought it was the new program I was installing a few days ago, but yesterday I tried to install a game and it was the same thing.
I made several returns with Eazy Fix and it was only when I used a snapshot prior to installing Open Shell new version that the installation of the game went smoothly.

**Comment by PiliJ** [comment]
Yes (if and as soon as I install a program or activate it... when exactly it happens, I don't know)!

**Comment by ge0rdi** [comment]
Oki, in such case I have no clue what could be wrong, nor what else to ask for.
Never heard about such issue with `Open-Shell`.
I'm sorry.

**Comment by PiliJ** [comment]
Not a real problem for me. I'll stay with version 4.4.191...
Thank you.

**Comment by PiliJ** [comment]
Hi geOrdi,
I tested something else. As I said I installed the latest version on top of the old one (as always).
This Time I uninstalled 491 and made a new installation of 494. I wasn't asked to close Explorer or reboot.
I tried then installing the programs again and everything went smoothly... no more interrupted internet connection.
Problem solved thus.

**Comment by ge0rdi** [comment]
Cool.
Thank you for letting us know.
