### ISSUE TITLE
sendto can't be added to

### ISSUE THREAD

**Issue by micstan** [Open-Shell/Open-Shell-Menu#2079]
### Describe the bug

used shell:sendto to open context menu sendto folder. Added a shortcut, but does not show in context menu sendto

### Area of issue

Windows Explorer

### To reproduce

run "shell:sendto", Add shortcut. Open context menu on a file, select "sendto", shortcut does not appear

### Expected behavior

Shortcut to be there and when clicked will operate program of shortcut on selected file.

### Open-Shell version

4.4.194

### Windows version

windows 11

### Additional context

This operates fine with OpenShell on windows 10, but not on windows 11.

**Comment by ge0rdi** [comment]
Why do you think this is related to `Open-Shell`?
I don't think `Open-Shell` has anything to do with _sendto_.

Does the issue go away when you uninstall `Open-Shell`?
