### ISSUE TITLE
Binary/Installer branding

### ISSUE THREAD

**Issue by XenHat** [Open-Shell/Open-Shell-Menu#21]
There is some branding left to do in the installer/binaries:

- [x]  Ivosoft installer "company"

- [x] "ClassicShellSetup" installer name

- [x] "ClassicShell" Solution and project names

- [ ] Links and references to classicshell.net should be changed to ????

- [ ] Translations need to be updated to reflect the new branding

- [ ] Add credit to IvoSoft / Ivo Beltchev where possible and relevant

- [ ] Change "Email <classic shell author> for details" to something else

- [ ] Update documentation in Localization/English (+ translations)

Thankfully we use git and it can handle such renames.

**Comment by coddec** [comment]
>  Links and references to classicshell.net should be changed to ????

I guess https://github.com/passionate-coder/Classic-Start or https://github.com/passionate-coder ???

**Comment by worldsdream** [comment]
Why don't you make a website for it: for example classicstart.net? (I hope you bought that domain). Then reference all classicshell.net to classicstart.net.

With a website, it looks much better for customers/users.

**Comment by worldsdream** [comment]
Doesn't look professional when you do it like that. I hope you can keep up the high standards of classicshell.net.

**Comment by XenHat** [comment]
> I guess https://github.com/passionate-coder/Classic-Start or https://github.com/passionate-coder ???
Yeah I used these links where appropriate for the moment

**Comment by XenHat** [comment]
Currently 🚫 blocked from completion by #36

**Comment by ibuprophen1** [comment]
I'm just curious as to the status of this specific issue? 


~Ibuprophen
