### ISSUE TITLE
All Programs/Administrative Tools

### ISSUE THREAD

**Issue by KCEOC** [Open-Shell/Open-Shell-Menu#210]
I would like to see All Programs not display the Administrative Tools for standard local user accounts. I have seen where hiding the start menu folders or changing permissions will accomplish this, but that also changes it for local Administrator users.

Please note that I'm not talking about the setting under Customize Start Menu.

**Comment by Ibuprophen** [comment]
I understand what you're stating but, I would like to know exactly what you're referring to specifically (please excuse my ignorance) as the "Administrative" reference can apply to a few items/topics and I prefer not to assume anything. 

Thank you! :-) 


~Ibuprophen

**Comment by KCEOC** [comment]
Sure, understood...

I'm trying to replicate an things they way they used to be before Microsoft turned their start menu into a marketing machine. Here's a screenshot of the area I'm referring too,

![image](https://user-images.githubusercontent.com/54673544/63948682-137da180-ca47-11e9-8289-75750cc10dab.png)

Windows XP and 7 did not display Administrative Tools for users outside the Administrators group.

Really appreciate your help!

**Comment by Ibuprophen** [comment]
Thanks for your response. I'm understanding what you're referring to now but, what are you ultimately/specifically asking? 

why it's there?, It doesn't work?, How to remove it?, Etc... 

Thanks! :-) 


~Ibuprophen

**Comment by CollinChaffin** [comment]
This is not controlled by Classic/OpenShell.  In the future - Google is your friend. :open_mouth:

Two ways to disable:

Methos 1 - GUI/Manual (per user):

![2H6BUOKKsc](https://user-images.githubusercontent.com/9301483/63982652-e651e300-ca88-11e9-93bc-e424d1f04ed2.gif)


Method 2 - Automatic (per user or load their hive or via GPO or via logon script):

```
reg ADD "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /V Start_AdminToolsRoot /T REG_DWORD /F /D 0
reg ADD "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /V StartMenuAdminTools /T REG_DWORD /F /D 0
```

**Comment by Ibuprophen** [comment]
Thank you very much @CollinChaffin! 

@KCEOC, if the previous post does work out for you, please close this issue as being resolved. 

Thank you very much! :-) 


~Ibuprophen

**Comment by Ibuprophen** [comment]
I'm just going to close this issue as a resolution was clarified by member contribution. 

If you have this issue after trying what @CollinChaffin had provided, please open a new issue with a detailed explanation regarding it. 

Thank you very much for your time and understanding with this! :-) 


~Ibuprophen
