### ISSUE TITLE
Upgrade from Classic Shell 4.3.1 needs attention, should start Open Shell after update

### ISSUE THREAD

**Issue by glowingwire** [Open-Shell/Open-Shell-Menu#214]
I am amazed that the update from classic shell 4.3.1 to openshell was pretty smooth... in that it worked and my computer hasn't caught fire yet.

We should add a notification about the detection of previous versions installed....   it appeared to uninstall classicshell...   Which is OK, but I expected it to ask me about saving and importing my settings.

There should also be a "start after install" checkbox in the installer... and it should be checked if classic shell is set to start at computer boot.

Windows 10 is unusable without this program, so We need it to work.  This is a mission critical app.

Thank you so much for  making it work, I hope there are ways to send you guys some money... I think I can still donate to the original author... and he may continue to work a bit if he is able...  This is the MOST important program on the entire computer.

**Comment by blackcrack** [comment]
You can't please anyone, Did you see aany Bug, so make it as Issue, this is not an issue !

Classic Shall iss no more supportet, is is go into OpenShell,
if you have a problem with it, deinstall it !

best regards
Blacky

@Ibuprophen

so, this issue should close .
Blacky

**Comment by Ibuprophen** [comment]
@glowingwire, this requires that your system be restarted since it's dependencies include the explorer.exe to be restarted and many/most individuals either can't do this OR don't know how to do this manually. 

Thank you very much for your question regarding this and I hope that I had explained this okay via text. 


~Ibuprophen
