### ISSUE TITLE
I was just about to ask something similar :)

### ISSUE THREAD

**Issue by thunderpants** [Open-Shell/Open-Shell-Menu#215]
I was just about to ask something similar :)
I saw this "Open Shell 4.4.135" :
https://www.techspot.com/downloads/7103-open-shell.html
Thought there was a new release.

It comes up in Openshell Google results near the top.
Though if you click through it does have both stable(4.4.131) and beta versions.

**Comment by Ibuprophen** [comment]
Please see my response on the https://github.com/Open-Shell/Open-Shell-Menu/issues/212#issuecomment-527223323. 


~Ibuprophen

**Comment by thunderpants** [comment]
Thanks ,i found the correct nightly site.
