### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by JOHNJACOBJlNGLEHEIMERSCHMIDT** [Open-Shell/Open-Shell-Menu#216]
Somebody on the old forums posted this translation. might want to add it to the next update?
http://www.classicshell.net/forum/viewtopic.php?f=20&t=7879&p=36243#p36243

**Comment by Ibuprophen** [comment]
I just downloaded the help file and I'll see what I can do to add it. 

Thank you for bringing this to our attention! :-) 


~Ibuprophen

**Comment by gbrausi** [comment]
### 1st question
I translated to italian the help file of old ClassicShell, published on the old forums:
http://www.classicshell.net/forum/viewtopic.php?f=20&t=7879&view=unread#p36242

Now I translated to italian the new **OpenShell** help file.

How and where should be posted?
There a NEW forum related to OpenShell?

### 2nd question:
The OpenShell configuration window is displayed in English, although Italian is set as the language.
ClassiShell displayed it correctly. Why not anymore now?

Thanks

**Comment by JOHNJACOBJlNGLEHEIMERSCHMIDT** [comment]
1 open shell doesnt have its own forum, just the github page I linked to on the classic shell forums. that is the best place to post your new version

2 I have no idea; I never worked with the lower level stuff on classic shell, mostly just did testing and moderation of forums

________________________________

**Comment by gbrausi** [comment]
Thanks JOHN, I apologize if it seems like I am addressing you directly, but in reality I am responding to the discussion so I expect an answer from an OpenShell member to give me some guidance.
If I have to open a new issue, tell me, I don't want to bother you.
