### ISSUE TITLE
Instalelr - Multi-language version

### ISSUE THREAD

**Issue by bovirus** [Open-Shell/Open-Shell-Menu#221]
@Ibuprophen 

Could be possible in a near feature to have a multi-language installer?

Or like for  Classic Shell several installer files one for each language?

 Thanks.

**Comment by Ibuprophen** [comment]
@bovirus, it's funny you should ask about this as I do recall that I had asked the same question about a zillion years ago (I do know that it was a while ago). 

The answer is simple... 

There's currently no plans, conversations, talks, etc... between any of the developers regarding this type of implementation. 

Though I can state that it's been a topic of interest for a few of us that doesn't really have any priority to go any further. 

The reason: With all the Localizations implemented within a few initialization files (aka ini files), this type of change would require "ALLOT" of work to include a huge rewrite for the software itself. 

We would have to break up, redirect, change the call out (an old reference I still use), etc... that would really put a wedge on the current issues that need to be/are being addressed. 

I would just state that this is a great idea but, currently this a combination of "bad timing" and "lack of time" as this type of undertaking would require most/all the developers here to commit to this on a long term basis (within a new Repository) till it was accomplished and even afterwards to iron out the bugs and such. 

I hope that I had explained this okay via text... :-P 


~Ibuprophen

**Comment by bovirus** [comment]
@Ibuprophen 

For me currently Italian installer is a feature that is missing in Open Shell and was available in Classic Shell.

I believe that for any sofwtare the localization should include after GUI also the installer, because the user have to know/understand what the software installer show to accept it.

I didn't uinderstand because you have do some many changes in program structure.
I just ask to localize the installer.

What kind of application are you using to create the installer?
