### ISSUE TITLE
Missing share overlay

### ISSUE THREAD

**Issue by MidnightInAurora** [Open-Shell/Open-Shell-Menu#225]
Classic Shell on 2016 LTSB (1607) gave us the share overlay on shared folders.  When upgrading to 2019 LTSC (1809) and Open-Shell 4.4.131, the share overlays were missing.

The option was checked in Open-Shell explorer settings, the icon (74) exists and all looks correct, but no overlays.

**Comment by Ibuprophen** [comment]
I'm limited in my being that familiar with the LTSB & LTSC but, I've never felt the want/need to do so. 

It seems that your missing something, specifically, within the LTSC build itself that allows Open Shell to appropriately work on your OS. 

I can only provide you with a location where you should be able to locate and/or obtain some support and guidance to, ultimately, get this to work out for you. 

The following forum is a great one that includes your Windows OS. 

https://forums.mydigitallife.net

The following are just a few thread posts there that includes some helpful hints and such that just may fall into this topic (so to speak). 

https://forums.mydigitallife.net/threads/discussion-windows-10-enterprise-n-ltsc-2019.76325/page-156#post-1503915

https://forums.mydigitallife.net/threads/dpi-less-than-100-scale.79226/#post-1509299

The following is also an interesting option that may have a solution for you as well. 

https://forums.mydigitallife.net/threads/msmg-toolkit.50572/

The following area of that forum does have allot of discussions regarding the Windows 10 LTSC/LTSB support and guidance. 

https://forums.mydigitallife.net/forums/windows-10.54/

I'm going to close this issue for now as I believe that it's specific to the OS itself and not Open Shell. 

I wish you the best of luck! :-) 


~Ibuprophen
