### ISSUE TITLE
Menu won't open as a remoteapp

### ISSUE THREAD

**Issue by thomassuckow** [Open-Shell/Open-Shell-Menu#226]
When running RDP with a remoteapp. Attempting to open Open Shell Menu just starts a process that appears to do nothing. Works fine over a normal remote desktop.

Possibly due to a lack of explorer in remoteapp?

**Comment by Ibuprophen** [comment]
Yes... The Open Shell Software's primary dependency is the `explorer.exe`... 

Sorry for the bad news. :-( 


~Ibuprophen
