### ISSUE TITLE
Menu: newly installed programs won't sort

### ISSUE THREAD

**Issue by Gittyperson** [Open-Shell/Open-Shell-Menu#228]
Not sure what happened (Windows Update?), but since recently any new program I install, will have their start menu folder put as last entry in Programs, instead of sorting it automatically as usual. The option "Sort the main menu only the first time" is of course disabled.

Using "Classic with two columns" stlye, "Metro" skin.

Open-Shell Menu 4.4.131, Windows 10 Pro 1903 (18362.356)

**Comment by Gittyperson** [comment]
Looks like the context-menu "Auto arrange" setting was unchecked. Not sure why. I'll see if it sticks.

**Comment by blackcrack** [comment]
Hi @Gittyperson, if all works well so far for you, could you clouse this issue :) by side of "Comment" => "Close and Commend" or something :)

**Comment by Ibuprophen** [comment]
I do apologize for your long wait and, from what you had figured out, it would have been something that I would have mentioned to you as well. 

All seems to be well with @Gittyperson! :-) 

Please open another issue if you have any further issues but, hopefully you'll be good to go for a while (at least). 


~Ibuprophen
