### ISSUE TITLE
Search Box does not find Windows settings

### ISSUE THREAD

**Issue by PeteM92** [Open-Shell/Open-Shell-Menu#229]
Searching for "Ransomware" e.g. in the search box does not find any Windows settings.
Thus the search box does not work like Windows search or Cortana search, where settings menu for Ransomware Protection ist found correctly.

**Comment by ge0rdi** [comment]
Duplicate of #57

**Comment by PeteM92** [comment]
Thank you ge0rdi,
this seems to be an old isssue, which is still not resolved.

**Comment by ge0rdi** [comment]
> this seems to be an old issue, which is still not resolved.

Unfortunately we have no solution yet :(
