### ISSUE TITLE
Update all URL's to Github and Github Homepage

### ISSUE THREAD

**Issue by blackcrack** [Open-Shell/Open-Shell-Menu#230]
Hi,

Update the whole URL's to the Github Adresses and actual Adresses
to know the peoples where it's the Bear on fire ! 

So, PLEASE ! Update the URL's / Addresses in the whole code !!

And maybe update The Homepage to a better Designed Page and not a Homepage 
like in a ProgramerHell one ..

https://github.com/Open-Shell/Open-Shell-Menu/issues/87
https://github.com/Open-Shell/Open-Shell-Menu/issues/122

**Comment by blackcrack** [comment]
@ge0rdi 
>I guess we will do release when there will be something substantial added/fixed.

then is maybe also possible to change the whole URL's in the Programm to Github, Issues and something to have a program with correkt refer / send off  to this place and the whole users know
where they are come to working with. 

https://github.com/Open-Shell/Open-Shell-Menu/issues/192#issuecomment-536209274

**Comment by ge0rdi** [comment]
Sure, we are accepting PRs.
So anyone can help with this.

**Comment by blackcrack** [comment]
@ge0rdi  

 - don't make jockes !! -
