### ISSUE TITLE
BSOD when installing Open-Shell

### ISSUE THREAD

**Issue by AnErrupTion** [Open-Shell/Open-Shell-Menu#231]
Hello everyone,
So I wanted to install Open-Shell but instead of the UAC window to pop up, my PC literally crashes with that :

Stop code : KMODE_EXCEPTION_NOT_HANDLED
File that failed : Ntfs.sys

I wanted to know how to fix this problem because I never had it.
Sincerely,
~ ErrupTion_

**Comment by blackcrack** [comment]
@AnErrupTion 

1. Ordering System, Which version, Windows 10 Release 12345 or WinXP ?
2. What did you do to have this behaver , Programs installing before, or behind ?
Or it is fresh installed ?, 
Which updates do you have installed before ?

common, tell it us .

best

**Comment by AnErrupTion** [comment]
I'm using Windows 10 1903 and this is a fresh install.

**Comment by ge0rdi** [comment]
It is very unlikely the issue is related to `Open-Shell`.

You should rather verify if you don't have some HW issue (disk, RAM).
Crash in `ntfs.sys` may indicate some disk related issue.

**Comment by AnErrupTion** [comment]
Just last comment, i sucessfully the latest build (not release) of Open-Shell, but the release always does crash my PC. I've absolutely no idea of why that happens.
