### ISSUE TITLE
Doesn't ask for admin privileges when installing

### ISSUE THREAD

**Issue by MemesDank456** [Open-Shell/Open-Shell-Menu#232]

**Comment by Ibuprophen** [comment]
Hmmm... I don't believe that this applies to all as I've seen this work for some (not all). 

There's also a few different Administrative scenarios and such regarding both the User and Software Admin Permissions as well. 

I believe that your feedback may have had positive intentions and we all thank you for your time and consideration. 

Thank you for using this Software and Enjoy! :-) 


~Ibuprophen
