### ISSUE TITLE
"Documents" empty

### ISSUE THREAD

**Issue by Anselm970** [Open-Shell/Open-Shell-Menu#239]
Hello, the menu item "Documents" remains empty here, although I have set "Recent documents" to "Display as a menu". What's wrong? Thanks in advance, Anselm970

**Comment by blackcrack** [comment]
maybe because "Recent Documents" meant, like, youngest Document in the "History" 
and maybe it was moved or deleted by your own.. and this could be ..

please check it and go directly in your User-Folder C:\user\Anselm970\Documents  
and check if the Document gone.. 
and if it is, please close this issue.. thank you 

best regards
Blacky

**Comment by Ibuprophen** [comment]
I think I understand the question/issue... 

Just to clarify, the Recent Documents means the most recent ones accessed. It goes by the date & time the documents were accessed and not by the age of the documents itself. 

To be honest, I don't use this menu feature myself but, I'll have to take a look at this a bit more. 


~Ibuprophen

**Comment by blackcrack** [comment]
@Ibuprophen 

Hi Ibu, i guess, his file is deleted and the link rotten around still in "Recent documents" \*g*

best
Blacky

gammel fleisch ist nicht geniesbar

**Comment by ge0rdi** [comment]
@Anselm970 
Make sure you have `Show recently opened items ...` enabled in Windows settings `Personalisation -> Start`.

**Comment by Anselm970** [comment]
> Make sure you have `Show recently opened items ...` enabled in Windows settings `Personalisation -> Start`.

That was exactly the cause. Thanks to all of you.
Greetings, Anselm970

**Comment by Ibuprophen** [comment]
@Anselm970, That's great news! :-) 

If all is well, can you please close this issue? 

If not, please let us know. 


~Ibuprophen

**Comment by Anselm970** [comment]
Thanks. I'm new here.
