### ISSUE TITLE
[Request] 4.4.142   re-add Menu Skin Smoked Glass

### ISSUE THREAD

**Issue by blackcrack** [Open-Shell/Open-Shell-Menu#241]
Hi,

where is The Skin Smoked Glass ?

please re-add smoked Glass again, why not more as 20-30 Skins, or downloading possibility for a Skin-pack for non integrated Skins or removed Skins for the Users where lofe Skins where have years used a spezial Skin and suddenly it's gone, for that there has to be a collected skins pack.

Or please, don't delete any Skin , different users use diffrent Skins, let it in or make a extra Collecting Skin pack.
A easy deleting any skin is not good, this simply skips the users (also the long term users and let disappoint they are)

best regards
Blacky

**Comment by ge0rdi** [comment]
No skin was removed AFAIK.

`Smoked Glass` is available only in `Classic style` and `Classic with two columns` style. So make sure you are using one of those.

**Comment by blackcrack** [comment]
youre right, i have use the Windows 7 Style and there can not use the Smoked Glass and it is also therewith not visibel , so have i think it is no more avail.. and i have not become with to use the "wrong " Startmenu Style. and Smoked Glass is in the themefolder, you're right :)
Thank you for your hint.

best regards
Blacky
