### ISSUE TITLE
Open Shell admin confirmation

### ISSUE THREAD

**Issue by Blisk** [Open-Shell/Open-Shell-Menu#242]
Is there a way to skip that admin confirmation after update, because some users doesn't have admin rights to do that??

**Comment by Blisk** [comment]
Anyone please?

**Comment by ge0rdi** [comment]
If you mean admin confirmation after OS _upgrade_, please have a look at [OS upgrade without user interaction](https://github.com/Open-Shell/Open-Shell-Menu/wiki/OS-upgrade-without-user-interaction) Wiki page.

**Comment by RaspberryPiFan** [comment]
@Blisk The update can only be done by an Admin.

**Comment by Blisk** [comment]
> 
> 
> If you mean admin confirmation after OS _upgrade_, please have a look at [OS upgrade without user interaction](https://github.com/Open-Shell/Open-Shell-Menu/wiki/OS-upgrade-without-user-interaction) Wiki page.

I tried this but it doesn't work

**Comment by ge0rdi** [comment]
@Blisk 
Could you describe what exactly did you do and what doesn't work?
Do you use `OpenShell` at least 4.4.138?

**Comment by Blisk** [comment]
No I use 4.4.131

and this start at computer start
%ProgramFiles%\Open-Shell\StartMenu.exe -upgrade -silent

**Comment by ge0rdi** [comment]
You need to use at least 4.4.138. It is mentioned on the Wiki page.
Older versions don't support this silent upgrade.

**Comment by Blisk** [comment]
> 
> 
> You need to use at least 4.4.138. It is mentioned on the Wiki page.
> Older versions don't support this silent upgrade.

thank you

**Comment by Blisk** [comment]
I check release ad there is still 4.4.131 how can I upgrade to 4.4.138?
https://github.com/Open-Shell/Open-Shell-Menu/releases

**Comment by Blisk** [comment]
I check release ad there is still 4.4.131 how can I upgrade to 4.4.138?
https://github.com/Open-Shell/Open-Shell-Menu/releases

**Comment by ge0rdi** [comment]
You can use latest [nightly build](https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts).

I will eventually add it to releases.

**Comment by ge0rdi** [comment]
I have created [4.4.142](https://github.com/Open-Shell/Open-Shell-Menu/releases) release.

**Comment by Blisk** [comment]
thank you
