### ISSUE TITLE
Massive memory leak Windows 7

### ISSUE THREAD

**Issue by RoyBatty64** [Open-Shell/Open-Shell-Menu#243]
**Describe the bug**

On Windows 7 there is a massive memory leak that quickly uses up all system ram and the paging file, 100% CPU use and creates an ever growing cache file in the user profile folder. I tested the newest version on a fresh Windows 7 install with nothing but windows updates and drivers installed. Nothing in Event Logs pertaining to the issue.

I had to boot into safe mode and uninstall it to resolve this issue.

**Version:**
 - 4.4.131
 - Windows 7 Ultimate
 - HW 250GB EVO 860 SSD, C2D E8500, ASUS P5E, 8GB RAM, USB 3.0 HUB, ASUS WiFi Card, MSI 1050Ti, ASUS Optical

**Comment by blackcrack** [comment]
uninstall Openshell 4.4.131 test it again and play a bit around, it can be also an other Programm or a AV-Software,
if you have play around 1/2 Day's
then test this ..
https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts

**Comment by RoyBatty64** [comment]
It was a fresh install, no AV, and I disabled MSE immediately.

I uninstalled and installed the last version of Classic Shell and it's working as expected.

It's possible that an update broke something, as I did install it before updating completely.
