### ISSUE TITLE
Virustotal.com reports Malware ? 

### ISSUE THREAD

**Issue by mainufer** [Open-Shell/Open-Shell-Menu#244]
I followed a link "Latest Nightly Build" within this page https://open-shell.github.io/Open-Shell-Menu/  which led me to https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts
The build there 4.4.142 has these results in https://www.virustotal.com/gui/file/38f23b6527c41c0f7c7760189ae7a7da0747f7c85a04d464bbcb17e1d87ee914/detection

Wrong detection, or is there something wrong ? 
![image](https://user-images.githubusercontent.com/45529131/67633924-67c1c800-f8b6-11e9-9c5d-86562a5e8969.png)

**Comment by ge0rdi** [comment]
This is a _false positive_.

There is nothing wrong in `Open-Shell`. You can check its source code and eventually compile by yourself.

**Comment by trillwin** [comment]
ok @ge0rdi 

i heard that 2 or less vendors makes the file look probably safe but you still have to test it on VirtualBox or Sandboxie. or a separate computer, but 3 or more vendors mean that the file is unobtanium. sorry guys but sadly im absolutely not downloading this. i was trying to make my pc look like Windows XP.
