### ISSUE TITLE
Cannot move the drag handle on the explorer bar - Win 10 1903

### ISSUE THREAD

**Issue by HizzyHaz** [Open-Shell/Open-Shell-Menu#246]
![2019-10-31_052624](https://user-images.githubusercontent.com/7669787/67917007-473c8b00-fba0-11e9-85e2-f42881823c38.png)

That thing simply refuses to move.  It's stuck on the left side permanently.  The bar is not locked, and the handle is there, and it changes shape when I left click on it, but it just won't move.  Is there something else that may be locking it in place?
I've tried installing different versions - latest official, latest nightly, the last classic one.  
I do remember being able to move that for a long time in Classic Shel.  Could a Windows update be messing with this?

Thanks in advance!

**Comment by getreadyforme** [comment]
I wonder, has anyone else experienced this?  This would tell me if I should look for the issue on my end.

**Comment by blackcrack** [comment]
1903 its to old, today is 20h1 actual and, no, no other have this problem, i use 10 in VBox + OShell
no troubles .. 
best
Blacky

**Comment by glimmerwell** [comment]
Wait, I just found this thread! I have had this **_EXACT_** problem for years! Great explanation, OP, BTW! You can drag that bar around at first on a new install, but if you get it too close to the left (or if you release the drag handle while moving it carelessly) it will fly over hard left, then never move again.

I have had it on at least three different versions of Windows, from W7 to W10.

Did anyone solve it? Thanks!

**Comment by glimmerwell** [comment]
@awalkonthebeach 
Yes, you are not alone! And thanks for that great video!

Now I know that I can (probably) install a 2nd toolbar to get the drag hander unstuck. 

I see you are using 7+ Taskbar Tweaker. Me, too. Besides Vivaldi and Firefox, its the one thing I can see that we both have in common. Not sure if that means anything.

And, to clarify my first comment, Lock/Unlock the Toolbars has no effect on getting the problem unstuck, but I think locking the toolbar _does_ prevent it from getting stuck in the first place.

**Comment by awalkonthebeach** [comment]
yes, as long as I leave the Open Shell toolbar somewhere far from the left edge, I can keep moving it, but I usually lock it and forget about it.  But as soon as I drag it all the way to the left edge where the "empty" handle is, then it tends to become stuck and I can't move it back, and also the "empty" handle is just gone.  Occasionally though, it works as it should and the "empty" bar gets sent to the right edge, and I can keep swapping them.  This UI works similar to the shortcut toolbars that you can create on the taskbar, like Quick Launch and other custom ones (in my video I have 3 of them on the bottom left).  One of them is always sitting on the left edge, and if I drag another one over it, they swap sides.  And I can do that swap with Open Shell and Foxit toolbars in explorer, but for some reason when I do it with the "empty" handle, it tends to disappear and there is nothing left to swap so Open Shell is stuck.  
I'm glad this was of some use to you.

**Comment by awalkonthebeach** [comment]
btw if you are looking for an app that creates an extra toolbar to help get your Open SHell unstuck, you can try this little free app.  
[https://www.thewindowsclub.com/qttabbar-windows-explorer](https://www.thewindowsclub.com/qttabbar-windows-explorer)
I haven't used it recently though...
