### ISSUE TITLE
upgrade from classic shell to open shell fails

### ISSUE THREAD

**Issue by tfk2** [Open-Shell/Open-Shell-Menu#253]
i get the follwoing error:

the feature you are trying to use is on a netowrk resource or unavailable
click ok to try again or enter an alternate path to a folder containind the installation package classic.shell.Setup64_4_3_0.msi
prompts for folder c:\program data

this happened on the same day when i successfully updated windows 10 to the 1903 release from a while back.

I can't uninstalll (I 'm a bit technical)
i've run ccleaner
i've tried putting the msi into the folder specified (but i mave have put the worng msi version and it didn't work in any case)
i think ive delted the folders in %appdata% and %programfiles%
caches are clean
drive is clean/degfdfragged/rebooted/checked for updates

classic shell was working fine for YEARS..never a prob until now

HELP: I cant use windows without classic shell (open shell) ;-)

**Comment by michaelleepow90** [comment]
I tried downloading Open Shell 44.1.4.2, but the download get stuck, I tried pausing it, & it appeared as if it was finished. I tried opening it & got an error saying that the program file is corrupted..

**Comment by coddec** [comment]
Could you try to copy the setup up binary to real local drive rather than launching the setup from any kind of USB or RAM disk or network shared folder etc. then launch the setup from there (local drive)?
