### ISSUE TITLE
Bitdefender sees a virus in 4.4.142

### ISSUE THREAD

**Issue by Attobuoy** [Open-Shell/Open-Shell-Menu#254]
"The file C:\Users\(username)\Downloads\OpenShellSetup_4_4_142.exe is infected with Gen:Suspicious.Cloud.2.@x0@aWI6KQji and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean"

So, staying with 4.4.131 for now

Windows 10 update 1903, Bitdefender.

**Comment by michaelleepow90** [comment]
Wow, thanks for letting me know, no wander the download took so long & then it stopped. Will do the same here too.

**Comment by ge0rdi** [comment]
There is no malware in `Open-Shell`.
You can check the source code and compile on your own if you want.

Please report this false positive to [Bitdefender](https://www.bitdefender.com/consumer/support/answer/29358/).

**Comment by michaelleepow90** [comment]
Been wondering why the download is extremely slow though, I have a 10 Megabit/sec connection but the download is showing only 11-12 kilobits/sec..
