### ISSUE TITLE
Latest v Windows 1909  FYI

### ISSUE THREAD

**Issue by whutch47** [Open-Shell/Open-Shell-Menu#258]
This is not really a bug in OpenShell but I just installed the latest Nov 2019 version of Windows 10
v1909 and it broke OpenShell.  The two menu selection options that have two columns no longer shows two columns in the menu.  The only option that works like it used to is the Classic one column option.

Just an FYI

**Comment by ge0rdi** [comment]
I'm using 1909 for several months already and haven't noticed any issue.
Could you attach a screenshot how does it look like?
Could you try to save your config and then reset all settings to default, if there will be any change?

**Comment by whutch47** [comment]
Thanks for the reply. I did a reset of all settings to default and cleared the cache and did a save to XML file.

I am including a screenshot. The screen shot shows what my menu looks like for both the Windows 7
and Classic with two columns choices.

     On Saturday, November 23, 2019, 12:23:50 PM CST, ge0rdi <notifications@github.com> wrote:  
 
 
I'm using 1909 for several months already and haven't noticed any issue.
Could you attach a screenshot how does it look like?
Could you try to save your config and then reset all settings to default, if there will be any change?

**Comment by ge0rdi** [comment]
@whutch47 
I guess you forgot to attach the screenshot.

**Comment by mailinglists35** [comment]
i just installed two instances of 1909 upgraded from 1903 and both worked fine

**Comment by whutch47** [comment]
I really did attach the screenshot file.

I am attaching it three times to this e-mail. JPG's 151kB each.

Thanks for taking a look at this. I really like OpenShell with the Windows 7 menu option.'

     On Saturday, November 23, 2019, 3:24:59 PM CST, ge0rdi <notifications@github.com> wrote:  
 
 
@whutch47
I guess you forgot to attach the screenshot.

**Comment by whutch47** [comment]
Thanks, hopefully I'm doing something wrong that someone can show me how to correct
on my end. I have attached a screen shot of what is going on with my configuration.

The attached screenshot is what happens when I chose either Classic two columns for Windows 7 two
columns.



     On Saturday, November 23, 2019, 3:30:54 PM CST, mailinglists35 <notifications@github.com> wrote:  
 
 
i just installed two instances of 1909 upgraded from 1903 and both worked fine

**Comment by whutch47** [comment]
Screenshot via gmail.

**Comment by whutch47** [comment]
It looks like my screenshot can't make it through either via yahoo or gmail.

Any other way or address can send it to? Or, can I upload the image somewhere?

The image is a JPG file and shows up in my sent emails from both my yahoo
and gmail accounts.
 
     On Saturday, November 23, 2019, 3:24:59 PM CST, ge0rdi <notifications@github.com> wrote:  
 
 
@whutch47
I guess you forgot to attach the screenshot.

**Comment by blackcrack** [comment]
you can put your screenshot easy in your posting, this load your picture up to github and link automatical in youre posting.. so take the image easy and put it into youre posting.
best

**Comment by whutch47** [comment]
[](url)
![image](https://user-images.githubusercontent.com/58117810/69487623-ead92e00-0e22-11ea-884e-3f49bb32473a.png)

**Comment by whutch47** [comment]
Thanks! Got it! I have the image uploaded now.
     On Saturday, November 23, 2019, 6:41:13 PM CST, blackcrack <notifications@github.com> wrote:  
 
 
you can put your screenshot easy in your posting, this load your picture up to github and link automatical in youre posting.. so take the image easy and put it into youre posting.
best

**Comment by whutch47** [comment]
To reopen issue.

**Comment by ge0rdi** [comment]
@whutch47 
So what's wrong with your menu?
According to screenshot it looks good and working.

**Comment by whutch47** [comment]
It only has the one column. It used to have two columns like what is shown in the menu
setup options for both Windows 7 and the Classic two columns.
     On Sunday, November 24, 2019, 2:41:05 AM CST, ge0rdi <notifications@github.com> wrote:  
 
 
@whutch47
So what's wrong with your menu?
According to screenshot it looks good and working.

**Comment by ge0rdi** [comment]
@whutch47 
Not sure if I understand. But the start menu on your [screenshot](https://user-images.githubusercontent.com/58117810/69487623-ead92e00-0e22-11ea-884e-3f49bb32473a.png) has two columns. One (on the left) contains pinned/recent shortcuts and the second (on the right) contains standard shortcuts/commands.

It looks as it should.

**Comment by blackcrack** [comment]
@whutch47 lil tip,
try ![libre office](https://www.libreoffice.org/) (libreoffice.org), it's more better and more community..

**Comment by whutch47** [comment]
Thanks. And thanks again on helping me post my JPG example file.
     On Sunday, November 24, 2019, 10:22:15 AM CST, blackcrack <notifications@github.com> wrote:  
 
 
@whutch47 lil tip,
try  (libreoffice.org), it's more better and more community..

**Comment by whutch47** [comment]
Thanks for looking at it for me. It's really great having familiar style menus since the "Tile" stuff
is a bit much for me to handle.

I was pleasantly surprised at how good a job Microsoft did with Win 10, and making it work
on older hardware. I really loved Windows 7 and hated to have to give it up.

Thanks again.

     On Sunday, November 24, 2019, 10:04:51 AM CST, ge0rdi <notifications@github.com> wrote:  
 
 
@whutch47
Not sure if I understand. But the start menu on your screenshot has two columns. One (on the left) contains pinned/recent shortcuts and the second (on the right) contains standard shortcuts/commands.

It looks as it should.
