### ISSUE TITLE
Thread Warning with Cisco Amp

### ISSUE THREAD

**Issue by hmakmur** [Open-Shell/Open-Shell-Menu#261]
I am a bit alarm today to findout that Cisco AMP is preventing me from installing OpenShell.  Can someone shed some light on this? I hope this is false alarm. 
-Hanz
See pictures.
![Screen Shot 2019-11-26 at 3 20 42 PM](https://user-images.githubusercontent.com/32586402/69669983-f1ed7f80-1060-11ea-801e-03d4699b2492.jpg)
![Screen Shot 2019-11-26 at 3 20 33 PM](https://user-images.githubusercontent.com/32586402/69669996-f5810680-1060-11ea-93eb-be819a122fa8.jpg)

**Comment by Ibuprophen** [comment]
This, like a handful of those types of protection software, is a false positive. 

If you want to use the software, you will have to manually locate & remove it from the quarantine listing and then locate where you can add the software to its trusted/exception list. 

I'm not sure about the specific verbiage reflected on that software, but you should be able to understand what I mean. 

Also, I know that some of those types of software has a way to submit false positives to their system. It's kinda like feedback that gets reviewed that typically doesn't have/require a response from them. 

I hope that I had explained this okay via text... :-) 

~Brian Kerr
