### ISSUE TITLE
VirusTotal is flagging your OpenShellSetup_4_4_142.exe as having Trojans and Malware (2019-12-05)

### ISSUE THREAD

**Issue by Data-Logistix** [Open-Shell/Open-Shell-Menu#267]
VirusTotal is flagging your OpenShellSetup_4_4_142.exe as having Trojans and Malware (2019-12-05)

See the attached image 
![Open Shell Setup - Virus Total Results (Trojan - Malware) 2019-12-05-1608UTC](https://user-images.githubusercontent.com/12822530/70261489-6ef6b400-1747-11ea-9b45-9d4f311a29fb.JPG)

**Comment by ge0rdi** [comment]
It is false-positive.

Duplicate #266 .

**Comment by Ibuprophen** [comment]
Users... Please see the following comment:

https://github.com/Open-Shell/Open-Shell-Menu/issues/269#issuecomment-562964765


~Ibuprophen
