### ISSUE TITLE
settings webpage still shows www.classicshell.net

### ISSUE THREAD

**Issue by Aokromes** [Open-Shell/Open-Shell-Menu#272]
**Describe the bug**
settings webpage still shows www.classicshell.net

**To Reproduce**
1. right click on start button -> settings
2. you see www.classicshell.net

**Expected behavior**
It must link to https://github.com/Open-Shell/Open-Shell-Menu/

**Screenshots**
https://i.imgur.com/IgOzoLr.png

**Version:**
 - Open-Shell: 4.4.142
 - OS: [e.g. Windows 10 1903 / 2003]

**Additional context**

**Comment by Aokromes** [comment]
missed https://github.com/Open-Shell/Open-Shell-Menu/commit/30ffce6939f18b1c31874d2423ae4b731a510a51

**Comment by blackcrack** [comment]
@Aokromes , psst : https://ci.appveyor.com/project/passionate-coder/open-shell-menu

klick Artifacts and try it again with the .x.143-gmm...
