### ISSUE TITLE
Missing Toolbar

### ISSUE THREAD

**Issue by tzr916** [Open-Shell/Open-Shell-Menu#275]
Win10 1909, Open Shell v4.4.142 just installed over last version of Classic Shell... Missing the Classic Explorer toolbar buttons, like cut, copy, paste, etc. 
Already been to IE addons, ensured Open Shell options are enabled.
Already been to IE options/advanced/browser/enable 3rd party is checked.

Curious that the status bar is working, but the toolbar does not! Any help is appreciated, the most used feature of Classic Shell Explorer for me were the toolbar buttons. Love to get them back!

**Comment by ge0rdi** [comment]
Make sure you have in `View -> Options -> Classic Explorer Bar` checked.
![image](https://user-images.githubusercontent.com/2453094/71197429-de18f000-2291-11ea-9401-013d82e7ff9b.png)

**Comment by tzr916** [comment]
That was it! Thank you
