### ISSUE TITLE
Migration from Classic Shell to Open Shell

### ISSUE THREAD

**Issue by RegisStGelais** [Open-Shell/Open-Shell-Menu#276]
This is not a bug report.

I just want to know if I should uninstall the original classic shell before installing Open Shell ??

**Comment by ge0rdi** [comment]
You can install `Open-Shell` over `Classic-Shell`.
It will automatically import all the previous settings.

**Comment by RegisStGelais** [comment]
Tks, it's what I hoped.

Another silly question: Is there an auto-update (or an update menu) in Open Shell or we need to download the binary manually every time we want to update ?

**Comment by ge0rdi** [comment]
Automatic update doesn't work currently :(

You can watch this repo for new releases (using `Watch` button at the top) and then download and install manually when there is new release.

**Comment by RegisStGelais** [comment]
I'm already watching this repo.
You may close this issue.
Tks.
