### ISSUE TITLE
Surface Book 1 won't show correct Open Shell screen

### ISSUE THREAD

**Issue by Axellarator** [Open-Shell/Open-Shell-Menu#279]
Need some help

Did an update towards Win10 1909. Open Shell was pre-installed, but now with every Start I get the Windows Apps on screen and Open Shell is gone. A repair run helps temporarely. If the Aero button pops up, then the Win Apps will show up plus the expected Win 7 behavior. Every program starts normally but if the mouse lost focus I am back with the Win10 standards.
The Open Shell set-up is default, exept Aero button und Win7 style. Deleted and Reinstalled Open Shell, but no change in appearance. 

Any Idea?

**Comment by blackcrack** [comment]
screenshot, any idea ?

**Comment by Axellarator** [comment]
Back on track
I got a driver update from MS. Intel Serial IO I2C Host Controller was updated, the Intel Xeon E3  Gaussian Mixture Model 1911, 2 VC++ runtimes and the MS XNA Framework. And after a reboot everything looks and acts normal.
