### ISSUE TITLE
How can I donate to this project?

### ISSUE THREAD

**Issue by nanthracite** [Open-Shell/Open-Shell-Menu#281]

**Comment by nanthracite** [comment]
I should have said donate money, not just donate.  :-)

**Comment by coddec** [comment]
Hi @nanthracite 
Thank you very much for considering! :)
Unfortunately, we haven't got time to think about it yet and not sure how is it going to work.
I think we will announce if we have time to think and discuss about it internally, in the future when we have time to.

Heaps thanks for your consideration!!! 👍 👍  :)

**Comment by nanthracite** [comment]
I really appreciate it that you have picked this project up and I hope you 
continue and figure out how we can donate to help you out!

Nancy Anthracite

On Tuesday, January 14, 2020 3:08:49 PM EST coddec wrote:

Hi @nanthracite
Thank you very much for considering! :)
Unfortunately, we haven't got time to think about it yet and not sure how is 
it going to work.
I think we will announce if we have time to think and discuss about it 
internally, in the future when we have time to.
Heaps thanks for your consideration!!! 👍 👍 :)

**Comment by coddec** [comment]
Thank you very much!!! We all appreciate your consideration!!!
👍 👍 👍 😊😊😊

**Comment by jrfnl** [comment]
Came here to ask exactly the same. Every year I try to put some money towards supporting the developers of the open source projects I use and I couldn't find a funding option for this project.

I truly believe we need to normalize funding of open source software, but we can only do so if projects accept funding.
