### ISSUE TITLE
ImmersiveControlPanel removal? w10

### ISSUE THREAD

**Issue by trolloos** [Open-Shell/Open-Shell-Menu#282]
Is there an option to use this program to just replace all the default w10 immersive control panel items with the old ones? I have not found this function yet? I have tried to remove the immersivecontrolpanel package myself by using powershell and typing: Get-AppxPackage windows.immersivecontrolpanel | Remove-AppxPackage. Ofcourse this does not work because it has the IsInbox:1 property in the database which I tried to remove this way:
http://woshub.com/remove-appxpackage-0x80073cfa-removal-failed/.
That did not work for some reason because it gives the error unknown function workID.

**Comment by nurky** [comment]
Have you considered removing the package folder entirely from C:\Program Files\WindowsApps and then trying the command?

**Comment by NebelNidas** [comment]
Yeah, the old Control Panel is slowly but surely getting replaced by the Settings app, and there is nothing Open Shell could do about this. It's not that Microsoft just hides the Control Panel entries, they are completely removing them, and you obviously can't access something that isn't there anymore. The only solution would be to program an own Control Panel like app with all the features implemented by yourself, but for most users that's really too much work for an app you won't access that often.

**Comment by ge0rdi** [comment]
I don't think we can do anything about this.
