### ISSUE TITLE
Items not getting added to 'Recent Items' Menu

### ISSUE THREAD

**Issue by starfire42** [Open-Shell/Open-Shell-Menu#283]
**Describe the bug**
No files, of any type get added to the "recent items" menu. This behavior appeared after doing a clean install of Windows (reinstalled open shell and restarted, obviously). Before the clean install it had worked as expected. Prior to the windows reinstall I'd upgraded to open shell from classic shell.

**To Reproduce**
1. Perform a clean install of Windows
2. Install 'Open shell' and configure to show 'recent items' in menu
3. Open any file
4. 'Recent items' menu still says empty

**Expected behavior**
non-executable Files should be added to the recent files menu as they are opened
** Screen Shots **
![empty recent items menu](https://user-images.githubusercontent.com/16580865/71953035-c0a2bc00-3195-11ea-9ae0-c288e30ae6f6.png)
**Version:**

 - Open-Shell: 4.4.142
- Windows 10 Build 18362

**Comment by ge0rdi** [comment]
@starfire42 
Make sure you have `Show recently opened items ...` enabled in Windows settings `Personalisation -> Start`.

**Comment by CTVCAM8** [comment]
That's interesting, 
for me about a year ago a major Win 10 update disabled the jumplists from appearing on
 Open-Shell/Classic Shell.
I was not aware at the time of recent items missing.
I had tried everything in all the shell options, and finally found the same Win 10 setting that worked.

![Turn on recently opened items](https://user-images.githubusercontent.com/44127216/72004150-abfb0e00-31ff-11ea-9ce4-b6969b64c57f.png)

Thinking about other possibilities for recently opened items not showing could be the use of a file cleaner(Crap Cleaner), that will clear that recent list.


There is a way to have incorrect settings in Open-Shell/Classic Shell that will show no recent items.
Just in case, check that "Recent Documents" has a number higher than 0

![Set resent docs to higher number](https://user-images.githubusercontent.com/44127216/72004203-c59c5580-31ff-11ea-8c8b-756ec23d5762.png)

**Comment by starfire42** [comment]
The Windows setting was the problem. Soon as I enabled 'show recently opened items ...' in windows, it started working correctly. 

I did spot the 'max recent documents' setting in my initial troubleshooting
