### ISSUE TITLE
taskbar texture dont't work 

### ISSUE THREAD

**Issue by Daddie2** [Open-Shell/Open-Shell-Menu#288]
when i use a taskbar texture it only appy on side of taskbar at the center it remain the taskbar of windows

![Immagine](https://user-images.githubusercontent.com/50950554/72607299-af3d7a80-3920-11ea-84c7-f5b6be29e1c5.jpg)

**Comment by blackcrack** [comment]
try transparent, then a png as texture ..

**Comment by CTVCAM8** [comment]
Also, try resetting the border sizes to show 0,0 or some other number like 5,3
It that doesn't work, probably a new bug.

**Comment by Daddie2** [comment]
i have windows insider i upgrade and it work thanks

**Comment by TurnstilesCBS** [comment]
I got the same problem how do i fix it
