### ISSUE TITLE
Menu stays open with Run as Administrator/Open file location

### ISSUE THREAD

**Issue by Gittyperson** [Open-Shell/Open-Shell-Menu#295]
Open-Shell Menu, right-click a program (either directly or on search results) and select "Run as administrator". The program opens but the Menu does not go away and can interfere. When opening programs, the Start Menu should always disappear.

I assume this is a consequence of: https://github.com/Open-Shell/Open-Shell-Menu/issues/238 and https://github.com/Open-Shell/Open-Shell-Menu/pull/291.

Open-Shell Menu 4.4.143, Windows 10 1909 Pro x64 (18363.592)

**Comment by ge0rdi** [comment]
@Gittyperson 
I'm unable to replicate it :(

Do you use administrator account, or standard user?
Do you have standard UAC settings (dimmed display, UAC prompt)?

**Comment by Gittyperson** [comment]
Administrator account, UAC setting=do not dim my desktop, Menu Style: Classic with two columns

**Comment by ge0rdi** [comment]
Ok, got it. There also has to be some window opened (it works well if desktop is empty).
So here is how to reproduce:

* Run under Administrator account
* Set UAC to notify but don't dim desktop
* Open some window (and leave it opened on desktop)
* In Start Menu, right-click a program (Command prompt for example) and select `Run as administrator`
* After answering `Yes` in UAC dialog Start Menu stays opened

**Comment by Gittyperson** [comment]
Thanks for testing this. Perhaps only a few times it won't occur, but it almost always does here, whether other windows are present on the desktop or not (= happens on an empty desktop, too).

**Comment by Gittyperson** [comment]
Problem also occurs if I right-click on something and select "Open file location".

**Comment by ge0rdi** [comment]
@Gittyperson 
One more thing.

It seems you are using build from my PR #291.
Can you test with latest build from master (4.4.142)?

I cannot replicate the issue with 142 build. So it seems to be caused by changes in mentioned PR.

**Comment by Gittyperson** [comment]
Confirmed - the issues described here (Run as Admin/Open file location) do not occur on 4.4.142.

**Comment by ge0rdi** [comment]
@Gittyperson 
Please, try with this [build](https://ci.appveyor.com/project/passionate-coder/open-shell-menu/builds/30360890/artifacts).
It should be fixed.

**Comment by Gittyperson** [comment]
Ran some quick tests and everything worked fine - thank you ge0rdi.

**Comment by ge0rdi** [comment]
@Gittyperson 
Glad to hear that :)

Please, let me know if you'll find any more issues with that build.
Ideally directly in #291 PR as this is not merged to master yet.
I will keep PR open for a while and merge only when there will be no more reports.

Thank you for testing.
