### ISSUE TITLE
the "start menu (windows)" link has disappeared

### ISSUE THREAD

**Issue by rexland** [Open-Shell/Open-Shell-Menu#296]
regarding the "start menu (windows)" link when you click on the windows start button and it shows the windows 7 style start menu, the link to windows 10 apps has disappeared.  I've repaired, uninstalled, reinstalled, rebooted, etc. but the link isn't showing any longer.  what did I do?  it's possible that it was deleted by accident (not the only person using the computer) but how do I restore it?  please.
thanks in advance.

**Comment by CTVCAM8** [comment]
Try this

![Windows start screen or start menu shortcut](https://user-images.githubusercontent.com/44127216/73237670-3376d580-414b-11ea-94a8-7525eebae498.png)

**Comment by rexland** [comment]
exactly what I was look for.  I thought I scrolled to the bottom of the list looking for it but apparently I did not.  thanks, I'll give it a try.
