### ISSUE TITLE
Define resource bitmaps in external files // or // allow custom mode skins in their own folder

### ISSUE THREAD

**Issue by TheArkive** [Open-Shell/Open-Shell-Menu#300]
Is it feasible to be able to modify how theme files are read, so that external references to bitmaps and fonts (in external files) can be used?

This would theoretically make it much easier to have a start menu theme that matches a 3rd party theme.

// or //

Modify the handling of the "custom theme" mode, that uses resource numbers for file names, and always looks for 1.txt ... modify this behavior so that users can place these files in a subfolder within the SKINS folder.

This makes it much easier to develop multiple skins without the need to resource-hack constantly.

**Comment by ge0rdi** [comment]
I guess there is no plan for that.

> This makes it much easier to develop multiple skins without the need to resource-hack constantly.

You can pick some base skin from `Src/Skins`, change files you need and then build skin project in Visual Studio.
No need for Resource Hacker.
