### ISSUE TITLE
remove the pin to start option for openshell

### ISSUE THREAD

**Issue by Janaue** [Open-Shell/Open-Shell-Menu#303]
I have windows 10 1809 and when I right click on an exe or some icon on the dektop, i see an option to  ''pin to start''  (open shell) which i dislike.
I want to remove it.
For the official pin to start by microsoft, i use this tutorial https://www.tenforums.com/tutorials/37258-add-remove-pin-start-context-menu-windows-10-a.html
but for openshell, i do not know how to remove it

**Comment by blackcrack** [comment]
Suggestion:

Startbutton [right Mouse Klick]=> Configuration
[General Behavior]
a checkbox for in the configuration 
[Default on] "Enable Pin to start at the Sub-Filemenu" 

best regards
Blacky

**Comment by Janaue** [comment]
yes it works with your way
