### ISSUE TITLE
Open-Shell Silent install switches

### ISSUE THREAD

**Issue by ITKid1124** [Open-Shell/Open-Shell-Menu#307]
Hi,
What silent switches should I be using to get Open-Shell to install the classic startmenu silently please for deployment.
thank you,

**Comment by blackcrack** [comment]
@ge0rdi @Ibuprophen 

Please add in the Wikipages "Unattended Install" with the Setup Switches
i have tried and have push the button "New", but it goes return to the Project..

best regards
Blacky

**Comment by ITKid1124** [comment]
Hi, Thanks for your reply.
I have tried those switches and anything with ADDLOCAL the install just ignores or does nothing., Please advise

**Comment by blackcrack** [comment]
how do you use this cmdl, do you use a installer like WPI or something 
or easy a cmd/batch ?

**Comment by ITKid1124** [comment]
Hi,
I am using a batch file and the \OpenShellSetup.exe /qn ADDLOCAL=StartMenu does not work it just ignores it and does not install,

**Comment by blackcrack** [comment]
if you take a "\" then must you use a point befor, like so ".\" this names, on "." this point on this "\" place 
like you told .\thisfolder\this.exe, so, should you use " .\OpenShellSetup.exe"  with the fullstop point .

then should it works.

if it's works, please, close this issue.. take a look by the side of comment "Button"

**Comment by fygul** [comment]
@ITKid1124

try this:

`OpenShellSetup_4_4_142.exe /qn ADDLOCAL=StartMenu /l* log.txt`

Then check log.txt, maybe you will find something like this:

> Error 1925. You do not have sufficient privileges to complete this installation for all users of the machine. Log on as administrator and then retry this installation.
> MSI (s) (08:C8) [22:38:08:556]: Product: Open-Shell -- Error 1925. You do not have sufficient privileges to complete this installation for all users of the machine. Log on as administrator and then retry this installation.

**Comment by ge0rdi** [comment]
Running installer with `/qn ADDLOCAL=StartMenu` parameter should install Start Menu component silently.
Make sure you are running it as elevated admin.
