### ISSUE TITLE
admx template

### ISSUE THREAD

**Issue by haleman22** [Open-Shell/Open-Shell-Menu#308]
**Describe the bug**
downloaded latest version of Open-Shell Menu and copied admx template to active directory (win 2016 standard). When creating a new gpo, I get error pointing to the admx file.  After acknowledging the error, Open-Shell Menu gpo entry does not show.

**To Reproduce**
1. Add amdx template to central gpo store in AD
2. Create new gpo and edit settings under Admin Templates
3. See error

**Expected behavior**
No error.  New gpo settings related to Open-Shell Menu should display.

**Screenshots**

**Version:**
 - Open-Shell: [ 4.4.142]
 - OS: Windows 10 Pro 1909 & Windows 2016 Standard

**Additional context**
Installing only Open-Shell Menu. I've actually added the admx template to server and workstation and attempted to open in both.  Same error even though file is present on server\workstation c:\windows\policydefintions and server central gpo store
![error](https://user-images.githubusercontent.com/60796733/74065927-fbca2200-49c3-11ea-8332-d09e6a911165.png)

**Comment by Ibuprophen** [comment]
I believe that the following response from @ge0rdi applies to this specific question and should resolve your issue. 

https://github.com/Open-Shell/Open-Shell-Menu/issues/165#issuecomment-487102745


~Ibuprophen

**Comment by haleman22** [comment]
That's exactly what I did but it does not work.  I had actually ran across that post during my search before I decided to post a question.

**Comment by Ibuprophen** [comment]
Did you change/add the ownership/permissions of the admx file to include yourself with all permissions? 

~Ibuprophen

**Comment by ge0rdi** [comment]
@haleman22 
You need to also copy corresponding `adml` (language) files to `en-US` folder.

See `PolicyDefinitions.rtf` guide in `PolicyDefinitions.zip` for more info.

**Comment by haleman22** [comment]
Thank you for th reply but I did that from the get go.  Still not working.

**Comment by haleman22** [comment]
UPDATE:  I downloaded the file again and extracted it, again and copied both files again to the same locations as before (again) and this time it worked.  Thank you for the help.

**Comment by ge0rdi** [comment]
Great :)
