### ISSUE TITLE
Eliminate additional Windows Shut Down dialog box after clicking Shut Down

### ISSUE THREAD

**Issue by KennethK19** [Open-Shell/Open-Shell-Menu#309]
After clicking on Shut Down from my Start menu, an additional dialog box appears with the same list of options provided in the Shut Down menu from the Start menu.  Why does a simple Shut Down event need to be redundant?  Clicking once should suffice in letting the computer know that I would in fact like to shut it down.  Toggling various options already provided in Settings did nothing to change this situation.  Getting rid of that extra step when shutting down would be most helpful.

**Comment by ge0rdi** [comment]
I assume you are using `Classic` or `Two column` style.
You can pick actual _shutdown_ action from menu (that little arrow to the right of `Shutdown` text).

Alternatively you can use `Windows 7 style`, where you can select what _action_ will Shutdown button do (e.g. Shutdown, Restart, Sleep).
It can be set via `Settings -> Main Menu -> Shutdown command`.

**Comment by Gittyperson** [comment]
Go to Settings/Customize Start Menu. On the left column (Current menu items) locate the Shutdown entry, it should be near the bottom.

Does it say "Shutdown dialog" perhaps? Something else? Right-click/Edit Item and in the Command selection at the top pick "shutdown" (instead of "shutdown_box").
