### ISSUE TITLE
Can't get Open Shell to Open

### ISSUE THREAD

**Issue by KJS-NYC** [Open-Shell/Open-Shell-Menu#312]
Until today, I was using Classic Shell.  I prefer its Windows Explorer Toolbar.   The Toolbar suddenly vanished.  I uninstalled and reinstalled Classic Shell, but it's not where I can see it.
    I found this page about Open Shell.  I uninstalled CS, rebooted, then installed Open Shell.  Again, it's like I didn't install anything.    It appears in the Control Panel (Win 10), but not in the Start Menu. 

With both installs, the choice to select or not select isn't available; each says it "won't be installed." 

I really want to get that Toolbar back.  Any help is appreciated.  Thanks.

**Comment by KJS-NYC** [comment]
Update - I uninstalled OpenShell, rebooted, then tried reinstalling as Administrator.  The only difference is that it now appears on the Windows 10 Start Menu.  I opened Options for the File Explorer Bar, and my settings from Classic Shell are still there.

The last time the Classic Shell Bar worked, it was included on the regular Windows toolbar under View Options.  When it stopped appearing for Classic Shell, I installed Open Shell.  It still isn't  listed under View Options.

The Win 10 tool bar is giving me eyestrain, as well as a pain to use.  If someone has any ideas, please respond.

**Comment by ge0rdi** [comment]
Make sure you have `Classic Explorer Bar` enabled in explorer `View` -> `Options`:
![image](https://user-images.githubusercontent.com/2453094/91668855-510c8300-eb10-11ea-8b22-d70c1e8c65a9.png)
