### ISSUE TITLE
Bitdefender says Open-Shell manifests ransomware behavior.

### ISSUE THREAD

**Issue by AarontheRobotWolf** [Open-Shell/Open-Shell-Menu#317]
This isn't a bug, but it is a huge problem for me. I leave my computer on for a few days
and then all of my programs close and Bitdefender says:
![Annotation 2020-02-13 105049](https://user-images.githubusercontent.com/39656218/74455691-b8543580-4e53-11ea-8266-2623163bdc29.png) 
I've been getting this problem on both my Desktop and Laptop for a while. I think it's just a false positive but it's messing me up with work so I wanted to know if this is fixable. 

**Steps to reproduce the behavior:**
1. Have both Open-Shell & Bitdefender installed.
2. Go to 'Bitdefender'
3. Then go to 'Protection'
4. Turn on 'Ransomware Remediation'
5. Leave your computer running for a while, not sure how long.
6. Bitdefender will see a problem and try to fix it, resulting in all your programs closing and your work being lost.

**Version:**
 - Open-Shell: 4.4.142
 - OS: Windows 10 1903

**Comment by ge0rdi** [comment]
Please, report this issue to Bitdefender.
There is nothing malicious in `Open-Shell`.

If they will provide any proof of some wrong behavior, we can have a look at it.
But most likely it is just false positive.

**Comment by AarontheRobotWolf** [comment]
k
