### ISSUE TITLE
Freeze explorer Windows 2016 - able to reproduce

### ISSUE THREAD

**Issue by domantia** [Open-Shell/Open-Shell-Menu#319]
The issue is the same as described in https://github.com/Open-Shell/Open-Shell-Menu/issues/132, but I found a way in which I can reproduce the behavior.

1. Log in to a Windows 2016 server as an local administrator
2. Start a Windows Explorer window and browse to a mapped network drive
3. Import a .reg file which I have shared here https://drive.google.com/file/d/11YoMFh7gnzEtrTmGweOd0xg1q0Qw-qyT/view?usp=sharing
4. After the import you can no longer change folders in the Windows Explorer windows until you restart the shell explorer.exe process in the user session. If you restart the explorer.exe process the issue no longer occurs during that user session.

Test configuration:
- Windows 2016 server virtual machine
- tested with OpenShell 4.4.135 and 4.4.142

The .reg file imports mostly File Type Associations in the "HKEY_CURRENT_USER\SOFTWARE\Classes" registry key. We found that a application called Bricscad was causing the explorer freeze, but after investigating this further we noticed that this application imports these registry keys when starting the application. If OpenShell is not installed on the computer (or not started) the problem does not occur. Now we can reproduce the issue even if Bricscad is not installed on the computer by just importing a .reg file similar to what the Bricscad application does when it launches.

I'm not sure if it actually is an OpenShell problem or a Windows problem, but I hope you now can reproduce this issue yourself as well and possibly find a way to fix it.

**Comment by ge0rdi** [comment]
Could you provide manual crash dump from explorer.exe?
You can create it for example using Task Manager.

**Comment by domantia** [comment]
I have shared an explorer.dmp (zipped) here [https://drive.google.com/file/d/1Ttf9J7RtF3a0efW5TTKYg5dO9gfYfN2w/view?usp=sharing](url)

**Comment by domantia** [comment]
If I can assist further with investigating this issue, please let me know.

**Comment by ge0rdi** [comment]
I was looking at the dump. And it is definitely weird. There is more than 800 threads running in explorer. This is definitely not normal.

But no thread is running inside `Open-Shell` so I have really no clue what could be going on :(
I don't know what to begin with.

I guess I need to install Windows Server 2016 to VM and try to replicate it (and then debug).
But I'm not sure when I'll get to that.

Could you possibly try with latest Windows Server 2019 whether there is the same issue?

**Comment by domantia** [comment]
I can not reproduce this issue with Windows Server 2019. Unfortunately I'm not able to upgrade to 2019 any time soon. If I reproduce the issue and look with process explorer I indeed see 800+ threads in explorer.exe. With process explorer I can see the trheads and the stack of those threads. 

I do not really understand what I'm looking at to be honest, but I have attached a screenshot and perhaps you have a better understanding on what is going on in those threads/stack after seeing this screenshot.
![High_thread_explorer_exe](https://user-images.githubusercontent.com/61272604/76071638-da466100-5f96-11ea-8a59-1e3283ab2177.jpg)

**Comment by domantia** [comment]
In the same process i also see:
![High_thread_explorer_exe2](https://user-images.githubusercontent.com/61272604/76072247-eaab0b80-5f97-11ea-89d2-021f957d7ced.jpg)

Is it shcore.dll which is actually triggering this problem?

**Comment by ge0rdi** [comment]
> I can not reproduce this issue with Windows Server 2019.

At least something positive.

> Unfortunately I'm not able to upgrade to 2019 any time soon.

That's really unfortunate. But I'd really recommend to upgrade no matter of this issue. Server 2016 is already 3 years old. And I know about more issues in it (that are resolved in 2019).
For example we've had issues with updating 2016, update process took very long. This works well in 2019.

>  With process explorer I can see the trheads and the stack of those threads.

I can see that in dump. But I don't know why did it end up in that state.

But since there is no such issue in new Server 2019, I can only assume that there was some bug in older Windows and it was already fixed.

I'm sorry but I don't want to spend my time with hunting bugs in old versions of Windows :(

I guess you will have to upgrade OS if you want to use `Open-Shell`.

**Comment by domantia** [comment]
I understand your reasoning. Thanks for you assistance.
