### ISSUE TITLE
How to remove toolbar?

### ISSUE THREAD

**Issue by Tymski** [Open-Shell/Open-Shell-Menu#326]
How to remove the toolbar in explorer? I deleted all entries, the toolbar is still there.
![image](https://user-images.githubusercontent.com/8183632/75578967-23615700-5a65-11ea-9550-ade1db22fc68.png)

**Comment by blackcrack** [comment]
oh i see a issue, wrong url @ge0rdi 
i guess, start the setup again, then have you a 
possible which things remove completely and which things able to install
You can also right click on the Classic Explorer Bar and remove the chop on "Classic Explorer Bar"
then is the bar away..

**Comment by ge0rdi** [comment]
@Tymski 
You can either uninstall whole `Classic Explorer Bar` feature using installer.

Or you can just disable showing explorer bar. Untick `Classic Explorer Bar` in Explorer `View -> Options`:
![image](https://user-images.githubusercontent.com/2453094/75607787-dd56d280-5afa-11ea-92f2-583870a545e9.png)

**Comment by Tymski** [comment]
thanks

**Comment by ackzell** [comment]
Hello, 

I removed the Classic Explorer (I don't want the bar) using the installer, but I am left with this thin bar that gives me a resizing cursor.

![image](https://user-images.githubusercontent.com/601266/110878695-455cfe80-82a1-11eb-8608-8751c5d35924.png)

Any way I can get rid of it? You'll notice I don{t have the option to hide Classic Explorer Bar because I removed it.
![image](https://user-images.githubusercontent.com/601266/110878879-9b31a680-82a1-11eb-9998-cd0f1bc33a4a.png)

**Comment by ge0rdi** [comment]
@ackzell 
I'm afraid this has nothing to do with `Open-Shell` since you removed `Classic Explorer` completely. And no other component should interfere with File Explorer.

**Comment by ackzell** [comment]
Thanks for your response@ge0rdi, 
I came across #658 where basically the same thing happened to me. 
It makes me believe that actually `Open-Shell` had to do with it.

**Comment by ge0rdi** [comment]
Try to uninstall `Open-Shell` completely to see whether the issue will disappear.

**Comment by ackzell** [comment]
Thanks again!

Tried that already and it didn't help.

Uninstalled just `Classic Explorer`, repaired the installation, uninstalled `Open-Shell` via the installer yet the bar remains.

Is there a guide on how to remove `Open-Shell` completely along with any traces on the registry or files on the file system that might be left behind by the installer?

**Comment by ge0rdi** [comment]
Uninstaller is supposed to uninstall everything relevant.

After uninstallation only `Open-Shell`'s user registry key and `AppData` folders should remain (so that you won't lose any settings).
But these can hardly cause any issue with File Explorer.

It is very likely the issue is not related to `Open-Shell`.

**Comment by mhgschmidt** [comment]
Fine. But how to do this on the COMMANDLINE ???
(registry setting or some setting in the XML config ???)

... been searching. Found nothing ...
:-(

**Comment by bonzibudd** [comment]
I imagine that this is probably related to Classic Explorer, but more so a bug being exposed in Windows Explorer itself regarding toolbars in general. I imagine this will get worse with time as MS seems to be making some big changes to the Explorer interface.

**Comment by Whoniverse** [comment]
https://github.com/Open-Shell/Open-Shell-Menu/issues/681#issuecomment-813086151

**Comment by Whoniverse** [comment]
> Fine. But how to do this on the COMMANDLINE ???
> (registry setting or some setting in the XML config ???)
> 
> ... been searching. Found nothing ...
> :-(

You can solve this bug by this Reg Key:
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Internet Explorer\Toolbar]
**"Locked"=dword:00000001**

**Comment by MohaNNadO** [comment]
> This "bug" append if you uncheck the lock of the "toolbar" THEN disabled Classic-explorer
> you have those options by a right-clik on the toolbar
> https://i.goopics.net/lvj47.png
> 
> the "uninstaller" should enable (Locked) the "toolbar" before uninstalling everything
> 
> You can solve this bug by this Reg Key:
> [HKEY_CURRENT_USER\SOFTWARE\Microsoft\Internet Explorer\Toolbar]
> "Locked"=dword:00000001

Thank u vary much 
it works 
u r a life saver

**Comment by ackzell** [comment]
Thank you @Whoniverse! Exactly what was needed.

**Comment by MinhHieuNguyen0210** [comment]
> This "bug" append if you uncheck the lock of the "toolbar" THEN disabled Classic-explorer
> you have those options by a right-clik on the toolbar
> https://i.goopics.net/lvj47.png
> 
> the "uninstaller" should enable (Locked) the "toolbar" before uninstalling everything
> 
> You can solve this bug by this Reg Key:
> [HKEY_CURRENT_USER\SOFTWARE\Microsoft\Internet Explorer\Toolbar]
> "Locked"=dword:00000001

it work for me !

**Comment by ulrichando** [comment]
you guys don't need all of that you can simply remove that during the installation process

**Comment by Craulback** [comment]
Disable "Show status bar" in Classic Explorer settings
![Screenshot 2023-02-18 211805](https://user-images.githubusercontent.com/92492424/219921965-b9df5428-661f-4f7b-a080-291d4fbbc5f0.png)

**Comment by Merfyn007** [comment]
Well, the developpers probably fork another tool because they don't even understand how to type one line of code to put an option that will give a user the right to remove this shitty toolbar.

Guys, time to learn how to code, we don't gave a f* about this shitty toolbar.

So, now in 2023 with the last Windows 11 version, what is the solution to remove this shitty and very shitty useless toolbar ?

Thanks ! 

(devs that make me wasting my times shouldn't work in programming sector)

**Comment by Merfyn007** [comment]
> Disable "Show status bar" in Classic Explorer settings ![Screenshot 2023-02-18 211805](https://user-images.githubusercontent.com/92492424/219921965-b9df5428-661f-4f7b-a080-291d4fbbc5f0.png)

Dude, stop posting without reading the question and what you share ! It's not the toolbar but the status bar.

**Comment by Merfyn007** [comment]
> oh i see a issue, wrong url @ge0rdi i guess, start the setup again, then have you a possible which things remove completely and which things able to install You can also right click on the Classic Explorer Bar and remove the chop on "Classic Explorer Bar" then is the bar away.. if you want add it again, press the "ALT" button in explorer, then see you the menu, then again right Mouse Key at the Menubar and Enable "Classic Explorer Bar"

It come back everytime because the dev don't learn how to code before compiling this application.

**Comment by Remikaa** [comment]
> This "bug" append if you uncheck the lock of the "toolbar" THEN disabled Classic-explorer you have those options by a right-clik on the toolbar https://i.goopics.net/lvj47.png
> 
> the "uninstaller" should enable (Locked) the "toolbar" before uninstalling everything
> 
> You can solve this bug by this Reg Key: [HKEY_CURRENT_USER\SOFTWARE\Microsoft\Internet Explorer\Toolbar] "Locked"=dword:00000001

when i first open file explorer i dont have the tool bar. but after my wallpaper changes (I have wallpaper engine) the tool bar appears again. even after locking the toolbar

**Comment by Alexen08** [comment]
Thank you very much, it worked!!! :3

**Comment by simonLeary42** [comment]
the fix for me was unticking and reticking the "lock the toolbar" option and then closing and reopening explorer: https://github.com/Open-Shell/Open-Shell-Menu/issues/1526#issuecomment-2484164103

**Comment by niccy266** [comment]
> This "bug" append if you uncheck the lock of the "toolbar" THEN disabled Classic-explorer you have those options by a right-clik on the toolbar https://i.goopics.net/lvj47.png
> 
> the "uninstaller" should enable (Locked) the "toolbar" before uninstalling everything
> 
> You can solve this bug by this Reg Key: [HKEY_CURRENT_USER\SOFTWARE\Microsoft\Internet Explorer\Toolbar] "Locked"=dword:00000001

This worked for me as well, thank you so much!!

**Comment by Potato95** [comment]
It's still early, but I seem to have nuked that ribbon bar by deleting ITBar7Layout at [HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Toolbar\ShellBrowser].

I don't get the small bar even after setting Locked to 0, so it seems to have solved all problems.
