### ISSUE TITLE
Fix the path C:\ProgramData\OpenShell\ on C:\ProgramData\Open-Shell\

### ISSUE THREAD

**Issue by Andy-Solo** [Open-Shell/Open-Shell-Menu#330]
Fix the path C:\ProgramData\OpenShell\ on C:\ProgramData\Open-Shell\

**Comment by ge0rdi** [comment]
Is there any problem with currently used path?

**Comment by ge0rdi** [comment]
We don't plan to change the path (unless there is some issue with current one).
