### ISSUE TITLE
SCCM won't install new version during OSD

### ISSUE THREAD

**Issue by Wasshup** [Open-Shell/Open-Shell-Menu#334]
Hi,
I'm trying to install Open-Shell with SCCM while deploying new operating system with task sequence. After OS deployment I created Install Applications task and put Open-Shell there.
With version 4_4_138 no problem at all, everything works fine, but now if I download 4_4_142 or 4_4_143 version it just simply won't install. Deployment type is MSI and I used this command with parameters: 

`OpenShellSetup_4_4_143.exe /qb ADDLOCAL=StartMenu APPLICATIONFOLDER="C:\Program Files\OpenShell"`

Are the parameters different in new version ? Or can the problem be anywhere else ?

Thank you for suggestions.

Screens:
https://imgur.com/a/hT0SrzP

**Comment by blackcrack** [comment]
i use ever /qn :
OpenShellSetup.exe" /qn ADDLOCAL=StartMenu
best

**Comment by ge0rdi** [comment]
@Wasshup 
I'm not aware of any changes related to installer.

You may try to add `/lvx* msi.log` parameter and then examine log created by MSI installer. Maybe you'll find some clue there.
Eventually post it here, I can have a look.
