### ISSUE TITLE
Scaling needs some work for 4k/150% displays

### ISSUE THREAD

**Issue by klepp0906** [Open-Shell/Open-Shell-Menu#339]
So this is gonna be small/quick as my wife is glaring at me and i didnt expect to stumble upon this.

the new qbitorrent release has some scaling problems.   A developer suggested a workaround here https://github.com/qbittorrent/qBittorrent/issues/12248#issuecomment-603545033

the tldr version is adding environmental variables for scaling made the menu look substantially better on my 4k/150% scaled screen.

might want to look into where the discrepancy lay with the currently used scaling by open-shell and what is being enforced by using those environment variables.

This goes way way above my paygrade.   Just the messenger.

I always hated how crisp it looked on my laptop without scaling compared to my desktops.   now my desktops look just as crisp :)

My fear (based on the commotion in their issue tracker) is that the developers there will tackle the scaling issue pretty quickly) which means ill be stuck pulling the environment variable at that point.

For the time being, if anyone knows how to use such a variable but pointed towards open-shell that would be great :P

**Comment by blackcrack** [comment]
i have a LG 43" UHD TV, the Scaling is perfect !
have a resolution with 2560x1440 and there is the Screenshoot
![Screen 00003](https://user-images.githubusercontent.com/7925717/77522114-fba6b880-6e83-11ea-8c87-6cc9afde945a.jpg)

must it not ever be the highest ..
![Screen 00004](https://user-images.githubusercontent.com/7925717/77522202-22fd8580-6e84-11ea-8a59-dfbd5cd454b8.jpg)

do you have also an Screenshoot ?
best regards
Blacky

**Comment by klepp0906** [comment]
It's been talked about elsewhere, its not dramatic or to do with sizing, everything is the same size as far as the menu itself goes.   The font and icons just come in sharper.

Ill take some screenshots once i get done w/ work and post em up
