### ISSUE TITLE
No option to left as default for windows 10 Start Menu

### ISSUE THREAD

**Issue by ctorbaoglu** [Open-Shell/Open-Shell-Menu#341]
Hi,

I don't wanna change my full screen Windows 10 start Menu but no option in this software to do so.

Please add.

Thank you.

**Comment by blackcrack** [comment]
@Ibuprophen we are in the getto ?... holy..
could you close it... to set see some lang is not accept ..
best
Blacky

**Comment by ctorbaoglu** [comment]
sorry for the wrong typo mistake

**Comment by NebelNidas** [comment]
@ctorbaoglu Sorry, I don't really get what you want to express here.
>I don't wanna change my full screen Windows 10 start Menu

Do you mean:
1. You don't want Open Shell to replace your default Win10 menu (but why would you have installed it then?)
2. You don't want Open Shell to replace your default Win10 menu if it's in fullscreen mode
3. You don't want Open Shell to replace your default Win10 menu when you're in tablet mode (most plausible to me)

If for option 1, then just uninstall Open Shell or make it the secondary menu. Option 2 also doesn't make much sense. Option three would actually be a nice feature and I think it should get implemented, too.

**Comment by ge0rdi** [comment]
You can also select what key/action opens `Open-Shell` menu and what open standard Windows start menu in:
`Open-Shell settings` -> `Controls`
