### ISSUE TITLE
After installation, I can't get back to the open shell setting menue

### ISSUE THREAD

**Issue by mhodish** [Open-Shell/Open-Shell-Menu#344]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**
 - Open-Shell: [e.g. 4.4.131]
 - OS: [e.g. Windows 10 1903]

**Additional context**

**Comment by bonzibudd** [comment]
Can you provide more details? If you right-click on the Start button, it will open a menu that can take you to Open Shell settings.
