### ISSUE TITLE
Can't seem to figure out how to resize open shell menu

### ISSUE THREAD

**Issue by TimmSkiller** [Open-Shell/Open-Shell-Menu#346]
I've searched every menu and couldn't find any way to resize the open-shell horizontally or vertically. It currently is too big vertically and I would like to be able to resize it like the normal Windows start menu.

**Comment by bfoos** [comment]
You can adjust main menu icon sizes to change vertical menu size.

**Comment by bonzibudd** [comment]
You can resize it vertically by changing how many recent items appear in the list. A click and drag style resizer was never available in Classic Shell, nor stock Windows start menus before Windows 10.

**Comment by OfficialAwesomeDude** [comment]
> You can resize it vertically by changing how many recent items appear in the list. A click and drag style resizer was never available in Classic Shell, nor stock Windows start menus before Windows 10.

how do you change the recent items? whenever i try and delete a recent item a new one appears?

**Comment by michaelts1** [comment]
Actually there is a setting to resize the Open Shell menu: In the settings window, after checking "Show all settings" go to the "Main Menu" tab, there you will find the following settings:  Minimum menu height, Jumplist pane width, Programs pane width. Under "Menu look", there is also "Sub-menu width".
