### ISSUE TITLE
[question] updating from classic shell

### ISSUE THREAD

**Issue by atesin** [Open-Shell/Open-Shell-Menu#349]
hi... i just realized classic_shell development had opened source and contiued here, what made me very happy (thanks ivo beltchev, thanks open_shell team) ... 

so to update i just downloaded open_shell and installed over classic_shell,... i do it with the hope it read/import my preferences and uninstall later (the programs have different names) but i don't know if it is ok, seems it preserved my preferences but... 

when i wanted to uninstall classic_shell later i couldn't find it anywhere, seems it were already uninstalled / wiped out / overwriten / renamed / combined / absorbed by open_shell ... i don't know if the things are clean, or the correct update process....

seem to worked but... now i'm not sure if i have comflicting programs , or if i could remove any one i will provoke some data inconsistence , etc

the documentation says no word about it... would be good if you write some little instructions on how to do it, for me and anyone possible in the same case, please

thanks again

**Comment by bfoos** [comment]
As far as I know, Open-Shell properly updates over ClassicShell.

**Comment by ge0rdi** [comment]
`Open-Shell` can be installed over existing `Classic-Shell` installation.
It will also automatically import settings from `Classic-Shell`.
