### ISSUE TITLE
Menus (or toolbar) in File Explorer doesn't seem to be removed after uninstalling it

### ISSUE THREAD

**Issue by favianrizqulloh** [Open-Shell/Open-Shell-Menu#351]
**The 'menus' in File Explorer doesn't seem to be removed after uninstalling it**
So I just did a uninstall, reboot, and then 'the menus' in File Explorer is still there
![image](https://i.imgur.com/0L8Xk3a.png)
Tried to open Folder Options --> View tab --> uncheck 'Always show menus' does not work

**Version:**
 - Open-Shell: 4.4.142
 - OS: Windows 7 (Service Pack 1)

If anyone know how to remove it, please tell us how to do it.

**Comment by xcasxcursex** [comment]
![image](https://user-images.githubusercontent.com/58130821/83265291-a03ad300-a204-11ea-9a7a-4fdb4e127566.png)

**Comment by favianrizqulloh** [comment]
I tried that already and it didn't work

**Comment by xcasxcursex** [comment]
I notice in your screenshot, you're showing the 'My Computer', which is supposed to always show the menu - that option is not meant to work everywhere. Try opening the control panel for example.

![image](https://user-images.githubusercontent.com/58130821/83266500-40452c00-a206-11ea-9d8d-812aa38bd736.png)

**Comment by favianrizqulloh** [comment]
![image](https://user-images.githubusercontent.com/48427319/83268424-cdc95180-a1ef-11ea-98bd-54be0cf673b2.png)

**Comment by xcasxcursex** [comment]
Ohhh kaaayy that's weird. Sorry I can't reproduce that here :( 

If you open regedit, and browse to Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced , there should be a key there called "AlwaysShowMenus", is it set to 0?

**Comment by favianrizqulloh** [comment]
Okay, there's no key called "AlwaysShowMenus" in my PC. So I added that key and set to 0, restart, and still... No luck :(
![image](https://user-images.githubusercontent.com/48427319/83275808-e3dc0f80-a1f9-11ea-833d-7f8c3eab9ed8.png)
(and thank you for trying to help 😊)

**Comment by xcasxcursex** [comment]
I fear I may be of limited help because I'm on Win10 and you're on... Win8? I forget what the old ones look like hahah
I have installed the open shell windows extension and removed it though, and this setting is being respected here, so I don't know why your PC doesn't want to do as it's told :(

Do you have this key: Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\Folder\AlwaysShowMenus ?

If so, there should be a key in there called `RegPath`, which appended with the value for the key `ValueName` specifies the registry path that is used to store this setting - which in my case is the key you edited above.... but again, this might be a Win10 thing. If you've ticked and unticked that box then it should have changed the setting so the fact that key doesn't exist for you, suggests that it's stored elsewhere in your case. Perhaps the above, may help you find out where.

Make sure you undo anything you change in case I'm leading you down the wrong path here. I don't see this causing any harm, but it's probably best not to leave something strange in your registry.

**Comment by favianrizqulloh** [comment]
I'm using Windows 7

and yup... tick and untick the box changes the value here

**Comment by xcasxcursex** [comment]
It's really odd that it was missing entirely. As best I can tell reading the source here, this app doesn't remove it - and if it's missing, ticking the box in settings recreates it, so I don't see how it was missing.  Something is very amiss here.

I was hoping I could help you with a setting you might have overlooked but it seems there's something else at play. I guess it's nice that you've excluded this setting being on, as causing the problem but now you've got another "why isn't this working?" question to add to the original... I'm sorry!

**Comment by alfieedev** [comment]
Hmm same issue here. Tried all of the methods given above, nothing is working

**Comment by NebelNidas** [comment]
I've also had this issue several times in the past. I then always restored my system to an earlier System Restore Point, but obviously that's not a good solution. According to several sources in various Windows forums, this solution should work (although I cannot verify it now, as I don't know of any way to reproduce this issue):
>Navigate to registry key `HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Toolbar\ShellBrowser` and delete the `ITBar7Layout` value.

**Comment by xcasxcursex** [comment]
@alfieedev @NebelNidas You guys on Win7 too?

IE trick is worth a try since IE and explorer are basically the same in ye olde windows.

**Comment by favianrizqulloh** [comment]
can confirm this is it. It works now! Thanks 😄

![image](https://user-images.githubusercontent.com/48427319/83962000-2f11b480-a8c3-11ea-9194-99b77f3abaf1.png)

**Comment by xcasxcursex** [comment]
Had a poke around and a few seconds of searching tells me that this is in fact a very old win7 bug that happens to all kinds of different IE/Explorer toolbar addons. Good catch @NebelNidas !

**Comment by NebelNidas** [comment]
@xcasxcursex It's around since at least Windows Vista, seems like Microsoft never bothered to fix it as it's a very rare bug to occur. So it's still possible to get it in Windows 10, unfortunately... 😕

**Comment by xcasxcursex** [comment]
I do have a vague recollection of it being especially problematic around a time when malware toolbars were booming. I was getting out of the desktop tech support space back then so I kinda caught a glimpse of it on the way out. I'm getting old, and so is win7, but some things never change.... Like MS leaving old bugs until it's too late.

Offtopic my favourite one lately is that Window's scheduler has always been junk, MS ignored it for years and years while a small subculture of CPU-intensive users (physics sims, audio and video editing, etc) cried... and when Ryzen CPUs dropped they completely broke it. They're finally scrambling to fix it now, after 25 years. Meanwhile windows runs faster on linux in a VM than it does on bare metal. LOL.

I guess we should expect these things around here, given that we're all trying to emulate an ancient long dead and actually decent start menu  LOL
