### ISSUE TITLE
Major Memory leak on Windows 10!

### ISSUE THREAD

**Issue by Dracrius** [Open-Shell/Open-Shell-Menu#353]
**Describe the bug**
I had had issues for years on my main machine with Windows Explorer just ever expanding and eating up all my RAM. I never identified the issue but never tried uninstalling classicshell that I had updated to openshell. But recently I rebuilt my main rig from scratch. After completing my step by step install of essential software I noticed it happening again on a 100% fresh install of Windows 10 1909. I removed any other possible culprit with shexview to disable all none Microsoft shell extensions even Openshells but that made no difference. After that it was down to Openshell or AeroGlass so AeroGlass was uninstalled next with no change, I finally just uninstalled Openshell and after 2 hours up my Explorer is still running at   93-110mb rather then the 330+ it would reach in 30min or 2.5gb it would sit at after a couple hours.

**To Reproduce**
1. Install most recent Openshell
2. Use Windows (Maybe open 5-6 windows to watch RAM Climb close and notice no decrease)
3. Go about business for an hour (watch youtube through Firefox) 
4. Open task manger to see Explorer Next highest RAM using app to Firefox at 380mb.
5. Go even longer not knowing what is reasonable and check after 2hrs and see 2.5gb

**Expected behavior**
Uninstall Openshell and in 2 hrs I have seen a max of 204mb on Windows Explorer in Task manager

**Version:**
 - Open-Shell 4.4.142
 - OS: Windows 10 1909

**Comment by Nodens-** [comment]
I'm 99,999% sure your issue is unrelated to OpenShell entirely and is triggered by something else. Regardless, the information you provide is not enough.
Use the information here: https://kb.sitecore.net/articles/253710 (Gathering memory dump files - on-demand)
Create 5-6 memory dumps of explorer.exe while the process is leaking, in increments of 200mb. Preferably on the lower end of the leak so that the resulting memory dumps are smaller.
Zip them up and post them here.

**Comment by xcasxcursex** [comment]
204MB?! Mine's using 34.

I'd be taking a closer look at your other 'essential software'.

**Comment by Dracrius** [comment]
Ok been way to busy to get to test anything especially when this has always been a rabbit hole but I am kinda beyond frustrated that a brand new build not sharing a single piece of hardware from the first has grown the same issue despite being brand new with the most recent Windows 1909 the install media was made from microsofts own tool for creating install usb's 2-3 weeks ago. 

I have now seen it pop back up oddly for short times going into the gigs but it will clear back down to like 34-56mb. I'm running almost nothing I can contribute it to but openshell seems to exasperate the problem as I notice it almost immediately after a fresh reboot if I watch task manager over a couple hours of regular use while it took about a week of monitoring for me to catch an instance of it doing it after uninstalling openshell but I will admit I have seen 3 times in the last week where Explorer was over a gig but if I checked back it would drop down which I was not seeing with openshell installed as it would continuously stack and I would have to force explorer to restart. 

If anyones willing to help me identify the issue despite it not directly being openshell I will gladdly run these test tonight or in the morning as everything I have left installed is either very well maintained or hardware related software/drivers so being able to identify who's at fault would save my butt as I never expected this again on the new build.

**Comment by Dracrius** [comment]
Sorry it took me quite some time to get around to dumps but I did them for both machines.

https://drive.google.com/file/d/1MyB1R2SUWlQ_2gGK9ajfOAsVUB1c8kfk/view?usp=sharing

https://drive.google.com/file/d/1q4zDZHxkrYEchdnZB5BDBwpeyudAU777/view?usp=sharing

If anyone can identify whats causing explorer to grow on me you'd be a life saver haha

**Comment by bonzibudd** [comment]
@Dracrius 

I would recommend doing the ETW trace described [here](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-obtain-ETW-trace). Note that this file will contain any sensitive data you may have, so you may want to get in contact with a member of the Open-Shell team directly to handle the file.

**Comment by ge0rdi** [comment]
For memory leak diagnostics ETW tracing has to be configured differently. There has to be heap tracing enabled for given process (`explorer.exe`) and the trace will be quite big.

But as it was already mentioned, this issue is not very likely caused by `Open-Shell`.

**Comment by bonzibudd** [comment]
Oh, ok. Thanks for clarifying.

**Comment by ale5000-git** [comment]
It happened to me that spatial audio setting of Windows 10 leak memory indefinitely when watching youtube and disabling that fixed it.

I suggest to try it before everything else.
