### ISSUE TITLE
Open-Shell Menu on newer versions of Windows 10 does not show results from the Settings app.

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#358]
Open-Shell and Classic Shell on newer versions of Win10 (After 2016 or so) does not reflect the "Search Settings" toggle when searching for modern settings. This is a pretty big usability issue and I hope that it is able to be fixed. I draw a comparison to StartIsBack++, where this option still works in new Windows 10 versions, however I don't use StartIsBack for many usability issues.

**Comment by ge0rdi** [comment]
This is known issue.
See #57.
