### ISSUE TITLE
Add GUI option to change Start button fade/hover speed

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#360]
If you use a custom button with this ability, it always fades at a constant speed regardless of your Windows "Animations in the Taskbar" preference.

**Comment by CTVCAM8** [comment]
That's a good option to have added.
Also, there is the Animated Buttons tutorial that can do the same thing: 

http://www.classicshell.net/tutorials/buttontutorial.html

One doesn't need to have tens to hundreds of frames for the animation button to work.
Any 3 state start button will work the same way, as long as the image has one-pixel extra horizontal line code added to the original image.
It can be instant change between states or super long change.

I'm uploading a fast state change transparent sample button. I don't know if it will appear correctly on this page or not.



![Instant for large taskbar](https://user-images.githubusercontent.com/44127216/83309455-2a137d80-a1be-11ea-8f42-1579222a905d.png)

Here's what the pixel line looks like up close:
![Zoomed  in top added linein](https://user-images.githubusercontent.com/44127216/83309511-53cca480-a1be-11ea-8d3c-25007bd93191.png)



If it does, copy the top 1-pixel line and add to any start button to get instant change.
If any of those pixels are altered in brightness/color, then it won't work anymore.

If that button can't be used, 
there are the same fast action coded pixel line buttons in the Inspirat start menu/start button zip to play with:

http://classicshell.net/forum/viewtopic.php?f=17&t=8541

**Comment by bonzibudd** [comment]
I'm closing this for now. I don't think it's much of a priority anymore.
