### ISSUE TITLE
Taskbar Volume icon Right-Click Context Menu: Volume Mixer should open PC Settings Mixer

### ISSUE THREAD

**Issue by Nicholas-Steel** [Open-Shell/Open-Shell-Menu#362]
**Is your feature request related to a problem? Please describe.**
The legacy Volume Mixer has various issues I've clearly explained here https://old.reddit.com/r/pcgaming/comments/gu2vsx/the_qol_suggestion_about_exiting_the_game_from/fsht9pa/

**Describe the solution you'd like**
Make the context menu open the PC Settings Volume Mixer UI instead of the legacy Volume Mixer UI. The PC Settings version does not suffer the problem and behaves like you'd expect.

**Comment by NebelNidas** [comment]
I think that's out of scope for a start menu replacing program like Open Shell, I don't even think that's possible to change without redirecting all the calls to open the classic one to the new one through some registry tweaks (similar to how Microsoft redirects many of the old Control Panel links to the new Settings).
I would tell Microsoft about this in the Feedback Hub App. MS will replace the old dialogues either way, if enough people upvote your request, maybe it will get done sooner.
If you really can't wait for this to be implemented by MS themselves, you can make an app yourself. Let it run in the SysTray, give it the same icon as the default one, let it run _sndvol.exe -f_ when clicked (opens the volume slider), and add a context menu entry pointing to _ms-settings:apps-volume_, which opens the new Volume Mixer. Voilà!

**Comment by blackcrack** [comment]
@NebelNidas Julian, the Volume Mixer is not Part of Open-Shell !!

Please Close you Issue !
(by side of the "Comment Button !")

**Comment by NebelNidas** [comment]
>Julian, the Volume Mixer is not Part of Open-Shell !!

Yeah, I know this, and I already told him that above:
> I think that's out of scope for a start menu replacing program like Open Shell

 I only gave him some tips on how to solve the problem himself.

**Comment by blackcrack** [comment]
i meant Nicholas-Steel, sorry, update post..
