### ISSUE TITLE
When dragging/moving a menu item, replace/skip dialogue box is obscured

### ISSUE THREAD

**Issue by VilcxjoW** [Open-Shell/Open-Shell-Menu#368]
Description: When dragging/moving an item in OpenShell's menu between folders/sub-folders when the target folder already contains that item, a dialogue box "Replace or Skip Files" warns that the target folder already contains a file named ... and asks whether to replace or skip the file. However, this dialogue box is not "on top" and so is partially obscured by the Open-Shell menu itself. The user has to drag the dialogue box aside, in order to get at its action buttons.

To Reproduce:
1. Put a file (e.g. "Acrobat Reader DC" shortcut) into the OpenShell "Programs" menu folder, and a copy of that same file(name) into a subfolder within the OpenShell "Programs" menu folder.
2. Click on the OpenShell "start" button on the toolbar
3. Drag the file from the OpenShell "Programs" menu into/onto the subfolder
4. See how the "Replace or Skip Files" dialogue box is not "on top", but is obscured by the OpenShell menu with cascaded sub-menu.

Expected behaviour:
I would expect the  "Replace or Skip Files" dialogue box to be "on top"/in front of of the OpenShell menu, so that it (and its action buttons) are completely visible. That was the behaviour in the original "Classic Shell".

Screenshot: 
![open-shell menu drag defect](https://user-images.githubusercontent.com/66475842/83878170-a1538f00-a733-11ea-8423-a63cb0f912ed.png)

**Version:**
 - Open-Shell: 4.4.142
 - OS: Windows 10 2004

**Comment by ge0rdi** [comment]
Please, try with [latest nightly build](https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts).
It should be fixed already.

Related to #257.

**Comment by VilcxjoW** [comment]
Thanks, I confirm the issue is indeed fixed in 
![open-shell  issue#368 fixed](https://user-images.githubusercontent.com/66475842/83941647-e08de880-a7e4-11ea-9c86-74da6bbfbe51.png)
v4.4.143
