### ISSUE TITLE
Fix the handling of Jump lists for modern applications

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#375]
Classic shell handles modern jump lists strangely, it often shows items, but with no icons. Whenever you try to click them it opens a window saying that it can't find the location (Which seems to be indexed). I don't know if this is something that can be easily altered in terms of behavior, but I hope that at the least, the option can be completely disabled for modern apps. I apologize if this is a known issue, I didn't see it while searching.

**Comment by bonzibudd** [comment]
Another thing I noticed was that it seems to do the same for Microsoft Office applications. I believe this has something to do with some cached locations that Windows no longer uses or indexes.

**Comment by NebelNidas** [comment]
>  it often shows items, but with no icons

Do you mean something like this?
![image](https://user-images.githubusercontent.com/48808497/86038455-3d299f80-ba41-11ea-8050-417c90e157b0.png)
In this case, there are icons, but they are barely visible because the icons are white. And white on an almost-white background is barely visible...
The default Win10 start menu handles this better:
![image](https://user-images.githubusercontent.com/48808497/86038554-69452080-ba41-11ea-80ed-a8b1325c90a7.png)

I don't know if Win10 just inverts the colors accordingly or grabs different ones altogether based on what the application's manifest says, but this is definitely something the Open-Shell team should also look into.

**Comment by bonzibudd** [comment]
@NebelNidas no, my issue is different than this. I have currently experienced the problem on most built-in UWP apps, and additionally it seems to happen in Excel sometimes as well. The text for the list items appears normally, but it shows a blank default icon beside of it. When you click the list item, it shows a dialog saying "Windows is searching for......." and it never opens, sometimes it fails instantly. I have tried this on multiple systems and VMs with standard indexing enabled, so I have come to the conclusion that it is because of a change in Windows. Many standard x86 apps work fine, however.

I will try to post an image of the problem when I have the chance.

**Comment by bonzibudd** [comment]
![image](https://user-images.githubusercontent.com/61938331/86515401-a1a08200-bde6-11ea-8950-058513573bd8.png)

This is what it looks like in the menu, and the error message that it gives.

**Comment by NebelNidas** [comment]
I was able to reproduce this issue in the latest Open Shell (4.4.152) and Windows 10 2004.

Expected default behavior:
![image](https://user-images.githubusercontent.com/48808497/92882514-499e8100-f410-11ea-8e86-1ad2713dc2a9.png)

The visible links open the app and perform the corresponding task.

---

Open Shell:
![image](https://user-images.githubusercontent.com/48808497/92882745-7f436a00-f410-11ea-8a87-0026a2ec798b.png)

Note that the recently used items still show up. However, no preview images for the tasks are loading, and when clicking them, following "Shortcut not found" window pops up:
![image](https://user-images.githubusercontent.com/48808497/92883314-05f84700-f411-11ea-9a3e-035dfdfc82b6.png)

(Sorry, my Windows is German)

After waiting around 10 seconds, Windows finds nothing:
![image](https://user-images.githubusercontent.com/48808497/92883623-553e7780-f411-11ea-972d-5341cda348a0.png)

**Comment by bonzibudd** [comment]
@NebelNidas That's exactly it. Do you think this can be looked into to be fixed? For me, this is one of the only big usability issues in Open-Shell. I wouldn't even mind just having UWP Jump lists disabled, for however long it might take for a real solution to be put into place.

**Comment by NebelNidas** [comment]
I'm unfortunately not very familiar with Open Shell's codebase nor with C++ in general (currently learning it, though). So for the moment we have to hope that one of the maintainers (@ge0rdi or @coddec) finds the issue... 🤷‍♀️

**Comment by ge0rdi** [comment]
I can confirm that `Open-Shell` cannot handle `Tasks` category jump lists for modern applications.
System returns them as `IShellLink` items and `Open-Shell` just doesn't support that.

I'll try to have a look at it eventually.

**Comment by ge0rdi** [comment]
Gyus, please, try build from PR #461.
It should fix modern app jump-lists.

**Comment by bonzibudd** [comment]
@ge0rdi 

Just installed, seems to work as intended!
![image](https://user-images.githubusercontent.com/61938331/93824470-7f720f80-fc31-11ea-8ed8-7e6589f2118e.png)

I haven't tried 7 yet. I think I will try it when all of the new fixes have been merged to an actual nightly build.

**Comment by bonzibudd** [comment]
@ge0rdi I noticed that this build doesn't seem to have any of the fixes for the "Modern" search. Is this to be expected from a stand-alone build? If it matters, I uninstalled the old version and installed the new one from the .exe installer.

**Comment by ge0rdi** [comment]
@bonzibudd 
Build from PR contains everything from master (so yes, the Modern settings search feature is there), plus new functionality that is being reviewed.

It is not meant for daily usage, just for checking whether given new functionality works.
Sorry, I should've put proper disclaimer there (will try to keep it in mind for the future).

Though I'm glad that it works also outside of my machine(s) :)

**Comment by ge0rdi** [comment]
Latest nightly build (4.4.155) contains the change.

**Comment by NebelNidas** [comment]
Thanks! But what about the white-icon-on-white-background issue I commented about in my [first comment](https://github.com/Open-Shell/Open-Shell-Menu/issues/375#issuecomment-651269707) above? Should I create a new issue for this?

**Comment by ge0rdi** [comment]
> Should I create a new issue for this?

Yes. Please, create new issue.
The same issue is with Modern settings (in search, or if you'll pin them to start menu).

Currently I don't know what to do with it :(

**Comment by bonzibudd** [comment]
@ge0rdi I don't know if this is related, but I noticed that the Settings app unnecessarily displays a list area, only for it to show as (Empty). Is there an easy fix for this?
![image](https://user-images.githubusercontent.com/61938331/94350206-08b28900-001a-11eb-94e0-d9fac4bc0b92.png)
I didn't notice this on any other app. 

Also, I think the ability for modern Jump list items to be dragged and dropped should be removed. If you wanted to try and open them from the dragged location, you get this error:
![image](https://user-images.githubusercontent.com/61938331/94350365-9f337a00-001b-11eb-8d04-94e07ccb379e.png)

**Comment by ge0rdi** [comment]
@bonzibudd 
> I don't know if this is related, but I noticed that the Settings app unnecessarily displays a list area, only for it to show as (Empty). Is there an easy fix for this?

`Settings` app reports one category of jump list. So `Open-Shell` thinks that it should show jump list.
But when actual list is expanded, we'll notice that this category is of unsupported type and skip it. Thus it will result in empty jump list.

I guess we can just report no jump list for `Settings` app (based on AppId).
Will do that sometime.

> Also, I think the ability for modern Jump list items to be dragged and dropped should be removed. If you wanted to try and open them from the dragged location, you get this error:

Please, create separate issue for that.
Jump list tasks are in fact _links_ so in theory it should be possible to create standalone shortcuts to them.
If that won't be possible, we can consider disabling drag&drop for them.

**Comment by anonimuos** [comment]
I am on 4.4.169 currently. The jumplist icons show but are poorly rendered/scaled. Here's a screenshot.

![image](https://user-images.githubusercontent.com/46422834/129785451-d309bbd4-9236-4c23-93d8-a390a4439b30.png)
