### ISSUE TITLE
I need some help on a few configuration settings.

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#376]
I would post this on the Classic Shell forum, but it seems that the sign-in system is broken. Anyway, I have a few things that I have been unable to find the configuration setting in the .skin7 file. I have looked in the skinning tutorial and haven't found the options, but I'm sure they exist. Here are the settings I wish to change:
1. Removing/changing position of the "separator" line above the "All Programs" button.
2. Changing height/padding of search box (not the padding of the area around it, could be related to slices)
3. Removing the line beside of the header in the Jump list
4. Same as 3, but when searching for an item (may be same option)
5. Changing icon beside "See more results" button in Search view
6. Changing/removing light border around Shut Down button (I don't think it is in the bitmap)
7. Removing separator between Main and Main2 (This is in the tutorial but I couldn't find the option in the skin)

I appreciate any help with this, and I apologize if this isn't a good place for it (again, I couldn't sign in to the Classic forum). Hopefully this can help other people who are looking for some of the same things in CSM and OSM.

**Comment by CTVCAM8** [comment]
Hi @bonzibudd
Yes, looks like Classic Shell forum stopped new forum members a couple of years ago, 
and the site has reduced bandwidth for the number of users online.
I'm still thankful the original developer has kept the site up,
as I've uploaded a number of ported skins to his site in the last couple of years.
Thanks for @coddec in 2017 for making a Github backup archive of the forum,
for using when the original CS site is slow or removed permanently.

It would be great if the skinning tutorial, 
or a similar reference guide in Github could be made and continually updated to serve coders and the general public.
There are a lot of things I can't figure out as well, so you are not alone. :)
In general, if there is not text and images that override a setting in the original skin file, then the software code is the master. :) 


Woah, so many questions that look simple to answer, but depend on what base .skin7 is being modified.

Some of those separators will automatically show the chiseled (semi-transparent dark top line with light line below) type even when there is no text and image in the file.


Another scenario is if say there is only text and horizontal separator image for Main_separator,
and no other text/image for the other separators Main2_separator and List_separator (jump & search views) in the file.
What happens is those other separator locations automatically copy and show the same Main_separator image
(Inherits from Main_separator)

(3&4) If you just want to have a more open look for just the List_separator, copy the Main_separator image
and make it almost invisible (1/255 alpha) in your favourite image editor. Unless one has very sharp eyes 1/255 won't be noticeable.
For simple stuff like this, 
I use Pixelformer program as it is easy to see the alpha channel apart from the RGB channels.   
Why 1/255A? From experience, sometimes if an image is 0/255 alpha, the separator will display as a big opaque black block in the start menu.
Add the modified image to the skin file as a new resource along with text with its splicing dimensions etc, for List_separator 



(7)Sometimes to stop the vertical separator between Main and Main2 from displaying 
can be as simple as adding "0" or "none" 
in place of the image reference number:

from 
Main_separatorV=125
Main_separatorV_slices_Y=10,3,10 

to
Main_separatorV=0


If it's the "Classic.skin7" file, I never figured out the magic word or number to use
and had to use a real invisible image and text to override the separator from showing.
I believe it also has to do in that the skin does not use "Main_opacity" text and follows Windows os code.
I've heard with a little hacking in Windows 10, the Classic.skin7 can display transparent Acrylic noise/blur.

If it's the "Metro.skin7" file, that vertical separator is right on the Main_bitmap_mask and Main_bitmap_jump_mask images.
To make those disappear, one would have to edit them out in an image editor.


(1) There does not appear to be any way of changing,
or deleting the Main separator above the "All Programs" button in the "Customize Start Menu" settings tab.
That is a good question for a coder. :) 
All we can do is increase the vertical height or/and make invisible the actual Main_Separator image.



(5)[Changing icon beside "See more results" button in Search view]
That's a good coder question as well. I think the start menu pulls the icon from Windows. 

I only changed a different image "More_bitmap" on the right side of the search view years ago.
by changes in the skin file from More_bitmap=none to More_bitmap=0 or to a real image More_bitmap=26 
or More_bitmap=  which shows the same magnifier image as the "See more results" area.

Funny, I never noticed before. 
The "See more results" magnifier icon changes to a different searching icon 
then switches back to just the magnifier.
It is a good indicator of when the search has finished. 

![Busy searching](https://user-images.githubusercontent.com/44127216/84604202-2718be00-ae49-11ea-947e-97b49b48126e.png)

(6)[Changing/removing light border around Shut Down button]? 
Need to know which skin or a show a screenshot.
The 3 stacked button image/bitmap can be altered in an image editor.


(2)[Changing height/padding of search box (not the padding of the area around it, could be related to slices)]
For inside the box, it's all about the slices. Font size and display size affect the box size as well.
Looking at the Metro "Search_background_mask=13" the vertical slices are "Search_background_slices_Y=5,1,3, 0,4,0, 2,2,3",
the stretching area is the 4 number along with a 2 pixel non stretching area above and below.

![Metro Search background slices](https://user-images.githubusercontent.com/44127216/84604222-41eb3280-ae49-11ea-844c-8430678d1a5e.png)

To make even bigger box height change text to "Search_background_slices_Y=5,1,4, 0,2,0, 3,2,3"
For making the box shorter do the opposite text like "Search_background_slices_Y=5,1,2, 0,6,0, 1,2,3"
Going smaller like "Search_background_slices_Y=5,1,1, 0,8,0, 0,2,3" makes the exit button size start to overlap the box border.

Let us know what skin you are working on to see if Item (6) can be changed.

**Comment by bonzibudd** [comment]
Hey @CTVCAM8, thanks for all the info! I will definitely be applying this info to the skin that I'm working on.

I realized that (6) was a bit redundant since it varies with each skin, the one that I am using is the "Metro" style (I am attempting a Windows 10 Technical Preview/Non XAML layout menu with my own twist). Now that I am more familiar with slicing, I might be able to figure it out, but it's still somewhat confusing. Thanks for all the help!

**Comment by CTVCAM8** [comment]
If it's to make the "at rest" shutdown button rectangle lines disappear,
it's the top portion of the 3 part button that needs altering. 
Be aware the Metro skin has two shutdown button images.

![Make resting shutdown button invisible](https://user-images.githubusercontent.com/44127216/84607254-196f3280-ae61-11ea-811a-35f54fa6c115.png)


Oh yeah, that search box area has so many splices and padding adjustments to figure out,
it causes a lot of head-scratching. 
The Metro is a lot simpler in one area as there is not a dark grey border or special menu colors like on the Aero skin.

About changing the "See more results" icon.
Not that I know anything about coding, 
it makes me curious as to whether there is some text setting words that stick out in the SkinManager.h file?
I'm going to do a look-see when I have some time.
Bye
