### ISSUE TITLE
UWP Apps that can be launched as an admin cannot be pinned.

### ISSUE THREAD

**Issue by dustojnikhummer** [Open-Shell/Open-Shell-Menu#378]
**Describe the bug**
UWP/Store Apps that can be launched as an admin cannot be pinned. Apps like Facebook Messenger, Spotify, Windows Terminals and games like Gears Tactics cannot be pinned to the Classic Start Menu (the context menu just is not there). Apps like Netflix or Forza Horizon 4 can be pinned.

Try to pin Store version of Spotify.

**Expected behavior**
Pinning of all UWP/Store apps

**Screenshots**
https://imgur.com/a/8sibbLO

**Version:**
 - Open-Shell: 4.4.142
 - OS: Windows 10 1909 18363.900

**Comment by ge0rdi** [comment]
Try latest [nightly build](https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts). It should work now for desktop packaged applications.
