### ISSUE TITLE
From Contact form: [Question] Function, Trigger for search in open-shell

### ISSUE THREAD

**Issue by coddec** [Open-Shell/Open-Shell-Menu#380]
> Hi! Me and a friend are trying to modify the search function in OpenShell to use the software Everything (From VoidTools, the SDK of it). We can't seem to find the actual function that executes when you search for something to integrate our own code, so if you could give us a lead on how your code works, it would be really helpful.

**Comment by ge0rdi** [comment]
Search is done in `CSearchManager::SearchThread` function (`Src/StartMenu/StartMenuDLL/SkinManager.cpp`).

Best way of integrating anything to search is to create _virtual shell folder_ that will provide searched items.
You can see similar thing being done in this [commit](https://github.com/Open-Shell/Open-Shell-Menu/commit/0da20180ac440f4fc9a65985d075c859601e88bc).
