### ISSUE TITLE
From contact form: [Question] What is datacache.db file? What does it store?

### ISSUE THREAD

**Issue by coddec** [Open-Shell/Open-Shell-Menu#381]
> Good afternoon, My name is (name removed for privacy), I'm a forensic analyst and long time fan of Classic Shell. In a recent case, I have found evidence via strings in the 'datacache.db' file that is auto-generated by Classic Shell; however, I have no way of parsing this database and no understanding of how it gets built and written to. Do you understand the way that the database is written after having built Open Shell, and if so have you found a way to parse the database file and analyze it? I have tried a few methods but none of them seem to work... Any suggestions? Thank you for your time, hope to hear from you soon. (name removed for privacy)

**Comment by ge0rdi** [comment]
Have a look at [CItemManager::LoadCacheFile](https://github.com/Open-Shell/Open-Shell-Menu/blob/master/Src/StartMenu/StartMenuDLL/ItemManager.cpp#L3148).
This function reads data from the file.
