### ISSUE TITLE
Windows 10 build 2004 possible issue

### ISSUE THREAD

**Issue by StephKoenig** [Open-Shell/Open-Shell-Menu#382]
**Describe the bug**
Explorer/start menu and other apps can become unresponsive along with other app when started.

**To Reproduce**
Kicks in a few minutes after booting and messing about in windows. There are no useful notifications in the windows error logs.

**Version:**
4.4.142
- OS: [e.g. Windows 10 2004]

**Additional context**
Open Shell did correctly fire it's new OS configuration dialog and did report update success on completion.

This may not be Open Shell at all but I recognise the symptoms from Classic Shell. With CS some major Windows updates would cause this sort of hanging, explorer crashes and unresponsiveness of the taskbar/start menu etc.

If I uninstall Open Shell I don't seem to have those issues. 

Also I know there's some funny business with Chrome and b2004..

**Comment by jtblsngm** [comment]
I'm also having these issues. Explorer/start menu/task bar/apps become completely unresponsive on startup of the machine or randomly a few minutes after startup. 

Sometimes killing then restarting Windows Explorerixes it, but it isn't guaranteed. 

The Windows lock screen is also unresponsive to mouse clicks (but fine with keyboard input) on startup whenever this happens.
Started noticing it a few weeks back while on Windows 10 1909. Upgraded to Windows 10 2004, problem persists. 
Uninstalling Open Shell has fixed it.

**Comment by SoerenBusse** [comment]
We've seen the same issue on our computers. Did you find a solution for this issue?

**Comment by StephKoenig** [comment]
I've uninstalled whilst the build 2004 issues got ironed out as I wante dot narrow down issues we were seeign on our rigs.. I'll reinstall it and see...

**Comment by pheonixfirewingz** [comment]
I'm on the latest build of windows and this is not an issue. Windows 10 Pro 20H2 19042.487 (insiders build)
