### ISSUE TITLE
Default Windows 10 Menu

### ISSUE THREAD

**Issue by Internet-Anon** [Open-Shell/Open-Shell-Menu#383]
An option to not change the default windows 10 menu would be nice. I am currently using this to customize the taskbar and would like if the menu would not change as I prefer the default menu.

**Comment by ge0rdi** [comment]
You can configure such behavior in `Settings -> Controls`.
Just select `Windows Start Menu` for keys/buttons that trigger start menu.

**Comment by Internet-Anon** [comment]
I did not notice that. Thank you so much!
