### ISSUE TITLE
Doesn't respect system-wide theme preference

### ISSUE THREAD

**Issue by JamesYeoman** [Open-Shell/Open-Shell-Menu#386]
I have Dark Theme enabled on Windows 10, and the Classic Shell theme is jarring and it's clearly an addon to the shell as a result, rather than fitting in seamlessly

Here's a screenshot
![image](https://user-images.githubusercontent.com/21042602/85343162-0f45d780-b4e4-11ea-8e5e-90faedebfe1f.png)

**Comment by glowingwire** [comment]
I believe that is controllable in settings

**Comment by NebelNidas** [comment]
Duplicate of #361.
