### ISSUE TITLE
Win10 (1909): on-screen-keyboard hides Open-Shell-startmenu

### ISSUE THREAD

**Issue by ruby-os** [Open-Shell/Open-Shell-Menu#391]
Hello,

can you please help me with following issue:
I have installed Open-Shell on a tablet (Microsoft Surface Go 2). It's working properly but if I open the on-screen keyboard it hides the Open-Shell-menu so I only can see the keyboard but not the Open-Shell-startmenu. With another tablet (Acer, Win8) open-shell jumps upon the on-screen keyboard when I open it so I can see what I'm typing in Open-Shell.
How can I change this für my Win10-tablet?

Thanks for all ideas!

ruby

**Comment by blackcrack** [comment]
für.. ja klar *bg*, it names "for my Win10.."
let'z coll the programmer ;)
@ge0rdi, @coddec , do you have a clue ? 

best
Blacky

**Comment by ruby-os** [comment]
Und was sagt uns das jezt? Sorry, bin vielleicht etwas begriffstutzig ...

**Comment by blackcrack** [comment]
dass wir warten bis jemand von den zwei sich regt.. die sind vielleicht auch in urlaub.. oder flachgelegt wegen covit..

**Comment by ge0rdi** [comment]
I guess this is duplicate of #390 .
So I'm closing this one.
