### ISSUE TITLE
Add "Apply" button on settings window

### ISSUE THREAD

**Issue by stdedos** [Open-Shell/Open-Shell-Menu#392]
**Is your feature request related to a problem? Please describe.**
When I am tinkering with Settings, pressing "OK" to apply then (and then needing to restart the Settings window) is painful

**Describe the solution you'd like**
Add Apply button

**Describe alternatives you've considered**
None. There are none

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by ge0rdi** [comment]
Most of settings are applied directly when changed.
You should see the change immediately (without pressing `OK`).

**Comment by stdedos** [comment]
Oh, I see! Somehow it didn't occur on me to re-open the start menu (except e.g. when changing colors).

If it's easy to keep start always-open while configuring the settings (so as to clearly demonstrate what you said) would be nice, otherwise, I am fine closing this as-is.

By the way ... How is it possible to kill _and restart `explorer.exe`_, with all folders re-opened?!?
Is it somehow possible to "extract" that save/restore functionality as a standalone dll/exe?

**Comment by ge0rdi** [comment]
> If it's easy to keep start always-open while configuring the settings (so as to clearly demonstrate what you said) would be nice, otherwise, I am fine closing this as-is.

I think that's not exactly easy :(
Start menu is created every time from scratch. There is no functionality to refresh displayed menu when settings change.

> By the way ... How is it possible to kill and restart explorer.exe, with all folders re-opened?!?
Is it somehow possible to "extract" that save/restore functionality as a standalone dll/exe?

Not sure I understand what do you mean.

**Comment by stdedos** [comment]
> > By the way ... How is it possible to kill and restart explorer.exe, with all folders re-opened?!?
> > Is it somehow possible to "extract" that save/restore functionality as a standalone dll/exe?
> 
> Not sure I understand what do you mean.

Kind of separate topic, but I didn't think an issue was worth starting .. when installing/updating 
OpenShellMenu, explorer.exe needs to be killed. Somehow, the installation is able to restart explorer.exe, along with all previously opened folders. I was wondering if OpenShellMenu is somehow involved in this or it's just an installer gimmick

**Comment by ge0rdi** [comment]
> I was wondering if OpenShellMenu is somehow involved in this or it's just an installer gimmick

MSI handles that automatically. So no special support on `Open-Shell` side.
