### ISSUE TITLE
add dark mode !!!!!

### ISSUE THREAD

**Issue by thanasis299** [Open-Shell/Open-Shell-Menu#394]
It would be nice to have a dark mode for the windows 7 look of the menu

**Comment by CTVCAM8** [comment]
There is a skin "Windows Aero Dark" that I made for @radzo73 that was based on the original "Windows Aero" skin.
It has all the white menu views changed to dark greys. 

It's on the Classic Shell site:

http://classicshell.net/forum/viewtopic.php?f=17&p=36403&sid=5c6ebc3e65083051e59b603fcea446b9#p36403


![Windows Aero Dark revC](https://user-images.githubusercontent.com/44127216/86499977-eb379100-bd42-11ea-8743-511f461736ac.png)

**Comment by CTVCAM8** [comment]
Turning on/off "Reduce glass color" skin option
as well as "Enable menu glass", "Override glass color" and "Glass opacity"(0-100) combinations in "Menu Look" settings tab
can show different 2nd column looks.
Such as brighter at the top(Vista), or more color at top/bottom, blur transparency, dark transparency, and opaque.

**Comment by WSLUser** [comment]
Change this to "use system mode". So if Light Theme is enabled, OpenShell uses it. if Dark Mode is enabled, that is used instead.

**Comment by blackcrack** [comment]
take that skin man ... this nice proggy have skins and you have possible to use different skins and not the MS-Own..
you should e happy about it.. or make you own skin if's not fit..

**Comment by ge0rdi** [comment]
I think we can close this as _dark mode_ can be achieved by using proper skin (as provided in comments).

**Comment by WSLUser** [comment]
I think being able to use the system along with custom skins would be better. I'm not satisfied with existing skins that ship with OpenShell for Dark Mode. Most Windows applications can use the system mode or explicitly set Dark Mode or Light Mode from the OS. This one should too.

**Comment by CTVCAM8** [comment]
Couldn't the "Classic" .skin and "Classic".skin7 be developed more for this auto system mode, 
as these are basically invisible or empty canvas menus that rely on system colors? 
These days Classic skins are only good for High contrast themes or light grey color on Windows 10. 
I've seen a screenshot of the classic skin with the acrylic look, so anything is possible with Classic skins.
There was some Win10 os hacking involved to get the skinner's screenshot.

![Acrylic look](https://user-images.githubusercontent.com/44127216/91369913-d23ae180-e7c1-11ea-917c-0792112f91c6.png)
