### ISSUE TITLE
They take the name of Classic Start menu

### ISSUE THREAD

**Issue by blackcrack** [Open-Shell/Open-Shell-Menu#399]
@Ibuprophen 
@ge0rdi 
@coddec 

https://www.softpedia.com/get/Desktop-Enhancements/Shell-Replacements/CSMenu.shtml
http://www.classicstartmenu.com/

this is also to have a better Homepage.. this 
https://open-shell.github.io/Open-Shell-Menu/
css page only is crap/bull..beep !

**Comment by Ibuprophen** [comment]
Isn't that something... Has anyone tried reaching out to Softpedia? 


~Ibuprophen

**Comment by blackcrack** [comment]
that is not a thing of Softpedia,
this is the domain and the name of Classic Start Menu 
and also the domainname of them "classicstartmenu.com"

**Comment by ge0rdi** [comment]
This software does exist for long time.
It was also one of reasons to pick `Open-Shell` name (to not clash with it).

More details in #36.
