### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by sydbarrett74** [Open-Shell/Open-Shell-Menu#40]
@XenHat 
This isn't an 'issue' _per se_, but I just wanted to thank you for taking this project over. I look forward to good things happening in future.

I didn't know how else to express my sentiment since GitHub disabled PM's.

**Comment by ibuprophen1** [comment]
Just a friendly heads up @sydbarrett74... 

@XenHat, @coddec and @ge0rdi are the 3 Developers/Maintainers for this project and I know that you feel the same way as myself and many others do regarding their Continued Development, Support, Guidance and more! 


~Ibuprophen

**Comment by XenHat** [comment]
@sydbarrett74 You're welcome. I've been using Classic Shell for years now and I'm quite delighted to be able to improve upon it.

We do not have PM on GitHub, but we have chat rooms on Gitter: https://gitter.im/passionate-coder/Lobby

**Comment by Clintlgm** [comment]
Yea keep up the great work lots of us out here very happy about this.
