### ISSUE TITLE
Add "-exit" parameter for command script compatibility

### ISSUE THREAD

**Issue by taskkill-f-im** [Open-Shell/Open-Shell-Menu#402]
Hi, 
Not really an issue, perse. More like a nice feature.
It would be nice to have a parameter like "-exit" similar to how Classic Shell used to have it.
I am working on a custom windows iso right now so it would be nice to have this available as a command line. As of right now, I am improving my silent install script which involves installing Open-Shell, then importing my Menu Settings xml (not automated, idk how), and lastly exiting and relaunching Open-Shell (automated, WIP). My goal for the last step is to automate the restart since it is nice to just import my xml and let my script do everything else. Even better if I could automate importing the xml in my script as well, though I do not know how.

**Comment by taskkill-f-im** [comment]
My apologies, I was not aware of the "enhancement/feature" filter.

**Comment by ge0rdi** [comment]
There is `-exit` parameter already.

Just run:
`"C:\Program Files\Open-Shell\StartMenu.exe" -exit`

It will _exit_ `Open-Shell` menu.

**Comment by taskkill-f-im** [comment]
Huh, I tried it before and it didn't work. Maybe I need to update it. I
already figured out how to do the powershell script once I figured out how
to import an xml file via command line. Thanks for the help.
