### ISSUE TITLE
Settings localization?

### ISSUE THREAD

**Issue by altwarg** [Open-Shell/Open-Shell-Menu#406]
**Describe the bug**
Settings for Open-Shell Menu are not localized

**To Reproduce**
1. Set custom language for Open-Shell
2. Check language by clicking on the Start button - Start menu will be localized
3. Reopen Settings for Open-Shell Menu
4. Settings will still use English

**Expected behavior**
Not only Start menu but also Settings must be localized

**Screenshots**
![image](https://user-images.githubusercontent.com/34391398/88617747-12faea00-d0a0-11ea-81f7-f25e2a9a6535.png)

**Version:**
 - Open-Shell: 4.4.142
 - OS: Windows 10 Build 2004

**Comment by ge0rdi** [comment]
You need to download localization DLL manually.
See https://coddec.github.io/Classic-Shell/www.classicshell.net/translations/index.html.
