### ISSUE TITLE
Repeated "blacking out" of desktop, followed by crash of explorer.

### ISSUE THREAD

**Issue by CLBrown66** [Open-Shell/Open-Shell-Menu#408]
With OpenShell, and Windows 7 x64, I repeatedly (and apparently without specific cause) get the following error.  (Info taken from my Windows Application Log.)

******************************************************
Faulting application name: explorer.exe, version: 6.1.7601.23537, time stamp: 0x57c44efe
Faulting module name: StartMenuDLL.dll, version: 4.4.142.0, time stamp: 0x5db490fe
Exception code: 0xc0000005
Fault offset: 0x000000000007bcb7
Faulting process id: 0x%9
Faulting application start time: 0x%10
Faulting application path: %11
Faulting module path: %12

******************************************************
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-07-30T19:45:48.000000000Z" /> 
  <EventRecordID>34106</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>CarysMainPCWin7</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>explorer.exe</Data> 
  <Data>6.1.7601.23537</Data> 
  <Data>57c44efe</Data> 
  <Data>StartMenuDLL.dll</Data> 
  <Data>4.4.142.0</Data> 
  <Data>5db490fe</Data> 
  <Data>c0000005</Data> 
  <Data>000000000007bcb7</Data> 
  </EventData>
  </Event>
********************************************************************

This never occurs without OpenShell (or 4.2+ versions of "Classic Shell") running, it seems.   I have no issues running, say, Classic Shell 3.5.

I suspect, based upon timing (of the bug appearing in ClassicShell) and the issue reported above (StartMenuDLL.dll causing Explorer to crash) that something was done within that DLL to fix an issue with Windows X, and this "fix" caused a problem with Windows 7.

The visual manifestation of this error is that, first, icon backgrounds change to black, then the full icons, then the desktop... then the taskbar either becomes black, or crashes (in either case, it's invisible and impossible to interact with alongside its invisibility, so it's effectively the same thing).   If I kill OpenShell (using the task manager), the display comes back to "normal" in roughly a minute.  If I don't kill OpenShell, the display almost always remains "blacked out" indefinitely.

I've been seeing this for a while now...  even removed OpenShell for an extended time, though I really miss the functionality and clean-reinstalled it (only to find the problem recurring).

**Comment by ge0rdi** [comment]
If you can replicate those crashes, please follow [How to create dump on Windows Explorer crash](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-create-dump-on-Windows-Explorer-crash) guide and provide crash dump here.
