### ISSUE TITLE
Windows Security Shortcut Broken + Workaround

### ISSUE THREAD

**Issue by DerekZiemba** [Open-Shell/Open-Shell-Menu#409]
**Describe the bug**
Windows Security shortcut does not appear in the start menu
![Gif of WIndows Security not showing](https://i.imgur.com/zUzhxQS.gif)

**Workaround**
Edit the Command from `windows_security` to `shell:Appsfolder\Microsoft.Windows.SecHealthUI_cw5n1h2txyewy!SecHealthUI`

**Version:**
 - Open-Shell: 4.4.142
 - OS: Windows 10 Education v1909

**Comment by bonzibudd** [comment]
I think you are confused. The security item is for Remote Desktop sessions only. This is separate from the Windows Defender application.
