### ISSUE TITLE
Feature Request: Behavior of start menu click vs Win key

### ISSUE THREAD

**Issue by musicman281** [Open-Shell/Open-Shell-Menu#410]
**Is your feature request related to a problem? Please describe.**
When accessing the start menu via mouse click, the expected Win XP style start menu appears. However when accessing the start menu via the Windows Key (or by tabbing to highlight the start menu button + Enter button), the old Win 10 start menu appears. As an assistant to a totally blind PC user, who is a 100% keyboard user, I can't find a way to make the Win XP menu appear via the keyboard. The current Win 10 start menu is more difficult for the primary user to navigate when compared to Win XP start menu.

Was the current behavior intended to be this way? Is there an existing bug-report/feature-request for this particular behavior?

**Describe the solution you'd like**
Win XP style start menu activated via keyboard.

**Comment by ge0rdi** [comment]
`Win` key is supposed to open `Open-Shell` start menu by default.

You can check it in `Settings` -> `Controls` -> `Windows Key opens`. 
Make sure you have `Open-Shell menu` selected there.
