### ISSUE TITLE
Start menu: Custom scrollbars on Win10?

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#415]
In previous versions of Windows (8,7), Classic shell and Open-Shell used the scrollbar options provided by the skin file. That does not seem to be the case anymore with Windows 10. The scrollbars in all skins look like this:
![image](https://user-images.githubusercontent.com/61938331/89564052-6da3ec80-d7ea-11ea-8f94-6da9f1a15a85.png)
I tagged this as a feature request because I don't know if this is intentional or not.

**Comment by CTVCAM8** [comment]
I've asked for this too, a couple of years ago.
Now if only more than two people (like qty 100) could ask for this feature to work again, then something might happen. :)

Way back when Windows 10 first came out, all 7 style skins could have this feature.
The "Metro.skin7" used to show colored scrollbars. If you look at the skin file you can see the scrollbar section. 
I made some skins that had this feature as well.
Once Creators update came out, Ivo's code got disregarded by Windows 10. :(

**Comment by bonzibudd** [comment]
That's interesting. 

I also found that the scrollbar doesn't seem to have been completely overridden, as it still shows up here, in the search function:
![image](https://user-images.githubusercontent.com/61938331/89732340-1a18e500-da1c-11ea-8f0f-9a7a9bc75392.png)
Since it still appears in the search section, it seems possible that it could be added back.

**Comment by CTVCAM8** [comment]
Hey @bonzibudd 
Good work.

I do believe you have found something important for the coders to ponder on.
Why can Search scrollbar show a skinned scrollbar and only show Windows 10 default scrollbar in programs tree?

This is excellent news. I tried a number of skins that have skinned bitmaps, arrows, etc inside the skin file.
There has to be a small bit of code that's making the skinning info to be bypassed in the Windows 10 programs tree?

![Why does search scrollbar work correctly](https://user-images.githubusercontent.com/44127216/89827207-41e77600-db0c-11ea-8caa-47694a49c97b.png)

**Comment by CTVCAM8** [comment]
There is also another way the programs tree scrollbar can be skinned sometimes.
That is, through a theme that makes use of the UxTheme.
@NebelNidas made me aware of this in this thread (near the bottom):

https://github.com/Open-Shell/Open-Shell-Menu/issues/364 

It bricked my Windows 10. Thankfully a restore point brought my computer back to life. :)

So to get this skinning scrollbar feature working fully again, there has to be code,
I assume in the SkinManager.cpp or  SkinManager.h 
Not a coder, but I can see programs tree and scrollbar code: 

	if (g_CustomScrollbarThread && g_CustomScrollbarThread==GetCurrentThreadId() && hTheme==g_CustomScrollbarTheme)
	{
		CProgramsTree::DrawScrollbarBackground(hdc,iPartId,iStateId,pRect);
		return S_OK;



and further on UxTheme at bottom, more code:

#else
	HMODULE hUxTheme=LoadLibrary(L"uxtheme.dll");
	DWORD ver=GetVersionEx(hUxTheme);
	if (hUxTheme && ver>=0x6020000)


All we need is people who know code to take up the challenge and figure out where it's getting hung up for the internal scrollbar skinning in the program's tree area.
 It's not adding a new feature, it's getting it to work correctly again. :)

**Comment by bonzibudd** [comment]
Yeah, I am aware of Ux theming, I have used it in the past and it generally works well (Sometimes not after updating, but it is what it is). It's almost as good as OSM's and is a viable workaround.

Hopefully this feature will return at some point.

**Comment by ge0rdi** [comment]
Guys, please, try this [build](https://ci.appveyor.com/project/passionate-coder/open-shell-menu/builds/34603536/artifacts).
It fixes theme usage for programs tree window.

And thanks for the hint with properly themed scroll bar in search window. It helped to identify the problem.

**Comment by bonzibudd** [comment]
**Look at that!**
![image](https://user-images.githubusercontent.com/61938331/89939623-41231280-dbe6-11ea-83e8-2f58982217ec.png)

Completely fixed from what I can tell. I didn't expect this to be in place so quickly.
Thanks for the work on keeping this feature alive!

**Comment by CTVCAM8** [comment]
Thankyou @ge0rdi
So happy this is fixed!

Tried on Windows 10 2004-works
I also tried on Windows 8.1 to make sure it still works as usual-Works as before.
Wonder how long it would be before it is a secure stable release to the general public?
I had trouble downloading it on New Edge. Firefox let it download without any security blocking.

**Comment by ge0rdi** [comment]
@CTVCAM8 
> Wonder how long it would be before it is a secure stable release to the general public?

Fix is now in master.
So it is already in latest nightly build.

I will create new official release at some point (need to check changes since last release).
Didn't want to create release for every simple fix.

**Comment by CTVCAM8** [comment]
I understand. Was not trying to speed it up in any way.
The reason I was asking was once it is is an ok release, I see now it is, I will mention in the old Classic Shell forum about new Open_Shell nightly build that fixes the skinned scrollbar.


I see @bonzibudd is having some problem so I'll wait first to see if something develops.
