### ISSUE TITLE
Differentiate "Main" shadows from "Submenu" shadows

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#416]
This would be a very useful option. As it is now, the "Enable menu shadow" switch is the only one which can control shadows, and there is no option to show shadows only in submenus, like in Windows 7, for example. I don't know if this is doable with Open-Shell's engine or if it solely relies on Windows for stuff like this, but I would love to hear some responses.

**Comment by CTVCAM8** [comment]
Actually Menu shadow can be turned on or off independently in a skin file.
Say, if you want to have the main menu as floating(with a big invisible space around it),
add "Main_shadow=0" to stop the main menu shadow from showing in the wrong place. The submenu will still show a shadow.
Ivo used this technique when he made the Metallic skin that has big round corners on the main menu.

Or you could stop submenu shadow and have main menu shadow show by using this text in the skin file:
Main_shadow=1
Submenu_shadow=0
I guess coders could be able to take these skin engine instructions and put them in global settings?

**Comment by bonzibudd** [comment]
Oh wow, I guess this completely went past me. This is basically all I wanted, for some reason I didn't think it was configurable per skin. I will certainly be using both of those lines in my skins.

I am going to mark this as closed unless there is any plan of implementing this further, like for example a scenario where this was independent of the skin.

**Comment by CTVCAM8** [comment]
I copied Ivo's text from his skin. Notice there is also  a "glass" option shadow:

 Main_shadow - enables or disables the drop shadow. The values are:
0 - disable shadow. useful for alpha skins with complex outline. The alpha opacity only supports rectangular shadows, which may not look good for some shapes
 1 - enable shadow (can be overriden by the start menu settings or the Windows settings)
 glass - enable the shadow if the menu is using glass or fullglass opacity. Use with glass skins with complex outline. Windows 8 and 8.1 don't support glass, so the menu falls back to using alpha opacity. It may be desirable to turn off the shadow in that case
        
Main_shadow=0

**Comment by bonzibudd** [comment]
Ah, I see. Never knew of the "Glass" option for the shadow either. Interesting.

On a side note (Somewhat related), the glass and fullglass options using Aero glass **specifically** in submenus seems to have gotten more glitchy in the past few years. i.e. pointing in and out of the menu and hovering over different items often makes the transparency sporadically switch into transparent, non-glass transparency. I thought this was an issue with something I changed in my own skin but I found out that it also affects the Smoked Glass skin built-in to Open-Shell. 

Do you have any experience with this or why this might happen? I have switched to the alpha transparency when I use it because of this but I prefer the consistency of using Glass throughout.

**Comment by CTVCAM8** [comment]
I noticed the flashing on the glass submenu a few years ago too and don't have knowledge of why it does it or how it can be fixed.
I think I mentioned to Ivo, but don't remember if I had before and after screenshots to show the weird action.
You could try free Big Muscle glass to see if there is any difference.

I tend to blame Microsoft for getting rid of code with each new release. That's partly why Ivo gave up on Classic Shell.

Same as the temporary flash on the search box on the glass main menu. 
Very noticeable if search box color is black there will be a brief flash where the search box becomes invisible to the desktop background. Does not always happen though.

**Comment by CTVCAM8** [comment]
Here is one link

http://classicshell.net/forum/viewtopic.php?f=12&t=7478

That one is not so much about flashing. I don't know where the other ones are.
Anyway, I got no response at the time. Yep, Creators update is where things got worse for Classic Shell. :(

**Comment by bonzibudd** [comment]
@CTVCAM8 

Sorry for the late response. 

What you provided seems to be part of the issue I was having. I had the same thing happen, and the weird spontaneous darkening of the submenu. It also seems to happen sometimes when first opening the submenu altogether.

The other issue that seems to have happened between then and now is that the submenu, similarly to how it turns dark, will sometimes switch from Aero to alpha transparency, and switch back after hovering over some different items. It seems to happen more frequently after Open-Shell has been running for a long time. It's a little more noticeable since the alpha transparency is generally a set amount and cannot be changed. Additionally, Aero colors usually appear brighter than standard transparent ones.

I'm not that upset about this but it is annoying. especially since Aero glass is now an underlying feature which should stay functioning properly. It would be best if Open-Shell hosted it's own glass transparency which was user customizable in terms of radius and other effects, however that's another heap of code and probably a performance hinderance.

**Comment by CTVCAM8** [comment]
We bad. :) Really going off the original topic. Are we supposed to be discussing stuff like this on 

https://gitter.im/Open-Shell/Lobby?source=orgpage
or
https://gitter.im/Open-Shell/UC-Menu-Skins?source=orgpage


I wonder if the speed of one's computer is part of the flashing problem?
Maybe even graphics driver issues. I've had my share of weird visual issues after Windows updates, 
where the old Edge browser window would become invisible if I dragged the window to resize it. Only invisible in the dragging area.

What you could do is document all the flashing and other visual issues you have, with a video that captures enough frames per seconds
so it's easy for the coders and others to see. It might stay at low priority for a long time, but at least there will be a record of it.

I don't think I have your glass to alpha issue. I do have the flashing.
I've tried turning off submenu animation. It seems to help a little bit, 
but is inconsistent as before, depending on if opening same submenu again
or a different submenu link.

The flashing looks more noticeable when the glass color mask is at maximum. 
Could that mean there is a delay in retrieving glass color information?



There's something going on with submenu animation.
Example with 7 style start menu on Win10.
Set submenu animation speed to 2000 with slide.
Click the start button to get the start menu.
Hover mouse over recent items on the second column.
Submenu slides out-expected.
Now quickly hover over Control Panel- notice submenu opened without animation. 
Hover over recent items again-opens without animation. 
If I wait 2 seconds on a different entry on the 2nd column then hover on another submenu link, then slide animation keeps working.
Maybe it's always been this way?
It's as though there is a timing reset problem.

**Comment by bonzibudd** [comment]
Those seem like plausible ideas. I'll record some stuff and post it to a separate issue. I can't say for sure that I've seen the glass-alpha issue on any other machines, it could have to do with my AMD card. 

I think I'll post other stuff like this on the UC-Menu-Skins discussion.

**Comment by CTVCAM8** [comment]
Mine is AMD as well but the processor is combined 
AMD A8-3850 APU with Radeon(tm) HD Graphics.
I see the alpha switching on and off on menus as well.
I made a video of glass to alpha switching and will post as an issue.
