### ISSUE TITLE
Serious problem, seems to have been caused by installation of build 4.4.147

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#419]
Whenever I try to run any system32 app, I receive an error like this one:
![image](https://user-images.githubusercontent.com/61938331/90065926-fde6a380-dcba-11ea-9f73-7f02795bb39e.png)
This makes the feature completely unusable. I have tried uninstalling and reinstalling, which does not fix the issue.

I am not sure if this applies to other types of apps as well, but from what I can tell all non system32 apps work fine.

**Comment by CTVCAM8** [comment]
I'm using build 4.4.147 and don't have any new problems that I know of relating to Open-Shell. 
Before that, I was using Open-Shell 4.4.144 version
My system is 64 bit Win10 2004


![ver 4 4 147 Pinned works for me](https://user-images.githubusercontent.com/44127216/90089466-537c7980-dcd6-11ea-9f0c-e2956ceb2d72.png)

**Comment by blackcrack** [comment]
good blanked .. hehehehe .... :+1:

**Comment by CTVCAM8** [comment]
Sorry @bonzibudd, I can't help you.
I tried pinning with the "Use Start Menu folder" option-works.

![Pinned with start menu folder](https://user-images.githubusercontent.com/44127216/90096534-64ce8180-dce8-11ea-8b75-1b21c58c78f6.png)

**Comment by ge0rdi** [comment]
@bonzibudd 
Please do following:
* enable [logging](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-obtain-advanced-Open-Shell-Menu-log)
* replicate the issue (open start menu, try to run cmd)
* provide log here

**Comment by bonzibudd** [comment]
@ge0rdi 
[StartMenuLog.txt](https://github.com/Open-Shell/Open-Shell-Menu/files/5068618/StartMenuLog.txt)

For some reason it thinks all system32 apps are pinned. This doesn't seem to apply to apps in C:\Windows, or apps in the Start menu folders in ProgramData and AppData respectively. I installed this version of Open-Shell on a VM and did not have the same issue, so this may or may not be related to the newest builds.

**Comment by blackcrack** [comment]
my system Windows 7 pro (with the update today ..) , no problem..

**Comment by ge0rdi** [comment]
@bonzibudd 
I don't see any issue in log.
Could you describe what exactly are you doing? Step-by-step.

**Comment by bonzibudd** [comment]
1. click start button
2. type "cmd" or "mspaint" or any other system32 program
![image](https://user-images.githubusercontent.com/61938331/90142549-806a7400-dd4a-11ea-8897-186c6c817c2c.png)
![image](https://user-images.githubusercontent.com/61938331/90142673-a7c14100-dd4a-11ea-8b89-811591d723ba.png)
These apps don't have any icons and point to the "pinned" folder which doesn't have anything in it, as I don't have anything pinned to the menu.
3. Click the app or click enter on it
When I click the icon it gives me this error:
![image](https://user-images.githubusercontent.com/61938331/90142976-08e91480-dd4b-11ea-86c9-4c61b7ec84ba.png)

Would it be worth uninstalling Open-Shell and deleting the OpenShell registry key? I have been looking around and it does have some remnants of old pinned items which could be causing some problems.

**Comment by ge0rdi** [comment]
Its weird :( Not sure where those items are coming from, but they are incorrect.

> Would it be worth uninstalling Open-Shell and deleting the OpenShell registry key?

First try to delete cached information:
`Settings -> Backup -> Clear cached information`

If that doesn't help then try:
* backup your settings
* exit Open-Shell
* delete `HKEY_CURRENT_USER\SOFTWARE\OpenShell` registry key
* start Open-Shell and check if the issue is fixed
* import your settings
* check if everything is OK

**Comment by bonzibudd** [comment]
Ok, so the registry thing did end up fixing it. The items are displaying and opening correctly after a re-install. 
![image](https://user-images.githubusercontent.com/61938331/90149423-79476400-dd52-11ea-8466-6ca3a38d2f21.png)
That's one of the weirder problems I've had with Open-Shell or Classic Shell. Is there any reason that the System32 apps would be treated differently than others in this regard?

**Comment by ge0rdi** [comment]
>  Is there any reason that the System32 apps would be treated differently than others in this regard?

Hard to tell. Apparently you had some wrong info stored for them. But how did it get to that state, I cannot say.
You don't have backup of that registry key, do you?

**Comment by bonzibudd** [comment]
@ge0rdi sadly no. All I can say is that I saw that there were some old pinned items stored there, one of which was a system32 app.

I'll play around with it some more and see if I can consistently replicate it.
