### ISSUE TITLE
Problem Updating

### ISSUE THREAD

**Issue by tanzanos** [Open-Shell/Open-Shell-Menu#420]
Hi, I recently upgraded from Classic Shell (using it for many years) to Open Shell. However when I go to check for updates it says "Failed to check". This is just a report and not a hassle as I can just frequently check for newer versions to download and install.
I sincerely wish to thank you  all for I simply am lost without Shell.

**Comment by ge0rdi** [comment]
This is known issue.
In-product update is simply not supported at the moment.

I think we should rather remove it (until implemented) to avoid confusion.

**Comment by tanzanos** [comment]
OK, Thank you for letting me know. Best of luck to you and your team.

**Comment by ge0rdi** [comment]
I'd like to let you know that latest nightly build (4.4.156) contain support for auto updates.
It is also possible to check for nightly updates.
