### ISSUE TITLE
Is there any way to make Control Panel expandable in Win 10?

### ISSUE THREAD

**Issue by Dave-Rado** [Open-Shell/Open-Shell-Menu#423]
I have just upgreaded to Windows 10 and installed Open Shell and I can't see any way to make Control Panel expandable. Under Windows 7 with Classic Shell, Control Panel **was** expandable. In other words, when I clicked on Settings and then Control panel I saw a submenu of all the Control Panel items, whereas in Windows 10 if I click on Settings and then Control panel it opens a new window with all the items in it. Is there any way to make it expandable under Windows 10, as it was in Windows 7?

Similar story with Start -> Settings -> Printers - I can't see any way to make it exandable with Open Shell under Windows 10, but it used to be expandable with Classic Shell under Windows 7. Is possible to make this expandable as well?

If this is no longer possible, please could this funcionality be reinstated?

Dave

**Comment by ge0rdi** [comment]
You can change it in `Settings` -> `Customize Start Menu`.
Just select `Display as a menu` for `Control Panel` command. Similarly for `Devices and Printers`.

**Comment by Dave-Rado** [comment]
Hi ge0rdi 

If I go into Open Shell Menu Settings (I presume that's the settings you meant, not the Windows 10 ones), and on the Customize Start Menu tab, I right click on Control Panel, I only see the [following options](https://iili.io/dNMNaf.png). 

If I then select Edit from that right-click menu, I only see the [following options](https://iili.io/dNMs8x.png).

I don't see "Display as a menu" anywhere. What am I missing?

Thanks for your help.

Dave

**Comment by Dave-Rado** [comment]
I've found it - it was on the "Special Items" tab, rather than on the "Customize Start Menu" tab. As was Printers.

However, Settings + Settings (i.e. Microsoft's new partial replacement for Control Panel) **wasn't** listed there, so I presume it's not possible to make that expandable? If not, is that functionality something that could be considered to be added in a future version of Open Shell?

Dave

**Comment by ge0rdi** [comment]
> I've found it - it was on the "Special Items" tab, rather than on the "Customize Start Menu" tab. As was Printers.

Ah, sorry. I'm using `Windows 7 style` menu and apparently settings looks different for various menu styles.

> However, Settings + Settings (i.e. Microsoft's new partial replacement for Control Panel) wasn't listed there, so I presume it's not possible to make that expandable?

At the moment that's not possible.
There is also problem with modern settings enumeration (see #57).

Once this will be resolved, we may eventually consider adding possibility to display them as menu (though there is quite many of such settings and the menu would be huge).
