### ISSUE TITLE
Trojan inside installer!!!

### ISSUE THREAD

**Issue by spam-receiver** [Open-Shell/Open-Shell-Menu#426]
https://ci.appveyor.com/api/buildjobs/ov7lj1lgqod5i9mq/artifacts/OpenShellSetup_4_4_149.exe

This installer contains Trojan: Win32/Wacatac.D2!ml

In files:

C:\Windows\Installer\MSI357C.tmp
C:\MSI62f02.tmp

Be careful.

**Comment by ge0rdi** [comment]
This is false-positive.
Please, report it to your AV vendor.

Our source code is public, so anybody can check if it contains any malicious code.
It is very unlikely that build pipeline on Appveyor will introduce any malware, because then many more projects will be affected as well.
