### ISSUE TITLE
Shutdown button is gone

### ISSUE THREAD

**Issue by Blisk** [Open-Shell/Open-Shell-Menu#428]
**Describe the bug**
A shutdown button is gone, there is no way to logoff or shutdown or restart
**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**
 - Open-Shell: [e.g. 4.4.131] 4.4.142
 - OS: [e.g. Windows 10 1903] windows 10 1803

**Additional context**

**Comment by Ibuprophen** [comment]
1) Right Click the Start Menu Button and select Settings. 

2) Select the "Main Menu" tab (at the top of the dialog). 

3) Scroll down to the "Command Options" and see if the top "None" is selected as this will hide this from the menu. 

I typically have the "Shutdown Dialog" selected for the option to cancel the shutdown in case I mistakenly select the shutdown when the menu is open. 


~Brian Kerr
