### ISSUE TITLE
Generate msix

### ISSUE THREAD

**Issue by WSLUser** [Open-Shell/Open-Shell-Menu#429]
**Is your feature request related to a problem? Please describe.**
Better deployment method that's compatible to Windows 7 (but has more features in Windows 10) and would also allow for publishing to the MS Store.

**Describe the solution you'd like**
I'd like install an msix instead of an msi. I'd also like to see auto-updates from the MS Store.

**Describe alternatives you've considered**
Just install the usual msi.

**Additional context**
See https://github.com/microsoft/msix-packaging for getting started.

**Comment by Ibuprophen** [comment]
Wow... This isn't a "Feature Request", but a complete overhaul in order to comply with the Microsoft msix Prerequisites (to include the cost for a few). 

I didn't delve into the whole thing as this would consume allot of time. 

@ge0rdi, @XenHat & @coddec, what's your take on this? 


~Ibuprophen

**Comment by ge0rdi** [comment]
Doesn't sound like complete overhaul to me. It is just about different packaging.
For me this is normal feature request and makes completely sense.

**Comment by Ibuprophen** [comment]
My apologies. This was why I mentioned you to take a look as I had just read it wrong. 


~Ibuprophen

**Comment by DragoCubed** [comment]
looks like it requires a cert :/

**Comment by ge0rdi** [comment]
Also MSIX packaged applications run in _app container_ so it is not possible to do things we need in `Open-Shell` (inject into `explorer.exe` for example).

I'm afraid it won't be possible to use MSIX for `Open-Shell`.

**Comment by WSLUser** [comment]
Powershell needs the same access and they are generating an msix. I suggest looking at their code base. Also Visual Studio generates a cert for you. It can part of the CI in Appveyor. Again check powershell code base and look at the build steps.

**Comment by XenHat** [comment]
One other advantage of MSIX package is that, in the best case, the application will be preserved/reinstalled after a Windows Refresh :tm: operation.
