### ISSUE TITLE
Modernize OpenShell with UWP + WinUI

### ISSUE THREAD

**Issue by WSLUser** [Open-Shell/Open-Shell-Menu#430]
**Is your feature request related to a problem? Please describe.**
Make the UI better and more configurable by switching to WinUI and building a UWP app
**Describe the solution you'd like**
I'd like to see a more visually pleasing Start Menu created by OpenShell.
**Describe alternatives you've considered**
I could stop using this but that would be pointless as I prefer a Win7 start menu on Win 10.
**Additional context**
See https://github.com/microsoft/microsoft-ui-xaml and https://github.com/microsoft/Windows-universal-samples for great helpful references for getting started.

**Comment by Ibuprophen** [comment]
Open Shell is not a "Windows App". The first sentence of the WinUI description even States "WinUI is a user interface layer that contains modern controls and styles for building Windows apps." 

The UWP is a part of the WinUI that's inclusive with the requirements for Windows Apps. 

My apologies, and a big thank you for your time and understanding, but I don't believe that this would happen anytime soon. 

If @XenHat, @ge0rdi and/or @coddec feels differently, please let me know. :-) 


~Ibuprophen

**Comment by WSLUser** [comment]
I would consider OpenShell an Windows Application. If powershell can be on the store (finally), then so could this.

**Comment by ge0rdi** [comment]
> If powershell can be on the store (finally), then so could this.

If something is on MS store it doesn't mean it is UWP app.
https://stackoverflow.com/questions/40701937/how-is-a-non-uwp-app-in-the-windows-store

I think there are no plans to put OpenShell to MS store nor making it UWP.

**Comment by Ibuprophen** [comment]
It just seems to me that MS isn't a big fan of Open Shell and, if so, they wouldn't be very welcoming for it to be on their store. Just an option on my part. :-) 


~Ibuprophen

**Comment by WSLUser** [comment]
You're kidding right? They have Amazon Alexa and ITunes in the Store. Both belong to competitors. They don't care about who it is, they only care that the guidelines are followed and since this is an OSS project, there's no fees associated.

**Comment by DragoCubed** [comment]
>since this is an OSS project, there's no fees associated.

I'm not sure about that. You need to spend (iirc) 20 USD for an individual developer account. 

WinUI 3 lets you embed it in non-UWP apps. It's way too much work for this project for little gain though. You were literally asking for a rewrite. The whole point of Open Shell is to restore the old interface.

**Comment by WSLUser** [comment]
Yeah you need an org so it can be free. Linux distros wouldn't be offered on the Store if they were paying something to MS. Or any other OSS project for that matter. 

For WinUI, I was thinking embed some XAML controls for use on supported OS. XAML can be supported on Win7 with effort. Yes this project doesn't have enough time and people to get it working (something MS is working to make easier) but  I was hoping the idea of it might catch somebody's eye and submit a PR to bring it about. Such a PR would obviously need review for the core contributors to ensure the only differences are the UI elements on supported OS, maybe even a different project altogether that exists in this repo for use on Win10. Let's face it, you have more users on Win10 than you do on any other OS because 8.1 isn't that great and 7 isn't supported even if some people choose to run it anyways. You are under no obligation to support users of Win 7. Only Win 8.1 and higher actually require support as they are still supported by MS and makes it easier for you to troubleshoot that a bug indeed belongs to OpenShell instead of Windows.

**Comment by DragoCubed** [comment]
And Microsoft gives some Linux orgs a bit of cash too. They want distros to be in their Store because they want WSL so devs use Windows. MS also happens to be on the Linux foundation board or something too.

**Comment by NebelNidas** [comment]
I have been thinking about modernizing the settings window with XAML recently, too. XAML islands make this fairly easy already, and with the introduction of WinUI 3 it should be possible even for a small team like Open Shell. This will and should probably not be a focus for the core developers, though, but we have to be open for the idea that someone might do this eventually.

I myself am currently quite busy, though I'm trying to get into C++ and WinUI as soon as possible for my personal projects. If no one finds themselves interested in this task until then, I'll try to implement this on my own when having a bit of time to spare again, let's say around summer next year.
