### ISSUE TITLE
About text should say "Classic Shell Reborn" or "Reborn Classic Shell"

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#431]
Not an issue with the program, just an OCD thing that bugs me when I load the page on Github. Hopefully it's OK to post small stuff like this on here.

**Comment by ge0rdi** [comment]
What text are you referring to?
Could you post a screenshot for clarification?

**Comment by bonzibudd** [comment]
@ge0rdi sorry for not being clear. I'm referring to the about text on the main github page.

![image](https://user-images.githubusercontent.com/61938331/91639638-fe36ac80-e9e5-11ea-8278-963f3fcf755b.png)

**Comment by ge0rdi** [comment]
Fixed.
