### ISSUE TITLE
Adjustable Height XP Start-menu Top Bar

### ISSUE THREAD

**Issue by blackwidowfarms** [Open-Shell/Open-Shell-Menu#432]
There's a problem with the XP start menu on 4k monitors, even with the display at 150% zoom. The blue toolbar on top of the XP Start Menu is now too short, it doesn't look right at half the height it should be (see attached image).

I would like to see a manual "height" control for that blue bar (in settings), the User Account picture could scale up or down with the set height of the bar.

I've looked all through Openshell's program files but there seems to be no config files to get into which deal with that.
Here is a screenshot of my monitor, thanks very much if you would help:
![Openshell XP on 4k](https://user-images.githubusercontent.com/70411948/91614648-c58bca00-e936-11ea-9903-5dd05531827a.jpg)

This is a Windows 10 computer and I'm retrofitting it with the XP sound and appearance 👍  so nobody wants to steal it, plus the XP look is awesome. Thanks for openshell, it's cool stuff.

Here is a side-by-side approximation of the difference I'm seeing. I also just noticed the "Log Off" and "Shut Down" buttons don't have a blue area of their own like in XP and the green arrow icon beside "All Programs" is way too small. 
![xpmenu2](https://user-images.githubusercontent.com/70411948/91621797-405de080-e949-11ea-98cd-81d161575e77.jpg)

**Comment by bonzibudd** [comment]
You might be better suited with something like this: [CS Forum](http://www.classicshell.net/forum/viewtopic.php?f=17&t=7872)

There's a few options to try, they might work a bit better with high DPI and also have some added functionality.

**Comment by blackwidowfarms** [comment]
@bonzibudd thanks very much, I actually found a few skins with a taller top to the start menu. I'm 90% stoked, it's awesome.
I realize it may be more difficult than I thought for "stretching" options as bitmaps are referred to and sliced up for placement... I still think it would be great if the height option could exist.
![screen](https://user-images.githubusercontent.com/70411948/91695765-7fe02480-eb23-11ea-9100-bda5432370e6.jpg)

**Comment by CTVCAM8** [comment]
In case you are interested, I posted a test XP Blue 200% size.skin on the old Classic Shell forum:

http://classicshell.net/forum/viewtopic.php?f=17&p=36412#p36412

I don't have a 4k monitor to see if it works, but I think it will.

**Comment by blackwidowfarms** [comment]
@CTVCAM8  wow! that's simply amazing. I was able to use your skin instantly with much improvement to the overall effect, on a 4k 65" monitor it looks amazing. I am thoroughly impressed with how much closer this skin is to XP's. I will spend some time now putting things into place, I'll post again when it's adjusted but here is how it looks right out of the box:
![xp](https://user-images.githubusercontent.com/70411948/92270025-287ee300-ee9a-11ea-9036-916fcb37f431.jpg)
Thanks very much! I think you know how much I appreciate that :)

**Comment by blackwidowfarms** [comment]
@CTVCAM8  (or any of the many amazing coders here) I have a question, sorry to bother the flow of the thread... I built a Luna shutdown menu:
![Screenshot 2020-09-25 133154](https://user-images.githubusercontent.com/70411948/94315497-76d24f80-ff37-11ea-93cb-dbdaeb4b2058.jpg)

... which means I have no need for the sub-menu items located on the "Turn off Computer" button:
![Screenshot 2020-09-25 133125](https://user-images.githubusercontent.com/70411948/94315514-80f44e00-ff37-11ea-8e88-b34147ec10c2.jpg)

but when I get rid of the sub-menu items, the "Turn off Computer" is no longer a split button menu and the text defaults to blue instead of white (your skin code "Main2_split_text_color" doesn't work with it anymore) : 
![Screenshot 2020-09-25 133254](https://user-images.githubusercontent.com/70411948/94315522-86519880-ff37-11ea-88f9-5b218c4fde31.jpg)

Is there some code which would color the "Turn off Computer" text when there's no split-text sub-menu attached to it?

**Comment by CTVCAM8** [comment]
Well, as a layman, no easy fix for that.
You could get rid of the text all together by putting & & in the shutdown label
and changing some other option checkboxes in the Customize section for the shutdown.

A different way we used way back was to insert "sub-items as buttons" see the picture of 144 size.
There is no text. Could make fake text for it and include the text image as an emblem in the skin file to show in the correct area.

![Sub items as buttons](https://user-images.githubusercontent.com/44127216/94324577-52826d00-ff4f-11ea-8c20-4ed40f710d75.png)


Sorry, I don't have any time to do it for you for 200% size.

**Comment by blackwidowfarms** [comment]
Perfectly fine that you not build it for me :) thanks very much for your info, it's all new to me. I'll smash away at that and see what I can come up with.
