### ISSUE TITLE
Modal dialogue locks OpenShell

### ISSUE THREAD

**Issue by der-ada** [Open-Shell/Open-Shell-Menu#435]
**Describe the bug**
If you have a startmenu with a lot of entries, they will be arranged in multiple coloumns. When you try to delete one of the entries, a confirmation dialogue appears *behind* these multiple coloumns. This dialogue is modal. So you can neither close the dialogue (it is hidden) nor close the OpenShell menu, because the dialogue is modal. 

**To Reproduce**
1. open a program menu with many entries
2. try to delete one

**Expected behavior**
The confirmation dialogue shoud appear above the OpenShell menu.

**Version:**
 - Open-Shell 4.4.142

**Comment by ge0rdi** [comment]
Please, try with [latest nightly build](https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts).
It should be fixed there.

**Comment by der-ada** [comment]
Yes it is fixed. The dialogue appears in front of the OpenShell programs menu now. Thank you very much!
