### ISSUE TITLE
Multiple columns in pinned folder not working properly (only rarely)

### ISSUE THREAD

**Issue by Linnshet** [Open-Shell/Open-Shell-Menu#436]
For some reason, the option in General Behavior, does not indeed make multiple columns. I've seen it working just when I had just set it up, but now no matter how much I switch back and forth, it continues to be scroll. This is the "Classic with two columns" style, in case it makes a difference (I have not wanted to test the others, as I didn't wanna mess up my work).

Edit: now it seemingly randomly started working again. This has happened before though, as mentioned when I had just set it up, it went from scroll, to multiple columns, to scroll for no apparent reason. I'll update this and close it, if it hasn't occured again after three days.

Edit2: A second after posting this, I went to check again, and it has gone back to scroll.

**Comment by ge0rdi** [comment]
Seems to be working without any issue for me.

**Comment by Linnshet** [comment]
I switched the skin, and it still regularly does this for me, so now I know it's not that.
These are my settings in general behavior. Should be pretty standard.
![sss](https://user-images.githubusercontent.com/52015410/91656553-1e7b6f80-eaa9-11ea-9650-e1afb8e47516.png)

**Comment by Linnshet** [comment]
Aha! @ge0rdi, apparently it's only in my pinned folder, rather than the actual programs folder. They're identical in my case, so I didn't think of the difference. Maybe this helps narrow down the issue?

**Comment by ge0rdi** [comment]
Could you post a screenshot and highlight the issue? So we know what do you mean exactly.

**Comment by Linnshet** [comment]
Sure. 
![EXAMPLE](https://user-images.githubusercontent.com/52015410/91663981-a4b0a980-eadb-11ea-9260-307e60c8cf46.png)

**Comment by ge0rdi** [comment]
Oki, got it. So it seems that pinned folder doesn't respect the `Use multiple columns` setting.
Will try to have a look at it.

**Comment by ge0rdi** [comment]
@Linnshet 
You can try this [build](https://ci.appveyor.com/project/passionate-coder/open-shell-menu/builds/34931976/artifacts) if you want to test the fix.

**Comment by Linnshet** [comment]
You did it! Thank you. 👍

**Comment by anonimuos** [comment]
This is a great improvement. It should work like that for pinned folders too, not just custom items. Thank you.
