### ISSUE TITLE
Search being overrided when highlighting specific folder

### ISSUE THREAD

**Issue by Linnshet** [Open-Shell/Open-Shell-Menu#437]
The start menu search box is accessed normally and selected by default. However, if the mouse is moved up from the start button (which is hard not to accidentally do), to hover on for example programs or a pinned app/folder, it will override the search box selection, and not search as commanded.

In the attached .gif, even though I accidentally recorded without cursor showing, you can see that when my start button is highlighted, the search bar works as it should. However, when I move my mouse up a very little bit to programs, it will first of all take the first recognized tapped letter, in my case open the associated folder, and then next tap the associated program. In the example, I simply pressed **S** twice.

Windows 10, 4.4.142

**Comment by ge0rdi** [comment]
I think it is by-design that focus is changed when menu is automatically opened (by hovering on it).
You can then use keyboard to navigate opened menu.

I'd suggest:
* Disable sub-menu auto opening (change `Settings` -> `General Behavior` -> `Menu delay` to some big number)
* Use `Win` key to open start menu - this way you can start typing immediately without the risk of moving mouse pointer

**Comment by Linnshet** [comment]
Am currently using the win key to open my start menu now. It takes some getting used to, after using the original Windows 10 start menu that didn't do this. The sub-menu auto opening makes no difference, due to as soon as tapping the key, it pops open.

**Comment by ge0rdi** [comment]
> The sub-menu auto opening makes no difference, due to as soon as tapping the key, it pops open.

Can you explain what "pops open"?

With menu auto opening disabled it shouldn't matter where mouse pointer is. Search should stay in focus. So you should be typing into it.

**Comment by Linnshet** [comment]
Okay, I see that it actually does fix it when making the auto-opening a ludicrously high number. I am satisfied, and I see that it has already been added, so I will close this. Thanks for your help ge0rdi.
