### ISSUE TITLE
Menu opening and closing/focus bug

### ISSUE THREAD

**Issue by anonimuos** [Open-Shell/Open-Shell-Menu#439]
**Start menu focus issue**
I am not sure yet which version of Open Shell this bug cropped up in as I started _recently_ testing builds after the Settings search was added (until then I was using Classic Shell 4.3.1). But the problem is the main menu simply loses focus for some reason and immediately closes when opened. First I thought this was a bug with my mouse - it was double clicking by accident when single clicking due to a faulty left click but then I realized it was happening only with the Start menu. Also, now this happens with both - the Win key as well as the mouse click. 

I am using the Classic with two columns style currently.

It happens so fast and randomly that often I open the menu, and it quickly closes but I have begun typing so only the submenu with search results appears and works while the main menu has closed!

**To Reproduce**
It is hard to reliably reproduce the behavior but I am certain it's some focus related bug in Open-Shell's menu

**Screenshots**
Here's a screenshot of how it looks when this happens.

![image](https://user-images.githubusercontent.com/46422834/91876546-70cfb280-ec9a-11ea-8337-1e83452d8db0.png)
The submenu is open while the main menu has closed. 😂 The focus is in the Search box and I am able to search even though it looks like I have pasted a submenu screenshot on top of the web browser. 😂

**Version:**
 - Open-Shell: 4.4.152 and 4.4.151 also
 - OS:  Windows 10 1803

For now I have reverted to Classic Shell 4.3.1 although I am willing to try new builds to get this fixed.

**Comment by anonimuos** [comment]
It's happening now on Classic Shell 4.3.1 also so it's not an Open-Shell problem but a Windows issue. I am closing it.

**Comment by ge0rdi** [comment]
> It is hard to reliably reproduce the behavior but I am certain it's some focus related bug in Open-Shell's menu

Well, unless you'll be able to figure out some way to reproduce it, I guess it will be also hard to find/fix 👍 
I have never noticed such behavior so far.

Try to start with clean settings:

- Exit Open-Shell
- Make backup of `HKCU\SOFTWARE\OpenShell` key and then delete it
- Make backup of `%LOCALAPPDATA%\OpenShell` folder and then delete it
- Start Open-Shell and check if the issue is still there
