### ISSUE TITLE
to be able to have 100% transparent background on the classic theme

### ISSUE THREAD

**Issue by pheonixfirewingz** [Open-Shell/Open-Shell-Menu#442]
I would add it myself but I don't know where or how open-shell changes the start menu and taskbar are overridden. I would have liked a 100% transparent start menu and taskbar

**Comment by pheonixfirewingz** [comment]
![image](https://user-images.githubusercontent.com/26938574/92401179-12d11e00-f125-11ea-9813-14b7d2ba4448.png)

**Comment by bonzibudd** [comment]
It is possible. I'll get back with you with a modified skin.

**Comment by bonzibudd** [comment]
https://1drv.ms/u/s!AqxEMH2XuF6DxHGvsDmgmSqF9KAH?e=hA1dRe

Make sure to set "Glass Opacity" to 0 for the fully transparent effect. Also, I expect that you might want some more items to be transparent, so I can do that if you would like.
