### ISSUE TITLE
Can't see how to make File Explorer navigation pane show subfolders

### ISSUE THREAD

**Issue by Dave-Rado** [Open-Shell/Open-Shell-Menu#444]
When I was using Classic Shell with Windows 7, with the navigation pane style set to Windows XP, the navigation pane displayed all the folders and subfolders in the path. So for instance if the right hand pane was looking in C:\Temp, the left hand pane was displaying the root folder "Local Disc C:\" and below that it displayed the subfolder "Temp".

But I am now running Open Shell with Windows 10, again with the navigation pane style set to Windows XP. but now the navigation pane is just displaying the root folder  "Local Disc C:\" with nothing displayed below it. If I click on the Expand icon next to "Local Disc C:\" it **then** displays the subfolders of C:\ and the Temp folder is highlighted - but I don't want to have to do that every time I open File Explorer - I want it to be expanded by default. How can I make the navigation pane display with the subfolders expanded automatically as it used to?

Dave

**Comment by Dave-Rado** [comment]
It's okay I found the answer [here](https://winaero.com/blog/make-navigation-pane-expand-open-folder-windows-10/).

**Comment by Ibuprophen** [comment]
If you were successful in locating a resolution, for what your issue is regarding, you can close this issue. 

Thanks a Bunch! :-) 


~Ibuprophen
