### ISSUE TITLE
Windows XP Start menu icon hover text

### ISSUE THREAD

**Issue by blackwidowfarms** [Open-Shell/Open-Shell-Menu#445]
**Is your feature request related to a problem? Please describe.**
There's no problem, but for XP Luna type skins, in the Start menu icons, the default XP "hover info text" is nowhere to be found, only the default hover text referrals from the user's non-XP system in "StartMenuL10N.ini".
Can there be a way to select a custom INI for the menu tips under "customize menu", instead of defaulting to the included one?

**Describe the solution you'd like**
-  I presume replacing it with a custom one would work.
- I would like to share my partial collection of Windows XP hover-text text for Start Menu icons. These can be copy/pasted into the text boxes in the "tip" area in customize menu options:
![tip options screen](https://user-images.githubusercontent.com/70411948/92534900-d2d46e80-f1ea-11ea-8935-d3a6a264a85f.jpg)
Maybe we could come up with a "StartMenuL10N_XP.ini" file created for XP like the default one in Openshell programs folder?

This will make things much easier for those of us who want to go the extra distance in recreating XP more accurately, which is where I think a lot of interest is going to be in the near future. Here's the hover text tips for your Start menu icons (if you see periods at the ends, that was part of the original hover text) :

Windows Messenger:
Shows whether your friends are online and lets you have online conversations.

My Documents:
Opens the My Documents folder, where you can store letters, reports, notes, and other kinds of documents.

My Pictures:
Opens the My Pictures folder, where you can store digital photos, images, and graphics files.

My Music:
Opens the My Music folder, where you can store music and other audio files.

Control Panel:
Provides options for you to customize the appearance and functionality of your computer, add or remove programs, and set up network connections and user accounts.

Set Program Access and Defaults:
Chooses default programs for certain activities, such as Web browsing or sending email, and specifies which programs are accessible from the Start menu, desktop, and other locations.

Network Connections:
Connects to other computers, networks, and the Internet.

Help and Support:
Opens a central location for Help topics, tutorials, troubleshooting, and other support services.

Log Off:
Disconnects your session.  You can reconnect to the session when you log on again.

I don't have hover text for some stuff, like E-mail, Windows Media Player, MSN Explorer, Tour Windows XP, MSN Explorer, Automatic Updates, Printers and Faxes, Run, Shutdown dialog, Lock, Sleep, Restart or Shutdown sections. I'd really appreciate some help with that :)
Here's the Control Panel hover text in action:
![hover text example](https://user-images.githubusercontent.com/70411948/92536691-2c3e9c80-f1ef-11ea-9f77-6f2a81f9b4e6.jpg)

**Comment by CTVCAM8** [comment]
Can't you just make a backup .XML file that has every personal setting you made?
Then share it

**Comment by blackwidowfarms** [comment]
Oops (original post edited) I kinda forgot to pose the main feature request, sorry. Can there be a way to select an INI for the menu tips, instead of defaulting to the included one? I presume replacing it with a custom one would work.
 In response, yes I do back it up into my XML but the option to select a custom "StartMenuL10N.ini" would be great for people skinning Luna theme stuff if they could select the XP version of hover-tips.

**Comment by CTVCAM8** [comment]
Other. I see you have extended the shutdown text lower onto the blue bar.
Did you know by adding this text in the skin file, just the split button will have white text:

Main2_split_text_color=#FFFFFF,#FFFFFF,#7F7F7F,#7F7F7F
Main2_split_arrow_tint1=#FFFFFF

**Comment by blackwidowfarms** [comment]
That's actually something that was bugging me, what a simple solution! Thanks very much for that, it works very well.
![white text](https://user-images.githubusercontent.com/70411948/92576806-c974f180-f23e-11ea-92f0-a7bf127d0ce4.jpg)

**Comment by Ibuprophen** [comment]
Your awesome @CTVCAM8 for the much needed assistance others have in a "User Helping User" way! :-D 

@blackwidowfarms, if your all set with this open ticket, you can close it now. Thanks a Bunch for your understanding! :-) 


~Ibuprophen

**Comment by blackwidowfarms** [comment]
Thanks very much everyone here :) I'm learning quite a lot. I'm sorry, I know there's a Classic Shell forum but I can't make an account because the Captcha test (to prove I'm human) is broken.
 This ticket was a request for the ability to choose a custom "StartMenuL10N.ini" from the options menu under "Customize Menu" and I think perhaps replacing it manually is the best answer, then sharing custom INI files with skins.
 Thanks again 👍
