### ISSUE TITLE
What about making a official discord server ?

### ISSUE THREAD

**Issue by ImZary** [Open-Shell/Open-Shell-Menu#448]
i think if we have a discord server it could help people like me & other's to get a easier way to learn about open shell's menu system & also getting helped a lot faster & easier 

so that mean that if we had an official discord server it could maybe be helpful then github page & idk 

ty for reading this & have a nice day

**Comment by Ibuprophen** [comment]
Interesting question/feedback. I've, personally, never really thought about this type of avenue myself... 


~Ibuprophen

**Comment by XenHat** [comment]
I noticed this just after making one today. Done! check the readme for the invite :)

**Comment by ImZary** [comment]
thanks for seeing this feature request & have a nice day (:
