### ISSUE TITLE
Documentation on Symbols.7z

### ISSUE THREAD

**Issue by Bamajon1974** [Open-Shell/Open-Shell-Menu#449]
Is there any documentation and/or instructions how to install/use the files in the Symbols.7z compressed archive? 

Basically, what do the symbols do, how are they different from those in the OpenShell default installation and how are they installed? 

Thanks!

**Comment by ge0rdi** [comment]
Symbol files are used for diagnostic/debugging purposes.
They are needed mostly by developers to analyze crash dumps, etw traces for example.

Most of users can safely ignore _symbols_ package.

**Comment by Bamajon1974** [comment]
Thank you for the clarification!
