### ISSUE TITLE
Many of the search options do not work after latest update (4.4.152)

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#452]
This issue seems to be new as of the latest general release. I have tested this with 2 different machines and can confirm that the issue is reproducible. Here are the options which I have confirmed to be broken:
![image](https://user-images.githubusercontent.com/61938331/93007749-5d460680-f53a-11ea-9c50-e675c227c475.png)

This might be related to the newly added "Modern Settings" index. Any input on this would be appreciated.

**Comment by ge0rdi** [comment]
Can you provide examples of items that do not work?
Without specifying exact issue it would be very hard to do anything about it.

**Comment by bonzibudd** [comment]
![image](https://user-images.githubusercontent.com/61938331/93007749-5d460680-f53a-11ea-9c50-e675c227c475.png)
So whenever I would toggle any one of these settings, it would not make any difference to the search results. When I posted this, two of my computers were having the same issue (I disabled "Search Metro apps" for example, and still got those results). However currently, both of my systems seem to be working properly, which I can't really explain. If the issue happens again, I will definitely provide more details. And sorry for the confusion.

**Comment by ge0rdi** [comment]
I think there is some kind of cache for search results.
Reboot (or Open-Shell exit) should clear it.

Anyways, feel free to reopen if there will be some issue with it.
But please, specify what exact results do you get and why it is not expected (screenshot should help).
