### ISSUE TITLE
How to set all open-shell settings to default

### ISSUE THREAD

**Issue by hreintke** [Open-Shell/Open-Shell-Menu#457]
Running Windows 10 & open-shell 4.4.152

I have been experimenting with themes and openshell settings -> a lot of custom settings.
Like to return now to the default settings as they are at a fresh install of open-shell.

Tried uninstall -> install but after that the "old" custom settings are still in place.

Is there a way to revert to the "factory settings" ?

**Comment by NebelNidas** [comment]
Go into Open Shell's settings and select this option from the "Backup" dropdown button:
![image](https://user-images.githubusercontent.com/48808497/93600193-8a256e00-f9bf-11ea-93b4-363c9d45cb18.png)

**Comment by hreintke** [comment]
Thanks.
