### ISSUE TITLE
Provide the ability for Start menu skins to detect 125% scaling

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#458]
**Is your feature request related to a problem? Please describe.**
Currently, skins have the ability to detect 100% and 150% scaling automatically, which can be used in several ways, such as different icon sizes, text padding, etc. However, this is not the case for 125% scaling, and if skin creators want to implement custom settings for that size, they must add a toggle which can only be activated manually.

**Describe the solution you'd like**
Similar to the "HIGH_DPI" key for 150% scaling, there should be a line of text which can be used to specify 125% scaling, something like "120_DPI" or "MEDIUM_DPI." I would also like a solution like this for 175% and 200% scaling options, but I think that 125% scaling is the most necessary at the moment.
**Describe alternatives you've considered**
Like stated previously, if custom options are needed for 125% scaling, they must be done through a standard toggle. This could be confusing to the user, especially if they don't know the DPI of their display. This is even more confusing since there is already an option for 150% scaling.

**Additional context**
It would be nice if the default skins received new options for 125% scaling, but it is not necessary unless a current skin is broken or hindered at that size.

I'm not sure how difficult this would be to implement, but I'm hoping that it would be possible to take existing code in the skinning engine for 150% scaling and apply something similar for detection of 125%.

In case there is any confusion to what I am referencing, this is how the "HIGH_DPI" feature is used in the Metro skin:
![150% scaling detection](https://user-images.githubusercontent.com/61938331/93689091-3424f900-fa99-11ea-8f70-e687f574f120.png)

**Comment by ge0rdi** [comment]
Please, try with build from PR #459.
I've added `120_DPI` option to skin engine.

Do you know what DPI is associated with 175% and 200% scaling?
I'd add also those.

I was only able to find values for 100%, 125% and 150% here:
https://docs.microsoft.com/en-us/windows/win32/learnwin32/dpi-and-device-independent-pixels

**Comment by bonzibudd** [comment]
@ge0rdi thanks a lot for this! I couldn't find documentation either when looking, but I am fairly confident that the values would be 168 and 192 from doing a quick calculation. I'll dig deeper and see if I can find confirmation on this.

**Comment by ge0rdi** [comment]
>  am fairly confident that the values would be 168 and 192 from doing a quick calculation

Ah, right. That sounds reasonable (if that scaling percent is linear).
This SU answer agrees with that (though no reference is mentioned):
https://superuser.com/a/1158836/142967

**Comment by bonzibudd** [comment]
@ge0rdi 

I just updated my skin to use the new option, and it seems to work flawlessly. I will close this issue once the other DPI options are added. I think that it would also be worth adding those 225% and 250% options as well, and my calculations match up with SU's if that is helpful. I am confident that they should increase linearly.

**Comment by ge0rdi** [comment]
@bonzibudd 
I've updated PR.

Now there are 6 new DPI options.
Original `HIGH_DPI` should still work as before (defined for 144 DPI and higher).

**Comment by bonzibudd** [comment]
Fantastic! I will close this issue for now. If I find any problems, I will point them out here.

I am curious, if 120_DPI is defined but HIGH_DPI is not, will 144+ DPI choose options for 96 or 120?

**Comment by ge0rdi** [comment]
> I am curious, if 120_DPI is defined but HIGH_DPI is not, will 144+ DPI choose options for 96 or 120?

If you have section that uses `[120_DPI]` in your skin file, that section will be active when system DPI is >= 120 and < 144.

Not sure if this is what you wanted (or what will be the best from skin-maker POV).
The alternative could be that `[120_DPI]` option will be active when system DPI >=120.
But then it may be quite harder to have more sections for various DPIs.

**Comment by bonzibudd** [comment]
Ok, I see. I think most scenarios would need to have both defined if not simply using the old HIGH_DPI option. This shouldn't cause any issues.

**Comment by ge0rdi** [comment]
@bonzibudd 
So do you want keep these _exact DPI_ options?
Or would you rather have _XXX DPI and higher_ kind of options?

Original `HIGH_DPI` is in the second category.

**Comment by bonzibudd** [comment]
@ge0rdi I think it's fine how it is. If you had _XXX DPI and higher_ options, I think that could get confusing, and there would be no need for a 144_DPI and HIGH_DPI. I've already implemented this into a skin of mine and have found no issues regarding this.

**Comment by ge0rdi** [comment]
@bonzibudd 
> I think it's fine how it is.

Just to be clear, you mean it is fine as it is in PR #459, right?

**Comment by bonzibudd** [comment]
@ge0rdi Yep.
