### ISSUE TITLE
Some icons don't adjust their color to the background

### ISSUE THREAD

**Issue by NebelNidas** [Open-Shell/Open-Shell-Menu#466]
**Describe the bug**
Some Programs make use of single-colored jump list icons, whose color gets automatically adjusted to which one is needed. Let's look at MS Teams, for example. When you search for it in the Win10 start menu, which has a white background, the icons are displayed as black:
![image](https://user-images.githubusercontent.com/48808497/94014274-963c7180-fdab-11ea-86af-12b245b5d965.png)

And when displayed on a dark background, e. g. when on the taskbar jump list, they are white:
![image](https://user-images.githubusercontent.com/48808497/94014403-c4ba4c80-fdab-11ea-8ac4-5d650a507b8b.png)

Open Shell, on the other hand, always displays them as white, which makes them look invisible on white backgrounds. Here, on this slightly blue-tinted background, you can just barely make them out:
![image](https://user-images.githubusercontent.com/48808497/94014980-912bf200-fdac-11ea-9ac5-1c04121137c5.png)

**Possible solution**
I don't know how Windows accomplishes it. But if Open Shell wants to implement this behavior accordingly, I think by default it should look at the contrast between the white icon and the background it is displayed on and, if too low, render it in black. However, it should be overridable in skins.

**Comment by NebelNidas** [comment]
Oops, I just noticed that it doesn't only happen to jump list icons. This issue also applies to search results from the Settings app: 
![image](https://user-images.githubusercontent.com/48808497/94018853-54aec500-fdb1-11ea-9a70-f5266150b52e.png)

**Comment by ge0rdi** [comment]
These (modern settings, task jumplists) are basically mono-chrome icons and they are white by default.
They can basically have any color (ideally their color should match color of text of given item).
But the way `Open-Shell` works (it obtains icons once and then caches them) makes it harder to do such _dynamic_ changes.

I'd like to have a look at how it should be done with actual system.

For now I can just recommend to use _dark_ skin where this is no problem at all.
Personally I'm using Tenified skin which fits nicely to Win10 (can be easily googled).

**Comment by bonzibudd** [comment]
This is just an idea, but maybe this should be controlled by the skin. Maybe something like "(Main/List/Search/Submenu)_glyph_color" could define it. I think that would be the best solution since Open-Shell doesn't need to figure that out by itself, or be forced to follow the Windows color, which may not work well with the skin.

**Comment by XenHat** [comment]
By the skin, unless it's set to follow the system's theme (as mentioned in #262). I'm not sure how the system theme is done, either by having two sets of icons (one for dark theme, one for light theme) but if they are white and simply colored black in dark theme mode, this should be easy to fix. If it's not, and there are two icon sets, keeping both in memory would be wasteful, but I'm sure this could be worked out to switch on demand.

I feel bad for giving ge0rdi so much work 🤣

**Comment by ge0rdi** [comment]
> This is just an idea, but maybe this should be controlled by the skin.

Well, its a possibility. But it will be better to simply work out-of-the box with all skins.
As I wrote it will be ideal to use the same color that is used for texts (text have to be visible so its color should be right).

> I'm not sure how the system theme is done, either by having two sets of icons (one for dark theme, one for light theme) but if they are white and simply colored black in dark theme mode, this should be easy to fix.

I wrote that these _icons_ are basically mono-chromatic images. So they can be colored to any color (programatically).
So I assume system just use the same color as it uses for drawing corresponding text.

> I feel bad for giving ge0rdi so much work 🤣

You don't have to. I'm only working on things that I'm interested in ;)

**Comment by ge0rdi** [comment]
I've prepared fix for this (you can test with build from PR #470).
It looks like this on light background:
![image](https://user-images.githubusercontent.com/2453094/94301506-f4fc1980-ff6a-11ea-86ce-c3332b2ba4dd.png)

**Comment by NebelNidas** [comment]
Yeah, I can confirm it works. MS Teams:
![image](https://user-images.githubusercontent.com/48808497/94341828-e108f400-000c-11eb-8af3-cc076147801d.png)

Settings search results:
![image](https://user-images.githubusercontent.com/48808497/94341836-fd0c9580-000c-11eb-85f3-892343602977.png)

Thank you very much, @ge0rdi! 😁👍

**Comment by ge0rdi** [comment]
Fixed in build 4.4.160.
