### ISSUE TITLE
What is Symbols.7z

### ISSUE THREAD

**Issue by yaxunil** [Open-Shell/Open-Shell-Menu#475]
Not actually an issue, but what is 'Symbols.7z'? how is it used? I could not find any info about it on this site and I extensively googled 'Symbols.7z' but found nothing. Thanks

**Comment by XenHat** [comment]
7z is an archive format, and Symbols is the term for the splittable debugging information.You don't need them to use the application but if there ever is a need to debug a specific build, those are required.
