### ISSUE TITLE
Unwanted items added to start menu without user input

### ISSUE THREAD

**Issue by dehcra** [Open-Shell/Open-Shell-Menu#477]
Start menu is being populated with items when user has not selected them. They can also reappear even after the user selects "Remove from this list".

**To Reproduce**
1. Install Open Shell
2. Do not fill Start menu
3. Open a file that uses a Windows app such as "Movies & TV"
4. Close app
5. Open Start menu and find Movies & TV has been added automatically

**Expected behavior**
Menu additions should be chosen by the user, not the application.

**Comment by ge0rdi** [comment]
`Open-Shell` displays _frequently used_ programs on Start menu by default.

You can configure it in `Open-Shell Settings` -> `Main menu` -> `Show recent or frequent programs`.

**Comment by blackcrack** [comment]
@ge0rdi , you should make a Schooling Videos for something like that if comes more peoples like him **\*giggle***
but some Videos could also help for make more prominent on youtube \;)

oh boy, he brings me on ideas ... \*bg*
for luck have i am not a youtubeaccount..
best :smile:

**Comment by dehcra** [comment]
@blackcrack Instead of dumb ideas from 'peoples' like you, how about someone create an actual help forum so new users can ask a question about things that don't appear to work as expected?
