### ISSUE TITLE
UX themes clashing with the taskbar texture

### ISSUE THREAD

**Issue by xXStarBriteXx** [Open-Shell/Open-Shell-Menu#483]
**Describe the bug**
If you apply a UX patcher theme alongside open shell, the modern UI taskbar covers up the glossy one I set.
![Screenshot (2)](https://user-images.githubusercontent.com/72238489/94882195-eb702700-042c-11eb-8f71-9afbe602d561.png)
I'm not sure if it's just the theme or shell itself, but doesn't look as nice... Thanks for reading this and fixing it if you can!

**Version:**
 - Open-Shell: 4.4.152
 - OS: Windows 10 Home 18362.1082

**Comment by blackcrack** [comment]
@xXStarBriteXx have nothing to do with Edge or other webbrowsers..
is this Web-browser Edge ?
best

**Comment by xXStarBriteXx** [comment]
> @xXStarBriteXx have nothing to do with Edge or other webbrowsers..
> is this Web-browser Edge ?
> take an other theme and look if there also an irritation..
> maybe it is this from the theme and not from the Startmenu with enhancements.. only the ux-patch changes so pregnant some look.. and this normally only over the themes who you take from the theme-picker /selector
> 
> best

No, it's just google chrome ^^
And so far I've tried 4 versions of the XP royale theme and they all have that bug :/

**Comment by xXStarBriteXx** [comment]
NEVERMIND I FIXED IT

**Comment by bonzibudd** [comment]
Did you find a solution?

**Comment by bonzibudd** [comment]
I’m not sure if this was still an issue, but if it was, I think it should be fixed by nightly 4.4.161. It changes when the code for the custom Taskbar gets injected.
