### ISSUE TITLE
Win+S bugged when Taskbar is set to Search>Hidden

### ISSUE THREAD

**Issue by pig-cop** [Open-Shell/Open-Shell-Menu#485]
If in Windows 10 the taskbar searchbox is hidden on start-up (the options are: hidden, show search icon, show searchbox) pressing Win+S will not open the windows search menu normally (in a small popup window) but instead will open it in fullscreen.

1. Right click to taskbar, select Search>Hidden
2. Restart Windows
3. Press Win+S
4. The search menu will cover the entire screen

This is how it looks:
![bug_fullscreen](https://user-images.githubusercontent.com/1793444/95004862-1e631800-05f1-11eb-899d-f22e4f9cf2b5.png)

This is how it should be:
![bug_normal](https://user-images.githubusercontent.com/1793444/95004864-20c57200-05f1-11eb-83d8-0e9e9e38a225.png)

- Open-Shell: 4.4.152
- OS: Windows 10 19041

**Comment by bonzibudd** [comment]
I seem to have experienced this myself. However, are you sure this is tied to Open-Shell, and not a Windows glitch?

**Comment by pig-cop** [comment]
You're actually right, it's Windows related.
Just tried to disable Open-Shell on startup, the glitch remains.
It's related to hiding the searchbox or its icon on the taskbar but not it's not Open-Shell's fault.
