### ISSUE TITLE
Search should show User folders (Documents, Music, etc.) as "Programs" instead of "Files" (Windows 7 behavior)

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#486]
**Is your feature request related to a problem? Please describe.**
It is annoying that when I go to search for a user folder, the first options that appear are Settings results instead of the actual folder I'm searching for.

**Describe the solution you'd like**
User folders should appear under the "Programs" category instead of appearing as "Files." This would improve the search experience for instances in which a User folder was searched.

**Describe alternatives you've considered**
I believe you could just put shortcuts to the folders in the Start Menu folder, however I would prefer that list to not be cluttered.

**Additional context**
Here's a screenshot, if it is unclear:
![image](https://user-images.githubusercontent.com/61938331/95016535-90ebec00-0621-11eb-9d9c-8cbce0e0943b.png)

**Comment by ge0rdi** [comment]
I don't quite see how showing _non-programs_ under `Programs` category will make UX better :(

We may eventually consider adding new category `User files` (or something alike) and consider where to place it in search results.
But we should rather avoid inconsistent (non-logical) behavior.

**Comment by bonzibudd** [comment]
I guess that makes sense. Hopefully most people keep their folders in the right-hand menu so they don’t have to search for it at all. I thought it would be worth considering since Windows 7 did actually display user folders as “Programs” and I believe Windows 8 did with some as well. I’ll close this for now, unless I can think of a better solution.
