### ISSUE TITLE
Main menu and Sub-menu width options appear to be broken

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#491]
**Describe the bug**
When I change the "Main menu width" or "Sub-menu width" options on either the 7 or classic styles, they seem to do absolutely nothing. I have tried this in a VM and on my main system, and they both seem to have the same problem. Strangely, however, the "Programs pane width" and "Jumplist pane width" options for the 7 style seem to work fine.

**To Reproduce**
1. Go to "Menu Look" tab in Settings
2. Set width options to something different than the default option
3. Notice Start menu Main menu/Sub-menu width

**Expected behavior**
The width should be larger or smaller, depending on what you set it to.

**Screenshots**
Sub-menu with original width:
![image](https://user-images.githubusercontent.com/61938331/96058481-54a66000-0e59-11eb-8df4-7c6e1e8ef7f5.png)
Sub-menu with 120 char. width (double):
![image](https://user-images.githubusercontent.com/61938331/96058558-8a4b4900-0e59-11eb-82e3-4bbdac6f81c5.png)

**Version:**
 - Open-Shell: 4.4.160
 - OS: Windows build 19041/19042

**Additional context**
It is possible that I am not understanding this option correctly, but it definitely seems like something is broken.

**Comment by CTVCAM8** [comment]
About the Main menu width and Sub-menu width.
They always worked that way.
They really only limit the text width. Try putting in 10 and see what happens.
Adjust the limit higher if there are long names in the menu so they don't get cut off with ",,,"


![Width](https://user-images.githubusercontent.com/44127216/96213653-64dc3f00-0f2e-11eb-8d4d-9147a8646a7d.png)


The 7 style pane adjustments do work differently to the point of absurdity. :) Try 400

**Comment by bonzibudd** [comment]
Ok, I see now. Yep, that is pretty confusing, but at least it's working as it should.
