### ISSUE TITLE
Settings app shows wrong icon in new Insider builds

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#495]
**Describe the bug**
It appears that in some locations (notably the right-hand column), the Settings app shows the old Metro icon instead of the new Fluent icon introduced in new Insider builds. I think that this is because Open-Shell is taking the icon from the SystemSettings.exe file used in Windows 8, instead of whatever location is used for the new icon.

**To Reproduce**
1. Click Start button
2. Activate right-hand icon for Settings item
3. Notice Metroey-ness of icon

**Expected behavior**
The icon should be the same that is used in the rest of Windows

**Screenshots**
Right-hand icon (incorrect):
![image](https://user-images.githubusercontent.com/61938331/96391590-41600100-1187-11eb-8ea3-3df2bde1a335.png)

Icon shown in apps list (correct):
![image](https://user-images.githubusercontent.com/61938331/96429388-e18d4880-11ce-11eb-9c7b-4bf82ab800c6.png)

**Version:**
 - Open-Shell: 4.4.160
 - OS: Windows build 20236

**Additional context**
Not much else to add, it seems like this should be an easy fix. Also, this issue does not appear for the icon in Search or the Apps list.

**Comment by ge0rdi** [comment]
Could you also add version of Windows where you can replicate it?
And also screenshot of how do you think the icon is supposed to look like.

**Comment by bonzibudd** [comment]
I updated the original post.

**Comment by bonzibudd** [comment]
Can confirm: OSM uses the icon from `SystemSettings.exe,10` instead of `windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel`. I don't know if OSM can currently use icons from those locations, but hopefully it is possible to change it to the new one.

**Comment by ge0rdi** [comment]
> I don't know if OSM can currently use icons from those locations, but hopefully it is possible to change it to the new one.

Currently only _standard_ icon location (`image,id`) can be used. We'd need to add the possibility to use icon from modern packages for this custom menu. Also we'd need to support a fallback for older systems.

**Comment by bonzibudd** [comment]
@ge0rdi 

Found a solution, actually. The icon seems to auto-populate if you replace the settings item link with `shell:AppsFolder\windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel`:
![image](https://user-images.githubusercontent.com/61938331/98045188-123bc780-1df6-11eb-865f-af131c269731.png)

Hopefully there's an elegant way to implement this as the default without disrupting older versions.

**Comment by mzso** [comment]
I get the old icon on Win10 is this meant to change it on 11?

**Comment by ge0rdi** [comment]
@mzso 
Windows 10 contains just the old icon.
