### ISSUE TITLE
Update the icon for the "Apps" item to match Win10

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#497]
**Is your feature request related to a problem? Please describe.**
It's not a usability issue, but just a visual inconsistency that sticks out. Currently, the icon for the Apps menu uses a Windows 7/8 style folder, when Windows 10 folders use a different design.

**Describe the solution you'd like**
The icon should be updated to match the Windows 10 style, one way or another. However, the old icon should be kept for users of Windows 8.

**Screenshot**
![image](https://user-images.githubusercontent.com/61938331/96526788-97e34300-124c-11eb-9d00-c8e262ae77aa.png)

**Additional context**
I could try to make a new icon myself if nobody else makes one. However, I don't know where to find a folder icon in the "Opened" state at the 16x16 size, which the current icon uses. Maybe it should be updated to be more similar to the user folders, which don't show a folder at all at the lower size.

**Comment by kamyk2000** [comment]
Have you seen this?

https://coddec.github.io/Classic-Shell/www.classicshell.net/forum/viewtopica462.html?f=17&t=921

**Comment by bonzibudd** [comment]
I haven't, but the problem is that custom icons can't be applied to the "Apps" item in the Windows 7 style. Even then, it would be better to limit how much effort the user needs to put into the appearance of the menu.

**Comment by kamyk2000** [comment]
My solution was to put the apps folder on the right pane as an expandable menu using that icon.  I'm guessing you want to change the folder in the all programs section?

**Comment by bonzibudd** [comment]
I'm going to close this specific issue, now that there are several folder styles in Windows 10, it may be best to create several icons for different versions. I may or may not try to add this.
