### ISSUE TITLE
Control panel keeps opening up as "Large icons", how do I change it to open as "Category"?

### ISSUE THREAD

**Issue by Joe23232** [Open-Shell/Open-Shell-Menu#502]
![image](https://user-images.githubusercontent.com/34926497/96823421-36072100-1478-11eb-86d8-ac38b5a061fc.png)

Everytime I open up Control Panel on Windows 10, it opens up like this. I change it to Category but the next time I open it again opens as "Large icons".

How do I get Open Shell to automatically open up as "Category" for Control Panel?

**Comment by ge0rdi** [comment]
Hmm, not sure how this could be related to `Open-Shell`.
Does it happen also if you uninstall `Opne-Shell`?

Does changing view type to `Category` does something?

**Comment by Joe23232** [comment]
> Does it happen also if you uninstall Opne-Shell?

Nope sorry mate

> Does changing view type to Category does something?

It just shows control panel in a different view.

**Comment by ge0rdi** [comment]
I have no clue what could be going on and how it should be related to Open-Shell.
I can't replicate such behavior. For me the Control Panel remembers last view type selected (standard Windows behavior).

What Windows version do you have?

**Comment by Joe23232** [comment]
I have Windows 10. But it doesn't matter, I was the one who created the issue, Open-Shell is not at fault at all, any normal user would not have such issues, people like who who are serious about privacies change all sorts of registry keys and could potentially end up breaking stuff.

**Comment by bonzibudd** [comment]
Try enabling "Use Categories view for the Control Panel."

**Comment by Joe23232** [comment]
> I have Windows 10. But it doesn't matter, I was the one who created the issue, Open-Shell is not at fault at all, any normal user would not have such issues, people like who who are serious about privacies change all sorts of registry keys and could potentially end up breaking stuff.

Sorry wrong comment, It hought this was for the other post.

**Comment by Joe23232** [comment]
@bonzibudd Where is that located mate?

**Comment by bonzibudd** [comment]
@Joe23232 you should find it under the "Main Menu" options, you can also search for it.

**Comment by Joe23232** [comment]
![image](https://user-images.githubusercontent.com/34926497/96866332-e4ca5200-14b6-11eb-93c3-913879c81150.png)
Are you talking about this one mate?

**Comment by bonzibudd** [comment]
No, sorry, I should clarify. It is in the Open-Shell menu settings. By default, it overrides the option you set in the Control panel itself.

**Comment by Joe23232** [comment]
I see, that seems to solve it mate, thank you very much :)

But where is `Use Categories view for the Control Panel` actually located? I searched for it and enabled it, but I don't know where that setting is placed, do you know mate?

**Comment by Joe23232** [comment]
Nevermind I found it, thanks :)

**Comment by ge0rdi** [comment]
> It is in the Open-Shell menu settings. By default, it overrides the option you set in the Control panel itself.

Wow, didn't even know there is such option in `Open-Shell`.

**Comment by ge0rdi** [comment]
@Joe23232 
I guess we can close this one?

**Comment by Joe23232** [comment]
Oh yes I will close it.
