### ISSUE TITLE
How do I automatically get an application to be listed in Open Shell if I open it?

### ISSUE THREAD

**Issue by Joe23232** [Open-Shell/Open-Shell-Menu#503]
With one of my other computers if I search for "notepad" (as an example) it will automatically put it as a shortcut in the start menu. But with my other computer this does not happen at all.

I tried to export the xml file from the other computer and imported into this computer but it did not change anything. I was just wondering if somebody knew anything?

Also in one of my computer it fills the entire start menu with applications but on this PC it doesn't. Is this a bug or something?

Edit: On this PC
![image](https://user-images.githubusercontent.com/34926497/96827010-5b982880-1480-11eb-868e-985644a2482c.png)

I seem to already have this setting enabled so how come it is not working?

**Comment by ge0rdi** [comment]
You need to run given application few times. Then it should show in `Frequent programs` list. The list should show programs you are using frequently.

**Comment by Joe23232** [comment]
I have litereally opened "Notepad" many times but it still fails, I have tried with other applications as well.

On the other PC  I only have to open notepad once and it will show, even when I remove it.

**Comment by Joe23232** [comment]
Ok after some investigations it appears after running [ShutUp10](https://www.oo-software.com/en/shutup10) causes this issue (after running it on the other PC with the EXACT same settings as my current PC). I am not too sure which setting is responsible for it though.

![image](https://user-images.githubusercontent.com/34926497/96831095-2b548800-1488-11eb-94a9-4aa68a86db68.png)
![image](https://user-images.githubusercontent.com/34926497/96831149-3e675800-1488-11eb-9af5-6b9c34b81f67.png)
![image](https://user-images.githubusercontent.com/34926497/96831171-4e7f3780-1488-11eb-936b-3b39f34c82bc.png)
![image](https://user-images.githubusercontent.com/34926497/96831189-563edc00-1488-11eb-88b7-a3fd5bd333be.png)


I am going to look into it though but do you know which setting is causing this issue?

**Comment by Joe23232** [comment]
Ignore the above it is not the cause of the issue.

![image](https://user-images.githubusercontent.com/34926497/96831321-956d2d00-1488-11eb-96fe-a143f4059919.png)

I enabled this setting and it works on the other PC but not current PC for some reason, is there another cause of this?

**Comment by ge0rdi** [comment]
> I enabled this setting and it works on the other PC but not current PC for some reason, is there another cause of this?

Yes, that setting has to be enabled, so that Windows tracks usage of programs and `Open-Shell` can then obtain the list of frequent programs.
It should work. Maybe try to reboot.

**Comment by Joe23232** [comment]
It turns out after enabling the setting, I had to "Reset All Settings" after a reboot and I also cleared all the cache data
