### ISSUE TITLE
Classic/Two column menu: Use "Help" icon from imageres.dll instead of shell32.dll

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#506]
**Is your feature request related to a problem? Please describe.**
Not a usability problem, but an inconsistency which has bugged me. The "Help and Support" item uses the Shell32.dll file for its icon, which hasn't been updated since Windows Longhorn. On the other hand, the Imageres.dll file from Vista uses an updated icon which looks better on modern Windows versions.

**Describe the solution you'd like**
The default configuration should change the location of the "Help and Support" icon to Imageres.dll in order to fit better on Windows 7 through 10. 
For some reason, the 7-style uses the newer icon, but the classic styles still use the old one. This dll is available on all Windows versions which support OSM, so there's no reason not to use it.

**Describe alternatives you've considered**
You can change the icon yourself relatively easily, but the item should look good without needing to be changed by the user.

**Screenshots**
Current icon:
![image](https://user-images.githubusercontent.com/61938331/96942308-c22e3e00-14a2-11eb-9c0a-ae84f1106100.png)

What it should look like (Will look different on older versions):
![image](https://user-images.githubusercontent.com/61938331/96942551-762fc900-14a3-11eb-8826-d27d22f9443b.png)

**Comment by ge0rdi** [comment]
Could you possibly check also older Windows (7, 8) whether they contain such icon in that file?
Eventually put screenshots of those icons here too, so we have them for the reference.

**Comment by bonzibudd** [comment]
Yes, I confirmed that 7 and 8 have the help icon in that location (imageres.dll,99).
7:
![image](https://user-images.githubusercontent.com/61938331/97008990-87172380-1511-11eb-8b04-301420bf1f5e.png)

8:
![image](https://user-images.githubusercontent.com/61938331/97009779-8763ee80-1512-11eb-9638-6f7991a8a912.png)

**Comment by bonzibudd** [comment]
Very good!
