### ISSUE TITLE
Run Standalone?

### ISSUE THREAD

**Issue by mhsimkin** [Open-Shell/Open-Shell-Menu#511]
Is it possible to run Open-Shell from the command prompt or off the start menu?

I'm building out a Windows RemoteApp (RemoteApps and Desktop Connection) infrastructure.  If I have some sort of menu/dock as the application being started then I don't need to have each application configured as a remote application.

As long as the remote application gets launched from an already running remote application things are fine.

Therefore, I would like to run Open-Shell as a remote app that is used to then launch other remote apps.

Thanks

**Comment by ge0rdi** [comment]
You can simply run `C:\Program Files\Open-Shell\StartMenu.exe`.

**Comment by mhsimkin** [comment]
Thanks.

**Comment by mhsimkin** [comment]
My apologies for taking so long to get back to this discussion.  Just launching the StartMenu.exe doesn't resolve my issue.

When using the RemoteApps feature of RDP, the taskbar/start menu from the remote system is not rendered on the host.  Therefore, anything that expects a specific set of keystrokes and/or mouse movements does not work, unless the active window is from the remote system.

What I am looking for is a way to run Open-Shell in it's own window that is always visible.  This would allow the Open-Shell executable to be running on the remote system, but rendered by the host.

Thanks

-marc

**Comment by ge0rdi** [comment]
I'm afraid that's not possible currently.
Not even sure if it would be possible to modify `Open-Shell` to behave that way.
Though I have no experience with Windows RemoteApps.

**Comment by mhsimkin** [comment]
Thanks, not surprised by the answer.
