### ISSUE TITLE
"OS upgrade without user interaction" page

### ISSUE THREAD

**Issue by tsherrington** [Open-Shell/Open-Shell-Menu#513]
Sorry if this is the wrong place to put this, but the code on this page:
schtasks /Create /RU "NT AUTHORITY\SYSTEM" /SC ONSTART /TN "Open-Shell OS updgrade check" /TR "%ProgramFiles%\Open-Shell\StartMenu.exe -upgrade -silent"

Is incorrect - it should be:
schtasks /Create /RU "NT AUTHORITY\SYSTEM" /SC ONSTART /TN "Open-Shell OS upgrade check" /TR "'%ProgramFiles%\Open-Shell\StartMenu.exe' -upgrade -silent"

(Note the '%ProgramFiles%\Open-Shell\StartMenu.exe' part - otherwise, Task Scheduler will make the command:
c:\program
and the arguments be files\Open-Shell\StartMenu.exe -upgrade -silent

With this change the command becomes:
c:\program files\open-shell\StartMenu.exe
and the arguments are -upgrade -silent

Thanks for the great program.  Really love it.

**Comment by ge0rdi** [comment]
Fixed.

Thank you for reporting 👍
