### ISSUE TITLE
Start button context menu: Customize and/or remove header

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#515]
**Is your feature request related to a problem? Please describe.**
In the OSM context menu for the Start button, it displays the text `== Open-Shell Menu ==` at the top. There is no built-in option to customize or remove the text if the user finds it unnecessary.

**Describe the solution you'd like**
In the "Context Menu" section of the Start menu settings, there should be a toggle to enable or disable the header. This option should also remove the separator underneath it, if necessary. Additionally, it would be nice to be able to customize the text, so it could display information such as your name or the Windows version.

**Additional context**
I will also add that I think the default text should just say `Open-Shell Menu` instead of `== Open-Shell Menu ==`. I think the equal signs are unnecessary, but this is up to the developers to decide.

**Screenshot**
![image](https://user-images.githubusercontent.com/61938331/97764128-fe395280-1ae3-11eb-9562-b2f9e843e3bb.png)

**Comment by NebelNidas** [comment]
I think we should completely remove this menu from the start button and always show the Win+X menu, like Windows does it by default. But where to put this Open-Shell context menu then, you may ask?

Well, in Windows 7, you could simply right-click the the Start menu at an empty place and it would give you the according context menu, it's a better option if you ask me:
![](https://www.groovypost.com/wp-content/uploads/2011/12/image69.png)

**Comment by ge0rdi** [comment]
> always show the Win+X menu, like Windows does it by default.

You can do this easily in `Controls -> Right click opens Win+X menu`.

After that right click on Start behaves just like in original Start menu.
And `Shift`+`Right click` shows `Open-Shell` menu (I'm using it like that).

**Comment by NebelNidas** [comment]
@ge0rdi  Yeah, I'm using it the same way, too. Nevertheless I think it would still be better to do it the Windows-7-way, in order to not confuse (new) users and behave more like default Windows 🤔

**Comment by bonzibudd** [comment]
I’m happy with the change to this as presented in #1222, so when that goes through I’ll close this topic. I’d still like to see the “Properties” menu like Win7, but that’s a separate issue.

**Comment by bonzibudd** [comment]
Closing in favor of #542 with fixes from #1222.
