### ISSUE TITLE
Can I design Xfce or MATE-like menu, and how?

### ISSUE THREAD

**Issue by bckpkol** [Open-Shell/Open-Shell-Menu#52]
Which files should I edit?

**Comment by ibuprophen1** [comment]
@bckpkol, have you been able to figure this out or similar? 


~Ibuprophen

**Comment by Ibuprophen** [comment]
I'm just going to close this issue as being abandoned/unresponsive by the OP Issuer. 

If you would like, please open a new issue with a detailed explanation regarding your issue.

Thank you very much for your time and understanding with this! :-)

~Ibuprophen

**Comment by coddec** [comment]
@bckpkol 
I suppose, the folder we should look into for skin is
https://github.com/Open-Shell/Open-Shell-Menu/tree/master/Src/Skins
