### ISSUE TITLE
How to contribute translation to Open-Shell? Templates, guide etc. ? (Norwegian)

### ISSUE THREAD

**Issue by coddec** [Open-Shell/Open-Shell-Menu#520]
> Hi! I have been an active user of Classic Shell through many years, and would like to support the "new" OpenShell project with a Norwegian translation. I haven't created the translation yet, but would like to know where to submit it and in what format, if it's interesting to include it :-)   Thank you!  Best regards ddybing

@ddybing

**Comment by ddybing** [comment]
Thanks for creating this issue. My bad, though - I didn't see it until now that there is already a Norwegian translation, and it seems to be correct / without any spelling errors. Sorry!

**Comment by coddec** [comment]
> Thanks for creating this issue. My bad, though - I didn't see it until now that there is already a Norwegian translation, and it seems to be correct / without any spelling errors. Sorry!

No problem ;)
Appreciate your interest 😊
Maybe there are translation required in the future, if you can help then that will be great! 😁

**Comment by NebelNidas** [comment]
For the general question of how to create translations, see here: https://coddec.github.io/Classic-Shell/www.classicshell.net/forum/viewtopic036c.html?f=20&t=1344
