### ISSUE TITLE
Explorer try to connect to the Internet

### ISSUE THREAD

**Issue by circcc** [Open-Shell/Open-Shell-Menu#523]
I installed Open-Shell v4.4.160 without Open-Shell Update.
After that, Explorer try to connect to the Internet.
Previous versions don't have this problem.

**Comment by bonzibudd** [comment]
We need some more information. Is there an error message you're getting from Explorer? A screenshot would be useful.

**Comment by circcc** [comment]
When I run Explorer after booting Windows, comodo firewall pops up the Explorer Internet connection alert window. I just block it.

**Comment by blackcrack** [comment]
can you get the Domainname or the ip where want connect, if the Firewall tell a alert.

**Comment by altimumdelta** [comment]
Probably trying to connect to get some theme/icons/metadata for games and devices, or it may be something new they added in recent version. You need to check it with utilities to see what is it trying to do.

**Comment by ge0rdi** [comment]
This is most likely caused by `Open-Shell` update checks.
You can disable automatic update checks in `Open-Shell Update`.
