### ISSUE TITLE
Taskbar changes Transparency upon position change

### ISSUE THREAD

**Issue by RishiVora** [Open-Shell/Open-Shell-Menu#527]
Hii,
I just started using Open Shell on Windows 7 SP1. I just wanted a transparent taskbar and did not want to change the start menu look.
Because I have patched my system with Theme Resource Changer and am using [THIS](https://www.deviantart.com/sagorpirbd/art/Windows-10-RTM-Themes-for-Win-7-FINAL-550460125) custom theme.
So the problem is that the when the taskbar is at 'Bottom', it works fine, but when I change the taskbar position to 'Top', transparency goes away and it changes to my custom theme's default colour (ie. black)

**ORIGINAL:**
![Default](https://user-images.githubusercontent.com/74235469/98650409-dad19b80-235e-11eb-9868-ca53fb20463a.JPG)

**BOTTOM:**
![Bottom](https://user-images.githubusercontent.com/74235469/98650477-f63ca680-235e-11eb-855f-4eef8f7b6b8d.JPG)

**TOP:**
![Top](https://user-images.githubusercontent.com/74235469/98650554-0e142a80-235f-11eb-9cfa-f17bcce6c74e.JPG)

How can I fix this?

Version:
 - Open-Shell:  4.4.160
 - OS: Windows 7 SP1

**Comment by bonzibudd** [comment]
I’ve had a similar experience. Windows 7 seems to be buggy with the Taskbar customization. I can’t think of a real fix as of now.

**Comment by bonzibudd** [comment]
Actually, try the latest nightly version. It has some changes to taskbar skinning.

**Comment by RishiVora** [comment]
> Actually, try the latest nightly version. It has some changes to taskbar skinning.

Tried it. But still no luck.
