### ISSUE TITLE
Error: System.AppUserModel.ToastActivatorCLSID on update

### ISSUE THREAD

**Issue by Jamesstevens-3rd** [Open-Shell/Open-Shell-Menu#528]
Updated from v4.4.152 to 4.4.160 via full download (not the updater) and got this error message popup before the installer finished.

![upgrade install error](https://user-images.githubusercontent.com/55051487/98702602-7c161d00-2372-11eb-82a4-428ad81f3b3e.png)

OS Windows 8.1 x64 Pro.

**Comment by bonzibudd** [comment]
This should be fixed in later nightly releases. It's a compatibility issue between the new toast additions and older unsupported versions.

@ge0rdi unless the fix wasn't applied to 8.1?

**Comment by ge0rdi** [comment]
This is fixed in latest nightly builds.
