### ISSUE TITLE
Consider removing Classic IE

### ISSUE THREAD

**Issue by asianmusicguy** [Open-Shell/Open-Shell-Menu#529]
With Microsoft abandoning internet explorer and finally turning edge into something reasonable  classic IE is redundant

**Comment by bonzibudd** [comment]
I think the developers are considering splitting the Open-Shell products into different packages. So it would probably be good to put ClassicIE in a "Deprecated" state.

**Comment by asianmusicguy** [comment]
come to think it does "classic file explorer" work under windows 10 or is the menu the only truly working component now?

**Comment by bonzibudd** [comment]
It does still work with Win10, but it requires a few extra steps and doesn't work well with Dark mode.

**Comment by blackcrack** [comment]
> 
> 
> With Microsoft abandoning internet explorer and finally turning edge into something reasonable classic IE is redundant


in WinXP and Win7 it is important,

in the Installer it is possible to deselect it for your Ordering system.

The Open-Shell is for multible WinNT versions and not only for Win10,
hold that in the brain and therewith is this Tread closeable ..

thank you.

**Comment by ge0rdi** [comment]
If it was up to me to decide, `Classic IE` was removed long time ago.
I can't see any valid reason to use IE these days.

Well, unless one is forced to use some corporate site that still uses Silverlight or some other obsolete technology.
Still in such case one can simply use IE just for that site (without the need for special additions) and use _normal_ browser for the rest.

Though as @blackcrack already mentioned it is easy to simply deselect `Classic IE` during installation.
Thus I'm closing this.

**Comment by asianmusicguy** [comment]
It’s easy is it logical no I shouldn’t as a user have to concern myself with deselecting components nor should their  existence hinge on any chance that someone may use a long deprecating operating system  Open shell is great but trim the fat a bit remove classic ie update classic file explorer for windows 10 compatibility and move the project forward as best you can

**Comment by blackcrack** [comment]
Classic Shell is down compatible and therewith should what's programmed not removed for older Systems 
If it hurts in your eyes and you so lazy to not able to remove a Checkbox by install, should you use a brain connector .

pffhh...

**Comment by NebelNidas** [comment]
I wouldn't remove Classic IE *just* yet (maybe in a few years), but in my opinion it should be de-selected by default. Most people only care about the Start menu part of Open Shell, so the other (mostly unsupported) portions shouldn't be installed by default.
