### ISSUE TITLE
"Background" github wiki page refers to old repo

### ISSUE THREAD

**Issue by hatalmasalma** [Open-Shell/Open-Shell-Menu#535]
Hello,
The Github wiki page "Background" (link: https://github.com/Open-Shell/Open-Shell-Menu/wiki/Background) states:
"Future development will be committed at: https://github.com/passionate-coder/Classic-Start"

But the referred repo's readme states:
"Renamed to NeoClassic-UI - https://github.com/NeoClassic-UI/Menu
Then renamed to Open-Shell - https://github.com/Open-Shell/Open-Shell-Menu"

So I gues the current repo (Open-Shell/Open-Shell-Menu) is the correct one.
Could you clarify it at least on the wiki page?

You know if it would worth still mentioning the (passionate-coder/Classic-Start) repo, but please make it clear, that this is the current branch.

Thanks

**Comment by ge0rdi** [comment]
I have removed obsolete information from `Home` wiki page.
Thanks for reporting.
