### ISSUE TITLE
'Welcome' boot screen loads for long time after open-shell/classic-shell installation

### ISSUE THREAD

**Issue by pardovot** [Open-Shell/Open-Shell-Menu#540]
**Describe the bug**
First, I don't actually know if it's a bug, but I thought I'd share this.
I'm running a freshly installed windows on my new Nvme ssd, Windows 10 Pro 2004 build 19041.630
I started with classic-shell(as I didn't even knew development continued), I noticed that the moment I installed it, after restarting my PC, when the boot reaches the 'Welcome' part it simply loads for around 15-30 seconds.
I tried to uninstall and install the software many many times, both classic-shell and now after finding this the latest open-shell release, the issue consistently happened when classic-shell was installed, and consistently didn't happen when classic-shell is not installed.

**To Reproduce**
1. Run Windows 10 Pro 2004 build 19041.630
2. Install Classic/Open-shell
3. Welcome boot screen should take long time to load?

**Expected behavior**
Welcome boot screen should take around 5 seconds max to continue?

**Version:**
 - Open-Shell: 4.4.160 / Classic-Shell 4.3.1
 - OS: Windows 10 Pro 2004 build 19041.630

**Additional context**
Again, don't know if this is somehow only for me, related to the app, unrelated to the app, actual bug or not, but I currently feel like I can't use it and it seems pretty clear that this is the cause.
Really hope to find a solution as this is the best software ever.

Thanks.

**Comment by CTVCAM8** [comment]
Win10 V 20H2 (OS Build 19042.630)
Fast SSD, loaded with many programs. Has all the Windows Updates back to Win8.

I did notice about a week ago that the welcome screen took a lot longer.
Did not count at the time. Assuming around 30 or more seconds.
After a few restarts, the welcome screen is around 12 to 15 seconds. 
I had OpenShellSetup_4_4_152 then installed OpenShellSetup_4_4_160 yesterday. 
Still around 12 to 15 seconds.
It was always quick before, 3 to 5 seconds.

Another drive
Win10 V 20H2 (OS Build 19042.630)
Slow old SSD, loaded with one MS Office program, really that's it. Freshly installed about six months ago.
The welcome screen took around 5 seconds.
After installing ClassicShellSetup_4_3_1 changed to around 6 seconds.
After installing OpenShellSetup_4_4_160 same time, around 6 seconds.

Who knows, it could be the more bloated the system is, 
a new Windows update is doing some extra scanning behind the scenes each and every boot?

**Comment by pardovot** [comment]
As sort of a workaround, I simply disabled the 'Start automatically for this user' option and added the open shell manually to the start menu folder. It doesn't start up right away on windows boot as with that option, and takes around 5-10 more seconds, but as long as I'm not stuck for 30 seconds on the welcome screen that's fine by me...

As CTVCAM8 said, I have a feeling it's really related in a way to how bloated your system is. No idea why, or if it's even true, but seems like it.
