### ISSUE TITLE
Can not access network location _\.

### ISSUE THREAD

**Issue by iiDk-the-actual** [Open-Shell/Open-Shell-Menu#548]
**Describe the bug**
When I try to install OpenShell versions 4.4.160 and 4.4.152 it has an error about "Can not access network location _\."

**To Reproduce**
Get to "Creating Shortcuts" in any installation.

**Expected behavior**
I thought it was gonna... what do you think would happen? Install the damn shortcuts!

**Screenshots**
https://i.gyazo.com/e49bcf82c976e30fbf8edb3846190ce7.png

**Version:**
 - Open-Shell: 4.4.160 & 4.4.153
 - OS: Windows 10 Home 1909

**Additional context**
None

**Comment by ge0rdi** [comment]
`Open-Shell` installer is not supposed to access any network locations.

Try to run installer with following parameters:
`/l* log.txt`

It should create `log.txt` log file. Please attach it for further investigation.

**Comment by blackcrack** [comment]
firewall ?

**Comment by bonzibudd** [comment]
Just my two cents, it sounds like more of an issue with the installer service than Open-Shell specifically. I would see if you get similar errors on other installers.

**Comment by blackcrack** [comment]
monney monney monney, bring it on, any cent count's @bonzibudd ! :grin:

**Comment by iiDk-the-actual** [comment]
> Just my two cents, it sounds like more of an issue with the installer service than Open-Shell specifically. I would see if you get similar errors on other installers.

yes, infact. blocksworld, adventure academy, probably autodesk, most other windows installers.
at least i installed mc before this bug existed

**Comment by iiDk-the-actual** [comment]
> `Open-Shell` installer is not supposed to access any network locations.
> 
> Try to run installer with following parameters:
> `/l* log.txt`
> 
> It should create `log.txt` log file. Please attach it for further investigation.

[log.txt](https://github.com/Open-Shell/Open-Shell-Menu/files/5604993/log.txt)
still just error 1606

**Comment by ge0rdi** [comment]
@iiDk-the-actual 
Hmm, I don't see anything useful in the log.

Please, try to create _verbose_ log using this switch:
`/lvx* log.txt`

**Comment by iiDk-the-actual** [comment]
> @iiDk-the-actual
> Hmm, I don't see anything useful in the log.
> 
> Please, try to create _verbose_ log using this switch:
> `/lvx* log.txt`

[log.txt](https://github.com/Open-Shell/Open-Shell-Menu/files/5608385/log.txt) verb log

**Comment by ge0rdi** [comment]
It seems that `SHGetFolderPath` API returned wrong path for _Startup_ folder.
It returned `_` (instead of real path).

Please check `Startup` value in `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders` registry key.
By default it should be `%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`.

**Comment by iiDk-the-actual** [comment]
> It seems that `SHGetFolderPath` API returned wrong path for _Startup_ folder.
> It returned `_` (instead of real path).
> 
> Please check `Startup` value in `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders` registry key.
> By default it should be `%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`.

didn't work and i may have corrupted by registry data. what is it supposed to be

**Comment by ge0rdi** [comment]
I wrote it should have value `%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`.

**Comment by iiDk-the-actual** [comment]
> I wrote it should have value `%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`.

can u still help me with this tho

**Comment by ge0rdi** [comment]
Download and extract this file:
[StartupFix.reg.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/5609490/StartupFix.reg.zip)

Then apply extracted .reg file (just double click on it).

**Comment by iiDk-the-actual** [comment]
> 
> 
> Download and extract this file:
> [StartupFix.reg.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/5609490/StartupFix.reg.zip)
> 
> Then apply extracted .reg file (just double click on it).

it worked! tysmmmm
