### ISSUE TITLE
Taskbar text stays unchanged despite specifying taskbar text color in OpenShell's taskbar settings tab

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [Open-Shell/Open-Shell-Menu#549]
**Describe the bug**
Taskbar text color doesn't change when specifying a custom text color.
**To Reproduce**
1. Go to Taskbar under OpenShell settings menu
2. Click on 'Taskbar text color'
3. Specify a custom color of your choosing
4. Nothing at all changes

**Expected behavior**
Taskbar Text color should have changed according to the specified color in open shell settings

**Screenshots**

**Version:**
 - Open-Shell: 4.4.160
 - OS: Windows 10 1903

**Additional context**

**Comment by bonzibudd** [comment]
Tried this myself. It didn't apply automatically, I had to exit the Start menu process and relaunch. I hope this helps.
