### ISSUE TITLE
Release list confusing, multiple sources, missing builds

### ISSUE THREAD

**Issue by DAOWAce** [Open-Shell/Open-Shell-Menu#55]
So we go from [one link](https://github.com/coddec/Classic-Shell) from the forums to [another link](https://github.com/passionate-coder/Classic-Start)... get [here](https://github.com/NeoClassic-UI/Menu) and the release list is [28 days old](https://github.com/NeoClassic-UI/Menu/releases) with the original software then 2 preview builds, and a link to [appveyor](https://ci.appveyor.com/project/passionate-coder/classic-start/branch/master/artifacts) with many builds not here.. and then the page at appveyor says it's obsolete.  Look in the commit changes here, find another [link](https://github.com/NeoClassic-UI/Menu/release)..

**What is the actual main release of the software and where can we track the releases?**

Is this the current and active development area? https://github.com/NeoClassic-UI/Menu

Is this the current active release build? https://ci.appveyor.com/project/passionate-coder/classic-start
Or is this?  https://ci.appveyor.com/project/passionate-coder/menu

It's just all too confusing.

I wanted to see if anyone took up the reigns to update Classic Shell after problems installing the latest Java (10.0.2) breaking explorer/quicklaunch and had to run through so much stuff to figure out just where the current release of the software is.

**Comment by coddec** [comment]
@DAOWAce 
Current latest dev builds are here 
https://ci.appveyor.com/project/passionate-coder/menu

These confusions are mostly due to naming issue: https://github.com/NeoClassic-UI/Menu/issues/36

Latest builds are always on AppVeyor, but the exact link will only settle after the name of this project is settle, hopefully it clears some confusion for you 😃

**Comment by coddec** [comment]
There may will be a wiki page for clarification.

**Comment by ge0rdi** [comment]
@coddec 
We should put the link to latest nightly build from master to the front page.
It should point to:
https://ci.appveyor.com/project/passionate-coder/menu/branch/master/artifacts

I've also removed obsolete links from Releases page.

**Comment by ibuprophen1** [comment]
@ge0rdi, I personally don't believe that the AppVeyor link is a good choice. 

I feel that the AppVeyor link is more of an RC (Release Candidate) and doesn't reflect all merges, fixes, etc... within those builds. 

The Wiki page idea from @coddec is a good one but, i would recommend that it's Stated Clearly on the Main Github Readme page first. 

Another idea others use is to include it on the Releases tab of Github with the Clarification of it being a Stable, Alpha, Beta, Release Candidade, etc... (though I'm not suggesting all of those labels but, just suggesting one or more of those clarifications or similar). 


~Ibuprophen

**Comment by ge0rdi** [comment]
I have added link to latest nightly build to project main page.

There is no need to create official Github release for every build containing minor changes.
We should create releases only when substantial changes were done (such as RS5 support fix).

**Comment by ibuprophen1** [comment]
I was just proving some personal thoughts and was just reflecting some options that others have used as well @ge0rdi... :-) 


~Ibuprophen

**Comment by coddec** [comment]
@ibuprophen1 
>The Wiki page idea from @coddec is a good one but, i would recommend that it's Stated Clearly on the Main Github Readme page first.

Just to clarify, it was @XenHat 's idea ;)

I don't want to steal haha :D

**Comment by ibuprophen1** [comment]
I thought that all the ideas are from @coddec and @XenHat just says Yes Sir Boss? 

HA-HA! 😷

**Comment by coddec** [comment]
Eventually yes, and @ge0rdi too.
We've discussed, but @XenHat came up with that idea first, so at least, credit should goes to @XenHat  :P

**Comment by ibuprophen1** [comment]
I was only kidding... 😱

I wasn't aware that there was a specific structure to your team. 

I thought that it was like The Beatles... 

Which ones the "Shy one", "Cute One", "Quiet One", etc... 😰


~Ibuprophen

**Comment by XenHat** [comment]
> It's just all too confusing.

I'm sorry @DAOWAce. We ran into a branding and copyright issue, twice. We will update the links and documentation the best we can when this is sorted. Apologies for the inconvenience.

**Comment by XenHat** [comment]
> I feel that the AppVeyor link is more of an RC (Release Candidate) and doesn't reflect all merges, fixes, etc... within those builds.

Not to mention that the software CAN break and still build. These links should be reserved for the users who have experience in bug reporting and/or are willing to closely and actively cooperate with us for bug fixing.
