### ISSUE TITLE
Start button disappears

### ISSUE THREAD

**Issue by MacCraker** [Open-Shell/Open-Shell-Menu#557]
**Describe the bug**
When I try to use the "Replace Start Button" option and save, the start button disappears, no matter what.

**To Reproduce**
1. Go to the start button.
2. Right click on it.
3. Left click on "Start button" if not already selected.
4. Left click on the box next to "Replace Start Button".
5. Left click on OK.
6. See the start button disappear.

**Expected behavior**
I expected the start button to be correctly replaced with the .png file I was trying to use.

**Screenshots**

**Version:**
 - Open-Shell: 4.4.160
 - OS: Windows 7 Home Premium 64-Bit EN + SP1

**Additional context**
I am using the classic theme in windows and the classic skin in the start menu, which is one column, with small taskbar buttons and the taskbar buttons set to "Combine when taskbar is full", and I am using a display that has a resolution of 1366x768.

**Comment by bonzibudd** [comment]
Some troubleshooting:
 - Do the included Start buttons work properly? (Aero, Classic)
 - Does your png have 3 vertical sections for the button “modes”? (Standard, hot, pressed)
 - Some options you could try changing: Taskbar size, combine behavior, switch to Aero theme

I would personally try reinstalling/repairing to see if you can get the button to appear, if nothing else works.

It’s definitely possible this is a OSM glitch though, there have been a few Win7 specific problems with Open-Shell.

**Comment by CTVCAM8** [comment]
Works ok on Win7 Ultimate 32 bit 1920x1080 with Classic Shell 4.3.1

You might be missing the extra settings to use your own start button image.
See picture.

Also if button size is 1 or a very high number, 
it may disappear or default to an internal start button.  

![start button settings](https://user-images.githubusercontent.com/44127216/101220932-780cb080-363b-11eb-819d-a57b36d1a875.png)

**Comment by MacCraker** [comment]
The only included button (besides the one included in windows) that works is the classic button, and button size is set to 0. The start button .png works on my windows 10 machine perfectly fine, and perfectly fine on my previous installation of windows 7.
