### ISSUE TITLE
Whenever I pin a folder to Quick Access it is removed next time I restart

### ISSUE THREAD

**Issue by Dave-Rado** [Open-Shell/Open-Shell-Menu#560]
I installed Open Shell under Windows 10 a few months ago and in File Explorer it  says I have Classic Explorer 4.4.142 (although I installed Open Shell, not Classic Shell).

Whenever I pin a folder to Quick Access it is removed from there the next time I restart my computer. Any ideas on how to trouble-shoot this?

Dave

**Comment by ge0rdi** [comment]
> File Explorer it says I have Classic Explorer 4.4.142

Where do you see the information?

> Any ideas on how to trouble-shoot this?

First of all, try to uninstall `Open-Shell` (or `Classic-Shell`) completely. And check if the issue is still present.
Then install latest `Open-Shell` and check again.
