### ISSUE TITLE
Corrupted large icons while using my custom skin

### ISSUE THREAD

**Issue by amymor** [Open-Shell/Open-Shell-Menu#561]
Hello
I created a skin which right pane and left pane have different icons size. I mean the left pane use small size while right pane use large. But i stuck on classic shell 4.3.0 because all newer version dont show large icons. The only soulotion i found is opening settings>Skin then uncheck and check "Small icons". That means every time open-shell opened or explorer restarted i must do that. Can you fix this in the next update?
Sry for my bad eng
TY

my skin:
https://we.tl/t-iprnjoOvBC

**Screenshots**
4.3.0(good):
https://imgur.com/d2QyLoi
newer version:
https://imgur.com/TmRG3fC

**Version:**
 - [Open-Shell=all version] [Classic-Shell=newer than 4.3.0]
 - OS: [ Windows 10 1909 and 20H2]

**Comment by bonzibudd** [comment]
Yep, this does seem to be an issue, I’ve experienced this myself. I don’t know if this was ever “officially” supported, but it’s definitely useful to have different main2 size. Some configurations with icon sizes still work, but others never seem to be usable. Hopefully this is fixable, it’s one of the only real bugs with skinning that I can think of.

**Comment by CTVCAM8** [comment]
This is the only info I can find on Classic Shell 4.3.0 release:

● New internal skin settings, Main_icon_size and Main2_icon_size. You can set them to "none", "small" and "large" independently to get different sized icons in left and right column of a 2-column menu

**Comment by bonzibudd** [comment]
While digging through source code, I found some references to these settings:
![image](https://user-images.githubusercontent.com/61938331/101975298-6a41c700-3c09-11eb-8fd7-ef4bb15f5474.png)

It's in `SkinManager.cpp` for reference. Maybe a developer could find where the process is going wrong, if it's that simple.

@CTVCAM8 looks like this section is where main2 icons for Win7 style are defined as well. That could be interesting to play around with.

**Comment by bonzibudd** [comment]
I wonder if there is any way to access the CSM 4.3.0 source code to see if a change was made?

**Comment by CTVCAM8** [comment]
Maybe. 
It's a long shot. 
I would ask @coddec (@thx_4_the_hard_wk on Classic Shell), 
if he could log on to the Classic Shell forum and send a request to Ivo asking for that specific 4.3.0 code.
I see very rarely Ivo will check the forum and respond. Guess it all depends if his email notification is turned on?

**Comment by CTVCAM8** [comment]
I'm sure a coder would be able to figure it out without the old 4.3.0 code.

Something to look for is does it have every possible combination of the old 

"Main_large_icons=0" or "Main_large_icons=1" or "undefined" along with the new

"Main_icon_size", "Main2_icon_size" with  "none", "small" and "large".


Classic 2 column skin with CS 4.3.1 on Windows 7

1st col size-2nd col size

none - none = works
small- none = works
large- none = works

none- small = Now not working at all
none- large = Now not working at all
 
small- small = works 
large- large = works 

small- large = not working after Classic Shell restarted
large- small = not working after Classic Shell restarted

Here is a picture where it will sometimes display one or more proper sized icons at the top of column after restart, 
and the rest below them will show the default white icon same size.

![Partial proper icons show](https://user-images.githubusercontent.com/44127216/104660933-62e46200-567c-11eb-9fe8-86fc521af063.png)


So does that mean we are looking in the wrong place?
It's as though for the small-large and large-small combos, the start menu gets cut off from displaying the rest of the icons.
It ran out of time? 

I also tried combinations of Pre-cash icons and Delay loading of icons options. No difference.

**Comment by bonzibudd** [comment]
That is a very good idea. Maybe having multiple icon sizes in the main section requires more time/another requirement to display properly, which may have not been acknowledged in 4.3.1 and later. I'll have to think if there may be another logical problem, maybe with something that was listed in the 4.3.1 changelog. I don't know of anything right now.

**Comment by amymor** [comment]
Open shell 4.4.169 the problem still remains. devs! pls fix it.
thanks

**Comment by toiletflusher** [comment]
Is this bug fixed?

**Comment by amymor** [comment]
> Is this bug fixed?

Not as far as I know, I installed OpenShell 4.4.170 yesterday and found it still not fixed. I gonna use the taskbar toolbar instead. But for explorer I still can't find any Windows thing that does like the classic bar. Maybe a custom button in the Command bar or maybe Navigation pain :)

**Comment by blackcrack** [comment]
we (The OpenShell Communiy like you) need programmers for it, 
Peoples who want programmed at OpenShell...
also the compatibility to Win11 and later versions must be fixed..

best

**Comment by Ibuprophen** [comment]
Closed this as completed (and commit pushed that referenced this issue) in https://github.com/Open-Shell/Open-Shell-Menu/pull/1088. 

~Ibuprophen

**Comment by blackcrack** [comment]
slurrppgghhh !
