### ISSUE TITLE
StartMenu repeated sorting

### ISSUE THREAD

**Issue by GH-User-X** [Open-Shell/Open-Shell-Menu#563]
**Describe the bug**
OpenShell alphabetizes some of the files, then goes to 'A', alphabetizes more files, and repeats. In essence, I have several alphabetized lists in one long list, instead of one long alphabetized list.

**To Reproduce**
1. Go to Start Menu
2. Click on All Programs
3. Scroll down to The first Z

**Expected behavior**
All items should be sorted alphabetically in one list.

**Screenshots**
![Screenshot - 12_8_2020 , 12_46_48 PM_ver001](https://user-images.githubusercontent.com/20276263/101542048-16a85280-3957-11eb-8c71-92adc2543dd9.png)

**Version:**
 - Open-Shell: 4.4.143
 - OS: Windows 10 Pro 20H2

**Additional context**
What I see when I use OpenShell, is that the apps/folders are in alphabetical order for several items, but then the order somehow starts back at "A". I would like it, if, like the regular Start Menu, they are alphabetized into one long list, instead of several short ones,. I find myself using the Windows version more than I'd like, to find programs faster and easier.

**Comment by ge0rdi** [comment]
You can right click on some item in menu and select `Auto Arrange`.
This will enable automatic arrangement so that your items will be always sorted.

**Comment by bonzibudd** [comment]
I agree with @ge0rdi. The only other cause I could think of is that the ProgramData and AppData folders are not being sorted together, but I highly doubt that. It might be good to update to the latest build as well, just for consistency.

**Comment by Darthagnon** [comment]
I'd noticed this weird behaviour, too. I thought maybe it was something to do with UWP/Metro vs Win32 programs. 

Is the solution "right-click and enable autosort"? Or will this become a default setting in future releases?
