### ISSUE TITLE
Opt-in mode for new users

### ISSUE THREAD

**Issue by theultramage** [Open-Shell/Open-Shell-Menu#565]
By default, Open Shell loads for all users and displays its settings UI on first use, allowing a tech-savvy user to opt out and deactivate it for their account. I would like to change this behavior to opt-in, that is, Open Shell would only start loading for that account if they manually launched Open Shell Menu Settings from the start menu (and perhaps toggled that one settings checkbox).

**Comment by hatalmasalma** [comment]
I think that an option in the installer would be ideal.

But if this won't be implemented, then in my opinion the opt-out should remain.

**Comment by theultramage** [comment]
It seems there already was a way to do this, via the bundled PolicyDefinitions.zip Group Policy files.
Specifically, "Start automatically for this user" can be set to 2 (Unlocked) and the default can be set to disabled.
The relevant registry is in HKLM\Software\Policies\OpenShell\StartMenu AutoStart_State=2 AutoStart=0
