### ISSUE TITLE
"Use categories view for control panel" setting has no effect

### ISSUE THREAD

**Issue by ezxpro** [Open-Shell/Open-Shell-Menu#568]
**Describe the bug**
Control panel only works as a list, regardless of the configuration mentioned in the title being enabled or not

**To Reproduce**
1. Just try and access the control panel when (using the Windows 7 like skin at least), it will be shown as a list in a sub-context menu and I can't change that behaviour, nor can I double click the Control Panel and be taken to the full version of it

**Expected behavior**
I wanted to:
1. Have a clickable entry in the start menu that takes me to the Category view of the Control Panel, Windows 7's menu would
2. Get rid of that list-like control panel in start shell

**Screenshots**
![image](https://user-images.githubusercontent.com/15344931/102012111-3fe62b80-3d27-11eb-8bc8-a133216d21cd.png)
This is what I want to get rid of /\
![image](https://user-images.githubusercontent.com/15344931/102012142-62784480-3d27-11eb-82e0-df2135b7ba8b.png)
/\ As can be seen, the "Open" (Abrir) option is greyed out, so there's literally no way I can open the control panel from the start menu, unless I search for it

**Version:**
 - Open-Shell: v 4.4.160
 - OS: Windows 10 2004 x64

**Additional context**
----

**Comment by bonzibudd** [comment]
Navigate to the "Customize Start Menu" tab in Open-Shell settings. Change the Control Panel item from "Display as a menu" to "Display as a link." 

If that doesn't work, you need to reset the Start Menu layout or the defaults for that item specifically. The "Categories" option only changes the Control Panel layout once the program has already been opened.
