### ISSUE TITLE
Default icon sizes don't scale beyond 150%

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#576]
**Describe the bug**
Open-Shell menu doesn't increase the default size for the "Small" and "Large" icons when the system DPI is set beyond 144. This can make the menu become very small when used in 200-250% scaling scenarios. The user can override this if needed, but it shouldn't be necessary just for the icon size to be correct.

**To Reproduce**
1. Set system/override DPI to a high number, ex. 240
2. Sign out/restart OSM
3. View incorrectly sized icons in menu

**Expected behavior**
Icons should scale up to a higher range to accommodate for higher DPI displays. If it is not possible to scale the icons indefinitely, then the cutoff should be around 240DPI.

**Screenshots**
Expected:
![Expected](https://user-images.githubusercontent.com/61938331/102435956-87014480-3fe5-11eb-892f-3a9665664868.png)
Actual:
![Actual result](https://user-images.githubusercontent.com/61938331/102436138-e95a4500-3fe5-11eb-9719-fa66dab9e179.png)

**Version:**
 - Open-Shell: 4.4.162
 - OS: Windows v2009

**Additional context**
This should work the same for both small and large icons. Now that we have 1440p/4K screens crammed into laptops (and higher resolutions in general), this icon size cutoff becomes apparent.

**Comment by bonzibudd** [comment]
Addressed in #711.

**Comment by ge0rdi** [comment]
> Addressed in #711.

Btw if there is issue associated with give PR, you can add line like this to commit message (at the end):
`Fixes #576`

And Github will automatically close referred issue when such PR is merged.

**Comment by bonzibudd** [comment]
Yeah, I will try to remember that next time. I forgot I made this when I did the commit.
