### ISSUE TITLE
Classic Shell Start Menu not Working

### ISSUE THREAD

**Issue by CH1CK3NT3ND135** [Open-Shell/Open-Shell-Menu#580]
So about an hour ago I was searching up "how to make windows 10 feel more like windows 7" and one of the guides told me to create a shortcut with the classic personalization window. When I opened it, I proceeded to click the "synchronized theme" which changed my desktop background. I then clicked the default windows theme which resetted my dark mode and the start menu. I had the Windows 7 start menu designated in Classic Shell and it worked with no problems whatsoever but it seems that whatever I clicked in the personalization window removed my ability to edit the start menu, which was one of the main reasons I installed Classic Shell in the first place. I don't know how to fix this and I need help, please and thank you. I have the latest Windows 10 version.

**Comment by bonzibudd** [comment]
Is the Open-Shell menu actually appearing, or is it using the Windows menu?

Are you able to access the Open-Shell menu settings window? (Right-click Start button, click "Settings").
