### ISSUE TITLE
Uninstaller?

### ISSUE THREAD

**Issue by Clyde-Beep** [Open-Shell/Open-Shell-Menu#584]
I want uninstall Open-Shell and I have no idea how to do it-

**Comment by bonzibudd** [comment]
Just go to Control panel -> Programs and Features and uninstall from there. 

Alternatively you can just run the installer again with the "Remove" option.

**Comment by XenHat** [comment]
For future questions like this, please make use of the new Discussions feature. https://github.com/Open-Shell/Open-Shell-Menu/discussions
