### ISSUE TITLE
during initial startup, Open-Shell grabs focus away from other activity

### ISSUE THREAD

**Issue by rsutton43** [Open-Shell/Open-Shell-Menu#590]
Whenever the system reboots (for whatever reason), the Open-Shell program is late starting.  As a result, I often find myself typing into a cmd prompt or searching in a search box and find that the cursor is no longer entering my keystrokes because Open-Shell has initialized and has take focus away from current app.

It's easy to reproduce:
1. reboot system
2. as soon as you are logged in, move cursor to left side of screen
3. with in 20-30 secs cursor will jump to center of screen. (thereby disrupting any keyboard action you have started)

Expected behavior:
Open-Shell would not take focus away from current operation.

**Comment by bonzibudd** [comment]
I believe I can partially reproduce this, but regardless of if Open-Shell is installed or not. I have not experienced the cursor behavior though.

**Comment by rsutton43** [comment]
The way I decided that Open-Shell was the cause was to uninstall Open-Shell and go thru the reboot process.  I placed the cursor to the left and waited. Nothing happened to the cursor.

I re-installed Open-Shell, rebooted, and placed the cursor to the left. After 10-15 sec, cursor jumps to middle of screen.

Sorry I didn't make this clear.  By the way, I am using Windows 20H2 build 19042.685 on an Asus laptop intel core i7-4700HQ w/ 16GB ram.

**Comment by ge0rdi** [comment]
Does `Open-Shell` _work_ during those 10-15 sec after reboot?
Try to press Start button right after reboot to check it.

There is also autorun item `Open-Shell Start Menu` in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` key.
This one is supposed to start `Open-Shell` at startup if it is not running already (which should be rare situation).
It should basically just exit if `Open-Shell` is running already.

Maybe try to remove that startup item (make backup of the key beforehand).
To see if this will help with the focus issue.

**Comment by rsutton43** [comment]
Well, I'm embarrassed to say, that I cannot reproduce this on my other Windows machines (all running Windows 10 20H2 build 19042.685). I mostly use this Asus N550J laptop and I failed to test the other machines! Sorry to have wasted your time.  This problem is most probably NOT an open-shell issue: it must be an issue on the laptop.  I need to find what service is actually the culprit on THIS machine.  I'll post back when I find the actual culprit.

**Comment by ge0rdi** [comment]
Closing for now.
Feel free to reopen once you'll be able to reproduce it with `Open-Shell`.
