### ISSUE TITLE
"This PC" icon RMB -> "Properties" opens Metro Settings -> About, instead of old "System properties" window

### ISSUE THREAD

**Issue by WhiteChairFromIkea** [Open-Shell/Open-Shell-Menu#599]
**Description**
Previous (~year ago..?) open-shell versions opened windows "native" "System properties" window, instead of "metro about app" for RMB on "This PC" -> "Properties" sub menu. I think it was a right choice.

Could you implement a way to choose which version of window to open? :)

**To Reproduce**
1. Configure "Open-Shell Menu" 4.4.160 -> "Customize Start Menu" tab to show "This PC" as "Display as link"
![explorer_IcqMvXl1qo](https://user-images.githubusercontent.com/46539653/103744737-f081db00-5006-11eb-8123-fcd0e0c40929.png)
2. Open "Start" menu, right mouse click on "This PC" -> "Properties"
![KL5lfaC0BI](https://user-images.githubusercontent.com/46539653/103744841-2030e300-5007-11eb-9325-87d93459c2dc.png)
3.  "Metro" / "modern" "About" window will be opened instead of good old "System Properties" window.
![ApplicationFrameHost_t8RJyd1Jsg](https://user-images.githubusercontent.com/46539653/103745043-769e2180-5007-11eb-9b02-b0e2e9e3dab2.png)

**Expected behavior**
I was expecting for this to be opened (as was before upgrade to v 4.4.160):
![SystemPropertiesAdvanced_rl30YvewPF](https://user-images.githubusercontent.com/46539653/103745105-92a1c300-5007-11eb-8026-471cd201f48b.png)

**Version:**
 - Open-Shell: [e.g. 4.4.160]
 - OS: [e.g. Windows 10 20H2 / 19042.685]

**Comment by ge0rdi** [comment]
I believe `Open-Shell` doesn't do anything special here.

`This PC` is standard shell item.
Recent Win10 versions simply started to launch modern About dialog instead of the old one.

**Comment by WhiteChairFromIkea** [comment]
I also would think so, but no windows update kicked in yesterday, only updated open-shell to latest version.. :(
On the other hand, I am not sure when I used "System Properties" before, it looks like latest windows update happened on 2020-11-11, and I am pretty sure changed "Environment variables" (via "System Properties" window) during this time (I change environment variables often to swith between different toolchains)..

**Comment by ge0rdi** [comment]
I think it was changed in Win10 20H2.

You can easily check that this is `Open-Shell` independent by simply right clicking on `This PC` in explorer and selecting `Properties`.
It will show modern about dialog no matter if `Open-Shell` is installed or not.

**Comment by WhiteChairFromIkea** [comment]
Jep, you are right, properties on "This PC" in explorer opens "modern" about thingy. Thank you, and sorry for disturbance :)
