### ISSUE TITLE
Classic Shell on Fosshub

### ISSUE THREAD

**Issue by blackcrack** [Open-Shell/Open-Shell-Menu#604]
**Describe the bug**
https://www.fosshub.com/Classic-Shell.html

**To Reproduce**
1. Go to https://www.fosshub.com/Classic-Shell.html
2. Look on https://www.fosshub.com/Classic-Shell.html
3. no successor announced

**Expected behavior**
A clear and concise description of the Successor.

**Screenshots**
see webpage.

**Additional context**
Add any other context on Fosshub don't know about the more new Version with the successor  .

**Comment by 43v6c3463** [comment]
Open-Shell is developed by entirely different people who don't have access to the Classic Shell fosshub page. You should contact them instead.

**Comment by CTVCAM8** [comment]
I don't see what the issue is?

FossHub, Mediafire, Source Forge are on the Classic Shell downloads page:

http://classicshell.net/downloads/

**Comment by blackcrack** [comment]
but there is no hint to our Open Shell Successor Page, 
the peoples think still if they have no news, the Classic shell is no further developed 
and if there no hint to the more new version and a successor 
do they easy not know.. so it's a must setting up Info's for send the peoples 
to Open Shell for have a possibility to follow ..
best :)

**Comment by CTVCAM8** [comment]
Guess that's up to Ivo if he wants to put more links to Open-Shell on the download page. 

As you should still have the power to log in, you could ask Ivo or Gaurav if an Open-Shell link could be more visible. 
If no reply, post a new topic in the "Classic Start Menu", "Bug Reports" and "Feature Requests" sections.
Use a standout title along with similar below words like: 
As Classic Shell is not being developed anymore, and you require bug fixes and new features, please visit these links:

https://github.com/Open-Shell/Open-Shell-Menu

https://gitter.im/Open-Shell

And give some simple instructions on how to use the areas on the Open-Shell pages,
(a lot of people will just get lost in it, download unusable files and give up). :)
You could put a couple of small screenshots with visual instructions as well.

**Comment by blackcrack** [comment]
hmm, have anyone a Fosshub account.. i've not .. like i have noticed .. and i dont see an "login" or something..
have anyone a clue.. or be i easy to old ? (no, i have not Farnsworth Glasses *g*)

**Comment by CTVCAM8** [comment]
Yes, that was a funny show. :)

You have 2 ways to solve your issue. 
Contact Fosshub directly or by logging on to the Classic Shell forum,
sending a personal message to Ivo, or posting on the forum to inform more people about Open-Shell 
(your old post on the forum is not that visible).
