### ISSUE TITLE
Windows XP and/or 9x style shutdown dialog? 

### ISSUE THREAD

**Issue by TorutheRedFox** [Open-Shell/Open-Shell-Menu#606]
A Windows XP style shutdown dialog would allow for customizability using button bitmaps and a background bitmap (with the option to add a regular button that inherits the standard button styling of the current theme, as a cancel button for example), while a 9x style dialog would be customizable by adding and positioning options in a regular Windows dialog

**Comment by bonzibudd** [comment]
Looks like you may have been in the right place at the right time. https://github.com/Open-Shell/Open-Shell-Menu/discussions/612#discussioncomment-285908
