### ISSUE TITLE
How to get rid of the Recent Items option above My Computer/This PC?

### ISSUE THREAD

**Issue by EsfanLock** [Open-Shell/Open-Shell-Menu#616]
<title>

Oh and how do I make the menu non-transparent?

**Comment by bonzibudd** [comment]
Click "Show all settings" in Open-Shell Menu settings. Then go over to "Customize Start Menu" and change the items from there.
 
If you want to disable transparency, go to the "Skin" tab and select "Opaque" or "Disable Glass Transparency." If that option doesn't exist in your skin, go to the "Menu Look" tab and scroll down to Glass opacity and change it from there.

You can use the "Discussions" page for any other questions.
