### ISSUE TITLE
[Classic Explorer] Option to disable it completely.

### ISSUE THREAD

**Issue by Galenmacil** [Open-Shell/Open-Shell-Menu#618]
I thought that removing all "toolbar buttons" from the Classic Explorer Settings would disable it but no. It still shows as a (very annoying and distracting) "Open-Shell" icon on the far right of the explorer window, just below the search input box.

So, for user like me who do not need it, could it be possible to add a simple "disable classic explorer" option somewhere.

Thanks.

Great utility by the way. On a new install of Windows 10 after fiddling with the registry and services the default start menu got disabled somehow... Open-Shell saved me from having to reinstall.

**Comment by bonzibudd** [comment]
You can run the installer again and uncheck Classic Explorer from there.

**Comment by Galenmacil** [comment]
Oh... Ok. Pretty simple. Thanks.
