### ISSUE TITLE
Start Button Image / Can't figure out how to make start menu transparent.

### ISSUE THREAD

**Issue by AlcoholicJohn** [Open-Shell/Open-Shell-Menu#619]
Hey all, I'm not sure where to post this. I'm just wondering if there was a way to change the behaviour of the start button image?
I'm using a custom image 900x900. Though I've made this smaller the behaviour remains the same.

When Start Button idle: Top third of image is shown.
Hover over button: Middle third of image is shown.
After click/in use: Bottom third of image is shown.

Now, I like this, it's kinda cool, however the most time spent regarding start menu is using it itself. 
So, when active, all I see is the bottom third of the image... Which is basically just nothing. 
Is there a way to change this? Maybe only two changes: idle and hover?
A cool idea would be have the two changes, top half on idle the bottom half on hover, then after click the image because the start menu background. That'd be great. But I know that's just wishful thinking. 

On a side note, I can't figure out how to make the start menu transparent even though my settings have 0% opacity.

Hope that all made sense.
Thanks in advance!

**Comment by bonzibudd** [comment]
For the start button image: Why not just make it 3x taller and have the image repeating? Also, the Start button tutorial outlines some things you can add to the image to specify how many states it has.


As for the start button, it's a limit of whatever skin you choose. If you want, I can make a transparent version, I just need to know what skin you are using.
