### ISSUE TITLE
Outdated description and tags

### ISSUE THREAD

**Issue by Hasnep** [Open-Shell/Open-Shell-Menu#62]
I've noticed the description and tags are out of date since the rebrand.

See here:
![image](https://user-images.githubusercontent.com/25184102/43821102-c4427e62-9b1a-11e8-857c-ef80b3c39eb0.png)

**Comment by ibuprophen1** [comment]
@Hasnep, what specifically is out of date? 

That area is only intended as a brief description. This way if someone performs a search, they will see this brief description to know whether or not this is the correct repository. 

The Readme.md is actually where the more extensive information is to look at.... 

Do you have any suggestions for the developers to consider that may, briefly, describe the development? 

They are always open to suggestions to help better improve the development. 


~Ibuprophen

**Comment by ge0rdi** [comment]
I've updated (simplified) the description.

Though I think tags/topics are ok. They are not related to project naming.
They are meant to make repository more discoverable by providing areas that given repo relates to.

@Hasnep Do you have concrete idea of what we could add to tags?

**Comment by Hasnep** [comment]
> they will see this brief description to know whether or not this is the correct repository.

That's why I thought it might be confusing if they saw an old name in the description.

> Do you have concrete idea of what we could add to tags?

Nope, I think they're fine as they are then.
