### ISSUE TITLE
OpenShell 4.4.162 Problem

### ISSUE THREAD

**Issue by MGBLN39** [Open-Shell/Open-Shell-Menu#621]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**
 - Open-Shell: [e.g. 4.4.131]
 - OS: [e.g. Windows 10 1903]

**Additional context**

Windows 10 Prof. 64-bit, Vers. 20H2  Build 19042.746 OpenShell Vers.4.4.162
My problem is difficult to describe, but I will try.
If I want to move a folder to a different position under “ALL PROGRAMS”, I do so with the left mouse button pressed. I move the folder to the desired position and then release the mouse button.
But it hasn't worked like that for some time.
Because while I move the folder over the other folders, they open one after the other. This creates a completely confusing situation so that it is impossible to see where I actually wanted to insert the folder.
I don't know how I can prevent all other folders that I touch with the folder to be moved from opening and presenting their contents.
I hope that I have expressed myself clearly

**Comment by bonzibudd** [comment]
I have the same issue. For some reason it isn't showing the white spacers correctly, and there is nowhere to move the items.

However, I tried this on a VM with the same version and it is working properly, so I have no idea if the new version caused this issue, I assume that it's completely unrelated. You could try reinstalling and see if that fixes it.

**Comment by MGBLN39** [comment]
I removed and reinstalled the program. It didn't fix the problem.
I think it's a bug. In the hope that the developers notice this and write an update.
It's a shame it started so nicely and now ends so badly.

**Comment by bonzibudd** [comment]
Interesting. I don't know if this could help or not, but try right-clicking an item in the Programs list and see if "Auto-Arrange" is on. That is the only option that I can think of that would change this behavior.
