### ISSUE TITLE
Program components not completely removed after uninstall.

### ISSUE THREAD

**Issue by PapaiJarda** [Open-Shell/Open-Shell-Menu#622]
I've uninstalled v4.4.160 and still have "Pin to Start menu (Open-Shell)" entry in Windows Explorer context menu.
I had no success trying to remove it using regedit and a third-party uninstaller, but instead I've found many registry keys and files related to Open-Shell components even after uninstalling it and rebooting the machine.

OS: Windows 10 Enterprise LTSC

**Comment by ragnarcb** [comment]
This program makes your shell and dlls and stuff a total mess. Really harmful. And no one helps with problems. Just do a system restore and never use this again. Go with StartIsBack++ and OldNewExplorer, safer way to achieve all the functionality.

**Comment by ge0rdi** [comment]
@PapaiJarda 
Haven't heard about such issue yet. The installation is done via standard MSI mechanism.

Can you try to install `Open-Shell` again and then uninstall it?
Eventually do reboot after install and also reboot after uninstall.

**Comment by AEAEAEAE4343** [comment]
@PapaiJarda 
The registry keys you see are most likely user data. These are just your Open-Shell settings, so that if you decide to reinstall you get your settings back.

**Comment by PapaiJarda** [comment]
> @PapaiJarda
> Can you try to install `Open-Shell` again and then uninstall it?
> Eventually do reboot after install and also reboot after uninstall.

Yes, I did it before but the context menu entry still exists in the system.

**Comment by PapaiJarda** [comment]
I've found this key on the system:
_**HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Folder\shellex\ContextMenuHandlers\StartMenuExt**_
And also this file:
_**C:\Windows\System32\StartMenuHelper64.dll**_

After deleting both by hand my system have no context menus entries related to Open-Shell-Menu and no traces from Open-Shell at all.
