### ISSUE TITLE
Sometimes when I click Open-Shell start menu and press "D" the computer shuts down.

### ISSUE THREAD

**Issue by ezxpro** [Open-Shell/Open-Shell-Menu#629]
**Describe the bug**
Sometimes, when I open open shell and press "D" the computer will immediately shutdown

**To Reproduce**
I found no reliable way to reproduce this.

What I know is that about a dozen times, I clicked the Open-Shell start menu and pressed "D" to search for "Defrag and Optimise Drives" and the computer immediately began the shutdown sequence.

At first I didn't realise what was going on and thought I might have done something else. But as I often open Windows' builting defrag tool that way, I verified that _often_, **when doing nothing else**, I clicked the start button, pressed "D" and the PC immediately starts to shut down.

This is the exception rather than the rule though, most of the times this doesn't happen. This also happened across 2 different Windows 10 installs, which makes me think that is indeed a bug in Start Shell rather than something else

**Expected behavior**
Clicking start shell and pressing "D" should simply search for apps and indexed items starting w. letter "D"

**Screenshots**

**Version:**
 - Open-Shell: v4.4.160
 - OS: On Windows 10  x64 1903 I experienced this issue maybe 2 or 3 times
 - Then  I **reinstalled** Windows, a Windows 10 2004 x64 MSDN ISO. There I experienced this about half a dozen times.
 - Then I *updated* to version 20H2 and experienced the issue only twice.
 

**Additional context**
The computer is new, all parts were bought brand new starting in Aug-2020, Thus I know of no defective parts in it, everything, including RAM and storage disks are ok. Every time this issue happened the PC had been on for some time, usually a few hours.

**Comment by bonzibudd** [comment]
Related to https://github.com/Open-Shell/Open-Shell-Menu/issues/447

**Comment by ge0rdi** [comment]
Search should be now properly focused when start menu is opened in [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build.

Additionally, it is now possible to configure accelerators to trigger only when Alt is pressed (`Require Alt key for accelerators` setting) or disable keyboard accelerators completely (`Enable accelerators` setting).

**Comment by ezxpro** [comment]
I just checked and this problem still exists as of yesterday's nightly release. 

As it stands right now, when I open the start menu and press certain keys (for instance, "D") it still triggers some action instead of typing. In other words, the search bar is not focused by default


Thankfully, I was able to deal with the problem by checking the `Require Alt key for accelerators` settings, which is enough of a workaround for me.

Thanks.

**Comment by ge0rdi** [comment]
> As it stands right now, when I open the start menu and press certain keys (for instance, "D") it still triggers some action instead of typing. In other words, the search bar is not focused by default

Check if you have `Selected by default` option enabled in `Search Box` settings.
That one should be enabled by default, except for `Classic style` menu.
