### ISSUE TITLE
Load config XML from commandline for unattended install.

### ISSUE THREAD

**Issue by mhgschmidt** [Open-Shell/Open-Shell-Menu#630]
I am installing all my windows boxes with an unattended setup.
It's frustrating that there is actually no way to load OpenShell's config from the commandline.

Expected behaviour:
StartMenu.exe /LOADCONFIG=myconfig.xml

Should load the config that was exported with GUI.

**Describe alternatives you've considered**
I've considered to manipulate the registry. But this is too complicated (many registry keys).

**Comment by ge0rdi** [comment]
`StartMenu.exe -xml <path-to-xml>` should work.
You may need to pass full path to XML eventually.

**Comment by mhgschmidt** [comment]
Hi ge0rdi,

That works:
"c:\Program Files\Open-Shell\StartMenu.exe" -xml c:\TEMP\OpenshellSettings.xml
many thanks.

I did not find it in the documentation.
Where is it documented ?

**Comment by ge0rdi** [comment]
I guess it is not documented anywhere.
I have ticket for that already - #438 - so I'll try to put it together sometimes.
