### ISSUE TITLE
Classic skin start menu identifying itself as "Windows Vista"

### ISSUE THREAD

**Issue by WindowsXP13** [Open-Shell/Open-Shell-Menu#638]
Before i uninstalled Open Shell because of this, the built in open shell classic skin menu identifies itself as "Windows Vista"
![wtf](https://user-images.githubusercontent.com/78677673/107190201-7d182280-6a25-11eb-9ae0-6fe6ac02dcd9.png)
The icons of computer were just changed, I am running Windows 10 Home, can you please fix this bug?

**Comment by bonzibudd** [comment]
You can customize the text using the "Menu caption" option. I don't know what would cause this, but Open-Shell seems to be defaulting to the oldest version. Maybe it was changed if you applied an XML file?
