### ISSUE TITLE
Unable to upgrade nor to install on Windows 10

### ISSUE THREAD

**Issue by papin1** [Open-Shell/Open-Shell-Menu#640]
I feel this issue is not easily reproductible.

The computer is an old Toshiba Satellite P200. I use this PC only for work and only because of a software that absolutely requires at least Windows 10.

OS: Windows 10 Home - version: 10.0.18363.1171
Open-Shell installed: 4.4.142 (installed when i installed Windows 10 last summer)
The upgrade is not working (known big bug).

Trying to install 4.4.152 or 4.4.160 fails because the program believes the OS is Windows XP-x64, which is, to say the least, rather strange.

Unfortunately, I cannot extract (with UniversalExtractor) the update.exe component from the installer.

One way to solve this issue would be to make the component  update.exe downloadable (and no check on minimum Windows version would be nice --- after all, if we are here it means we are responsible adults who can read requirements, otherwise we wouldn't bother to install Classic/Open Shell).

The reason why I want to upgrade is that launching python GUI scripts (python 3.8.6 x64) from the command line makes the taskbar sometimes go crazy (lot of flickering) and make explorer.exe (alongside with dwm.exe) almost hanging with high CPU usage (sometimes up to 90%). In those cases, I have to kill explorer.exe. So, I, in turn, believe a newer version would help get rid of these issues. A side effect (?) is that the python scripts are extremely slow to run. 

Strangely (again) these issues don't happen when launching the very same scripts from an IDE (python 2.7 x32).

Thank you for your help.

**Comment by NebelNidas** [comment]
Are you sure that you haven't accidentally enabled compatibility mode for the installer? That would be the only cause I can think of for the installer to detect your system as XP. Otherwise, that's weird, indeed...

**Comment by papin1** [comment]
1. Before posting, I already tried with compatibility mode enabled (7, 8), to no avail.
2. OpenShellSetup_4_4_163.exe yields same error.
3. Copied upgrade.exe from OpenShellSetup_4_4_163.7z to C:\Program...\upgrade.exe. Well, it gets better, in the sense that the program now says, although wrongly, "Your version of Open-Shell is up to date" (nightly build checked and unchecked). 

The last step above lead me to create a new OpenShell folder in C:\Program and manually copy each .exe and .dll to that folder, restart startmenu.exe, et voilà! running version 163.

One thing with the startMenu.xxx in the 7z file: I copied the first one of the 2 files, based on the size of startMenu.exe (the biggest). To me the choice wasn't clear but it worked so who cares.

Conclusion: The way to determine the Windows version is not reliable.
msinfo32 = 10.0.18363
python = 10.0.18362
OpenShell = Windows < 7

Thank you very much for providing the link to version 163. 
I guess this issue is closed (I mean you can close it yourself if you wish) although the problem will remain.

**Comment by papin1** [comment]
I forgot to tell that the flickering of the taskbar seems to have become a thing of the past.
