### ISSUE TITLE
Recently used apps list doesn't populate.

### ISSUE THREAD

**Issue by Galane** [Open-Shell/Open-Shell-Menu#645]
I use the Classic with two columns style on Windows 10 x64. Since the move from Classic Shell to Open Shell, the list of recently used apps on the left column of the menu has never filled up on computers that have been updated through the versions. Completely blank between Start Menu (Windows) at the top and Programs at the bottom.

I recently built an all new PC with a clean install of Windows 10 20H2 and started with the latest Open Shell 4.4.160. That list of apps works on it.

On my laptop, which started out on an older build of Windows 10 and Classic Shell, I just uninstalled an older version of Open Shell, rebooted, then installed Open Shell 4.4.160 then rebooted again.

I launched a bunch of programs and still nothing in the recently used list. How do I get that to work?

**Comment by NebelNidas** [comment]
See my answer here: https://github.com/Open-Shell/Open-Shell-Menu/issues/348#issuecomment-640114625
