### ISSUE TITLE
Pinned folders shouldn't shouldn't open with C:\Users\*\AppData\Roaming\OpenShell\Pinned\*

### ISSUE THREAD

**Issue by VarunAgw** [Open-Shell/Open-Shell-Menu#653]
When I double click on a pinned folder to open it, it opens with this path `C:\Users\VarunAgw\AppData\Roaming\OpenShell\Pinned\igfx_win10_100.9313`.

If the folder is in `D:\Software\igfx_win10_100.9313`, I would prefer that the original folder is opened instead rather than the symlink.

**Comment by bonzibudd** [comment]
Agreed, it's especially annoying when you need to navigate to paths above the original.
