### ISSUE TITLE
Resize Main Menu Buttons and User Photo

### ISSUE THREAD

**Issue by Tromick** [Open-Shell/Open-Shell-Menu#657]
Hello,

![image](https://user-images.githubusercontent.com/13919269/110545920-dbc4df00-813e-11eb-870e-694622240ccb.png)

I have some tweak problems... 

#1 I did all my favorite settings and using Windows Aero Skin and Windows 7 Style. But Main Menu Items are too close to each other. I mean the right list.  Documents, Downloads, Pictures etc. They should be little bit far away from each other. Is there way to make them far away from each other? If so, how can i do it? Where is the setting? 

#2 User Picture is too small. It should be bigger. Is there way to resize it also? 

Thank you! 😃

**Comment by bonzibudd** [comment]
You should use the [WIN7LIKE Combo RevE](http://www.classicshell.net/forum/viewtopic.php?t=5824) skin to accomplish what you are looking for.

**Comment by Tromick** [comment]
Thank you sir! Problem solved!!! ❤️
