### ISSUE TITLE
Classic Explorer problem  I can't Disable it fully 

### ISSUE THREAD

**Issue by MohaNNadO** [Open-Shell/Open-Shell-Menu#658]
THIS White line does not disable 
I tried to remove all options in Classic Explorer Settings but it does not disappear
I tried to uninstall but nothing happen 
I tried also to reinstall it and uncheck  Classic Explorer
nothing helps it 

![Screenshot_8](https://user-images.githubusercontent.com/67446855/110674521-a4a40b80-81da-11eb-9e92-7828f72f847d.png)

**Comment by Whoniverse** [comment]
https://github.com/Open-Shell/Open-Shell-Menu/issues/681#issuecomment-813086151
