### ISSUE TITLE
Does not recognize installed programs

### ISSUE THREAD

**Issue by Tringo61** [Open-Shell/Open-Shell-Menu#663]
Open Shell

CCleaner has somehow deleted all program folders from the start menu. The programs are still installed on the PC when I go into the folder and from Da Manuel the program does not work which work all !!!!!. The programs will stop "just not" in the Start menu does not appear on Windows own start menu.
Open Shell should best scan under C: / Program Folders and Programs (x86) all installed programs and display them in the program menu at Open Shell, that would be perfect.

Thank you for your nice efforts :-).

Best Regards

**Comment by bonzibudd** [comment]
It doesn't make sense for Open-Shell to look for programs in Program Files, as the binaries won't always provide all necessary information (program name, parameters, etc.) This would also cause unnecessary and repeated programs to appear. Open-Shell (like the Windows Start menu) gets search results from the Start menu folders and indexed files.
