### ISSUE TITLE
Where to go for latest stable build for end user

### ISSUE THREAD

**Issue by azhermit** [Open-Shell/Open-Shell-Menu#68]
I'm an end user - not a programmer - using "Classic Shell" which seems to work pretty well despite Windows Updates. Then I find out it's no longer being developed -- now picked up by all of you from the community. Kudos to you all! 
But for the layman who just wants the  updated product to use and refer to others it was not easy to follow the "paper trail" for development to find a link to what I'm surmising is the latest version of the now "Open Shell" application.
For those wanting to simply use Open Shell on their W10 machines is the latest nightly build @ 
https://github.com/Open-Shell/Open-Shell-Menu
the place to go and use the link that takes you to 
https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts
to find that latest build?
And is this link always stable? Or is there a repository for "latest stable build" that is more or less agreed upon?
Thanks much !!

**Comment by coddec** [comment]
AppVeyor produce nightly builds, it contains both latest fix and latest bugs if any.
Pre-release on Github is more like Beta.
Release on Github will be stable release.
@XenHat @ge0rdi  Correct if I'm wrong, thanks! :)

**Comment by ge0rdi** [comment]
As @coddec wrote, stable releases will be published on Github [releases](https://github.com/Open-Shell/Open-Shell-Menu/releases) page.

Nightly builds incorporate latest changes and are meant for advanced users that wan't to test those changes.

We don't have official release yet.

I guess we are still in rebranding/consolidating phase.
And there weren't done any substantial changes compared to official `ClassicShell`.
Well, except for a fix related to upcoming Win10 RS5.

So if you are not using Windows Insider builds and want 100% stability, just stick to official `ClassicShell` for now.

**Comment by azhermit** [comment]
Thanks much for the info. I assume when you've all agreed on a functionally needed, superior and stable version of Open Shell you might post a notice on the original Classic Shell site to announce the changeover in name and a link to the new site?
And... a GIANT thanks again to the community for taking up this project!!!  Windows 10 IS better than 8.1, (so is an abacus) and yeah, it does have a few nice features, but for those of us who want to get some work done and be actually able to find stuff and fix it W7 is still the champ of organization and logic to me. I'm always going over to one person's house or another to straighten out their W8.1 mess cause they can't find anything or fix it... - and I'm still running W7Pro on my business machines as long as possible. Just bought the W10 laptop for my wife as a tryout of W10 and that brought me to the discovery of Classic Shell. What a life saver to be able to continue production instead of another horrible learning curve.
I would have contributed as I do with shareware after a few weeks of use with about $25. I still will toward your efforts if you set up something or ship you a case of eye drops for the red-eye. :-)

**Comment by XenHat** [comment]
We posted on the forums (well coddec did because account creation is non functional), but soon after we ran into branding issues. Everything is still rough and we are still working on the public facing part of the project. We haven't done advertising because of said branding issues, we want to be fully ready this time instead of doing the same mistake twice.

Don't worry we have a plan.
