### ISSUE TITLE
Explorer caught in a loop of crashing and restarting

### ISSUE THREAD

**Issue by Lionmeow** [Open-Shell/Open-Shell-Menu#687]
**Describe the bug**
After installing, explorer gets stuck in a loop of crashing and then restarting, making the system impossible to use.

**To Reproduce**
I'm not sure how to reproduce it, as it started occurring right after install.

**Expected behavior**
The menu works and does not get stuck in a crash loop.

**Version:**
 - Open-Shell: 4.4.160
 - OS: Windows 10 Pro Insider Build 21354

**Additional context**
I doubt it's the issue with igfxCPL.cpl because such file does not exist on my system.
[Procdump.](https://www.dropbox.com/s/q38d3pi6ai04gos/explorer.exe_210413_093036.dmp?dl=0)

**Comment by ChuckBaggett** [comment]
I'm having a similar problem  after years of using open-shell with no trouble.
