### ISSUE TITLE
How do I increase size of font & icons in nested folders in start menu?

### ISSUE THREAD

**Issue by paulri** [Open-Shell/Open-Shell-Menu#688]
I just installed OS 4.4.160.  I have it almost like I want it, but one thing is that the nested folders inside the Programs menu are very small. I am just fine with the size of the text & icons that I see when I hit the Windows key (I am on Windows 10), but when I move my cursor to the Programs menu and see all those programs open up, those rows are too small--icons & text. Is there a way to increase the size? 

I have circled the area that I want to see with bigger text & icons in the screenshot.

![OpenShell](https://user-images.githubusercontent.com/4674109/114609002-28766b00-9c53-11eb-8587-2bb83ad4afa1.png)

**Comment by bonzibudd** [comment]
You may want to try changing the “Small icon size”; Search for it in Open-Shell menu settings and try something like 24, or 32 if you want it even larger.

**Comment by paulri** [comment]
Thanks. I changed it to 24 and then restarted, as advised. That did it.

**Comment by paulri** [comment]
I changed it to 20 and liked it even more. 

Thanks again.

**Comment by bonzibudd** [comment]
I think you meant to close it?

**Comment by paulri** [comment]
Yeah I did, then I logged back in, to let anyone else know that they could alter the number to others, instead of just 24 or 32.  Thanks for the reply. I tried the W10 start menu but it just got worse and worse for me, I never should have stopped using Classic/OpenShell.

**Comment by ICON-Games** [comment]
That just changes the icon size - not the text size. Is there any way to make the text bigger?
