### ISSUE TITLE
AVG flags generated .exe files as infected with Win32:MalOb-CA [Cryp]

### ISSUE THREAD

**Issue by sydbarrett74** [Open-Shell/Open-Shell-Menu#69]
I cloned the master branch in Visual Studio 2017 and attempted to build the project. AVG flagged the files listed below as infected with **Win32:MalOb-CA [Cryp]** and quarantined them. I sent feedback to AVG saying this is a false positive. I'm still filing a PR for the sake of due diligence.

ClassicExplorerSettings.exe
ClassicIE_32.exe
StartMenu.exe

Please advise.

**Comment by AveYo** [comment]
Best advice is to get rid of that pesky crapware, bloatware, spyware AV and get a competent solution from the likes of Avira, BitDefender, or even built-in Defender.

**Comment by ge0rdi** [comment]
@sydbarrett74 
This is false-positive detection of AVG. Files don't contain any threat.

You should report it to [AVG](https://www.avg.com/en-us/false-positive-file-form).
