### ISSUE TITLE
Bug: Moving file to a pinned folder disappears it

### ISSUE THREAD

**Issue by VarunAgw** [Open-Shell/Open-Shell-Menu#691]
This is another issue related to #653.

Open `C:\Users\VarunAgw\AppData\Roaming\OpenShell\Pinned\abc` by double-clicking on start menu.

Now paste a file in this folder. 

Expected: File to be pasted in abc folder and visible here.

Result: File is pasted in an inaccessible folder and can't seen anywhere.

**Comment by muhachris297** [comment]
fantastic... do you know when this is going to be released, officially? I see the program hasn't had an official release in over a year.
