### ISSUE TITLE
Open Shell causing Desktop to Go Black and Not Show Icons or Task Bar

### ISSUE THREAD

**Issue by larryw11720** [Open-Shell/Open-Shell-Menu#697]
I have been using Open-Shell / Classic-Shell for years with Windows 10. The Windows security Updates since 10/2020 have been causing issues with the most recent versions of Windows 10, from 1909 to 20H2. Until 20H2, I would remove the latest KB and the desktop would be restored. For the PC's that have been upgraded to 20H2, this has not worked. I have to completely remove Open Shell for the desktop to be restored. This happens on newly purchased  Dells as well as older PC's regardless of Motherboards or video cards. In most cases I'm using the latest version of Open-Shell, but it also happens with earlier versions. Open-Shell is very useful as I hate the Windows 10 Start menu. Has anyone else seen this issue?

**Comment by bonzibudd** [comment]
I haven't had issues personally, but I think others have had similar problems. You might be able to reach out to the maintainers for help with troubleshooting/diagnosis if you can easily reproduce the problem.

**Comment by bonzibudd** [comment]
Hey @larryw11720 

If you're still having this issue, it will help to create a crash dump for Explorer as explained here: [How to create a dump on Windows Explorer crash](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-create-dump-on-Windows-Explorer-crash).

Otherwise it might be best to close this in favor of other crash-related issues.

**Comment by larryw11720** [comment]
It is happening when any Windows Update occurs. In all cases uninstalling and reinstalling Open Shell fixes the issue. Normally when after an update occurs and you launch open shell it throws a dialog box that warns that Open shell needs to reconfigure for the new operating system. In all cases of the GUI going black after an update, open shell is not doing this.  I must wait for the next Windows update, then if I experience the issue , I will create a dump and reopen/ or send new( if you choose to close this).



Larry Walsh
MIS Director
Consumers Kitchens & Baths
Phone: 631-563-3200 ext. 1240
Fax: 631-567-1852
www.ConsumersKitchens.com<http://www.ConsumersKitchens.com>








________________________________
