### ISSUE TITLE
Unable to register Orginal Forums / Add Steps to _MakeFinal.bat

### ISSUE THREAD

**Issue by CaelThunderwing** [Open-Shell/Open-Shell-Menu#7]
(while the bit about being unable to register on the original forums is offtopic i hope there'll be a community forum or such to keep in contact about any development of this branch since the orginal dev has ceased work on ClassicShell itself, )

i would suggest either adding steps to the compiling .bat to check for HTML Help workshop & WiX in the PATH variable if missing Add OR update the BUILDME to tell the user to Check for this themselves and to add it if missing.  (i was failing to compile even after having everything installed to find out the installers for both didnt add to Path so while things *were* there it just couldn't be found. )

**Comment by coddec** [comment]
For forum:
As mentioned in https://github.com/passionate-coder/Classic-Start/pull/8
Thinking of using Gitter as replacement of forum, but need to confirm are there any limitation of no. of users in a public room.
Appreciated if anyone can help to confirm on that.

For MakeFinal.bat,
Errr...
No sure about that...

@ge0rdi

**Comment by coddec** [comment]
The new place for community to communicate is set now with Gitter.
https://gitter.im/passionate-coder
Seems they do not have limitation on no. of users in a public room, or way higher than the number of members exist on classic shell forum.
@CaelThunderwing
