### ISSUE TITLE
What is The Official Name

### ISSUE THREAD

**Issue by GTK66** [Open-Shell/Open-Shell-Menu#70]
You people have taken a great program and confused everyone that is trying to use it. What is The Latest Stable Name? Can CS 4.3.1 still be installed on Windows 10 build 1803. The update program does not work. and neither did saving everything to an XML file. I am so fed up with this that I may just go back and use the WINDOWS 10 Funkt GUI!

**Comment by Clintlgm** [comment]
Yes 4.3.1 still runs on 1803, its 1809 coming that will not work CS, this is why 4.4.109 was released for the people on preview releases would still be able to continue using CS now Open Shell While the team works on bringing CS up to date to run on the future version of Windows 10. Please remember these people are doing this on there own time for free. I personally am very happy that they are.

**Comment by XenHat** [comment]
Not everything always go as planned. We ran into a copyright issue with the first rename, and the new name wasn't well received.
News articles were too fast in announcing the changes so we had to rush even more. 

Please be patient, we are working on a smooth transition from Classic Shell.
