### ISSUE TITLE
“About this skin” links still point to www.classicshell.net

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#704]
The hyperlink text reads Open-Shell, but clicking the link leads to www.classicshell.net. I can try to fix this if needed.

**Comment by ge0rdi** [comment]
> I can try to fix this if needed.

Sure, go ahead. Any help is welcome. 👍

**Comment by bonzibudd** [comment]
Sounds good. I also have some other skin-related changes I am working on, so I may add those as well.

**Comment by ge0rdi** [comment]
Sure, feel free to submit them too.
Just keep in mind that individual (unrelated) changes should go to separate commits (there is no problem with having multiple commits in one PR).

**Comment by bonzibudd** [comment]
Addressed in #705.
