### ISSUE TITLE
Items in All Programs sorted into 2 sections

### ISSUE THREAD

**Issue by markschnegg** [Open-Shell/Open-Shell-Menu#707]
The programs in the All Programs are in two sections with both folders and programs. I cant seem to find a way to get them in the proper sorted order. I do have a lot of entries in the list

Is there a way to force a re-sort or is it a bug or am I missing something. There are no entries in the user specific start menu folder in the Roaming folder.

Thanks
Mark

OpenShell v4.4.160

**Comment by bonzibudd** [comment]
Try right-clicking an item and selecting "Auto Arrange." That should group everything together properly.
