### ISSUE TITLE
I need a version that doesn't customize the taskbar.

### ISSUE THREAD

**Issue by yakanika1116** [Open-Shell/Open-Shell-Menu#708]
The current openshell can customize the taskbar, but if I install other software that customizes the taskbar (such as WindowBlinds) at the same time, the taskbar display becomes strange.
Can you please release a version that does not allow customizing the taskbar?
I love openshell!
Thank you
(I'm not very good at English, sorry)

**Comment by ge0rdi** [comment]
Try latest [nightly build](https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts).
It should not interfere with other taskbar customization software when `Open-Shell` taskbar customization is disabled (default).

**Comment by yakanika1116** [comment]
It worked.
Thank you very much.

**Comment by ge0rdi** [comment]
You are welcome 👍
