### ISSUE TITLE
info: UAC being wonky when upgrading Classic Shell

### ISSUE THREAD

**Issue by Ryder17z** [Open-Shell/Open-Shell-Menu#709]
upgraded a system i haven't used in a long time from 16xx to 18xx to 20H2 (windows 10)

This greeted me afterwards: 
![image](https://user-images.githubusercontent.com/2000703/117569196-c92a4000-b0c4-11eb-898d-2c2e0fbb1920.png)

I retyped the upgrade command in cmd and it seems to work. 

This might affect Open-Shell as well.

**Comment by YamiYukiSenpai** [comment]
For me, it simply just asks to be "configured", which needs admin privilege to do.

It's a pain in the rear to see that, especially for my coworkers who prefer the classic style.

**Comment by YamiYukiSenpai** [comment]
Upgrade to Open Shell
Upgrading in-place works fine.  Did it for some of my coworkers.

**Comment by Ryder17z** [comment]
yeah. it was fine after installing openshell over it and rebooting
