### ISSUE TITLE
"Display as a menu" not working with folders

### ISSUE THREAD

**Issue by dt192** [Open-Shell/Open-Shell-Menu#713]
**Describe the bug**
'Display as a menu' not working with folders

**To Reproduce**
1. Settings > Customize start menu
2. Add a folder
3. Set item to 'Display as a menu'

**Expected behavior**
I expect it to show as a menu, the same as Control Panel does and the same as the folder does if you add it on the left side.

**Screenshots**
![h2EtqwbRyu](https://user-images.githubusercontent.com/2612048/117944147-d46bae80-b304-11eb-8e72-a06aa571f4f5.png)

**Version:**
 - 4.4.160
 - Win 10 Pro 20H2 19042.928

**Additional context**

**Comment by bonzibudd** [comment]
Is the problem just with the "Games" folder? Because the Windows built-in Games shell was removed from Windows 10, so it would make sense that it wouldn't show any items.

If it happens with all folders,  make sure the folders actually have items in them.

**Comment by dt192** [comment]
@bonzibudd Thanks for the response. No it was just a folder, I had already removed the original Games link.

I just realised what the issue was. I had put the path in the 'Command' box, instead of the 'Link' Box. It was working fine though other than the menu not showing, so didn't notice.

I'll close the issue.
