### ISSUE TITLE
Making the Start menu look like Windows 10

### ISSUE THREAD

**Issue by Ats456** [Open-Shell/Open-Shell-Menu#723]
I would like to have my Start Menu as it was before I downloaded this. so how do I make it back to normal?

**Comment by ge0rdi** [comment]
Uninstall `Open-Shell` ?

**Comment by Ats456** [comment]
Well I need the invisebel Tastbar

**Comment by ge0rdi** [comment]
You can select to open `Windows Start Menu` in `Basic settings`:

![image](https://user-images.githubusercontent.com/2453094/118443077-c1355600-b6eb-11eb-9d3a-92935653b371.png)

**Comment by Ats456** [comment]
Ah thank you that worked perfect!! and thank you for the fast respond

**Comment by ge0rdi** [comment]
You are welcome 👍
