### ISSUE TITLE
After the "new" Windows, can't use Open Shell

### ISSUE THREAD

**Issue by Moizevitch** [Open-Shell/Open-Shell-Menu#724]
Hello! 
Unfortunately I had to accept another Windows 10 update. 
It turns out that the Open Shell oscillates between on and off. 
Or active and deactivated, in short, the bar is constantly changing from transparent to normal (Windows just installed), and the screen is flashing, making it impossible to use the PC. 
What happens? 
How to solve this, please? 
Thanks.

**Version:**
 - Open-Shell: [4.4.160]
 - OS: [Windows 10 20H2]

**Comment by Moizevitch** [comment]
I've tried the instructions in this video and it gave the same problem.
I don't know if it helps, but it's more information.
(https://www.youtube.com/watch?v=QyQlFW1wx_o&ab_channel=vhanla)

**Comment by ge0rdi** [comment]
Try to reinstall `Open-Shell`.

**Comment by Moizevitch** [comment]
> Try to reinstall `Open-Shell`.

I did it, **ge0rdi**.

It's the same.

Thanks for the help.

**Comment by Kman780** [comment]
Hi there. I have this exact issue after (forced) Windows 10 update 20H2. I had Classic Shell 4.3.1 that ran perfectly until this Windows update then it began the same issues as Moizevitch described above. Tried uninstalling and reinstalling Classic Shell, didn't work, same issue. Installed latest version of Open Shell 4.4.160 and same issue. Please help!  Have been a Classic Shell user for 5+ years now and love it, need it.....   Hope you can find a fix for Open Shell and latest Windows 10 update 20H2.

**Comment by bonzibudd** [comment]
I haven't had this happen personally, but I could definitely see issues like this become more common as MS pushes out bigger updates.

It would be helpful to create a crash dump as explained [here](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-create-dump-on-Windows-Explorer-crash), as it sounds like Explorer is in a crash loop.

@Kman780 you can also follow these instructions if you are having similar symptoms.
