### ISSUE TITLE
OpenShell StartMenu does nothing when clicking on "reboot" machine

### ISSUE THREAD

**Issue by ghost** [Open-Shell/Open-Shell-Menu#726]
**Describe the bug**
I have VMWare and VirtualBox virtual machines and cannot reboot the machine using OpenShell. It works if I quit OpenShell and use Windows 10's default start menu to reboot the machine. Those machines were set-up for testing purposes, so no processes run on it when I attempt to reboot. I suspect something in OpenShell is wrong related to virtual machines.

**To Reproduce**
1. Go to 'Open Shell Start Menu'
2. Click on 'Right arrow' button at the reboot/shutdown/standby actions
3. Click on 'reboot'
4. Nothing happens

**Expected behavior**
- I expect the VM to reboot.

**Screenshots**
- Please see some seconds of video here.
- Link: https://youtu.be/dbDC9CaeNy4

**Version:**
 - Open-Shell: 4.4.160
 - OS: Windows 10 Pro 1903 x64

**Additional context**
- Open-Shell running in a VM
- Problem occurs on VirtualBox 6.1.16r140961 VM
- Problem occurs on VMWare ESXi 6.7u2 VM
- (other hypervisor software not tested, I expect the problem to occur there as well)

**Comment by ge0rdi** [comment]
Should be fixed in [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build.
