### ISSUE TITLE
Windows 10, version 21H1 compatibility with News and Interests widget turned off

### ISSUE THREAD

**Issue by aoleg** [Open-Shell/Open-Shell-Menu#727]
After updating to Windows 10 21H1 and installing the first Cumulative update, Windows starts displaying the News and Interests widget in the taskbar to the left of the system clock. I see no issues if this widget is left enabled. However, if I disable the widget (and Open Shell Menu is running), Windows corrupts tray icons.

**To Reproduce**
Update to Windows 10 21H1, install the first Cumulative update. Verify that the News and Interests widget has appeared in the taskbar.
Disable the widget by right-clicking on it and selecting News and interests - Turn off in the pop-up menu.
Observe behavior of the system tray icons. It may be different; I've seen them being messed up (screenshot attached) or disappearing completely.

**Workaround**
Option 1: Exiting Open Shell Menu fixes the icons.
Option 2: Re-enabling the News and interests widget also fixes the icons even if Open Shell Menu is running.

**Workaround that does not work**
Rebooting the computer and/or restarting explorer.exe from Task Manager only fixes the issue temporarily. After a few minutes, I witness the described behavior.

**Expected behavior**
Tray icons should continue to display normally when Open Shell Menu is running and News and interests widget turned off. 

**Screenshots**
<img width="226" alt="tray" src="https://user-images.githubusercontent.com/17113545/119963018-e8bbd680-bfa7-11eb-9394-b07952f76947.png">

**Version:**
 - Open-Shell: 4.4.160
 - OS: Windows 10 21H1, first Cumulative update installed

**Comment by ge0rdi** [comment]
Does work for me without any issue (running on 21H1 19043.1023).
I'm have "News and interests" disabled.

Could you have taskbar customizations enabled (`Customize taskbar` in `Open-Shell` settings)?
Maybe that's interfering somehow.

**Comment by Masfo** [comment]
Same happens to me. What I've seen it moves the ToolbarWindow32, "User Promoted Notification Area" coordinates to the side. I made a workaround hack script that restarts Open-Shell.

**Comment by aoleg** [comment]
> Could you have taskbar customizations enabled (`Customize taskbar` in `Open-Shell` settings)?
I have just verified that taskbar customizations are disabled in Open-Shell settings. Still having the issue.

**Comment by wdscxsj** [comment]
It's NOT Open-Shell's issue. Today's Windows patch fixes the "preview" blunder.

**Comment by aoleg** [comment]
> It's NOT Open-Shell's issue. Today's Windows patch fixes the "preview" blunder.

Installed the hotfix. Issue persists.

**Comment by wdscxsj** [comment]
> Installed the hotfix. Issue persists.

Yes, just a bit better than before on my machine. Likely related to [this issue](https://winaero.com/kb5003214-causes-taskbar-crashes-with-news-and-interests-enabled/).

**Comment by Masfo** [comment]
Latest Windows update 21H1 build 19043.1081 seems to fix this.

**Comment by wdscxsj** [comment]
Yes! The fix comes with KB5003690.
