### ISSUE TITLE
Add Open-Shell to Windows Package Manager (winget)

### ISSUE THREAD

**Issue by schui** [Open-Shell/Open-Shell-Menu#728]
**Is your feature request related to a problem? Please describe.**
Now that the Microsoft has released [Windows Package Manager 1.0 (winget)](https://devblogs.microsoft.com/commandline/windows-package-manager-1-0/), I expect that some people will move away from Chocolatey to winget, since winget will be installed by default.

**Describe the solution you'd like**
I thought it might be a good idea to add Open-Shell on the [Microsoft community repository](https://github.com/microsoft/winget-pkgs), similar to how Open-Shell is currently available on Chocolatey. 

Is this something you'll consider?

**Comment by KaranKad** [comment]
It's already there. [Open-Shell-Menu](https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/Open-Shell/Open-Shell-Menu)

**Comment by schui** [comment]
My bad. I was searching "openshell" and "open shell" and didn't think to search "open-shell".

**Comment by KaranKad** [comment]
I'll update the file a bit so when you type `winget install openshellmenu` it will immediately recognize it.

**Comment by schui** [comment]
Thanks!  I see that you added "openshellmenu" as a Moniker!
