### ISSUE TITLE
After the last Windows update, Spotify now ruins the Open Shell start menu

### ISSUE THREAD

**Issue by HansestHans** [Open-Shell/Open-Shell-Menu#738]
I have a BMP image replacing the Windows button, 918 pixels long. After the last Windows update, whenever I start Spotify, all icons and tasks move to the left and disappear under the BMP image. If I go to Open Shell settings and adjust the length to any other length or back to 918, everything works fine again, until I close and launch Spotify. Maximizing or minimizing Spotify doesn't reproduce the bug. No other program causes this, only Spotify.

**Comment by bonzibudd** [comment]
Can you post a screenshot? There are some bugs with the Windows taskbar after the latest update on Microsoft's end, so maybe this is related.

**Comment by HansestHans** [comment]
![1](https://user-images.githubusercontent.com/42211511/121758674-b1f6cc00-cb22-11eb-8e74-901cec5439e2.JPG)
![2](https://user-images.githubusercontent.com/42211511/121758675-b28f6280-cb22-11eb-8582-48c89b6ca529.JPG)

1.jpg: Taken before I launch Spotify, the 918px start menu button BMP is faded from black to grey, I use it as a spacer to push programs that are open further to the middle on my screen, it's a 49" ultrawide monitor. Also it's practical to have a huge start menu button, saves time when moving the mouse quickly. 
2. Taken after I launch Spotify, the 918px BMP is still there, but the task bar is unaware of it, the contents (except the task view button) is pushed to original sized start menu button, under the 918px BMP. As long as Spotify is open, this problem persists. When I close Spotify, it's back to normal and it's like screenshot #1. 

I don't know if this is related to this problem, though I doubt it, since this started happening after the last Windows update. 

https://community.spotify.com/t5/Desktop-Windows/Spotify-open-in-full-screen-cannot-access-taskbar-anymore/td-p/1044311/page/2
