### ISSUE TITLE
A larger "Folder Up" button

### ISSUE THREAD

**Issue by Yaron10** [Open-Shell/Open-Shell-Menu#743]
Hello,

I'm using `Open Shell` both on Windows 7 and Windows 10. Thank you for your great work. 👍 

On Windows 10, the "Classic Conflict" dialog is unavailable and I'm only using the "Classic Start" component.
I'm wondering if it's possible to force Windows to use a 32x32 "Folder Up" button (in File Explorer NavBar) *without the "Classic Explorer" component*.

I'd appreciate your reply.

**Comment by ge0rdi** [comment]
> I'm wondering if it's possible to force Windows to use a 32x32 "Folder Up" button (in File Explorer NavBar) without the "Classic Explorer" component.

I'd say that's not possible.
