### ISSUE TITLE
"Open-Shell Modern Settings" folder automatically shows in Explorer "Frequent" apps list

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#744]
**Describe the bug**
The Open-Shell Modern Settings folder for Windows Settings results automatically populates in the "Frequent" list in File Explorer, even without manually navigating to the shell folder.

**To Reproduce**
**Open jump list for File Explorer**

**Expected behavior**
The folder should not appear in the Frequent list.

**Screenshots**
![image](https://user-images.githubusercontent.com/61938331/121941712-9e638500-cd1d-11eb-913b-0b42199f97b6.png)
**Version:**
 - Open-Shell: 4.4.168
 - OS: Windows 10	21H1 build	19043.1055

**Comment by ge0rdi** [comment]
Here is how to replicate:

- Install `Open-Shell` on clean VM
- Search for some modern setting (e.g. `defender`)
- Click on found modern setting
- Right-click on `File Explorer` taskbar icon
- `Open-Shell Modern Settings` is shown in `Frequent` list

We should not include `CMIC_MASK_FLAG_LOG_USAGE` flag when invoking modern settings command.
