### ISSUE TITLE
Gen:Variant.Razy.327413

### ISSUE THREAD

**Issue by kkunderwood** [Open-Shell/Open-Shell-Menu#75]
IOBit ASC 11.1 is flagging ClassicIEDLL_32.dll as a threat in Open-Shell-Menu versions 130 and 131. Reinstalled version 129.

**Comment by kkunderwood** [comment]
AveYo: Just what is your problem? I am reporting a legitimate error! I have been using IOBit ASC for a long time and it has kept my several PCs safe from everything except trolls like you! Please crawl back under your rock!

**Comment by AveYo** [comment]
Who's trolling who? Take your "legitimate error!" and stick it up to IOBit's support arse because that's where it originates, instead of harassing incipient open-source projects that lack the funding for an annually digital certification as the only shield against crap "security" programs..

**Comment by ge0rdi** [comment]
@kkunderwood 
Please, report false-positive detection on [IObit forums](http://forums.iobit.com/forum/iobit-security-software/false-positive-reports-by-iobit-products).

**Comment by kkunderwood** [comment]
Thank you for your support. I am a retired software engineer with 50 years experience. As a courtesy we always went to the developer/maintainer first. Someone needs to start taking his/her medicine again!

From deep in the heart of Indian Territory...

Kenneth Underwood
________________________________
