### ISSUE TITLE
Support for Windows 11

### ISSUE THREAD

**Issue by niente0** [Open-Shell/Open-Shell-Menu#751]
Please add support for Windows 11! Thanks

**Comment by blackcrack** [comment]
https://github.com/Open-Shell/Open-Shell-Menu/discussions/745

**Comment by domjant** [comment]
Before close this 'issue' please make a statement on the Open-Shell webpage (https://open-shell.github.io/Open-Shell-Menu/) about what is expected regarding Windows 11 support. As well as where can track the current compatibility challenges.

**Comment by Kvarkas** [comment]
I am insider, technically 4.4.160 is working in windows 11, just use replace button option, see my last [comment ](https://github.com/Open-Shell/Open-Shell-Menu/issues/763)

**Comment by blackcrack** [comment]
> 
> 
> Before close this 'issue' please make a statement on the Open-Shell webpage (https://open-shell.github.io/Open-Shell-Menu/) about what is expected regarding Windows 11 support. As well as where can track the current compatibility challenges.

"Classic style Start Menu for Windows 7, 8, 8.1, 10  "

you Win11 addict \*bg* 

and by the way :  
https://github.com/Open-Shell/Open-Shell-Menu/issues/763

**Comment by anonimuos** [comment]
Use a square Start button to make the button work reliably such as the Windows 2000 logo Start button: http://www.classicshell.net/forum/viewtopic.php?f=18&t=4400

You can also instead do a tweak using Winaero Tweaker for those not comfy with Registry editing: https://winaero.com/winaero-tweaker-1-20-1-get-back-windows-10-start-menu-and-taskbar-in-windows-11/ or a Registry tweak to bring back old Taskbar for now.

**Comment by blackcrack** [comment]
The menu and the systrayicons be now removed, but the Systrayicons be in able to recover, 
but Startmenu and Searchbox is not funktional :\

@anonimous, did you test it already in 220000.65 ? I guess, the Tweak works also no more full..

**Comment by Aokromes** [comment]
duplicate https://github.com/Open-Shell/Open-Shell-Menu/issues/766 @coddec @ge0rdi

**Comment by ge0rdi** [comment]
Support for Windows 11 start button was added in [4.4.181](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.181).
