### ISSUE TITLE
Use Regular Windows 10 Start Menu

### ISSUE THREAD

**Issue by jcronic420** [Open-Shell/Open-Shell-Menu#758]
Is there a way to use regular Windows 10 start menu. I want to use other features/customizations but still use regular windows 10 start menu. Thanx

**Comment by TheMadHau5** [comment]
Shift+click the start button

**Comment by Kvarkas** [comment]
> Is there a way to use regular Windows 10 start menu. I want to use other features/customizations but still use regular windows 10 start menu. Thanx

If you look on the top its option to call "regular" windows tails menu
https://prnt.sc/1735c6n
