### ISSUE TITLE
Windows 11: Start Menu cannot be activated with new Start button

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#770]
**Describe the bug**
Microsoft has replaced the Start button on Windows 11, and it cannot currently be detected by Open-Shell.

In order to activate the Open-Shell menu, you must either use the Windows key or enable a custom Start button in Open-Shell, which creates a new button on the left side of the screen. Open-Shell should integrate with the new button to fix the behavior.

**To Reproduce**
**Click Start button on Windows 11**

**Expected behavior**
Open-Shell menu should open, not the Windows Start menu.

**Screenshots**
With Windows Start button:
![image](https://user-images.githubusercontent.com/61938331/123709120-7fdfac80-d83a-11eb-9928-54debadbe40c.png)

With Open-Shell custom button or WinKey:
![image](https://user-images.githubusercontent.com/61938331/123709300-d64ceb00-d83a-11eb-8b7c-55015d8a9d22.png)

**Version:**
 - Open-Shell: 4.4.168
 - OS: Windows 11 Official Insider Preview build 22000.51

**Additional context**
@ge0rdi I have sent you a trace.etl file that should help with troubleshooting. I can provide more assistance if needed.

**Comment by medievil1** [comment]
as is currently if you have the start button on the left like normal, the replacement icon sits over top of it, but slightly offset so you can technically click on both 
![image](https://user-images.githubusercontent.com/38597905/123733029-c51ad300-d868-11eb-87c8-c7e361dc05a3.png)

**Comment by blackcrack** [comment]
ehh:  
https://github.com/Open-Shell/Open-Shell-Menu/issues/763 
and 
https://github.com/Open-Shell/Open-Shell-Menu/issues/766#issuecomment-869142218

![Screen 00001](https://user-images.githubusercontent.com/7925717/123739842-9b34d100-d8a7-11eb-9ada-0017b5f1fe31.jpg)

**Comment by ge0rdi** [comment]
> @ge0rdi I have sent you a trace.etl file that should help with troubleshooting. I can provide more assistance if needed.

I'm not sure if ETL will help in this case anyhow.
This will require debugging and figuring out what's going on there.

For now I have no plans to deal with Win11 (maybe somehow later).
So hopefully someone else could have a look at this.

**Comment by Aokromes** [comment]
> as is currently if you have the start button on the left like normal, the replacement icon sits over top of it, but slightly offset so you can technically click on both
> ![image](https://user-images.githubusercontent.com/38597905/123733029-c51ad300-d868-11eb-87c8-c7e361dc05a3.png)
> 
> and it shows wrong version (should say Windows 11 pro)
> ![image](https://user-images.githubusercontent.com/38597905/123733191-0b703200-d869-11eb-9795-d6b7d096d773.png)

windows 10 thing is microsoft issue, if you open cmd you will see "windows 10" not "windows 11".

**Comment by Aokromes** [comment]
btw duplicate of https://github.com/Open-Shell/Open-Shell-Menu/issues/763

**Comment by Diwax** [comment]
Thank you so much

________________________________

**Comment by 0E800** [comment]
I was able to work around the issues regarding Start Menu icon and incorrect version.

![image](https://user-images.githubusercontent.com/6632069/124032238-2946af80-d9ad-11eb-8a3b-ec5aa707949b.png)

To remove the Windows 10 label goto Menu Settings and click on the Skin tab. Uncheck "Caption" 
![image](https://user-images.githubusercontent.com/6632069/124033272-9f97e180-d9ae-11eb-93d5-9f96fe8b15e4.png)


To fix the Menu icon issue. Goto https://png-pixel.com/ and generate a custom icon. It will vary depending on your screen resolution. You will have to play with the dimensions, as you can see from the samples below, they are not square but you can see in the screenshot that the Windows 11 Menu is completely covered, minus the few pixels on the top for me to still use the native menu.

Hope this helps.

Transparent 0 Opacity 77x180
![77x180-00000000](https://user-images.githubusercontent.com/6632069/124032855-ffda5380-d9ad-11eb-824a-824cd12a5bbc.png)

Transparent 0.1 Opacity 77x180
![77x180-aef3ff19](https://user-images.githubusercontent.com/6632069/124032877-049f0780-d9ae-11eb-9d31-baa1121a8144.png)

Transparent 0.2 Opacity 77x180
![77x177-aef3ff19](https://user-images.githubusercontent.com/6632069/124032883-09fc5200-d9ae-11eb-81ff-30c5ca5e32f9.png)

**Comment by medievil1** [comment]
> 
> 
> I was able to work around the issues regarding Start Menu icon and incorrect version.
> 
> ![image](https://user-images.githubusercontent.com/6632069/124032238-2946af80-d9ad-11eb-8a3b-ec5aa707949b.png)
> 
> To remove the Windows 10 label goto Menu Settings and click on the Skin tab. Uncheck "Caption"
> ![image](https://user-images.githubusercontent.com/6632069/124033272-9f97e180-d9ae-11eb-93d5-9f96fe8b15e4.png)
> 
> To fix the Menu icon issue. Goto https://png-pixel.com/ and generate a custom icon. It will vary depending on your screen resolution. You will have to play with the dimensions, as you can see from the samples below, they are not square but you can see in the screenshot that the Windows 11 Menu is completely covered, minus the few pixels on the top for me to still use the native menu.
> 
> Hope this helps.
> (Edit: I am unable to use a 100% transparent image, it will not overlay the native menu. Make sure to use 0.1 opacity.)
> 
> Transparent 0 Opacity 77x180 - DONT USE WONT WORK.
> ![77x180-00000000](https://user-images.githubusercontent.com/6632069/124032855-ffda5380-d9ad-11eb-824a-824cd12a5bbc.png)
> 
> Transparent 0.1 Opacity 77x180
> ![77x180-aef3ff19](https://user-images.githubusercontent.com/6632069/124032877-049f0780-d9ae-11eb-9d31-baa1121a8144.png)
> 
> Transparent 0.2 Opacity 77x180
> ![77x177-aef3ff19](https://user-images.githubusercontent.com/6632069/124032883-09fc5200-d9ae-11eb-81ff-30c5ca5e32f9.png)

I was able to do it by trimmiing a row of pixels off my icon png.. (shifting them on the canvas) and unselecting align to corner
![image](https://user-images.githubusercontent.com/38597905/124319928-f6392300-db48-11eb-98a2-b5f5aa8274e6.png)

**Comment by anonimuos** [comment]
For now if you replace the Start button and use a square button such as the Windows 2000 Logo Start button: http://www.classicshell.net/forum/viewtopic.php?f=18&t=4400 it works around the issue of transparent pixels in other circular Start buttons being ignored on Windows 11 to activate the Open Shell Start menu.

**Comment by anonimuos** [comment]
Also, you can just create a new user account after enabling the Classic Taskbar in HKLM. That enables the clock and most of the icons they broke/disabled in Windows 11 except for the Network icon.
![image](https://user-images.githubusercontent.com/46422834/125159167-65d78f80-e193-11eb-8def-f982e59a10cc.png)

**Comment by Aokromes** [comment]
@ge0rdi  duplicate of #763 :)

**Comment by bonzibudd** [comment]
@Aokromes in that case, I will close in favor of #763.
