### ISSUE TITLE
Issue with items in the start menu

### ISSUE THREAD

**Issue by SuperLumberjack** [Open-Shell/Open-Shell-Menu#778]
Hello,

**I have a big issue with Open-Shell (4.4.160) since I have changed the location of the "Documents" and "Pictures" folders of Windows 10 Pro.**

(It's a new PC that I mounted for my parents. So now I have lots of things to install.)

**In the menu I have now 2 icons with "_No Text_" written and in the settings I have same problems with the Documents and Pictures folders which are showing "_user_documents_" and "_user_pictures_"**

![Open-Shell issue 1](https://user-images.githubusercontent.com/82117649/124608909-6f00ed80-de6f-11eb-96bc-b720245cf628.png)

![Open-Shell issue 2](https://user-images.githubusercontent.com/82117649/124608518-16315500-de6f-11eb-8c8e-e902eb50d714.png)

I tried to uninstall Open-Shell several time with Revo Uninstaller Pro, but this problem is still here.

Thanks for your help !

(sorry for my bad English)

**Comment by SuperLumberjack** [comment]
It's strange, because I didn't find any trace of Open-Shell in the registry after I have uninstalled it...

The problem is maybe somewhere else.

**Comment by SuperLumberjack** [comment]
It's strange, because I didn't find any trace of Open-Shell in the registry after I have uninstalled it...

The problem is maybe somewhere else.

**Comment by blackcrack** [comment]
Hi @SuperLumberjack ,

install this 4.4.168 : https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts  

and give feedback.. and by the way, you could delete one of the doublepost's ;)

best

**Comment by SuperLumberjack** [comment]
Hello @blackcrack 

Thanks for your answer ! :-)

I just found the cause of the problem. It's a bit hard to explain, but when I clicked on "_Documents_" or "_Pictures_" (Images) in "_This PC_" (Ce PC), the paths were good, but when I clicked on "_Documents_" or "_Pictures_" in the _Libraries_ (Bibliothèques), I was redirected into a "_Documents_" folder in "_Documents_" or a "_Pictures_" folder in "_Pictures_".

In fact, I should have been redirected to the same folders in both cases.

I tried the default folders but the problem was the same.

![Windows 10 libraries](https://user-images.githubusercontent.com/82117649/124641156-aa5ee480-de8e-11eb-9357-32930966453e.png)

I had to play with the registry and the default path for these folders until it works.

Here are the paths of the registry if someone encounters the same problem one day :

_HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders_

_HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders_ 


Thanks for your help !
