### ISSUE TITLE
Periodic Release 4.4.169 > Smart Screen blocking install

### ISSUE THREAD

**Issue by RalfRoemling** [Open-Shell/Open-Shell-Menu#784]
Win10.21H1

When tryin' to install or to upload to virustotal.com Windows Smart Screen is popping up stoppin' the process.
![ScreenShot 552 ](https://user-images.githubusercontent.com/12496450/125590559-0577a2c4-977e-4bd3-af7d-5f083301b60c.jpg)

**Comment by bonzibudd** [comment]
You can avoid it with the "More info" button. This issue will resolve itself after enough people have downloaded and verified the program.

**Comment by RalfRoemling** [comment]
I see. How do i verify ?

**Comment by bonzibudd** [comment]
It will happen automatically after a few days, when more people have downloaded it.

**Comment by blackcrack** [comment]
@RalfRoemling 
Ralf, klick auf den Weitere Informationen, wie Bonzi sagte, dann klickst Du auf weiter, da Openshell keine MS App iss und alles was nicht MS ist, in naher Zukunft alles Blockieren wird, musst Du lernen Dich darüber hinweg setzen und einfach weiter machen
und dir selber ein bisschen vertrauen.. Microsoft spielt mittels Sicherheit mit der Anst der User, daß sie jaaaahh was falsch machen würden und scheiss vorsichtig sein sollen.. DAS ist aber 1. quatsch, zweitens ne ausgemachte sauerrei, weil sie damit die Leute immer mehr einschüchtern.. und den Usern Ihrer Software somit immer mehr und mehr einkreisen über lange sich hinweg..
Das ist sowas von mießer Masche, Sichere Deine Daten auf einer USB-Festplatte und Du kannst ein USB rein schieben und kannst wieder neu installieren und Du verlierst nichts... Du darfst hald nur nicht faul sein und deine Daten immer schön sichern und eben von USB dann eben alles öffnen und sichern, wie ein Baum.. dann findest Du auch wieder alles und deine C: kann abrauchen..

Dann lädst Du den Total Commander von Chrsitian runter, also von [https://www.ghisler.com/deutsch.htm](https://www.ghisler.com/deutsch.htm) runter und schaust dir mal deine Daten an und wie alles so angeordnet iss..

dann lädst Du das hier runter :  
[https://winaero.com/winaero-tweaker/](https://winaero.com/winaero-tweaker/)
von da [https://winaero.com/download-winaero-tweaker/](https://winaero.com/download-winaero-tweaker/)  und schausst dir mal die Möglichkeiten an.. ich hoff Du kannst ein bisschen english :D 
Da gibts auch ne option, wo man diesen Smartscreen ausschalten kann.
  
und wenn alles geklappt hat, diese Issue auch.. weil sonnst hängen bei Issues viele posts rum, die zwar resolved sind, aber nicht geschlossen ..  
Also viel Spaß beim Lernen..  
  
and by the way, Over google can you read such issues about "Windows 10 Smartscreen verify and disabling" , denn sowas kann man über regkeys und anderen Möglichkeiten ausschalten.. ;) Denn wir hier sind alle unbezahlt und und das Thema hier ist Open Shell, kleiner Tip, lad dir mal Quiterss als portable runter, und adde [Deskmodder.de](http://www.deskmodder.de) und solche seiten, kommt nem menge info rüber, viele Seiten unterstützen rss und iss ne prima morgenzeitung..
 
liebe Grüße  
Best regards   

Blacky

**Comment by RalfRoemling** [comment]
@blackcrack 
Hi Blacky, 
Danke für die Tips, aber ich glaub' das geht am Thema vorbei. Ich kenn sogar [Litestep](https://de.wikipedia.org/wiki/LiteStep) noch aus einer der ersten Versionen, da war Deskmodder noch nicht mal angedacht... Ja, so alt bin ich :-)

Mir selbst sind die grundsätzlichen Zusammenhänge klar, aber es gab bis dato noch nie eine SmartScreenmeldung bei den Installern. Von daher finde ich das Ticket insbesondere für Noobs relevant, die sich dasselbe fragen.

Und Christians TC is' hab' ich vor 20 Jahren gekooft :-)
Und mein Backup is' GFS über mehrere Medienarten :-)))

Liebe Grüße zurück,
Ralf

**Comment by blackcrack** [comment]
@RalfRoemling 
dann sind wir gemeinsam imho in div. BBS gewesen...
Ach ne ... vor 20 Jahren, dann haste mich ja auch schon ein zwei mal in Chris Forum mitbekommen ;) 
allerdings bin ich da unter Blacky drin mit so nem gehörnten Dingends drin.. :D 
Hab damals von Chris den WC um 25 Euro abgekauft, das war noch bei den CD Shareware Zeiten "Topware-CD"
da war er dann drauf und hab ihn dann damals, weil NC für Win31 und 311 unbrauchbar war und der damals schon umbenannte zu TC damals so wunderbar passte auch in den Boxen verteilt und danach dann bei Schadt bei jedem den Kunden drauf geknallt
im LK.GP als ich als Systemberater arbeitete ... \*kicher*  
und bei mir im Keller steht ne Fedorakiste mit selfhost.de Anbindung ;) nachdem ich vor ein, zwei Jahren vollens zu fedora von Mandriva gewechselt war.. ich war sogar der jenige, der damals Gael die Idee von der rpmdrake Oberfläche erzählte, ohne dass die damals so hies.. er brachte die generelle Idee vom Configurationszentrum .. aber lange her.. ich hab über ftp und das Gefühl zwischen Fehlermeldungen, schlechten rpms und langsamen tot der neuen rpm's und das auseinander reisen der Mandrivacommunity alles mitbekommen und mir blutete das Herz.. die 8.0er war so geil mit dem 3er kde und dem Onlineinstaller und urpmi ... wenn ich heut wieder drann denk..
Als dann alles anfing intern und wobo sowie die ein zwei anderen.. bloß weil im Büro wegen den Spannungen jeder die klappe nicht aufbekamen.. ich sag dir, das mit der Deutschen Community war das schlimmste..  im Strahl.. echt im Riesenstral..
Gael war damals als er gekickt wurde, mehr als Enttäuscht, deshalb war vieles ihm auch egal weil er wusste wie und dass man gegen Ihn konsperierte.. und er nichts machen konnte und so weiter.. war ne besch. Zeit.. kommt grad alles wieder hoch.. hat mir einiges an schöne Linuxzeiten geraubt wo ich mich dann auch abwandte wieder zu Win.. heut seh ich das eher Linuxserver/winworkstation eben weil WinNT ne einheitliche scheiße iss und man sehr leicht mit portablen proggys umgehen kann und nich verschiedene Distros verschieden alte Libs haben.. wenn sie' sie überhaupt haben.. Deshalb schau ich auch daß ich immerwieder nen aufruf mach und bei mir überall ROS hochgehoben wird , daß man bei Reactos helfen soll, daß wir ein Freies WinNT haben und nicht abhängig sind von nem "Pizzahat" mit Anhängsel und Einrichtungen..

Na dann wer nicht backupt iss selber schuld.. ;) richtig.. 

Das mit der Smatscreenwarnung iss ein MS Dingens, sich haben Jetzt die ganzen Treiberfirmen unter sich, nun fangen Sie an mit Win10 und 11 die Ganzen programme in Ihren Store zu bekommen, weil sie mitbekommen haben, daß das mit dem Google-Store klappt und man sich die ganzen Kunden noch besser an sich binden kann, auch das mit dem Cloud Account, bei Win11 musste nur das Netzkabel rausziehen, dann passts plötzlich oder bei VBox die Netzverbindung kappen unten am Fenster über das icon, rechte Maustaste..  
So wie ich das mit bekomm seit Win7/10 rein nach Gefühl werden die immer penetranter .. Man sollte in div. verschiede Git's aufbauen und den Leuten in div. Unis ermöglichen frei an Reactos mit zu arbeiten um später alles auf einen schlag zusammen zu fügen, dann hat nicht nur Deutschland sondern die ganze Welt ein Freies WinNT, das eben nich gesteuert werden kann... und jede Sicherheitslüche innerhalb von Stunden dann gleich geschlossen werden kann.. Tut gut mal in deutsch infos zu tippern auf Github und zu wissen, daß man verstanden wird.. reallive und Computerlive kann man ohne bombardiert mit irgendeinem Scheiss zu werden nicht mehr zusammen zu legen.. von wegen SozialeMedien.. das mit Marc und den Aufbau von Gesichtsbuch.. da wusst ich schon daß nicht nur Junge Leute sich einloggen, sondern das kurz oder lang zu ne rießen sch.. wird.. und hab mich deshalb auch von dem ganzen sch. raus gehalten.. nach Gefühl her.. Forum, freier Chat und Mail.. das iss immer noch das Beste..

Von wegen Issues.. und Information... Welcher Noob checkt, daß hidden Texte/geschlossene Aufgaben noch zu finden/lesen sind wenn du das Thema schließt .. (Hand vor dem Gesicht nach obenfächer {augennachobendrück}\*blummm*) verlang von denen so was nicht, hat denen doch bis jetzt niemand was von gesacht'  wird im Datenjungle verschwinden und nie wieder auftauchen..
und auserdem wirds per robot.txt auch aus den Suchmaschinen gehalten, damit es die Suchmaschinen nicht überflutet..

Ich schau daß ich das Win so einfach als Ordering System halt , installier, alles soweit abschalt inklusive Telemetrie, was zwei regkeys in Win11 sind :  
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection]
"AllowTelemetry"=dword:00000000
"MaxTelemetryAllowed"=dword:00000000

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection\Users]

```

die stehen normalerweise auf 00000001 , dann sollte das ganze telemetriegedöns aus sein  
so einfach mal nebenher..  

jo.. uff.. hab seit ner langen zeit mal wieder alles schön rauslassen können...

liebe Grüße
Blacky

**Comment by RalfRoemling** [comment]
@blackcrack 
Krass, da mußt Du ja noch viiiel älter sein als ich :-) 
Und ja, BBS... das waren noch Zeiten...33,6, 56 und dann erst ISDN... das flog!

Unix/Linux hat mich nie so richtig gepackt. Ich fand's doof, das man so häufig auf Treiber und Funktionen warten bzw. manuell installieren mußte, die bei Windows meist out of the box liefen. reactos sagt mir momentan gar nix, muß ich mal recherchieren.

Und ja, der Store in Win10 geht strategisch definitiv in Richtung Plattformökonomie. Allerdings stellen die sich mit der Öffnung zu Linux und Android deutlich cleverer an, als Google und apple. Da wird ihnen eine Kartellbehörde schlecht'n Strick draus drehen können von wegen Monopolausnutzung und so. Wirklich clever...

Bei den noobs bin ich etwas optimistischer, aber da hast Du'n Punkt.

Und auch bei Win bin ich d'accord. Telemetrie is' off, Autoupdater von Programmen auch, und ab und an, schaue ich mal, mit Wireshark, wer evt. nach Hause telefoniert.

In diesem Sinne... hab'ne gute Zeit. Man liest sich :-)

**Comment by blackcrack** [comment]
@RalfRoemling 
oh ja, bis das erste ppoe kam..
mit den Flat's bei den Telleitungen, würds sich ja heut richtig rentieren, daß man ne BBS auf macht !
Hab in meiner Workstation in Win7 noch ne AVM pnp drin \*breitgrinz*

Reaction against MS Politique , Reactos.org, sag aber blooos ned, daß de mich kennst, weil sonst blockierst Du dir den weg..
weil EmuandCo und ein paar andere wollten mich unbedingt raus haben.. jetzt muss ich mal guggen, wie ich das mach...
EmuandCo, Daniel Raimer aus Munchen und ein paar andere.. ach musst Du selber raus bekommen was Sache iss.. und bekommst Du mit der zeit auch raus.. ich war auf jedenfall vor Raimer dabei.. der hat sich angepisst und hat uncorreckterweise mir div. sachen in die Schuhe gestekt und nen anderen mich rauswerden lassen.. Xpert.. und im ?Mastodon? dauernd gegen mich geschossen .. und so weiter.. eben alles drann gesetzt.. egal.. ich unterstützt Reactos trozdem.. ich beis mir jetzt noch in den ... daß ich den gesupportet hab.. Das mal zu reactos .. Halt dich bedeckt und reines codeschaufeln, jeh mehr du macht um so mehr ansehen bekommst du..  

5O und fang beim neuen Pro.di in Renningen zu lernen an, mal sehen obs funtzt und ich bis zum ende komm.. \*g*
iss ja nich mal die Hälfte von 130 ... hrhrhrhr ... nachher häng ich an ner Hardware und kann sagen, moooment Fachi, ich hab hier die Hardware unter *meine* Griffel :) Genau das was man eben früher bei "Schad Comuter" gemacht hat ;) Schrauben, schrauben, schrauben, schrauben... und abfall .. irgendwie entsorgen... \*kicher*
