### ISSUE TITLE
Sleep button puts computer in hibernation instead of sleep 

### ISSUE THREAD

**Issue by tallman69** [Open-Shell/Open-Shell-Menu#787]
I am running Windows 10 Home 21H1 on a new HP laptop.  My Open Shell version is 4.4.160.  When hibernation is enabled the sleep button on the Shut Down menu puts the computer into hibernation.  When hibernation is disabled the sleep button does nothing.  If I exit Open Shell and use the shut down menu in the Windows 10 Start Menu the sleep button works normally.  I uninstalled Open Shell and installed Start is Back and sleep functioned normally.  After reinstalling Open Shell the issue persists.  I do not have this problem on my two Windows 8.1 computers.

**Comment by anonimuos** [comment]
From admin cmd prompt, try this command:
powercfg /a

What does it say? If you have a system with Modern Standby (Standby with Network Connected/Disconnected) instead of S3, that may be the reason. Classic Shell was never updated for Modern Standby as at that time, those systems were quite rare. I agree with you, Open Shell can be updated for it, but the devs can only do it if there is a reliable way via an API to determine if Modern Standby is enabled on a system.

**Comment by tallman69** [comment]
Thanks for the reply.  My research has shown that my version of Windows 10 does indeed employ Modern Standby.  That also explains why I could not get the normal method of creating a sleep shortcut on my desktop to work properly either.

Could you pleas explain how to add the monitor_off custom command to the Open Shell menu.

**Comment by anonimuos** [comment]
Look in the Classic Shell forum: http://www.classicshell.net/forum/viewtopic.php?p=22427

**Comment by eladkarako** [comment]
I've reverted to S3 power saving from Modern standby, and was able to use the `C:\Windows\System32\shutdown.exe "/h"` for proper Hibernation and its other variations for sleep and such.  
It was done on 21H2 preview version which fixes a lot of 2004 issues. used info from:  
https://borncity.com/win/2020/11/26/windows-10-v2004-cant-deactivate-modern-standby/

**Comment by anonimuos** [comment]
Unfortunately that PlatformAOACOverride value is not a universal fix. It seems to work only on those computers which have ACPI S3 state implemented in the firmware. If the device manufacturer has chosen to not implement S3 at all and rely only on the craptastic Modern Standby, it doesn't work. Also, it doesn't work on AMD platforms.

**Comment by ge0rdi** [comment]
Should be fixed in [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build.
