### ISSUE TITLE
https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/4.4.169-beta won't execute on windows 10

### ISSUE THREAD

**Issue by eladkarako** [Open-Shell/Open-Shell-Menu#789]
but exe from https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.160 does.

**Comment by epman100** [comment]
what Windows 10 version are you using?

v4.4.169 seems to run fine when running at least Win10 v1809, though I'm actually using it on LTSC 2019

**Comment by eladkarako** [comment]
never mind, I had it working fine on  
Cumulative Update Preview for Windows 10 Version 21H2 (19044.1149)  
(iso generated with https://uupdump.net/selectlang.php?id=dd631ce3-c755-4b66-bdd0-9bd82137c71c with old .Net as well, Enterprise).  

I was disabling user account control and using this registry patch:  

```reg
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
"EnableLUA"=dword:00000000
```
and adding my admin user, every existing user and 'everyone' as full control on the drive (without changing ownership).  
and had it working.  
probably an overkill by I'm fine with it.
