### ISSUE TITLE
Crash on User-Login

### ISSUE THREAD

**Issue by NordicAT** [Open-Shell/Open-Shell-Menu#79]
Hello,

I am responsible for an enterprise Terminal-Server environment.
ClassicShell 4.3.1 is installed on multiple "Windows Server 2016" machines running Citrix XenApp 7.x.

Randomly when users login, ClassicShell crashes. This happens without user-interaction. (clicking the start-button, etc.)

![2018-08-31 08_23_41-standard - asg-remotedesktop 2018](https://user-images.githubusercontent.com/42859522/44896478-dbcf0300-ace7-11e8-963c-e1ba390a3a31.png)

The message is german. It means, that ClassicShell doesn't work anymore.
The button says "Close program". I press the button and after that ClassicShell still works normally. I can press the start-button and don't recognize any problems ...

An Event Shows up in Windows EventLog:

![2018-08-31 08_14_42-cl1312363 - configuration manager remote control](https://user-images.githubusercontent.com/42859522/44896522-028d3980-ace8-11e8-9400-bc29dc52e979.png)

This issue happens randomly and is not easy to reproduce.
What should I do? How should I debug this to get Support and maybe fixed in a future Version of Open-Shell?

Thank you

**Comment by ge0rdi** [comment]
We'd need a crash dump to be able to investigate:
- Get Sysinternals [ProcDump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) tool.
- Run `procdump.exe -e ClassicStartMenu.exe` from command line.
- Replicate the crash. Dump file (`ClassicStartMenu.exe_*.dmp`) should be created.
- Compress dump (e.g. ZIP) and attach it here.

Eventually you may try to use [latest Open-Shell nightly build](https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts) to see if it crashes too.

**Comment by ge0rdi** [comment]
You can register _ProcDump_ as a post-mortem debugger, so that it will create dump each time some application crashes:

`procdump.exe /i <dump-folder>`

It should then create crash dumps into supplied _dump-folder_.

**Comment by NordicAT** [comment]
Dear ge0rdi,

Thank you for the Information.
I finally got some crashdumps by using "procdump.exe /i <dump-folder>"

The application crashed. The following crashdumps have been created:

- ClassicStartMenu.exe_180904_152553.dmp
- ClassicStartMenu.exe_180904_152554.dmp

I got the following message:
![cs-error](https://user-images.githubusercontent.com/42859522/45034433-0fdb5880-b047-11e8-95e7-4a5653067571.png)

I did press the button "Programm debuggen", which means "debug program" in English and a third dump has been created:

- ClassicStartMenu.exe_180904_152646.dmp

Last week it took about 10 minutes to reproduce, but now it took hours. Therefore I hope the dumps are helpful.

[ClassicStartMenu.exe_Crashdumps.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/2348849/ClassicStartMenu.exe_Crashdumps.zip)

**Comment by ge0rdi** [comment]
There is `Sfrhook64` in crash call stack.

It seems to be part of some hooking `Citrix` product:
`C:\Program Files (x86)\Citrix\System32\Sfrhook64.dll`

Try to disable/uninstall that SW.
Eventually if you need it, try to add some exclusion for `ClassicStartMenu.exe`, so that it doesn't hook it.

**Comment by NordicAT** [comment]
Thank you for the analysis.

Citrix (XenApp VDA-component) is the main software running on the hosts and there is no possibility uninstalling it. I am not aware, that there are possibilities, to add exclusions for external processes.

I'm not a developer, but I wanted to kindly ask, if there is any chance for an alternative, perhaps fixing this from Classic-Shell/Open-Shell side?

As far as I know Classic-Shell was very popular on Citrix-installations, especially running on Server 2012r2.

Thank you

**Comment by ge0rdi** [comment]
I see.
But I don't think `ClassicStartMenu` is anyhow responsible for those crashes. Nor I can see a way how to mitigate it 🙁 

It crashes inside `Sfrhook64!HookNtQueryValueKey+0x73` (I was able to find Citrix symbol server).
So _Citrix_ SW is hooking registry operations and apparently something goes wrong.

I'd suggest to contact _Citrix_ and send them dumps for analysis.
They should be able to find the culprit (and if it turns out that `ClassicStartMenu` does something wrong, I'd gladly fix it).

**Comment by AveYo** [comment]
Official way to exclude specific apps from being hooked at https://support.citrix.com/article/CTX107825  

```batch
reg add HKLM\SOFTWARE\Citrix\CtxHook /v ExcludedImageNames /d "ClassicStartMenu.exe,StartMenu.exe" /f 
reg add HKLM\SOFTWARE\Wow6432Node\Citrix\CtxHook /v ExcludedImageNames /d "ClassicStartMenu.exe,StartMenu.exe" /f
```
Enter in a Command Prompt (Admin) - has both the old and the current project executables added

**Comment by NordicAT** [comment]
Thank you, but what's giving me a bad feeling about that is, that ALL hooks get disabled for the process and not the specific one.
The alternative is disabling the specific hook for ALL processes

**Comment by NordicAT** [comment]
Thank you @AveYo , but what's giving me a bad feeling about that is, that ALL hooks get disabled for the process and NOT the specific one:

> You can disable all Citrix API hooks for a single executable file by creating the following registry values ...


The alternative is disabling the specific hook for ALL processes:

> You can disable a specific Citrix API hook, corresponding to an associated feature, for all processes by creating the following registry values ...

**Comment by AveYo** [comment]
What exactly are you expecting from Open-Shell devs?  
To do a reverse-fix on the Citrix API hook that is actually crashing? 
If that was even feasible / allowed /  possible, we would not have games and stuff crash left and right because bad hooks for decades..  
Be reasonable and use the hooking external program built-in exclusions - you definitely don't need any Citrix API hooks into what it is basically an explorer hooking app itself.

**Comment by Nodens-** [comment]
> Thank you @AveYo , but what's giving me a bad feeling about that is, that ALL hooks get disabled for the process and NOT the specific one
This is exactly what you want to do.
