### ISSUE TITLE
Latest cumulative Win 10 update broke the Start menu

### ISSUE THREAD

**Issue by leandroprz** [Open-Shell/Open-Shell-Menu#791]
**Describe the bug**
After updating Windows 10 today my Start menu doesn't stay opened.

**To Reproduce**
1. Install these updates: https://i.ibb.co/7JmC2HQ/Untitled.png
2. Click on the Start menu
3. You should be able to see the menu, but it flashes for a second, then disappears.

**Expected behavior**
I expected to see the Start menu, but it disappears after clicking on it.

**Screenshots**
A quick video: https://drive.google.com/file/d/1MZ4ByYAZJNVAOlURS6gHcGcE5aUe0bv5/view?usp=sharing

**Version:**
 - Open-Shell: 4.4.169
 - OS: Windows 10 Pro 21H1 19043.1151

**Additional context**
I tried resetting all settings but that didn't fix the issue.

**Comment by Shintaro3000** [comment]
I am having the exactly the same problem on all 3 Win10 PC's in our house after the Win update today. 
I got Open-Shell: 4.4.169 and it still does not work.
OS: Windows 10 Home
I too tried resetting all settings but that didn't fix the issue.
The Win10 start menu does not work now too..
My wife works from home and this is really bad for her.
Please email if there is a fix.  vp-ustak@att.net
Thank you!

**Comment by wallymann** [comment]
yep, same issue here.    thankfully de-installing the MS update allows me to get back to work!

![2021-07-30 07_59_21-Installed Updates](https://user-images.githubusercontent.com/18448369/127651159-67b44083-0348-4181-b6d3-e2c6a29fe954.jpg)

**Comment by CaptPat** [comment]
same issue here.  start menu immediately disappears...

**Comment by eladkarako** [comment]
I was working around the updates issue by installing a fresh W10 integrated 21H2 on a Lenovo.  
I did used to have the same issues in the W10-2004 update, which didn't matter even when I've updated it manually - with the latest 4.4.169, which I solved by installing an older version of 4.4.160.  

<details><summary>and..</summary>
I strongly advise for you to use https://uupdump.net/ with your existing Windows 10 and Windows Kits 10 (ADK) installed, to generate an integrated installation and Rufus with GPT (not MBR) to make a USB installation, 
to freshly install the OS. Choose Enterprise and use HWID (https://github.com/massgravel/Microsoft-Activation-Scripts).  
Lenovo was finally able to use the MS store without an account and (finally) install that Lenovo Vantage to control the annoying FN keys switching permanently without accessing the BIOS every boot. 
</details>

**Comment by insectdude1258** [comment]
Windows 10 desktop and microsoft surface running windows 10, both having this issue after updates. it runs fine after reboot for a few seconds, then starts glitching out and closes every time you open it. i installed the nightly build from 7/11 and it still does it

**Comment by CaptPat** [comment]
uninstalling 4.4.169 and installing 4.4.160 does not change the behavior.  Both versions experience the immediate closing of the menu.  completely uninstalling OpenShell reverts to a functioning windows 10 standard menu;)  Someone in Redmond got a bonus for breaking OpenShell;)

**Comment by insectdude1258** [comment]
> 
> 
> yep, same issue here affecting 3 lenovo laptops running win10-64pro. thankfully de-installing the MS update allows me to get back to work!
> 
> ![2021-07-30 07_59_21-Installed Updates](https://user-images.githubusercontent.com/18448369/127651159-67b44083-0348-4181-b6d3-e2c6a29fe954.jpg)

unable to uninstall update 5004296 (windows requires this update to run). even tried uninstalling through powershell and it refuses

**Comment by Thunder27609** [comment]
same problem, after opening up my bowser, I click on the start button and hold the mouse button down, after 3 or 4 times the start menu stays open. Not a fix  but just passing this along.

**Comment by Shintaro3000** [comment]
I just found out my full my full screen game IL2 is doing the same thing the start button/menu is. It opens and the game starts but, if it is minimized, it flashes open for a second and closes again... That Windows update did more that just mess with the start button!!

**Comment by 42IDN** [comment]
On one computer out of 8, I see the same picture. Removing the program settings, downgrading the program version does not change the situation. On this computer, I had to uninstall Open-Shell.

**Comment by blackcrack** [comment]
Ordering system Version and update KBXXXXXXXX should you also posting for known with WinNT-Versions number with KBXXXXX Number for direct known which variables be also in the game ;) 

by the way, MS makes it any more harder with any update.. this is known if you surfing an bit in google about it ..

**Comment by Darkwolflair** [comment]
Hi,

same issue here, and I found what causes that issue on my PC (which receives that update) : my taskbar is located on the right of the screen, and since the update, Open Shell quickly closes. Just after, I see that other softwares with preview on the taskbar, when you go more than 20 windows to lookup, have the same issue (unable to select the opened windows from the till). 

But, if I put the taskbar on the bottom of the screen, everything is working fine. I also see that now I have weather displayed in the taskbar. If I disabled it, I no longer have both issues with multi-windows selection from the taskbar and collapsing of Open-Shell.

I hope it will last...

**Comment by blackcrack** [comment]
@Darkwolflair, Version of the Ordering system ? Version of OpenShell ?
otherwise will bring the statement nothing at all ..

**Comment by Thunder27609** [comment]
moving my taskbar back to  bottom did cure problem!

**Comment by Darkwolflair** [comment]
> @Darkwolflair, Version of the Ordering system ? Version of OpenShell ?
> otherwise will bring the statement nothing at all ..

Windows 10 21H1 19043.1151 // OpenShell 4.4.160

**Comment by Shintaro3000** [comment]
> moving my taskbar back to bottom did cure problem!

Thank you!!!!!   That worked for me too!!! Everything was there just like it was before!
Even my full screen Flight sim is back to normal. I do hope it gets fixed so I can move the taskbar back to the top, it has been that way on every PC I have had since Windows 3.1...

**Comment by wallymann** [comment]
>  I do hope it gets fixed so I can move the taskbar back to the top, it has been that way on every PC I have had since Windows 3.1...

same here...agree 100%...fingers crossed!

**Comment by CaptPat** [comment]
I also can say moving the Taskbar to the bottom of the screen restored functionality...  I had noticed odd behavior - usually menus closing prior to selection of an item - in other areas of the UI that were Microsoft's...  for instance notification area of the taskbar and associated menus and icons there exhibited similar issues...  Moved the taskbar to the bottom of the screen and all seems OK, so re-installed 4.4.169 version and all seems OK now.   windows 10, all updates, including the one that broke the functionality.  Hopefully Microsoft themselves will fix whatever they broke with the update.  Since they also broke their own notification area and many right-click menus in addition to OpenShell.   i have 7 machines here running Win10Pro all latest updates, G903 mice/G-pad - 10900K/Z490/3090's  and 11900/Z590/3090's - latest everything -  all had same issue with the update and all had 4.4.160 OpenShell.

**Comment by Thunder27609** [comment]
After moving the taskbar to bottom, everything work fine. After reboot, move taskbar back to top, works fine.

**Comment by CaptPat** [comment]
based on the above report I moved it back to the top and it works fine now.  Strange.  no longer a problem.

**Comment by ishindensin** [comment]
KB5004296 may have a bug.
Unless you put the taskbar "down" and click on an empty area on the taskbar to disable "news and interests", Openshell and Classic Shell will open and close immediately only on the main monitor. This cannot be selected unless the taskbar is "down".

**Comment by henrik1958** [comment]
Windows 10 21H1 19043.1151 // OpenShell 4.4.160/167/169
Move Taskbar to Bottom.
Right-click on the Taskbar. Turn off News and interests. 
Move Taskbar to Top. 
Back in business.

In Windows 11 there are big changes in the GUI. One is that only Taskbar at the bottom is supported and much more. I hope the developers of Open Shell will do what´s necessary to make it work properly. It can be fixed in Registry, but not a long term solution.
-Henrik

**Comment by wallymann** [comment]
i tried this -- start menu works ok when aligned to bottom, after moving start menu back to top...it only works correctly for the 1st click.  after that it reverts to the "disappearing" behaviour...also rebooting doesnt help at all.

start menu works fine if aligned to bottom or left or right side...but aligned to top of screen...it disappears when clicked as others have reported.

> 
> 
> After moving the taskbar to bottom, everything work fine. After reboot, move taskbar back to top, works fine.

**Comment by Thunder27609** [comment]
Intesting wallymann , mine is still working fine at top?

**Comment by Darkwolflair** [comment]
> i tried this -- start menu works ok when aligned to bottom, after moving start menu back to top...it only works correctly for the 1st click. after that it reverts to the "disappearing" behaviour...also rebooting doesnt help at all.
> 
> start menu works fine if aligned to bottom or left or right side...but aligned to top of screen...it disappears when clicked as others have reported.

Have you tried disabling the "News and Interests" feature (the one with weather appearing when putting the taskbar at the bottom)?

I think that plugin may cause an autorefresh that OpenShell can't manage.

**Comment by wallymann** [comment]
ah....yes...that solved it...THANK YOU EVERYONE!!!

> 
> 
> > i tried this -- start menu works ok when aligned to bottom, after moving start menu back to top...it only works correctly for the 1st click. after that it reverts to the "disappearing" behaviour...also rebooting doesnt help at all.
> > start menu works fine if aligned to bottom or left or right side...but aligned to top of screen...it disappears when clicked as others have reported.
> 
> Have you tried disabling the "News and Interests" feature (the one with weather appearing when putting the taskbar at the bottom)?
> 
> I think that plugin may cause an autorefresh that OpenShell can't manage.

**Comment by Aokromes** [comment]
"fix" on
#795 (comment)
