### ISSUE TITLE
"Slow" Start Menu with Windows Explorer open

### ISSUE THREAD

**Issue by DoubleGi74** [Open-Shell/Open-Shell-Menu#794]
I don't know if it's a bug or my own problem.

I have installed OpenShell 4.4.169 beta on Windows 11.
If Windows Explorer is closed everything works fine, the Start Menu responds fine.
When I open Windows Explorer and then open the Start Menu, its use becomes very slow and unusable, presenting an important lag.
What can I check to understand where the problem is?
I've also tried uninstalling and reinstalling OpenShell, but the problem is always there. 

1. Use OpenShell Start Menu
2. Open Windows Explorer
3. Open Start Menu
4. Mouse Hover is very slow

- Open-Shell: 4.4.169
- OS: Windows 11

**Comment by Shintaro3000** [comment]
Have you seen this yet DoubleGi74?
https://github.com/Open-Shell/Open-Shell-Menu/issues/791
Did you get a windows update in the last week? It looks like MS is playing with the start button..

**Comment by DoubleGi74** [comment]
> 
> 
> Have you seen this yet DoubleGi74?
> #791
> Did you get a windows update in the last week? It looks like MS is playing with the start button..

I dont'have that update.

I forgot to tell that problem was present in Windows 10 (Insider Version), it worked for a while, but now there's the problem again.
