### ISSUE TITLE
Startmenu opens then closes after recent windows update

### ISSUE THREAD

**Issue by Shadowtuy** [Open-Shell/Open-Shell-Menu#795]
KB5004296 
Causes Openshell And ClassicShell to open and close immediately only on main monitor for some reason.
No issue on second monitor. 

Uninstalling update removes issue for the time being.

**Comment by JohnBlumstein** [comment]
Yes damn, same issue here. Win 10 Pro 21H1 german.

**Comment by Thunder27609** [comment]
check out the other thread, I move my taskbar back to bottom and menu work fine, rebooted and put taskbar back to top and it work fine too.

**Comment by ishindensin** [comment]
KB5004296 may have a bug.
Unless you put the taskbar "down" and click on an empty area on the taskbar to disable "news and interests", Openshell and Classic Shell will open and close immediately only on the main monitor. This cannot be selected unless the taskbar is "down".

**Comment by Warlock-Weary** [comment]
Yeap : KB5004296 Broke it ..

However can be fixed .. move start bar to bottom of screen.
disable ( news and interests ) ( Right Click Bar goto news and interests and disable )
Now reboot .. move bar to TOP / SIDE make sure news and interests is still disabled.
Should be fine now ! Good Luck  :)

**Comment by JohnBlumstein** [comment]
Thanks for the workaround, guys. 
Tried to reinstall the KB and it's working now.  
I'm using Classic/Open Shell since Win 8 and I can't live without.

**Comment by mmalloy0** [comment]
This WORK AROUND worked and crazy how anyone figured this out, but THANK YOU!

**Comment by Shadowtuy** [comment]
> Yeap : KB5004296 Broke it ..
> 
> However can be fixed .. move start bar to bottom of screen.
> disable ( news and interests ) ( Right Click Bar goto news and interests and disable )
> Now reboot .. move bar to TOP / SIDE make sure news and interests is still disabled.
> Should be fine now ! Good Luck :)

Confirmed working, windows fully up to date and working fine with it.

**Comment by BobJorge** [comment]
I've already tried all the options I've seen here on this blog.
My Windows does not have the News and Interest option to run from the Task Bar. 
The only way of to see the Open-Shell Start Menu is to fix the Task Bar on de left side of the screen.
If someone
If anyone has any new tips i would greatly appreciate your post.
Thank you!

**Comment by Shadowtuy** [comment]
> I've already tried all the options I've seen here on this blog.
> My Windows does not have the News and Interest option to run from the Task Bar.
> The only way of to see the Open-Shell Start Menu is to fix the Task Bar on de left side of the screen.
> If someone
> If anyone has any new tips i would greatly appreciate your post.
> Thank you!

"News and interest" option appears when you right click on taskbar when the taskbar is at the bottom of the screen only it appears.
Move to bottom of screen
Right click and disable "news and interests" 
Move back taskbar to your desired location

**Comment by planalp** [comment]
Yes, the solution involving moving the taskbar, etc. worked for me perfectly.  Thanks all!

**Comment by unmog** [comment]
Was on Classic Shell, ran into this problem. Tried updating, reinstalling, then installing the new Open Shell. Couldn't figure out what was going wrong until I read the information here, thanks to everyone for sharing.

Anyone have any idea when this will be fixed so we can have the task bar on the top along with the new and interests enabled? I rather like knowing the weather and temperature outside on my computer.
