### ISSUE TITLE
New Folder in wrong place

### ISSUE THREAD

**Issue by Krodo77** [Open-Shell/Open-Shell-Menu#80]
Using the Organize Start menu -> New Folder option creates a new Folder in %user%\AppData\Local\Micosoft\Windows. That makes no sense. The correct location should be %user%\AppData\Roaming\Micosoft\Windows\Start Menu\Programs.
![open-shell_1](https://user-images.githubusercontent.com/43062831/45210089-f2003480-b28e-11e8-9a38-59f49af51bb8.png)

**Comment by bonzibudd** [comment]
Has this issue been fixed? It seems odd that an “Easy fix” tag would be left open for so long.

**Comment by NebelNidas** [comment]
Yep, just tried it, has indeed been fixed! 👍
