### ISSUE TITLE
Taskbar texture on Windows 11 not working correctly.

### ISSUE THREAD

**Issue by Sakyce** [Open-Shell/Open-Shell-Menu#803]
1. Get Windows 11, I have the 22000.120 Build.
2. Set a new taskbar texture.
3. After the taskbar texture glitches a bit or even doesn't show at all, it works but it's not shown behind the currently opened apps icon.
![image](https://user-images.githubusercontent.com/55030860/128636150-6708946e-2247-4fbc-9c22-d78c7773d389.png)

The taskbar should show correctly like in Windows 10.

**Version:**
 - Open-Shell: 4.4.160
 - OS: Windows 11 21H2 22000.120 Build

**Comment by AoifeConneely** [comment]
Hi
Windows 11 has chanegd the way the taskbar and start menu work so Open Shell does not work at the moment.
I've found this discussion thread that might be useful - https://github.com/Open-Shell/Open-Shell-Menu/discussions/745

Please note that I am not one of the developers, I am simply a member of the community.

Thanks
A

**Comment by ge0rdi** [comment]
Fixed in [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build.
