### ISSUE TITLE
App start by first letter after win bar opened

### ISSUE THREAD

**Issue by sanakess** [Open-Shell/Open-Shell-Menu#805]
**Describe the bug**
Sometimes when im press WIN button and start to search something, search doing wrong and start application in WIN list by first key i pressed. 

**To Reproduce**
search in "access normaly" mode in basic settings does not always work. It look like it sometimes work like "access with tab" mode. It makes randomly. 

To see what happend then search work wrong, do:
1. Go to basic settings
2. Click on show search box
3. check "access with tab" 
4. type win key and any first key of app in your pinned apps in start menu

**Version:**
 - Open-Shell: [ 4.4.160]
 - OS: [Windows 10 21h1]

**Comment by ge0rdi** [comment]
Search should be now properly focused when start menu is opened in [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build.

Additionally, it is now possible to configure accelerators to trigger only when Alt is pressed (`Require Alt key for accelerators` setting) or disable keyboard accelerators completely (`Enable accelerators` setting).
