### ISSUE TITLE
Add warning about "News and Interests" panel to README.md

### ISSUE THREAD

**Issue by thisismy-github** [Open-Shell/Open-Shell-Menu#818]
There's been a large influx of complaints about the new bugs introduced by the News and Interests panel in recent updates, and Microsoft seemingly has no intention of fixing these bugs anytime soon... or ever. To prevent confusion for the swarms of people affected by this issue (many of which likely not being familiar with GitHub's layout), we should add something directly to the README explaining what causes the bug as well as how to fix it.

**Comment by BraINstinct0** [comment]
Also if automating the fix is possible, I'd suggest it be added to the installation process.

**Comment by Aokromes** [comment]
#795 @ge0rdi @coddec
