### ISSUE TITLE
when i install open shell and play roblox my roblox textures don't load but i have a really good pc 

### ISSUE THREAD

**Issue by dicio123** [Open-Shell/Open-Shell-Menu#825]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**
 - Open-Shell: [e.g. 4.4.131]
 - OS: [e.g. Windows 10 1903]

**Additional context**

**Comment by aor2021** [comment]
I think its just ur textures being corrupt
