### ISSUE TITLE
Cursor auto clicks when I start-up Windows.

### ISSUE THREAD

**Issue by Lillipad** [Open-Shell/Open-Shell-Menu#831]
**Describe the bug**
Everytime I start up Windows 10, the mouse auto clicks, causing EVERYTHING to glitch out. it opens random stuff I do not mean to open.

**To Reproduce**

**Expected behavior**
I expect the mouse to not auto-click on things I do not mean to open, so I can customize my Start Menu however I want.

**Screenshots**

**Version:**
 - Open-Shell: [e.g. 4.4.131]
 - OS: [e.g. Windows 10 1903]

**Additional context**
I have tried uninstalling and reinstalling, and that seems to work, UNTIL I start up Windows again, then it glitches out all over again.

**Comment by blackcrack** [comment]
"Joined 31 minutes ago" woow extra a new account... 

buy a new Grafic Card or buy a new Windows 10 in the Computerstore at the corner of your Town
this is not a Open-Shell thing...

best
Blacky

and by the way.. why do you think why it gives a Issue posting-matrix before you Post ..
for ignore it ?

this issue should be closed ..

**Comment by Brad-git-man** [comment]
> Everytime I start up Windows 10, the mouse auto clicks,

How old is your mouse? Are the springs worn out in it? Did you buy it for Win 95 or if you're not that old, did someone from back then give it to you? I have worn mouse button springs out before & they do the same behavior you describe.
