### ISSUE TITLE
Classic Shell Explorer doesn't go away even if uninstalled

### ISSUE THREAD

**Issue by Yaroooo1** [Open-Shell/Open-Shell-Menu#838]
In Explorer window you can deactivate Classic Shell Explorer, but this leave a tiny bar of a color that is different from Explorer dark theme.

Also trying to correct installation removing Classic Shell Explorer doesn't solve this problem.

Is possible to act on Win 10 registry to manually remove this bar?

![Screen](https://user-images.githubusercontent.com/48443296/133219684-2716a8ff-335b-477d-93a7-6a65391da0d9.png)

**Comment by Unknown6656** [comment]
I have the very same problem.

**Comment by Yaroooo1** [comment]
I've found that problem is generated by Classic Shell but it's related to a Windows Explorer setting.
You can remove this bar by this steps:
- Open Internet Explorer;
- Right-click on the toolbar or title-bar;
- From the fly-out menu, select ‘Lock the toolbars’ option.
