### ISSUE TITLE
OpensShell no longer works since the recent Windoes 10 update

### ISSUE THREAD

**Issue by ghost** [Open-Shell/Open-Shell-Menu#842]
Since loading the Security Update for Windows 10 (KB5005565) and the Servicing Stack 10.0.09041.1220 both on 15 September 2021, Open-Shell no longer works on my system. When I click the Start button on my desktop my system freezes for a couple of moments, reverts to the original Windows 10 start menu for a second, then goes back to the Open-Shell style, however clicking on the Start menu button, the menu does not open. I can not acees the start menu from my desktop. I have uninstalled and re-installed the Open-Shell program, but this has not resolved the issue. This issue did not occur prior to the recent Windows update

**Comment by DaVyper** [comment]
![image](https://user-images.githubusercontent.com/21184466/133970216-aa123b48-db8b-4efc-a5e4-e9217d79ccb1.png)
works fine for me

**Comment by klepp0906** [comment]
yea i just came to post about the same thing.  just rolled up to windows 11 since its now at RTM and no more open-shell.  RIP
