### ISSUE TITLE
Control Panel sorting bug

### ISSUE THREAD

**Issue by Gaurav-Original-ClassicShellTester** [Open-Shell/Open-Shell-Menu#843]
I installed Open Shell 4.4.170 on both Windows 10 and Windows 11. There is some sort order issue with Control Panel on any build. Here's a screenshot from Windows 10 (see how items with C begin again after Windows Defender Firewall).

![image](https://user-images.githubusercontent.com/46422834/133943796-027dbb72-0d8a-4926-b443-fc20cd0c36ef.png)

Even after Sort by name or Auto arrange, the order is not right.

**Comment by ge0rdi** [comment]
This should be fixed in latest nightly already.
