### ISSUE TITLE
Custom Start button bug when scaling set to 125%

### ISSUE THREAD

**Issue by StarryWindy** [Open-Shell/Open-Shell-Menu#846]
**Describe the bug**
When I picked the custom Start button in my laptop, because the scaling is set to 125% by default because it's on 1920x1080 resolution, the Start button looks tad bit smaller, to the point that I have to adjust the button size in Open-Shell's settings for it to look right. This problem is mostly obvious when I picked XP-styled Start button. This looks odd compared to the 2 preset buttons included in the app (Aero and Classic buttons) that are already scaled properly.

**To Reproduce**
1. Make sure the Scale and layout in Windows Settings is set to 125%
2. In Open-Shell, select a custom Start button.
3. The Start button would look smaller.

**Expected behavior**
I was expecting them to scale well just like when the scaling was 100%.

**Screenshots**
![openshell error](https://user-images.githubusercontent.com/88781160/134624770-ded66890-efe8-42e9-b264-cef2d11ed45a.png)

**Version:**
 - Open-Shell: 4.4.169
 - OS: Windows 10 21H1 (64-bit)

**Comment by bonzibudd** [comment]
Open-Shell uses the true size of custom buttons, so it's not a bug that it doesn't scale to 125%. The original button was the correct size at 100% because that is the size of the original file.
