### ISSUE TITLE
Recent applications do not appear under Start Menu (Windows)

### ISSUE THREAD

**Issue by operalover** [Open-Shell/Open-Shell-Menu#851]
For some reason, none of my recently used applications appear now in the "left panel" under Start Menu (Windows).
I've never had this problem before, and I've been a very, very long-time user.
I uninstalled and reinstalled Open-Shell-Menu, but the problem persists.
Please see the attached screen capture.
Any suggestions would be appreciated.

<img width="325" alt="Open Shell 2021-09-30_19-17-46" src="https://user-images.githubusercontent.com/44822781/135547577-5627ba88-86b9-4873-ba0b-12e6b7c7e972.png">

**Comment by Gaurav-Original-ClassicShellTester** [comment]
Check your settings. If using Frequent, the Windows setting also needs to be on:

![image](https://user-images.githubusercontent.com/46422834/135605561-bf5c86b6-bf0b-408e-8116-b6b3d3820175.png)
![image](https://user-images.githubusercontent.com/46422834/135605637-56869521-0218-4f5b-bfed-e6e257ddb4ff.png)

**Comment by fiskhest** [comment]
![tempsnip](https://user-images.githubusercontent.com/26885267/136738345-77848cf1-c6df-4b05-a553-7f54e774c202.png)

Any way to unlock that setting if it's disabled? (I have no idea how it's been disabled, I only noticed the issue of missing menu items after a windows update)
