### ISSUE TITLE
doesnt open directly to folder

### ISSUE THREAD

**Issue by clutchmaster420** [Open-Shell/Open-Shell-Menu#852]
i have folders pinned in this thing and instead of opening to the proper location it open to my appdata folder this needs to be fixed
what it opens to:
C:\Users\clutc\AppData\Roaming\OpenShell\Pinned\Completed
what it should be opening to:
G:\[01A]Downloads\Completed

**Comment by Gaurav-Original-ClassicShellTester** [comment]
Try Open Shell 4.4.170 from here: https://1drv.ms/u/s!AvOMnbjzo1eEkwyqayBPDOHuWx0v?e=w5OPCp and this setting: (The build from AppVeyor has been auto-deleted since it's older than a month).

![image](https://user-images.githubusercontent.com/46422834/135649758-57bd917c-abb3-4880-9faa-7809d585b293.png)

**Comment by clutchmaster420** [comment]
> Try Open Shell 4.4.170 from here: https://1drv.ms/u/s!AvOMnbjzo1eEkwyqayBPDOHuWx0v?e=w5OPCp and this setting 'Open pinned folders to their true path' : (The build from AppVeyor has been auto-deleted since it's older than a month).
> 
> ![image](https://user-images.githubusercontent.com/46422834/135649758-57bd917c-abb3-4880-9faa-7809d585b293.png)

thanks

**Comment by clutchmaster420** [comment]
great why isnt this part of the main program cause this option disappeared

**Comment by ge0rdi** [comment]
@clutchmaster420 
The option `Open pinned folders to their true path` was added in 4.4.174 (thus it is nor present in official release yet).
Please, use [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) `Open-Shell` build.
