### ISSUE TITLE
How to uninstall Open-Shell?

### ISSUE THREAD

**Issue by edgarfigueira** [Open-Shell/Open-Shell-Menu#855]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**
 - Open-Shell: [e.g. 4.4.131]
 - OS: [e.g. Windows 10 1903]

**Additional context**

**Comment by aor2021** [comment]
The same you do it for classic shell. But for me i had a problem so i had to kill explorer.exe
