### ISSUE TITLE
Remove Hotkeys "u" "w" "L" "o" "R" "S" "H" for Shutdown, Switch User, Log Off, Lock, Restart, Sleep, Hibernate

### ISSUE THREAD

**Issue by xSimone** [Open-Shell/Open-Shell-Menu#857]
Not sure whether or not to label this a bug, or a feature request, because it's kind of both.

Sometimes when typing into the search bar, I'll type something "Du" and press enter, sometimes it doesn't register I'm typing into the edit box for searching, and instead thinks I'm using hotkeys and will shu̲tdown my PC

Can we have a toggle, unless there already is one, to DISABLE this?

**Comment by RenHoekNL** [comment]
I'll second this.. it's been a few times when I hit the Windows key and start typing for the Search box but I'm too quick and I shutdown the computer instead.

Or give us the ability to change the hotkeys (and thus remove) when you edit a menu item.

**Comment by updawg** [comment]
Third - I've shutdown/rebooted my computer accidentally multiple times due to the search box not taking focus.

**Comment by Catfriend1** [comment]
Me too :). Sorry for the extra post. But despite this request, I'm a very happy year-long user of OpenShell . Thanks for all your work.

**Comment by IkkixD** [comment]
I'm jumping on this too! I love open-shell, however recently a game I've been playing has a hotkey that I have to press frequently (Alt + U) and the amount of times I fat finger the windows key and immediately get a forced computer shutdown that I didn't want is very annoying!

**Comment by ge0rdi** [comment]
Search should be now properly focused when start menu is opened in [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build.

Additionally, it is now possible to configure accelerators to trigger only when Alt is pressed (`Require Alt key for accelerators` setting) or disable keyboard accelerators completely (`Enable accelerators` setting).

**Comment by xSimone** [comment]
It might've taken a while, but it got done! Awesome. <3
