### ISSUE TITLE
Is this Windows 10 1809 ready?

### ISSUE THREAD

**Issue by ImSpecial** [Open-Shell/Open-Shell-Menu#86]
So the rumored 1809 release date is October 2nd, so it's just a week away from now, and I'm currently still using official Classic Shell 4.3.1, my understanding is that this version does not work with the new Windows 10, so I'll need to use this fork instead, is everything working okay on the newest Windows 10 1809 build? Where's the download link that people like myself should be downloading, and is there anything I need to do or make note of to carry over my current settings when I update Classic Shell to Open Shell?

**Comment by isshininu** [comment]
Classic Shell 4.3.1 works on 1809 so far.

**Comment by DrTeeth707** [comment]
Is this project still alive?

**Comment by XenHat** [comment]
> Is this project still alive?
Yes, definitely.
Progress depends entirely on the team members' availability. I am currently busy with other projects and other life matters.

**Comment by coddec** [comment]
We are not dedicated full time Open-Shell developers.
We are from community as well just like you, so we need to take care of our lives just like others.

Thanks for asking though, it is still alive, confirmed.
Thanks for answering @XenHat long time ;) Sorry I'm currently busy with other matters too.

**Comment by DrTeeth707** [comment]
No disrespect was intended by my question. It is just when things go quiet, one does begin to wonder.

Cheers

DrT

**Comment by ImSpecial** [comment]
Wait so Classic Shell 4.3.1 works on 1809? And how does one upgrade to this fork if I decide to go that route, do I install over top Classic Shell or do I need to uninstall Classic Shell first?

**Comment by ge0rdi** [comment]
> Wait so Classic Shell 4.3.1 works on 1809?

Yes, it seems to be working well.
There was some issue with some RS5 preview builds in the past. But apparently MS did some _fix_ and it works on final RS5 build (17763).

> do I install over top Classic Shell or do I need to uninstall Classic Shell first?

It should be possible to install over `ClassicShell`.

Though there seems to be some issue with _Windows Installer_ that it may not restart _explorer_ correctly (this is not related to `OpenShell` only). And we don't have any automatic workaround for this currently.

So probably the safer option is to uninstall `ClassicShell` first. Settings will get migrated either way.

**Comment by coddec** [comment]
@DrTeeth707 
Backup is always good ;)
If you are willing to take a chance.
1. Backup classic shell settings (use export to xml option)
2. Uninstall classic shell
3. Install open-shell
4. Import xml file to open-shell.

Though, I do not guarantee there's 0 chance of error.
If there's any, it won't kill your PC, the worst case is the open-shell cant' work correctly, just reinstall classic-shell then. I haven't heard of any major issues though.
Take extra care if you have many skins installed for classic shell, I did hear that some custom skins can cause issue while using this way to migrate.

Good luck!

**Comment by ge0rdi** [comment]
Latest [nightly](https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts) build does import settings from previous `ClassicShell` installation.

It was added in this [commit](https://github.com/Open-Shell/Open-Shell-Menu/commit/07a5a7ba7249e731ba7442ef4028a0536ab675e0).

**Comment by DrTeeth707** [comment]
Cheers. Will install that later today after backing up settings.
Many thanks for the info on the nightly.
Cheers
DrT

**Comment by ImSpecial** [comment]
Just made the switch, seems everything went smooth, a big shout out to all you guys who are keeping this project alive, I was really dreading the Windows 10 update thinking this might break, but now I'm ready!

**Comment by DrTeeth707** [comment]
No need, just need to make a restore point before installing beta programs. I was not worried about the explorer.exe issue as I have had it before. Explorer and also be restarted from the task manager.

It was the "pin to start" issue that flummoxed me.

Take care

DrT

**Comment by XenHat** [comment]
Is this still an issue?

**Comment by dragnilar** [comment]
@XenHat  I updated to 1809 a week ago and haven't found any problems myself. Not sure if you are waiting to hear back from @ImSpecial .

I noticed another problem (Classic Explorer doesn't seem to have a dark theme to match the new dark theme in File Explorer. Do you want me or someone to make a  Feature Request? You have #98  but it looks like that is for Windows 8, not 10).

**Comment by thegreatestminer** [comment]
The Start Menu part works perfectly on Windows 10 1903. I can't say for any other features, as I have not installed them.

**Comment by Ibuprophen** [comment]
I'm not sure why this issue is still open as the topic has been addressed/confirmed on a few occasions as working. 


~Ibuprophen
