### ISSUE TITLE
Plz Update Headpage's on Configuration Window at bottom..and..

### ISSUE THREAD

**Issue by blackcrack** [Open-Shell/Open-Shell-Menu#87]
Hi,

Plz Update the head Headpage url on Configuration Window at bottom..and..

and at the Mainpage at
http://www.classicshell.net/
The history and add the link 
to this Github-page .. or exist a other Open-shell-menu.org page ?

best regards
Blacky

**Comment by ge0rdi** [comment]
Seems to be already fixed.
