### ISSUE TITLE
In Classic Explorer, the default font in the status bar is not the current system font size

### ISSUE THREAD

**Issue by Anixx** [Open-Shell/Open-Shell-Menu#870]
And no size entered into this field can make it the default size (for me, 9 is too big and 8 makes the text too small, though the system default is 8pt).

This is a minor issue, as making the field empty makes the font exactly as system default. As a partial easy fix, I suggest to make this field empty by default, that will make the font of the system default size. Changing it to 9 or 8 will increase or decrease the size.

**Comment by ge0rdi** [comment]
What is the version of Windows and `Open-Shell` you are using?

> And no size entered into this field can make it the default size

What field are you referring to?

Please, provide more clear description of your issue. Add screenshots that will show it.
Describe exactly what are you doing (in steps).

Feel free to re-open then.

**Comment by Anixx** [comment]
I am currently using Microsoft Windows [Version 10.0.22000.1098], but the issue was reported when I was using Windows 8.1. The issue remains. OpenShell version is 4.4.169.

I am referring to this setting:

![изображение](https://user-images.githubusercontent.com/1271736/206939045-63a0f2ef-22e0-4633-bf9e-cf800599cb03.png)

When it is empty the font is correct, system-wide size. The default value though, makes the font wrong size and no other value except empty makes the font to have correct size.

As a partial fix, I suggest to make this value empty by default.

**Comment by Anixx** [comment]
How do I reopen this?

**Comment by ge0rdi** [comment]
Please, provide screenshots (and all info) in English.
