### ISSUE TITLE
When the action of root shutdown item is not default, an empty element appears in the menu

### ISSUE THREAD

**Issue by Anixx** [Open-Shell/Open-Shell-Menu#871]
![изображение](https://user-images.githubusercontent.com/1271736/136670282-d554a686-14cc-4b0d-ad28-2d707a9d02a9.png)

The empty item appears only if the action link links to a file using full path, and the file exists. 

This depends only on the root (folder) item of the shutdown box, not the item inside the list.

If it uses a command such as "shutdown -p" the empty item does not appear. If the file does not exist, there is no empty item either. If there are command prompt parameters, there is no empty item, only if there are none.

For instance, link %SystemRoot%\System32\shutdown.exe produces empty item, whille %SystemRoot%\System32\shutdown.exe -p does not.

This does not depend on theme.

**Comment by ge0rdi** [comment]
Please, provide exact steps you are doing to replicate the issue.
Feel free to re-open then.
