### ISSUE TITLE
is windows 11 but in classic menu shows windows10!

### ISSUE THREAD

**Issue by Cla77bz** [Open-Shell/Open-Shell-Menu#878]
Hello,

i use open shell in Windows11 an in my classic menu it shows   WINDOWS10 (see attachement Foto)

how can i change this
![win11](https://user-images.githubusercontent.com/63242086/137451969-cc001c85-4caf-419e-a0b9-0f05bdc10b8e.jpg)
?

**Comment by Gaurav-Original-ClassicShellTester** [comment]
There is a Menu Caption setting on the Menu Look tab in Settings. Or you can use search box in Settings window to find it.

You can also always search in the Classic Shell forum first using Google.
