### ISSUE TITLE
upgrade install 131 from 109 

### ISSUE THREAD

**Issue by Clintlgm** [Open-Shell/Open-Shell-Menu#88]
I ran 131 as an upgrade from 109. Explorer could not be shut down. I said to try again, again it said explore could not be shut down options were install anyway and restart required or try again. I selected try again and the install completed. I was left with a blank screen for me I use a blue back ground and I was left with that and my 8gadget pack gadgets still running but no way to restart or shut down. I just used my power button to shut down and on restart 131 has installed with my settings as they were on 109. All seems to be working fine

**Comment by ibuprophen1** [comment]
Just as a suggestion for manually restarting Explorer... 

1) Use the Key Combination "Ctrl + Shift + Esc" to launch the Task Manager.

2) Select/Highlight the Windows Explorer on the list and then, at the Bottom Right, select the Restart Option.

This is just one option... 

Good Luck! :-) 


~Ibuprophen

**Comment by ge0rdi** [comment]
This is currently handled by MSI installer itself.
It is supposed to terminate processes that are using `Open-Shell` binaries (typically `explorer.exe`), then install new version and restart those processes.
