### ISSUE TITLE
'Useful links' points to http://www.classicshell.net

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Open-Shell/Open-Shell-Menu#880]
**Describe the bug**
The help file (right click tray, select 'Help' and then 'useful links') points to http://www.classicshell.net.

**To Reproduce**
See above.

**Expected behavior**
The link should be to https://github.com/Open-Shell/Open-Shell-Menu (or to a similar page).

**Screenshots**
![image](https://user-images.githubusercontent.com/47056543/137552717-c80156f2-db08-4f9e-8a64-8c9834104a12.png)

**Version:**
 - Open-Shell: Version ~~4.3.1 – general release~~. EDIT: no, it is 4.4.169.

 - OS: Windows 10 Pro - 21H1 (2009: 19043)

EDITED to insert a missing parenthesis.

**Comment by acshef** [comment]
Can you confirm your version? Look at the titlebar of the OpenShell settings window -- the home page of the help docs show an outdated version (mine shows "4.3.1 - general release" even though I'm on 4.4.131)

**Comment by LinuxOnTheDesktop** [comment]
acshef: good call. It turns out I am on OpenShell 4.4.169:

![image](https://user-images.githubusercontent.com/47056543/137580682-ddf3c46f-e5a0-4d0b-b93d-c471b96fd52e.png)

So here we have a second bug.

**Comment by Ibuprophen** [comment]
I didn't realize they were still there... 

I see quite a bit of them and, with all the localization entries, it would be a bit tedious as well. 

I wouldn't consider this a bug. It more like a minor update that's needed within the Help menu itself. 

Hmm... 

Thank you very much for pointing this out too. :-)) 


~Ibuprophen
