### ISSUE TITLE
Open Shell and StartAllBack together

### ISSUE THREAD

**Issue by usoquesto** [Open-Shell/Open-Shell-Menu#887]
Dear everyone,
i read that you suggest in different posts to make aa mixed usage of Open Shell (Start menu) and StartAllBack for all the rest: http://www.classicshell.net/forum/viewtopic.php?f=7&t=8580

I have indeed installed both and i have a display issue of the "program preview" once you move the mouse onto application in the task bar: there is a huge blurred row around and over the programs.

![thumbnail_blurred](https://user-images.githubusercontent.com/93029616/138547366-8bc0cf2c-5272-4b85-a34f-9ae1a111d201.jpg)

Uninstalling Open Shell leaving StartAllBack solves the problem, but then the best Start Menu program ever written is out and i cannot use it. Is there a way to fix this problem?

Thank you so much for the great features you give us with this program

**Comment by lullofthesea** [comment]
I had this issue as well on latest dev build.  Clean installed to the current beta build (22000.282) and have not been able to reproduce it.  Can't think of any program in particular off the top of my head that would cause this behavior.  Using custom theme currently, but light and dark themes work just fine.

**Comment by usoquesto** [comment]
Hi lullofthesea and thank you for replying!
I see what you mean, but how do you explain that newly installed virtual machines (3 in total) have all the same problem?

**Comment by lullofthesea** [comment]
> 
> 
> Hi lullofthesea and thank you for replying! I see what you mean, but how do you explain that newly installed virtual machines (3 in total) have all the same problem?

What build of W11 are you using?  Also, what is the virtual machine software you are using?  I can probably try some testing on my end to see if I can get the issue to appear.

**Comment by usoquesto** [comment]
Hello DanceOfArrows, apologies for the late reply.
On all computers/VM i am having Windows 11 21H2 Build 22000.282
For the virtual machines i am using VMware Workstation 16 player

Thank you so much for taking time to check this!!

**Comment by DanceOfArrows** [comment]
Sorry for the late reply.
I tested the exact same set up and could not get startallback to work -> it kept crashing explorer continuously. 
Afterwards, I clean installed 22000.348 which ran flawlessly.  Not sure why it kept crashing on the other install

**Comment by usoquesto** [comment]
ok so you think that if i run a clean install should also correct the problem of this topic?
it is strange because on the virtual machine it was clean installed...

**Comment by usoquesto** [comment]
Hello all,
i just wanted to say that the problem described here was solved with the new version of open shell: OpenShellSetup_4_4_170

now i have active the transparency and the effect is perfect. Does anybody know what changed?
