### ISSUE TITLE
Missing icons in Start menu on Windows 7

### ISSUE THREAD

**Issue by truefriend-cz** [Open-Shell/Open-Shell-Menu#90]
In open-start menu on Windows 7 only missing all icons of items.

**Comment by LOuroboros** [comment]
Can confirm. I just installed Open Shell on Windows 7 Professional x64 because it's more configurable than the default start menu, and surprise surprise, every icon that should appear within Open Shell's start menu seems to be missing.
I didn't have this issue back on Windows 8.1, in case it matters.
![1](https://user-images.githubusercontent.com/4485172/62742299-6e0d7a00-ba14-11e9-975c-b4577b3f7ae8.png)
![2](https://user-images.githubusercontent.com/4485172/62742300-6ea61080-ba14-11e9-89a2-4c8aa5e83bae.png)

**Comment by CollinChaffin** [comment]
I run mostly Win7x64 on most of my boxes and I've never had this occur.  Just curious, did you select all options when you installed including IE?  Try this:

Open IE go to addons, ensure all the open/classic shell addons are enabled.  Also, are you doing any kind of folder redirection for your profile and/or by chance any kind of custom symlink/junctions?

Just a couple ideas other than clearing your icon cache or uninstalling, rebooting and reinstalling etc.

**Comment by nanoscopic** [comment]
I am running Windows 7 SP1, and I also don't see icons next to either folder or programs in any of the cascading menus. ( classic view )

I installed OpenShell via the OpenShellSetup_4_4_142 release. I selected all options, and checked IE and all the addons are enable.

This is a fresh brand new updated install of Windows 7 and has been rebooted multiple names. I have also reinstalled OpenShell and it makes no difference.
![openshell_snap](https://user-images.githubusercontent.com/905365/70821569-4c404d00-1d90-11ea-8c49-df98a09fb5eb.png)

**Comment by PF94** [comment]
Also happens to me on a virtual machine. It gives me the impression that something is corrupted.

**Comment by bonzibudd** [comment]
I am using release 4.4.142 and do not see this issue, I am using a fully updated VM of Windows 7 Professional x64. I only installed the menu and disabled the IE and Explorer extensions if that changes anything. 
![image](https://user-images.githubusercontent.com/61938331/83285938-20354e80-a1ad-11ea-8526-2533efc6f0aa.png)

**Comment by danskee** [comment]
Also same problem here, occurs on 4.4.131, .4.4.142 and 4.4.145.
![Capture](https://user-images.githubusercontent.com/67833514/86515317-b7329d80-be20-11ea-9c7a-0ce6c966cf88.PNG)

**Comment by bonzibudd** [comment]
I was just able to reproduce this:
![image](https://user-images.githubusercontent.com/61938331/100488583-11d4da80-30dd-11eb-981b-27f8efec3b90.png)
![image](https://user-images.githubusercontent.com/61938331/100488629-519bc200-30dd-11eb-87f1-cc595a6d0ef6.png)
It's a brand new install, with SP1 but no additional updates. I think it might have something to do with that.

@ge0rdi 

What sort of log should I upload to diagnose the issue?
