### ISSUE TITLE
Is it possible to add Large font option to Classic skin.

### ISSUE THREAD

**Issue by towlerg** [Open-Shell/Open-Shell-Menu#906]
**Is your feature request related to a problem? Please describe.**
Recently bought a 3840x2160 monitor and found everything too tiny unless I use 200% scale. But font size of start and start sub menus seems to be unchanged and so looks tiny. I'm using the Classic skin.

**Describe the solution you'd like**
Add Large font option to Classic skin

**Describe alternatives you've considered**
Use a skin that does have the Large font option. Basic gets it done.

**Additional context**
pretty please

**Comment by CTVCAM8** [comment]
Have you tried increasing the "Override system DPI" in the "Menu Look" tab of Open-Shell settings?

![200 percent display size](https://user-images.githubusercontent.com/44127216/142273616-cc26d91a-b3bc-40f2-b7a3-cf74fb762db8.png)

Someone on Classic Shell wanted the opposite.
@raywood wanted a smaller font for the tiniest menu in the world.
I borrowed the adjustable text size option from the Metallic skin. 
I'm not sure if that option still follows the system font or not.
I'm not even sure if it worked.
You could try out that modded classic skin and instead increase the text size:

http://classicshell.net/forum/viewtopic.php?f=7&p=36497#p36497

**Comment by towlerg** [comment]
Thanks for the above info. I seem to have screwed something up because even tho override DPI reset to 0 it no longer seems to be honored neither  does large font. Soon as I get a chance I'll reboot and perhaps reinstall.

**Comment by towlerg** [comment]
As far as I can tell Override system DPI does nothing. My be specific to my config.

Anyway now have working solution. System DPI set to 150%, make text larger (who says that ms are dumbing the os down) 175% and Widows basic skin with large text ticked.

**Comment by Mero-IOS** [comment]
I'll add to this: DPI setting does nothing on my Windows 10 Machine either.
