### ISSUE TITLE
Start Menu Appears Offscreen

### ISSUE THREAD

**Issue by skennedy1331** [Open-Shell/Open-Shell-Menu#908]
I have 3 monitors, the left monitor is in portrait while the center and right monitors are in landscape.
The center monitor is set as the main monitor and has the only taskbar.
The center's taskbar is set vertically on the left side of the screen and is set to autohide.
The issue I am having is when I press the Windows key on the keyboard the start menu appears off the main screen.
The taskbar pops open correctly but the start menu is displayed at the top of the left monitor and 99% of the menu is missing. 
All I see is 1/4 of a windows search bar, 1/4 shutdown button, and my account icon obscuring part of the shutdown button.
See attached screenshot. Now If I triple-tap the Windows key the start menu shows normally. Any thoughts on how to fix it?

Windows 10 21H2, I7-6700K,16GB-2133, GTX 980 Ti, EVO 850. Monitors: L=LG, C=Sam, R=HP; L, C, R = 1080p

![Screenshot (2)](https://user-images.githubusercontent.com/80284735/142570971-9a438953-918d-41ec-9772-7e53837e40f8.png)

**Comment by DerGuteWolf** [comment]
Hi @skennedy1331 , I have a similar setting and the same problem, although all 3 monitors are in landscape and the only taskbar is in the right of the center monitor, left and middle monitor are 1920x1080, right monitor is 1600x900, all at 100%, all monitors alligned at the top.
Do you have a solution already?

**Comment by burritosoftware** [comment]
I am having the same issue as well.

**Comment by skennedy1331** [comment]
@burritosoftware @DerGuteWolf Sorry to hear we all have the same problem. I have no solution except for moving all taskbars to the bottom of the screen. Hopefully, there can be a bug fix soon.

**Comment by collinsmith** [comment]
I have this issue as well.

**Comment by ge0rdi** [comment]
Could you, guys, create `Open-Shell` log using this [guide](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-obtain-advanced-Open-Shell-Menu-log)?
It should contain info about screen, taskbar and start menu position/dimensions. Maybe that will shed some light onto the issue.

Do you use some special software for multi-monitor setup?
Or just plain Windows?

**Comment by ge0rdi** [comment]
Thank you for the additional info.

I can see in log that there is something wrong:
`Main Rect: 0, 0, 0, 0`
This should be rectangle that spans whole screen where start menu is about to show.

Apparently, some issue with detecting what monitor we should display on, or something alike.
I guess I'd need to manage multi-monitor setup to be able to debug it somehow.

For now, maybe you can just disable taskbar hiding? So that it at least works.

**Comment by skennedy1331** [comment]
@ge0rdi 
[StartMenuLog.txt](https://github.com/Open-Shell/Open-Shell-Menu/files/10132458/StartMenuLog.txt)
Just like @collinsmith , I just use plain Windows and I have Fancy zones too. 
With the initial bad opening visible, if I quickly double-tap the windows key the start menu loads correctly.

**Comment by ge0rdi** [comment]
@skennedy1331 
Is the log file from case where `Open-Shell` start menu position was wrong?
Because I see nothing suspicious there.

Though as I wrote, this will require some debugging on multi-monitor setup (I'll try to get to that somehow, but no promises).

**Comment by skennedy1331** [comment]
@ge0rdi 
[StartMenuLog.txt](https://github.com/Open-Shell/Open-Shell-Menu/files/10133132/StartMenuLog.txt)
I erroneously uploaded a log where I double-tapped the Windows key after the menu opened in the wrong position.
This upload is when the menu opened in the wrong position.

**Comment by ge0rdi** [comment]
Oki, thanks.
This log is consistent with the one from @collinsmith.
So it will be the same issue with determining what monitor menu should be displayed on.

**Comment by ge0rdi** [comment]
I was able to replicate the issue using two monitors.
Prepared fix that will eventually get to official build.

In the meantime, I'd like to ask you guys to test with this [build](https://ci.appveyor.com/project/passionate-coder/open-shell-menu/builds/45549680/artifacts) to see if it's fixed for you as well.

Note that it is development build (and there are more changes included).
It should be safe to use, but better backup your settings before installing (in case if something goes wrong).

**Comment by collinsmith** [comment]
@ge0rdi Looks that that did the trick. Thank you!

**Comment by ge0rdi** [comment]
@collinsmith 
Perfect!

You can keep using the build.
Once the change will get to master, this issue will be closed automatically and there will be new official build available (should be 4.4.181).
Then please install the official one.

**Comment by skennedy1331** [comment]
@ge0rdi it worked for me as well, thanks a bunch.

**Comment by ge0rdi** [comment]
Hi guys.
We have official [4.4.181](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.181) build.
Please, install this one and enjoy :)

**Comment by collinsmith** [comment]
@ge0rdi just an fyi, it seems that the dev build is ahead of the newer pre-release build?
![image](https://user-images.githubusercontent.com/4914327/206024441-62c032ac-b2b3-4edc-be09-70c09db66aca.png)

**Comment by ruddnev** [comment]
Having the same problem with 21:9 main screen and a 16:9 secondary, running retrobar, main rect is 0, 0 (and menu is offscreen) when i have some window on the secondary screen and no windows and my mouse on the main screen. Only in those conditions. Changing 21:9 screen to 16:9 fixes it, having a window fixes it, having no windows anywhere fixes it
