### ISSUE TITLE
Fully Add Windows 11 support.

### ISSUE THREAD

**Issue by GitHubUser21359** [Open-Shell/Open-Shell-Menu#909]
I found my USB drive with my download and I currently have Windows 11. **CAN YOU ADD WINDOWS 11 FUNCTIONALITY?**

**Comment by dragonDScript** [comment]
As far as I know, Windows 11's toolbar is completely different. This will take some time. Please be polite, the contributors are working on this in their free time, for free.

**Comment by klepp0906** [comment]
yea, im sure the contributors are aware that theres no shortage of folks waiting for windows 11 support.

i know this is one of the key factors in my staying on 10 for now.

this and the inability to move the taskbar to another monitor.

the latter can be worked around using startisback (which id prefer not do but thus is life) however the former is in the hands of those much more versed in all things software. 

thats my long winded +1

**Comment by Ibuprophen** [comment]
Yes. It does work in Windows 11, but the known/reproducible issues & bugs is always a work in progress. 

Please keep in mind that the software is free with all our contributors/developers who are volunteers and tries our best to do what we can when we can get time to invest in the project. 

This is why we always encourage others (of course... who knows what they're doing) to help out with submitting changes for review. 

I tried my best to explain the above okay via text... :-) 


~ibuprophen

**Comment by ge0rdi** [comment]
The issue description is too vague.
For the future I'd recommend describing what exactly is not working for you or what you are missing (see other issues related to Windows 11 here).

There is work in progress on Windows 11 support.
I'm closing this now.
