### ISSUE TITLE
Line Appears on Primary Monitor When Opening Classic Skin Menu Menu from Secondary Monitor

### ISSUE THREAD

**Issue by 266-750Balloons** [Open-Shell/Open-Shell-Menu#910]
I have classic skin enabled on my start menu. When I open it from my right monitor , a tiny, 1-pixel wide line shows up on the very right of the left monitor. It seems that the skin is just 1 pixel too wide to the left. The strange thing is that the line only shows up after the animation has been played.

**To Reproduce**
1. Switch the skin to classic on any menu style.
2. Open a window in full-screen on the left monitor that provides high contrast, such as a window with a black background.
3. Open the menu on the monitor to the right.

**Expected behavior**
For best aesthetics, I would prefer that the line does not exist.

**Screenshots**
![image](https://user-images.githubusercontent.com/79549730/143311475-b62ef871-3eef-4ef2-92b3-fa7bdc9405cb.png)
If you're wondering about that Apple loading screen, that's just my Hackintosh VM in Virtualbox.

**Version:**
 - Open-Shell:  4.4.160
 - OS: Windows 10 20H2

**Additional context**
I believe it is not a software bug, but an actual mistake in the design of the skin, as the issue does not occur on any other skin.

**Comment by ge0rdi** [comment]
You can try to set `Menu Look` -> `Horizontal position offset` to `1`.
That way menu should be 1 pixel shifted to the right.
