### ISSUE TITLE
win 10 black screen with cursor

### ISSUE THREAD

**Issue by Blisk** [Open-Shell/Open-Shell-Menu#917]
**Describe the bug**
I spend almost 20 hours to find out why none of solutons for black screen with cursor in win 10 doesn't work. I tried all and more.
than I read some post that someone has the same problem and installed open-shell. After removing open-shell reboot and reinstall open-shell now it work again. I think it must be some update which cause that problem with open-shell.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**
 - Open-Shell: [] latest
 - OS: [e.g. Windows 10 ] fully updated

**Additional context**

**Comment by ocsnetworks** [comment]
I know have this same issue with OpenShell. However re-installing does not fix this issue.
I have installed the Pre-release 4.4.179 and issue still occurs.
I only install the "OpenShell" nothing else as well, no explorer or other features. Same result.

Removed all Windows updates in the last 10 days, which had no effect.


Had to remove OpenShell using these steps:
1. On the Black Screen, press CTRL+ALT+DELETE
2. Click Task Manager
3. Expand the task manager to see the menus.
4. File Menu, and select run
5. Type Control Panel
6. Go to Programs & Features
7. Find OpenShell & Uninstall.
8. Press CTRL+ALT+Delete and sign out.
9. Log back in.
