### ISSUE TITLE
Won't install with Classic Shell running

### ISSUE THREAD

**Issue by Dan-Essin** [Open-Shell/Open-Shell-Menu#918]
**Describe the bug**
Won't install with Classic Shell running. Says it wants to close explorer but can't

**To Reproduce**
1. run installer
2. Click on "OK to close listed apps (explorer"
3. See error

**Expected behavior**
installation should work
It works if CS is uninstalled.
OS installer shout check for CS and trigger uninstall if necessary

**Screenshots**

**Version:**
 - Open-Shell: [e.g. 4.4.169]
 - OS: [e.g. Windows 10 21H1]

**Additional context**

**Comment by maplez1** [comment]
Open Shell and Classic Shell are basically the same thing, so you should uninstall Classic Shell. Then it _should_ work. Because, what you are basically doing is installing the same program again.
