### ISSUE TITLE
 2nd column text padding issue

### ISSUE THREAD

**Issue by mckinnon42** [Open-Shell/Open-Shell-Menu#92]
I'm sorry if this is not an appropriate forum for discussing issues. I am not a developer, just a longtime user of Classic, now Open, Shell.

I have recently started seeing an issue on my laptop that is difficult to explain, so please bear with me.

I have a Windows 7 style start menu, configured with a cascading sub-menu. Along the left side of my menu, I have 'Recent Programs'. I have set the max recent programs to 11, which lines up perfectly with the right side of my menu (photo 01).
![photo 01](https://user-images.githubusercontent.com/44040737/46769364-ca92f200-cca8-11e8-903d-4f1602941c51.png)
My issue is that, for some reason, my start menu will stop lining up (photo 02).
![photo 02](https://user-images.githubusercontent.com/44040737/46769379-d1ba0000-cca8-11e8-9a1b-c4962e8587a4.png)
My solution has been to simply increase the number of 'Recent Programs' to 13, which makes everything line up again (photo 03).
![photo 03](https://user-images.githubusercontent.com/44040737/46769383-d7174a80-cca8-11e8-9e76-4df919ac4699.png)
The thing is, eventually, the problem will go away, which causes things to become misaligned but this time along the right side of my menu (photo 04).
![photo 04](https://user-images.githubusercontent.com/44040737/46769386-db436800-cca8-11e8-989a-8f70a7de244d.png)
I think the issue has something to do with spacing on the right side of the menu, as it seems there is a bigger gap between Start Menu items when the problem appears. I am not actively changing any settings, but maybe something I am doing is causing this shift?

Several caveats. My laptop is a Lenovo W520 (with both an integrated Intel HD 3000 graphics and a discrete nVidia Quadro 1000M graphics card) and I am running a dual monitor setup (my primary display is set to 1920x1080 @ 100% scale and my secondary display is set to 1680x1050 @ 100% scale). I am not sure if these would cause any issues, but I felt it important to mention them here regardless.

Additionally, I originally experienced this issue on a previous installation of Windows 10 running Classic Shell, where I took some of my screenshots. Unfortunately, I do not recall the exact version numbers of either Windows or Classic Shell, but I was having unrelated networking issues at the time and did a fresh install. I hoped the new install would also fix the Classic Shell issue, but it did not.

My current software is as follows:
Windows 10 v1803 build 17134.320
OpenShell v4.4.131
Intel graphics driver v9.17.10.4459 (dated 2016-05-19)
nVidia graphics driver v21.21.13.7755 (dated 2017-07-13)

If you can offer any assistance, I would be most appreciative.

Thank you!

**Comment by CTVCAM8** [comment]
Not a developer.

The shutdown button is taller and wider. 
Looks like something is changing shutdown text padding and 2nd column text padding.

My guess is something is triggering a touch-enabled setting or a bug.

**Comment by CTVCAM8** [comment]
Looking inside the Metro.skin7 instruction code, 
I see there is an option called [TOUCH_ENABLED AND NOT SMALL_ICONS].
This will increase the text padding height and arrow padding to the exact pixel dimensions in your screenshot picture.

This feature should only turn on if a touchscreen computer is detected.
Check your shell menu settings for some type of touch option.
If found, toggle setting off. 
If computer monitors have no touch screen feature, and no menu setting found,
I suspect a bug that enables that function with newer Windows 10 versions.

**Comment by CTVCAM8** [comment]
I don't see anything in the link that relates to mckinnon42 issue.
Perhaps the title 'Recent Programs changing size' could be renamed to something related to the 2nd column text padding issue, 
as that is the real problem. The recent programs area on the first column is just expanding because the 2nd column got taller from the increased invisible padding.

As a test, to confirm my hunch that this issue is to do with the touch feature,
I used Resource Hacker to open Metro.skin7 
forced the skin to use the below data

;[TOUCH_ENABLED AND NOT SMALL_ICONS]
Shutdown_text_padding=10,8,10,8,100%
Shutdown_arrow_padding=12,9,100%
Main2_text_padding=1,10,8,10,100%
Main_split_arrow_padding=14,14,100%

I customized menu (added extra entries, separators) to match mckinnon42.
It comes out exactly as mckinnon42 screenshot.
So either one of mckinnon42 monitors is touchscreen and turning on "Enable touch features" setting'
or it is a touchscreen detection bug. 

Only mckinnon42 has the answers.

**Comment by CTVCAM8** [comment]
Had a thought.
There is another solution for mckinnon42. Will not solve root of the problem, 
for it might be touch pad drivers on his laptop triggering touch feature in the shell menu.

If mckinnon42 only uses the Metro.skin7 menu skin, it is quite easy to modify skin with Resource Hacker,
to deactivate the touch feature from ever turning on.

Just put ";" in front of the five lines of code:

;[TOUCH_ENABLED AND NOT SMALL_ICONS]
;Shutdown_text_padding=10,8,10,8,100%
;Shutdown_arrow_padding=12,9,100%
;Main2_text_padding=1,10,8,10,100%
;Main_split_arrow_padding=14,14,100%

Save the file as Metro no touch.skin7
Put that skin file in the skins folder, exit, restart menu, select that skin file.

**Comment by mckinnon42** [comment]
My e-mail tagged these as SPAM messages, so apologies for not responding right away.

Thank you both for your replies.

As CTVCAM8 pointed out, I don't think ibuprophen1's link has any directly related information. It is very likely I am just missing the pertinent information. Regardless thank you for responding.

Regarding touch screen controls. I do not have a touch screen monitor, BUT I do have a touchpad that has some fancy features. I don't actually use the pad at all (It's a thinkpad, I use a mouse or the nubbin), so I have disabled it to see if this will fix the issue.

The issue seems to happen at least once throughout the day, so I hopefully can respond back either today or tomorrow as to whether the issue has been resolved. If disabling the touchpad doesn't fix it, I will try editing the skin.

**Comment by mckinnon42** [comment]
I can't say for sure, but editing the skin seems to have done the trick. I'm a bit hesitant to say anything with certainty, because I haven't used my laptop all that much these past few days, but the behaviour does seem to be gone. Thanks!
