### ISSUE TITLE
Menu opens halfway up my monitor unless a window is open

### ISSUE THREAD

**Issue by thelabcat** [Open-Shell/Open-Shell-Menu#926]
**Describe the bug**
If no windows are non-minimized, opening OpenShell menu has it appear halfway up my screen, high above the RetroBar taskbar. This is **not because of the taskbar size.**

**To Reproduce**

1. Run RetroBar
2. Close or minimize all windows
3. Click Start.

**Expected behavior**
OpenShell menu should always be only a bit above RetroBar and not only when windows are showing.

**Screenshots**

![Screenshot (1)](https://user-images.githubusercontent.com/53358500/145123515-87fda3f8-1d60-47de-9e86-00e093e1e16a.png)
![Screenshot (2)](https://user-images.githubusercontent.com/53358500/145123617-94a20b10-d5a7-4478-be61-b0d646bcec39.png)

**Version:**
 - Open-Shell: Latest
 - OS: Windows 11

**Additional context**
RetroBar was running [GitHub page](https://github.com/dremin/RetroBar)
MJD's tutorial was followed [MJD YouTube video](https://www.youtube.com/watch?v=j172icGBhRo)

**Comment by ge0rdi** [comment]
You may try with latest [4.4.181](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.181) build that added support for Windows 11.
