### ISSUE TITLE
shift-click with Windows 11

### ISSUE THREAD

**Issue by Coolmicro** [Open-Shell/Open-Shell-Menu#930]
Latest version
With Windows 11, shift + click has no effect: choice in the parameters that shift + Windows key and shift + left click gives access to Openshell

**Comment by ROBERT-MCDOWELL** [comment]
seems that openshell is not (yet) compatible with win11

**Comment by ge0rdi** [comment]
Fixed in [4.4.181](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.181).
