### ISSUE TITLE
Menu color does not change.

### ISSUE THREAD

**Issue by clickmario** [Open-Shell/Open-Shell-Menu#931]
I'm not able to change the menu color, with glass on or off.
I can check the box but the effect does not work.
The menu is always blue.

Menu settings...
Menu look tab
Override glass color

 - Open-Shell: 4.4.169
-  OS: Windows 10 21H2

Thank you

**Comment by bonzibudd** [comment]
See https://github.com/Open-Shell/Open-Shell-Menu/issues/162#issuecomment-483805878

The metro theme relies on the system accent color, so it can't be overridden with that option. You can try some of the other included skins, or you might want to try my skin [Fluent-Metro](https://github.com/bonzibudd/Fluent-Metro) which has more options to customize the color.

**Comment by clickmario** [comment]
Thank you for your answer.
