### ISSUE TITLE
Open-shell setup Error code: 2503 and 2502

### ISSUE THREAD

**Issue by OmarShadowSpike** [Open-Shell/Open-Shell-Menu#943]
**Description**
I was trying to install Open-shell and while it's installing it gave me 2 errors the codes was 2503 and 2502.

**To Reproduce**
1. Open Open-shell setup
2. Click Next
3. Accept to the Terms in the License Agreement
4. Click Next
5. Click Next again and leave everything default
6. Click Install

**Expected behavior**
Just install Open-shell in my PC

**Screenshots**
![ScreenShot_20220102152352](https://user-images.githubusercontent.com/65337921/147869170-b9a8ca7f-6c29-4b0a-8539-ec0ddc172a4d.png)
![ScreenShot_20220102152157](https://user-images.githubusercontent.com/65337921/147869171-c0d6bae9-ddd5-4e2c-9cbe-4e4ffbf35cea.png)

**Version:**
 - Open-Shell: **4.4.160**
 - OS: **Windows 8.1 Build 8900**

**Comment by OmarShadowSpike** [comment]
Wait never mind I tried to run it as an administrator and it works :/

**Comment by Ibuprophen** [comment]
I recall similar errors that were Windows OS related and the associated permissions to the temp folder. Windows Administrative permissions to this folder is typical as you may need to add administrative permissions to your user account (in some cases). 

Try what's outlined on the following link to help resolve this issue. 

https://winaero.com/fix-msi-installer-errors-2502-and-2503-in-windows-10-windows-8-1-and-windows-7/

Let's keep our fingers crossed! :-) 


~Ibuprophen
