### ISSUE TITLE
Open Shell for Windows 10 ARM via parrelles on M1

### ISSUE THREAD

**Issue by Jack451** [Open-Shell/Open-Shell-Menu#950]
**Is your feature request related to a problem? Please describe.**
Ive tried to run open shell on windows 10 and 11 ARM via parallels on a M1 mac and it crashes the OS. Would love to make my M1 mac look like windows xp!!!
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ylluminate** [comment]
We do need this badly for both 10 + 11.

**Comment by Jack451** [comment]
is it hard to do?

**Comment by ge0rdi** [comment]
ARM64 support was added in [4.4.196](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.196).
Please, use that one (or newer) on ARM64 devices.
