### ISSUE TITLE
Don't work on Windows 11

### ISSUE THREAD

**Issue by ComputerGod63** [Open-Shell/Open-Shell-Menu#954]
Hello,
i use Windows 11 and the Start button don't take effect on the taskbar.

**Version:**
 - Open-Shell: [e.g. 4.4.160]
 - OS: [e.g. Windows 11 21H2]

**Comment by MadDogDean** [comment]
I just installed it to test Classic Shell before using Win11 it on our production system, and this appears 1/2 true. 

If you click the Start button, you get the Windows 11 start menu, but if you press the Win key on the keyboard, Classic Shell pops up...

**Comment by VsevolodGolovanov** [comment]
It works if you revert to the Windows 10 taskbar: https://www.askvg.com/tip-restore-windows-10-classic-taskbar-in-windows-11-along-with-classic-start-menu/

**Comment by ge0rdi** [comment]
Fixed in [4.4.181](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.181).
