### ISSUE TITLE
Classic Explorer In Windows 11

### ISSUE THREAD

**Issue by bert07** [Open-Shell/Open-Shell-Menu#955]
**Describe the bug**
The Classic Explorer Bar does not work on the Windows 11 Explorer.
This seems to be due to the new Explorer Commandbar

**To Reproduce**
Just install OpenShell on Windows 11

**Expected behavior**
Showing the Classic Explorer Toolbar

**Screenshots**
Sorry, I fixed it here so I can not show you again, unless I enable the Commandbar again.

**Version:**
 - Open-Shell 4.4.169
 - OS: Windows 11 21H2

**Additional context**
To disable/enable the Win11 Explorer Commandbar, use an Administrative CMD and run:

- Disable:

reg add "HKCU\Software\Classes\CLSID\{d93ed569-3b3e-4bff-8355-3c44f6a52bb5}\InprocServer32" /f /ve

- Enable

reg delete "HKCU\Software\Classes\CLSID\{d93ed569-3b3e-4bff-8355-3c44f6a52bb5}\InprocServer32" /f /ve

**Comment by NukeThief** [comment]
open shell isnt yet fully supported with windows 11 thats why you have to do these steps

**Comment by ge0rdi** [comment]
`Classic Explorer` toolbar seems to be working on Windows 11 22H2+.

Not sure if there is still any issue on 22H1 (don't have it at the moment), but since 22H2 is widely available I guess there is no real need to stick to old Win11.
