### ISSUE TITLE
Windows Update kb5008212 breaks Open Shell

### ISSUE THREAD

**Issue by ZooperMaX** [Open-Shell/Open-Shell-Menu#956]
**Describe the bug**
Open Shell doesnt show in File Explorer any more

**To Reproduce**
Just install and watch

**Expected behavior**
I expect Open Shell to still show my icons in File Explorer

**Screenshots**
No screenshots since there is nothing to show since it doesnt show in File Explorer

**Version:**
 - Open-Shell: both Normal and latest beta ( 4.4.160 and beta 4.4.169 )
 - Windows 10 20H2 Build 19042.1415

**Additional context**
KB5008212 does the following : 
    Fixes issues with File Explorer’s folder view.
    Fixes a bug crashing apps after the update.
    Fixes font rendering issues on Windows 10.
    Fixes issues with Start Menu, including a bug where apps won’t appear on the menu.
    Fixes issues with the Windows Search process.

**Comment by ge0rdi** [comment]
See https://github.com/Open-Shell/Open-Shell-Menu/issues/275#issuecomment-567597531 .
