### ISSUE TITLE
What's currently stopping v4.4.169 to be the official release?

### ISSUE THREAD

**Issue by YamiYukiSenpai** [Open-Shell/Open-Shell-Menu#957]

**Comment by Pav-Osmolski** [comment]
This is not a bug. Please consider posting here instead https://github.com/Open-Shell/Open-Shell-Menu/discussions

**Comment by Ibuprophen** [comment]
I don't believe that "Jumping the Gun" (so to speak) regarding releases aren't a wise move since there's work on some other areas being worked on that may affect that specific version. 


~Ibuprophen
