### ISSUE TITLE
Openshell not working after upgrade from W10 to W11 on DELL XPS

### ISSUE THREAD

**Issue by JamesStuart999** [Open-Shell/Open-Shell-Menu#959]
Hi Guys. I am just a user of the software which has worked fine for many years.
Since I upgraded Openshell no longer gives me the W7 menu? Only the W11 menu?
Am I missing something??

**Comment by massimopetrini** [comment]
add the keys via registry

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell\Update\Packages]
"UndockingDisabled"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell\Update\Packages\BuiltIn]
"PackageFamilyName"="MicrosoftWindows.Client.CBS_cw5n1h2txyewy"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell\Update\Packages\Retail]
"PackageFamilyName"="MicrosoftWindows.Client_cw5n1h2txyewy"

and reboot; with 169 version run fine

**Comment by massimopetrini** [comment]
the only question is the name of version, remain still w10 and not w11....  as winver returns....

**Comment by YamiYukiSenpai** [comment]
If you click the Windows/Meta/Super key on your keyboard, does it show Open Shell?
If so, you can overlay a custom Start button on top of it.

**Comment by ge0rdi** [comment]
Fixed in [4.4.181](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.181).
