### ISSUE TITLE
Crash when selecting any of the Modern Settings

### ISSUE THREAD

**Issue by TheRealNox** [Open-Shell/Open-Shell-Menu#96]
![image](https://user-images.githubusercontent.com/1244091/47002082-4dde9880-d12c-11e8-81f3-055601ad98da.png)

If I try to click on any of the modern settings as shown above, I get the following error:

![image](https://user-images.githubusercontent.com/1244091/47002045-2e477000-d12c-11e8-8511-a35c0c517c22.png)

**Comment by ge0rdi** [comment]
This is not crash.
Something is just not working correctly,

Please, check latest nightly build (there is a link on main page).
We've added better support for Modern Settings.
