### ISSUE TITLE
name of windows installed on w11

### ISSUE THREAD

**Issue by massimopetrini** [Open-Shell/Open-Shell-Menu#960]
After install of w11 , the insert of the keys in the registry to return of the normal windows button, the install of 169 revision, still remain the win10 in left of then window as you can see.  Can somebody modify it ?

![image](https://user-images.githubusercontent.com/11225547/152116636-ef1cbb7d-b242-4a65-8e58-b26f6f98891e.png)

**Comment by bonzibudd** [comment]
See https://github.com/Open-Shell/Open-Shell-Menu/discussions/745 for more details on W11 stuff, there's still a lot that needs to be updated.
