### ISSUE TITLE
setup window is not closing - cant delete

### ISSUE THREAD

**Issue by aiden-creates** [Open-Shell/Open-Shell-Menu#961]
i go ahead and setup open shell, but change my mind and cancel it, but the window doesnt close

**To Reproduce**
set up open shell
cancel the setup
experience the pain of the window not closing 

**Expected behavior**
the window would close

**Comment by enochterror** [comment]
Even with such a well described "issue" , an outline of the steps to reproduce.....not a comment to close it. 

I have the same dilemma , hoping to see resolve.

**Comment by ge0rdi** [comment]
If you are still experiencing the issue, please provide information about `Open-Shell` version you are using, as well as Windows version and exacts steps to replicate the issue.

Feel free to reopen the issue then.
