### ISSUE TITLE
Custom Start Button icon no longer accepts custom sizes with 4.4.170

### ISSUE THREAD

**Issue by Pav-Osmolski** [Open-Shell/Open-Shell-Menu#962]
**Describe the bug**
Custom Start Button icon no longer accepts custom sizes with version 4.4.170. Instead, it is automatically forced to fit within the constraints of the Start bar itself.

**To Reproduce**
1. Go to 'Settings' > 'Start Button' tab
2. Specify a Custom button, change the Button image and set the size to something large like 150 or 200.
3. Notice how the image is only ever constrained to the bar.

**Expected behavior**
The icon should display at the intended size, even if this means that it should partially appears outside the constraints of the Start bar. Stylistically, it is subjective, but a forced constraint does not make sense if the user is allowed to specify a size.

**Screenshots**
Incorrect behaviour:
![Screenshot 2022-02-07 173457](https://user-images.githubusercontent.com/48226562/152890475-58f267b4-4f32-45cc-bf38-80e66644fb15.png)

Correct behaviour:
![Screenshot 2022-02-07 173927](https://user-images.githubusercontent.com/48226562/152890476-f14015ff-dda0-4b8f-8b07-547a4b0c7931.png)

**Version:**
 - Open-Shell: 4.4.170
 - OS: Windows 10 Pro 21H1

**Additional context**
The correct behaviour was last noticed with version 4.4.169.

Thanks.

**Comment by komawoyo** [comment]
Build 170??? You mean this change? : https://github.com/Open-Shell/Open-Shell-Menu/pull/946

That prevents overflow.

**Comment by Pav-Osmolski** [comment]
> Build 170??? You mean this change? : #946
> 
> That prevents overflow.

Yeah, that's not a bug fix. It's a feature change, and it's not a good one either for the sake of the Start Menu icon.

**Comment by ge0rdi** [comment]
The build you mentioned is not official one, but rather build from not-merged-yet pull-request.
Please, for the future discuss PR related changes directly in given PR.
