### ISSUE TITLE
Taskbar loses custom settings after opening search menu

### ISSUE THREAD

**Issue by BluishRed** [Open-Shell/Open-Shell-Menu#963]
Hi,

If I use the search feature from the taskbar, but then click off of the search, the taskbar will lose its transparency until I open the start menu.

**Comment by BluishRed** [comment]
Here's a gif of the bu
![OpenShellBug](https://user-images.githubusercontent.com/69787726/153194094-30ee975c-b7c3-429d-accd-e3c24471642d.gif)
g

**Comment by BluishRed** [comment]
After the most recent Windows 11 update, the taskbar will lose all custom taskbar effects if I just open the search menu

**Comment by LondoJI** [comment]
Have to add that after Apr.6, (date for Windows 11 Build 10.0.22593) effects over taskbar (say Gloss or Transparency), stopped to work.

**Comment by ge0rdi** [comment]
Fixed in [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build.
