### ISSUE TITLE
Black Screen @ Windows 11 on ARM (Run on Parallels)

### ISSUE THREAD

**Issue by Paw2Pom** [Open-Shell/Open-Shell-Menu#966]
**Describe the bug**
After install OpenShell and restart the Windows, when reboot, windows become all black screen with no response to any keyboard command. Basically dead machine. The following release versions have been tried and all have black screen issue:
4_4_169
4_4_160
4_4_142
No versions tested so far can make it work.

**To Reproduce**
1. Install OpenSell
2. Restart Windows after install.
3. Black Screen

**Expected behavior**
Windows can reboot correctly with OpenShell installed.

**Screenshots**
Just a very black screen.

**Version:**
OpenShell: 4_4_169, 4_4_160, 4_4_142
Windows 11 On ARM (Runs on Parallels) Build 22543.rs_prerelease.220122-2315

**Comment by Ibuprophen** [comment]
First a bit of background... 

Windows on ARM: Windows on an ARM system uses a system called CHPE Files (Compiled Hybrid Portable Executable Files). This is something that's specially compiled coding for ARM devices. 

Windows on ARM64: Windows on an ARM64 system still uses a system called CHPE Files (Compiled Hybrid Portable Executable Files), but it's technically an ARM64EC (Emulation Compatible). This is both backwards compatibility to ARM and the additional Emulation Compatibility for software to run within an Emulation Environment that's not specifically developed for Android Specific Architecture/Hardware. 

With that stated... 

The Open Shell software is not developed under this environment without the assistance of an Emulator. 

This ability would require allot of work in creating a new repository branch and a complete revamp in a different Coding Language.

I tried to explain the above the best way I can via text... 

I'm going to close this and am sorry for the bad news. 


~Ibuprophen

**Comment by Caumaker** [comment]
Same here.. thanks explanation

**Comment by Caumaker** [comment]
how to revert it? I unistalled it. but not worked.. keep black screen

**Comment by ge0rdi** [comment]
ARM64 support was added in [4.4.196](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.196).
Please, use that one (or newer) on ARM64 devices.
