### ISSUE TITLE
All programs in two sections

### ISSUE THREAD

**Issue by perdrix52** [Open-Shell/Open-Shell-Menu#969]
### Discussed in https://github.com/Open-Shell/Open-Shell-Menu/discussions/968

<div type='discussions-op-text'>

<sup>Originally posted by **perdrix52** February 13, 2022</sup>
When I click on All Programs the list of folders and applications is opened with quite a few programs at the top, then a set of folders then the Apps and then another set of Folders 

![image](https://user-images.githubusercontent.com/20211762/153766169-010be8a5-9984-4b95-8ef8-4b80f926bf65.png)

I expected the second set of folders to be sorted in with the others - why aren't they?

D.</div>

**Comment by Ibuprophen** [comment]
Try right clicking any of those listed and there should be sorting options to choose towards the bottom of that menu. 


~Ibuprophen

**Comment by perdrix52** [comment]
OK - but there's a configuration setting (which I have set) that's supposed to do that ...

**Comment by Ibuprophen** [comment]
I can't remember the option in the settings for this specific action, but I had never really done it any other way besides that as it had done the job. 

Did that take care of/answer your question? 


~Ibuprophen

**Comment by drtaft** [comment]
Unfortunately, I have the exact same problem... the icons are not sorting...

![1](https://user-images.githubusercontent.com/13759277/155054847-587ce13b-5ce7-4377-8a58-bde83f86780b.PNG)
![2](https://user-images.githubusercontent.com/13759277/155054881-14f2d93b-52a0-4926-811f-48cb911f367f.PNG)
 
Could this be a new bug?

Thanks!

**Comment by bonzibudd** [comment]
Right-click in the programs section and select “Auto Arrange.” This should fully sort the menu.

If that doesn’t work, it may be an issue between the common folder and the user folder.

**Comment by bonzibudd** [comment]
@perdrix52 does my above comment solve the issue?

**Comment by perdrix52** [comment]
Yes that worked, sorry for not providing feedback
