### ISSUE TITLE
Start Menu - Recently run Programs Not Shown in the List

### ISSUE THREAD

**Issue by GCoves81** [Open-Shell/Open-Shell-Menu#970]
Hello All,

First, congrats for continuing to support this great App!

I'm facing a problem with the recent programs list in Open-Shell-Menu. It does not display the programs I run, just the "Start Menu (Windows)" entry and the "Settings" app. Here is a pic.
![Here](https://user-images.githubusercontent.com/55602999/154164866-cd51a5bd-27b7-4165-967d-25d983b38e4f.jpg)

The problem appeared while still using the (old) Classic Shell app - I knew it was no longer in development. But found Open Shell and installed it (uninstalled Classic Shell first). The same issue keeps affecting Open Shell as well.

Searched a little, found DataCache.db and ModernSettings.dat under C:\Users\UserName\AppData\Local\OpenShell, closed StartMenu, moved them out and restarted StartMenu, hoping that re-creating the db could fix the problem, but it didn't. So moved them back in their place.

First, i would to ask where are the items to be shown in the list stored at. Maybe there is some erroneous or ill-behaving item there that causes the list population or enumeration to fail.

If the above doesn't help either, the app must be traced/debugged. Of course it makes no sense to ask for... personalized support for such an app. And I guess it would even be inefficient to send/receive special debug versions and log or trace files. Therefore I would be willing to debug it on my computer. I will need some help though, could someone point out the code where the list is populated or read? Also how and when it is updated? I will of course report back my findings.

Thank you in advance

**Comment by UncleScrooge85** [comment]
Windows 10 settings --> Privacy
In the general tab, make sure to enable "Let Windows track app launches to improve Start and search results"

**Comment by ge0rdi** [comment]
Have a look at #149.
