### ISSUE TITLE
Does this work when Windows is booted to Safe Mode?

### ISSUE THREAD

**Issue by e-t-l** [Open-Shell/Open-Shell-Menu#973]
Specifically, does Open-Shell augment the native Windows start menu, or does it disable and replace it as a 3rd-party app? If it's the latter, is it an extra process that runs in the background? Would it work if Windows were booted into Safe Mode? (and if not, how _would_ you access the start menu etc. if you need to boot into Safe Mode?)

**Comment by ReubenDollmanYT** [comment]
No windows only loads the required programs when booted into safe mode

you would need to use the windows start menu or manually start open shell
