### ISSUE TITLE
Unknown icons on right side when small

### ISSUE THREAD

**Issue by toiletflusher** [Open-Shell/Open-Shell-Menu#980]
**Describe the bug**
There are a ton of unknown icons on the right side, when the skin makes them small for just the right side.

Go to the screenshots to see this bug.

**To Reproduce**
1. Use the skin below
2. Go to Open-Shell settings
3. Apply it
4. Turn on small icons

**Expected behavior**
The icons should appear as it should, like in Classic Shell 4.3.0. (see screenshots)

**Screenshots**
Unknown icons
![image](https://user-images.githubusercontent.com/80153347/156925941-526ca466-0d0d-43c7-a942-37119cd32549.png)
Expected behavior
![image](https://user-images.githubusercontent.com/80153347/156926107-467b8bde-1de8-4481-bfbe-e0191c588803.png)

**Version:**
 - Open-Shell: 4.4.169
 - OS: Windows 10 1607 (LTSB 2016)

**Skin: **
[Windows XP Classic.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/8192702/Windows.XP.Classic.zip)

**Comment by bonzibudd** [comment]
Related to https://github.com/Open-Shell/Open-Shell-Menu/issues/561

**Comment by blackcrack** [comment]
https://github.com/Open-Shell/Open-Shell-Menu/issues/561
