### ISSUE TITLE
Fixed Start Menu entries steal focus from program shortcuts

### ISSUE THREAD

**Issue by ackern** [Open-Shell/Open-Shell-Menu#984]
**Describe the bug**
This behavior is completely different from Classic Shell. In Start Menu the standard entries for Programs, Settings, Search, etc. have stolen the shortcut keys p, s, c, etc. so if you add your own program shortcuts and they start with any of those letters, you can't get to them by typing the letter. In other words if you have Chrome in the Start Menu you can't open it by typing <c> because <c> only goes to Search. In Classic Start Menu you could have as many programs starting with C as you want and typing <c> would go through all of them in sequence.

The full list of letters "stolen" by the standard entries is:

p, s, c, h, r, l, u, for Programs, Settings, Search, Help, Run, Log Off, Shut Down

For programs that don't start with those letters there's no problem and you can open them by typing the first letter.

**To Reproduce**
1. Drag any program whose name begins with p, s, c, h, r, l, or u to start menu, for example Chrome.
2. Type first letter of program, for example <c>. In this example, focus will not go to Chrome but only to Search.

**Expected behavior**
Typing first letter of program in start menu takes you to that program

**Version:**
4.4.160
Win 8.1

``
![x2scrap](https://user-images.githubusercontent.com/8440262/158037764-a744f696-2846-4853-8196-108e8058fc14.png)

**Comment by ackern** [comment]
Don't know if this is useful information I just saw in the notes I kept on earlier versions that this (navigate by typing first letter of program) was working in Classic Shell 4.1.0 and was broken in Classic Shell 4.3.1. I don't know about the versions in between.

**Comment by bonzibudd** [comment]
This behavior can be changed under "Main Menu" settings:

![image](https://user-images.githubusercontent.com/61938331/209513493-797e3246-b843-4fa9-9cd4-2f760fe19b0c.png)

In this case, the option you want to use is "Normal shortcuts." By default, it uses the num keys as shortcuts.
