### ISSUE TITLE
Versioning inconsistent, can't now install 4.4.161

### ISSUE THREAD

**Issue by VulcanTourist** [Open-Shell/Open-Shell-Menu#988]
**Describe the bug**
I cannot now install the newest version 4.4.161, because the previous version released 9 months earlier has a *later* version number 4.4.169 and now prevents the downgrade.

**To Reproduce**
1. Have 4.4.169 already installed;
2. try to install 4.4.169;
3. installation error: "A newer version of Open-Shell is already installed. The setup will now exit."

**Expected behavior**
Versioning should be consistently progressive with each new release.

**Version:**
 - Open-Shell: 4.4.169
 - OS: Windows 11 64-bit, build 22000.556

What do I do now?  Will first uninstalling 4.4.169 and then installing 4.4.161 preserve existing configuration?

**Comment by Ibuprophen** [comment]
My apologies. Please disregard that one. 

I removed that release as I'm a bit rusty with releasing. 

When I get more time, I'll try to get a pre-release out. 


~Ibuprophen

**Comment by VulcanTourist** [comment]
Thank you for the explanation.  You wouldn't recommend uninstalling 4.4.169 and then installing 4.4.161?  (I still have the download.)  If not, I can wait; I was looking forward to seeing how the new changes might be beneficial.

**Comment by Ibuprophen** [comment]
If it's working, I wouldn't worry about it.

When another release is out , you shouldn't have an issue installing it as an update. 

That last one was only a beta/pre-release. 


~Ibuprophen
