### ISSUE TITLE
Windows ARM64 support 

### ISSUE THREAD

**Issue by holaimscott** [Open-Shell/Open-Shell-Menu#990]
Great project :) It would be amazing if you could consider making this also in an ARM64 native support, since it would be nice to add to my ARM PC device without having to emulate it via emu layer.

With the rise of ARM devices, this would definitely be a fun tool to have for newer devices to have this useful too.

**Comment by Ibuprophen** [comment]
First a bit of background... 

Windows on ARM: Windows on an ARM system uses a system called CHPE Files (Compiled Hybrid Portable Executable Files). This is something that's specially compiled coding for ARM devices. 

Windows on ARM64: Windows on an ARM64 system still uses a system called CHPE Files (Compiled Hybrid Portable Executable Files), but it's technically an ARM64EC (Emulation Compatible). This is both backwards compatibility to ARM and the additional Emulation Compatibility for software to run within an Emulation Environment that's not specifically developed for Android Specific Architecture/Hardware. 

With that stated... 

The Open Shell software is not developed under this environment without the assistance of an Emulator. 

This ability would require allot of work in creating a new repository branch and a complete revamp in a different Coding Language.

I tried to explain the above the best way I can via text... 

I'm going to close this and am sorry for the bad news. 


~Ibuprophen

**Comment by holaimscott** [comment]
No worries, I appreciate the explanation, and thanks!

**Comment by ge0rdi** [comment]
ARM64 support was added in [4.4.196](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.196).
Please, use that one (or newer) on ARM64 devices.
