### ISSUE TITLE
Black screen when login

### ISSUE THREAD

**Issue by Blisk** [Open-Shell/Open-Shell-Menu#991]
**Describe the bug**
I have about 70 computers with win10 fully updated and one by one get problem with black screen and only cursor visible. 
And nothing happend. Even when computer is restart or reset when login I get black screen with cursor.

**To Reproduce**
Login

**Expected behavior**
to get my desktop with icons

**Screenshots**
black screen with cursor

**Version:**
 - Open-Shell: [e.g. 4.4.160]
 - OS: [e.g. Windows 10 1903]

**Additional context**

**Comment by blackcrack** [comment]
70 Computers ?
Then you be a Administrator and enough experience to give a more exactly error description
with more System details, you have to help with and not easy puke on a support 
call or did you buy anytime at contract of Support ?

This is a Open Source Software with a Free Community ! You have to help with my friend..

best

.. I would like to say other things, but I hold back! (holy... )

**Comment by Blisk** [comment]
What more I can say. There is no error. Simply when you login you get black screen with cursor and nothing else. When I check event log nothing usefull. All computers are updated to last update, all computers have the same setup of win10 and apps. 
You can restart it but it is the same. It works only when I uninstall open-shell remotelly, what I did now for all users because every day more users have the same problem. It works if I unistall open-shell and install it again, for some time.

**Comment by Ibuprophen** [comment]
I'm curious @Blisk if you try and see if the Explorer Patcher fix explained by @tallman69 on https://github.com/Open-Shell/Open-Shell-Menu/discussions/987#discussioncomment-2359387 provides any positive results for you. 

Fingers Crossed... 👍 

~Ibuprophen

**Comment by blackcrack** [comment]
@Ibuprophen .. hey Ibu, updated, not upgraded *bg* because he did not say'ed he have 11 .. "updates" only..

```
Ibu, how do you recognize that you have a good admin in front of you ?
he talks about details, up to the speck of dust corners of the Serverroom.. ;) ! 
```

**Comment by Blisk** [comment]
> @Ibuprophen .. hey Ibu, updated, not upgraded *bg* because he did not say'ed he have 11 .. "updates" only..
> 
> ```
> Ibu, how do you recognize that you have a good admin in front of you ?
> he talks about details, up to the speck of dust corners of the Serverroom.. ;) ! 
> ```

Exactly. Windows 10 are fully updated. And none have win11. I will not install win11 for another 2 years until first SP1.
and for now I will remove open-shell because it makes too much trouble. I will see in future if that black screen problem will be gone than I will install it again.

**Comment by Ibuprophen** [comment]
@blackcrack got it My Friend... 👍 

@Blisk, it was just a thought as that suggestion was an issue that began in Windows 10 that carried over to Windows 11,but I digress. 

I personally never experienced this behavior (nor do I recall anyone mentioning this behavior as well) as It appears that there's more to this situation as a whole. 

I believe that this may not specifically be the Software itself, but rather something kina reacted/panicked (software or possibly even hardware related) to this specific software. 

Personally, It seems like one of those "I have to personally see the system" situations. 

I'll definitely try keep a personal note of this in case I encounter someone else here having this same specific issue. 

I'll close this issue with my deepest apologies in what your experiencing... :-(( 


~Ibuprophen

**Comment by Blisk** [comment]
No problem. But yes I see some others have the same problem, when I googled it about black screen.

**Comment by tallman69** [comment]
@Blisk, Have you tried running the 4.4.169 beta version of Open-Shell?  I have not tried it on my Windows 10 laptop, but I have been running it without issue on my Windows 11 laptop.
