### ISSUE TITLE
Open Shell No Start Menu Effect.

### ISSUE THREAD

**Issue by NickDeBeenAIE** [Open-Shell/Open-Shell-Menu#994]
Start Menu is still the same as it was with Windows 11.

Reproduce by opening Open Shell Menu Settings.

Then click on the Classic Style.

Nothing happens, it just closes with no effect on the start menu.

![unknown_2022 03 26-13 33](https://user-images.githubusercontent.com/60248725/160222485-854c7953-48da-4c96-8d40-4822f02b049a.png)

**Comment by namiltd** [comment]
Look at: https://www.askvg.com/tip-restore-windows-10-classic-taskbar-in-windows-11-along-with-classic-start-menu/

**Comment by NickDeBeenAIE** [comment]
Another problem is, when you click on start (yes, I have When I click Start, it opens enabled), Start doesn't open when it is clicked.

**Comment by NickDeBeenAIE** [comment]
OpenShell, along with EVERY other shell customizing program f***s with the registry, and kills an operating system.

I switched to Linux for 5 days to prove this, because my Windows 11 install s*** itself as of way too much customization.

**Comment by ge0rdi** [comment]
Fixed in [4.4.181](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.181).
