### ISSUE TITLE
Classic Menu on Win 11 still says Windows 10 Home

### ISSUE THREAD

**Issue by FrankConijn** [Open-Shell/Open-Shell-Menu#996]
See the screenshot. Installation went fine and it works alright, but even though it's installed on Win 11, the Classic Start menu still says Windows 10 Home. Open-Shell version: 4.4.169. 

![Classic Shell Win 11 - screenshot Start menu](https://user-images.githubusercontent.com/12108138/160366766-7a16bd3e-50b7-476a-bcbe-757cdb7ae63b.png)

**Comment by YesTrustMe** [comment]
Other than the name issue, how's the application working otherwise? I read not long ago users have many issues with W11.

**Comment by FrankConijn** [comment]
Otherwise it works fine. Didn't encounter any problems on two Win 11 machines.

**Comment by Ibuprophen** [comment]
I didn't realize this... Hmm... 

~Ibuprophen

**Comment by blackcrack** [comment]
hmm.. Win11 is not compatible to Open Shell.. well, kick the Win11 in the trash or Win11 must be bugfixed and patched  :stuck_out_tongue_winking_eye: :joy: :feelsgood:

**Comment by Ibuprophen** [comment]
@blackcrack It seems as though that, by the time we got it fully compatible with Windows 11, Windows 21 will be released... LOL! 👍 

~Ibuprophen

**Comment by maplez1** [comment]
Im pretty sure the reason why it says Windows 10 is because Microsoft didnt bother to change the text in the registry which says what version of Windows you have. So you could change the text, but im not sure if that actually is the problem.

**Comment by ge0rdi** [comment]
Here is a workaround (until it gets fixed):
https://github.com/Open-Shell/Open-Shell-Menu/discussions/1063#discussioncomment-4010418

**Comment by ge0rdi** [comment]
Fixed in [4.4.181](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.181).
