### ISSUE TITLE
How to disable shortcuts in the menu?

### ISSUE THREAD

**Issue by q1k** [Open-Shell/Open-Shell-Menu#998]
So, I was looking for Audacity and the computer was SHUT DOWN!

I'm using the windows 7 style if that makes any difference.

**Expected behavior**
to focus on the search box and not shutdown ffs

**Comment by ge0rdi** [comment]
Search should be now properly focused when start menu is opened in [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build.

Additionally, it is now possible to configure accelerators to trigger only when Alt is pressed (`Require Alt key for accelerators` setting) or disable keyboard accelerators completely (`Enable accelerators` setting).

**Comment by q1k** [comment]
Well, here's where this differs a lot from the Windows 7 search. 
Windows 7 would autofocus on the search box when you start typing. The current OpenShell implementation doesn't.
Click all programs and go back, now start typing and it doesn't focus on the search, whereas win7 would be searching.

**Comment by ge0rdi** [comment]
I plan to do some improvements regarding search focus in the future.
